main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildEvaluationContext.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
Project GUIDs and MSBuild properties should be checked with ordinal ignore case.
=> [Core] Swap 2 hashsets to use ordinal ignore case.

main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/AnalyzeWholeSolutionHandler.cs
Previously, when no issue was raised by the analyzers we still opened the error pad.
It's clearer to not open the error pad and report success like we do when building so people know that something happened, success, there are no issues.
=> [Refactoring] Report success when analyzers found no issues

main/src/addins/MonoDevelop.DotNetCore/Properties/MonoDevelop.DotNetCore.addin.xml
With Mono's MSBuild having the .NET Core SDK files, but the .NET
Core runtime or SDK not being installed separately, the .NET Core
category was displayed and it contained the .NET Standard library
project template. Whilst this project can be compiled it is
confusing that it is displayed in the .NET Core category when the
.NET Core sdk or runtime has not been installed.
The .NET Standard Library project template is now no longer displayed
in the .NET Core category if .NET Core is not installed separately.
This then prevents the .NET Core category from being displayed.
The .NET Standard Library project is still available in the
Multiplatform - Library category.
=> [DotNetCore] Do not show .NET Core category if runtime not installed

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/IndentationTracker.cs
That turns off smart backspace - this is only useful for some
programming languages like c#, vb - but not for web, xml, text etc.
=> Fixed 'Bug 56006 - Backspace deleting too far'

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CSharpCompletionTextEditorExtension.cs, main/src/addins/CSharpBinding/MonoDevelop.CSharp.Features/Completion/CompletionEngine.cs, main/src/addins/CSharpBinding/MonoDevelop.CSharp.Features/Completion/ContextHandler/SpeculativeNameContextHandler.cs, main/src/addins/CSharpBinding/MonoDevelop.CSharp.Features/Completion/ContextHandler/XmlDocCommentContextHandler.cs
comments'
Backspace now has a special trigger info but was filered out in the
backend - the trigger info was introduced later. The xml doc
completion now takes that trigger info into account when suggesting
items.
=> Fixed 'Bug 55970 - Backspace shows no code completion items in

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/KeyBindingService.cs
This avoids a first-chance exception on startup when we try to read from a file that doesn't exist.
=> Check if keybinding file exists before opening it

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Features/ParameterHinting/ParameterHintingEngine.cs
This change fixes parameter hinting so that it works similar to how Roslyn handles it. This will do for now, until we switch to roslyn's ISignatureHelpProvider
Best viewed side-by-side, as nothing of the old code remains, uses the same mechanism as here: http://source.roslyn.io/#Microsoft.CodeAnalysis.CSharp.Features/SignatureHelp/InvocationExpressionSignatureHelpProvider.cs,54
=> [C#] Optimize parameter hinting handling.

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Navigation/DocumentNavigationPoint.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Navigation/TextFileNavigationPoint.cs
close.
Versions become invalid after closing the document & leak documents in
memory.
=> [Ide] TextFileNavigation points remove text source version on document

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests.csproj, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreVersionTests.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.csproj, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreRuntimeVersions.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreVersion.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/MSBuildProjectExtensions.cs
If the latest version of the .NET Core runtime installed is a 2.0
pre-release then the default Microsoft.NETCore.App version, which
will be 2.0, is modified before it is written to the
project.assets.json file so it is the pre-release version. This allows
the NuGet restore to work.
=> [d15-3-preview][DotNetCore] Allow .NET Core 2.0 pre-release projects to restore 

main/src/addins/MacPlatform/MacPlatform.cs
When Full Keyboard Access is enabled, turn on the focus ring for checkbuttons and radiobuttons
Fixes BXC #53829 and 45 duplicates :)
=> [A11y] Turn on focus ring for checkbuttons and radiobuttons

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/DefaultMSBuildEngine.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildEvaluationContext.cs, main/tests/UnitTests/MonoDevelop.Projects/MSBuildTests.cs, main/tests/test-projects/project-with-wildcard-links/PortableTest/PortableTest.csproj
Item metadata was not correctly evaluated since the item context was not
always set when evaluating an item.
=> [MSBuild] Fix item metadata evaluation issue

main/src/addins/AspNet/Properties/MonoDevelop.AspNet.addin.xml
StylesheetTemplate.css and the RazorTagHelper.xft.xml file imports
had the wrong case.
=> [AspNet] Fix case on imported files

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Ide.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/RootWorkspace.cs
When opening files either at startup or as a result of an OS request
wait for solution loading operations to end before opening the files.
This will ensure that files opened as the result of solution status
restoration won't steal the focus to the files being explicitly loaded.
=> Fix bug #55994 - File open ordering issue after solution load

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/FileTemplate.cs
It happens when an add-in is disabled during the build and the NREX
prevents the solution-level "Add new file" dialog from showing up.
=> Don't throw NREX when a template is unavailable.

main/src/addins/MonoDevelop.Packaging/MonoDevelop.Packaging.Tests/MonoDevelop.Packaging.Tests/AddPlatformImplementationTests.cs, main/src/addins/MonoDevelop.Packaging/MonoDevelop.Packaging.Tests/MonoDevelop.Packaging.Tests/ProjectTemplateTests.cs
Some tests fail on Linux because there's no MonoDroid or XamarinIOS
solution item there:
`MonoDevelop.Projects.MSBuild.UnknownSolutionItemTypeException : Unknown solution item type: XamarinIOS`
=> [Packaging] Exclude tests on Linux which don't work there

main/src/addins/CSharpBinding/MonoDevelop.CSharp/PathedDocumentTextEditorExtension.cs
window'
This version makes the path comparer more robust in case of future
language changes as well.
=> Fixed 'Bug 55904 - Method or Field navigation on the source code

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/EventCreationCompletionData.cs
generate method stub'
Broke during roslyn 2 port.
=> Fixed 'Bug 56257 - FooButton_Clicked handler completion does not

main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/ComparisonWidget.cs, main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/EditorCompareWidgetBase.cs, main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/MergeWidget.cs
When setting the local text, the text setter would end up formatting the tabs to spaces due to how the policy was set. Disable that setting.
=> [VCS] Don't set tabs to spaces due to default policy in the diff editor.

main/src/core/MonoDevelop.Ide/gtkrc.mac, main/src/core/MonoDevelop.Ide/gtkrc.mac-dark
Turn on interior focus for check/radio buttons so the focus gets drawn less squashed
To draw this nicely needs changes in both gtk and the xamarin-gtk-theme and I don't have time to do that now, so we'll leave it like this for now.
=> [A11y] Improve the way check/radio buttons are focus highlighted

main/src/addins/CSharpBinding/MonoDevelop.CSharp.ClassOutline/CSharpOutlineTextEditorExtension.cs
=> Fixed 'Bug 56425 - Clicking nodes in Document Outline don't navigate

main/src/addins/VBNetBinding/MonoDevelop.VBNet/VBNetTextEditorExtension.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/RoslynClassificationHighlighting.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
Extracted roslyn classification highlighting so it can be re used for
c# bypassing the slow textmate highlighter in future versions.
=> Fixed 'Bug 55915 - Editor doesn't render the full text'

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/RoslynSymbolCompletionData.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/CompletionData.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/ListWidget.cs
Instead of having a DataItemComparer externally to CompletionData, have a CompletionData.Comparer singleton and use that.
Make sure all logic is concentrated in one place and does comparisons one step at a time.
The whitespace changes are the result of unifying the entire file to use LF consistently.
=> Make CompletionData comparer stable.

main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/ComparisonWidget.cs, main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/EditorCompareWidgetBase.cs, main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/MergeWidget.cs
When setting the local text, the text setter would end up formatting the tabs to spaces due to how the policy was set. Disable that setting.
=> [D15.2][VCS] Don't set tabs to spaces due to default policy in the diff editor.

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.Helpers/TestablePackageReferenceNuGetProject.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.csproj, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/PackageReferenceNuGetProjectTests.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/PackageSpecCreatorTests.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.csproj, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/MonoDevelopNuGetProjectFactory.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageReferenceNuGetProject.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageSpecCreator.cs
Non .NET Core Sdk style projects that use PackageReference in their
MSBuild project file are now supported. Previously the Solution
window would not show any packages for the project, would not allow
restoring, and would install new NuGet packages using a packages.config
file. Now if the project has a PackageReference the Packages folder
shows the installed packages and can be used to update or install
NuGet packages which will also create PackageReference MSBuild items.
If the project has no PackageReferences then by default a
packages.config file will be created. There is no UI option to opt-in
to using PackageReferences currently so the project file will need
to be edited to include at least one PackageReference before the
default behaviour of using a packages.config file is …
=> [NuGet] Support non .NET Core projects using PackageReference

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/GenericProject.cs
Fixed bug #55783 - XS crashes when adding new project
https://bugzilla.xamarin.com/show_bug.cgi?id=55783
When adding a new generic project to an existing solution using the
New Project dialog an error dialog would be displayed saying that the
project does not have a file name and the save failed. The problem
was that the TemplateInitializationCallback was not called when
the GenericProject was initialized from the template so the filename
was not being set.
=> [Core] Fix error when adding new generic project to solution

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/GenericProject.cs
On trying to open the project options dialog for a generic project
a null reference exception was thrown by the RunConfigurationPanel
since it could not find an run configuration editor for generic
projects. To avoid this the generic project now indicates it does
not support run configurations so the project options dialog can
be opened.
=> [Core] Fix project options cannot be opened for generic projects

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Highlighting/HighlightUsagesExtension.cs, main/src/addins/CSharpBinding/MonoDevelop.CSharp.Refactoring/CSharpFindReferencesProvider.cs
implementations'
This is just a bandaid fix. The infrastructure seems to be implemented
in EditorFeatures. It's not reasonable that this isn't part of the
SymbolFinder core features. This implementaiton fixes the problem, but
once EditorFeatures is accessible for us we should just switch to
their find reference service.
=> Fixed 'Bug 56687 - Find references of method doesnt account for

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/ParameterInformationWindow.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/ParameterInformationWindowManager.cs
disruptive'.
Basically that bug was caused by the async nature of updating the
parameter info window. The window size may update after the
PositionParameterInfoWindow call so it operates on invalid values.
However it's more natural to 'correct' the x/y position after the
resizing so the location correction algorithm got splitted up. Seems
to fix the issue for me.
=> Fixed 'Bug 55735 - Intellisense popups are layered, intrusive, and

main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/SystemAssemblyService.cs
Fixes bug# 56086 - XS not resolving types with visible compilation errors,
but builds without problem
=> Fix assembly resolution issue

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.SharedAssetsProjects/SharedAssetsProject.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.SharedAssetsProjects/SharedAssetsProjectMSBuildExtension.cs, main/tests/UnitTests/MonoDevelop.Projects/SharedAssetsProjectTests.cs, main/tests/test-projects/DotNetCoreSharedProjectTest/DotNetCore/DotNetCoreProject.csproj, main/tests/test-projects/DotNetCoreSharedProjectTest/DotNetCore/Program.cs, main/tests/test-projects/DotNetCoreSharedProjectTest/DotNetCoreSharedProjectTest.sln, main/tests/test-projects/DotNetCoreSharedProjectTest/Shared/MyClass.cs, main/tests/test-projects/DotNetCoreSharedProjectTest/Shared/Shared.projitems, main/tests/test-projects/DotNetCoreSharedProjectTest/Shared/Shared.shproj
Two fixes for shared projects:
56144 - NetCore Projects show the files from a referenced Shared Project
56147 - NRE restoring Shared Project in a NetCore app
Also removed some code calling Project.LoadProjectItems SharedAssetsProjectMSBuildExtension since it never seemed to add any files since the MSBuildProject loaded was not evaluated. The files are added later by other sections of code. The LoadProjectItems was being called during re-evaluation and clearing the Project.Files collection for the project referencing the shared project.
=> [DotNetCore] Fix shared project re-evaluation and shared files displayed in Solution pad

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/MonoExecutionParameters.cs
Fixes bug #56699 - Mono Runtime Settings: need option to control arch
=> [Core] Added architecture to mono execution options

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProject.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProjectInstance.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/RemoteProjectBuilder.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs, main/tests/UnitTests/MonoDevelop.Projects/MSBuildTests.cs, main/tests/test-projects/DotNetCoreMultiTargetFramework/DotNetCoreMultiTargetFramework.sln, main/tests/test-projects/DotNetCoreMultiTargetFramework/DotNetCoreMultiTargetFramework/Class1.cs, main/tests/test-projects/DotNetCoreMultiTargetFramework/DotNetCoreMultiTargetFramework/DotNetCoreMultiTargetFramework.csproj
Fixed bug #55508 - Support multiple target framework projects
https://bugzilla.xamarin.com/show_bug.cgi?id=55508
SDK style projects that target multiple frameworks can now be opened
and will show source files and dependency information. Currently
the support is limited. The project is treated as though it only has
one target framework which is the first one specified in the
TargetFrameworks property in the project file.
This is not a complete solution but it is better than the existing support. NuGet restore will only consider one target framework which is incorrect. Also it is not currently supported to install a NuGet package conditionally into the supported target frameworks if it is not compatible with all of them.
=> [Core] Add limited support for multi target framework projects

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/FolderNodeBuilder.cs
WHenever we open a new folder, we calculate project paths to decide where the file ends up.
That said, the ProjectFileCollection is a bit heavy, as it does a lot more than just being a container for ProjectFile. It creates a tree of items, allocates a lot of data that we don't need, subscribes to change events. Addition of an item to a ProjectFileCollection is not O(1) either, its a recursive method which queries dictionaries based on how many path segments there are. The code just needs to check whether the path is a child of another path, so, since we do it in the GetFolderContent method, just use a simple List<ProjectFile>.
Expanding the icons folder from MonoDevelop.Ide is now ~instant, from 2-3s observed time.
=> [Ide] Improve performance of first folder expansion.

main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebuggingService.cs, main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/PinnedWatchStore.cs
when loading user preferences.
Fixed bug #52527 : Hard crash while debugging simple console app
https://bugzilla.xamarin.com/show_bug.cgi?id=52527
This crash happens because it seems not to restore tracing breakpoints
even though it restores LiveUpdate property when loading user
preferences.
The same crash doesn't happen with this patch, but not useful yet due
to bug #52528
=> Restore breakpoints for pinnedwatches

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Highlighting/CSharpSyntaxMode.cs
for Mac'
Broke during textmate port…
=> Fixed 'Bug 56681 - nfloat Syntax Highlighting Broken, Visual Studio

main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/AssemblyBrowserWidget.cs
first start'
The replace with widget call broke the expose event handler. It's only
for correcting the hpaned position - so it's working on general
expose.
=> Fixed 'Bug 56612 - Assembly Browser doesn't show assemblies list on

main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/Extensions.cs
This was missed when MultiDebugging support was introduced, same thing was done for other "start debug" calls e.g.: https://github.com/mono/monodevelop/commit/7826ec03c149c75ba943fd44a9f7d9bddfc3fd3b#diff-5d6c50c1e9217c288ff67babbbb8a9aeL49
=> Bug 55617 - Run->Debug Application doesn't support MultiProcessDebugging

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildEvaluationContext.cs, main/tests/UnitTests/MonoDevelop.Projects/MSBuildProjectTests.cs, main/tests/test-projects/msbuild-tests/functions.csproj
Evaluate indexers for any expression result, not only for properties.
Fixes bug #55516 - Project evaluation fails to evaluate property in roslyn.
=> Fix msbuild evaluation issue

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageReferenceNuGetProject.cs
Added missing GetAssetsFilePathOrNullAsync which is a new required
method for BuildIntegratedNuGetProject derived classes in NuGet 4.3.
=> [NuGet] Fix build

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/FileProvider.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/Scope.cs
Value cannot be null error'
Not exactly sure why document.FileName was null. I would've guessed it
was a new empty unsaved file use case - but the screenshots doesn't
look like so. Anyways in the search in open documents use case it's
not needed to look at the file name at all - so that should fix that
issue. But I hadn't any use case for that.
=> Fixed 'Bug 55398 - Replace in Files within Current Document gives

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/OnTheFlyFormatter.cs
Now with internals access Formatter.GetFormattedTextChanges is
available for us that issue can be fixed. The way creating a new
syntax tree & get the diff to the old tree caused too large text
replace changes. When the caret was in between two changes it moved to
the end of both because the tree diff concated both replace operations
to one. This fixed the bug & on the fly formatting should be way
faster without the work around.
=> Fixed 'Bug 56806 - Intellisense breaks when typing #region in C# file'

main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/TargetRuntime.cs
This brings down RegisterSystemAssemblies from 618ms to 44ms, most of it IO bound. Total File.Exists calls down from 8919 to 402.
=> 	[Perf] Optimize loading of SystemAssemblyService

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTests.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/DotNetCoreNuGetProject.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/DotNetProjectExtensions.cs, main/src/addins/MonoDevelop.Packaging/MonoDevelop.Packaging.Gui/GtkCrossPlatformLibraryProjectTemplateWizardPageWidget.cs, main/src/addins/MonoDevelop.Packaging/MonoDevelop.Packaging.Gui/GtkPackagingProjectTemplateWizardPageWidget.cs, main/src/addins/MonoDevelop.Packaging/MonoDevelop.Packaging.csproj, main/src/addins/MonoDevelop.Packaging/MonoDevelop.Packaging/DotNetProjectExtensions.cs, main/src/addins/MonoDevelop.Packaging/MonoDevelop.Packaging/PackageReferenceCollection.cs, main/src/addins/MonoDevelop.Packaging/MonoDevelop.Packaging/PackagingNuGetProject.cs, main/src/addins/MonoDevelop.Packaging/MonoDevelop.Packaging/PackagingProject.cs, main/src/addins/MonoDevelop.Packaging/MonoDevelop.Packaging/ProjectPackageReferenceExtensions.cs, main/src/addins/MonoDevelop.Packaging/PostBuild.proj, main/src/addins/MonoDevelop.Packaging/Templates/CrossPlatformLibrary.xpt.xml, main/src/addins/MonoDevelop.Packaging/Templates/PackagingProject.xpt.xml, main/src/addins/MonoDevelop.Packaging/packages.config, main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectConfigurationItem.cs
Fixes several NuGetizer 3000 bugs including:
1. 56701 - Windows created nuspec can not be loaded on a mac
2. 56706 - Can not create a nuget package with Standard net libraries
3. 52657 - Creating a new Multiplatform Library requires a
description
4. Packages folder empty on re-opening NuGet packaging project
5. Fix Dependencies folder being displayed if latest NuGet.Build.Packaging 0.1.276 NuGet package is installed.
6. Create MSBuild targets during restore for NuGet packaging project if they are missing.
7. Update to latest stable NuGet.Build.Packaging 0.1.276 in project templates.
=> [NuGetizer3000] Visual Studio on windows compatibility

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CustomTools/CustomToolService.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CustomTools/ResXFileCodeGenerator.cs, main/tests/UnitTests/MonoDevelop.Projects/MSBuildTests.cs, main/tests/test-projects/DotNetCoreResources/DotNetCoreProject/DotNetCoreProject.csproj, main/tests/test-projects/DotNetCoreResources/DotNetCoreProject/Program.cs, main/tests/test-projects/DotNetCoreResources/DotNetCoreProject/Resources.Designer.cs, main/tests/test-projects/DotNetCoreResources/DotNetCoreProject/Resources.resx, main/tests/test-projects/DotNetCoreResources/DotNetCoreResources.sln, main/tests/test-projects/DotNetCoreResources/NetStandardProject/Class1.cs, main/tests/test-projects/DotNetCoreResources/NetStandardProject/NetStandardProject.csproj, main/tests/test-projects/DotNetCoreResources/NetStandardProject/Resources.Designer.cs, main/tests/test-projects/DotNetCoreResources/NetStandardProject/Resources.resx
Fixed bug [#56519](https://bugzilla.xamarin.com/show_bug.cgi?id=56519) - ResX files produced for .NET Core generate code that does not compile
Projects that target .NET Core App 1.x or .NET Standard 1.x cannot
compile code that uses "typeof(Resources).Assembly" which was
generated by the ResXFileCodeGenerator. Now if these target frameworks
are used by the project then the code generated uses
"typeof(Resources).GetTypeInfo().Assembly" which is supported.
.NET Core 2.0 and .NET Standard 2.0 do not require the use of
GetTypeInfo.
As implemented, the ResXFileCodeGenerator knows about the .NETCoreApp and .NETStandard target frameworks. So not sure if this is the best place for the logic. It currently has a special case for the .NETPortable target framework.
=> [Ide] Fix generated code for resx files in .NET Core projects

main/src/core/MonoDevelop.Ide/MonoDevelop.Components/GtkUtil.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkMacInterop.cs
Problem was that Gtk.Global.CurrentEventTime is returning 0(at least on my computer) and throttling logic doesn’t like that, hence it ignores command
=> Fixed problem with Cmd+Shift+F not always working

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Features/AutoInsertBracket/CSharpAutoInsertBracketHandler.cs, main/src/addins/CSharpBinding/MonoDevelop.CSharp.UnitTests/CSharpNUnitSourceCodeLocationFinder.cs
This happened while editing a file that was not set with BuildAction=Compile.
=> [C#] Fix NRE in AutoInsert bracket handler.

main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.Tests/DebugTests.MonoDevelop.cs
In past version had `4.8 (something)` now it's just `5.0`
=> Fixed version parsing of newer versions of Mono runtime in debugger unit tests

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs, main/tests/test-projects/msbuild-glob-tests/glob-test-saved3.csproj
Fixed bug #56957 - Adding new resource file causes duplicate file
build error
https://bugzilla.xamarin.com/show_bug.cgi?id=56957
Adding a new Resources file to a .NET Core project would add the
.resx file and the .Designer.cs file as an Include instead of an
Update item:
```
<ItemGroup>
<EmbeddedResource Include="Resources.resx">
<Generator>ResXFileCodeGenerator</Generator>
<LastGenOutput>Resources.Designer.cs</LastGenOutput>
</EmbeddedResource>
</ItemGroup>
<ItemGroup>
<Compile Include="Resources.Designer.cs">
<DependentUpon>Resources.resx</DependentUpon>
</Compile>
</ItemGroup>
```
This then caused the build to fail since these files are part of
existing wildcard globs and should instead be Update items. This
problem affected new files that have extra metadata when they are
added to the …
=> [Core] Fix new resx file not added as Update item in Sdk projects

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdk.cs
Fixed bug #56999 - Show details dialog is not displaying detailed
build information
https://bugzilla.xamarin.com/show_bug.cgi?id=56999
.NET Core sdk not being installed would result in the
DotNetCoreSdk.Versions being null which caused an exception in the
About dialog when trying to list the sdk versions installed.
=> [DotNetCore] Fix null ref in About dialog

main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Rename/RenameItemDialog.cs, main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Rename/RenameRefactoring.cs
Fix is to disable that option in non source code case. Renaming in generated code is complex in general case.
=> Fixed 'Bug 56890 - Rename a XAML type doesn't rename the file.'

main/msbuild/MDBuildTasks/MDDownloadFiles.cs
On Windows the CodeTaskFactory uses a very old C# compiler that doesn't support string interpolation. The cheapest thing to keep Windows build working is to downgrade this script.
=> Avoid using C# 6 in MDDownloadFiles.cs

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProject.cs, main/tests/UnitTests/MonoDevelop.Projects/MSBuildTests.cs
Fixed bug #55560 - Setting Build Action to None for C# file is ignored
https://bugzilla.xamarin.com/show_bug.cgi?id=55560
Creating a .NET Core console project, then changing the build action
on a C# file to None, back to Compile and then back to None again
would result in the Remove item not being added to the project file.
So the project file would end up having:
```
<ItemGroup>
<None Include="Program.cs" />
</ItemGroup>
```
When it should have had:
```
<ItemGroup>
<Compile Remove="Program.cs" />
</ItemGroup>
<ItemGroup>
<None Include="Program.cs" />
</ItemGroup>
```
The problem was that when the Compile Remove item was removed when
switching the build action back to Compile the associated best item
group was not removed since the wrong group id was used. Then when
the new Compile Remove …
=> [Ide] Fix Remove item not added

main/src/addins/MacPlatform/MainToolbar/SelectorView.cs
The main toolbar SelectorView icons must match the IDE theme and not the OS interface style.
=> [Mac] Fix ExecutionTarget icon theme

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.addin.xml
This avoids having duplicate NuGet.Frameworks.dll if this assembly
is required by another addin that depends on the NuGet addin.
=> [NuGet] Import NuGet.Frameworks.dll

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.addin.xml, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.csproj, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/HasNuGetPackageOrReferenceFileTemplateCondition.cs
A file template can now specify that it should be enable if the project
has a specific reference or has a particular NuGet package installed.
Whilst a reference will work for project's that use a packages.config
file if the project uses a project.json file or uses PackageReferences
then just checking the references will not find any matches. By
allowing a file template to specify a package id then projects that
do not have an explicit reference to a particular assembly, due to not
using a packages.config file, can now have file templates enabled or
disabled.
<HasPackageOrReference PackageId="Xamarin.Forms" Assembly="Xamarin.Forms" />
=> [NuGet] Add file template condition for packages

main/src/addins/MonoDevelop.HexEditor/Mono.MHex.Rendering/Margin.cs, main/src/addins/MonoDevelop.HexEditor/MonoDevelop.HexEditor.csproj, main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs, main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/MessageBubbleTextMarker.cs, main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SearchInSelectionMarker.cs, main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs, main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/TextMarker/DebugTextMarker.cs, main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/TextMarker/UsageSegmentMarker.cs
This prevents allocating an extra char array on drawing line parts. Use short lived pinning of strings instead of this.
=> [Ide] Optimize text drawing.

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/MicrosoftTemplateEngineSolutionTemplate.cs
With the new template engine, parameters can have default values:
```
"symbols": {
"MinimumOSVersion": {
"type": "parameter",
"description": "Overrides the Info.plist's MinimumOSVersion",
"replaces": "$MinimumOSVersion",
"datatype": "string",
"defaultValue": "8.0"
}
}
```
Therefore we need to combine those "DefaultParameters" values with the ones set by the ExtensionNode.
=> [MicrosoftTemplateEngine] Get default parameters from ITemplateInfo

main/src/addins/WindowsPlatform/WindowsPlatform/ImageBox.cs
Loaded event was called multiple times, while unloaded only once. Only subscribe to changed events when not subscribed. This guarantees that debugging operation in core (and windows) is leak free.
=> [Windows] Fix leak of ImageBox.

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreRuntime.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdk.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/PackageSpecCreatorTests.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageSpecCreator.cs
These workarounds are no longer needed now that the installed .NET Core sdk is now resolved.
=> [DotNetCore] Remove .NET Core 2.0 workarounds

main/MonoDevelop.props
MSBuild 15.3 will be briefly broken, see details here:
https://github.com/Microsoft/msbuild/issues/2165
It is not yet public and will be fixed soon, but we're already starting to hit the problem as we upgrade. To temporarily work around this until everybody upgrades the MSBuild that fixes the issue this is a simple workaround with no other side effects.
=> Add a preventative workaround for an incoming MSBuild regression

main/src/core/MonoDevelop.Core/MonoDevelop.Core/Runtime.cs
For some reason even though we call Assembly.Load from the codebase, it still doesn't seem to get promoted from LoadFrom to the Load context.
A solution is to use AssemblyResolve event and just resolve to the assembly that's already loaded.
=> Avoid assembly load failure on Windows.

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeTemplates/CodeTemplate.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeTemplates/ExpansionObject.cs
from toolbox'
The offset wasn't correct in the old semantic model. So using the
insertion offset fixes that crash.
=> Fixed 'Bug 57155 - Visual Studio for Mac crashing when adding snippet

main/src/addins/MacPlatform/MainToolbar/StatusBar.cs
Update or hide the status bar popover on status changes.
(fixes bug #56725)
=> [56725][Mac] Update or Hide status popover on status changes

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/KeyBindingSet.cs
If KeyBindingSet is being compared to its parent,
only the key bindings defined by the child need
to be compared. Other bindings are inherited and
equal for both.
(fixes bug #57111)
=> [Ide] Fix KeyBindingSet compare with parent

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Commands/PackageManagementStartupHandler.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Gui/AddPackagesDialogRunner.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.Helpers/FakeUpdatedPackagesInWorkspace.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.Helpers/TestableCheckForNuGetPackageUpdatesTaskRunner.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/BackgroundPackageActionRunner.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/CheckForNuGetPackageUpdatesTaskRunner.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/IUpdatedNuGetPackagesInWorkspace.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageManagementCredentialService.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/RestoreAndCheckForUpdatesAction.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/UpdatedNuGetPackagesInWorkspace.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/UpdatedNuGetPackagesProvider.cs, main/src/addins/MonoDevelop.PackageManagement/NuGet.Credentials/CredentialService.cs
Fixed bug #56674 - VS for Mac constantly prompting for MyGet
credentials
https://bugzilla.xamarin.com/show_bug.cgi?id=56674
With check for updates enabled, multiple projects in the solution,
and a package source that was missing or had invalid credentials,
on opening the solution the credential dialog would display multiple
times even if the correct username and password was entered or the
dialog was cancelled. The dialog was being displayed for each
project and the credential information was not being re-used.
To fix this the NuGet SourceRepositories are re-used when checking
for updates and also when restoring the projects when the solution
is first opened. Any valid credentials entered will be re-used
when checking the remaining projects. If the credential dialog is
cancelled then the …
=> [NuGet] Fix credential dialog shown multiple times on opening solution 

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.PropertyGrid.Editors/PropertyTextEditor.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.PropertyGrid/PropertyGridTable.cs
Tab/Shift-Tab moves through the rows and <space> collapses/expands rows
Fixes BXC #53711
=> [A11y] Make the property grid fully keyboard accessible

main/external/fsharpbinding/MonoDevelop.FSharp.Tests/CompilerArguments.fs, main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/CompilerArguments.fs, main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/CompilerLocationUtils.fs
Fixes unit tests. msbuild doesn't reference mscorlib by default, so the IDE
shouldn't either
=> [F#] Add target frameworks and don't reference mscorlib.

main/src/core/MonoDevelop.Startup/app.config
This is the version that we actually depend on using NuGet (4.3.0) and deploy to output folder.
=> Binding redirect for S.R.IS.RI to 4.0.1.0

main/src/addins/MonoDevelop.ConnectedServices/CodeDependency.cs
Fixes the following exception
WARNING [2017-06-05 10:55:13Z]: Operation not supported in background thread. Location:   at System.Environment.get_StackTrace () [0x00000] in /private/tmp/source-mono-2017-04/bockbuild-2017-04/profiles/mono-mac-xamarin/build-root/mono-x64/mcs/class/corlib/System/Environment.cs:316
at MonoDevelop.Core.Runtime.CheckMainThread () [0x00014] in /Users/builder/data/lanes/4989/8d2d1180/source/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Core/Runtime.cs:445
at MonoDevelop.Ide.TypeSystem.MonoDevelopWorkspace.TryApplyChanges (Microsoft.CodeAnalysis.Solution newSolution, Microsoft.CodeAnalysis.Shared.Utilities.IProgressTracker progressTracker) [0x00000] in /Users/builder/data/lanes/4989/8d2d1180/source/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide. …
=> [Connected Services] Invoke the code actions on the UI thread.

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/LanguageCellRenderer.cs
Selecting a different category in the New Project dialog would
throw a null reference exception in the language cell renderer due
to the template not being available initially.
Also wondering if we should make LanguageCellRenderer class non-public on master and on the d15-3 branch. It is only used by the New Project dialog.
=> [Ide] Fix null reference exception in New Project dialog

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/LanguageCellRenderer.cs
Selecting a different category in the New Project dialog would throw a null reference exception in the language cell renderer due to the template not being available initially.
Also made LanguageCellRenderer class non-public
=> [d15-3] Fix null ref language cell renderer

main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.QuickTasks/QuickTaskOverviewMode.cs, main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.QuickTasks/QuickTaskStrip.cs, main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorWidget.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.DockNotebook/TabStrip.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/DockBarItem.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/DockFrame.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/DockItemTitleTab.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/TabStrip.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components/ImageButton.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components/PathBar.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Tabstrip.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DefaultWorkbench.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Styles.cs
Make the main UI navigable by the tab key.
Obviously you can't tab out of the main text editor though, but it seems like that's not a thing that can be done on native macOS anyway.
=> Make main UI keyboard accessible

main/src/core/MonoDevelop.Ide/ExtensionModel/Commands.addin.xml, main/src/core/MonoDevelop.Ide/options/KeyBindingSchemeVisualStudio-mac.xml, main/src/core/MonoDevelop.Ide/options/KeyBindingSchemeVisualStudio.xml
This makes the Page+Up/Page+Down keys less discoverable, but its the only way to resolve the conflict between the command manager and default Gtk key handler inside the text editor without bigger command system design changes.
(fixes bug #55143)
=> [Ide] Don't bind Page+Up Page+Down keys by default

main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Tabstrip.cs
When the tabstrip was being focused it could try to access a tab with a negative index and crash
=> [A11y] Fix crash when the tabstrip is reset on debugging

main/src/core/MonoDevelop.Ide/MonoDevelop.Components/RestartPanel.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.OptionPanels/IDEStyleOptionsPanel.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.OptionPanels/SdkLocationPanel.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
Split the Restart panel out into a separate widget, make it accessible.
Fixes BXC #53523
=> [A11y] Add a Restart panel and make it accessible

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DefaultWorkbench.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopSourceTextContainer.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
Without a repro it's hard to tell why that happens. This patch should
ensure that no invalid document is open and that the analysis document
invalidates when the roslyn workspace closes the open document. The
source text container has now a check on invalid documents as well and
tries to reopen the document in that case. This should fix the issue.
=> Fixed 'Bug 56650 - Many workspace errors logged while coding'

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.csproj, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/MSBuildSdksPathGlobalPropertyProvider.cs, main/src/addins/MonoDevelop.DotNetCore/Properties/MonoDevelop.DotNetCore.addin.xml
Fixed bug #57195 - Xamarin.Forms with ASP.NET Mobile Backend does not
build
https://bugzilla.xamarin.com/show_bug.cgi?id=57195
Building an ASP.NET Core project when .NET Core SDK 1.0.3 or lower
was installed, or if no .NET Core SDK was installed, would result in
the build failing with the error:
error MSB4057: The target "Build" does not exist in the project.
With .NET Core SDK 1.0.4 or later installed this build error does not
occur. The problem is that with older .NET Core SDKs the ASP.NET Core
project uses the Microsoft.Web.Sdk.Web MSBuild imports. The older
Microsoft.Web.Sdk.Web  imports use the MSBuildSdksPath property when
importing other MSBuild targets files. This is not defined and results
in nothing being imported and so the build targets are not available.
To fix this the …
=> [DotNetCore] Fix ASP.NET Core project build error with old SDK

main/external/fsharpbinding/MonoDevelop.FSharp.Tests/TestTooltipProvider.fs, main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpSymbolHelper.fs
This is a workaround for a bug in FCS. The compiler is returning the
same location for both start and end of the namespace name, which
resulted in a zero width tooltip.
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=57140
=> [F#] Fix tooltip position for namespaces

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.csproj, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/MSBuildSdksPathGlobalPropertyProvider.cs, main/src/addins/MonoDevelop.DotNetCore/Properties/MonoDevelop.DotNetCore.addin.xml
Fixed bug #57195 - Xamarin.Forms with ASP.NET Mobile Backend does not
build
https://bugzilla.xamarin.com/show_bug.cgi?id=57195
Building an ASP.NET Core project when .NET Core SDK 1.0.3 or lower
was installed, or if no .NET Core SDK was installed, would result in
the build failing with the error:
error MSB4057: The target "Build" does not exist in the project.
With .NET Core SDK 1.0.4 or later installed this build error does not
occur. The problem is that with older .NET Core SDKs the ASP.NET Core
project uses the Microsoft.Web.Sdk.Web MSBuild imports. The older
Microsoft.Web.Sdk.Web  imports use the MSBuildSdksPath property when
importing other MSBuild targets files. This is not defined and results
in nothing being imported and so the build targets are not available.
To fix this the …
=> [d15-3][DotNetCore] Fix ASP.NET Core project build error with old SDK 

main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs
Don't modify the background of the root window, if
the text editor is not inside a ScrolledWindow.
(fixes bug #43049)
=> [TextEditor] Don't modify root window background

main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/TextEditorOptions.cs
When copying a TextEditorOptions derivate which overrides `TextEditorOptions.EditorThemeName`, always use the overriden style name, since the internal `colorStyle` could be wrong.
This also fixes the wrong Diff View theme (alsways default `Light`).
=> [TextEditor] Properly copy the TextEditorOptions color style

main/src/addins/MacPlatform/MacInterop/ProcessManager.cs
This fixes only part when mono/app fails to close itself and IDE needs to force close it, underlying problem still needs to be fixed by XM/Mono.
=> Bug 57223 - Debugger does not disconnect from mac apps properly

main/src/addins/AspNet/MonoDevelop.AspNet.csproj, main/src/addins/AspNet/packages.config, main/src/addins/TextTemplating/MonoDevelop.TextTemplating/MonoDevelop.TextTemplating.csproj, main/src/addins/TextTemplating/MonoDevelop.TextTemplating/packages.config
Instead of strongnaming it at build time, which always dirties the build.
=> Use strongnamed T4 NuGet

main/src/addins/MonoDevelop.AzureFunctions/Properties/Manifest.addin.xml, main/src/addins/MonoDevelop.DotNetCore/Properties/MonoDevelop.DotNetCore.addin.xml, main/src/core/MonoDevelop.Ide/ExtensionModel/Templates.addin.xml, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Codons/TemplateCategoryCodon.cs
The project template categories were defined in the .addin.xml file
using an attribute without an underscore so they were not added
to the translations. The project template categories now use _name
for the category name so they are added to the translations. To
maintain backwards compatibility the name attribute without the
underscore is still supported.
<Category id="library" _name="Library">
=> [Ide] Fix project template categories not added to translations

main/src/addins/MonoDevelop.Gettext/MonoDevelop.Gettext.addin.xml
CDATA tags that were inside translatable xml elements were included
in the extracted translation text when the files are scanned. The
CDATA tags themselves should not be displayed to the user so they are
now excluded with the regular expression. CDATA tags are used in
the project templates and were not translated since the text being
passed to the translation catalog would not include these tags and
would not find a match.
=> [Gettext] Do not include CDATA tags in translations

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/NewFileDialog.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/FileTemplate.cs
Fixed bug #53635 - Many "New file" dialogs/strings are unlocalized.
https://bugzilla.xamarin.com/show_bug.cgi?id=53635
File templates that require a custom localizer were not translated
since Gettextcatalog.GetString was always used.
Requires [md-addins change](https://github.com/xamarin/md-addins/pull/2077) before this will translate the file templates.
=> [Ide] Fix file templates not translated

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.csproj, main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj, main/src/core/MonoDevelop.Startup/MonoDevelop.Startup.csproj
This is better for build incrementality as MSBuild and VS fast up-to-date-check will always rebuild a project if it has an item with CopyToOutputDirectory=Always.
=> Use PreserveNewest instead of Always

main/src/addins/MonoDevelop.Gettext/MonoDevelop.Gettext.addin.xml
CDATA tags that were inside translatable xml elements were included
in the extracted translation text when the files are scanned. The
CDATA tags themselves should not be displayed to the user so they are
now excluded with the regular expression. CDATA tags are used in
the project templates and were not translated since the text being
passed to the translation catalog would not include these tags and
would not find a match.
=> [d15-3][Gettext] Do not include CDATA tags in translations

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeTemplates/ExpansionObject.cs
constructor'
We should consider replacing our code template system with the VS.NET
one or rework the system.
=> Fixed 'Bug 57392 - ctor code snippet is producing an nameless

main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitCredentials.cs
Bug 56534 - Update git repo on VSTS fails with "null username or password"
=> [Git] Fix misleading exception being thrown on declining auth prompt

main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitCredentials.cs
Bug 56534 - Update git repo on VSTS fails with "null username or password"
=> [D15.3][Git] Fix misleading exception being thrown on declining auth prompt

main/src/core/MonoDevelop.Startup/app.config
Do NOT trust nuget package versions for coreclr as they do NOT reflect the actual assembly version. Target frameworks supply different versions, the only way to know which version range and version to use is to look at all the package binaries and the binaries in the build directory.
=> [Windows] Make MD open

main/src/addins/MonoDevelop.Packaging/gtk-gui/MonoDevelop.Packaging.Gui.GtkNuGetPackageMetadataOptionsPanelWidget.cs, main/src/addins/MonoDevelop.Packaging/gtk-gui/gui.stetic
Fixed bug #56918 - When typing a description in NuGet package Metadata
the UI keeps on growing
https://bugzilla.xamarin.com/show_bug.cgi?id=56918
In project options typing a long description for the NuGet package
metadata would cause the dialog to increase in width. The release
notes on the other tab does not have this problem. Setting the
scroll window's policy to never show the horizontal scrolllbars
seems to break the word wrapping. Leaving it as the default fixes
the wrapping so the dialog does not increase in width.
=> [Packaging] Fix description metadata not wrapping in project options

main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/CompilerArguments.fs
Fixes the warning when  a badly formatted NoWarn compiler option such as `;1591` is received.
=> Fix badly formatted nowarn

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetCompilerParameters.cs
Creating the configuration when creating a project would throw a null
reference exception since the CSharpCompilerParameters was trying to
notify its parent project that a property had changed but it was
not associated with a parent configuration.
=> [Core] Fix null ref exception on creating a new project

main/src/addins/PerformanceDiagnostics/PerformanceDiagnostics/LeakHelpers.cs, main/src/addins/PerformanceDiagnostics/PerformanceDiagnostics/LeakSummaryService.cs, main/src/addins/PerformanceDiagnostics/PerformanceDiagnostics/LeakTrackerPad.cs
This triggers a few gcs before updating the label when hovering the pad.
=> [Perf] Allow non-steady collection report for the pad

main/src/core/Mono.TextEditor.Platform/PlatformCatalog.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj, main/src/core/MonoDevelop.Core/packages.config, main/src/core/MonoDevelop.Ide/ExtensionModel/MonoDevelop.Ide.addin.xml, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Composition/CompositionManager.cs, main/src/core/MonoDevelop.Startup/app.config
A set of fixes that enables the new VSMEF composition live side-by-side with the old compositions for now. This will allow the WebTools addin to target the new composition while everything else is unchanged.
=> Enable VSMEF parallel to the old composition

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Templating/DotNetCoreProjectTemplateWizard.cs, main/src/addins/MonoDevelop.DotNetCore/Properties/MonoDevelop.DotNetCore.addin.xml
Fixed bug #57591 - .NET Core Class Library targets .NET Standard
https://bugzilla.xamarin.com/show_bug.cgi?id=57591
When a single .NET Core app runtime was installed then the .NET
Core app class library project would use the default framework set
by the project template which is .NET Standard instead of .NET Core
App. This happens when the wizard is not displayed so the framework
is not set. Now the framework is set if the wizard page is not
displayed so the correct target framework is used in the created
class library project.
=> [DotNetCore] Fix .NET Core library project targeting .NET standard

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Composition/CompositionManager.cs
For now while we're still prototyping it's useful to be able to use the composition even if it has errors.
=> Don't throw in VSMEF on composition errors.

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/RegisteredPackageSourcesViewModelTests.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/RegisteredPackageSourcesViewModel.cs
Fixed bug #57588 - Adding package source url with extra spaces should
be trimmed
https://bugzilla.xamarin.com/show_bug.cgi?id=57588
Copying and pasting NuGet package source url can sometimes copy extra
whitespace which can then result in restore errors such as:
Failed to verify the root directory of local source
' https://api.nuget.org/v3/index.json'.
The package source name and url entered are now trimmed. This also
matches Visual Studio on Windows behaviour.
=> [NuGet] Trim whitespace from new package source

main/external/fsharpbinding/MonoDevelop.FSharp.Shared/Extensions.fs, main/external/fsharpbinding/MonoDevelop.FSharp.Tests/CompilerArguments.fs, main/external/fsharpbinding/MonoDevelop.FSharp.Tests/TemplateTests.fs, main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpProject.fs, main/external/fsharpbinding/MonoDevelop.FSharpBinding/RefactoringOperationsHandler.fs, main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/CompilerArguments.fs, main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/Extensions.fs, main/external/fsharpbinding/MonoDevelop.FSharpi.Service/Program.fs, main/external/fsharpbinding/paket.lock
Simplify Task usage by allowing async to bind and return `Task` or `Task<T>`
=> [F#] Simplify Task usage

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/PackageSpecCreatorTests.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageSpecCreator.cs
Project references that have ReferenceOutputAssembly set to false
should not be added to the project.assets.json file. This can cause
the restore to fail. For example, if a .NET Standard project has a
project reference to a .NET Core App project, but has the
ReferenceOutputAssembly set to false, then dotnet restore from the
command line works, but the restore would fail in the IDE. Now the
restore works when run by the IDE.
=> [NuGet] Ignore ReferenceOutputAssembly false project refs for restore

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/syntaxes/CSharp/C#.sublime-syntax
method names and property names'
=> Fixed 'Bug 57594 - Numbers syntax highlighted in namespace names,

main/src/addins/CSharpBinding/CSharpBinding.addin.xml, main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/QuickFixMenuHandler.cs
Changed the way the quick fix menu is shown. It used to be a command
that generated a submenu with the fixes. Now the quick fix menu is
defined as an item set that contains the quick fix command array.
This is a workaround to a Cocoa issue. When a submenu is made visible,
there seems to be no way to hide it, even when the item that defines
the submenu is removed. By changing the way the quick fix menu is
generated, that menu doesn't need to be closed and recreated, it is
just updated.
Fixes bug #57704
=> Fix quick fix menu load issue

main/src/addins/CSharpBinding/MonoDevelop.CSharp/AstStockIcons.cs, main/src/addins/CSharpBinding/MonoDevelop.CSharp/DeclaredSymbolInfo.cs, main/src/addins/CSharpBinding/MonoDevelop.CSharp/ProjectSearchCategory.cs
First part of work that needs to be done to be able to switch to roslyn services that use SyntaxTree/SymbolTree caches.
=> [Ide] Replace our DeclaredSymbolInfo with roslyn implementation.

main/src/addins/MonoDevelop.GtkCore/libsteticui/AssemblyResolver.cs
ERROR [2017-06-23 22:59:52Z]: The file '/Users/therzok/Work/md/monodevelop/main/external/mono-addins/Mono.Addins.Gui/Mono.Addins.Gui/AddinManagerDialog.cs' could not be opened.
System.InvalidCastException: Specified cast is not valid.
at Stetic.AssemblyResolver.ClearCache () [0x0000e] in /Users/builder/data/lanes/432/5315887a/source/monodevelop/main/src/addins/MonoDevelop.GtkCore/libsteticui/AssemblyResolver.cs:88
at Stetic.CecilWidgetLibrary.Flush () [0x0000e] in /Users/builder/data/lanes/432/5315887a/source/monodevelop/main/src/addins/MonoDevelop.GtkCore/libsteticui/CecilWidgetLibrary.cs:364
at Stetic.Registry.EndChangeSet () [0x0002f] in /Users/builder/data/lanes/432/5315887a/source/monodevelop/main/src/addins/MonoDevelop.GtkCore/libstetic/Registry.cs:44
at …
=> [Stetic] Fix InvalidCastException preventing editing

main/src/core/MonoDevelop.Core/MonoDevelop.Core/StringTable.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildWhitespace.cs
This reduces the number of duplicate strings from 40MB to 30MB. We now
avoid substringing and creating a lot of string junk and reusing simple
whitespace strings.
Also cache the first part of the string, as most of them are just
newlines
=> [Core] Optimize MSBuild evaluation whitespace allocations.

main/external/fsharpbinding/MonoDevelop.FSharp.Tests/TestTooltipProvider.fs, main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpSymbolHelper.fs
Fixes this tooltip issue where the tooltip appears in the wrong position when endOffset == offset
=> Fix offsets for base method tooltip. Fixes #57807

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildEvaluationContext.cs
Intermediate parsing strings can be cached in the pool. Total string allocations coming in from the Project Model dropped a lot.
Previously, MSBuildEvaluationContext.EvaluateReference would create 250MB of strings, now it only allocates 3.5MB total
=> [Core] Drop another 10MB of duplicate strings

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/LanguageCellRenderer.cs
Fixed bug #57904 - Language not shown for all recently used projects
in New Project dialog
https://bugzilla.xamarin.com/show_bug.cgi?id=57904
In the New Project dialog the Recently used section would only show
the template language if the row was selected. Now every row shows
the language.
=> [Ide] Fix language not displayed for recently used project templates

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.addin.xml, main/src/addins/PerformanceDiagnostics/PerformanceDiagnostics/Properties/PerformanceDiagnostics.addin.xml
NuGet - General and Performance Diagnostics - General were using the same section id as Text Editor - General so the wrong preferences page was displayed on re-opening the global preferences dialog. The Text Editor - General section was previously always selected since it was the first matching section id.
=> Fix duplicate global preference section ids

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdk.cs
Fixed bug #57769 - F# .NET Core 2.0 projects do not compile
https://bugzilla.xamarin.com/show_bug.cgi?id=57769
F# .NET Core projects would fail to compile with an error about the
Build target being missing.
MSB4057: The target "Build" does not exist in the project.
Also the FSharp.Core package reference was not added to the generated
project.assets.json file. This is an implicit reference added by the
.NET Core sdk MSBuild targets.
Until the Microsoft.FSharp.NetSdk.targets and .props files are
included in Mono a workaround has been added where the F# shim
properties are set as environment variables which allows the project
to be evaluated properly and the build to work.
FSharpPropsShim=/usr/local/share/dotnet/sdk/2.0.0-preview2-006497/FSharp/Microsoft.FSharp.NetSdk.props …
=> [d15-3][DotNetCore] Fix F# .NET Core 2.0 projects do not compile

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs
Fixed bug #55351 - Dirty file interferes with creating new project
https://bugzilla.xamarin.com/show_bug.cgi?id=55351
With unsaved files open in the IDE, creating a new project would
show a dialog prompt asking to save changes. This dialog had two
buttons Cancel and Save (or Save As). Now the dialog also has a
Don't Save button which will discard the changes and close the unsaved
file. Also the dialog now has a message saying that not saving will
cause the changes to be permanently lost.
=> [Ide] Support not saving files when creating new project

main/src/addins/MonoDevelop.WebReferences/MonoDevelop.WebReferences.Dialogs/WebReferenceDialog.cs
Fixed bug #57449 - Remove WCF 'Add a Reference' dialog
https://bugzilla.xamarin.com/show_bug.cgi?id=57449
The WCF option in the Web References dialog is enabled if the project
targets the .NET Framework. If the project targets a Xamarin mobile
framework then WCF cannot be selected, the combo box is disabled, and
instead the .NET 2.0 Web Services option is selected by default. The
logic for PCL projects is unchanged from before and WCF will selected
by default and the .NET 2.0 Web Services option cannot be selected.
Also updated the default url used in the dialog to one that works. Not sure if we should be using a default url, maybe no url, or just the last one used might be better. VS 2017 on Windows in its Service References dialog does not use a default and does not remember the last …
=> [WebReferences] Disable WCF option in dialog when unsupported

main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj, main/src/core/MonoDevelop.Core/packages.config, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj, main/src/core/MonoDevelop.Ide/packages.config, main/src/core/MonoDevelop.Startup/app.config
The bump is required to support ZIP files with
versions not supported by the old SharpZipLib 0.86
=> Replace SharpZipLib package with JetBrains.SharpZipLib.Stripped

main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/LanguageService.fs
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=57925
To test -
- `git clone https://github.com/fsharp/FsAutoComplete.git`
- `cd FsAutoComplete`
- `./build.sh`
- Open up the solution in VSfM
- Wait for tooltips to appear
- Run Find references on any symbol
=> F# Find references deadlock

main/src/addins/AspNet/Templates/MvcCommon/_Layout.cshtml
Fixed bug #57640 - ASP.NET MVC default profile, showed Chinese will
be garbled
https://bugzilla.xamarin.com/show_bug.cgi?id=57640
Added a meta tag to the layout page specifying the character set to be
utf-8 which prevents the text from not being displayed correctly in
the browser. This matches the .NET Core MVC project templates and also
the non-.NET Core MVC project templates in Visual Studio.
=> [AspNet] Fix MVC project template html page character set

main/src/addins/AspNet/Templates/MvcCommon/_Layout.cshtml
Fixed bug #57640 - ASP.NET MVC default profile, showed Chinese will
be garbled
https://bugzilla.xamarin.com/show_bug.cgi?id=57640
Added a meta tag to the layout page specifying the character set to be
utf-8 which prevents the text from not being displayed correctly in
the browser. This matches the .NET Core MVC project templates and also
the non-.NET Core MVC project templates in Visual Studio.
=> [d15-4][AspNet] Fix MVC project template html page character set

main/src/core/MonoDevelop.Core/MonoDevelop.Core/StringInternPool.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Core/StringTable.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/DefaultMSBuildEngine.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildEngineManager.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildEvaluationContext.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProject.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildWhitespace.cs
The normal instance methods are really good only for serial code. If parallel code uses it, it's better to use the thread safe global cache rather than the local cache.
Fixes some abnormal behaviour in unlucky scenario where lock contention in bg
can reach 20s for evaluating Main.sln
=> [Core] Expose shared cache methods to StringInternPool.

main/external/fsharpbinding/MonoDevelop.FSharp.Gui/MonoDevelop.FSharp.Gui.csproj
This project wasn't signed and StrongNamer was invoked for this project causing a double-write (an occasional build race condition), also breaking build incrementality.
=> Sign MonoDevelop.FSharp.Gui.

main/external/fsharpbinding/MonoDevelop.FSharpi.Service/MonoDevelop.FSharpInteractive.Service.fsproj
The F# binding project already copies these files to the destination. Avoid copying them here so that we don't have a double-write.
=> Avoid copying some F# dependencies twice.

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Refactoring/CSharpFindReferencesProvider.cs, main/tests/UnitTests/MonoDevelop.CSharpBinding.Refactoring/CSharpFindReferencesProviderTests.cs, main/tests/UnitTests/UnitTests.csproj
fails leaving an error in the log'
The bug was in the find all references command. Not in the find
references command.
=> Fixed 'Bug 58060 - [VSFeedback Ticket] #454760 - "Find References"

main/external/fsharpbinding/MonoDevelop.FSharpBinding/MonoDevelop.FSharp.fsproj, main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.csproj, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.csproj, main/src/addins/MonoDevelop.Packaging/PostBuild.proj, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
This helps avoid unnecessary copy operations during the build.
=> SkipUnchangedFiles="true" when copying files in MSBuild.

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.SharedAssetsProjects/SharedAssetsProject.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/OperationContext.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectExtension.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs, main/tests/UnitTests/MonoDevelop.Projects/ProjectTests.cs
The FastCheckNeedsBuild method now takes an OperationContext as argument.
This is necessary because when building a project, OperationContext can
contain custom msbuild properties that can have an effect on the build
(for example, a build can be specific to the target device currently selected
in the IDE).
OnFastCheckNeedsBuild now keeps track of the global msbuild properties
specified in the context, and uses them when checking for changes.
=> Fix issue in FastCheckNeedsBuild

main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
Move most Roslyn references to MD.Ide.
Remove some unneeded references from MD.Core.
Sort references in MD.Core and MD.Ide.
Remove ProductVersion and SchemaVersion which are never useful.
=> Cleanup MD.Core and MD.Ide references.

main/external/fsharpbinding/paket.lock
StrongNamer 0.0.6 has a fix that avoids rewriting a signed binary if it already exists and the Mvid matches.
=> Update to StrongNamer 0.0.6 that supports better build incrementality.

main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/TextLinkEditMode.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/GruvboxStyle.json, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/MonokaiStyle.json, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/NightshadeStyle.json, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/OblivionStyle.json, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/SolarizedDarkStyle.json, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/SolarizedLightStyle.json
mode'
Some highlighting styles were wrong in that highlighting case. Dark &
Light mode are well supported - but some of the lesser used ones
needed attention.
Fixed a minor drawing bug in text link mode as well.
=> Fixed 'Bug 57303 - Renaming makes the text unreadable while in dark

main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorWidget.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/SdiWorkspaceWindow.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs
Now that the whole of the shell UI can be focused, lots of controls like to
steal the keyboard focus meaning that when we expect to be able to type in the
editor, we often can't. To fix this, when opening a new document, we have the
editor grab focus.
=> [A11y] Fix the keyboard focus on the editor

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/KeyBindingSet.cs, main/tests/UnitTests/MonoDevelop.Ide/KeyBindingSetTests.cs, main/tests/UnitTests/UnitTests.csproj
* fix parent selection for compare
* skip unchanged and empty bindings in schemes
(fixes bug #57111)
=> [57111][Ide] Fix KeyBindingSet compare with parent Pt. 2

main/external/fsharpbinding/MonoDevelop.FSharpBinding/MonoDevelop.FSharp.fsproj, main/external/fsharpbinding/paket.lock, main/src/addins/CSharpBinding/CSharpBinding.csproj, main/src/addins/CSharpBinding/packages.config, main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj, main/src/core/MonoDevelop.Core/packages.config
This makes our build more deterministic, without different versions of System.ValueTuple.dll overwriting each other in the output directory.
=> Unify most System.ValueTuple references to 4.3.1.

main/src/core/MonoDevelop.Ide/ExtensionModel/Commands.addin.xml, main/src/core/MonoDevelop.Ide/ExtensionModel/MainMenu.addin.xml, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/HelpCommands.cs
Adding a mark in the log can be helpful to find a point in a busy log. Mark the
log before doing an action, and then it can be easier to work out when you
started the action
=> Adds a Diagnostics menu item to put a mark in the log.

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Features/Completion/ContextHandler/RoslynRecommendationsCompletionContextHandler.cs, main/tests/MonoDevelop.CSharpBinding.Tests/Features/CodeCompletion/PortedRoslynTests/SymbolCompletionHandlerTests.cs
This is a common scenario for Unity developers, as all attributes defined in Unity's API are not suffixed with `Attribute`.
=> [CSharp] Fix completion for attributes without Attribute suffix

main/external/fsharpbinding/MonoDevelop.FSharp.Shared/MonoDevelop.FSharp.Shared.fsproj, main/external/fsharpbinding/MonoDevelop.FSharp.Tests/MonoDevelop.FSharp.Tests.fsproj, main/external/fsharpbinding/MonoDevelop.FSharpBinding/MonoDevelop.FSharp.fsproj, main/external/fsharpbinding/MonoDevelop.FSharpi.Service/MonoDevelop.FSharpInteractive.Service.fsproj
FCS no longer ships FSharp.Compiler.Service.MSBuild.v12. The references should have been removed on the last compiler bump.
=> Remove FSharp.Compiler.Service.MSBuild.v12 reference

main/src/core/MonoDevelop.Startup/MonoDevelop.Startup.csproj, main/src/core/MonoDevelop.Startup/packages.config
The new version of the tool support incrementality, so if the binary is already patched, it won't touch it so the timestamp will remain the same and won't invalidate dependencies unnecessarily.
=> Update to LargeAddressAware 1.0.1 which supports incrementality.

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/Formats/OldFormat.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/syntaxes/CSharp/C#.sublime-syntax
theme'
Didn't think there were themes that used the old keyword colors.
They're a direct inheritance of SharpDevelop :). However there isn't
any reason we don't support that in the textmate theme - we still
control that.
=> Fixed 'Bug 58219 - Keyword(Access) not working in custom text color

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Gui/AddPackagesDialog.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Gui/PackageCellView.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageSearchResultViewModel.cs
Fixed bug #58238 - Searching for Microsoft.AspNet.WebApi.Client in
the Add Packages dialog terminates IDE
https://bugzilla.xamarin.com/show_bug.cgi?id=58238
With the NuGet v3 package source https://api.nuget.org/v3/index.json
enabled searching for Microsoft.AspNet.WebApi.Client would result in
the IDE terminating when an attempt was made to display the results.
The crash was in Pango when it attempts to determine the size of
the package title displayed in the search results. If the package
title contained Chinese characters this would throw an exception:
Illegal byte sequence encounted in the input.
at (wrapper managed-to-native) Pango.Layout:pango_layout_get_pixel_size (intptr,int&,int&)
Then when trying to use Pango again to determine the size of the text
would result in the IDE …
=> [NuGet] Fix crash when displaying Chinese characters in dialog

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Gui/AddPackagesDialog.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Gui/PackageCellView.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageSearchResultViewModel.cs
Fixed bug #58238 - Searching for Microsoft.AspNet.WebApi.Client in
the Add Packages dialog terminates IDE
https://bugzilla.xamarin.com/show_bug.cgi?id=58238
With the NuGet v3 package source https://api.nuget.org/v3/index.json
enabled searching for Microsoft.AspNet.WebApi.Client would result in
the IDE terminating when an attempt was made to display the results.
The crash was in Pango when it attempts to determine the size of
the package title displayed in the search results. If the package
title contained Chinese characters this would throw an exception:
Illegal byte sequence encounted in the input.
at (wrapper managed-to-native) Pango.Layout:pango_layout_get_pixel_size (intptr,int&,int&)
Then when trying to use Pango again to determine the size of the text
would result in the IDE …
=> [d15-4][NuGet] Fix crash when displaying Chinese characters in dialog

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads/ErrorListPad.cs
The error pad is constantly resizing the description column, which causes it to recalculate all the column widths,
update all the texts and strings.
This is playing havoc with the accessibility, even with only two errors shown
Instead of resizing the description column as needed, just set it to a good default width
=> Stop the error pad resizing column widths constantly

main/src/addins/MonoDevelop.Packaging/MonoDevelop.Packaging/MSBuildGlobalPropertyProvider.cs
Fixed bug #58244 - Error loading project - NuGetAuthoringPath item
already added
https://bugzilla.xamarin.com/show_bug.cgi?id=58244
Prevent the MSBuild property NuGetAuthoringPath being added twice
to the same dictionary by making the property provider thread safe.
=> [Packaging] Make msbuild property provider thread safe

main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/BreakpointPropertiesDialog.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components/InformationPopoverWidget.cs
The conversion from Xwt -> Gtk using ToGtkWidget () is awkward until we have the Xwt accessibility work completed
=> [A11y] Make the New Breakpoint dialog accessible

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.NodeBuilders/DotNetCoreProjectNodeBuilderExtension.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests.csproj, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreSdkTests.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreNotInstalledDialog.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdk.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/TargetFrameworkExtensions.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/TargetFrameworkMonikerExtensions.cs
Fixed bug #58271 - Handle .NET Core 2.0 SDK not being installed when
opening a .NET Core 2.0 project
https://bugzilla.xamarin.com/show_bug.cgi?id=58271
If a .NET Core 2.0 or .NET Standard 2.0 project is opened and .NET Core
2.0 SDK is not installed then a dialog is shown allowing the user to
download and install it. The project in the Solution window will show
an error icon with the same information about .NET Core 2.0 not being
installed. Currently the download link goes to the .NET Core 2.0
preview page - https://www.microsoft.com/net/core/preview#macos - the
url is shorted and can be redirected later without changing the code.
=> [DotNetCore] Handle .NET Core 2.0 not being installed

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectReloadMonitor.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Commands/RestorePackagesInProjectHandler.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.Helpers/FakeMonoDevelopBuildIntegratedRestorer.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.Helpers/FakeNuGetProject.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.Helpers/FakeSolutionManager.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.csproj, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/DotNetCoreNuGetProjectTests.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/DotNetProjectExtensionsTests.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/RestoreNuGetPackagesInNuGetIntegratedProjectTests.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.csproj, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/DotNetCoreNuGetProject.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/DotNetProjectExtensions.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/IBuildIntegratedNuGetProject.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/IMonoDevelopBuildIntegratedRestorer.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/MonoDevelopBuildIntegratedRestorer.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageReferenceNuGetProject.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/ProjectJsonBuildIntegratedProjectSystem.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/RestoreNuGetPackagesInNuGetIntegratedProject.cs
Fixed bug #58009 - Transitive assembly references not available until
project reloaded
https://bugzilla.xamarin.com/show_bug.cgi?id=58009
With a solution containing three .NET Standard projects: LibC
references LibB which references LibA. If the Newtonsoft.Json NuGet
package was installed into LibA the types from this NuGet packages
are not available in LibB or LibC until the solution is closed and
re-opened again. Closing and re-opening the solution refreshes the
reference information for the type system. To fix this when a NuGet
package is installed into a .NET Core project the projects that
reference this project have their reference information refreshed
by calling NotifyModified ("References") which causes the type system
to get the reference information again from MSBuild. Types …
=> [NuGet] Transitive assembly references not available until solution reloaded

main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpPathExtension.fs
Fixes NRE
```
ERROR [2017-07-21 15:33:12Z]: An unhandled exception has occured. Terminating Visual Studio? False
at <StartupCode$FSharpBinding>.$FSharpPathExtension+clo@55-25.Invoke (System.EventHandler eventDelegate) [0x00000] in /Users/builder/data/lanes/4349/cb33ab8f/source/monodevelop/main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpPathExtension.fs:55 
at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers+CreateEvent@341[TDelegate,TArgs].Microsoft-FSharp-Control-IDelegateEvent`1-RemoveHandler (TDelegate handler) [0x00000] in /Users/builder/data/lanes/4992/mono-mac-sdk/external/bockbuild/builds/fsharp-fsharp-991186f/src/fsharp/FSharp.Core/seqcore.fs:346 
at …
```
=> Fix NRE in FSharpPathExtension reported by @7sharp9

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/NewProjectController.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/TemplateImageProvider.cs, main/tests/Ide.Tests/Ide.Tests.csproj, main/tests/Ide.Tests/MonoDevelop.Ide.Projects/DummyNewProjectDialogBackend.cs, main/tests/Ide.Tests/MonoDevelop.Ide.Projects/NewProjectDialogTests.cs, main/tests/Ide.Tests/MonoDevelop.Ide.Projects/TestableNewProjectDialogController.cs
Fixed bug #57934 - When adding project to solution "Create a project
directory within the solution directory." checkbox is not respected
https://bugzilla.xamarin.com/show_bug.cgi?id=57934
To reproduce the original bug:
1. Create a new solution using the New Project dialog and ensure
the Create a project directory within the solution directory is
unchecked.
2. Add a new project to the existing solution.
3. The final page of the New Project dialog would have the Create
a project directory within the solution directory check box checked
and disabled. However the project would not be created in its own
directory.
=> [Ide] Fix project not created in own directory with New Project dialog

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectReloadMonitor.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Commands/RestorePackagesInProjectHandler.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.Helpers/FakeMonoDevelopBuildIntegratedRestorer.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.Helpers/FakeNuGetProject.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.Helpers/FakeSolutionManager.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.csproj, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/DotNetCoreNuGetProjectTests.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/DotNetProjectExtensionsTests.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/RestoreNuGetPackagesInNuGetIntegratedProjectTests.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.csproj, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/DotNetCoreNuGetProject.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/DotNetProjectExtensions.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/IBuildIntegratedNuGetProject.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/IMonoDevelopBuildIntegratedRestorer.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/MonoDevelopBuildIntegratedRestorer.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageReferenceNuGetProject.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/ProjectJsonBuildIntegratedProjectSystem.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/RestoreNuGetPackagesInNuGetIntegratedProject.cs
Fixed bug #58009 - Transitive assembly references not available until
project reloaded
https://bugzilla.xamarin.com/show_bug.cgi?id=58009
With a solution containing three .NET Standard projects: LibC
references LibB which references LibA. If the Newtonsoft.Json NuGet
package was installed into LibA the types from this NuGet packages
are not available in LibB or LibC until the solution is closed and
re-opened again. Closing and re-opening the solution refreshes the
reference information for the type system. To fix this when a NuGet
package is installed into a .NET Core project the projects that
reference this project have their reference information refreshed
by calling NotifyModified ("References") which causes the type system
to get the reference information again from MSBuild. Types …
=> [d15-4][NuGet] Transitive assembly references not available until solution reloaded

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.NodeBuilders/DotNetCoreProjectNodeBuilderExtension.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests.csproj, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreSdkTests.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreNotInstalledDialog.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdk.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/TargetFrameworkExtensions.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/TargetFrameworkMonikerExtensions.cs
Fixed bug #58271 - Handle .NET Core 2.0 SDK not being installed when
opening a .NET Core 2.0 project
https://bugzilla.xamarin.com/show_bug.cgi?id=58271
If a .NET Core 2.0 or .NET Standard 2.0 project is opened and .NET Core
2.0 SDK is not installed then a dialog is shown allowing the user to
download and install it. The project in the Solution window will show
an error icon with the same information about .NET Core 2.0 not being
installed. Currently the download link goes to the .NET Core 2.0
preview page - https://www.microsoft.com/net/core/preview#macos - the
url is shorted and can be redirected later without changing the code.
=> [d15-4][DotNetCore] Handle .NET Core 2.0 not being installed

main/src/addins/TextTemplating/MonoDevelop.TextTemplating/Templates/T4PreprocessedTemplateCSharp.xft.xml, main/src/addins/TextTemplating/MonoDevelop.TextTemplating/Templates/T4TemplateCSharp.xft.xml
Fixed bug #56625 - T4 editor breaks - no syntax highlighting and
typing issues
https://bugzilla.xamarin.com/show_bug.cgi?id=56625
Creating a new T4 file from the template would result in the file
having duplicate byte order marks at the start. Deleting characters
from the file in the text editor would then have odd behaviour where
some of the characters were not removed. The problem was that the file
templates had a byte order mark in the CDATA section which was causing
the duplicate byte order marks in the created .tt file.
=> [T4] Fix duplicate byte order marks in new T4 file.

main/src/addins/MonoDevelop.Packaging/MonoDevelop.Packaging/MSBuildGlobalPropertyProvider.cs
Fixed bug #58244 - Error loading project - NuGetAuthoringPath item
already added
https://bugzilla.xamarin.com/show_bug.cgi?id=58244
Prevent the MSBuild property NuGetAuthoringPath being added twice
to the same dictionary by making the property provider thread safe.
=> [d15-4][Packaging] Make msbuild property provider thread safe

main/src/addins/MonoDevelop.AzureFunctions/GenerateRuntimeImports.targets
The prior fix to generate the imports automatically works fine if the files are already present. Unfortunately I forgot that the download tasks happen after the build. This temporarily fixes this issue for 15-4 (master and onwards shouldn't need any of this).
=> [Azure Functions] Fix build by performing the download and copy of nugets at the same time as generating the imports.

main/external/fsharpbinding/MonoDevelop.FSharp.Tests/TemplateTests.fs
The portable class library project is being tested already. The shared
project needs other parameters configured so it is created instead of
the portable class library project.
=> [F#] Add test for Xamarin.Forms template using a shared project

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/SolutionTemplate.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/TemplatingService.cs, main/tests/UnitTests/MonoDevelop.Ide.Templates/ProjectTemplateCategorizerTests.cs
Fixed bug #58412 - Unable to create CocoaApp from recent templates
https://bugzilla.xamarin.com/show_bug.cgi?id=58412
After creating a CocoaApp (Mac - App - General) that targets
Mavericks if the CocoaApp project template was selected from the
recent projects list in the New Project dialog the project would not
be created if a later Mac OS was selected. In the IDE log an error
would be reported:
No template found matching condition 'Yosemite=false'.
The problem was that the selected project template was part of a
group but the group was not selected. When a different Mac OS was
selected for the new project the condition applied would result in
no template being found.
Also fixed duplicate recent project template for grouped templates:
Creating a CocoaApp project that targeted Mavericks …
=> [Ide] Fix failure to create CocoaApp project from New Project dialog

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreSdkTests.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdk.cs
Fixed bug #58439 - SDK Style projects targeting .NET Core 4.6.1 fails
to build even when .NET Core 2.0 preview2 is installed
https://bugzilla.xamarin.com/show_bug.cgi?id=58439
Building a SDK style project that targeted the .NET Framework would
fail to build returning an error about the .NET Core SDK not being
installed even though it was installed. The project would also have
an error icon in the Solution window with an error message about
the .NET Core SDK not being installed.
The problem was that the check added to test for the .NET Core 2.0
SDK being installed for .NET Core 2.0 projects was indicating that
the .NET Framework was not supported. This resulted in the error
about the .NET Core SDK not being installed being reported. This
check has been changed so if the project's target …
=> [DotNetCore] Fix build error for SDK projects targeting .NET Framework

main/src/addins/TextTemplating/MonoDevelop.TextTemplating/Templates/T4PreprocessedTemplateCSharp.xft.xml, main/src/addins/TextTemplating/MonoDevelop.TextTemplating/Templates/T4TemplateCSharp.xft.xml
Fixed bug #56625 - T4 editor breaks - no syntax highlighting and
typing issues
https://bugzilla.xamarin.com/show_bug.cgi?id=56625
Creating a new T4 file from the template would result in the file
having duplicate byte order marks at the start. Deleting characters
from the file in the text editor would then have odd behaviour where
some of the characters were not removed. The problem was that the file
templates had a byte order mark in the CDATA section which was causing
the duplicate byte order marks in the created .tt file.
=> [d15-4][T4] Fix duplicate byte order marks in new T4 file.

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/NewProjectController.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/TemplateImageProvider.cs, main/tests/Ide.Tests/Ide.Tests.csproj, main/tests/Ide.Tests/MonoDevelop.Ide.Projects/DummyNewProjectDialogBackend.cs, main/tests/Ide.Tests/MonoDevelop.Ide.Projects/NewProjectDialogTests.cs, main/tests/Ide.Tests/MonoDevelop.Ide.Projects/TestableNewProjectDialogController.cs
Fixed bug #57934 - When adding project to solution "Create a project
directory within the solution directory." checkbox is not respected
https://bugzilla.xamarin.com/show_bug.cgi?id=57934
To reproduce the original bug:
1. Create a new solution using the New Project dialog and ensure
the Create a project directory within the solution directory is
unchecked.
2. Add a new project to the existing solution.
3. The final page of the New Project dialog would have the Create
a project directory within the solution directory check box checked
and disabled. However the project would not be created in its own
directory.
=> [d15-4][Ide] Fix project not created in own directory with New Project dialog 

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/NewProjectController.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/SolutionTemplate.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/TemplatingService.cs, main/tests/UnitTests/MonoDevelop.Ide.Templates/ProjectTemplateCategorizerTests.cs
Fixed bug #58412 - Unable to create CocoaApp from recent templates
https://bugzilla.xamarin.com/show_bug.cgi?id=58412
After creating a CocoaApp (Mac - App - General) that targets
Mavericks if the CocoaApp project template was selected from the
recent projects list in the New Project dialog the project would not
be created if a later Mac OS was selected. In the IDE log an error
would be reported:
No template found matching condition 'Yosemite=false'.
The problem was that the selected project template was part of a
group but the group was not selected. When a different Mac OS was
selected for the new project the condition applied would result in
no template being found.
Also fixed duplicate recent project template for grouped templates:
Creating a CocoaApp project that targeted Mavericks …
=> [d15-4][Ide] Fix failure to create CocoaApp project from New Project dialog

main/external/fsharpbinding/MonoDevelop.FSharp.Tests/ProjectCracking.fs, main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/CompilerArguments.fs
Removed passing all package references to the compiler options.
This fixes the F# unit tests for d15-4 //cc: @manish . It's also a real error - There is a warning squiggle in the editor for the F# tvos template.
=> [d15-4] F# Fix unit tests

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.cs
Fixed bug #58392 - Blank Forms App Template Uses C# Language Instead
of Previous Selection
https://bugzilla.xamarin.com/show_bug.cgi?id=58392
The language button selector was not updated when a recently used
project template was selected on opening the New Project dialog. This
resulted in the selected language in the UI not being the language
used when creating the project. Now the language selector is updated
if the language is changed when a recently used project template is
selected.
=> [Ide] Ensure New Project dialog language selector matches language

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreSdkTests.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdk.cs
Fixed bug #58439 - SDK Style projects targeting .NET Core 4.6.1 fails
to build even when .NET Core 2.0 preview2 is installed
https://bugzilla.xamarin.com/show_bug.cgi?id=58439
Building a SDK style project that targeted the .NET Framework would
fail to build returning an error about the .NET Core SDK not being
installed even though it was installed. The project would also have
an error icon in the Solution window with an error message about
the .NET Core SDK not being installed.
The problem was that the check added to test for the .NET Core 2.0
SDK being installed for .NET Core 2.0 projects was indicating that
the .NET Framework was not supported. This resulted in the error
about the .NET Core SDK not being installed being reported. This
check has been changed so if the project's target …
=> [d15-4][DotNetCore] Fix build error for SDK projects targeting .NET Framework

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.cs
Fixed bug #58392 - Blank Forms App Template Uses C# Language Instead
of Previous Selection
https://bugzilla.xamarin.com/show_bug.cgi?id=58392
The language button selector was not updated when a recently used
project template was selected on opening the New Project dialog. This
resulted in the selected language in the UI not being the language
used when creating the project. Now the language selector is updated
if the language is changed when a recently used project template is
selected.
=> [d15-4][Ide] Ensure New Project dialog language selector matches language

main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/LanguageService.fs
Remove workaround that was put in place for a previous version of the
compiler. This allows project references to work. Fixes #57061
=> [F#] Fixes #57061

main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/DebugValueWindow.cs
Fixed value of 10 was set before retina displays, hence making it 20 fixes problem of cut off popup at edge of screen
Before:
After:
=> [Debugger] Fix debug value popup cut off at edge of screen

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Templating/DotNetCoreProjectTemplateWizard.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.UnitTesting/DotNetCoreTestPlatformAdapter.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.csproj, main/src/addins/MonoDevelop.DotNetCore/Properties/MonoDevelop.DotNetCore.addin.xml, main/src/addins/MonoDevelop.DotNetCore/packages.config
- Allow .NET Core 2.0 project templates to be enabled for other .NET Core SDK versions being installed. Previously only .NET Core 2.0 preview 2 being installed would enable the project templates.
- Updated the .NET Core 2.0 project templates to match those included with preview 3.
- Fix IDE being terminated after debugging .NET Core unit tests with latest .NET Core 2.0 SDK.
=> [d15-3][DotNetCore] Support other .NET Core 2.0 SDK versions

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpTextPasteHandler.cs
It's just a guess what could go wrong. The new text is now formatted
before it's inserted in the text - not afterwards. I assume that there
may be a race when formatting it with the on the fly formatter
afterwards.
I couldn't reproduce the reported bug.
=> Fixed 'Bug 58139 - Paste corrupts inserted text'

main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/ExtensibleTextEditor.cs
The android designer uses source editor view directly - in that case
the WorkbenchWindow seems not to be set. This change makes the
template insertion more robust against that scenario.
=> Fixed 'Bug 58286 - Code Snippet won't expand'

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpTextPasteHandler.cs
code option to "Use default settings from 'Text file'"'
=> Fixed 'Bug 56288 - Spaces converted to tabs on paste with C# source

main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs, main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs, main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/TextDocument.cs
This was caused by some old code trying to manage the addition/removal
of line markers. Was a left over of times where line markers weren't
stored in segment trees. I removed the old handling code it was mostly
unused anyways.
=> Fixed 'Bug 53583 - Using IExtendingLineMarker causes redraw issues'

main/src/addins/Xml/Editor/BaseXmlEditorExtension.cs
There is no real need for using policies here - the editor options are
already set according to the policies.
=> Fixed 'Bug 58570 - cut & paste always inserts tabs in xml'.

main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
On lines with fold markers the selection drawing was wrong - there was
a gap after the last fold marker because that code measured the whole
last line instead of just the remaining part to be drawn.
=> [TextEditor] Fix selection drawing bug.

main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.csproj, main/src/addins/MonoDevelop.AspNetCore/Properties/MonoDevelop.AspNetCore.addin.xml, main/src/addins/MonoDevelop.AspNetCore/packages.config, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Templating/DotNetCoreProjectTemplateWizard.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.UnitTesting/DotNetCoreTestPlatformAdapter.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.csproj, main/src/addins/MonoDevelop.DotNetCore/Properties/MonoDevelop.DotNetCore.addin.xml, main/src/addins/MonoDevelop.DotNetCore/packages.config
- Allow .NET Core 2.0 project templates to be enabled for other .NET Core SDK versions being installed. Previously only .NET Core 2.0 preview 2 being installed would enable the project templates.
- Updated the .NET Core 2.0 project templates to match those included with preview 3.
- Fix IDE being terminated after debugging .NET Core unit tests with latest .NET Core 2.0 SDK.
=> [d15-4][DotNetCore] Support other .NET Core 2.0 SDK versions

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Highlighting/CSharpSyntaxMode.cs
Declaration" key not working in custom text color theme'
Makes not really sense to check if the colors are equal - checking if
it exists is enough. If colors are equal then there are no visual
differences.
=> Fixed 'Bug 58576 - [VSFeedback Ticket] #438331 - "User Property

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/NSObjectResult.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AppQuery.cs
For Mac UI elements, we use `SubViews` to traverse the hierarchy, but this model breaks down when we have to handle special butterflies like `NSSegmentedControl` which is actually just one view with multiple segments.
1) Added support to generate `NSObjectResult` for each segment of `NSSegmentedControl`
2) Match using `Text` Operation and it matches using value fetched from `NSSegmentedControl. GetLabel `
3) For the `Property` operation we have to handle `NSSegmentedControl` specially by matching `NSSegmentedControl.IsEnabled ` for properties of - `Visible` and `Sensitive`
=> [AutoTest] Added support for NSSegmentedControl

main/external/fsharpbinding/MonoDevelop.FSharp.Tests/TemplateTests.fs
Was investigating various version of mono to make sure that mdb files are emitted, so modified the template test.
=> Quick test to ensure that mdb files are emitted

version.config
Now that we are finalising 15.3 builds, we can remove the preview branding.
=> 15.3 - remove "Preview" from builds

main/src/addins/MonoDevelop.AspNetCore/Properties/MonoDevelop.AspNetCore.addin.xml
Fixed bug #58608 - Duplicate "ASP.NET Core Web App" shown in
"New Project" dialog
https://bugzilla.xamarin.com/show_bug.cgi?id=58608
The default name was changed in the latest .NET Core project templates
and did not include any mention about Razor pages being used.
=> [d15-4][AspNetCore] Fix Razor Pages project template name

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/RecentFileStorage.cs, main/tests/UnitTests/MonoDevelop.Ide.Templates/ProjectTemplateCategorizerTests.cs
The RecentTemplates_TwoTemplatesInGroupDifferentLanguage_TreatedAsDifferentRecentTemplate test occasionally fails to find any recent templates. To make the recent template tests more robust the list of templates is retried several times before failing. This handles the case where the RecentFileStorage's constructor occasionally clears out the cached in-memory list whilst the test is
adding new items. The in-memory list is eventually updated when the file is saved but this can take some time to happen since the save is delayed.
Also a different file name is used with the recent file storage for each unit test to minimize the chance of a sharing violation from occuring.
Also added some logging to the RecentFileStorage class if the file save fails.
=> [Ide] Make recent template tests more robust

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/DefaultSourceEditorOptions.cs
with option-arrow isn't Mac-like'
It's fixed by changing the defaults.
=> Fixed 'Bug 58255 - [VSFeedback Ticket] #438405 - Navigating XAML files

main/src/addins/VersionControl/MonoDevelop.VersionControl.Git.Tests/BaseRepositoryTests.cs, main/src/addins/VersionControl/MonoDevelop.VersionControl.Git.Tests/MonoDevelop.VersionControl.Git.Tests.csproj, main/src/addins/VersionControl/MonoDevelop.VersionControl.Subversion.Tests/MonoDevelop.VersionControl.Subversion.Tests.csproj, main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/BlameWidget.cs, main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/LogWidget.cs, main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.csproj, main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/Revision.cs, main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/RevisionHelpers.cs, main/src/addins/VersionControl/Subversion.Win32.Tests/VersionControl.Subversion.Win32.Tests.csproj
The code retains old broken functionality, commented out expected values are in unit tests.
Consider fixing this if Changelog style commits are still a thing. For now, just optimize it
by removing the usage of the TextEditor
Avoid creating a text editor and doing text manipulation there and rely on simple string parsing
Bug 56965 - Version control log filtering hangs IDE
=> [VCS] Optimize log widget rendering

main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs
files after leaving VSfM open for extended period; affected file
content is corrupt'
=> Fixed 'Bug 58077 - [VSFeedback Ticket] #461622 - Unable to save some

main/src/addins/MonoDevelop.AzureFunctions/Properties/Manifest.addin.xml
Significantly reduces the amount of assemblies being scanned.
=> Exclude Azure libs from scanning

main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.csproj, main/src/addins/MonoDevelop.AspNetCore/Properties/MonoDevelop.AspNetCore.addin.xml, main/src/addins/MonoDevelop.AspNetCore/packages.config, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Templating/DotNetCoreProjectTemplateWizard.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.UnitTesting/DotNetCoreTestPlatformAdapter.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.csproj, main/src/addins/MonoDevelop.DotNetCore/Properties/MonoDevelop.DotNetCore.addin.xml, main/src/addins/MonoDevelop.DotNetCore/packages.config
- Allow .NET Core 2.0 project templates to be enabled for other .NET Core SDK versions being installed. Previously only .NET Core 2.0 preview 2 being installed would enable the project templates.
- Updated the .NET Core 2.0 project templates to match those included with preview 3.
- Fix IDE being terminated after debugging .NET Core unit tests with latest .NET Core 2.0 SDK.
=> [DotNetCore] Support other .NET Core 2.0 SDK versions

main/src/addins/MonoDevelop.AspNetCore/Properties/MonoDevelop.AspNetCore.addin.xml, main/src/addins/MonoDevelop.DotNetCore/Properties/MonoDevelop.DotNetCore.addin.xml
Some of the .NET Core project template names were not being
translated in the New Project dialog. This fixes the translation of:
- xUnit Test Project
- ASP.NET Core Empty
- ASP.NET Core Web App
Not currently being translated:
- ASP.NET Core Web API
- ASP.NET Core Web App (Razor Pages)
=> [DotNetCore] Fix project template names not being translated

main/external/fsharpbinding/MonoDevelop.FSharp.Tests/ProjectTests.fs, main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpProject.fs
Sometimes when a file is added to the project, it doesn't yet exist
in the MSBuildItems. Fix by checking for Project Files that don't yet
exist in MSBuildItems. Fixes #57689
=> [F#] Fix a race condition when merging ItemGroups

main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Tabstrip.cs
(fixes bug #54901)
(cherry picked from commit a6f5c0e724e946a92d9cd5aec0900e7960a384d9)
=> [Ide] Fix document subview tab wrapping

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionFolder.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.ExternalTools/ExternalToolPanel.cs, main/tests/UnitTests/MonoDevelop.Projects/StringTagTests.cs
Fixed bug #58735 - Unable to start .exe from VSMac as External Tool
https://bugzilla.xamarin.com/show_bug.cgi?id=58735
When a solution is selected in the Solution window then running an
external tool would fail. With a project selected the external tool
would run successfully.
```
Error while executing command: Tool List
System.InvalidOperationException: The constructor of type MonoDevelop.Projects.SolutionFolder must call Initialize(this)
at MonoDevelop.Projects.WorkspaceObject.AssertExtensionChainCreated ()  in MonoDevelop.Core/MonoDevelop.Projects/WorkspaceObject.cs:331
at MonoDevelop.Projects.WorkspaceObject.get_ItemExtension ()  in MonoDevelop.Core/MonoDevelop.Projects/WorkspaceObject.cs:346
at MonoDevelop.Projects.WorkspaceObject.GetStringTagModel …
```
=> [Ide] Fix external tool failing to run when solution selected

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/ProjectPackageReferenceTests.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.csproj, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/ProjectPackageReference.cs, main/src/addins/MonoDevelop.UnitTesting.NUnit/AddinInfo.cs, main/src/addins/MonoDevelop.UnitTesting.NUnit/MonoDevelop.UnitTesting.NUnit.csproj, main/src/addins/MonoDevelop.UnitTesting.NUnit/MonoDevelop.UnitTesting.NUnit/NUnitProjectTestSuite.cs
This needed to use some (currently) internal types of MonoDevelop.PackageManagement for which a temporary InternalsVisibleTo was added.
=> [NUnit] Recognize unit-test projects when using PackageReference NuGet references instead of packages.config

main/src/addins/CSharpBinding/MonoDevelop.CSharp/PathedDocumentTextEditorExtension.cs
declaration'
During the Editor.RunWhenRealized the if wasn't put into the delegate
- however the extension chain could change prior to editor ui
creation.
=> Fixed 'Bug 58715 - Text editor shows no text when using go to

main/src/addins/MonoDevelop.AspNetCore/Properties/MonoDevelop.AspNetCore.addin.xml, main/src/addins/MonoDevelop.DotNetCore/Properties/MonoDevelop.DotNetCore.addin.xml
Some of the .NET Core project template names were not being
translated in the New Project dialog. This fixes the translation of:
- xUnit Test Project
- ASP.NET Core Empty
- ASP.NET Core Web App
Not currently being translated:
- ASP.NET Core Web API
- ASP.NET Core Web App (Razor Pages)
=> [d15-4][DotNetCore] Fix project template names not being translated

main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/GutterMargin.cs, main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs, main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs, main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/TextMarker/DebugTextMarker.cs
+ Turned on highlighting
+ The current line marker is now displayed in the empty space left of
the line numbers and not on top of the icon marker.
=> Fixed 'Bug 58488 - Breakpoint highlighting not visible'

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild.Conditions/ConditionParser.cs, main/tests/UnitTests/MonoDevelop.Projects/MSBuildProjectTests.cs, main/tests/test-projects/msbuild-project-test/test.csproj
Fixed bug #58644 - Condition parsing issue with function calls
https://bugzilla.xamarin.com/show_bug.cgi?id=58644
.NET Core 2.0 SDK uses conditions that pass properties to the
Exists function without single quotes. These are now supported:
<PropertyGroup Condition="Exists($(FileName))">
Previously the condition would only be evaluated correctly if it had
single quotes around the property passed to the Exists function:
<PropertyGroup Condition="Exists('$(FileName)')">
=> [Core] Support parsing MSBuild Exists condition with unquoted property

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbarController.cs
Moved selection of target device from SelectActiveConfiguration to after target devices are actually set
=> Bug 58164 - Device/Simulator list is disabled upon creation of new iOS project

main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/AssemblyBrowserWidget.cs
placed incorrectly'
Was caused by the tabs -> spaces change. NRefactory calculates offsets
with tabs so the offset of the link marker was off in indented lines.
=> Fixed 'Bug 58871 - Links to navigate to types in assembly browser are

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild.Conditions/ConditionParser.cs, main/tests/UnitTests/MonoDevelop.Projects/MSBuildProjectTests.cs, main/tests/test-projects/msbuild-project-test/test.csproj
Fixed bug #58644 - Condition parsing issue with function calls
https://bugzilla.xamarin.com/show_bug.cgi?id=58644
.NET Core 2.0 SDK uses conditions that pass properties to the
Exists function without single quotes. These are now supported:
<PropertyGroup Condition="Exists($(FileName))">
Previously the condition would only be evaluated correctly if it had
single quotes around the property passed to the Exists function:
<PropertyGroup Condition="Exists('$(FileName)')">
=> [d15-4][Core] Support parsing MSBuild Exists condition with unquoted property

main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/MDMenu.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/MDMenuHeaderItem.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/MDMenuItem.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
This PR restores some Menu features which got lost with https://github.com/mono/monodevelop/commit/c54c8434fb43588c9be621b8f3aa7c607723f020
This includes:
* Disabled Tooltips
* Menu icons
* Section (Separator items) headers
=> [Mac] Restore lost main menu features/fixes

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.csproj, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/ImportedPackageReferenceProjectTests.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/PackageReferenceNuGetProjectTests.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageReferenceNuGetProject.cs
Fixed bug #58842 - Support imported PackageReferences
https://bugzilla.xamarin.com/show_bug.cgi?id=58842
If a project has no PackageReference items but imports a file that
does have PackageReference items the packages were not restored
on opening its solution. This was because only the PackageReference
items were checked inside the project itself to determine if the
project used any packages. Now the evaluated items are also checked
so any imported PackageReference items are detected and a restore
will then be run on opening the solution.
This only affected non .NET Core projects. Also the restore itself
already handled imported PackageReference items when generating the
project.assets.json file.
Imported PackageReference items are not currently displayed in the
Packages folder.
=> [NuGet] Support imported package references

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
SystemAssemblyService is not initialized when the branding service uses it
to load files.
=> Fix another bad use of SystemAssemblyService

main/tests/Makefile.am
Easy to use target to profile a unit test suite and get profiling reports and a mlpd
=> Add target to profile a unit test and write a report via mprof-report

main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Rename/RenameRefactoring.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs
Problem was that .xaml file projections were updated only for currently selected project(iOS or Android), hence if user .cs file was using different project file was not seeing changes in .xaml(new or renamed fields), this was pretty big problem because designer removes ability to change selected project for user...
=> Fix out of date type system projections(.xaml) for files in SharedProject

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionFolder.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.ExternalTools/ExternalToolPanel.cs, main/tests/UnitTests/MonoDevelop.Projects/StringTagTests.cs
Fixed bug #58735 - Unable to start .exe from VSMac as External Tool
https://bugzilla.xamarin.com/show_bug.cgi?id=58735
When a solution is selected in the Solution window then running an
external tool would fail. With a project selected the external tool
would run successfully.
```
Error while executing command: Tool List
System.InvalidOperationException: The constructor of type MonoDevelop.Projects.SolutionFolder must call Initialize(this)
at MonoDevelop.Projects.WorkspaceObject.AssertExtensionChainCreated ()  in MonoDevelop.Core/MonoDevelop.Projects/WorkspaceObject.cs:331
at MonoDevelop.Projects.WorkspaceObject.get_ItemExtension ()  in MonoDevelop.Core/MonoDevelop.Projects/WorkspaceObject.cs:346
at MonoDevelop.Projects.WorkspaceObject.GetStringTagModel …
```
=> [d15-4][Ide] Fix external tool failing to run when solution selected

main/src/addins/MonoDevelop.AspNetCore/Properties/MonoDevelop.AspNetCore.addin.xml, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Templating/DotNetCoreProjectTemplateWizard.cs
58548 - Enable new ASP.NET Core F# project templates
https://bugzilla.xamarin.com/show_bug.cgi?id=58548
ASP.NET Core Empty
- .NET Core 1.x and 2.0
ASP.NET Core Web API
- .NET Core 2.0 only
=> [AspNetCore] Enable new ASP.NET Core F# project templates

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/RecentFileStorage.cs
The file used for storage is opened with an exclusive lock in the
RecentFileStorage's constructor and the stream associated with the
file is not closed. This can prevent the SaveRecentFiles method
from being able to acquire the file lock and write to the file.
This seemed to cause the RecentTemplates_TwoTemplatesInGroupDifferentLanguage_TreatedAsDifferentRecentTemplate test on Wrench to fail sometimes.
=> [Ide] Close file stream in RecentFileStorage constructor

main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/MDMenuHeaderItem.cs
The new MDMenuHeaderItem is Mac specific but was being compiled
on all platforms.
=> [Ide] Fix build when not on Mac

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Ide.cs
This for instance allows an mpack to be installed simply by drag&dropping it on the dock icon on Mac.
Depends on https://github.com/mono/mono-addins/pull/84
=> [Ide] Support installing mpack directly from a file open operation

main/MonoDevelop.props
MSBuild 15.3 is out and the bug has been fixed.
=> Delete a workaround that is no longer necessary.

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/MicrosoftTemplateEngineProjectTemplatingProvider.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/MicrosoftTemplateEngineSolutionTemplate.cs, main/tests/Ide.Tests/ProjectTemplateTests.cs, main/tests/test-projects/DotNetCoreTemplating/.template.config/template.json, main/tests/test-projects/DotNetCoreTemplating/library1/MyClass.cs, main/tests/test-projects/DotNetCoreTemplating/library1/library1.csproj, main/tests/test-projects/DotNetCoreTemplating/library2/MyClass.cs, main/tests/test-projects/DotNetCoreTemplating/library2/library2.csproj
Fixed bug #58980 - Back slashes in .NET project templates result in
project not being added to solution
https://bugzilla.xamarin.com/show_bug.cgi?id=58980
The template.json file used by the new templating engine uses a
primaryOutputs property for projects and files. If the paths used
contained backslashes then the project would not be added to the
solution.
```
"primaryOutputs": [
{ "path": "Library1\\Library1.csproj" },
{ "path": "Library2\\Library2.csproj" }
]
```
Now the paths have the backslashes replaced with forward slashes if
the current platform does not support backslash as a directory
separator.
=> [Ide] Support backslashes in template primary output paths

version.config
Reason for Patch: 
```
Release communications consistency.  We had to include the full build number in the release notes sections for the 15.3.2 release because the all of the builds were still versioned as x.x.0.x.  We can strive to improve upon that for the 15.3.3 release by aligning the 3rd-digit version number with the Visual Studio 2017 service release number.
```
=> Update to x.y.3.z for 15.3 SR3

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildFileFormat.cs
Fixed bug #58839 - Solution converted to VS 2017 format cannot be
opened in VS 2017
https://bugzilla.xamarin.com/show_bug.cgi?id=58839
On converting the solution to Visual Studio 2017 format the solution
file it could then not be opened in Visual Studio 2017 since the
solution file format version was set to 15.0 which is not supported.
Visual Studio 2017 uses 12.0 as the solution file format.
=> [Core] Fix solution file format version for Visual Studio 2017

main/external/fsharpbinding/MonoDevelop.FSharpBinding/TypeSignatureHelp.fs
Reported by @decriptor - when using Menlo font, the F# signature help markers sometimes slightly overlap the editor text. Adjusted by 2 pixels.
=> Adjust signature help markers by a couple of pixels

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildFileFormat.cs, main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/MSBuildTests.cs
This fixes the failing tests on Wrench due to the merge of pull request #2957
Also added a test verifying that a new project added to an existing solution uses the default tools version as the existing project instead of upgrading it.
=> [Core] Fix project ToolsVersion being upgraded to 15.0

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs, main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/ProjectTests.cs
Fixed bug # 59111 - New file added to project with hyphen in name has
invalid namespace
https://bugzilla.xamarin.com/show_bug.cgi?id=59111
Creating a new .NET Core project with a name that contains a hyphen
and then adding a new class file to the project would result in an
invalid namespace being used. The same thing could happen with a non
.NET Core project if the RootNamespace in the project file contains a
hyphen.
=> [Core] Sanitize default namespace for new files

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/WorkspaceObject.cs, main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/ProjectCapabilityTests.cs, main/tests/test-projects/project-capability-tests/azurefunctions.targets
If the project extension uses an AppliesTo attribute which is
initially false and then a new project capability is added and the
project is re-evaluated then the AppliesTo attribute is now
re-evaluated. This will then cause the project extension to be added
to the extension chain. If the project extension was attached to the
project and the project capability is removed then the project
extension will now be removed when the project is re-evaluated.
Also added a test for this in MonoDevelop.Core.Tests but it relies on the AzureFunctions project
extension which I do not like. Ideally this would be independent of that addin being available. Maybe instead a test addin could be created or registered somehow that defines its own project extension that uses the AppliesTo attribute.
=> [Core] Re-evaluate AppliesTo condition on capability change

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild.Conditions/ConditionFactorExpresion.cs, main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/MSBuildProjectTests.cs, main/tests/test-projects/msbuild-project-test/test.csproj
Fixed bug #58338 - New .NET Core project has net461 target framework
when primary Mac OS language is Czech
https://bugzilla.xamarin.com/show_bug.cgi?id=58338
Single.TryParse returns true for an empty string when the machine's
culture is 'cs-CZ'. This was causing the MSBuild condition evaluation
to be treated as a boolean comparison incorrectly in some cases.
The condition below would return false even though the property was
not defined and both sides of the condition were empty strings:
<PropertyGroup Condition="'$(TargetFrameworkIdentifier)' == ''">
This was causing the TargetFrameworkIdentifier to not be set for
.NET Core projects so the default of .NETFramework was being used.
=> [Core] Fix MSBuild condition evaluation when using Czech locale

main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/MDMenu.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/MDMenuItem.cs
When pressing a shortcut key VoiceOver kept saying "Divider". This change makes it read the command name instead
Based on work by Dmytro Ovcharov
Fixes BXC #53648
=> [A11y] Make VO read the correct menu item description

main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/MonoTextEditor.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/DockContainer.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/DockFrame.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components/GtkWorkarounds.cs
On macOS we need to emit the add/remove signals for the accessibility system to work correctly. Normally doing it triggers a critical warning in Gtk, but the Xamarin macOS Gtk has code to work around it. Gtk on Linux/Windows do not so the code spams Criticals to the log.
Fix this by only emiting on macOS
Fixes BXC #57083
=> [A11y] Only emit the container::add/remove signal on macOS

main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/Extensions.fs, main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/LanguageService.fs
Without this change, it's not possible to debug the F# addin at all due to hitting an [assert](https://github.com/mono/mono/blame/90450cc1480d4b76732fd725da06d75da40665c6/mono/metadata/metadata.c#L1116)  in Mono.
This needs to be fixed in the compiler, but this change allows me to keep working.
=> Remove retry as it makes portable pdb debugging fail

main/src/core/MonoDevelop.Ide/MonoDevelop.Components/IdeTheme.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.OptionPanels/D152AccessibilityPanel.cs
NSUserDefaults seems to not want to synchronise when restarting the app, so reset it which seems to make it work.
Fixes BXC #59138
=> [A11y] Reset the user defaults before restarting the app

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Features/AutoInsertBracket/AbstractTokenBraceCompletionSession.cs, main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.csproj, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/EditSession.cs, main/tests/Ide.Tests/MonoDevelop.Ide.Editor/SkipCharSessionTests.cs, main/tests/Ide.Tests/MonoDevelop.Ide.Tests.csproj
Problem was that when typing “” first time and deleting with backspace IDE still thought it’s in “SkipCharSession” which is keeping track of when to skip second “ if user types after writing string… Fix for this issue is inspired by commit fa40fd0ed which fixed it for C# brackets… I also added logic needed for unit tests + removed unused field from C# session handler.
=> Bug 58764 - XAML Editor jumps to a new line when trying to insert property quote marks

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs, main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/MSBuildGlobTests.cs, main/tests/test-projects/msbuild-glob-tests/glob-import-remove-test-saved.csproj
Fixed bug #59139 - Duplicate .xaml files in .NET Standard project
https://bugzilla.xamarin.com/show_bug.cgi?id=59139
Adding a new .xaml file to a project was not adding a None Remove
item for the .xaml file to remove it from the default glob for all
files.
<None Remove="MyNewPage.xaml" />
On reloading the solution the Solution window would show two .xaml
files - one EmbeddedResource item and one None item.
=> [Core] Fix MSBuild remove item not added

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs, main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/MSBuildGlobTests.cs, main/tests/test-projects/msbuild-glob-tests/glob-remove-saved.csproj, main/tests/test-projects/msbuild-glob-tests/glob-remove-test.csproj
Fixed bug #59332 - Deleting .xaml file does not remove associated
None Remove MSBuild item
https://bugzilla.xamarin.com/show_bug.cgi?id=59332
When a file is deleted from the project and from the file system
any Remove MSBuild item was not being removed from the project file.
=> [Core] Deleting a file left Remove item in project file

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/FindInFilesDialog.cs
Fixed bug #59373 - Unable to open Find in Files dialog if Current
Document was selected
https://bugzilla.xamarin.com/show_bug.cgi?id=59373
Accessibility was being configured on the searchentryFileMask when
it was not created. Depending on the search option selected in the
'Look in' drop down list the searchentryFileMask is not always
created.
=> [Ide] Fix being unable to open Find in Files dialog

main/src/addins/Xml/Editor/XmlSchemasPanelWidget.cs
On Mac the parent window only gets focused if you Present it after the dialog has been closed
Fixes BXC 53773
=> [A11y] Refocus the parent window when closing the Add Scheme dialog

main/src/addins/CSharpBinding/CSharpBinding.csproj, main/src/addins/CSharpBinding/MonoDevelop.CSharp.Features/Formatter/CSharpEditorFormattingService.cs, main/src/addins/CSharpBinding/MonoDevelop.CSharp.Features/Formatter/SmartTokenFormatter.cs, main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpTextEditorIndentation.cs, main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/OnTheFlyFormatter.cs, main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/TextEditorOptions.cs
Inserted in Parenthesis'
I now fully ported the on typing formatter from roslyn - however that
code should be refactored when we have a working editorfeatures roslyn
subsystem.
=> Fixed 'Bug 59287 - [VSFeedback Ticket] #490276 - Automatic Space

main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs
Update the widget position when its size changes
and not only on creation. This fixes the extension
widget position during and after antimated resize.
(fixes bug #59211)
=> [59211][SourceEditor] Reposition extension widgets on resize

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/FindInFilesDialog.cs
Fixed bug #59373 - Unable to open Find in Files dialog if Current
Document was selected
https://bugzilla.xamarin.com/show_bug.cgi?id=59373
Accessibility was being configured on the searchentryFileMask when
it was not created. Depending on the search option selected in the
'Look in' drop down list the searchentryFileMask is not always
created.
Not sure if this meets the requirements for inclusion in 15.4. It affects searching in the current document or selection, but you could use the inline search instead here. However if one of those options were selected then the dialog cannot be re-opened until all documents are closed or the solution is closed.
It is a regression from VS Mac 7.1
=> [d15-4][Ide] Fix being unable to open Find in Files dialog

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/SdiWorkspaceWindow.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs
This bug was fixed in d15-2, but for some reason the fix didn't made it to master.
=> Fix bug 58445 - Closing a solution with unsaved changes and selecting "Save" before closing, solution doesn't close

main/src/addins/MonoDevelop.Packaging/MonoDevelop.Packaging/PackagingNuGetProject.cs
Fixed bug #59461 - UI hang creating packaging project
https://bugzilla.xamarin.com/show_bug.cgi?id=59461
The VSTest addin checks the installed NuGet packages for test adapters
when a new solution is created. Returning the installed NuGet packages
for the packaging project was causing the UI thread to be blocked and
caused the IDE to hang.
=> [Packaging] Fix UI hang creating new NuGet package project

main/src/addins/MacPlatform/MacExternalConsoleProcess.cs
Our terminal script used echo $? which is a Bash extension, and doesn't work for other shells such as zsh or fish, so
always execute out script inside a bash shell
Fixs BXC #56053
=> [Fix 56053] Force Bash shell when executing commandline apps

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTests.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs, main/tests/test-projects/dotnetcore-pcl/NetCore11/NetCore11.csproj, main/tests/test-projects/dotnetcore-pcl/NetStandard14/NetStandard14.csproj, main/tests/test-projects/dotnetcore-pcl/PclProfile111/PclProfile111.csproj, main/tests/test-projects/dotnetcore-pcl/dotnetcore-pcl.sln
Fixed bug #58526 - "Incompatible target framework" when referencing
PCL project from netstandard project
https://bugzilla.xamarin.com/show_bug.cgi?id=58526
Mirror Visual Studio on Windows behaviour where a .NET Core or a
.NET Standard project can reference any PCL project.
=> [DotNetCore] Allow PCL projects to be referenced

main/external/fsharpbinding/MonoDevelop.FSharpBinding/HighlightUnusedCode.fs
Seen while debugging the F# compiler
```
at MonoDevelop.FSharp.highlightUnusedCode.getOpenStatements (Microsoft.FSharp.Core.FSharpOption`1[T] tree) [0x00000] in /Users/jason/src/monodevelop/main/external/fsharpbinding/MonoDevelop.FSharpBinding/HighlightUnusedCode.fs:27
at MonoDevelop.FSharp.highlightUnusedCode+getUnusedCode@95.Invoke (System.Tuple`2[T1,T2] tupledArg) [0x00087] in /Users/jason/src/monodevelop/main/external/fsharpbinding/MonoDevelop.FSharpBinding/HighlightUnusedCode.fs:152
at Microsoft.FSharp.Core.OptionModule.Bind[T,TResult] (Microsoft.FSharp.Core.FSharpFunc`2[T,TResult] binder, Microsoft.FSharp.Core.FSharpOption`1[T] option) [0x00000] in …
```
=> Fix NRE in highlightUnusedCode.

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs, main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.Formats.MSBuild/BuildEngine.v4.0.cs, main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.Formats.MSBuild/ProjectBuilder.v4.0.cs, main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/MSBuildTests.cs, main/tests/test-projects/test-project-refresh/Extra.cs, main/tests/test-projects/test-project-refresh/Program.cs, main/tests/test-projects/test-project-refresh/extra.targets, main/tests/test-projects/test-project-refresh/test-project-refresh.csproj, main/tests/test-projects/test-project-refresh/test-project-refresh.sln
The problem was that when a project is modified and then refreshed in
the remote builder, the builder would unload not only the modified
project, but all loaded projects. This issue was introduced in this
commit: mono/monodevelop@ebf6c0a, when trying to fix another bug
(23435).
This fix was slowing down project loading because during source analysis,
several projects were marked for refresh, which caused all loaded projects
to be unloaded, so projects had to be loaded again and again. It was
much worse when installing .NET Core 2.0 because for some reason,
.NET Standard projects are much slower to evaluate when it is installed,
(but that's a different issue), and Main.sln has one of such projects:
RefactoringEssentials.
The bug that the original commit was fixing was that target files …
=> Fixes performance issue running msbuild targets

main/src/addins/MacPlatform/MacInterop/AppleScript.cs
When we fail to load the OSA component, throw an AppleScriptException
instead of a general Exception to make it easier to catch.
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=57438
=> [MacInterop] Throw AppleScriptException instead of Exception

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
renamed'
Project modify handler was missing the file changes.
=> Fixed 'Bug 59149 - Code completion stops working after a file is

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.Helpers/DummyDotNetProject.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/DotNetCoreNuGetProjectTests.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/PackageReferenceNuGetProjectTests.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/DotNetCoreNuGetProject.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageReferenceNuGetProject.cs
Fixed bug #59447 - Package is not compatible error for project.json
with imports
https://bugzilla.xamarin.com/show_bug.cgi?id=59447
Imports in a project.json file are ignored with older NuGet 4.3
versions. Updating to NuGet 4.3.1 fixes this. NuGet bug:
NuGet/Home#5806
=> [d15-4][NuGet] Update to NuGet 4.3.1.4445 

main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/EditorFactory.cs, main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/FileRegistry.cs, main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/InternalExtensionAPI/ITextEditorFactory.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/Projection/Projection.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextEditorFactory.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
Disposing the editor would be enough to fix that leak. But there is no
reason a projection should listen for file changes since projected
files are purely virtual and change only when the main document
changes. Giving the text editor type to the backends can allow some
optimizations for non UI text editor use cases.
=> Fixed 'Bug 58551 - Memory leak when editing .xaml files'

main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs, main/tests/Ide.Tests/MonoDevelop.SourceEditor/JSonIndentEngineTests.cs
tests - one of the last patches added a new "empty" constructor
breaking many tests.
=> [SourceEditor] Fixed unit test. Empty constructor is used in many

main/build/MacOSX/monostub.mm
Let's try with 8MB and see if it improves things.
=> [mac] Bump the minimum nursery size in mono

main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.csproj, main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ThreadsPad.cs, main/src/addins/MonoDevelop.Debugger/packages.config
What this commit does... It takes fetching for session, processes and threads needed by Thread Pad off Main thread to thread pool...
=> Bug 51324 - Deadlock initializing the Threads window after starting a debug session

main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.Formats.MSBuild/ProjectBuilder.v4.0.cs, main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/ProjectTargetEvaluationTests.cs
The previous code would only include custom metadata from the item and none of the default provided ones (such as FullPath).
Using MetadataNames and GetMetadataValue instead ensures every bit of metadata that an item normally exposes is returned to the caller.
=> Include all available MSBuild item metadata when returning evaluated items

main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.VsTest/VsTestAdapter.cs, main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.VsTest/VsTestRunAdapter.cs, main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.csproj, main/src/addins/MonoDevelop.UnitTesting/packages.config
Issue was in vstest which is fixed in https://github.com/Microsoft/vstest/pull/1108
So this commit updates to latest version of vstest and changes logic around extracting path from arguments to remove new quotes
Plus follows API changes
=> Bug 59517 - xUnit tests not discovered

main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs, main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/UnderlineMarker.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/OSXEditor.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
The line gap is not supported by pango therefore I use the os x
routines to determine the line height. However that only works on os x
- on linux the fluent fonts don't have that gap. But there is no
single gtk editor (and even sublime text) which supports that setting
there.
Underline position metrics are now taken into account for underlines
as well.
=> Fixed 'Bug 59260 - VS4M and MonoDevelop not adapting to applied fonts'

main/external/fsharpbinding/MonoDevelop.FSharp.Tests/TemplateTests.fs
I noticed that both the PCL and Shared source versions of the XF
template test shared the same folder to build in.
=> Possible fix for flaky F# test

main/src/addins/WindowsPlatform/WindowsPlatform/MainToolbar/WPFToolbar.cs, main/tests/MonoDevelop.Core.Tests/MonoDevelop.Core.Tests.csproj
Don't resolve references from the output directory because there's no guarantee they will be there at the time the project builds. Instead resolve deterministically from the packages directory. It is annoying because Nuget forces you to specify the version in the HintPath, but hopefully with the new SDK projects and PackageReference this can go away soon.
Implement missing members on WPFToolbar.
=> Fix Windows build.

version-checks
Xamarin Mac was bumped to 4.0.0.1 which requires XCode 9 for linking
=> Bump md-addins to build with XCode 9

main/src/addins/MonoDevelop.Packaging/MonoDevelop.Packaging/DotNetProjectExtensions.cs, main/src/addins/MonoDevelop.Packaging/PostBuild.proj, main/src/addins/MonoDevelop.Packaging/Templates/CrossPlatformLibrary.xpt.xml, main/src/addins/MonoDevelop.Packaging/Templates/PackagingProject.xpt.xml, main/src/addins/MonoDevelop.Packaging/packages.config
NuGet.Build.Packaging was bumped[1] to fix the build in mono-addins.
So, we pick up that change from mono-addins. And update
NuGet.Build.Packaging to v0.2.0 to be in sync.
bxc: #58815
--
1. https://github.com/mono/mono-addins/pull/88
=> Bump NuGet.Build.Packaging and mono-addins.

main/src/core/MonoDevelop.Startup/app.config
Even though the NuGet package version is 2.3.2, the assembly version inside is still 2.3.0.0.
=> Fix Roslyn versions.

main/src/core/MonoDevelop.Core/MonoDevelop.Core.Execution/RemoteProcessConnection.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/RemoteBuildEngine.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/RemoteBuildEngineManager.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/RemoteProjectBuilder.cs
Before shutting down a remote builder make sure that all remote calls have
been completed. It avoids unnecessary exceptions that might happen if
the builder is shut down too early.
=> Improve handling of remote builder shutdown

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Solution.cs, main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/ProjectCapabilityTests.cs, main/tests/test-projects/project-capability-tests/Library/Library.csproj, main/tests/test-projects/project-capability-tests/Library/Library.sln, main/tests/test-projects/project-capability-tests/Library/testcapability.targets
Fixed bug #58021 - New Azure Functions project can't be debugged
https://bugzilla.xamarin.com/show_bug.cgi?id=58021
When re-evaluating the project check to see if the project's
SupportsExecute has changed, which can happen if a new project
capability is installed via a NuGet package. If this has changed
then check to see if the solution's StartupItem should be refreshed
since it may now be possible to set a startup item for the solution.
Also handle the case where the project capability is removed and the
project can no longer be executed. In this case if the solution's
StartupItem is the project then the startup item should be changed.
=> [Core] Update solution startup item on re-evaluation

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Solution.cs, main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/ProjectCapabilityTests.cs, main/tests/test-projects/project-capability-tests/Library/Library.csproj, main/tests/test-projects/project-capability-tests/Library/Library.sln, main/tests/test-projects/project-capability-tests/Library/testcapability.targets
Fixed bug #58021 - New Azure Functions project can't be debugged
https://bugzilla.xamarin.com/show_bug.cgi?id=58021
When re-evaluating the project check to see if the project's
SupportsExecute has changed, which can happen if a new project
capability is installed via a NuGet package. If this has changed
then check to see if the solution's StartupItem should be refreshed
since it may now be possible to set a startup item for the solution.
Also handle the case where the project capability is removed and the
project can no longer be executed. In this case if the solution's
StartupItem is the project then the startup item should be changed.
=> [d15-5][Core] Update solution startup item on re-evaluation

main/src/addins/MonoDevelop.Packaging/MonoDevelop.Packaging/DotNetProjectExtensions.cs, main/src/addins/MonoDevelop.Packaging/PostBuild.proj, main/src/addins/MonoDevelop.Packaging/Templates/CrossPlatformLibrary.xpt.xml, main/src/addins/MonoDevelop.Packaging/Templates/PackagingProject.xpt.xml, main/src/addins/MonoDevelop.Packaging/packages.config
NuGet.Build.Packaging was bumped[1] to fix the build in mono-addins.
So, we pick up that change from mono-addins. And update
NuGet.Build.Packaging to v0.2.0 to be in sync.
bxc: #58815
--
1. https://github.com/mono/mono-addins/pull/88
=> [d15-5] Bump NuGet.Build.Packaging and mono-addins.

main/po/ja.po, main/po/zh_CN.po, main/po/zh_TW.po
It seems to be related to using markup. Remove these for now.
https://bugzilla.xamarin.com/show_bug.cgi?id=58759
This is https://github.com/mono/monodevelop/pull/3123 but cherry-picked for d15-5
=> Remove some translations that are triggering a crash

main/tests/Ide.Tests/MonoDevelop.Ide.Editor/SkipCharSessionTests.cs
Backporting https://github.com/mono/monodevelop/pull/3124 to 15.5 branch, to fix randomly failing unit test on Wrench
=> Fixed unit test depending on setting, causing it to fail on most Wrench bots

main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.QuickTasks/QuickTaskOverviewMode.cs, main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.QuickTasks/QuickTaskStrip.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.DockNotebook/DockNotebookTab.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.DockNotebook/TabStrip.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components/DropDownBoxListWindow.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components/PathBar.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Tabstrip.cs
After lots of trial and error, the main way to fix this leak is by manually unsubscribing events from the a11y proxies, as they can cause strong ref cycles between the object defining the event handler and the one holding the multicast delegate.
This fixes most of the source editor leaks caused by typing and opening/closing docs.
=> Nuke leaks caused by a11y event handlers

main/src/core/MonoDevelop.Ide/MonoDevelop.Components/GtkWorkarounds.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components/PangoUtil.cs, main/tests/Ide.Tests/MonoDevelop.Components/PangoUtilTests.cs, main/tests/Ide.Tests/MonoDevelop.Ide.Tests.csproj
Pango parses a markup without respecting multibyte
characters (byte based), hence the attribute indexes
need to be converted, in order to match the encoded
string representation.
(fixes bug #59844)
=> [Ide][59844] Fix unicode markup parsing

main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs
IMMulticontext.Reset might raise the PreeditChanged event, but
trying to retrieve the PreeditString leads to a native crash at this
point. Resetting the current preeditString if a IMContext reset is
requested fixes this issue.
(fixes bug #59642)
=> [TextEditor] Don't load PreeditString while resetting IMContext

main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs
#3102 for `d15-5`
IMMulticontext.Reset might raise the PreeditChanged event, but
trying to retrieve the PreeditString leads to a native crash at this
point. Resetting the current preeditString if a IMContext reset is
requested fixes this issue.
(fixes bug #59642)
(cherry picked from commit 3cfb1b3d13ceb04017a6ecb19a03667e7cc5508a)
=> [59642][TextEditor] Don't load PreeditString while resetting IMContext

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/DefaultMSBuildEngine.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildEngine.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildEngineV12.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildImport.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProject.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProjectInstance.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildTarget.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/RemoteBuildEngineManager.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/SingleFileDescriptionTemplate.cs, main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/DotNetCoreProjectTests.cs, main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/MSBuildGlobTests.cs, main/tests/test-projects/NetStandardXamarinForms/NetStandardXamarinForms.sln, main/tests/test-projects/NetStandardXamarinForms/NetStandardXamarinForms/MyPage.xaml, main/tests/test-projects/NetStandardXamarinForms/NetStandardXamarinForms/MyPage.xaml.cs, main/tests/test-projects/NetStandardXamarinForms/NetStandardXamarinForms/NetStandardXamarinForms.csproj, main/tests/test-projects/dotnetcore-console/dotnetcore-console/dotnetcore-disable-default-items.csproj, main/tests/test-projects/msbuild-glob-tests/glob-import-metadata-prop.csproj, main/tests/test-projects/msbuild-glob-tests/glob-import-metadata-prop.props
Various fixes for [bug 59286](https://bugzilla.xamarin.com/show_bug.cgi?id=59286).
The changes made to Project.cs are enough to get Xamarin.Forms 2.4 mostly working in a .NET Standard project. However the changes may not be enough to handle other MSBuild update items added by other NuGet packages. Also I am wondering if there is a better way to handle the code that runs on the UI thread to update the existing ProjectFile's fields - maybe somehow have this run when the file is added to the project before the saving is run.
Testing this branch the following problems have been identified and are not yet fixed. Renaming seems to be problematic independent of using Xamarin.Forms 2.4.
- Add ContentPage with xaml then change build action to None for .xaml file.
- Add ContentPage with xaml and …
=> Support Xamarin.Forms 2.4

main/src/addins/Xml/Editor/BaseXmlEditorExtension.cs
@nosami was seeing a crash on opening a xaml file, caused by possibly not having an image size set on the path entry icon.
```
FATAL ERROR [2017-10-06 13:11:32Z]: An unhandled exception has occured. Terminating Visual Studio? True
System.InvalidOperationException: Image size has not been set and the image doesn't have a default size
at Xwt.Drawing.Image.GetFixedSize () [0x0001b] in /Users/builder/data/lanes/5525/83cafc1a/source/monodevelop/main/external/xwt/Xwt/Xwt.Drawing/Image.cs:545
at Xwt.Toolkit.RenderImage (System.Object nativeWidget, System.Object nativeContext, Xwt.Drawing.Image img, System.Double x, System.Double y) [0x00008] in /Users/builder/data/lanes/5525/83cafc1a/source/monodevelop/main/external/xwt/Xwt/Xwt/Toolkit.cs:782
at MonoDevelop.Components.GtkUtil.DrawImage …
```
=> [Xml] Fix possible crash when opening Xaml file

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/DefaultMSBuildEngine.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildEngine.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildEngineV12.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildImport.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProject.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProjectInstance.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProjectService.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildTarget.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/SingleFileDescriptionTemplate.cs, main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/DotNetCoreProjectTests.cs, main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/MSBuildGlobTests.cs, main/tests/test-projects/NetStandardXamarinForms/NetStandardXamarinForms.sln, main/tests/test-projects/NetStandardXamarinForms/NetStandardXamarinForms/MyPage.xaml, main/tests/test-projects/NetStandardXamarinForms/NetStandardXamarinForms/MyPage.xaml.cs, main/tests/test-projects/NetStandardXamarinForms/NetStandardXamarinForms/NetStandardXamarinForms.csproj, main/tests/test-projects/dotnetcore-console/dotnetcore-console/dotnetcore-disable-default-items.csproj, main/tests/test-projects/msbuild-glob-tests/glob-import-metadata-prop.csproj, main/tests/test-projects/msbuild-glob-tests/glob-import-metadata-prop.props, version-checks
Various fixes for [bug 59286](https://bugzilla.xamarin.com/show_bug.cgi?id=59286).
The changes made to Project.cs are enough to get Xamarin.Forms 2.4 mostly working in a .NET Standard project. However the changes may not be enough to handle other MSBuild update items added by other NuGet packages.
Testing this branch the following problems have been identified and are not yet fixed. Renaming seems to be problematic independent of using Xamarin.Forms 2.4.
- Add ContentPage with xaml then change build action to None for .xaml file.
- Add ContentPage with xaml and then remove .xaml but do not delete .xaml file
- Add ContentPage with xaml and then remove .xaml.cs file but do not delete .xaml.cs file
- Add ContentPage with xaml. Then both .xaml and .xaml.cs file removed from the project but …
=> [d15-5] Support xamarin forms 2.4

main/src/core/MonoDevelop.Core/MonoDevelop.Core/MacSystemInformation.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components/IdeTheme.cs
This patch fixes just the dark titlebar background color (but not all the other `VibrantDark` `NSAppearance` issues on High Sierra :disappointed: ).
=> [59738] Fix Titlebar background color on HighSierra

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/GtkTreeModelResult.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/GtkWidgetResult.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AppResult.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/PackageServices.cs
cherry-picked from master https://github.com/mono/monodevelop/pull/3162
=> [AutoTest] Add ability to reference a TreeView column by number without having to add SemanticAttribute

main/src/addins/Xml/Editor/BaseXmlEditorExtension.cs
To match VS2017 behaviour
This is basically same as https://github.com/mono/monodevelop/commit/fb7a266e308c670011611e12916e1d0d7219b63e but to also include attribute value(didn't realise at time that VS2017 also does this for attribute values)
=> [Xml] Always show code completion when typing(not just Cmd+Space or start)

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CSharpCompletionTextEditorExtension.cs
object creation'
The roslyn version is a bit more flexible than ours since the match
priority is more flexible - like in case the original item fails out
of the list the next match priority item is taken when 2 items have
the same pattern match priority. Supporting that will happen when we
use the roslyn controllers inside our IDE.
=> Fixed 'Bug 60120 - Code completing selects wrong entry when typing new

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/DefaultMSBuildEngine.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildEngine.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildEngineV12.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildImport.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProject.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProjectInstance.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProjectService.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildTarget.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/SingleFileDescriptionTemplate.cs, main/tests/UnitTests/MonoDevelop.Projects/MSBuildGlobTests.cs, main/tests/UnitTests/MonoDevelop.Projects/MSBuildTests.cs, main/tests/test-projects/NetStandardXamarinForms/NetStandardXamarinForms.sln, main/tests/test-projects/NetStandardXamarinForms/NetStandardXamarinForms/MyPage.xaml, main/tests/test-projects/NetStandardXamarinForms/NetStandardXamarinForms/MyPage.xaml.cs, main/tests/test-projects/NetStandardXamarinForms/NetStandardXamarinForms/NetStandardXamarinForms.csproj, main/tests/test-projects/dotnetcore-console/dotnetcore-console/dotnetcore-disable-default-items.csproj, main/tests/test-projects/msbuild-glob-tests/glob-import-metadata-prop.csproj, main/tests/test-projects/msbuild-glob-tests/glob-import-metadata-prop.props, version-checks
Various fixes for [bug 59286](https://bugzilla.xamarin.com/show_bug.cgi?id=59286).
The changes made to Project.cs are enough to get Xamarin.Forms 2.4 mostly working in a .NET Standard project. However the changes may not be enough to handle other MSBuild update items added by other NuGet packages.
Testing this branch the following problems have been identified and are not yet fixed. Renaming seems to be problematic independent of using Xamarin.Forms 2.4.
- Add ContentPage with xaml then change build action to None for .xaml file.
- Add ContentPage with xaml and then remove .xaml but do not delete .xaml file
- Add ContentPage with xaml and then remove .xaml.cs file but do not delete .xaml.cs file
- Add ContentPage with xaml. Then both .xaml and .xaml.cs file removed from the project but …
=> [d15-4] Support xamarin forms 2.4

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests.csproj, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateTests.cs
The tests now create and build all .NET Standard, .NET Core and ASP.NET Core project templates. The tests take into account if the machine does not have the required .NET Core SDKs and only tests the project templates that would be available in the New Project dialog.
=> [DotNetCore] Create and build project templates in tests

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AppResult.cs
When there was no "." in the property name, it bombed
=> [AutoTest] Fix SetProperty when there is no "."

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DisplayBindingService.cs
line of Main.axml file.'
This ensures that the workbench window is correctly set for all sub
view contents.
=> Fixed 'Bug 52524 - Xamarin Studio crashes on adding Break-point to any

main/src/core/MonoDevelop.Core/MonoDevelop.Core.Execution/BinaryMessage.cs, main/tests/MonoDevelop.Core.Tests/MonoDevelop.Core.Execution/BinaryMessageTests.cs, main/tests/MonoDevelop.Core.Tests/MonoDevelop.Core.Tests.csproj, main/tests/MonoDevelop.Core.Tests/packages.config
The problem with the old code is that it assumed that any Array was uni-dimensional. Therefore, it would end up with an invalid cast exception.
When writing any array into the binary message, flatten the array. Thus, when reading the array back, we read it as uni-dimensional. It should not impact anything.
There is a fast-path for rank1 arrays, as the foreach is rewritten to handle generalized iteration.
Bug 59805 - Visual Studio for Mac potential issue on unit testing support
=> [Core] Add support for multi-dimensional array writing.

main/src/addins/MonoDevelop.Refactoring/AddinInfo.cs, main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeIssues/AnalyzersFromAssembly.cs, main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.csproj, main/src/addins/MonoDevelop.Refactoring/packages.config
This will provide us with code issues for writing code. Also, serves
as an infrastructure on how to add more analyzers that are specifically
for MonoDevelop developers usage
=> [Refactoring] If we build debug builds, enable RoslynClrHeapAnalyzer

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests.csproj, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateTests.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTests.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreTestBase.cs
After commit 7b6587aaa8dcc796b70ea66f79d5237fdcaea3b0 the template tests were failing with an error:
```
DotNetCoreProjectTemplateTests
System.Exception : Toolkit could not be loaded
----> System.IO.FileNotFoundException : Could not load file or
assembly 'PresentationFramework, Version=4.0.0.0, Culture=neutral,
PublicKeyToken=31bf3856ad364e35' or one of its dependencies.
at Xwt.Toolkit.LoadBackend (System.String type, System.Boolean isGuest, System.Boolean throwIfFails) [0x00081] in monodevelop/main/external/xwt/Xwt/Xwt/Toolkit.cs:295
at Xwt.Toolkit.Load (Xwt.ToolkitType type) [0x00049] in monodevelop/main/external/xwt/Xwt/Xwt/Toolkit.cs:235
at MonoDevelop.MacIntegration.MacPlatformService.LoadNativeToolkit () [0x00028] in monodevelop/main/src/addins/MacPlatform/MacPlatform.cs:144
at …
```
=> [DotNetCore] Fix failing tests

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs, main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/MSBuildGlobTests.cs
Removing a file but not deleting it would add an MSBuild remove item
for non .NET Core projects that were not using the advanced file glob
support.
=> [Core] Fix remove item added when UseAdvancedGlobSupport is false

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs, main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/MSBuildGlobTests.cs, main/tests/test-projects/msbuild-glob-tests/glob-file-link-test-saved1.csproj, main/tests/test-projects/msbuild-glob-tests/glob-file-link-test.csproj
Deleting a file link in a .NET Core project would add a remove item
for the file instead of just removing the link from the project.
=> [Core] Fix remove item added when removing file link

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs, main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/MSBuildGlobTests.cs, main/tests/test-projects/msbuild-glob-tests/glob-import-metadata-prop-saved1.csproj
With a Sdk style project when a new content page with xaml file was
added and then removed, but not deleted, a remove item was not added
for the .xaml.cs file.
=> [Core] Fix remove item not added for .xaml.cs file

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.csproj, main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.VsTest/VsTestProjectTestSuite.cs, main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.VsTest/VsTestRunAdapter.cs
This is fixed by making check if project is .NET Core or not more strict
Unfortunately adding unit test for this would not be simple :(
=> Fixed bug where .NET 4.6 project using SDK .csproj was debugged as .NET Core

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.csproj, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/ProjectJsonBuildIntegratedNuGetProjectTests.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/ProjectSystemReferencesReaderTests.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.csproj, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/NuGetProjectServices.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/ProjectJsonBuildIntegratedNuGetProject.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/ProjectSystemReferencesReader.cs
With two projects A and B that both use project.json files, project B
referencing project A, the NuGet package dependencies used by project
A were not available to project B transitively. This was because the
project reference information was not being added to the package spec
when a restore occurred so the assemblies from the transitively
referenced NuGet packages were not being added to the
project.lock.json file for Project B.
=> [NuGet] Fix transitive dependencies for project.json

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectSupportedTargetFrameworks.cs
Project options and the New Project dialog would show .NET Core 2.1
as an option if version 2.1 was installed along with 2.0. Currently
there are no project templates for 2.1 so project creation would
fail. So now only up to version 2.0 is shown as supported.
=> [DotNetCore] Do not show .NET Core version 2.1 for new projects

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestSession.cs
Part of the job to capture relevant details of memory usage as required by @Therzok 
corresponding PR: https://github.com/xamarin/QualityAssurance/pull/1314
=> [AutoTest] Added VirtualMemorySize and WorkingSet to MemoryStats

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestSession.cs
VirtualMemorySize field was renamed to VirtualMemory but not
all code was updated with this change.
=> [AutoTest] Fix build error

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
The default button was "Cancel" previously, which is rarely the button that you want to be selected by default.
=> Switch the default button to 'Build'. Fixes #60344

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/RecentOpen.cs
Don't clean up favorite recent projects automatically
based on file existance. A project might be located
on an external drive and temporary unavailable.
Remove a project from favorites only if it is unstarred
from the welcome page, or actively deleted.
(fixes bug #511658)
=> [511658][Ide] Don't remove missing favorite projects

main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.Tests/MonoDevelop.UnitTesting.Tests/TestResultBuilderTests.cs, main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.VsTest/TestResultBuilder.cs
Fixed bug #57783 - Null reference when running unit tests
https://bugzilla.xamarin.com/show_bug.cgi?id=57783
When building the test results the builder now handles null
returned from UnitTest.GetLastResult.
=> [UnitTesting] Fix possible null reference exception

main/src/addins/CSharpBinding/MonoDevelop.CSharp/PathedDocumentTextEditorExtension.cs
I'm not sure why it happened but this seems to have fixed it.
=> Fix a crash where DocumentContext was null

main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.Tests/MonoDevelop.UnitTesting.Tests.csproj, main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.Tests/MonoDevelop.UnitTesting.Tests/VsTestUnitTestTests.cs, main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.VsTest/VsTestUnitTest.cs
Fixed bug #56921 - Incorrect test names shown in Unit Tests window
https://bugzilla.xamarin.com/show_bug.cgi?id=56921
An xUnit test case that used '.' in the inline data would result in
the wrong name displayed in the Unit Tests window.
```
[Theory]
[InlineData ("a.b")]
[InlineData ("c.d")]
public void MyTest (string text)
{
}
```
The above test would result in the Unit Tests window displaying:
```
b")
c")
```
Instead of the expected:
```
MyTest(text: "a.b")
MyTest(text: "c.d")
```
=> [UnitTesting] Fix test case display name

main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeFixMenuService.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopSourceText.cs
document'
The source text implementation based on the visual studio layer was
invalid and caused that bug. The roslyn implementation of the changed
text works.
=> Fixed 'Bug 59890 - Inserting or sorting usages reformats the whole

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/ImportSymbolCompletionData.cs
When typing something like `backtrace.GetFrame(i);` after I typed `i` typing would get stuck for almost 1 second, so I profiled and noticed that problem is in list sorting and calls to ToDisplayString which put a lot of pressure on GC... Later I checked how many times it's called... turns out... out of 6,6k completion items `DisplayText` was called 181,7k...
Solution is cache all DisplayText up front...
=> [CSharp] Performance optimisation, code completion list appearence blocked UI for up to 1 second

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProjectService.cs
GetProjectImportSearchPaths is called from background threads but it queries
the add-in manager, which is not thread safe.
=> Fix threading issue when getting import search paths

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.csproj, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/ProjectJsonBuildIntegratedNuGetProjectTests.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/ProjectSystemReferencesReaderTests.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.csproj, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/NuGetProjectServices.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/ProjectJsonBuildIntegratedNuGetProject.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/ProjectSystemReferencesReader.cs
Fixed bug #60433 - Transitive dependencies not available when using
project.json
https://bugzilla.xamarin.com/show_bug.cgi?id=60433
With two projects A and B that both use project.json files, project B
referencing project A, the NuGet package dependencies used by project
A were not available to project B transitively. This was because the
project reference information was not being added to the package spec
when a restore occurred so the assemblies from the transitively
referenced NuGet packages were not being added to the
project.lock.json file for Project B.
=> [d15-5][NuGet] Fix transitive dependencies for project.json

main/msbuild/ReferencesVSEditor.props, main/src/core/MonoDevelop.Core/packages.config
Update to a version of MS.VS.Text.Implementation.dll that matches 15.6.150-preview (the version of VS Editor definitions we're currently referencing).
This version also removes a dependency on MS.VS.Text.Internal.dll so so one more step towards removing it and Text.UI.Wpf.dll from our list of dependencies.
=> Update to VS Editor implementation that matches 15.6.150-pre.

main/src/addins/MonoDevelop.PackageManagement/NuGet.PackageManagement.UI/MultiSourcePackageFeed.cs
The MultiSourcePackageFeed was not observing in the aggregated task
returned from Task.WhenAll. An unhandled exception was logged if the
package source returned an error or the url was invalid.
=> [NuGet] Fix unhandled exception when searching for packages

main/src/core/MonoDevelop.Core/MonoDevelop.Core/MacSystemInformation.cs
Fix the build after https://github.com/xamarin/md-addins/pull/2645 was merged in.
=> [Core] Add Sierra and High Sierra Mac version to system information

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/PackageReferenceNuGetProjectTests.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/DotNetProjectExtensions.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageReferenceNuGetProject.cs
Fixed bug #58985 - Support RestoreProjectStyle MSBuild property
https://bugzilla.xamarin.com/show_bug.cgi?id=58985
If a project sets the RestoreProjectStyle property to be
PackageReference then it should be restored as though it has
PackageReferences even if it does not have any.
<RestoreProjectStyle>PackageReference</RestoreProjectStyle>
This fixes runtime problems when a project references a .NET Standard
project that has PackageReferences since without this assemblies
from the NuGet packages are not copied to the output directory and
would have to be added to the main project.
=> [NuGet] Support RestoreProjectStyle MSBuild property

main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/UrlMarker.cs
The underline color now matches the start of the unterlined text - as
a plus the color is now cached which is a slight performance/memory
increase.
=> Fixed 'Bug 60220 - Hyperlink underline color should match test'

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads/ErrorListPad.cs
```
ERROR [2017-11-01 18:47:39Z]: Async operation failed
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object
at MonoDevelop.Ide.Gui.Pads.ErrorListPad.Dispose () [0x0002f] in /Users/jason/src/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads/ErrorListPad.cs:303
at MonoDevelop.Ide.Gui.DefaultWorkbench.OnClosed (System.EventArgs e) [0x000a0] in /Users/jason/src/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DefaultWorkbench.cs:748
at MonoDevelop.Ide.Gui.DefaultWorkbench+<Close>d__97.MoveNext () [0x001ef] in /Users/jason/src/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DefaultWorkbench.cs:789
```
=> Fix NRE when quitting before error list is shown

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/AbstractNavigationExtension.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj, main/src/core/MonoDevelop.TextEditor.Tests/MonoDevelop.TextEditor.Extension/NavigationExtensionTests.cs, main/src/core/MonoDevelop.TextEditor.Tests/MonoDevelop.TextEditor.Tests.csproj
pressed AFTER mouse down.'
Ctrl+Navigation should be turned off while selection.
=> Fixed '294858 [Feedback] Do NOT go to definition if Ctrl/Cmd is

main/external/fsharpbinding/MonoDevelop.FSharp.Tests/DebuggerExpressionResolver.fs, main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpDebuggerExpressionResolver.fs
```
type Test = { thing: string }
let a = { thing = "A" }
let x = a.thing
^^ put breakpoint here and hover over thing
```
=> [F#] Fix debugger expression resolver for record fields

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/RoslynCompletionData.cs, main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding/NamedArgumentCompletionTests.cs
keyword'
It's a work around for a roslyn bug
https://github.com/dotnet/roslyn/issues/22885
=> Fixed 'Bug 60365 - Escaped keywords autocomplete to the unescaped

main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser.csproj, main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/AssemblyBrowserWidget.cs, main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/UnresolvedIdStringProvider.cs
IdString generation was very basic so it failed in almost any advanced case. Unfortunately cecil doesn't have an id string generator implemented so a custom one was needed.
=> Fixed 'Bug 60082 - "Go to Declaration" doesn't work'

main/po/ko.po, main/po/ru.po, main/po/tr.po, main/po/uk.po
This is a followup to cbb96aba196ec77e6335424a7e938dbaaa5ebba4
https://bugzilla.xamarin.com/show_bug.cgi?id=58759
Followup to https://github.com/mono/monodevelop/pull/3126
=> Remove more translations that are triggering a crash

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs, main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/MSBuildGlobTests.cs, main/tests/test-projects/msbuild-glob-tests/glob-file-link-test-saved1.csproj, main/tests/test-projects/msbuild-glob-tests/glob-file-link-test.csproj
- Fixes remove item added when UseAdvancedGlobSupport is false 
Removing a file but not deleting it would add an MSBuild remove item
for non .NET Core projects that were not using the advanced file glob
support.
- Fixes remove item added when removing file link
Deleting a file link in a .NET Core project would add a remove item
for the file instead of just removing the link from the project.
=> [d15-5] Remove items being added to the project for non .NET Core projects

main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/StackTracePad.cs
This was regression from https://github.com/mono/monodevelop/pull/3279 where clearing was accidentally moved after `if(Debugger.IsPaused) return;` check...
=> Bug 60486 - VSmac pads don't appear to be updating when state changes

main/external/fsharpbinding/MonoDevelop.FSharpBinding/MonoDevelop.FSharp.fsproj, main/external/fsharpbinding/paket.lock
They are already in MonoDevelop bin, so no need to include in the bundle twice.
=> Don't copy local some assemblies in FSharpBinding

main/external/fsharpbinding/MonoDevelop.FSharpBinding/MonoDevelop.FSharp.fsproj
Turns out this Cecil package only has lib\net40 so the HintPaths were all wrong. This builds fine now.
=> Fix broken HintPaths.

main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/SystemAssemblyService.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/TargetRuntime.cs
During initialization, MonoTargetRuntime loads packages from .pc files.
The process of parsing .pc files uses SystemAssemblyService to find out
which frameworks do packages belong to. This query sometimes fails because
frameworks are loaded *after* runtimes are initialized, when the runtime
rises the TargetRuntime.Initialized event. The solution is to add a new event,
TargetRuntime.FrameworksInitialized, which is raised when frameworks are
created but before the .pc files are parsed. SystemAssemblyService now
subscribes TargetRuntime.FrameworksInitialized instead of
TargetRuntime.Initialized, so that frameworks are properly loaded before
.pc file processing.
=> Fix runtime initialization issue

main/src/addins/MacPlatform/Dialogs/MacAlertDialogHandler.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Window.cs
This patch enables alert dialog sheeting on Mac:
=> [Ide][Mac] Enable Alert sheeting on Mac

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/OnTheFlyFormatter.cs, main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding/OnTheFlyFormatterTests.cs
added to C# source file (VS 7.2 build 636).'
=> Fixed 'Bug 514890 - [Feedback] #region indentation changes when #if

main/Makefile.am
So that StrongNamer is restored before the F# addin is built.
=> [F#] Fixes #524437. Restore F# packages sooner

main/src/addins/MonoDevelop.AspNetCore/Properties/MonoDevelop.AspNetCore.addin.xml, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Codons/TemplateExtensionNode.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/MicrosoftTemplateEngineProjectTemplatingProvider.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/MicrosoftTemplateEngineSolutionTemplate.cs, main/tests/Ide.Tests/ProjectTemplateTests.cs, main/tests/test-projects/FileFormatExclude/.template.config/template.json, main/tests/test-projects/FileFormatExclude/library.csproj, main/tests/test-projects/FileFormatExclude/test.xml
Fixed bug #60627 - In Core MVC 2.0 template, site.min.css is not minified
https://bugzilla.xamarin.com/show_bug.cgi?id=60627
Do not format *.min.css, *.min.js and *.map files. The web tools
addin was re-formatting the minified files when the project was
created from the project template.
=> [AspNetCore] Do not format minified files and map files

main/src/core/MonoDevelop.Core/MonoDevelop.Core.ProgressMonitoring/AggregatedProgressMonitor.cs
The MonitorAction.All enum value did not include the ReportObject value.
=> [Core] Fix failing progress monitor test

main/external/fsharpbinding/MonoDevelop.FSharpi.Service/app.config, main/src/core/MonoDevelop.Startup/app.config
BinaryCompatChecker found a few issues :)
I've verified that our FSharp.Core.dll is 4.4.1.0, FSharp.Compiler.Service.dll is 16.0.2.0 and the VS Editor publicKeyTokens were wrong.
=> Fix issues in app.config files.

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/CompletionTextEditorExtension.cs
It breaks WebTooling completion for several reasons:
1. Sometimes HandleCodeCompletionAsync used to return null, which was semantically significant for WebTooling. Now it never returns null, but always returns a task.
2. WebTooling is not yet prepared to be able to run on a background thread. We need to do work to make our code properly thread-safe.
3. The timings have changed, so certain logic in WebTooling async completion is now wrong (we check if a completion is already up and don't return anything, and that check returns different results based on whether we're still on the UI thread or on a background thread now).
We will be revisiting the entire Completion story pretty soon with Roslyn EditorFeatures so I'm sure we'll arrive at a good solution that works for everybody. For now we …
=> Rollback PR #3211 temporarily.

main/build/MacOSX/make-dmg-bundle.sh
Really bump the size of the .dmg when creating it. There does not appear to be a suitable way to calculate this accurately and playing trial and error trying to find a value that works is painful and likely to break again. This is a hammer approach, but since all the extra space in the .dmg is compressed away to nothing it doesn't really matter that much.
=> [build] fix issues bundling live player

main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeFixMenuService.cs
Seems that this is a roslyn bug - the GetChangedSolutionAsync call is
missing all post processing for the code generation. Fortunately there
is an internal method forcing the post procession to be done.
=> Fixed '51873-Implement abstract class adds code without any spaces'

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/WorkspaceItem.cs, main/tests/Ide.Tests/MonoDevelop.Ide/UserPreferencesTests.cs, main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/ProjectLoadSaveTests.cs
The solution's user preferences file (SolutionName.userprefs) is now
saved in a subdirectory. For MonoDevelop this is:
.md/SolutionName/v7/UserPrefs.xml
For Visual Studio:
.vs/SolutionName/mac-v7/UserPrefs.xml
=> [Core] Save user preferences in subdirectory

main/build/MacOSX/monostub.mm
Bug 60378 - [VSFeedback Ticket] #513042 - Global search function, enter a letter collapse
=> [Ide] Fix different locales causing crashes in the IDE

main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs, main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/HighlightUrlExtension.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/InternalExtensionAPI/ITextEditorImpl.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextEditor.cs
When completion was triggered in an attribute value (`=""`) after typing the `"`, the completion window would attempt to determine the position by calling `TextViewMargin.ColumnToX`, which in turn would call `TextViewMargin.CreateLinePartLayout`.
Since the editor had just inserted the matching ", the line would not be present in the cache. CreateLinePartLayout would therefore build the line layout from scratch and then fire the
LineShown event.
`LineShown` appeared to exist purely to trigger `HighlightUrlExtension.Editor_LineShown`. If there was an URL in the line, this would add a marker... which immediately invalidates the cache and destroys the layout.
Hence the layout created by `TextViewMargin.CreateLinePartLayout` would become destroyed before being returned to its caller, and throw …
=> Fix incorrect completion popup position

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/MonoExecutionParameters.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Execution/MonoExecutionParametersWidget.cs
Fixes non-public bug <https://devdiv.visualstudio.com/web/wi.aspx?pcguid=011b8bdf-6d56-4f87-be0d-0092136884d9&id=527540>
`OnButtonResetClicked ()` needs to modify the original `MonoExecutionParameters` object that was passed into the `MonoExecutionParametersWidget.Load ()` method rather than creating a new `MonoExecutionParameters` object. Otherwise the changes will not be visible to the `DotNetRunConfigurationEditorWidget` object, and they will be discarded.
Preliminary verification
========================
I was able to save the cleared dialog as expected after I added this fix to a local build of the IDE.  I used the following testing scenario:
1. Create a new "Other > .NET > Console Project".
2. Under the project options, open "Run > Configurations > Default > Advanced \[tab\]" and …
=> [Ide] Fix "Mono runtime settings > Clear All Options"

main/src/addins/MacPlatform/Dialogs/MacOpenFileDialogHandler.cs, main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.addin.xml, main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.csproj, main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebugSourceFilesOptionsPanel.cs, main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DisassemblyView.cs, main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/Initializer.cs, main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/NoSourceView.cs, main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/SolutionHasDebugSourceFilesCondition.cs, main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/SourceCodeLookup.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Extensions/ISelectFileDialog.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/OpenFileDialog.cs
Card:
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/500134
This pull request adds support also for Portable .pdb(beside .mdb).
Adds UI familiar to VS2017 developer when source is missing instead going to Diasassembly view directly:
VSfM:
VS2017:
It also adds options to manage "Debug Sources Files" into Solution options
=> Debugger source lookups

main/src/core/MonoDevelop.Ide/MonoDevelop.Components/PathBar.cs
PathBar doesn't lose its alreadyHaveFocus flag when it loses focus. Fixed by
unsetting it in OnFocusOutEvent
Fixes BXC #60584
=> [PathBar] Stop PathBar stealing focus when path changes in text editor

main/src/addins/MacPlatform/Dialogs/MacOpenFileDialogHandler.cs
This code was recently introduced by me, I didn't realised NewDirectoryUrl can be `null`... This can happen when using search inside open dialog
=> Fixed NullReferenceException

main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/AttachToProcessDialog.cs, main/src/addins/MonoDevelop.Packaging/MonoDevelop.Packaging.Gui/GtkProjectNuGetBuildOptionsPanelWidget.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/NSViewContainer.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/VersionInformationTabPage.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.OptionPanels/TasksOptionsPanel.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.cs
The former is only called when explicitly invoking widget.Destroy.
The latter is called properly (i.e. when you destroy a dialog, it'll
recursively destroy all children, thus hitting OnDestroyed)
=> [Gtk] Switch overrides of Destroy to OnDestroyed.

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Parser/CSharpParsedDocument.cs, main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding.Parser/CSharpParsedDocumentTests.cs, main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding.Tests.csproj
The logic about this change is not keeping around all previous versions
of a CSharpParsedDocument. What happened here was:
* ParseOptions contained a ref to the old ParsedDocument
* ParsedDocument contained a reference to the current ParseOptions
* On the next query, both of these instances are kept alive in the new
ParsedDocument.
This caused a huge chain of live document+options+others to be alive
after many edits.
=> [C#] Fix performance issue with files opened for a long time

main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.QuickTasks/QuickTaskOverviewMode.IdleUpdater.cs
In files with > 10 tasks the quick task drawing infinite looped
because curIndex value need to be preserved in drawing step 2.
=> [SourceEditor] Fixed bug in quick task drawing.

main/src/core/MonoDevelop.Core/MonoDevelop.Core.Logging/FileLogger.cs
Main reason for this is that static constructors initialization failed, see stacktrace of NullReferenceException below...
`GettextCatalog.cctor` depends on `RuntimePreferences` being set(to figure out user Locale) but `RuntimePreferences` depends on `PropertyService` so it can get properties...
But `PropertyService.cctor` logs message "Didn't migrate any data"(or something like that) which makes full circle back to `RuntimePreferences` not being there yet for `GettextCatalog.cctor`.
For this issue to appear "MONODEVELOP_FILE_LOG_LEVEL" must be set(very rare) so FileLogger is created in 1st place and "MONODEVELOP_PROFILE" so `PropertyService` has something to log...
I found this testing StressTest.
Also our main logger(ConsoleLogger) which also logs into "Help->Open Logs Directory" doesn't …
=> Removed localising of headers(INFO, ERROR...) from FileLogger

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDocDocumentationProvider.cs, main/tests/Ide.Tests/MonoDevelop.Ide.Tests.csproj, main/tests/Ide.Tests/MonoDevelop.Ide/MonoDocDocumentationProviderTests.cs
=> Fixed '530737 - Information tooltips are not showing method docs, but

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/CheckForNuGetPackageUpdatesTaskRunner.cs
This allows other tasks to run while we're waiting for updated packages to be done. Amounted to around 6000ms.
=> [NuGet] Check for packages no longer blocking waits on bg thread

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/MessageService.cs
Don't use "special" top level windows (popups, pads, etc.) for message dialog auto-parenting.
First of all this is important for sheeting alerts on macOS, which should never be parented to pads or other "special" windows. But also in general we shouldn't use pads, or special windows (popups, menus, etc.) for dialog auto-parenting, not only on Mac.
(fixes bug #529486)
=> [529486][Ide] Improve dialog auto-parenting logic

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Tasks/TaskListEntry.cs
'JumpToPosition' isn't only called when double clicking an error in the error pad. It can also be called when we can jump to the first result.
For instance in an iOS project with the following code snippet (build for device):
```
class Foo : NSObject {
[Export ("b a r")]
void Bar () { }
}
```
Will throw this: `/Users/vidondai/Projects/iOSTest/iOSTest/ViewController.cs(31): error MT4160: Invalid character ' ' (0x20) found in selector 'b a r' for 'iOSTest.Foo.Bar()'`.
An error at a specific line of a specific file which we can jump to.
Because of that we needed to `ShowDocumentation ()` only when we can't open a specific file at a specific line. This is also a much better behavior since it's better to open a file in the IDE if possible than open the documentation (and we certainly don't …
=> [TaskListEntry] Fix 'JumpToPosition' to not show url on first jump

main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding.Refactoring/CSharpFindReferencesProviderTests.cs
When trying to run TestBug58060 individually it fails because the common TestBase doesn't call:
```
Runtime.Initialize (true);
DesktopService.Initialize ();
```
These two steps are needed for that unit-test to run successfully. I think we were just getting lucky that a previous test has called these methods for us.
=> Use a better TestBase

main/src/core/MonoDevelop.Core/MonoDevelop.Core/Runtime.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionFolder.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionItem.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.OptionPanels/BuildPanel.cs, main/src/core/MonoDevelop.Ide/gtk-gui/MonoDevelop.Ide.Gui.OptionPanels.BuildPanelWidget.cs, main/src/core/MonoDevelop.Ide/gtk-gui/gui.stetic, main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/SolutionTests.cs
which speeds up building projects with many project references
Here are some numbers, notice that all this numbers assume projects were built before inside IDE(this is needed for "unmodified projects" detection)
- Modify file in MonoDevelop.Debugger project and press Cmd+K(Build this project) and right after Cmd+Return(start debugging)
- before: ~9sec total: ~5.5 sec to build MD.Debugger + ~3.5sec to build MD.Startup
- after: ~3sec total: ~3sec to build MD.Debugger and ~0sec to build MD.Startup(0 invoking MSBuild, since Startup or any reference didn't change)
- Modify MD.CSharpBinding and use Cmd+K
- before: ~8.5sec
- after: ~4.5ses
- Modify MD.Startup and use Cmd+B(build all), this is most extreme one
- before:~18sec
- after:~2.5sec
Notice that all this differences come from MSBuild …
=> Added "Skip building unmodified projects" setting

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.NodeBuilders/PackageDependencyNode.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.NodeBuilders/SdkDependenciesNode.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.NodeBuilders/SdkDependenciesNodeBuilder.cs
Fixed bug #56455 - Show SDK for project when not restored
https://bugzilla.xamarin.com/show_bug.cgi?id=56455
When a new .NET Core project is created the Dependencies - SDK folder
shows no items until the restore is completed. Now the SDK dependency
is shown (e.g. NETStandard.Library or Microsoft.NETCore.App) whilst
the dependencies are being restored and the updated information has
not yet been returned from MSBuild. This mirrors the behaviour of
Visual Studio on Windows.
=> [DotNetCore] Show SDK information before dependencies are restored

main/external/fsharpbinding/MonoDevelop.FSharpBinding/MonoDevelop.FSharp.fsproj
I keep hitting bugs when using portable pdb that causes the IDE to
crash while debugging the IDE itself. This is a temporary fix until the issues
are fixed upstream in the compiler.
=> [F#] Switch debugging over to mdb format

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutput.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputWidget.cs
This adds support for saving different build logs into a merged .binlog file. Seems to work ok, although the structure of the saved file is different from what the "live" build log shows, as the code to save the logs removes the BuildStarted/BuildFinished events, except for the 1st *Started one and the last *Finished one, as it seems to not behave better with several BuildStarted/Finished pairs.
So, @KirillOsenkov what would be the best way to do so?
=> Add support for saving several build logs to a single .binlog

main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/MDMenuItem.cs
This fixes leaks of whole projects caused by the editor context menu on refactoring.
=> [Mac] Fix MDMenu leak when using async updates

main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
MSBuildToolsPath has the correct directory for MSBuild folder in windows and mac (probably in linux too), then there is no need to add additional changes to current path:
The conditional in MSBuild_OSS_BinDir was failing and giving a empty value, without this property correctly setted, <HintPath>$(MSBuild_OSS_BinDir)XXXXX.dll</HintPath> has a wrong path and 
it didn't fail to compile becuase is taking the `Microsoft.Build.dll` from GAC folder which is different version (older) than the MSBuildToolsPath and it didnt' have some types.
`/Library/Frameworks/Mono.framework//Versions/5.8.0/lib/mono/gac/Microsoft.Build/14.0.0.0__b03f5f7f11d50a3a/Microsoft.Build.dll `
Fixed this in MonoDevelop.Core.csproj and MonoDevelop.Ide.csproj
=> Fixes Microsoft.Build reference paths to use MSBuildToolsPath property

main/src/core/MonoDevelop.Core/MonoDevelop.Core.Instrumentation/TimeCounter.cs
Fixes crash that would happen if a counter is enabled after a TimeCounter
is created for it. This is a better fix for #3507.
=> Fix UI testing

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs, main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/DotNetCoreProjectTests.cs, main/tests/test-projects/DotNetCoreMultiTargetFrameworkProperty/DotNetCoreMultiTargetFrameworkProperty.csproj, main/tests/test-projects/DotNetCoreMultiTargetFrameworkProperty/DotNetCoreMultiTargetFrameworkProperty.sln, main/tests/test-projects/DotNetCoreMultiTargetFrameworkProperty/Frameworks.props
VSTS 540666
An SDK style project that defined the <TargetFrameworks> element to
be another imported MSBuild property would fail to restore. The
unevaluated MSBuild property value would be used and result in an
unknown target framework being used causing the restore to fail.
<Project Sdk="Microsoft.NET.Sdk">
<Import Project="Frameworks.props" />
<PropertyGroup>
<TargetFrameworks>$(TheFramework)</TargetFrameworks>
</PropertyGroup>
</Project>
MSBuild property TheFramework is defined in the Frameworks.props file.
Now the evaluated property value is used for the TargetFrameworks
property.
=> [Core] Support .NET Core multi target framework using MSBuild property

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTests.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs, main/tests/test-projects/TizenProject/Class1.cs, main/tests/test-projects/TizenProject/TizenProject.csproj, main/tests/test-projects/TizenProject/TizenProject.sln
Fixed bug #57307 Unable to use Xamarin.iOS10 with TargetFramework
https://bugzilla.xamarin.com/show_bug.cgi?id=57307
The target framework of an SDK style project is no longer restricted.
This allows Tizen projects to be loaded without the error message
"Project does not support framework 'Tizen,Version=v4.0'" being
displayed. Tizen projects have a Tizen.NET package reference which
imports MSBuild .props file that defines the Tizen target framework.
The MSBuild.Sdk.Extras NuGet package is now also supported so
SDK style projects can use target frameworks that this NuGet package
supports, such as Xamarin.iOS and MonoAndroid.
On building an unknown target framework, that is not defined by
any used NuGet package references, a build error that indicates
the framework is not supported will …
=> [DotNetCore] Allow unknown target framework projects to be loaded

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputProcessor.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/MSBuildOutputProcessor.cs
* Remove "Task Message" opening/closing nodes
* Don't display "empty" nodes (nodes that have neither a message,
a warning or an error
* Don't add closing Message node to nodes
=> [Ide] Reduce clutter in normal view with just some simple filtering

main/external/fsharpbinding/MonoDevelop.FSharp.Gui/gtk-gui/MonoDevelop.FSharp.Gui.FSharpCompilerOptionsWidget.cs, main/external/fsharpbinding/MonoDevelop.FSharp.Gui/gtk-gui/gui.stetic
(fixes bug #528908)
@nosami we've discussed that we want to add a documentation file path entry, but it's not as simple as expected. We can't use the normal Gtk file entry, cause it won't open a native file picker. For that purpose we have `MonoDevelop.Components.FileEntry` ([link](https://github.com/mono/monodevelop/blob/master/main/src/core/MonoDevelop.Ide/MonoDevelop.Components/FileEntry.cs)) but we can't use it without (a) referencing `MonoDevelop.Ide` and (b) using stetic (external widget import is broken). So I'd say, let's postpone that for the full preferences redesign, when we'll rewrite all the preference/option panels.
=> [528908][F#] Fix compiler configuration panel alignments

main/src/addins/MacPlatform/Dialogs/MacAlertDialogHandler.cs
In some cases, a window should show multiple alerts simultaneously.
At the moment if a window needs to show two alerts at the same time one of them will be displayed in a proper manner (sliding from the top and attached to the title bar). The second alert, however, will be just "floating" in the air.
Example:
Ideally, alerts should be queued and shown one by one. Like this:
=> Queue alert sheets

main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeFixMenuService.cs
Hard to tell from screenshot what really caused that I guess it's a
code refactoring provider for an action they've empty descriptions.
So filtering out options for them fixes the issue.
=> Fixed '530643 - Empty "options for" entry in fix menu'

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectReference.cs, main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/SharedAssetsProjectTests.cs
A project reference to a shared project that exists was shown as
invalid in the Solution window. It would have an error icon and have
the tooltip 'Project not found.' even though the shared project did
exist.
The problem was that the code was changed in commit d40ba5fec794edbe14ccf58c1e177944cd2a6fe9
so that if a project was not a DotNetProject then it was marked as
invalid even if it existed. The SharedAssetsProject class does
not derive from DotNetProject so the project was treated as though
it could not be found.
=> [Core] Fix project reference to shared project considered invalid

main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj, main/src/core/MonoDevelop.Core/MonoDevelop.Core/Runtime.cs
We don't deploy the 3 other MSBuild dlls, so let's not deploy this one.
MSBuild is taken from the toolset that's installed separately from MonoDevelop. Otherwise we might run into situations where our own copy is loaded instead of the official one and cause a mismatch.
=> Don't deploy Microsoft.Build.Tasks.Core.dll.

main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/AssemblyContext.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/SystemAssemblyService.cs
Introduce SystemAssemblyService.IsManagedAssembly() (same as in Mono.Addins). Avoid throwing a first-chance exception when trying to read native .dlls.
=> Avoid multiple first-chance exceptions when registering packages

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Resolver/TextEditorResolverProvider.cs
TextEditorResolverProvider needs to be removed - resolving doesn't
work this way. Fortunately it's only used in some very old scenarios.
=> Fixed '527496 - Error "while update show code surroundings window"'

main/src/addins/MonoDevelop.UnitTesting.NUnit/MonoDevelop.UnitTesting.NUnit/NUnitAssemblyTestSuite.cs, main/src/addins/MonoDevelop.UnitTesting.NUnit/MonoDevelop.UnitTesting.NUnit/NUnitProjectTestSuite.cs, main/src/addins/MonoDevelop.UnitTesting.NUnit/NUnit3Runner/NUnitTestRunner.cs, main/src/addins/MonoDevelop.UnitTesting.NUnit/NUnitRunner/NUnitTestRunner.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs
This PR changes the way dependencies of a test project are computed by relying on the MSBuild machinery instead of being limited to only the project model.
This fixes cases where assembly references are computed on the fly e.g. when custom `ReferencePath` are specified in the project so that `<Reference />` with no hint path are still resolved (something the old system would mistakenly think of as GAC assemblies).
The commits changes the API for gathering dependencies to be asynchronous and applies the same sort of filtering as before to only load dependencies that wouldn't be otherwise loaded.
An exception here is that facades are pulled in by the underlying call to `GetReferences` without a way to differentiate them from other references, that causes assembly load errors down the line …
=> [NUnit] Properly enumerate project assembly reference dependencies. 

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/HelpService.cs
Since we know it's going to fail anyway, do not attempt to load Monodoc. This prevents a first-chance exception in the startup path.
=> Avoid loading Monodoc on Windows

main/src/addins/MonoDevelop.UnitTesting/Services/AbstractUnitTestEditorExtension.cs
I know, but other option about a building tested project, before testing.  Bug report was about building tests project.
https://devdiv.visualstudio.com/DevDiv/_workitems?id=a2108d31-086c-4fb0-afda-097e4cc46df4&_a=query&fullScreen=true
=> Fixed  ignoring  "build before running" setting when running unit test

main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/GitIgnore.txt
Creating a new project with a .gitignore file would add the solution
preferences file from the .vs directory to the local Git repository.
The solution preferences file should not be included in the Git
repository by default.
=> [Git] Add .vs directory to .gitignore used with new projects

Makefile
Reproduce by installing Workbooks 1.4 RC1 and enabling terminal usage from its main menu. This adds    `/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin` to a file in `/etc/paths.d/`, introducing spaces in `$PATH`.
=> Makefile: fix all-recursive when $PATH has spaces

main/src/addins/WindowsPlatform/WindowsPlatform/ImageHelper.cs
This should be a good safe tactical fix (WindowsPlatform only), no Xwt changes needed.
=> Avoid a first-chance exception in WindowsPlatform ImageHelper.

main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs
text editor (misaligned lines and text)'
It's a side effect of the text editor optimizations - the editor
doesn't repaint it self so often anymore :).
=> Fixed '531459 - Initial opening of file results in bad rendering of

main/src/core/MonoDevelop.Ide/MonoDevelop.Components/GtkWorkarounds.cs
This avoids a first-chance exception when opening the editor
=> Avoid calling a non-existing libgtk-quartz .dll on Windows

main/src/addins/MonoDevelop.UnitTesting/Services/BinaryResultsStore.cs
This avoids another first-chance exception and unnecessary expensive XmlSerializer initialization until it's actually needed. This used to happen on startup with this stack:
```
> MonoDevelop.UnitTesting.BinaryResultsStore.BinaryResultsStore Line 38 C# Symbols loaded.
[Native to Managed Transition]  Annotated Frame
[Managed to Native Transition]  Annotated Frame
MonoDevelop.UnitTesting.SolutionFolderTestGroup.SolutionFolderTestGroup Line 48 C# Symbols loaded.
MonoDevelop.UnitTesting.SolutionFolderTestGroup.CreateTest Line 61 C# Symbols loaded.
MonoDevelop.UnitTesting.SystemTestProvider.CreateUnitTest Line 43 C# Symbols loaded.
MonoDevelop.UnitTesting.UnitTestService.BuildTest Line 359 C# Symbols loaded.
MonoDevelop.UnitTesting.UnitTestService.RebuildTests Line 346 C# Symbols loaded. …
```
=> Make UnitTesting BinaryResultsStore lazy initialize XmlSerializer

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectReference.cs, main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/SharedAssetsProjectTests.cs
A project reference to a shared project that exists was shown as
invalid in the Solution window. It would have an error icon and have
the tooltip 'Project not found.' even though the shared project did
exist.
The problem was that the code was changed in commit d40ba5fec794edbe14ccf58c1e177944cd2a6fe9
so that if a project was not a DotNetProject then it was marked as
invalid even if it existed. The SharedAssetsProject class does
not derive from DotNetProject so the project was treated as though
it could not be found.
=> [d15-6][Core] Fix project reference to shared project considered invalid

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild.Conditions/ConditionExpression.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild.Conditions/ConditionFactorExpresion.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild.Conditions/ConditionRelationalExpression.cs, main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/MSBuildProjectTests.cs, main/tests/UnitTests/Util.cs, main/tests/test-projects/msbuild-tests/condition-relational-expressions.targets
MSBuild has intrinsic support for comparing double and Version values. See http://source.dot.net/#Microsoft.Build/Evaluation/Conditionals/NumericComparisonExpressionNode.cs
Example file:
https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Extensions.Tasks/msbuildExtensions/Microsoft/Microsoft.NET.Build.Extensions/Microsoft.NET.Build.Extensions.NETFramework.targets#L18
=> Add support for comparing Versions in ConditionExpression

main/Directory.Build.props, main/msbuild/ReferencesRoslyn.props, main/msbuild/ReferencesVSEditor.props, main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj, main/src/core/MonoDevelop.Core/packages.config
Update VS Editor to 15.6.161-preview since that's the version referenced by Roslyn.
Remove a reference to Text.Internal.
Add a reference to Humanizer.Core 2.2.0. It is now a prerequisite.
=> Update Roslyn dependencies.

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CSharpCompletionTextEditorExtension.cs
defined keyword, auto-completion window is not displayed.'
Roslyn supports backspace completion now as well but introduced an
option for it. VS4Mac had this feature always on without any options.
=> Fixed '536946 - [completion window] After clearing last word from any

main/src/addins/MacPlatform/MainToolbar/SelectorView.cs
This PR fixes a couple of issues with the configuration selector (Toolbar), icluding weird behaviour on HighSierra.
* [53733](https://bugzilla.xamarin.com/show_bug.cgi?id=53733): broken Tab-Focus
* [60722](https://bugzilla.xamarin.com/show_bug.cgi?id=60722): wrong hit area calculation
* [59751](https://bugzilla.xamarin.com/show_bug.cgi?id=59751): Layout/Rendering issues on HighSierra
~~TODO: the SelectorView is still not really accessible, it is possible to navigate between the cells with the Tab key,  but VoiceOver sees only one big area without any possible action.~~ done in 
8827e7a
=> [Toolbar][Mac] Fix various configuration selector issues

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTests.cs
Ensure projects are disposed after running tests to prevent the file
watcher not being disposed and stopping the unit tests from finishing
on the build server.
=> [DotNetCore] Fix tests timing out on build server

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTests.cs
Ensure projects are disposed after running tests to prevent the file
watcher not being disposed and stopping the unit tests from finishing
on the build server.
=> [d15-6][DotNetCore] Fix tests timing out on build server

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/ProjectNodeBuilder.cs
On loading the Xamarin.Forms solution, with NuGet restore enabled,
the UI thread would be stuck in a loop trying to refresh the project
folders. When a project uses a shared project the re-evaluation
would cause the shared files to be removed from the project. Then
an attempt was made to refresh a parent folder for that file being
removed, if the project had the file watcher enabled. Since the file
was outside the project directory the while loop would not finish
and cause the UI thread to be blocked.
=> [Core] Fix UI hang on loading Xamarin.Forms solution

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/ProjectNodeBuilder.cs
On loading the Xamarin.Forms solution, with NuGet restore enabled,
the UI thread would be stuck in a loop trying to refresh the project
folders. When a project uses a shared project the re-evaluation
would cause the shared files to be removed from the project. Then
an attempt was made to refresh a parent folder for that file being
removed, if the project had the file watcher enabled. Since the file
was outside the project directory the while loop would not finish
and cause the UI thread to be blocked.
=> [d15-6][Core] Fix UI hang on loading Xamarin.Forms solution

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/AsyncCriticalSection.cs
The code before would hold the lock while exiting, thus forcing the continuation to run under the lock. This ended up causing Exit tasks to be chained on the same stack frame, ending up in a stack overflow for solutions which queued a lot of builders.
Fixes #3649
=> [Core] Fix a stack overflow exception bubbled via the msbuild builder

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/AsyncCriticalSection.cs
The code before would hold the lock while exiting, thus forcing the continuation to run under the lock. This ended up causing Exit tasks to be chained on the same stack frame, ending up in a stack overflow for solutions which queued a lot of builders.
Fixes #3649
=> [d15-6][Core] Fix a stack overflow exception bubbled via the msbuild builder

main/src/core/MonoDevelop.Ide/ExtensionModel/Commands.addin.xml, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbarCommandHandlers.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbarController.cs
This PR adds a "Run Command" (VS Code binding: Ctrl+Shift+P, Mac: Cmd+Shift+P) command to search commands and shows the appropriate category in the global search menu.
(fixes bug #540610)
(closes #3479)
=> [540610][Ide] Add Find Command command

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
Two optimizations: first, the default run configuration required for comparing
is generated only once and then cached. Generating the configuration is slow
because it needs a project evaluation.
Second, invalidation of the assembly and package references caches is now
instant. Instead of having to acquire a lock to clear the cache, there is now
a flag that can be set to signal that the cache is invalid and needs refresh.
Also added some logging.
This should fix VSTS issue #530382.
=> Optimize project save

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputWidget.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DocumentToolbar.cs
* Place buttons on the right, as was specified in the designs
* Add a11y to the toolbar buttons
* Make 'Save' button look like in other pads' toolbars
=> [Ide] Improve BuildOutputWidget's toolbar

main/src/core/MonoDevelop.Core/MonoDevelop.Core.Execution/RemoteProcessConnection.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Core/FileService.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Core/ProgressMonitor.cs
Most notably, optimize the ProgressMonitoring stack. The old code would create lambdas with captures for every progress monitor update. This was optimized to use a cached static delegate and no capture lambdas with a passed state parameter.
=> [Core] Optimize SynchronizationContext users

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProjectInstance.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildPropertyEvaluated.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildPropertyGroupEvaluated.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs, main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/ConfigurationMergingTests.cs, main/tests/test-projects/test-configuration-merging/TestConfigurationMerging10.csproj, main/tests/test-projects/test-configuration-merging/TestConfigurationMerging9.csproj, main/tests/test-projects/test-configuration-merging/TestConfigurationMerging9.csproj.saved, main/tests/test-projects/test-configuration-merging/TestConfigurationMerging9.csproj.saved2
After saving a project, if properties are changed in the main group, make
sure the initially evaluated values for those properties are not used
anymore to decide wether or not the property has to be serialized,
since the values may not be valid anymore.
Fixes VSTS bug #518933.
=> Fix serialization issue with ItemProperty and MergeToProject

main/src/addins/MacPlatform/Dialogs/MacOpenFileDialogHandler.cs
Changing the layout of the NSSavePanel AccessoryView does not work on High Sierra, which seems to always enforce initial constraints resulting in a wrong layout:
With this patch the accessory view layout remains always the same and it just enables/disables the "Close current workspace" checkbox:
(fixes bug #61102)
=> [61102][Mac] Fix open project dialog on High Sierra

main/src/addins/MacPlatform/Dialogs/MacOpenFileDialogHandler.cs
#3646 for `d15-6`
Changing the layout of the NSSavePanel AccessoryView does not work on High Sierra, which seems to always enforce initial constraints resulting in a wrong layout:
With this patch the accessory view layout remains always the same and it just enables/disables the "Close current workspace" checkbox:
(fixes bug #61102)
=> [d15-6][61102][Mac] Fix open project dialog on High Sierra

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/DefaultMSBuildEngine.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildEngine.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildEngineV12.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProperty.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildPropertyEvaluated.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildPropertyGroupEvaluated.cs, main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/ProjectLoadSaveTests.cs, main/tests/test-projects/property-save-test/default-value-save-2.csproj, main/tests/test-projects/property-save-test/default-value-save-2.csproj.saved, main/tests/test-projects/property-save-test/default-value-save-2.csproj.saved2, main/tests/test-projects/property-save-test/default-value-save-3.csproj, main/tests/test-projects/property-save-test/default-value-save-3.csproj.saved, main/tests/test-projects/property-save-test/default-value-save.csproj, main/tests/test-projects/property-save-test/default-value-save.csproj.saved, main/tests/test-projects/property-save-test/default-value-with-import-save-2.csproj, main/tests/test-projects/property-save-test/default-value-with-import-save-2.csproj.saved, main/tests/test-projects/property-save-test/default-value-with-import-save-2.csproj.saved2, main/tests/test-projects/property-save-test/default-value-with-import-save.csproj, main/tests/test-projects/property-save-test/default-value-with-import-save.csproj.saved, main/tests/test-projects/property-save-test/empty-property-save.csproj, main/tests/test-projects/property-save-test/empty-property-save.csproj.saved, main/tests/test-projects/property-save-test/test-2.props, main/tests/test-projects/property-save-test/test.props, main/tests/test-projects/roundtrip-test-projects/default-value-existing-save.csproj
A new flag is generated while evaluating properties: DefinedMultipleTimes.
This flag is used to determine if a property is defined only once in the
project file, or if it is defined more than once (or in other imported
project files). In the first case, property definitions that set the default
value can be safely removed, since we know that the property definition is not
overriding another definition.
=> Fix bug #40942 - XS is leaving empty properties in the project file

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs
When the flag for clearing the references cache is set, clear the whole
cache. The current implementation was just forcing a re-query of the
configuration being requested, and that's not enough. Cached references
for all configurations must be cleared.
=> Fix potential project save issue

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Parser/CSharpParsedDocument.cs, main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeIssues/CodeDiagnosticRunner.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
The old code fixes code runs diagnostics manually, so compiler diagnostics are skipped. We need to retain backwards compat here, will enable the new error system in editorFeatures
cc @mrward
=> [Refactoring] Fix quick fixes not appearing for compiler errors

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs, main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/ProjectTests.cs
If a project has a default namespace of '1' then adding a new C#
file from a template to the project would throw a null reference
exception in the FileTemplateTagsModifier.ModifyTags method since
the namespace returned from DotNetProject.GetDefaultNamespace was
null. The problem was that the sanitized namespace for the default
namespace was null.
VSTS 524637
=> [Core] Fix failure to create add new file to project

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs, main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/ProjectTests.cs
If a project has a default namespace of '1' then adding a new C#
file from a template to the project would throw a null reference
exception in the FileTemplateTagsModifier.ModifyTags method since
the namespace returned from DotNetProject.GetDefaultNamespace was
null. The problem was that the sanitized namespace for the default
namespace was null.
VSTS 524637
=> [d15-6][Core] Fix failure to create add new file to project

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/RegisteredPackageSourcesViewModelTests.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageSourceViewModelChecker.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/RegisteredPackageSourcesViewModel.cs
Switch to using an async await instead of Task.Wait when verifying
package sources are valid in Preferences - NuGet - Sources. Also
disabled checking package sources when running unit tests.
VSTS 534264
=> [NuGet] Remove Task.Wait when checking package sources

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/RegisteredPackageSourcesViewModelTests.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageSourceViewModelChecker.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/RegisteredPackageSourcesViewModel.cs
Switch to using an async await instead of Task.Wait when verifying
package sources are valid in Preferences - NuGet - Sources. Also
disabled checking package sources when running unit tests.
VSTS 534264
=> [d15-6][NuGet] Remove Task.Wait when checking package sources

main/src/addins/MonoDevelop.UnitTesting.NUnit/MonoDevelop.UnitTesting.NUnit/NUnitAssemblyTestSuite.cs, main/src/addins/MonoDevelop.UnitTesting.NUnit/MonoDevelop.UnitTesting.NUnit/NUnitProjectTestSuite.cs
The Unit Tests window would not show any unit tests when the project
contained an NUnit PackageReference.
Also fixed the load error not being cleared from the Unit Tests window.
=> [NUnit] NUnit PackageReference not recognized

main/src/addins/MonoDevelop.UnitTesting.NUnit/MonoDevelop.UnitTesting.NUnit/NUnitAssemblyTestSuite.cs, main/src/addins/MonoDevelop.UnitTesting.NUnit/MonoDevelop.UnitTesting.NUnit/NUnitProjectTestSuite.cs
The Unit Tests window would not show any unit tests when the project
contained an NUnit PackageReference.
Also fixed the load error not being cleared from the Unit Tests window.
=> [d15-6][NUnit] NUnit PackageReference not recognized

.gitignore, main/contrib/ICSharpCode.Decompiler/ICSharpCode.Decompiler.csproj, main/src/addins/CSharpBinding/CSharpBinding.csproj, main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser.csproj, main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj, main/src/core/MonoDevelop.Core/packages.config, main/tests/UnitTests/UnitTests.csproj
Switches for everything (Roslyn), but MonoDevelop.AssemblyBrowser.
AssemblyBrowser still references our own version of ICSharpCode.Decompiler.dll (0.0.0.0) and it is only copied to build/addins, not build/bin.
This is to ensure that both versions of Decompiler can co-exist side-by-side.
In the master branch a different approach is chosen: https://github.com/mono/monodevelop/pull/3682
=> Switch to new ICSharpCode.Decompiler.dll

main/src/addins/MonoDevelop.UnitTesting.NUnit/NUnit3Runner/NUnitTestRunner.cs
When a test used an Ignore attribute the Unit Tests window would
show a load error for the entire project and prevent any tests from
being run. The problem was that the load error check was looking for
a _SKIPREASON property on every test-suite xml element in the xml
produced by NUnit v3. When an Ignore attribute is used the xml has a
_SKIPREASON property for the test case and that was being found and
treated as an error. To avoid this only a test-suite xml element that
has a type of Assembly and has a runstate of NotRunnable is checked
for a _SKIPREASON.
VSTS 544671
=> [NUnit] Fix load error displayed for ignored tests

main/src/addins/MonoDevelop.UnitTesting.NUnit/NUnit3Runner/NUnitTestRunner.cs
When a test used an Ignore attribute the Unit Tests window would
show a load error for the entire project and prevent any tests from
being run. The problem was that the load error check was looking for
a _SKIPREASON property on every test-suite xml element in the xml
produced by NUnit v3. When an Ignore attribute is used the xml has a
_SKIPREASON property for the test case and that was being found and
treated as an error. To avoid this only a test-suite xml element that
has a type of Assembly and has a runstate of NotRunnable is checked
for a _SKIPREASON.
VSTS 544671
=> [d15-6][NUnit] Fix load error displayed for ignored tests

main/src/core/MonoDevelop.Ide/ExtensionModel/Commands.addin.xml, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbarCommandHandlers.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbarController.cs
#3658 for `d15-6`
This PR adds a "Run Command" (VS Code binding: Ctrl+Shift+P, Mac: Cmd+Shift+P) command to search commands and shows the appropriate category in the global search menu.
(fixes bug #540610)
(closes #3479)
=> [15.6][540610][Ide] Add Find Command command

main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextEditor.cs
Check that TextEditor isn't null before accessing it.
Fixes VSTS #513338
=> [TextEditor] IDE crash when closing C# files

main/src/addins/MonoDevelop.UnitTesting/Services/UnitTestService.cs
The NuGet package install/remove event handler method was calling
itself. Removed the duplicate event handler method since it is not
needed.
=> [UnitTesting] Fix stackoverflow when installing NuGet packages

main/src/addins/MonoDevelop.UnitTesting/Services/UnitTestService.cs
The NuGet package install/remove event handler method was calling
itself. Removed the duplicate event handler method since it is not
needed.
=> [d15-6][UnitTesting] Fix stackoverflow when installing NuGet packages

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/DefaultMSBuildEngine.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildEngine.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildEngineV12.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProperty.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildPropertyEvaluated.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildPropertyGroupEvaluated.cs, main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/ProjectLoadSaveTests.cs, main/tests/test-projects/property-save-test/default-value-save-2.csproj, main/tests/test-projects/property-save-test/default-value-save-2.csproj.saved, main/tests/test-projects/property-save-test/default-value-save-2.csproj.saved2, main/tests/test-projects/property-save-test/default-value-save-3.csproj, main/tests/test-projects/property-save-test/default-value-save-3.csproj.saved, main/tests/test-projects/property-save-test/default-value-save.csproj, main/tests/test-projects/property-save-test/default-value-save.csproj.saved, main/tests/test-projects/property-save-test/default-value-with-import-save-2.csproj, main/tests/test-projects/property-save-test/default-value-with-import-save-2.csproj.saved, main/tests/test-projects/property-save-test/default-value-with-import-save-2.csproj.saved2, main/tests/test-projects/property-save-test/default-value-with-import-save.csproj, main/tests/test-projects/property-save-test/default-value-with-import-save.csproj.saved, main/tests/test-projects/property-save-test/empty-property-save.csproj, main/tests/test-projects/property-save-test/empty-property-save.csproj.saved, main/tests/test-projects/property-save-test/test-2.props, main/tests/test-projects/property-save-test/test.props, main/tests/test-projects/roundtrip-test-projects/default-value-existing-save.csproj
A new flag is generated while evaluating properties: DefinedMultipleTimes.
This flag is used to determine if a property is defined only once in the
project file, or if it is defined more than once (or in other imported
project files). In the first case, property definitions that set the default
value can be safely removed, since we know that the property definition is not
overriding another definition.
=> Fix bug #40942 - XS is leaving empty properties in the project file (15-6)

main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/BreakpointPad.cs
The Go to breakpoint command needs to be registered with the command manager
before it will be displayed in the menu
=> [Debugger] The Go to breakpoint menu item doesn't appear

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.OptionPanels/PortableRuntimeOptionsPanel.cs, main/tests/Ide.Tests/MonoDevelop.Ide.Projects/PclToProjectJsonConversionTests.cs, main/tests/Ide.Tests/MonoDevelop.Ide.Tests.csproj, main/tests/test-projects/XamarinFormsPcl/XamarinFormsPcl.sln, main/tests/test-projects/XamarinFormsPcl/XamarinFormsPcl/XamarinFormsPcl-migrated.csproj, main/tests/test-projects/XamarinFormsPcl/XamarinFormsPcl/XamarinFormsPcl.csproj, main/tests/test-projects/XamarinFormsPcl/XamarinFormsPcl/packages.config
When a PCL project was migrated to project.json the imports for
MSBuild .targets were not removed. These imports are added by NuGet
into the generated ProjectName.nuget.props and
ProjectName.nuget.targets files on restoring when a project.json file
is used. Having the import in the project file results in the import
being used twice. When a PCL project that uses Xamarin.Forms was
migrated to project.json the build would fail with an error:
Error XF001: Xamarin.Forms targets have been imported multiple times.
Please check your project file and remove the duplicate import(s).
Now on migrating the imports from the packages that were used by
the project are removed from the project file.
VSTS 552280
=> [d15-6][Ide] Remove NuGet imports when migrating to project.json

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.OptionPanels/PortableRuntimeOptionsPanel.cs, main/tests/Ide.Tests/MonoDevelop.Ide.Projects/PclToProjectJsonConversionTests.cs, main/tests/Ide.Tests/MonoDevelop.Ide.Tests.csproj, main/tests/test-projects/XamarinFormsPcl/XamarinFormsPcl.sln, main/tests/test-projects/XamarinFormsPcl/XamarinFormsPcl/XamarinFormsPcl-migrated.csproj, main/tests/test-projects/XamarinFormsPcl/XamarinFormsPcl/XamarinFormsPcl.csproj, main/tests/test-projects/XamarinFormsPcl/XamarinFormsPcl/packages.config
When a PCL project was migrated to project.json the imports for
MSBuild .targets were not removed. These imports are added by NuGet
into the generated ProjectName.nuget.props and
ProjectName.nuget.targets files on restoring when a project.json file
is used. Having the import in the project file results in the import
being used twice. When a PCL project that uses Xamarin.Forms was
migrated to project.json the build would fail with an error:
Error XF001: Xamarin.Forms targets have been imported multiple times.
Please check your project file and remove the duplicate import(s).
Now on migrating the imports from the packages that were used by
the project are removed from the project file.
VSTS 552280
=> [Ide] Remove NuGet imports when migrating to project.json

main/src/core/MonoDevelop.Core/MonoDevelop.FSW/FileSystemWatcher.cs
A TypeInitializationException is thrown when a .NET Core project
is used on Windows. On Windows when a DllImport cannot be found a
DllNotFoundException is thrown not an EntryPointNotFoundException. To
avoid this the native Mac support check is now only run when the
platform is Mac.
=> [Core] Fix TypeInitializationException using file watcher on Windows

main/src/core/MonoDevelop.Ide/MonoDevelop.Components/GtkWorkarounds.cs
This matches these two functions to the C return types
See https://github.com/bratsche/gtk/blob/393f44073cf81c17d8c84138d3fa0549b6f07cf4/gdk/quartz/gdkkeys-quartz.c#L778
https://github.com/bratsche/gtk/blob/393f44073cf81c17d8c84138d3fa0549b6f07cf4/gdk/quartz/gdkglobals-quartz.c#L53
=> [Ide] Use void instead of bool for pinvoke return types

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/MonoExecutionParameters.cs
The option is `--verify-all`, not `--verifyAll`.
This was discovered while trying to debug something that needed the `--verify-all` option set. MonoDevelop just hung when pressing F5 to start the program. After enabling the show terminal option, I discovered that it said "unknown option --verifyAll".
=> Fix --verify-all MonoArg attribute

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/PadTreeView.cs
GtkTreeView has a feature that has an interactive search when you press
cmd/ctrl+f which we don't want to use. There is a bug in Gtk that reenables
the search when the model is set, so we need to hack around that
This fixes it for all uses of PadTreeView, including Search Results pad, Errors
pad, Breakpoints pad and many others.
Fixes VSTS #551327
=> [Padtree] Disable the default treeview search feature

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/RecentOpen.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
RecentFiles.GetProjects sorts the favourited projects first in the list, which
isn't what we want when opening the most recently used project. Create a
MostRecentlyUsedProject property and use it instead
Fixes VSTS #536619
=> [IDE] Previous solution not opened if projects are favourited

main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs
This fixes issues in languages like Japanese and Chinese where
the text isn't visible until it gets committed from the preedit
buffer.
Fixes VSTS #535828
=> [Editor] Reset IM context when filtering keypresses

main/src/core/MonoDevelop.Ide/MonoDevelop.Components/ContextMenuExtensionsMac.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/PadTreeView.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads/ErrorListPad.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Tasks/CommentTasksView.cs
Use the cross platform ContextMenu on for the Error and Tasks pads' popup menu.
Means that
- An ugly Gtk menu isn't used on Cocoa
- Fixes refcycles and leaks
Create a ColumnSelectorMenu for automatically generating context menus for
hiding or showing treeview columns
=> [IDE] Use ContextMenu on the Errors and Tasks pad

main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser.addin.xml
Add explicit dependency on our copy of ICSharpCode.Decompiler, otherwise a newer copy is loaded from build\bin.
=> Fix VSTS 555349 - Assembly browser doesn't work

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads/ErrorListPad.cs
The focus chain for the error pad is set to only let the Build Output be focused, but if Build Output is hidden, then nothing can be focused and so the autohide
closes the pad.
Add the scrolled window as a secondary focus widget as a back up if the Build
Output is hidden.
Fixes VSTS #561864
=> [IDE] Errors pad autohides after a few moments

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/WindowCommands.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DocumentSwitcher.cs
Showing the document switcher when there were no pads or documents left a blank
window in the top left corner of the screen because we were trying to destroy
it inside the constructor. Instead just pass if there's content or not to the
caller and let it decide what to do
Fixes VSTS #561851
=> [IDE] Don't show the document switcher if no pads/documents

main/src/core/MonoDevelop.Core/MonoDevelop.Core/Gettext.cs
OS X seems to have some cultures that do not exist in .NET. Fallback to default when they're not found.
Fixes VSTS #532970
=> [Core] Add a fallback when a given culture does not exist in .NET

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads/ErrorListPad.cs
(#3783 for `d15-6`)
The focus chain for the error pad is set to only let the Build Output be focused, but if Build Output is hidden, then nothing can be focused and so the autohide
closes the pad.
Add the scrolled window as a secondary focus widget as a back up if the Build
Output is hidden.
Fixes VSTS #561864
(cherry picked from commit 1d6a8648da9661f5d16934a24a2eb1faa5323b83)
=> [15.6][IDE] Errors pad autohides after a few moments

main/src/core/MonoDevelop.Ide/options/KeyBindingSchemeVSCode-mac.xml
working when select 'Visual Studio Code' Scheme in Key Binding
Section'
https://devdiv.visualstudio.com/DevDiv/_workitems?id=553389
=> Fixed 'VSTS Bug 553389: [Feedback] Autocomplete (Double Tab) Not

main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
This now reports that a loose object can not be found instead of crashing and shows checkout progress in the pad
Fixes VSTS #549721
=> [Git] Fix progress reporting on clone

main/src/core/MonoDevelop.Ide/ExtensionModel/Commands.addin.xml, main/src/core/MonoDevelop.Ide/ExtensionModel/MainMenu.addin.xml, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/TextEditorCommands.cs, main/src/core/MonoDevelop.Ide/options/KeyBindingSchemeVisualStudio-mac.xml, main/src/core/MonoDevelop.Ide/options/KeyBindingSchemeVisualStudio.xml
(#3757 for `d15-6`)
This PR brings back the "Edit → Toggle Completion Mode" menu entry and adds it's default _Ctrl + Alt + Space_ binding to the VS binding schemes.
Fixes gh #3640
=> [Ide] Add Toggle Completion Mode menu and keys

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads/ErrorListPad.cs
(#3783 for d15-5)
The focus chain for the error pad is set to only let the Build Output be focused, but if Build Output is hidden, then nothing can be focused and so the autohide
closes the pad.
Add the scrolled window as a secondary focus widget as a back up if the Build
Output is hidden.
Fixes VSTS #561864
(cherry picked from commit 1d6a8648da9661f5d16934a24a2eb1faa5323b83)
=> [15.5][IDE] Errors pad autohides after a few moments

Makefile
Seems like AzureFunctions included a roslyn library, and it ended up being used when AOT-ing, causing mismatches with the core assembly
=> [AOT] Fix the AOT profile not working on Mac.

main/src/addins/CSharpBinding/MonoDevelop.CSharp/PathedDocumentTextEditorExtension.cs
Issue: While having a "_pathed_" doc opened, when we (i.e.) do a `Select All` and `Cut`, (the doc's length becomes zero -empty-), the PathBar entries are not updated therefore when activating some element in the path bar's DropDownList it crashes.
Fix: Updates PathBar when PathedDoc root's length is equal or less than caret offset instead of just return;
Crash repro: https://www.dropbox.com/s/lwfrc21bm9zz2jv/vsformac%20bug.mov?dl=0
=> [Ide] Fixes a crash when activating no existent PathBar type / element

main/src/core/MonoDevelop.Core/MonoDevelop.Core/Gettext.cs
OS X seems to have some cultures that do not exist in .NET. Fallback to default when they're not found.
Fixes VSTS #532970
=> [d15-6][Core] Add a fallback when a given culture does not exist in .NET

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Tooltips/LanguageItemTooltipProvider.cs, main/src/addins/CSharpBinding/MonoDevelop.CSharp.Tooltips/QuickInfoProvider.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/RoslynCompletionData.cs
The inner code in roslyn is thread safe, and we don't need to run the continuation on a bg thread either. Only sync back to UI context after the query is done
This amounts to 100ms out of 2000 of UI thread execution while moving the mouse
=> [Ide] Don't run the completion service query on the UI thread

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CustomTools/CustomToolService.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/LogView.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads/DefaultMonitorPad.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/ProgressMonitors.cs
Rework the LogView so that it can handle multiple progress monitors feeding into
it and then CustomToolService just needs to use one Tool Output pad.
Fixes VSTS #527927
=> [d15-6] Fix 527927 - Tool output pad not being reused - appears multiple times

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/OnTheFlyFormatter.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeFormatting/CodeFormatter.cs
defined input variables upon creation'
https://devdiv.visualstudio.com/DevDiv/_workitems?id=561844
I obsoleted the formatting infrastructure - it should be taken out and
replaced with the roslyn infrastructure.
=> Fixed 'VSTS Bug 561844: [Feedback] Code snippets don't highlight

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CustomTools/CustomToolService.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/LogView.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads/DefaultMonitorPad.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/ProgressMonitors.cs
Rework the LogView so that it can handle multiple progress monitors feeding into
it and then CustomToolService just needs to use one Tool Output pad.
Fixes VSTS #527927
=> [IDE] Tool output pad not being reused - appears multiple times

main/src/addins/Xml/Editor/BaseXmlEditorExtension.cs
Problem was that default code completion was triggering code completion on `=` and `"` which user typed but default implementation doesn't know that Xml extension already inserts this values(="") in case of `AutoInsertFragments=true`, hence we have to also specify `KeyActions.Ignore` so editor doesn't insert additional `=` and `"`. This is same behaviour as VS has.
=> Fix #560350: Issue with adding a Style to Tags in cshtml views

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/WorkspaceExtensions.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
Since this is internal in Roslyn, we need to expose this to WebTooling and other addins that do not have IVT from Roslyn.
=> Expose an API to register Solution Crawler.

main/src/addins/VersionControl/MonoDevelop.VersionControl.Git.Tests/BaseGitRepositoryTests.cs, main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs, main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/CheckoutCommand.cs, main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlTask.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.ProgressMonitoring/BaseProgressMonitor.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.ProgressMonitoring/MessageDialogProgressMonitor.cs
This now reports that a loose object can not be found instead of crashing and shows checkout progress in the pad
Fixes VSTS #549721
=> [d15-6][Git] Fix progress reporting on clone

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.ProgressMonitoring/BaseProgressMonitor.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.ProgressMonitoring/MessageDialogProgressMonitor.cs
For some reason, when VCS finished checking out, the window that was chosen for the ShowError alert was not the root window, thus it would go behind.
That way, the IDE would be unusable until the user focuses out and back in and sees the dialog and clicks ok
=> [Ide] When showing a result dialog, compute transientFor if possible

main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/ToolboxWidget.cs
Fix crash if toolbox item icon is missing or has no fixed size.
Fixes gh #3590
=> [Designer] Fix Toolbox crashing

main/src/addins/MonoDevelop.UnitTesting.NUnit/MonoDevelop.UnitTesting.NUnit/NUnitProjectTestSuite.cs
The problem was that the NUnit test provider was finding a
PackageReference for NUnit, trying to load the tests for the .NET Core
project and failing. To fix this the NUnit test provider now ignores
.NET Core projects so the VS Test provider has a chance to load the
tests.
Fixes VSTS #565933
=> [NUnit] Fix being unable to use NUnit in a .NET Core test project

main/src/addins/MonoDevelop.UnitTesting.NUnit/MonoDevelop.UnitTesting.NUnit/NUnitProjectTestSuite.cs
The problem was that the NUnit test provider was finding a
PackageReference for NUnit, trying to load the tests for the .NET Core
project and failing. To fix this the NUnit test provider now ignores
.NET Core projects so the VS Test provider has a chance to load the
tests.
Fixes VSTS #565933
=> [d15-6][NUnit] Fix being unable to use NUnit in a .NET Core test project

main/Main.sln, main/tests/MonoDevelop.Core.Tests.Addin/MonoDevelop.Core.Tests.Addin.csproj, main/tests/MonoDevelop.Core.Tests.Addin/MonoDevelop.Core.Tests/TestCapabilityProjectExtension.cs, main/tests/MonoDevelop.Core.Tests.Addin/Properties/AddinInfo.cs, main/tests/MonoDevelop.Core.Tests.Addin/Properties/AssemblyInfo.cs, main/tests/MonoDevelop.Core.Tests.Addin/Properties/MonoDevelop.Core.Tests.addin.xml, main/tests/MonoDevelop.Core.Tests/MonoDevelop.Core.Tests.csproj, main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/ProjectCapabilityTests.cs, main/tests/test-projects/project-capability-tests/testcapability.targets
The test was using the AzureFunctions project extension which has
been removed. Added a test addin that defines a custom project
extension using a test capability. This addin is registered by
adding an .addins file to the local-config directory. This file is
deleted after the test fixture completes to avoid including the addin
in the final packaged IDE.
The test is now passing on Wrench and VSTS. The Wrench dmg does not contain the test addin.
=> [Core] Fix project capability test

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutput.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputNode.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputProcessor.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputViewContent.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputWidget.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads/ErrorListPad.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Tasks/TaskListEntry.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Tasks/UserTasksView.cs, main/tests/Ide.Tests/MonoDevelop.Ide/BuildOutputTests.cs
This feature allows go to selected error/warning/message in Log Build Output line from the ErrorListPad.
To jump into the error we need all the data loaded. I changed our current code to allow do this.
=> Structured build output Goto Log Build Output

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutput.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputViewContent.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputWidget.cs
- Implements File -> Save command handler
- Disables / Enabled Save button depending on IsDirty
- Removes SelectRow() and use MoveToMach() instead
- Enable / Disable search buttons depending on result matches
- When not matches, now displays "0 of 0" instead of "Not found"
- Implements missing PathChanged event
- Fixes: Save button should not show up when loading a log from a file (it is already saved)
- Adds a placeholder "Search Build Output";
- When pattern is null or empty, then FirstMatch returns null (This fixes -> Exclude output node itself in the breadcrumbs because they are too long. If the output element is selected, show just a parent in the breadcrumbs.)
- Removes nodes with no children in the pathBar  (Fixes: Exclude output node itself in the breadcrumbs because they are too …
=> UI fixes rebased

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/CompletionController.cs
The controller's ResetState method reset the StartOffset
to zero. Since this method is called when a mutable list
updates, the CompletionString used for filtering mutable
lists was the entire document up to the completion point,
which of course was so long and complex it matched nothing.
Also remove a redundant ResetSizes call that caused
unnecessary nontrivial work when updating mutable lists.
=> Fix mutable completion list filtering

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Tooltips/LanguageItemTooltipProvider.cs, main/src/addins/CSharpBinding/MonoDevelop.CSharp/SignatureMarkupCreator.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/RoslynCompletionData.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/SignatureHelpParameterHintingData.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/SyntaxHighlightingService.cs
This fixes the issue #3437. We introduced a theme detection logic (with eeb7779276f8483d7202bb3812037f840ccdcebe) which checks whether the current highlighting theme fits the current IDE theme. If it doesn't fit, we fallback to the IDE default theme for the current IDE style. But recent editor changes didn't take that into account.
=> [Ide] Fix editor tooltip theme fitting

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutput.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputWidget.cs, main/tests/Ide.Tests/MonoDevelop.Ide/BuildOutputTests.cs
Instead of creating a `BuildOutputDataSearch` instance for the whole lifetime of the `BuildOutputWidget`, just create it on demand, when a real search is started. And also, use this to keep track of whether we are in the middle of a search or not, instead of having to update a property.
=> Simplify keeping track of the current search

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputWidget.cs
We were unsuscribing the event after raising it
=> Fixes copy element menu handler to fire when click

main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpTextEditorCompletion.fs
Fixes vsts #563779 (#3798)
Determined that it is too difficult to detect all the occurrences of
identifiers in F# code for the time being, so it is hard to determine that the
popup should not be displayed. Given this, we should be far less aggressive
about auto-committing (even when "Complete with Space or Punctuation" is
switched on. This is a good default for C#, but a bad default for F#.)
This behaviour roughly matches both VS on Windows and VS Code
=> Intellisense never auto-commits for F#, not even for '.'

main/src/addins/CSharpBinding/CSharpBinding.csproj, main/src/addins/CSharpBinding/MonoDevelop.CSharp.Project/CSharpLanguageVersionHelper.cs, main/src/addins/CSharpBinding/MonoDevelop.CSharp.Project/CompilerOptionsPanelWidget.cs, main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding.Tests.csproj, main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding/CSharpLanguageVersionHelperTests.cs, main/tests/MonoDevelop.CSharpBinding.Tests/packages.config
Also add an unit test that will fail every time roslyn adds a new language version.
The output of the test is:
1) AssertWeHaveAllLanguagesInUI (MonoDevelop.CSharp.Project.CSharpLanguageVersionHelperTests.AssertWeHaveAllLanguagesInUI)
Roslyn added new C# language versions: 'CSharp7_2', add to CSharpLanguageVersionHelper.GetKnownLanguageVersions
Expected: 0
But was:  1
This will ensure that we never ship without adding these values to the UI.
Fixes VSTS #565692 Development with C# 7.2
=> [C#] Add language version 7.2 to supported languages UI

main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Rename/RenameItemDialog.cs, main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Rename/RenameRefactoring.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/IdeFileSystemExtensionExtension.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/MessageService.cs
update references in read-only files in Visual Studio for Mac 7.2
Preview
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/525922
The good old yes/no/cancel box solution.
=> Fixed VSTS 525922: [Feedback] Renaming a class silently fails to

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
However we need do find out why they're added. Someone is using the roslyn project model in a wrong way.
=> [Ide] Added duplicate reference check.

main/src/core/MonoDevelop.Ide/MonoDevelop.Components/ContextMenuExtensionsMac.cs
key
https://github.com/mono/monodevelop/issues/3826
The issue was in the NSMenu wrapper which always created an enter key
event for menu items even for submenus - that closed the menu item in
any case.
=> Fixes issue #3826 Quick fix context dialog incorrectly handles enter

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputTreeCellView.cs
This was lost when we switched to the custom cell renderer.
=> [Ide] Use dimmed color for skipped targets

main/src/addins/CSharpBinding/Razor/RoslynCompletionPresenter.cs
This is necessary for TypeScript completions to work in the editorFeatures branch.
=> Add TypeScript content type to RoslynCompletionPresenter

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputViewContent.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputWidget.cs
This exception:
```ERROR [2018-02-27 13:59:03Z]: An unhandled exception has occured. Terminating Visual Studio? False
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object
at Xwt.GtkBackend.TableViewBackend.DisableEvent (System.Object eventId) [0x00017] in /Users/builder/data/lanes/5691/e9bbd224/source/monodevelop/main/external/xwt/Xwt.Gtk/Xwt.GtkBackend/TableViewBackend.cs:135
at Xwt.GtkBackend.TreeViewBackend.DisableEvent (System.Object eventId) [0x00000] in /Users/builder/data/lanes/5691/e9bbd224/source/monodevelop/main/external/xwt/Xwt.Gtk/Xwt.GtkBackend/TreeViewBackend.cs:69
at Xwt.Backends.BackendHost.OnDisableEvent (System.Object eventId) …
```
=> [Ide] Fix double Dispose in BuildOutputWidget

main/src/addins/MonoDevelop.Refactoring/MonoDevelop.AnalysisCore/Gui/ResultsEditorExtension.cs
```
[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
at MonoDevelop.AnalysisCore.Gui.ResultsEditorExtension+<OnDiagnosticsUpdated>d__15.MoveNext () [0x0007f] in /Users/davidkarlas/GIT/MD1/monodevelop/main/src/addins/MonoDevelop.Refactoring/MonoDevelop.AnalysisCore/Gui/ResultsEditorExtension.cs:209 
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/jenkins/workspace/build-package-osx-mono/2017-12/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:152 
at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync> …
```
=> Fix possible crash in close all files

main/src/addins/MonoDevelop.SourceEditor2/VSEditor/Text/Impl/WpfToolTipAdornment/BaseWpfToolTipPresenter.cs, main/src/addins/MonoDevelop.SourceEditor2/VSEditor/Text/Impl/WpfToolTipAdornment/ViewElementFactories/WpfClassifiedTextElementViewElementFactory.cs, main/src/addins/MonoDevelop.SourceEditor2/VSEditor/Text/Impl/WpfToolTipAdornment/ViewElementFactories/WpfContainerElementViewElementFactory.cs
- This PR tweaks the UX and adds padding and support for horizontal quick info layouts to make UI more consistent with VS for Windows.
- Addresses issue #4001
**VS for Windows**
**Before:**
**After:**
If desired I can share a repro extension project once I have it cleaned up.
**NOTE:** quick info is unusable at the moment due to #3999
=> Better quick info content formatting.

main/build/MacOSX/monostub.mm
The reason is that the designers install a custom addin version
into the root of the IDE, caused a mismatch between the dll and
the static registrar generated for it
=> [StaticRegistrar] Allow libvsmregistrar.dylib to not exist

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutput.cs
Because we change the parent on nodes when aggregating them in
AggregatedBuildOutputNode, the summary node was, sometimes (depending
on when the full tree was requested), not summing up the errors and
warnings correctly, so use the aggregated nodes' values instead.
=> [Ide] Fix errors/warnings count in summary node

main/src/addins/VersionControl/MonoDevelop.VersionControl/VersionControl.addin.xml
Fixes VSTS #574214 [loc][query][DevDiv][XamarinStudio_GIT] Please clarify strings in " md-addins.po...." // Show _Authors Before
=> [VCS] Make the authors before command label less ambiguous

main/src/addins/VersionControl/MonoDevelop.VersionControl/VersionControl.addin.xml
Fixes VSTS #574214 [loc][query][DevDiv][XamarinStudio_GIT] Please clarify strings in " md-addins.po...." // Show _Authors Before
=> [d15-7][VCS] Make the authors before command label less ambiguous

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/LineSeparatorTextEditorExtension.cs
project
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/576053
This fix should not be needed - but just in case checking for that to
be != null doesn't hurt.
=> Fixed VSTS 576053: MonoDevelop closes trying to open a solution

main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs
https://devdiv.visualstudio.com/DevDiv/Xamarin%20VS%20for%20Mac/_workitems/edit/572337
Moving the file registry to central point requires to set the skip change to that point as well otherwise all other view content implementations are broken.
=> Fixes VSTS 572337: Saving changes causes the ViewContent to be reloaded

main/external/Makefile.am
Xamarin.Mac now contains a pdb, not a mdb. Try copying either.
=> Fix build of md-addins.

main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.PickMembersService/PickMembersDialog.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/576801
The bug wasn't reproduceable - seems only to happen in a very old
version however the dialog wasn't like VS.NET because the null check
option was missing. I added correct option support.
=> Fixes VSTS 576801: Generate Constructor... not performing any action

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Project/CodeGenerationPanel.cs, main/src/addins/CSharpBinding/MonoDevelop.CSharp.Project/CompilerOptionsPanelWidget.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.OptionPanels/BaseDirectoryPanelWidget.cs
VoiceOver was seeing some invisible spacer widgets because they hadn't been
hidden from accessibility.
Fixes VSTS #561850
=> [A11y] Hide some invisible widgets from VoiceOver

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Gui/AddPackagesDialog.UI.cs
Backport from master https://github.com/mono/monodevelop/pull/4064
Needed so that we don't have to maintain two different codebase or branching for automated tests. The change itself is extremely low risk as it just adds the name to various widgets
=> [d15-6] Add Xwt Name to various buttons and elements in PackageManagement dialogs

main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.ExtractInterface/ExtractInterfaceDialog.cs
dialog is initially shown (works in VS2017)'
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/576819
Found & fixed an issue with the cell view update as well.
=> Fixed 'Bug 576819: Extract Interface... OK button is disabled when

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/TypeSystemService_WorkspaceHandling.cs
Don't throw an exception if we don't have a Roslyn workspace, e.g. F#
fixes vsts #579690 (#4062)
=> [F#] Fix exception in Android previewer

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/TypeSystemService_WorkspaceHandling.cs
Don't throw an exception if we don't have a Roslyn workspace, e.g. F#
fixes vsts #579690 (#4062)
=> [F#] Fix exception in Android xaml previewer

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs
Fixes VSTS #577272 - Unable to expand SDK dependencies in Solution
window for .NET Core projects
On creating a new ASP.NET Core Web App project after the NuGet packages
have restored it was sometimes not possible to expand the dependencies
under the NuGet folder or SDK folder in the Solution window. The
problem was that the initial call to Project.GetPackageDependencies
was cancelled and that could cause the RemoveProjectBuilder to return
a build result with an error and no items. This list of zero items
was then cached resulting in the Dependencies folder only showing
the dependencies it found in the project directly.
=> [Core] Fix zero package dependencies cached when call is cancelled.

main/tests/StressTest/MonoDevelop.StressTest/ProfilerProcessor.cs
Using the immediate visitor doesn't guarantee the order of the events,
which results in crashes in HeapObjectEvent visitor if the class event
for the object in the snapshot hasn't arrived yet.
=> [StressTest] Use sorted visitor when processing MLPDs

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/Projection/ProjectedDocumentContext.cs
If ReparseDocument was called from a background thread the parsed event was called on the same thread. This should be fixed.
Fixes VSTS 572820
=> [Ide] Ensured that the document parsed event is called on UI thread.

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/EditorConfigService.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/580166
Seems that the coding conventions dll throws an exception if the file
doesn't exist - the given url for untitled files is valid - like
"/foo.cs"
=> Fixes VSTS 580166: File -> New file doesn't work

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildImport.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProject.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs, main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/GetSourceFilesAsyncTests.cs, main/tests/test-projects/project-with-corecompiledepends/consoleproject-import.targets, main/tests/test-projects/project-with-corecompiledepends/consoleproject.csproj
Installing a NuGet package such as Refit, which extends the
CoreCompileDependsOn to generate a C# file, the generated file would
not be available to the type system until the solution was closed
and re-opened again. The problem was that the result of running the
targets that are in the CoreCompileDependsOn property are cached.
When Refit is installed the cached result is returned so the
generated C# file is not available to the type system when it calls
Project.GetSourceFilesAsync. To fix this the project will be
re-evaluated before getting the CoreCompileDependsOn property if an
MSBuild import is added or removed. Note that projects that use
PackageReferences were unaffected since these projects are
re-evaluated by the NuGet addin. Only projects that use a
packages.config file were …
=> [Core] Ensure generated files available to type system

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildImport.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProject.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs, main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/GetSourceFilesAsyncTests.cs, main/tests/test-projects/project-with-corecompiledepends/consoleproject-import.targets, main/tests/test-projects/project-with-corecompiledepends/consoleproject.csproj
Installing a NuGet package such as Refit, which extends the
CoreCompileDependsOn to generate a C# file, the generated file would
not be available to the type system until the solution was closed
and re-opened again. The problem was that the result of running the
targets that are in the CoreCompileDependsOn property are cached.
When Refit is installed the cached result is returned so the
generated C# file is not available to the type system when it calls
Project.GetSourceFilesAsync. To fix this the project will be
re-evaluated before getting the CoreCompileDependsOn property if an
MSBuild import is added or removed. Note that projects that use
PackageReferences were unaffected since these projects are
re-evaluated by the NuGet addin. Only projects that use a
packages.config file were …
=> [d15-7][Core] Ensure generated files available to type system

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/LightStyle.json
This changes the search result highlighting color in the `Light` syntax highlighting theme to `#fcff54`.
Fixes VSTS #529478
=> [529478][Ide] Fix Light search result highlight color

main/build/MacOSX/monostub.mm
=> Bump minimum mono version to fix a gc descriptor bug

.gitignore, main/external/Makefile.am, main/src/addins/MacPlatform/MacPlatform.cs, main/src/addins/MacPlatform/MacPlatform.csproj, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/PlatformService.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/DesktopService.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeVersionInfo.cs
Fixes VSTS #577285 Report version of Xamarin.Mac that's used at runtime
=> Report the version of Xamarin.Mac that's used at runtime by the IDE

main/Directory.Build.props, main/src/addins/CSharpBinding/MonoDevelop.CSharp.Project/CSharpCompilerParameters.cs, main/src/addins/CSharpBinding/MonoDevelop.CSharp.Project/CSharpLanguageVersionHelper.cs, main/src/core/MonoDevelop.Core/packages.config, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Composition/CompositionManager.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/EditorThemeColors.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/Formats/OldFormat.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/RoslynClassificationHighlighting.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopPersistentStorageLocationService.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj, main/src/core/MonoDevelop.Startup/app.config, main/tests/MonoDevelop.Refactoring.Tests/MonoDevelop.Refactoring.Tests.csproj
* Bump Roslyn to 2.8.0-beta2-62708-11
* port persistent storage to 2.8 API
* Update Roslyn binding redirects to 2.8.0.0.
* Update VSMEF to 15.6.
* Fix ProjectReference relative path.
Fix Threading version.
Fix threading binding redirect.
* Temporarily comment out throwing on VSMEF composition errors.
Pending Roslyn bug https://github.com/dotnet/roslyn/issues/25211
* Add C# 7.3 language version.
* [C#] Reuse roslyn extensions for parsing string to language version
* Fix compiler options unit test
* Fixes issue #3436 Syntax highlighting regression
https://github.com/mono/monodevelop/issues/3436#issuecomment-372545839
* Don't use persistent storage for an adhoc workspace
* Log VSMEF errors to log file.
* Log MEF errors individually.
=> Bump Roslyn to 2.8.0-beta2-62708-11 (#4101)

main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs
When the window first focuses imContextNeedsReset is always set to true,
so here we set preeditString to null and it won't be displayed correctly
for Japanese and Chinese users. There may be other situations where it
also is set to true and the preedit string will disappear in the middle
of typing.
Fixes VSTS #573925
=> [TextEditor] Always fetch the preedit string

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
Opening a .NET Core project would sometimes log an unhandled
ArgumentNullException. When calling the MSBuildProject's
FindGlobItemsIncludingFile the MSBuildEngine is sometimes null so
a null was being returned. This is now handled. The files being
created on project load are typically in the obj folder so would be
ignored by the default file globs.
An unhandled exception has occured. Terminating Visual Studio? False
System.ArgumentNullException: Value cannot be null.
Parameter name: source
at System.Linq.Enumerable.Where[TSource]
in corefx/src/System.Linq/src/System/Linq/Where.cs:42
at MonoDevelop.Projects.Project.OnFileCreatedExternally
in src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs:4041
Fixes VSTS #567569 Opening a solution with NetStandard library throws …
=> [d15-7][Core] Fix file watcher argument null exception

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
Opening a .NET Core project would sometimes log an unhandled
ArgumentNullException. When calling the MSBuildProject's
FindGlobItemsIncludingFile the MSBuildEngine is sometimes null so
a null was being returned. This is now handled. The files being
created on project load are typically in the obj folder so would be
ignored by the default file globs.
An unhandled exception has occured. Terminating Visual Studio? False
System.ArgumentNullException: Value cannot be null.
Parameter name: source
at System.Linq.Enumerable.Where[TSource]
in corefx/src/System.Linq/src/System/Linq/Where.cs:42
at MonoDevelop.Projects.Project.OnFileCreatedExternally
in src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs:4041
Fixes VSTS #567569 Opening a solution with NetStandard library throws …
=> [Core] Fix file watcher argument null exception

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs
Fixes VSTS #577272 - Unable to expand SDK dependencies in Solution
window for .NET Core projects
On creating a new ASP.NET Core Web App project after the NuGet packages
have restored it was sometimes not possible to expand the dependencies
under the NuGet folder or SDK folder in the Solution window. The
problem was that the initial call to Project.GetPackageDependencies
was cancelled and that could cause the RemoveProjectBuilder to return
a build result with an error and no items. This list of zero items
was then cached resulting in the Dependencies folder only showing
the dependencies it found in the project directly.
=> [d15-7][Core] Fix zero package dependencies cached when call is cancelled.

main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/581661
Seems that a span change detection was missing completely - that this
worked in former versions must've been a side effect. I took the
chance to ensure that highlighting is really done in background which
looks ok on my systems.
=> Fixes VSTS 581661: [Feedback] /* */ Comments slow or non responsive

main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs
This is https://github.com/mono/monodevelop/pull/3976 for d15-7
When the window first focuses imContextNeedsReset is always set to true,
so here we set preeditString to null and it won't be displayed correctly
for Japanese and Chinese users. There may be other situations where it
also is set to true and the preedit string will disappear in the middle
of typing.
Fixes VSTS #569762
This reverts 3cfb1b3
=> [15.7] [TextEditor] Always fetch the preedit string

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/RoslynLogger.cs
Currently, no stacktraces are reported, because of https://github.com/mono/mono/issues/7649
=> [Ide] Add roslyn error reporting into our chain

main/src/core/MonoDevelop.Ide/MonoDevelop.Components/GtkUtil.cs
Loading the cell data to render CellTooltipWindow will
crash if the corresponding row is removed. To avoid the crash
the TreeIter must be validated on every redraw.
Fixes VSTS #550346
(cherry picked from commit 1a1fd2d531755020dace5e2bebe18502cf4077be)
=> [15.7][550346][Ide] Validate current iter when drawing CellTooltipWindow

.gitignore, main/tests/MonoDevelop.Core.Tests.Addin/MonoDevelop.Core.Tests.Addin.csproj, main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/ProjectCapabilityTests.cs
Register the MonoDevelop.Core.Tests.Addin in the project capability
tests and unregister it afterwards. This is instead of registering
the addin using an .addins file generated in the local-config folder
at build time and then deleting it after the test is run.
=> [Tests] Improve project capability tests

main/src/core/MonoDevelop.Ide/MonoDevelop.Components/GtkUtil.cs
Loading the cell data to render CellTooltipWindow will
crash if the corresponding row is removed. To avoid the crash
the TreeIter must be validated on every redraw.
Fixes VSTS #550346
(cherry picked from commit 1a1fd2d531755020dace5e2bebe18502cf4077be)
=> [15.6][550346][Ide] Validate current iter when drawing CellTooltipWindow

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/DirectoryTemplate.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/FileTemplate.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/FileTemplateReference.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/ProjectDescriptor.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/PropertyDescriptionTemplate.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/ResourceFileDescriptionTemplate.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/SingleFileDescriptionTemplate.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/TextFileDescriptionTemplate.cs
Fixed SingleFileDescription's public methods being removed.
Ensure that code that uses the obsolete non-async methods still
work by adding back the original code for these methods.
=> [d15-7][Ide] Fix file template API break

main/src/addins/MacPlatform/Dialogs/MDAccessoryViewBox.cs, main/src/addins/MacPlatform/Dialogs/MDBox.cs, main/src/addins/MacPlatform/Dialogs/MacAddFileDialogHandler.cs, main/src/addins/MacPlatform/Dialogs/MacCommonFileDialogHandler.cs, main/src/addins/MacPlatform/Dialogs/MacOpenFileDialogHandler.cs, main/src/addins/MacPlatform/Dialogs/MacSelectFileDialogHandler.cs, main/src/addins/MacPlatform/MacPlatform.csproj, main/src/addins/MacPlatform/packages.config
This uses the same fix as a4bbb0989b9c9767766e6b16a83f0c07c406d0c2
to fix this dialog being broken on High Sierra. Don't layout
after setting the accessory view
Fixes VSTS #585364 Add File/[Options] UI is not shown
=> [Mac] Fix Add Files dialog being broken on High Sierra

main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Actions/MiscActions.cs, main/src/core/MonoDevelop.TextEditor.Tests/Mono.TextEditor.Tests.DefaultEditActions/MiscActionsTest.cs
exception
MoveBlockDown doesn't have that bug. It's not a big one - doesn't
crash the IDE - just visible in the log file.
=> Fixes VSTS 586125: Alt+Up at beginning of the document results in an

.editorconfig, main/Main.sln
They were not in line with our styles and forced wrong formatting. Added .editorconfig to the solution.
It's a hidden file and this makes it easier to find & edit that.
=> Fixed some editorconfig settings.

main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SearchAndReplaceWidget.cs
We used to give the current selection an own color. That got lost with
the textmate theme switch. The selection is enough to highlight the
current selection and gives a better user experience when closing the
search widget.
=> [SourceEditor] Search widget no longer hides selection.

main/src/addins/MonoDevelop.AspNetCore/Templates/MVCViewImportsPage.xft.xml, main/src/addins/MonoDevelop.AspNetCore/Templates/MVCViewLayoutPage.xft.xml, main/src/addins/MonoDevelop.AspNetCore/Templates/MVCViewPage.xft.xml, main/src/addins/MonoDevelop.AspNetCore/Templates/MVCViewStartPage.xft.xml, main/src/addins/MonoDevelop.AspNetCore/Templates/RazorPage.xft.xml, main/src/addins/MonoDevelop.AspNetCore/Templates/RazorPageWithPageModel.xft.xml
Adding a new .cshtml file from a file template to an ASP.NET Core
project would modify the project file (.csproj) when it should not be
modified. The problem was the files were added as None items whilst
.cshtml are Content items. The project file would contain the
following after adding a new cshtml file from a template:
<ItemGroup>
<Content Remove="Views\Index.cshtml" />
</ItemGroup>
<ItemGroup>
<None Include="Views\Index.cshtml" />
</ItemGroup>
Another problem was that the Razor Page with view model file
template specifies a DependentUpon property so this is added to the
project file and the .cshtml and .cs files are nested where as
the other .cshtml and .cs files created with the initial ASP.NET
Core project template are not nested. The project file would include
the following: …
=> [AspNetCore] Fix ASP.NET Core file templates modifying project file

main/src/addins/MonoDevelop.AspNetCore/Templates/MVCViewImportsPage.xft.xml, main/src/addins/MonoDevelop.AspNetCore/Templates/MVCViewLayoutPage.xft.xml, main/src/addins/MonoDevelop.AspNetCore/Templates/MVCViewPage.xft.xml, main/src/addins/MonoDevelop.AspNetCore/Templates/MVCViewStartPage.xft.xml, main/src/addins/MonoDevelop.AspNetCore/Templates/RazorPage.xft.xml, main/src/addins/MonoDevelop.AspNetCore/Templates/RazorPageWithPageModel.xft.xml
Adding a new .cshtml file from a file template to an ASP.NET Core
project would modify the project file (.csproj) when it should not be
modified. The problem was the files were added as None items whilst
.cshtml are Content items. The project file would contain the
following after adding a new cshtml file from a template:
<ItemGroup>
<Content Remove="Views\Index.cshtml" />
</ItemGroup>
<ItemGroup>
<None Include="Views\Index.cshtml" />
</ItemGroup>
Another problem was that the Razor Page with view model file
template specifies a DependentUpon property so this is added to the
project file and the .cshtml and .cs files are nested where as
the other .cshtml and .cs files created with the initial ASP.NET
Core project template are not nested. The project file would include
the following: …
=> [d15-7][AspNetCore] Fix ASP.NET Core file templates modifying project file

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputTreeCellView.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputWidget.cs
This is a rewrite of `BuildOutputTreeCellView` with following improvements:
* Reduce amount of required size calculations
* Reuse the TextLayout for each node (main text only, TODO: reuse information text layouts)
* Improve alignments (left icon, text, expander)
* Disable animations
=> [BuildOutput] Optimize size calculations

main/src/core/MonoDevelop.Core/MonoDevelop.Core/Runtime.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Composition/JoinableTaskContextHost.cs
Fixes https://developercommunity.visualstudio.com/content/problem/210744/value-cannot-be-null-1.html
When opening a .json file (such as appsettings.json in an ASP.NET Core Web app) you get a fatal error message: Value cannot be null. Parameter name: context.
We think this is because of a race condition, where if someone first requests the JoinableTaskContext from a background thread, the importing constructor of JoinableTaskContextHost runs and returns, because we do not await the task spawned by the constructor. And so we grab the value of JoinableTaskContext property, which is still null, before it is being assigned by the UI thread task that we've started in the constructor.
The solution is to expose the MainThread from the runtime and forcibly initialize the JoinableTaskContext to the …
=> Fix VSTS 581051 - Value cannot be null. Parameter name: context

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/RoslynClassificationHighlighting.cs
Side effect of last fix. Seems the roslyn classifier can give back a span with a start prior to the requested classification area in case of multi line spans.
It's arguable if this is a bug or not - but anyways that's now handled.
=> Fixes issue #4267 Multi-line comment classification not working properly

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/DefaultMSBuildEngine.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildEngine.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProject.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProjectInstance.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ItemCollection.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
Fixes VSTS #524077 - Performance: Opening .NET Core project with many
files that are not excluded
Two parts two to this change:
1. Improve re-evaluation performance
2. Improve initial project load time
Timinges for .NET Core console project that has a node_modules directory
containing 17150 files:
- Initial project load time down from ~70-80 seconds down to ~20 seconds.
- Re-evaluation time from ~110 seconds down to ~20 seconds.
=> [Core] Improve .NET Core project load times for project with project files

main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.csproj, main/src/addins/MonoDevelop.UnitTesting/packages.config
Use the same Newtonsoft.Json verson 10.0.3 as used everywhere else.
Also prevent a local copy of the Newtonsoft.Json.dll being copied
to the addin directory.
=> [d15-7][UnitTesting] Update Newtonsoft.Json version and do not local copy

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/DefaultMSBuildEngine.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildEngine.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProject.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProjectInstance.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ItemCollection.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
Fixes VSTS #524077 - Performance: Opening .NET Core project with many
files that are not excluded
Two parts two to this change:
1. Improve re-evaluation performance
2. Improve initial project load time
Timinges for .NET Core console project that has a node_modules directory
containing 17150 files:
- Initial project load time down from ~70-80 seconds down to ~20 seconds.
- Re-evaluation time from ~110 seconds down to ~20 seconds.
=> [d15-7][Core] Improve .NET Core project load times for project with project files

main/configure.ac, main/tests/Makefile.am, main/tests/MonoDevelop.Core.Tests.Addin/Makefile.am
Fixes tarball build. It's smaller than last time!
=> Include MonoDevelop.Core.Tests.Addin in SUBDIRS

main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.VsTest/VsTestAdapter.cs
Problem was very obscure to debug because problem was 2 processes away... Basically when running locally VSfM ResultDirectory was set to `/Path/To/Current/Path/Of/Process/TestResults/` but when VSfM is started via `Finder` or `open /Application/Visual Studio.app/`, `Directory.GetCurrentDirectory()` returns empty, resulting in `/TestResults/` folder and test runner doesn't have permissions to access that folder, hence it failed. Now from VSfM always set ResultDirectory to project `obj/TestResults` folder.
=> Fix 541368: MSTest not supported in .NET Framework library project

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreMSBuildProjectTests.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.csproj, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreMSBuildProject.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreShortTargetFramework.cs
Adding a file to a .NET Core project that targets Tizen 4.0 would
result in the TargetFramework changing from tizen40 to tizen4.0
Now the original framework identifier name is not modified and if
the version of the framework changes then the version will be
dotted or just numbers based on the format that was originally used
in the project.
Fixes VSTS 578016 - Saving Sdk style project should not change the
TargetFramework format.
=> [DotNetCore] Fix TargetFramework short name format changing on save

main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebuggingService.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Ide.cs
Main issue here was that when Attaching to process and user Quiting IDE, it didn't ask user for confirmation, we usually do this when debugging specific project when unloading that project, but we can't do that when attached...
Also modified  IdeApp.Exiting event execution to fix possible issue with different handlers setting Cancel=true, Cancel=false same as 6873f00665b1885a8095454de148075ee678fd68
=> Fix 581032: Debugger session not properly exited

main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/MonoTextEditor.cs, main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs, main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
This fixes weird issues that happened when the user typed into a preedit
on an otherwise empty line and then clicked to another line in the
editor. Committing the preedit string and clearing the IM also seems to
be more like what other editors like Xcode and TextEdit do.
Fixes VSTS #569890
=> [15.7] [Editor] Commit and clear preedit string when changing lines

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/FallbackStyle.json
This changes the search result highlighting color in the Fallback syntax highlighting theme to `#fcff54`, as requested by @vancura  in https://github.com/mono/monodevelop/pull/4140#pullrequestreview-103751898
Fixes VSTS #529478
(cherry picked from commit b44f84c8d05a22ba45218594d18ab5400d27796e)
=> [529478][Ide] Fix Light search result highlight color in FallbackStyle

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/FallbackStyle.json, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/LightStyle.json
This changes the search result highlighting color in the `Light` syntax highlighting theme to `#fcff54`.
Fixes VSTS #529478
=> [15.7][529478][Ide] Fix Light search result highlight color

main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/FoldMarkerMargin.cs, main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/IconMargin.cs, main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/Margin.cs, main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AtkCocoaHelper/AtkCocoaHelper.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AtkCocoaHelper/AtkCocoaHelperMac.cs
When in the text editor, use Alt-Tab to focus the margins.
Tab, Shift+Tab, Left or Right to select the focus margin (Only folding margin
accepts focus at the moment).
Up and Down selects the fold
Space folds or unfolds the selected fold
Fixes VSTS #515126
=> [IDE] Make the folding margin keyboard accessible

main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
We're computing the byte indices when we update the color of the preedit
string, but we're using the length of the preedit string instead of the
byte count. For multibyte languages this makes it difficult to see the
entire preedit string, and especially when "highlight current line" is
enabled then part of the string is completely invisible.
Fixes VSTS #591143
This is https://github.com/mono/monodevelop/pull/4352 but for master
=> [Editor] Fix color of preedit string

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Gui/DotNetCoreSdkLocationPanel.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Gui/DotNetCoreSdkLocationWidget.UI.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Gui/DotNetCoreSdkLocationWidget.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.NodeBuilders/DotNetCoreProjectNodeBuilderExtension.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.csproj, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCorePath.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreRuntime.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreRuntimeVersions.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdk.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdkInstalledCondition.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdkPaths.cs, main/src/addins/MonoDevelop.DotNetCore/Properties/MonoDevelop.DotNetCore.addin.xml, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/MicrosoftTemplateEngine.cs
Fixes VSTS #566365 Support .NET Core SDK being installed in
non-standard location
In Preferences there is now a Projects - SDK Locations - .NET Core
section that can be used to configure the location of the .NET Core
command line tool (dotnet). This can be used to point to a different
non-standard install location of the .NET Core SDK. After this is
switched the MSBuild hosts are recycled and all .NET Core projects
are re-evaluated to ensure the new locations of any MSBuild targets
is used.
=> [DotNetCore] Allow .NET Core location to be configured 

main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
We're computing the byte indices when we update the color of the preedit
string, but we're using the length of the preedit string instead of the
byte count. For multibyte languages this makes it difficult to see the
entire preedit string, and especially when "highlight current line" is
enabled then part of the string is completely invisible.
Fixes VSTS #591143
Example of the issue:
* VSTS Story/Issue link https://devdiv.visualstudio.com/DevDiv/_workitems/edit/591143
FWIW, here is a screenshot of the fix:
=> [15.7] [Editor] Fix color of preedit string

main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/Margin.cs, main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs, main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
PointToLocation was being called once in TextViewMargin.MouseHover and once in
ShowTooltip, both called from TextArea.FireMotionEvent. Calculate the
DocumentLocation once in FireMotionEvent and pass it to the sub methods
Fixes GH #4380
=> [Performance] Only calculate the DocumentLocation once per mouse move

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Refactoring/CSharpFindReferencesProvider.cs, main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding.Refactoring/CSharpFindReferencesProviderTests.cs
reference stops working in some classes.
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/591385
=> Fixes VSTS 591385: [Feedback] Visual Studio Mac Community, find

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.csproj, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/FinalProjectConfigurationPage.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkProjectConfigurationWidget.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/NewProjectController.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/MicrosoftTemplateEngine.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/MicrosoftTemplateEngineSolutionTemplate.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj, main/src/core/MonoDevelop.Ide/packages.config, main/tests/Ide.Tests/MonoDevelop.Ide.Projects/NewProjectDialogTests.cs, main/tests/Ide.Tests/ProjectTemplateTests.cs
- Updated the templating engine to fix problems with @ characters in file names being incorrectly encoded on creating the project.
- Support new lines in descriptions for templates using new templating engine.
- Allow options on the final page to be configured from a project template wizard.
- Gitignore
- Create project directory
VSTS #521689
Backport of  #3912 without any change to the version-checks. It can be merged without the Xamarin.Forms project template changes, whilst #589649 is not yet resolved.
=> [d15-7][Forms] Use dotnet templating project templates 

main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
It's needed to run the highlighting on the UI thread. Note this also
fixes a problem that popped up in conjunction with github issue #4346.
=> Fixes VSTS 592988: Code colors flicker black when typing

main/Directory.Build.targets
Instead of installing support libraries, we just download a zip
with the files and unpack it in the repo.
This way we can resolve assemblies from a local directory
=> [VSTS] Bring in support for a local resolve directory for gtk

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs, main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/ProjectWithWildcardsTests.cs, main/tests/test-projects/console-project-with-wildcards/ConsoleProject-with-link-wildcard.csproj, main/tests/test-projects/console-project-with-wildcards/ConsoleProject-with-link-wildcard.csproj.saved1
Saving a project with a file wildcard that had a Link that used
MSBuild item metadata, as shown below, would result in the wildcard
being removed and replaced with MSBuild items for each file included
by the wildcard.
```
<Compile Include="**\*.cs" Exclude="obj\**">
<Link>%(RecursiveDir)%(Filename).cs</Link>
</Compile>
```
The problem was that the evaluated Link property value was being
compared with the unevaluated value, which did not match, resulting
in the wildcard being replaced with individual MSBuild items for
each file. Now if the property value contains '%' a comparison is
made against the evaluated value when checking if the project item
has changed.
Fixes VSTS #569295 - Projects that includes files using wildcards
will expand (and remove) wildcards upon save
=> [Core] Fix wildcards being expanded on saving a project

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CompletionProvider/ProtocolMemberCompletionProvider.cs
This PR is an attempt to fix the following issues:
* https://github.com/xamarin/xamarin-macios/issues/3762
* https://devdiv.visualstudio.com/DevDiv/_workitems/edit/585126
* https://github.com/mono/monodevelop/issues/4216
Essentially the problem boils down to iOS/Mac protocol method overloads not showing up in the completion list.
The fix description:
When we generate completion items in `ProtocolMemberCompletionProvider`, methods with the same name (but different signature) get similar completion info. Specifically, they get the same `SortText` and `Span`.
These two properties are then used by Roslyn to remove duplicates when merging multiple completion contexts. Refer to this code for more details:
https://github.com/dotnet/roslyn/blob/master/src/Features/Core/Portable/Completion/Completi …
=> Supply SortText to preserve protocol methods in the completion list

main/src/core/MonoDevelop.Core/MonoDevelop.Core/Gettext.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
Fixes VSTS #594227 "GTK warning at startup about unsupported locale"
WARNING [2018-04-03 11:59:27Z]: Gtk-Warning: Locale not supported by C library.
Using the fallback 'C' locale.
Stack trace:
at Gtk.Application.gtk_init (System.Int32& , System.IntPtr& ) [0x00000] in <13dfc6c534074eb08a8f382a81e605d5>:0
at Gtk.Application.do_init (System.String progname, System.String[]& args, System.Boolean check) [0x0004d] in /Users/builder/jenkins/workspace/build-package-osx-mono/2017-12/external/bockbuild/builds/gtk-sharp-None/gtk/Application.cs:102
at Gtk.Application.Init (System.String progname, System.String[]& args) [0x0000e] in /Users/builder/jenkins/workspace/build-package-osx-mono/2017-12/external/bockbuild/builds/gtk-sharp-None/gtk/Application.cs:131
=> [Ide] Fix Gtk warnings caused by unsupported locale

main/src/addins/MonoDevelop.Refactoring/MonoDevelop.AnalysisCore/Gui/ResultsEditorExtension.cs, main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/TextMarker/WavedLineMarker.cs, main/tests/MonoDevelop.Refactoring.Tests/ResultsEditorExtensionTests.cs
Force them to have a length of 1.
Fixes VSTS #594665 Removing curly braces in text editor does not display any error or red squiggle
Fixes VSTS #592144 [Feedback] Syntax highlighting doesn't detect missing ; in c# editor
=> [Refactoring,Editor] Allow for 0-length diagnostic spans to be drawn

main/src/addins/MacPlatform/MainToolbar/VerticallyCenteredTextFieldCell.cs
This ensures that if AppKit clones the native cell we will be able to
create a new C# wrapper for it.
One known cause of this is when calculating the BaselineOffsetFromBottom.
This issue also affected the designers.
This is being added as a preventative as we may not actually be
triggering an API which clones the native object, but it's better to
be safe than sorry!
=> [Mac] Ensure we support Copy(NSZone) for our NSTextFieldCell subclasses

main/external/fsharpbinding/MonoDevelop.FSharp.Tests/Interactive.fs
Removes timeouts from F# Interactive tests and kills processes when done.
One of these tests would fail roughly one in twenty times.
=> Test remove timeouts

main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.Formats.MSBuild/BuildEngine.v4.0.cs
Running the TestCreateBuildBlankFormsSharedAndroidIOS automation
test sometimes fails to build. The build fails due to various
missing Android assembly references from the NuGet packages that are
installed when the project is created. The project file itself has
the correct reference information but the MSBuild engine host was
building an old version of the project.
The problem was that the project was modified in memory which
results in the unsaved project xml being given to the remote build
engine host and whilst a refresh was requested when the project file
is saved the old unsaved project xml was being used when building.
This could happen if the remote build engine had not loaded any
projects. Now the unsaved project information is removed even if
there are no loaded projects.
Fixes …
=> [MSBuild] Fix unsaved project xml not cleared in remote build engine

main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs, main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/TextEditorData.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/RoslynClassificationHighlighting.cs, main/src/core/MonoDevelop.TextEditor.Tests/Mono.TextEditor.Tests/SmartIndentModeTests.cs, main/src/core/MonoDevelop.TextEditor.Tests/Mono.TextEditor.Tests/VirtualIndentModeTests.cs
https://github.com/mono/monodevelop/issues/4489
It was caused by FixVirtualIndentation taking caret.line - 1 for the
correct indentation check. The FixVirtualIndentation (int lineNumber)
method doesn't have that flaw so delegating to that fixes the issue.
That the whitespaces were not drawn was just a visual display bug
which got fixed as well.
=> Fixes issue #4489 Virtual indentation handling broken

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/WorkspaceItem.cs, main/tests/Ide.Tests/MonoDevelop.Ide/UserPreferencesTests.cs
If the solution used a custom BaseDirectory then the user preferences
were saved inside the custom base directory and then not loaded on
re-opening the solution. A custom base directory can be configured
in solution preferences - General - Main Settings and then changing
the Root Directory. This then adds a section to the solution file:
GlobalSection(MonoDevelopProperties) = preSolution
BaseDirectory = ..
EndGlobalSection
Now the user preferences are always stored in a .vs directory
relative to the solution file itself instead of using the Solution's
BaseDirectory.
Fixes VSTS #598545 When opening a solution, last files are not
re-opened correctly
=> [Core] Fix files not re-opened on opening a solution

main/src/addins/MacPlatform/MacPlatform.cs
This seems not to be needed. The original report where Macaque would break
the top menu seems to not reproduce anymore.
Fixes VSTS #598766
=> [Mac] Remove AssemblyLoad hack

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
DotNetProject.OnReevaluateProject causes a LoadProject call where we attempt to incrementally preserve documents from the previous project. The CreateDocuments call incorrectly passed the current projectData to GetOrCreateDocumentId, and the document was not found there and was recreated from scratch.
Simple fix is to pass the oldProjectData so we preserve the DocumentId and other info from the previous project data.
Symptoms included lack of classification when a .cshtml document was opened on project open.
=> Fix VSTS 586152: Preserve documents on project reload

main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs, main/src/addins/Xml/Parser/XmlNameState.cs, main/src/addins/Xml/Parser/XmlRootState.cs, main/src/addins/Xml/Parser/XmlTagState.cs, main/src/addins/Xml/Tests/Parser/AttributeNameTestFixture.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Util/SimpleBracketMatcher.cs
This is just MonoDevelop part of fix, what I did here is update XmlName/Root and Tag states to support having `< xmlns="formsNamespace"` and parse this as element with attributes, because until now this was not element element yet(because it doesn't have name) so attributes also were not parsed, resulting in Forms extension not being aware of referenced namespaces, hence code completion not working...
I included also 2 unrelated fixes in SourceEditorView.cs and SimpleBracketMatcher.cs which deal with file edge cases that I found while working on this.
=> Fix 597220: No IntelliSense for pages deriving from a custom ContentPage

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProjectExtension.cs, version-checks
Added a OnGetFacadeAssemblies method to the DotNetProjectExtension
that allows a project extension to provide the facade assemblies
for a project if the default behaviour does not work for the project.
This can be used by the Xamarin.Mac project extension to provide
the facade assemblies when the project uses Xamarin.Mac full. A
Xamarin.Mac full project will use a custom facades directory at
build time but the project has a target framework of .NET Framework
so the default facades assembly resolution logic will return the
wrong facade assemblies that are included with Mono.
=> [d15-7][Core] Support facade assemblies from a custom location

main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.QuickTasks/QuickTaskOverviewMode.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components/HslColor.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Styles.cs
This is a possible fix for less visible search result markers. If the search result highlighting color of the current editor theme is not visible enough, a default marker color will be used instead.
TODO:
* Final marker color (same for dark/light IDE?)
* Needs a better color visibility detection than brightness comparison?
NOTE: making the theme color brighter based on the current background is too complex. We have simple (brightness based) calculation in [`SearchResultWidget`](https://github.com/mono/monodevelop/blob/fix529478-editor-search-marker-fallback-color/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/SearchResultWidget.cs#L318), but it tends to calculate black/white colors for most themes, which doesn't look really good.
=> [529478][Editor] Fix search marker fallback color

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProjectExtension.cs, version-checks
Added a OnGetFacadeAssemblies method to the DotNetProjectExtension
that allows a project extension to provide the facade assemblies
for a project if the default behaviour does not work for the project.
This can be used by the Xamarin.Mac project extension to provide
the facade assemblies when the project uses Xamarin.Mac full. A
Xamarin.Mac full project will use a custom facades directory at
build time but the project has a target framework of .NET Framework
so the default facades assembly resolution logic will return the
wrong facade assemblies that are included with Mono.
=> [Core] Support facade assemblies from a custom location

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Styles.cs
Continuing https://github.com/mono/monodevelop/pull/4531#event-1572839415: now with final colors.
=> [529478][Editor] Fix search marker fallback color with final colors

main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreCertificateManager.cs, main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreRunConfiguration.cs, main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/DotNetCoreDevCertsTool.cs
- Do not install dev-certs tool. This is pre-installed with the .NET Core SDK 2.1 preview 2.
- Fix browser not opened when running an ASP.NET Core 2.1 preview 2 project. The applicationUrl launchSetting.json property now stores multiple urls which was not being handled.
=> [AspNetCore] SDK Preview 2 Changes

main/src/addins/MacPlatform/MacPlatform.cs
This should hopefully fix the rare case when Sierra decides to enable tabbing for the main IDE window described in https://developercommunity.visualstudio.com/content/problem/227348/cursor-position-is-shifted-because-of-the-bar-with.html.
Fixes VSTS #600128 – [Feedback] Cursor position is shifted because of the bar with project name, opened file name and Visual Studio IDE type
=> [600128][Mac] Disallow window tabbing mode

main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/OSXEditor.cs
'Mono.TextEditor.TextViewMargin' threw an exception." errors from VS
Community (Mac) on macOS 10.13.5 Beta
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/597271
Seems to be a bug in the macOS beta but it can be handled.
=> Fixes VSTS 597271: [Feedback] Getting "The type initializer for

main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor.Theatrics/BounceFadePopupWindow.cs, main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs, main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs, main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.Wrappers/SemanticHighlightingSyntaxMode.cs, main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorPrintOperation.cs, main/src/core/Mono.TextEditor.Shared/Mono.TextEditor.Highlighting/XmlReadHelper.cs, main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Actions/ClipboardActions.cs, main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/DiffTracker.cs, main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/EditMode.cs, main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/TextEditorData.cs, main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/TextEditorOptions.cs
already fixed (the line numbers indicate it). However the text editor
errors should be printed to the log and not the console. This had
historical reasons because the editor was stand alone and had no
connection to the Core/Ide and no own logging capabilities.
=> Fixes issue #4393 Error in text editor The original error should be

main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs, main/src/addins/MonoDevelop.SourceEditor2/VSEditor/TagBasedSyntaxHighlighting.cs
DO NOT MERGE. This PR is strictly to demonstrate a fix I have locally that fixes some colorization issues.
The commented out code in TagBasedSyntaxHighlighting is what I was doing if I wanted to keep this as a tactical fix just for VS classifications (and the textarea.cs change wouldn't be necessary). There is a more widespread issue in colorization outside razor that I can reproduce in c#.
C# repro:
Create a new class.
In a different file, reference that class (notice it colorizes correctly)
Go back to new class file and modify the class name.
Go back to referencing file and notice that it still colorizes the old class name as if it were an existing type.
=> Invalidate cached line upon TextArea.RedrawLine

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreSdkTests.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreNotInstalledDialog.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdk.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/TargetFrameworkExtensions.cs
If a .NET Core 2.1 project is opened and .NET Core SDK 2.1.300 or
above is not installed then a dialog is shown allowing the SDK to
be downloaded. The project in the Solution window will show an error
icon with the same information about .NET Core 2.1 not being
installed. Currently the download link goes to the preview 2 page
- https://www.microsoft.com/net/download/dotnet-core/sdk-2.1.300-preview2
the url is shortened and can be redirected later without changing
the code once .NET Core 2.1 SDK final is released.
Fixes VSTS #573785 - Prompt to install .NET Core 2.1 SDK if .NET Core
2.1 project opened
=> [DotNetCore] Handle .NET Core 2.1 SDK not installed

main/external/fsharpbinding/MonoDevelop.FSharp.Tests/ProjectTests.fs, main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpProjectFileNodeExtension.fs
Backport of #4552.
/cc @nosami
=> [d15-7] Allow XAML files and codebehind files to be moved as a single unit

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/ItemTemplate.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/MicrosoftTemplateEngine.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/MicrosoftTemplateEngineImageLoader.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/MicrosoftTemplateEngineItemTemplate.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
This is needed by the new Azure Functions templates so that the
"New Function" dialog can render theme-appropriate icons based
on the icons shipped with the Azure templates.
=> [d15-7][Templates] Added ItemTemplate.GetImage() for loading themed images

main/src/addins/VBNetBinding/Project/VBCompilerParameters.cs
VB.NET projects would fail to build with an error:
vbc : error BC31030: Conditional compilation constant 'DEBUG ^^ ^^ '
is not valid: Character is not valid.
The VB.NET addin was using ';' as the separator for the constants
but the VB.NET compiler only supports ',' as the separator.
VB.NET project build support requires Mono 5.12 to be installed.
Fixes VSTS #602648 - Incorrect compilation constants separator used
for VB.NET
=> [VB] Fix incorrect compilation constant separator

main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/TextDocument.cs
We are already checking for args.Changes == null, but we're not checking for args.Changes.Count == 0. As a result we were adding UndoOperations where changes list was empty.
The symptom was then in Undo when this code was throwing ArgumentOutOfRange:
((UndoOperation)op).Changes[0].OldPosition;
because it assumed that the Changes list is non-empty.
=> Fix VSTS 586112: ignore TextChange events with no Changes

main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/MonoTextEditor.cs, main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs, main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/DocumentUpdateRequest.cs
This way the caller can choose not to remove the line cache - removing
the line cache is always more costly and most of the time not needed.
=> [TextEditor] Handled line cache removal in redraw methods.

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionFolderItem.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionItem.cs, main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/ProjectTests.cs
When the Project's NotifyModifed method is called now the project
extension's OnModified method is called if the extension chain is
initialized.
The Android addin was using the project extension's OnModified to
set the project's target framework to the latest and this method was
not being called which resulted in the wrong Android project having
the wrong target framework when use latest frameworkwas enabled.
Fixes VSTS #602708 - Incorrect Android target framework version stored
in project.assets.json
For d15-7 we may want to use a less riskier fix and just change the Android addin to directly use the Project.Modified event. I implemented an alternative fix in the md-addins/android-fix-target-framework-not-set-to-latest branch.
The project extension's OnModified event is currently used by …
=> [Core] Fix SolutionItemExtension.OnModified not being called

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/DotNetCoreNuGetProject.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageCompatibilityHandler.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageReferenceNuGetProject.cs
When the target framework version in project options is changed and
the project uses PackageReferences a restore is now run after the
project file is saved. This ensures the PackageReferences work with
the new target framework and re-generates the project.assets.json file
to ensure the build is using the correct references. Without this
changing the target framework to use latest for an Android project
can result in the build failing since the project.assets.json file
is out of sync with the project until a restore was run again.
Fixes VSTS #603274 - PackageReference project not restored after
target framework changed
=> [NuGet] Restore PackageReference project after target framework changed

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/DefaultMSBuildEngine.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/SdkResolution.cs
- [Core] Fix null reference on opening .NET Core project with sdk version
Opening a SDK style project that used a Sdk attribute with a version
would show an error message "Error while trying to load project:
Object reference not set to an instance of an object". The problem
was that an SdkResolver will can return null from the Resolve method.
These null results were added to a list and then an attempt was made
to log the result warnings on a null result.
<Project Sdk="Microsoft.NET.Sdk.Razor/2.1.0-preview2-final">
This allows the project to load but no files are shown in the
Solution window and a warning about the project not having any
valid configurations is also shown since the sdk cannot be resolved.
- [Core] Fix .NET Core Sdk version not being parsed from Sdk attribute
The Sdk …
=> [NuGet] Initial work for NuGet Sdk Resolver support

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/TypeSystemService_WorkspaceHandling.cs
In this commit https://github.com/mono/monodevelop/commit/88afb8bc3257cde9e500fcbb193615c851eb7e68#diff-a93bf3423c7fe66c6f8e07d45a997a72 we have regressed the Unload and Reload behavior where manually reloading a project would result in errors.
The problem is that we didn't find an oldProject because the ReplacedItem was an UnloadedSolutionItem and not the original project.
This change attempts to recover the actual project that was previously unloaded and passes it to LoadProject, so that LoadProject can properly diff against it.
Also adding a call to Workspace.OnProjectRemoved to remove a Roslyn project from the workspace when the MonoDevelop project was removed.
=> Fix VSTS 602848: Project Reload doesn't work

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Commands/PackageManagementStartupHandler.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/MonoDevelopNuGetProjectFactory.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/MonoDevelopSolutionManager.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/RestoreAndCheckForUpdatesAction.cs
Use the solution load event to start a task which does the restore
and check for updates instead of having the work done on the UI
thread.
Fixes VSTS #59385 - NuGet restore checker does work on the UI thread
on solution load
=> [NuGet] Fix restore check on solution load using UI thread

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageManagementServices.cs
The NuGet SDK resolver will download and install SDKs for .NET Core
projects if they are missing. The NuGet SDK resolver was failing to
find the NuGet assemblies previously. The NuGet SDK resolver supports
a MSBUILD_NUGET_PATH environment variable which can be set to the
directory containing the NuGet assemblies that are included with
the NuGet addin. This is now set by the NuGet addin which allows
the NuGet SDK resolver to work.
=> [NuGet] Allow NuGet SDK resolver to find NuGet assemblies

main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/DebugValueTooltipProvider.cs
Remove the null check for the DocumentContext.ParsedDocument. This
allows tooltips to be shown when the document does not have an
associated parser. This makes it possible for a text editor extension
to implement the IDebuggerExpressionResolver and provide debug value
tooltips without having to provide a dummy ParsedDocument or implement
the debug value tooltip UI itself.
Also changed the code since it was creating a local variable for a
parameter that was passed into the method so the local variable was
not needed. The code when it was originally created was using the
workbench's active document so a local variable was needed then.
=> [SourceEditor] Allow debug value tooltips for documents without parser

main/src/addins/CSharpBinding/CSharpBinding.addin.xml, main/src/addins/CSharpBinding/MonoDevelop.CSharp.Features/AutoInsertBracket/CSharpAutoInsertBracketHandler.cs, main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.addin.xml, main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/DefaultAutoInsertBracketHandler.cs, main/src/core/MonoDevelop.Ide/ExtensionModel/MonoDevelop.Ide.addin.xml, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/AutoInsertBracketTextEditorExtension.cs
There's now a first pass filter using the file extension and mimetype, avoiding loading assemblies/types until needed. More specific matches are preferred over less specific matches, so there's less need to worry about node ordering.
The extension point now respects conditions on the editor context, and automatically refreshes when the mimetypes or the context change.
=> Improve AutoInsertBracketHandler extension filtering

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Parser/CSharpParsedDocument.cs
from the search window
Turns off c# parsed document folding - that now done by roslyn block
structure folding.
=> Fixes issue #4655 Text editor corrupts when you navigate to a file

main/src/addins/MacPlatform/MacPlatform.cs
The original implementation checks Gtk toplevels only and does not take real native modal windows into account.
Fixes bxc #59012 - [VSfM] Menu Bar Options are available to user even if Pop Ups are Over IDE
=> [59012][Mac] Fix IsModalDialogRunning for native dialogs

main/external/Makefile.am, main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.csproj, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj, main/xbuild.include
Fix some local copies that were causing invalidation of output directories and some small changes to how nuget package restoration works from makefiles (we already do it via the main `make` target)
=> Build incrementality improvements

main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj
This fixes build failures on Windows with users whose MonoDevelop git
checkout is in a path with a space in it.
=> Quote executagble paths in <Exec /> in MonoDevelop.Core.csproj

main/external/fsharpbinding/MonoDevelop.FSharp.Tests/TemplateTests.fs
The template tests were failing when trying to install the Android
Support NuGet packages since these have been updated and need the
Android project to target at least 8.0. The tests were setting the
target framework version to 7.0. This has been changed to 8.1 which
is used by default in the Xamarin.Forms project templates.
=> [F#] Fix F# project template tests

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Composition/CompositionManager.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
What happens here is that our Composition Catalog uses Mono.Addins behind the scenes
to gather all the assemblies to load for composition.
On the other hand, that _also_ loads the addins into the current engine.
That means that MEF holds the addin lock, so IDE startup is inconsistent
across sessions, depending on who gets to hold the lock first.
This should fix the startup of the IDE by a big margin
=> [d15-7][Perf] Optimize startup by doing MEF composition query on idle

main/external/fsharpbinding/MonoDevelop.FSharp.Tests/TemplateTests.fs
The template tests were failing when trying to install the Android
Support NuGet packages since these have been updated and need the
Android project to target at least 8.0. The tests were setting the
target framework version to 7.0. This has been changed to 8.1 which
is used by default in the Xamarin.Forms project templates.
=> [d15-7][F#] Fix F# project template tests

main/src/addins/MonoDevelop.Refactoring/MonoDevelop.AnalysisCore/Gui/ResultsEditorExtension.cs, main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeActionEditorExtension.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Composition/CompositionManager.Caching.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Composition/CompositionManager.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/TagCommentsTextEditorExtension.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Tasks/CommentTasksProvider.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Tasks/TaskService.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Services.cs, main/tests/Ide.Tests/IdeTestBase.cs, main/tests/Ide.Tests/MonoDevelop.Ide.Composition/CompositionManager.CachingTests.cs, main/tests/Ide.Tests/MonoDevelop.Ide.Tests.csproj
This changeset aims to improve MEF Composition in a few ways:
a) Adding logging for when something on the UI thread queries MEF before it's loaded.
b) Fixes offenders
c) Adds timer infrastructure around MEF composition and refactors code
d) Implements a rudimentary MEF cache which decides whether to invalidate the MEF cache based on assembly timestamp changes
e) Reliability around MEF cache usage, so cache cannot become corrupt
f) Makes the cache logic unit testable
=> Improve startup time by optimizing MEF composition
