- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/RoslynClassificationHighlighting.cs
editor
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/587075
> Fixes VSTS 587075: Duplicate Android attributes displayed in text

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AppResult.cs
We need more info on:
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/586401
> [Ide] Add some error logging to AppResult.GetPropertyValue

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpTextEditorIndentation.cs
CSharpTextEditorIndentation
That prevents that this code runs on a disposed extension.
> Fixes issue #4257 IDE crash - null reference in

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Tests.csproj
- main/tests/Ide.Tests/MonoDevelop.Ide/TypeSystemServiceTests.cs
- main/tests/Ide.Tests/TypeSystemServiceTestExtensions.cs
* [Workspace] De-asynchronify the workspace initial location setting
* [Ide] Return the workspace for loading a solution
* [Ide] Add test for persistent storage creation
Fixes VSTS #583994 Add unit test that verifies persistent storage has been created
* Simplify test and add storage locations ervice test
* Only delete the storage if it exists
> Persistent storage test (#4235)

- main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.VsTest/VsTestAdapter.cs
Backport of #4282.
/cc @Therzok
> [master] Fix 541368: MSTest not supported in .NET Framework library project

- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Actions/CaretMoveActions.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Actions/DeleteActions.cs
- main/src/core/MonoDevelop.TextEditor.Tests/Mono.TextEditor.Tests.DefaultEditActions/CaretMoveActionTests.cs
- main/src/core/MonoDevelop.TextEditor.Tests/Mono.TextEditor.Tests.DefaultEditActions/DeleteActionTests.cs
and lead to a fatal error
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/577507
> Fixes VSTS 577507: [Feedback] Emojis in XAML files break the editor

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputTreeCellView.cs
* Reduce amount of required size recalculations
* Relayout the TextLayout only if really needed
* Improve search results highlighting
* small bugfixes
> [BuildOutput] Optimize size calculations Pt. 2

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreMSBuildProjectTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.csproj
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreMSBuildProject.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreShortTargetFramework.cs
Backport of #4285.
/cc @mrward
> [d15-7] [DotNetCore] Fix TargetFramework short name format changing on save

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/LogView.cs
> [IDE] Use a unique name for the tag

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebuggingService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Ide.cs
> [d15-7] Fix 581032: Debugger session not properly exited

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputTreeCellView.cs
Fixes unselect items when there are no search text in combo
[Fixes #589023](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/589023)
> Fixes unselect items when there are no search text in combo

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputNode.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputTreeCellView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputWidget.cs
Adds feature to Expand Errors and Warnings by click on Summary
> Expand Errors and Warnings by click on Summary

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CSharpCompletionTextEditorExtension.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CompletionProvider/ProtocolMemberCompletionProvider.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding/CSharpCompletionTextEditorTests.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/564610
Work around for injecting protocol completion into the override
context.
> Fixes VSTS 564610: code completion is broken

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/Formats/Sublime3Format.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/RoslynClassificationHighlighting.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/SyntaxHighlighting.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Editor/SyntaxHighlightingTest.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/589495
> Fixes VSTS 589495: Opening Makefile in mono/monodevelop crashes IDE

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/FoldMarkerMargin.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/IconMargin.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/Margin.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AtkCocoaHelper/AtkCocoaHelper.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AtkCocoaHelper/AtkCocoaHelperMac.cs
> Fix 515126 d157

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Gui/DotNetCoreSdkLocationPanel.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Gui/DotNetCoreSdkLocationWidget.UI.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Gui/DotNetCoreSdkLocationWidget.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.NodeBuilders/DotNetCoreProjectNodeBuilderExtension.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.csproj
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCorePath.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreRuntime.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreRuntimeVersions.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdk.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdkInstalledCondition.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdkPaths.cs
- main/src/addins/MonoDevelop.DotNetCore/Properties/MonoDevelop.DotNetCore.addin.xml
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/MicrosoftTemplateEngine.cs
Backport of #4240.
/cc @mrward
> [d15-7] [DotNetCore] Allow .NET Core location to be configured 

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
Backport of #4378.
/cc @mkrueger
> [d15-7] Fixes issue #4346 Text editor - curly brace problems

- main/Directory.Build.props
- main/src/core/MonoDevelop.Core/packages.config
- version-checks
Roslyn is included for an IVT fix
Roslyn also bumped VSEditor
> Bump Roslyn and VSEditor

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/Formats/OldFormat.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/StackMatchExpression.cs
Backport of #4413.
/cc @mkrueger
> [d15-7] Fixes issue #4329 Enum Color Syntax Incorrect

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/HighlightUnusedCode.fs
Fixes VSTS #591145 (#4351)
Fixes VSTS #593854 (#4411)
> Fix fatal exception in unused code highlighter

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/HighlightUnusedCode.fs
Backport of #4416.
/cc @nosami
> [d15-7] Fix fatal exception in unused code highlighter

- .gitignore
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/ToolboxExtensions.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.csproj
Add helpers for working with toolbox interfaces. Partial fix for #3559.
> Toolbox helpers

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
Backport of #4419.
/cc @mkrueger
> [d15-7] Fixes VSTS 592988: Code colors flicker black when typing

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/ProjectWithWildcardsTests.cs
- main/tests/test-projects/console-project-with-wildcards/ConsoleProject-with-link-wildcard.csproj
- main/tests/test-projects/console-project-with-wildcards/ConsoleProject-with-link-wildcard.csproj.saved1
Backport of #4303.
/cc @mrward
> [d15-7] [Core] Fix wildcards being expanded on saving a project

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/ProjectReevaluationTests.cs
Backport of #4353.
/cc @mrward
> [d15-7] [Core] Fix references not saved on installing NuGet packages

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/ProjectReevaluationTests.cs
The fix applied in commit c459d3c
now means that Project.ReevaluateProject can be called at the same
time as NuGet packages are being installed if those NuGet packages
contains MSBuild imports. When creating a new Xamarin.Forms project
references are added to the Android project at the same time that
the ReevaluateProject method is called, indirectly when the type
system calls GetSourceFilesAsync and causes the CoreCompileDependsOn
targets to be run. During the call to MSBuildProject.EvaluateAsync,
which the ReevaluateProject method awaits on, the UI thread can be
used to add a new reference to the project. If the project is not
saved the MSBuildProject is not updated so the LoadProjectItems
was removing the references added to the project since they do not
exist in the evaluated items. …
> [Core] Fix references not saved on installing NuGet packages

- main/src/core/MonoDevelop.Ide/ExtensionModel/MonoDevelop.Ide.addin.xml
> [MEF] Include EditorFeatures.Text into composition

- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/SyntaxHighlighting.fs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/syntaxes/FSharp/F#.sublime-syntax
Backport of #4421.
/cc @nosami
> [d15-7] Fix function highlighting. Fixes VSTS #586435 (#4242)

- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Collections/LookupTable.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/ProjectReevaluationTests.cs
- main/tests/test-projects/console-project/ConsoleProject/ConsoleProject-duplicate-reference.csproj
- main/tests/test-projects/console-project/ConsoleProject/ConsoleProject-triplicate-reference.csproj
Backport of #4325.
/cc @mrward
> [d15-7] [Core] Fix duplicate key restore error if duplicate files in project

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
https://github.com/mono/monodevelop/issues/4346
> Fixes issue #4346 Text editor - curly brace problems

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/HighlightUnusedCode.fs
Backport of #4416.
/cc @nosami
> [d15-6] Fix fatal exception in unused code highlighter

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/CompletionController.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/566339
> Fixes VSTS 566339: Completion tooltip popup flickers

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/CompletionController.cs
Backport of #4453.
/cc @mkrueger
> [d15-7] Fixes VSTS 566339: Completion tooltip popup flickers

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Features/GotoDefinition/GotoDefinitionService.cs
(possibly while solution is reloading)
> Fixes issue #4452 [C#] Go to Definition NRE when trying to navigate

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Features/GotoDefinition/GotoDefinitionService.cs
Backport of #4473.
/cc @mkrueger
> [d15-7] Fixes issue #4452 [C#] Go to Definition NRE when trying to navigate

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs
Lowered the tooltip timeout to a value that feels more in line with
other applications.
> Fixes issue #4469 Make tooltip timeout configurable

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.IMonoDevelopEditorOperations.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/EditActions.cs
Backport of #4483.
/cc @nosami
> [d15-7] EditActions.MoveCaretRight moves caret right

- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/DocumentUpdateRequest.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/TextDocument.cs
Remove/Add marker needed to remove the layout cache in the chunk
altering text marker case.
> Fixes issue #4493 Unused highlighting does not work anymore

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CompletionProvider/ProtocolMemberCompletionProvider.cs
Backport of #4387.
/cc @Therzok
> [d15-7] Supply SortText to preserve protocol methods in the completion list

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
Main fix for this bug is in `LoadProject` method, problem was that if multiple calls to `LoadProject` were made, 1st call called `GetProjectData` and `CreateProjectData` and when second call called `GetProjectData` to set `oldProjectData` it was empty because 1st call didn't call `CreateDocuments` yet, resulting in `documentIdMap` being empty, hence documentIds were totally different after project reload, causing issues with GoToDefinition command...
While working on this I also noticed that OnProjectModified is called ~10 times when restoring NuGets for Android project and none of this is canceled, in theory it could happen that older version finishes after latest version and cause project references list to be outdated, hence I added logic to cancel old requests...
> Fix 594883: Goto Declaration is not available when creating an Android project

- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/DocumentUpdateRequest.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/TextDocument.cs
Backport of #4495.
/cc @mkrueger
> [d15-7] Fixes issue #4493 Unused highlighting does not work anymore

- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/Interactive.fs
Backport of #4510.
/cc @nosami
> [d15-7] Test remove timeouts

- main/src/addins/MacPlatform/MacPlatform.cs
Assembly Load events can happen in parallel, so we need to guard it,
because Runtime.RegisterAssembly is not thread-safe
ERROR [2018-04-11 12:54:05Z]: Error while trying to load the project /Users/davidkarlas/Downloads/MVVMSample1/MVVMSample1.Core/MVVMSample1.Core.csproj
System.ArgumentException: An item with the same key has already been added. Key: FSharpBinding, Version=0.0.0.0, Culture=neutral, PublicKeyToken=3ead7498f347467b
at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x000ad] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-02/external/bockbuild/builds/mono-x64/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/Dictionary.cs:424
at …
> [Mac] Fix random crash that could happen on assembly load

- main/src/addins/MacPlatform/MacPlatform.cs
Backport of #4513.
/cc @Therzok
> [d15-7] [Mac] Fix random crash that could happen on assembly load

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/WorkspaceItem.cs
- main/tests/Ide.Tests/MonoDevelop.Ide/UserPreferencesTests.cs
Backport of #4516.
/cc @mrward
> [d15-7] [Core] Fix files not re-opened on opening a solution

- main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.Formats.MSBuild/BuildEngine.v4.0.cs
Backport of #4503.
/cc @mrward
> [d15-7] [MSBuild] Fix unsaved project xml not cleared in remote build engine

- .editorconfig
> Add F# settings as editorconfig overrides IDE settings

- .editorconfig
Backport of #4535.
/cc @nosami
> [d15-7] Add F# settings as editorconfig overrides IDE settings

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.SpanUpdateListener.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.csproj
- main/src/core/MonoDevelop.TextEditor.Tests/Mono.TextEditor.Tests/TextViewTests.cs
- main/src/core/MonoDevelop.TextEditor.Tests/MonoDevelop.TextEditor.Tests.csproj
forward port of https://github.com/mono/monodevelop/pull/4488
That adds a better solution for the problem + unit tests.
> Master fix multispan highlighting

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.SpanUpdateListener.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.csproj
- main/src/core/MonoDevelop.TextEditor.Tests/Mono.TextEditor.Tests/TextViewTests.cs
- main/src/core/MonoDevelop.TextEditor.Tests/MonoDevelop.TextEditor.Tests.csproj
Test case:
Code should not flicker black while typing.
The /* should update next lines.
/* 
Code <- should be commented.
The old fix broke a work around that fixed the /* updating.
Fixes VSTS #594738.
> D15 6 fix592988

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.QuickTasks/QuickTaskOverviewMode.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/HslColor.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Styles.cs
Backport of #4531.
/cc @slluis
> [d15-7] [529478][Editor] Fix search marker fallback color

- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/ProjectTests.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpProjectFileNodeExtension.fs
> Allow XAML files and codebehind files to be moved as a single unit

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AtkCocoaHelper/AtkCocoaHelperMac.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AtkCocoaHelper/AtkCocoaHelperNoOp.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/CompletionListWindowGtk.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/ListWidget.cs
> [A11y] Make the Autocompletion suggestion window accessible in VO

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreCertificateManager.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreRunConfiguration.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/DotNetCoreDevCertsTool.cs
Backport of #4553.
/cc @mrward
> [d15-7] [AspNetCore] SDK Preview 2 Changes

- version-checks
> Updated reference to md-addins

- main/src/addins/MacPlatform/MacPlatform.cs
Backport of #4558.
/cc @sevoku
> [d15-7] [600128][Mac] Disallow window tabbing mode

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs
- main/src/addins/Xml/Parser/XmlNameState.cs
- main/src/addins/Xml/Parser/XmlRootState.cs
- main/src/addins/Xml/Parser/XmlTagState.cs
- main/src/addins/Xml/Tests/Parser/AttributeNameTestFixture.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Util/SimpleBracketMatcher.cs
> [master] Fix 597220: No IntelliSense for pages deriving from a custom ContentPage

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
> [master] Fix 594883: Goto Declaration is not available when creating an Android project

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AtkCocoaHelper/AtkCocoaHelperMac.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AtkCocoaHelper/AtkCocoaHelperNoOp.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/CompletionListWindowGtk.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/ListWidget.cs
Reverts mono/monodevelop#4548
Reverting because it causes longer delays on long completion lists
> Revert "[A11y] Make the Autocompletion suggestion window accessible in VO"

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/FileCommands.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs
keyboard shortcut multiple times
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/591324
This method isn't called anywhere else.
> Fixes VSTS 591324: Multiple Popup save dialog when close using

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreSdkTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreNotInstalledDialog.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdk.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/TargetFrameworkExtensions.cs
Backport of #4589.
/cc @mrward
> [d15-7] [DotNetCore] Handle .NET Core 2.1 SDK not installed

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/OSXEditor.cs
Backport of #4546.
/cc @mkrueger
> [d15-7] Fixes VSTS 597271: [Feedback] Getting \u0022The type initializer for

- main/src/addins/MonoDevelop.SourceEditor2/VSEditor/TagBasedSyntaxHighlighting.cs
> [master] Fix VSTS 584214: access Roslyn ClassifierAggregator on UI thread

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs
- main/src/addins/MonoDevelop.SourceEditor2/VSEditor/TagBasedSyntaxHighlighting.cs
> [master] Invalidate cached line upon TextArea.RedrawLine

- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/TextDocument.cs
> [master] Fix VSTS 586112: ignore TextChange events with no Changes

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/LogView.cs
Check if a tag is present before adding or removing it from the tag table,
because EndTask can be called multiple times for the same monitor.
Fixes VSTS #591647
> [15.7] [IDE] Check if a tag is present before adding or removing it

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/DotNetCoreNuGetProject.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageCompatibilityHandler.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageReferenceNuGetProject.cs
Backport of #4625.
/cc @mrward
> [d15-7] [NuGet] Restore PackageReference project after target framework changed

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/BlockStructureFoldingTextEditorExtension.cs
That collides with the custom fast folding parser and causes redraw errors because of event less fold/unfolds.
However the 1st fold update is just for syntactical folds that should be as fast as possible.
> [Ide] Fixed block structure folding.

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.AnalysisCore/Gui/ResultsEditorExtension.cs
Backport of #4636.
/cc @mkrueger
> [d15-7] Fixes issue #4633 ResultsEditorExtension:

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
> [master] Fix VSTS 586152: Preserve documents on project reload

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.AnalysisCore/Gui/ResultsEditorExtension.cs
DocumentContext.AnalysisDocument may be null
> Fixes issue #4633 ResultsEditorExtension:

- main/build/MacOSX/monostub.mm
This reverts commit 9276485a68853e316c7e3c6503df1ddaba093a15.
> Revert "[build] Make the static registrar opt-in, not opt-out"

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/LogView.cs
Check if a tag is present before adding or removing it from the tag table,
because EndTask can be called multiple times for the same monitor.
Fixes VSTS #591647
> [IDE] Check if a tag is present before adding or removing it

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
Seems like the .so file cannot be loaded by `ld`. Need to investigate further.
> [Linux] Temporarily disable persistent storage on linux

- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/FrameworkInfo.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/MonoFrameworkBackend.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/MsNetFrameworkBackend.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/SupportedFramework.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/TargetFramework.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/TargetFrameworkBackend.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/TargetRuntime.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.OptionPanels/PortableRuntimeSelectorDialog.cs
Add some caching and simplifying assumptions in SystemAssemblyService. 
Reduces SystemAssemblyService initialization time from 750ms to 180ms on my machine.
> Improve SystemAssemblyService initialization time

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/TypeSystemService_WorkspaceHandling.cs
> [master] Fix VSTS 602848: Project Reload doesn\u0027t work

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/RefactoringOperationsHandler.fs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Refactoring/CSharpFindReferencesProvider.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Refactoring/FindReferencesHandler.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Refactoring/RefactoryCommands.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/FindReferencesProvider.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/RefactoringService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/SearchProgressMonitor.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding.Refactoring/CSharpFindReferencesProviderTests.cs
> [master] Fix 587803: [Feedback] Find References command is slow 

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Parser/CSharpParsedDocument.cs
- main/src/core/MonoDevelop.Ide/ExtensionModel/MonoDevelop.Ide.addin.xml
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/ErrorHandlerTextEditorExtension.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/TagCommentsTextEditorExtension.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Tasks/CommentTag.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Tasks/CommentTasksProvider.Legacy.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Tasks/CommentTasksProvider.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Tasks/CommentTasksView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Tasks/TaskService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/Tag.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/RootWorkspace.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Tasks/CommentTasksProviderTests.Controller.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Tasks/CommentTasksProviderTests.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Tests.csproj
Switches the todo comments implementation from the custom C# Parsed Document one to the roslyn engine.
> Todo comments implementation

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/TextMarker/SmartTagMarker.cs
Line data structures are no longer comparable.
> Fixes issue #4667 [TextEditor] SmartTag marker position wrong.

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CompletionProvider/ProtocolMemberCompletionProvider.cs
C# code editor
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/605909
> Fixes VSTS 605909: IDE crash on attempt to override something in the

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CompletionProvider/ProtocolMemberCompletionProvider.cs
Backport of #4681.
/cc @mkrueger
> [d15-7] Fixes VSTS 605909: IDE crash on attempt to override something in the

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/TextMarker/SmartTagMarker.cs
Backport of #4668.
/cc @mkrueger
> [d15-7] Fixes issue #4667 [TextEditor] SmartTag marker position wrong.

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionItem.cs
Cherry-picked from the old unify-refs branch
> [Project] Log filename for unsupported project errors

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CompletionProvider/DelegateCompletionProvider.cs
event handler shown in intellisense window
> Fixes issue #4695 Attempt to access UI from background thread when

- main/src/core/MonoDevelop.Ide/ExtensionModel/StockIcons.addin.xml
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputTreeCellView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/StockIcons.cs
Fixes icon in expander in selected states
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/604892?src=WorkItemMention&src-action=artifact_link
> [Mac] Fixes icon in expander in selected states

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/BlockStructureFoldingTextEditorExtension.cs
They're filled by roslyn so IMO roslyn should remove the single line case somehow but I can't find any code for that so I assume vs does it on a higher level.
> Fixes issue #4747 Single-line members should not be collapsible.

- main/src/addins/Deployment/MonoDevelop.Deployment/MonoDevelop.Deployment.csproj
- main/src/addins/Deployment/MonoDevelop.Deployment/packages.config
This mirrors the version of SharpZipLib used in MonoDevelop.Ide
> Use NuGet for SharpZipLib in MonoDevelop.Deployment

- main/src/addins/MacPlatform/MainToolbar/SelectorView.cs
#4721 for `d15-7`, fixes VSTS #610547
(cherry picked from commit 3e08200d94e486103ff61da35330e08a12bfd351)
> [15.7][610547][Mac] Fix device selection with special characters

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CompletionProvider/DelegateCompletionProvider.cs
Backport of #4707.
/cc @mkrueger
> [d15-7] Fixes issue #4695 Attempt to access UI from background thread when

- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Execution/RemoteProcessConnection.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
- main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.Formats.MSBuild/ProjectBuilder.v4.0.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/ProjectBuildTests.cs
- main/tests/test-projects/builder-manager-tests/crasher/ConsoleProject.csproj
- main/tests/test-projects/builder-manager-tests/crasher/Program.cs
- main/tests/test-projects/builder-manager-tests/crasher/Properties/AssemblyInfo.cs
Backport of #4692.
/cc @slluis
> [d15-7] Fix concurrency issues in RemoteProcessConnection

- version-checks
Fixes VSTS #614238
Fixes VSTS #610340
> Bump md-addins to 32cc296

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.OptionProvider/CSharpDocumentOptionsProvider.cs
Fixes VSTS bug #613507
Fixes VSTS bug #606153
> Fixes convert tabs to spaces option being ignored

- main/src/addins/GnomePlatform/GnomePlatform.cs
Should fix https://github.com/mono/monodevelop/issues/4471, I think everything's right, please check my code. Thanks @directhex for the help.
> [Linux] Add support for XFCE's xfce4-terminal

- main/src/core/MonoDevelop.Core/MonoDevelop.Core/SystemInformation.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
For local builds:
```
INFO [2018-05-10 18:37:38Z]: Starting Visual Studio 2017 for Mac (Preview) 7.6 Preview (7.6)
INFO [2018-05-10 18:37:38Z]: Build Information
0cbd6f987cca7bc765be12d99966091be1d7a031
Xamarin extensions: 0dd558a39b82af50559b8ccd1f17f4933a11af51
```
For released builds:
```
INFO [2018-05-10 18:38:35Z]: Starting Visual Studio 2017 for Mac (Preview) 7.6 Preview (7.6)
INFO [2018-05-10 18:38:35Z]: Build Information
Release ID: $number
Git revision: 0cbd6f987cca7bc765be12d99966091be1d7a031
Build date: 2018-05-10 12:53:24+00
Build branch: master
Xamarin extensions: 0dd558a39b82af50559b8ccd1f17f4933a11af51
```
> [Log] Add build info to the IDE log

- main/src/addins/MonoDevelop.WebReferences/MonoDevelop.WebReferences.WS/WebServiceDiscoveryResultWS.cs
Backport of #4785.
/cc @mrward
> [d15-7] [WebReferences] Fix background thread used when adding file to project

- main/src/addins/MonoDevelop.UnitTesting/Services/UnitTestService.cs
This change moves rebuilding unit tests from UI thread to Threadpool and handles cancelation if newer requests comes in.
> Fix 591905: VSTest adapter delays solution load

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputTreeCellView.cs
We were overriding current cursor with arrow icon in all cases
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/602797
> Fixes wrong cursor display icon

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeFixMenuService.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeIssues/CodeIssuePanelWidget.cs
+Fixed the search highlight color - it was unreadable in dark theme.
> Fixes issue #4810 Configure Rule Quick Fix should filter rules

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/InsertionModeOptions.cs
> Fixes issue #4691 Create new event handler method wants to put method

- version-checks
Pull in the last few changes, to include e572c402cfd550f37f800dfcbc8a0bf12e894b29 etc
> Updated reference to xamarin/md-addins@34d80c1

- main/src/addins/VBNetBinding/MonoDevelop.VBNet/VBNetTextEditorExtension.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/DocumentContext.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopSourceTextContainer.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/TypeSystemService.cs
1494392 (d15-7 - c0d878b)
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/586401
> Fixes VSTS 586401: TestGotoDeclarationOpensAssemblyBrowser Failed in

- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/FrameworkInfo.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/MonoFrameworkBackend.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/MsNetFrameworkBackend.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/SupportedFramework.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/TargetFramework.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/TargetFrameworkBackend.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/TargetRuntime.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.OptionPanels/PortableRuntimeSelectorDialog.cs
Backport of #4648.
/cc @mhutch
> [d15-7] Improve SystemAssemblyService initialization time

- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/DocumentUpdateRequest.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/TextDocument.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/RoslynClassificationHighlighting.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/LineEventArgs.cs
Backport of #4622.
/cc @mkrueger
> [d15-7] Fixes VSTS 599407: C# classification doesn\u0027t update when compilation

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/PathBar.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputWidget.cs
Adds additional padding to PathBar to match with other canvas elements
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/604889
> Adds additional padding to PathBar to match with other canvas elements

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputNode.cs
Renders extra 0 in Seconds Time Stamp when there are minutes
It also does the same behaviour with Minutes when there are hours
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/590737
> Renders extra 0 in Seconds Time Stamp when there are minutes

- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/Interactive.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpInteractivePad.fs
> Fix shell history in F# Interactive order

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeTemplates/CodeTemplate.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Editor/CodeSnippetTests.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Tests.csproj
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/620177
> Fixes VSTS 620177: [Feedback] VS for Mac: code snippet problem

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
Use an ImmutableArray instead of an ImmutableList builder to hold
the evaluated source files in the project. ImmutableArray is a thin
wrapper around a normal array.
> [Core] Switch to ImmutableArray for holding evaluated source files

- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/TextDocument.cs
- main/src/core/MonoDevelop.TextEditor.Tests/Mono.TextEditor.Tests/FoldingTests.cs
Backport of #4733.
Fixes VSTS bug #612695
/cc @slluis
> [d15-7] Fixes VSTS 610190: Collapsed Regions Auto Expand

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/RefactoringOperationsHandler.fs
... when looking for local val bindings
Fixes VSTS #597602 (#4482)
> [F#] Find references should not check dependent projects

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.DockNotebook/TabStrip.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DefaultWorkbench.cs
> [Ide] Fix command route for document tab context menu commands

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/TemplateWizard.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/TemplateWizardProvider.cs
Needed for the Azure Functions wizard because the number of pages
is dynamic depending on which function is selected.
(Also needed to handle if the user hits Back and selects a different
function template)
> [Templates] Provide a way for Wizards to change their number of pages

- main/src/addins/MonoDevelop.Packaging/MonoDevelop.Packaging.Tests/MonoDevelop.Packaging.Tests/AddPlatformImplementationTests.cs
- main/src/addins/MonoDevelop.Packaging/MonoDevelop.Packaging.Tests/MonoDevelop.Packaging.Tests/ProjectTemplateTests.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices/MonoDevelopNotificationServiceFactory.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
- main/tests/Ide.Tests/MonoDevelop.Ide.Projects/NewProjectDialogTests.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.RoslynServices/MonoDevelopNotificationServiceIntegrationTests.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Tests.csproj
- main/tests/Ide.Tests/ProjectTemplateTests.cs
Will be used once we switch to roslyn's commanding system
> [Ide] Implement INotificationService

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/FoldMarkerMargin.VSNetFoldMarkerMarginDrawer.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/FoldMarkerMargin.cs
accessibility
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/621747
> Fixes VSTS 621747: Only showing code folding on mouseover breaks

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Services.cs
Add property to help identify startup time just after installation or upgrade.
Fixes VSTS #622583
Needs https://github.com/xamarin/md-addins/pull/3195.
> Improve startup time measurement

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/RootWorkspace.cs
- main/tests/Ide.Tests/MonoDevelop.Ide/TypeSystemServiceTests.cs
When loading a solution set the stored active configuration before adding
the solution to the workspace. In this way roslyn will use the correct
configuration to do the initial analysis, instead of trying to load with the
default configuration and later load again when stored preferences are
restored.
Fixes VSTS #603762 - LoadProject is called twice on solution load due
to configuration change
> Small project loading optimization

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Features/AutoInsertBracket/AbstractTokenBraceCompletionSession.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/SegmentTree.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/EditSession.cs
- main/src/core/MonoDevelop.TextEditor.Tests/Mono.TextEditor.Tests/SegmentTreeTests.cs
The segmenttree bug was a surprise…
> Fixes issue #3639 Add overtype marker in editor

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
> [PerfMetrics] Handle a null on Windows

- main/external/fsharpbinding/MonoDevelop.FSharp.Shared/Parser.fs
- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/CompletionTests.fs
- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/ParsingTests.fs
- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/TestHelpers.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpInteractivePad.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpParsedDocument.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpParser.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpTextEditorCompletion.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpTokens.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpTooltipProvider.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/CompilerArguments.fs
- main/external/fsharpbinding/paket.lock
Fixes VSTS #569960 (#3892)
Fixes VSTS #563771 (#3799)
Fixes VSTS #623092
> [F#] Various intellisense improvements

- main/src/core/MonoDevelop.Core/MonoDevelop.Core/Runtime.cs
Make sure old repository urls that don't use https are removed.
> Fix duplicate add-in repos

- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Actions/DeleteActions.cs
- main/src/core/MonoDevelop.TextEditor.Tests/Mono.TextEditor.Tests.DefaultEditActions/DeleteActionTests.cs
- main/src/core/MonoDevelop.TextEditor.Tests/Mono.TextEditor.Tests/SmartIndentModeTests.cs
Backport of #5050.
/cc @mkrueger
> [release-7.6] Fixes VSTS Bug 624076: No backspace on any smart-indented line in web

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputWidget.cs
Fixes VSTS #625411 - Sometimes the build output does not update after building again
> [BuildOutput] Unsubscribe from events on Dispose

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
This commit introduces some changes around MSBuild evaluation so unnecessary work is not done (logging, evaluation)
> [Core] Improve some MSBuild target runs

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
Backport of #4921.
Fixes issue #4906
/cc @mkrueger
> [d15-7] Fixes issue #4906 Gutter on the left corrupts when you hover over the

- main/winbuild.bat
Else we end up with missing deps
> [Win32] MSBuild restore whole solution

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpTextEditorIndentation.cs
- main/tests/IdeUnitTests/TextEditorExtensionTestBase.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding/CSharpTextEditorIndentationTests.cs
Param ref
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/567503
Basically it removes our old logic and ports the roslyn logic to the
indentation layer.
> Fixes VSTS Bug 567503: [Feedback] Documentation Comments: Exception,

- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Actions/DeleteActions.cs
- main/src/core/MonoDevelop.TextEditor.Tests/Mono.TextEditor.Tests.DefaultEditActions/DeleteActionTests.cs
- main/src/core/MonoDevelop.TextEditor.Tests/Mono.TextEditor.Tests/SmartIndentModeTests.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Editor/SkipCharSessionTests.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding/CSharpCompletionTextEditorTests.cs
editors
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/624076
> Fixes VSTS Bug 624076: No backspace on any smart-indented line in web

- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/TextDocument.cs
- main/src/core/MonoDevelop.TextEditor.Tests/Mono.TextEditor.Tests/UndoRedoTests.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/633531
> Fixes VSTS Bug 633531: File save sometimes not working

- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/TextDocument.cs
- main/src/core/MonoDevelop.TextEditor.Tests/Mono.TextEditor.Tests/UndoRedoTests.cs
Backport of #5070.
/cc @mkrueger
> [release-7.6] Fixes VSTS Bug 633531: File save sometimes not working

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputWidget.cs
Fixes VSTS #629161 - Log viewer does not show any loading progress
> [BuildOutput] Add a spinner when processing .binlog files

- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Execution/ProcessWrapper.cs
Fixes VSTS #633539 - Unable to re-run tests after stopping tests
> [ProcessWrapper] Some reliability fixes around process exiting

- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Execution/ProcessWrapper.cs
Backport of #5071.
/cc @Therzok
> [release-7.6] [ProcessWrapper] Some reliability fixes around process exiting

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs
- main/tests/test-projects/aspnetcore/aspnetcore.csproj
Backport of #5077.
/cc @mrward
> [release-7.6] [DotNetCore] Fix default build action for new file

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ItemCollection.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/DotNetCoreProjectTests.cs
Backport of #5079.
/cc @mrward
> [release-7.6] [Core] Fix .xaml.cs intellisense in new Forms .NET Standard project

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/DotNetCoreNuGetProjectTests.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/PackageReferenceNuGetProjectTests.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/DotNetCoreNuGetProject.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageReferenceNuGetProject.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/ProjectPackageReference.cs
Backport of #5091.
/cc @mrward
> [release-7.6] [NuGet] Fix updating PackageReference removes metadata

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
Backport of #5095.
/cc @mrward
> [release-7.6] [Core] Fix UI hang when building ASP.NET Core 2.1 Angular project

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpBinding.addin.xml
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FindReferenceUsages.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/MonoDevelop.FSharp.fsproj
- main/src/addins/CSharpBinding/CSharpBinding.addin.xml
- main/src/addins/CSharpBinding/CSharpBinding.csproj
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Refactoring/CSharpFindReferenceUsagesProvider.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Refactoring/FindProjectReferenceUsagesHandler.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.addin.xml
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.csproj
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/FindReferenceUsagesProvider.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/RefactoringService.cs
> Add FindReferenceUsagesHandler

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpTextPasteHandler.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding/CSharpTextEditorIndentationTests.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/634797
> Fixes VSTS 634797: Pasted text indents with extra whitespace

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/DefaultMSBuildEngine.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildEvaluationContext.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/ProjectLoadSaveTests.cs
- main/tests/test-projects/ImportCircularDependency/FirstImport.targets
- main/tests/test-projects/ImportCircularDependency/ImportCircularDependency.csproj
- main/tests/test-projects/ImportCircularDependency/ImportCircularDependency.sln
- main/tests/test-projects/ImportCircularDependency/SecondImport.targets
Backport of #5124.
/cc @mrward
> [release-7.6] [Core] Detect circular dependencies between MSBuild imports

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreMSBuildProjectTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreMSBuildProject.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProject.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildPropertyGroup.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/DotNetCoreProjectTests.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/MSBuildProjectTests.cs
- main/tests/test-projects/DotNetCoreNoMainPropertyGroup/Directory.Build.props
- main/tests/test-projects/DotNetCoreNoMainPropertyGroup/DotNetCoreNoMainPropertyGroup.sln
- main/tests/test-projects/DotNetCoreNoMainPropertyGroup/DotNetCoreNoMainPropertyGroup/DotNetCoreNoMainPropertyGroup.csproj
- main/tests/test-projects/DotNetCoreNoMainPropertyGroup/DotNetCoreNoMainPropertyGroup/Program.cs
Backport of #5114.
/cc @mrward
> [release-7.6] [Core] Allow loading of SDK style projects without TargetFramework  

- main/src/addins/MonoDevelop.SourceEditor2/VSEditor/TagBasedSyntaxHighlighting.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Editor/Commands/CodeCommentTests.cs
> [release-7.6] Fix #4822: Fixing code comment command for all cases

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputWidget.cs
Instead of just expanding them, scroll to the first one.
> [BuildOutput] Fix expansion of errors/warnings nodes

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputWidget.cs
Several small fixes for the structured-build-output feature
> Build output fixes

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/RefactoringOperationsHandler.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/Extensions.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/LanguageService.fs
> Find extension members should work in the background

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FakeSearchCategory.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/HighlightUnusedCode.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/RefactoringOperationsHandler.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/Extensions.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/LanguageService.fs
Fixes https://github.com/mono/monodevelop/issues/5049 and makes all Asynchronous code more robust in general by adding implicit exception logging.
> Fix 632894

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs
Backport of #5129.
/cc @mrward
> [release-7.6] [Ide] Fix build not being done when file is unsaved

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextEditor.cs
Fixes #5172 Error in document creation causes cascade of errors leading to crash
> [Ide] Handle exception in editor extension initialization

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/FileRegistry.cs
NullReferenceException in
MonoDevelop.SourceEditor.FileRegistry.HasMultipleIncorrectEolMarkers
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/613921
Bug was: In case not all open documents are SourceEditorViews ->
crash.
+ removed some code duplication.
> Fixes VSTS Bug 613921: [Feedback] Cannot open file,

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/FileRegistry.cs
Backport of #5203.
/cc @mkrueger
> [release-7.6] Fixes VSTS Bug 613921: [Feedback] Cannot open file,

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpTextPasteHandler.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding/CSharpTextEditorIndentationTests.cs
Backport of #5116.
/cc @mrward
> [release-7.6] Fixes VSTS 634797: Pasted text indents with extra whitespace

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpFormatter.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.OptionProvider/CSharpDocumentOptionsProvider.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/EditorConfigService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/SingleFileDescriptionTemplate.cs
> Fixes issue #5178 EditorConfig settings not applied to new file added

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputWidget.cs
Backport of #5158.
/cc @rodrmoya
> [release-7.6] Build output fixes

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputTreeCellView.cs
Backport of #5211.
/cc @rodrmoya
> [release-7.6] [StructuredBuildOutput] Fixes Summary Links Cursor Display

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputWidget.cs
Backport of #5104.
/cc @slluis
> [release-7.6] [BuildOutput] Fix expansion of errors/warnings nodes

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/LanguageBundle.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/SyntaxHighlightingService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.TextMate/TextMateBundleOptionsPanelWidget.cs
> Fixes issue #5186 'extensions' and 'default' are displayed in language

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/LanguageBundle.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/SyntaxHighlightingService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.TextMate/TextMateBundleOptionsPanelWidget.cs
Backport of #5229.
/cc @mkrueger
> [release-7.6] Fixes issue #5186 \u0027extensions\u0027 and \u0027default\u0027 are displayed in language

- main/src/addins/MonoDevelop.SourceEditor2/VSEditor/TagBasedSyntaxHighlighting.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/Formats/OldFormat.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/DarkStyle.json
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/LightStyle.json
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/OblivionStyle.json
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/TangoStyle.json
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/VisualStudioStyle.json
Backport of #5217.
/cc @slluis
> [release-7.6] Make Razor HTML Server-Side Script background yellow.

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpFormatter.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.OptionProvider/CSharpDocumentOptionsProvider.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/EditorConfigService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/SingleFileDescriptionTemplate.cs
Backport of #5200.
/cc @mkrueger
> [release-7.6] Fixes issue #5178 EditorConfig settings not applied to new file added

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorWidget.cs
changes" enabling code folding
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/618235
No need to upcast in that case.
> Fixes VSTS Bug 618235: Occasional "There was an error saving the

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorWidget.cs
Backport of #5233.
/cc @mkrueger
> [release-7.6] Fixes VSTS Bug 618235: Occasional \u0022There was an error saving the

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextEditorKeyPressTimings.cs
> [Telemetry] Include the buckets in the typing event

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads/ErrorListPad.cs
Backport of #5218.
/cc @slluis
> [release-7.6] [Ide] Re-add old text log viewer

- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/TextSegmentMarker.cs
That resets the line dash as well.
> Fixes issue #5160 Graphical glitching in the text editor.

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.AnalysisCore/Gui/ResultsEditorExtension.cs
Fixes VSTS #638581 - Error in QuickTaskStrip
> [Refactoring] Prevent collection modification while enumeration

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/RefactoringPreviewTooltipWindow.cs
See individual commits, fixes https://github.com/mono/monodevelop/issues/5136
> [CodeFix] Move work onto the background thread

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Rename/RenameRefactoring.cs
- main/tests/MonoDevelop.Refactoring.Tests/MonoDevelop.Refactoring.Tests.csproj
- main/tests/MonoDevelop.Refactoring.Tests/MonoDevelop.Refactoring/RenameRefactoringTests.cs
Backport of #5250.
/cc @mkrueger
> [release-7.6] Fixes issue #5162 Renaming method should not trigger removal of  generic type arguments

- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/TextSegmentMarker.cs
Backport of #5248.
/cc @mkrueger
> [release-7.6] Fixes issue #5160 Graphical glitching in the text editor.

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.AnalysisCore/Gui/ResultsEditorExtension.cs
Backport of #5267.
/cc @slluis
> [release-7.6] [Refactoring] Prevent collection modification while enumeration

- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/Cecil/EventDefinitionNodeBuilder.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/Cecil/FieldDefinitionNodeBuilder.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/Cecil/PropertyDefinitionNodeBuilder.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/Cecil/TypeDefinitionNodeBuilder.cs
target Visibility is "Only public members"
Cecil has fortunately easy to use properties to check the
accessiblity.
> Fixes issue #5235 assembly browser does not show public members if

- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/Cecil/EventDefinitionNodeBuilder.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/Cecil/FieldDefinitionNodeBuilder.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/Cecil/PropertyDefinitionNodeBuilder.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/Cecil/TypeDefinitionNodeBuilder.cs
Backport of #5270.
/cc @mkrueger
> [release-7.6] Fixes issue #5235 assembly browser does not show public members if

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/RefactoringPreviewTooltipWindow.cs
Backport of #5259.
/cc @Therzok
> [release-7.6] [CodeFix] Move work onto the background thread

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DocumentRegistry.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Editor/DocumentReloadTests.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Tests.csproj
Backport of #5277.
/cc @mrward
> [release-7.6] [Ide] Fix renaming a class asks to reload the file

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/AbstractNavigationExtension.cs
Note: It's just one of numerous exceptions in the log.
> Fixes VSTS Bug 640356: IntelliSense/Type recognition breaks in editor

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/AbstractNavigationExtension.cs
Backport of #5268.
/cc @slluis
> [release-7.6] Fixes VSTS Bug 640356: IntelliSense/Type recognition breaks in editor

- main/src/core/MonoDevelop.Core/MonoDevelop.Core/FileService.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core/Runtime.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/PlatformService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/LocalizationService.cs
Backport of #5269.
/cc @mrward
> [release-7.6] [Ide] Addin startup logging and lazy loading

- main/tests/Ide.Tests/MonoDevelop.Ide.Editor/DocumentReloadTests.cs
Backport of #5285.
/cc @mrward
> [release-7.6] [Ide.Tests] Ensure Document is disposed

- main/src/core/MonoDevelop.Core/MonoDevelop.Core/Properties.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices.Options/MonoDevelopGlobalOptionPersister.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices.Options/OptionsExtensions.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices.Options/RoslynPreferences.Properties.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.RoslynServices.Options/MonoDevelopOptionPersisterTests.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.RoslynServices.Options/RoslynPreferencesTests.cs
Punts at serialization/deserialization issues, both in implementation and being out of sync with roslyn. See respective commits for issues they fix.
> [Roslyn] Fix serialization and deserialization issues

- main/src/core/MonoDevelop.Core/MonoDevelop.Core/Properties.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices.Options/MonoDevelopGlobalOptionPersister.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices.Options/OptionsExtensions.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices.Options/RoslynPreferences.Properties.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.RoslynServices.Options/MonoDevelopOptionPersisterTests.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.RoslynServices.Options/RoslynPreferencesTests.cs
Backport of #5247.
/cc @Therzok
> [release-7.6] [Roslyn] Fix serialization and deserialization issues

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopAddMetadataReferenceCodeActionOperationFactoryWorkspaceService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
Backport of #5261.
/cc @mkrueger
> [release-7.6] Fixes issue #5246 Add Reference quick fix does not add a reference The

- main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj
- main/src/core/MonoDevelop.Core/MonoDevelop.FSW/PathTree.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.FSW/PathTreeNode.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/FileWatcherService.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/WorkspaceItem.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Core.Tests.csproj
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.FSW/PathTreeNodeTests.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.FSW/PathTreeTests.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/FileWatcherTests.cs
This PR should be reviewed commit by commit.
The idea is that it uses a helper tree that mimicks the real filesystem tree to prune the maximum amount of directories being watched.
> [FSW] Fix resource starvation by using a helper class

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/VSCodeImport/javascript/syntaxes/JavaScriptReact.tmLanguage.json
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/VSCodeImport/typescript/syntaxes/TypeScriptReact.tmLanguage.json
This is a minor regression from updating our language files the last time.
> Add React file types (.jsx, .tsx) in tmLanguage.json files.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
Fixes VSTS #637580 - Updated FWLink for Automatic Feature Suppression
> [Roslyn] Update the fw link for roslyn full solution analysis disabling

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
Backport of #5298.
/cc @Therzok
> [release-7.6] [Roslyn] Update the fw link for roslyn full solution analysis disabling

- main/src/addins/AspNet/Projects/AspNetAppProjectFlavor.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Project/CSharpProjectExtension.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp/CSharpBindingCompilerManager.cs
- main/src/addins/Deployment/MonoDevelop.Deployment/MonoDevelop.Deployment/DefaultDeployServiceExtension.cs
- main/src/addins/ILAsmBinding/ILAsmProject.cs
- main/src/addins/MonoDevelop.GtkCore/MonoDevelop.GtkCore.GuiBuilder/GuiBuilderService.cs
- main/src/addins/MonoDevelop.Packaging/MonoDevelop.Packaging/PackagingProject.cs
- main/src/addins/VBNetBinding/Project/VBProjectExtension.cs
- main/src/addins/VBNetBinding/VBBindingCompilerServices.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MD1/MD1DotNetProjectHandler.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProjectExtension.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectExtension.cs
Rescues some more bits from #2445
> Obsolete legacy build APIs

- main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj
- main/src/core/MonoDevelop.Core/MonoDevelop.FSW/PathTree.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.FSW/PathTreeNode.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/FileWatcherService.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/WorkspaceItem.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Core.Tests.csproj
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.FSW/PathTreeNodeTests.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.FSW/PathTreeTests.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/FileWatcherTests.cs
Backport of #5256.
/cc @Therzok 
Fixes VSTS #638612.
> [release-7.6] [FSW] Fix resource starvation by using a helper class

- main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.VsTest/VsTestDiscoveryAdapter.cs
On opening a solution containing a .NET Core test can sometimes
result in a UI hang. The IDE log shows a background thread and the
UI thread both stuck awaiting test discovery:
var discoveredTests = await VsTestDiscoveryAdapter.Instance.DiscoverTestsAsync (Project);
VsTestProjectTestSuite/<OnCreateTests>d__12.MoveNext
in MonoDevelop.UnitTesting.VsTest/VsTestProjectTestSuite.cs:95
Not been able to reproduce this problem directly by opening a
solution. However by modifying the code so a background thread
calls the VsTestDiscoveryAdapter.Instance just before the UI thread
tries to call it then the UI can hang. The problem here is that
the static Instance variable creates a new instance of the
VsTestDiscoveryAdapter. The VsTestDiscoveryAdapter's constructor
created a new progress monitor. The …
> [VSTest] Fix potential UI hang

- main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.VsTest/VsTestDiscoveryAdapter.cs
Backport of #5310.
Fixes VSTS #641134
/cc @mrward
> [release-7.6] [VSTest] Fix potential UI hang

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlService.cs
Backport of #5303.
/cc @Therzok
> [release-7.6] [VCS] Fix exception propagation from VersionControlService

- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Instrumentation/TimerCounter.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Core/InstrumentationTests.cs
Backport of #5302.
/cc @Therzok
> [release-7.6] [Instrumentation] Fix possible crash when converting null to value type

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/VSCodeImport/javascript/syntaxes/JavaScriptReact.tmLanguage.json
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/VSCodeImport/typescript/syntaxes/TypeScriptReact.tmLanguage.json
Backport of #5292.
/cc @slluis
> [release-7.6] Add React file types (.jsx, .tsx) in tmLanguage.json files.

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildFileFormatException.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProject.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/MSBuildProjectTests.cs
Backport of #5295.
/cc @mrward
> [release-7.6] [Core] Improve error information on project load failure

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbarController.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Xwt/XwtThemedPopup.cs
Backport of #5307.
/cc @slluis
> [release-7.6] [IDE] Search results aren\u0027t shown with fullscreen and multiple monitors

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/StatusView.cs
Backport of #5318.
/cc @Therzok
> [release-7.6] [VCS] Fix Review and Commit selection persisting through context menu

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputTreeCellView.cs
Renderer now calculates the maximum possible width of the navigation link and trims it correctly
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/621000
> [StructuredOutput] Makes Navigation link trimmed

- main/src/addins/Xml/Dom/XAttributeCollection.cs
- main/src/addins/Xml/Editor/BaseXmlEditorExtension.cs
- main/src/addins/Xml/Editor/XmlExpandSelectionHandler.cs
- main/src/addins/Xml/MonoDevelop.Xml.csproj
- main/src/addins/Xml/Tests/ExpandSelectionTests.cs
- main/src/addins/Xml/Tests/MonoDevelop.Xml.Tests.csproj
Implement the expand selections/shrink selection command for XML files.
> [Xml] Implement Expand/Shrink selection for XML

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Composition/CompositionManager.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/PlatformService.cs
Backport of #5327.
/cc @Therzok
> [release-7.6] Surface lazy methods for CompositionManager

- main/src/addins/WindowsPlatform/WindowsPlatform/WindowsPlatform.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/ViewCommands.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DefaultWorkbench.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs
Fix glitches on Windows where the window would resize immediately after startup. Also cleans up some dead code.
> Fix window launch glitch

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputTreeCellView.cs
Backport of #5241.
/cc @slluis
> [release-7.6] [StructuredOutput] Makes Navigation link trimmed

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Features/GotoDefinition/GotoDefinitionService.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Navigation/Counters.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Navigation/FindDerivedSymbolsHandler.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Navigation/FindExtensionMethodsHandler.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Navigation/FindImplementingMembersHandler.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Navigation/FindMemberOverloadsHandler.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Refactoring/FindReferencesHandler.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Refactoring/GotoBaseDeclarationHandler.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/BackgroundPackageActionRunnerTests.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/TestableInstrumentationService.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageManagementInstrumentationService.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/RefactoringService.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextEditorKeyPressTimings.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/Counters.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/Repository.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Instrumentation/Counter.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Instrumentation/TimeCounter.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Instrumentation/TimerCounter.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectService.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionItem.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/CompletionStatistics.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/MicrosoftTemplateEngineProjectTemplatingProvider.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/ProjectTemplate.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Ide.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/RootWorkspace.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Services.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Core/InstrumentationTests.cs
Fixes VSTS #633544.
Also fixes VSTS #639164.
> Properties and measures 7.6

- main/external/fsharpbinding/build.fsx
The FAKE script used to assume that all project files would specify the AssemblyName property but this is no longer the case, so derive it from the project file name when this is missing.
> Fix build script to allow for no AssemblyName in project files

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionItem.cs
This is needed so that we can figure out the success/fail rate of first-builds of Azure function projects
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/623478
> [Core] Include project capabilities in the FirstBuild telemetry

- main/src/addins/Xml/Editor/XmlExpandSelectionHandler.cs
Reduce array allocations. Belated review feedback from https://github.com/mono/monodevelop/pull/5334
> [Xml] Switch Stack to ImmutableStack

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.AnalysisCore/Gui/AnalysisOptionsPanel.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices.Options/RoslynPreferences.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.RoslynServices.Options/FullSolutionAnalysisTests.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Tests.csproj
Backport of #5324.
/cc @Therzok
> [release-7.6] [Roslyn] Disable ClosedFileDiagnostic for C# by default

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputWidget.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/MSBuildOutputProcessor.cs
Backport of #5362.
/cc @rodrmoya
> [release-7.6] Several build output fixes

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Gui/DotNetCoreRuntimeOptionsPanelWidget.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Commands/RestorePackagesInProjectHandler.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/ProjectTargetFrameworkMonitorTests.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageManagementServices.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/ProjectTargetFrameworkChangedEventArgs.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/ProjectTargetFrameworkMonitor.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/RestoreNuGetPackagesInNuGetIntegratedProject.cs
Backport of #5378.
/cc @mrward
> [release-7.6] [DotNetCore] Fix project not restored on target framework being changed

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/RemoteBuildEngine.cs
- main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.MSBuild/BuildEngine.Shared.cs
Backport of #5379.
/cc @Therzok
> [release-7.6] [Core] Make Disconnected event handler actually waited for 

- main/src/addins/MonoDevelop.SourceEditor2/VSEditor/TextSelection.cs
> Implement ITextSelection.VirtualSelectedSpans

- main/src/addins/MonoDevelop.SourceEditor2/VSEditor/TextSelection.cs
> [release-7.6] Implement ITextSelection.VirtualSelectedSpans

- main/src/addins/MonoDevelop.WebReferences/MonoDevelop.WebReferences.csproj
- main/src/addins/MonoDevelop.WebReferences/MonoDevelop.WebReferences/WebReferencesProjectExtension.cs
- main/src/addins/MonoDevelop.WebReferences/MonoDevelop.WebReferences/WebReferencesService.cs
Backport of #5366.
/cc @Therzok
> [release-7.6] Fixes issue #4377 WebReference addin slows down folder building

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
> Fixes issue #5390 Editor shouldn't render whitespace marks for virtual

- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Actions/MiscActions.cs
- main/src/core/MonoDevelop.TextEditor.Tests/Mono.TextEditor.Tests/VirtualIndentModeTests.cs
> Fixes issue #5279 Text Editor outdents to hard left instead of going

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputTreeCellView.cs
Fixes padding in row icons and text
Fixes Bug #636706
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/636706
> [StructuredBuild] Fixes padding in row icons and text

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputTreeCellView.cs
Backport of #5416.
/cc @netonjm
> [release-7.6] [StructuredBuild] Fixes padding in row icons and text

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Tasks/CommentTasksProvider.cs
Backport of #5349.
/cc @Therzok
> [release-7.6] [CommentTasks] Prevent possible error when removing a document

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProjectConfiguration.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/ProjectTests.cs
Backport of #5421.
/cc @mrward
> [release-7.6] [Core] Refresh type system when configuration mapping changes

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputNode.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputTreeCellView.cs
Backport of #5196.
/cc @slluis
> [release-7.6] [StructuredOutput] Fixes rounding rendering duration time

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
This should fix the IDE being locked up after an authentication error happens
Fixes VSTS #641132 - [Feedback] Visual Studio Mac checkout functionality freezes entire program
Fixes VSTS #619788 - Error when cloning new Git repository locks IDE main menu
cc @mrward about https://github.com/mono/monodevelop/issues/4862
> [Git] Don't trigger the authentication exception error on the UI thread

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/Tag.cs
Backport of #5437.
/cc @Therzok
> [release-7.6] [TODO] Fix todo comments not showing up in some cases

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputTreeCellView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputWidget.cs
Backport of #5428.
/cc @slluis
> [release-7.6] [StructuredOutput] Fixes select last character in node title

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
Backport of #5439.
/cc @slluis
> [release-7.6] [Git] Don\u0027t trigger the authentication exception error on the UI thread

- main/src/addins/MonoDevelop.SourceEditor2/VSEditor/TagBasedSyntaxHighlighting.cs
I used `userScope` before because thats RoslynSyntaxHighligher(what we used for coloring C# code had), having `Foregroud` as default makes much more sense imo...
> Fix #5427: Unclassified spans in editor default to `entity.name.class`

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/CheckoutCommand.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlService.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlTask.cs
Backport of #5447.
/cc @Therzok
> [release-7.6] [VCS] Fixup more UI thread semantics and make Wakeup use the UI context

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectExtension.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionItem.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionItemExtension.cs
7.6 backport of https://github.com/mono/monodevelop/pull/5347
> [7.6] [Telemetry] Add solution extension for fetching platform-specific metadata

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/ExtensibleTextEditor.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Actions/SelectionActions.cs
Backport of #5407.
/cc @slluis
> [release-7.6] [Editor] Ensure preedit committed before all selections actions

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/650989
A puerely visual bug.
> Fixes VSTS Bug 650989: Tab size in editor wrong.

- main/src/addins/MonoDevelop.Packaging/MonoDevelop.Packaging.Templating/PackagingProjectTemplateWizard.cs
- main/src/addins/MonoDevelop.Packaging/MonoDevelop.Packaging.Tests/MonoDevelop.Packaging.Tests.csproj
- main/src/addins/MonoDevelop.Packaging/MonoDevelop.Packaging.Tests/MonoDevelop.Packaging.Tests/AddPlatformImplementationTests.cs
- main/src/addins/MonoDevelop.Packaging/MonoDevelop.Packaging.Tests/MonoDevelop.Packaging.Tests/ProjectTemplateTests.cs
- main/src/addins/MonoDevelop.Packaging/MonoDevelop.Packaging.Tests/MonoDevelop.Packaging.Tests/TestablePackagingProjectTemplateWizard.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProjectService.cs
Backport of #5459.
/cc @mrward
> [release-7.6] [Core] Fix NuGet packaging project not creating .nupkg

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutput.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputTreeCellView.cs
Includes in the overall line the total minutes expended to complete the build
Fixes Bug #636829
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/636829
> [StructuredOutput] Adds overall time to the renderer

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutput.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputTreeCellView.cs
Backport of #5419.
/cc @rodrmoya
> [release-7.6] [StructuredOutput] Adds overall time to the renderer

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.QuickTasks/QuickTaskStrip.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.addin.xml
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/652917
In former versions it used to be a 3 state - but doesn't make sense
anymore.
> Fixes VSTS Bug 652917: Minimap cannot be turned off

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CompletionProvider/RegexCompletionProvider.cs
That doesn't really fix the issue - it's a roslyn one but at least the
completion list appears. It was an invalid context (checked now by
objectCreation.ArgumentList.OpenParenToken.IsMissing).
> Fixes issue #5479 Crash in regex completion provider

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildEvaluationContext.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/ProjectTests.cs
- main/tests/test-projects/msbuild-tests/msbuildruntimeversion.csproj
Backport of #5481.
/cc @mrward
> [release-7.6] [Core] Define MSBuildRuntimeVersion when evaluating project

- main/src/core/MonoDevelop.Core/MonoDevelop.Core/FileService.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Core/FileServiceTests.cs
Backport of #5491.
/cc @Therzok
> [release-7.6] Resolve paths with double slashes

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/ProjectReevaluationTests.cs
Backport of #5497.
/cc @mrward
> [release-7.6] [Core] Fix project run configurations not used when running solution

- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/TemplateTests.fs
- main/src/addins/MonoDevelop.Packaging/MonoDevelop.Packaging.Tests/MonoDevelop.Packaging.Tests/AddPlatformImplementationTests.cs
- main/src/addins/MonoDevelop.Packaging/MonoDevelop.Packaging.Tests/MonoDevelop.Packaging.Tests/ProjectTemplateTests.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/ISolutionItemDescriptor.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/ProjectDescriptor.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/ProjectTemplate.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/ProjectTemplatingProvider.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/SingleFileDescriptionTemplate.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/SolutionDescriptor.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/SolutionItemDescriptor.cs
- main/tests/Ide.Tests/ProjectTemplateTests.cs
Backport of #5507.
/cc @mrward
> [release-7.6] [Ide] Fix no files added to new project 

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads/ErrorListPad.cs
Backport of #5502.
/cc @rodrmoya
> [release-7.6] [Ide] Hide/Show build log on startup based on settings

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/ProjectTemplate.cs
Backport of #5529.
/cc @mrward
> [release-7.6] [Ide] Fix null ref logged by telemetry when creating NuGet project

- main/src/addins/PerformanceDiagnostics/PerformanceDiagnostics/UIThreadMonitor.cs
Backport of #5531.
/cc @mrward
> [release-7.6] [PerformanceDiagnostics] Fix UI thread hang app not starting

- main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.Tests/MonoDevelop.UnitTesting.Tests.csproj
- main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.Tests/MonoDevelop.UnitTesting.Tests/TestResultBuilderTests.cs
- main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.Tests/MonoDevelop.UnitTesting.Tests/UnitTestGroupTests.cs
- main/src/addins/MonoDevelop.UnitTesting/Services/TestContext.cs
- main/src/addins/MonoDevelop.UnitTesting/Services/UnitTest.cs
- main/src/addins/MonoDevelop.UnitTesting/Services/UnitTestGroup.cs
- main/src/addins/MonoDevelop.UnitTesting/Services/UnitTestResult.cs
- main/src/addins/MonoDevelop.UnitTesting/Services/UnitTestService.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/635510
> Improve unit testing test suite finish performance

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/MdTextViewLineCollection.MdTextViewLine.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/MdTextViewLineCollection.cs
> [release-7.6] Fix VSTS 656752 (Classification doesn\u0027t update)

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/SdiWorkspaceWindow.cs
Backport of #5571.
/cc @mrward
> [release-7.6] [Ide] Fix autosave not loading autosaved file

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbarController.cs
> [release-7.6] Fix Windows build.

- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/CaretImpl.ITextCaret.cs
> [release-7.6] Fix VSTS 645707: HTML tag smart indent doesn\u0027t work with Tabs

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpParser.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/TypeSignatureHelp.fs
Backport of #5550.
/cc @nosami
> [release-7.6] Limit the number of placeholder type signature markers

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutput.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputViewContent.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputWidget.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/Counters.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/MSBuildOutputProcessor.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads/ErrorListPad.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
Backport of https://github.com/mono/monodevelop/pull/4961
> [BuildOutput] Add basic usage telemetry

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpParser.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/TypeSignatureHelp.fs
Backport of #5550.
/cc @nosami
> [release-7.7] Limit the number of placeholder type signature markers

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/MdTextViewLineCollection.MdTextViewLine.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/MdTextViewLineCollection.cs
> [release-7.7] Fix VSTS 656752 (Classification doesn\u0027t update)

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/SdiWorkspaceWindow.cs
Backport of #5571.
/cc @mrward
> [release-7.7] [Ide] Fix autosave not loading autosaved file

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/MdTextViewLineCollection.MdTextViewLine.cs
Behavior on mac/linux seems to differ a bit.
> Fixes issue #4110 Inconvenient behavior of Ctrl+Right and Ctrl+Left

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/IEditorThemeProvider.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/SyntaxHighlightingService.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/656191
> Fixes VSTS Bug 656191: Invalid text editor theme can crash the IDE

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/IEditorThemeProvider.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/SyntaxHighlightingService.cs
Backport of #5598.
/cc @Therzok
> [release-7.6] Fixes VSTS Bug 656191: Invalid text editor theme can crash the IDE

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/IEditorThemeProvider.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/SyntaxHighlightingService.cs
Backport of #5598.
/cc @Therzok
> [release-7.7] Fixes VSTS Bug 656191: Invalid text editor theme can crash the IDE

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads/ErrorListPad.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/641608
> [Ide] Clear BuildOutput when clean operations start

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads/ErrorListPad.cs
Backport of #5609.
/cc @Therzok
> [release-7.6] [Ide] Clear BuildOutput when clean operations start

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads/ErrorListPad.cs
Backport of #5609.
/cc @Therzok
> [release-7.7] [Ide] Clear BuildOutput when clean operations start

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.QuickTasks/QuickTaskOverviewMode.IdleUpdater.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.QuickTasks/QuickTaskOverviewMode.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.QuickTasks/QuickTaskStrip.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorWidget.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/643116
> Fixes issue #4996 Show breakpoints and caret location in scrollbar

- main/tests/Makefile.am
Include the performance tests and perf tool in the deployed tests so we can run them in CI.
> Tests: Include perf tests in tests bundle.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
When multiple events are frozen inside the FileService event queue,
multiple removals in the queue might trigger multiple updates,
and raced on one of them removing from the reference list
and then applying bad changes.
Although we're triggering updates multiple times now,
we fixed the race by locking on the same lock for updating
this data.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/657372
> [Ide] Fix metadatareferencecache race

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
Backport of #5616.
/cc @Therzok
> [release-7.7] [Ide] Fix metadatareferencecache race

- main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.MSBuild/ProjectBuilder.cs
Mirror of https://github.com/Microsoft/msbuild/pull/3584/files
> [MSBuild] Ignore comments when reading MSBuild files

- main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.MSBuild/ProjectBuilder.cs
Backport of #5638.
/cc @Therzok
> [release-7.7] [MSBuild] Ignore comments when reading MSBuild files

- main/src/core/MonoDevelop.Ide/Gui/MonoDevelop.Ide.Gui.OptionPanels.BuildPanelWidget.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.OptionPanels/BuildPanel.cs
Backport of #5639.
/cc @sgmunn
> [release-7.7] [Ide] Add log verbosity setting back

- main/src/core/MonoDevelop.Ide/Gui/MonoDevelop.Ide.Gui.OptionPanels.BuildPanelWidget.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.OptionPanels/BuildPanel.cs
Backport of #5639.
/cc @sgmunn
> [release-7.6] [Ide] Add log verbosity setting back

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/ErrorHandlerTextEditorExtension.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.TextMate/TextMateIndentationTextEditorExtension.cs
TextMateIndentationTextEditorExtension.cs:58 (KeyPress)
> Fixes issue #5640 NullReferenceException in

- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/DefaultIndentationTracker.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/TextEditorData.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/IndentationTracker.cs
Backport of #5645.
/cc @mkrueger
> [release-7.6] Fixes issue #5533 Unable to type space characters into an xml file

- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/DefaultIndentationTracker.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/TextEditorData.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/IndentationTracker.cs
Backport of #5645.
/cc @sgmunn
> [release-7.7] Fixes issue #5533 Unable to type space characters into an xml file

- main/external/fsharpbinding/MonoDevelop.FSharp.Gui/MonoDevelop.FSharp.Gui.csproj
- main/external/fsharpbinding/MonoDevelop.FSharp.Shared/MonoDevelop.FSharp.Shared.fsproj
- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/MonoDevelop.FSharp.Tests.fsproj
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/MonoDevelop.FSharp.fsproj
- main/external/fsharpbinding/MonoDevelop.FSharpi.Service/MonoDevelop.FSharpInteractive.Service.fsproj
- main/msbuild/MonoDevelop.AfterCommon.props
- main/msbuild/MonoDevelop.BeforeCommon.targets
Improves consistency in release/debug settings across projects.
> Clean up F# MSBuild props

- main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/RoslynCompletionPresenterSession.View.cs
Avoid a crash caused by repositioning the completion window while it's being repainted.
> Fix VSTS 662457.

- main/src/addins/CSharpBinding/CSharpBinding.csproj
- main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/ExtensionMethods.cs
- main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/MonoDevelopContainedDocument.cs
- main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/RoslynCompletionPresenterSession.View.cs
Backport of #5682.
/cc @slluis
> [master] Temp workaround for VSTS 662639.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Ide.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
This reverts commit 74477489ef87a0d7fd3dca1605e6b304a576ef71.
> Revert "[Ide] Don't show welcome page when opening a specific item"

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CompletionProvider/RegexCompletionProvider.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Rename/RenameItemDialog.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Rename/RenameRefactoring.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/HighlightUrlExtension.cs
Fixes issue #5666 Exception in RegexCompletionProvider 
Fixes issue #5665 NullRef in HighlightUrlExtension
Fixes issue #5660 NullRef in Roslyn
> Fixes several null reference exceptions.

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CompletionProvider/DelegateCompletionProvider.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/665111
Not sure why that happens but the line guards now against null
indentation tracker. Note: A good example of why it is bad to have too
many method calls in one line :).
> Fixes VSTS Bug 665111: Roslyn/editor failures

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandHandler.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Ide.cs
These force load the addin, so log these to track in the future
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/643441
> [Ide] Log addin startup handlers

- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/SupportedFramework.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/TargetFramework.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.OptionPanels/PortableRuntimeSelectorDialog.cs
Backport of #5738.
/cc @slluis
> [release-7.6] [Ide] Fix crash on trying to change PCL profile in project options

- main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/RoslynCompletionPresenterSession.View.cs
Our theory is that when the async method returned it was checking the wrong cancellation token - there may be multiple async operations in flight, but only one cancellation token. So if we cancel one cancellation token, but another operation comes back, it would create a new Window.
I've refactored the code to ensure that only one window can be open at a time.
> Fix VSTS 645709: Completion description tooltip sometimes stays open

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CSharpCompletionTextEditorExtension.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/669434
With the provided information it's not possible to see what's going
on.
But I reviewed that method and hardened it against exceptions and
prevented some possible null reference cases.
At least the import completion no longer prevents completion from
showing up and will give better error information in case of failure.
> Fixes VSTS Bug 669434: AddImportCompletionData Throws Exception

- main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/RoslynCompletionPresenterSession.View.cs
> [release-7.6] Fix VSTS 645709: Completion description tooltip sometimes stays open

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CSharpCompletionTextEditorExtension.cs
Backport of #5748.
/cc @slluis
> [release-7.6] Fixes VSTS Bug 669434: AddImportCompletionData Throws Exception

- main/src/core/MonoDevelop.Ide/ExtensionModel/MimeTypes.addin.xml
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/SyntaxHighlighting.cs
- main/src/core/MonoDevelop.TextEditor.Tests/Mono.TextEditor.Tests/SyntaxHighlightingTests.cs
> [release-7.6] Fixes VSTS Bug 665407: TypeScript/JavaScript TextMate syntax

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/SearchResult.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/SearchResultWidget.cs
Backport of #5736.
/cc @mkrueger
> [release-7.6] Fixes VSTS Bug 650534: [Feedback] High CPU usage viewing \u0022Search in

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionItem.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/WorkspaceItem.cs
Backport of #5766.
Fixes VSTS #669419 - Exception in FileStatusTracker
/cc @mrward
> [release-7.6] [Core] Fix null reference exception in FileStatusTracker

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpTextPasteHandler.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeActionEditorExtension.cs
Backport of #5758.
/cc @slluis
> [release-7.6] Fixes vsts Bug 669030: [Feedback] VSMac 7.6 UI Blitz after pasting c#

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Tasks/CommentTasksProvider.cs
Backport of #5769.
/cc @sevoku
> [release-7.6] [Ide] Fix NRE in CommentTasksView

- main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/RoslynCompletionPresenterSession.View.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/RoslynCompletionData.cs
> Fixes issue #5661 RoslynCompletionData: Can't find item type

- main/src/addins/MonoDevelop.AspNetCore/Properties/MonoDevelop.AspNetCore.addin.xml
Backport of #5786.
/cc @mrward
> [release-7.6] [AspNetCore] Change project template order in New Project dialog

- version-checks
> Bump md-addins to f4aee57d7b72fa4be6b6d585ac90d614f20fa426

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopRuleSetManager.cs
Supression is serialized as None
Fixes VSTS #674233 - Lots of invalid value of suppress popups
> [Ide] Fix ruleset serialization

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/ProjectTests.cs
- main/tests/test-projects/expand-facades/ExpandFacadesFalse.csproj
- main/tests/test-projects/expand-facades/ExpandFacadesTest.sln
- main/tests/test-projects/expand-facades/ExpandFacadesTrue.csproj
- main/tests/test-projects/expand-facades/packages.config
Backport of #5804.
/cc @mrward
> [release-7.6] [Core] Do not add facades if ImplicitlyExpandDesignTimeFacades is false

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpTextEditorIndentation.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/MonoTextEditor.ITextView.cs
broken.
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/673555
> Fixes VSTS Bug 673555: Brace and Indent completion is all kinds of

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/SyntaxHighlightingService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/VSCodeImport/xml/syntaxes/xaml.json
Backport of #5781.
/cc @slluis
> [master] Fix 668995: [Feedback] Xaml Syntax Highlighting Has Reverted in 7.6 (2190)

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/DefaultAutoInsertBracketHandler.cs
Follow-up for issues that we've noticed in PR https://github.com/mono/monodevelop/pull/5823.
> Fix issues with default bracket handler.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/CompletionController.cs
> [master] Fix VSTS 634581 (triple """ in Json)

- version-checks
Updated reference to xamarin/md-addins@d396efb
Fixes designer https://devdiv.visualstudio.com/DevDiv/_workitems/edit/665173
> Updated reference to xamarin/md-addins@d396efb

- version-checks
Updated reference to xamarin/md-addins@23b4a1c
> Updated reference to xamarin/md-addins@23b4a1c

- version-checks
Updated reference to xamarin/md-addins@9c22754
> Updated reference to xamarin/md-addins@9c22754

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/IInfoBarHost.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/InfoBar.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DefaultWorkbench.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices/MonoDevelopInfoBarService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
The API is controlled via IdeApp.Workbench.ShowInfoBar.
Fixes VSTS #678441 - Provide public API for infobar usage
> [Ide] Create public API for infobars.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/IInfoBarHost.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/InfoBar.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DefaultWorkbench.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices/MonoDevelopInfoBarService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
Backport of #5878.
/cc @sgmunn
The API is controlled via IdeApp.Workbench.ShowInfoBar.
Fixes VSTS #678441 - Provide public API for infobar usage
> [release-7.7] [Ide] Create public API for infobars.

- main/src/core/MonoDevelop.Ide/ExtensionModel/MimeTypes.addin.xml
> [master] Fix VSTS 677075: JS triple \u0022\u0022 inserted instead of two

- main/src/core/MonoDevelop.Core/MonoDevelop.Core/Runtime.cs
- main/src/tools/mdtool/src/mdtool.cs
> [release-7.6] Fix VSTS 669803: using vstool with Razor

- main/src/core/MonoDevelop.Ide/ExtensionModel/MimeTypes.addin.xml
Backport of #5879.
/cc @slluis
> [release-7.7] Fix VSTS 677075: JS triple \u0022\u0022 inserted instead of two

- version-checks
Updated reference to xamarin/md-addins@8032e90
> Updated reference to xamarin/md-addins@8032e90

- version-checks
Updated reference to xamarin/md-addins@097e18c
> Updated reference to xamarin/md-addins@097e18c

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/SyntaxHighlightingService.cs
Mac 7.6
It contained a .json file with less than 3 lines so the JSon scanning
didn't work. Also fixed that a single loading error prevented to add a
whole bundle.
> Fixes issue #5873 Exception when using syntax highlighting in VS for

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/SyntaxHighlightingService.cs
Backport of #5897.
/cc @mkrueger
> [release-7.7] Fixes issue #5873 Exception when using syntax highlighting in VS for

- main/src/addins/MacPlatform/MainToolbar/RunButton.cs
- main/src/addins/MacPlatform/MainToolbar/SelectorView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbar.cs
Backport of #5899.
/cc @slluis
> [release-7.7] Add missing main toolbar tooltips

- main/src/addins/MacPlatform/MainToolbar/MainToolbar.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/SearchPackagesSearchCategory.cs
- main/src/addins/WindowsPlatform/WindowsPlatform/MainToolbar/WPFToolbar.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/IMainToolbarView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbar.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbarController.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/RoslynSearchCategory.DeclaredSymbolInfoResult.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/SearchInSolutionSearchCategory.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/SearchPopupWindow.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/SearchResult.cs
Backport of #5882.
/cc @slluis
> [release-7.7] Fixes VSTS Bug 648998: Accessibility: VoiceOver: MAS4.1.1: VoiceOver

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.UI.cs
Backport of #5895.
/cc @sevoku
> [release-7.7] [Ide][a11y] Fix Cancel button label in new project dialog

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.OptionProvider/CSharpDocumentOptionsProvider.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding.Tests.csproj
- main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding/CSharpDocumentOptionsProviderTests.cs
> Fixes issue #5925 Format document does not use the formatting

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.OptionProvider/CSharpDocumentOptionsProvider.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding.Tests.csproj
- main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding/CSharpDocumentOptionsProviderTests.cs
Backport of #5954.
/cc @mkrueger
> [release-7.7] Fixes issue #5925 Format document does not use the formatting

- main/src/addins/MacPlatform/MacInterop/Keychain.cs
- main/tests/MacPlatform.Tests/KeychainTests.cs
Backport of #5410.
/cc @Therzok
> [release-7.7] Append zero byte to URL path to find username and password in Keychain

- main/build/MacOSX/monostub-utils.h
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitVersionControl.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/Repository.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlService.cs
Backport of #5948.
/cc @Therzok
> [release-7.7] [VCS] Improve counter infrastructure and logic behind it

- main/src/addins/MonoDevelop.Debugger/Gui/MonoDevelop.Debugger.BusyEvaluatorDialog.cs
Backport of #5962.
/cc @Therzok
> [release-7.7] #5331 Prevent Window Resize

- main/src/addins/MacPlatform/MacProxyCredentialProvider.cs
The credential provider dialog did not focus the username text field
and tabbing did not move around the text fields and buttons.
Fixes VSTS #603815 - Credential provider dialog: tabbing and initial
focus
> [MacPlatform] Fix credential provider dialog tabbing and focus

- main/src/addins/MacPlatform/MacProxyCredentialProvider.cs
Backport of #5975.
/cc @luiscubal 
Fixes VSTS #603815
> [release-7.7] [MacPlatform] Fix credential provider dialog tabbing and focus

- main/src/addins/MacPlatform/MacInterop/Keychain.cs
- main/tests/MacPlatform.Tests/KeychainTests.cs
Backport of #5410.
/cc @slluis
(Should fix VSTS #514232)
> [release-7.6] Append zero byte to URL path to find username and password in Keychain

- main/src/addins/MacPlatform/MacProxyCredentialProvider.cs
Backport of #5975.
/cc @slluis
Fixes VSTS #603815
> [release-7.6] [MacPlatform] Fix credential provider dialog tabbing and focus

- version-checks
Updated reference to xamarin/md-addins@fcea43e
> Updated reference to xamarin/md-addins@fcea43e

- version-checks
Updated reference to xamarin/md-addins@d7866c0
> Updated reference to xamarin/md-addins@d7866c0

- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/TextEditorData.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/SearchResult.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.FindInFiles/SearchResultWidgetTests.cs
Solution" / "Scrolling over search results" observing ~9 seconds delay
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/672522
Fixes VSTS Bug 682954: Search result text height differences
> Fixes VSTS Bug 672522: Need Performance improvement on "Search in

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeFormatting/AbstractCodeFormatter.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Editor/AbstractCodeFormatterTests.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Tests.csproj
Backport of #5966.
/cc @mkrueger
> [release-7.7] Fixes VSTS Bug 677780: ArgumentOutOfRange in

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeFormatting/AbstractCodeFormatter.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Editor/AbstractCodeFormatterTests.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Tests.csproj
Backport of #5966.
/cc @slluis
> [release-7.6] Fixes VSTS Bug 677780: ArgumentOutOfRange in

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.ProjectSystemHandler.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Tests.csproj
- main/tests/Ide.Tests/MonoDevelop.Ide.TypeSystem/TypeSystemServiceTests.cs
- main/tests/test-projects/symlinked-source-file/SymlinkedFile.cs
- main/tests/test-projects/symlinked-source-file/test-symlinked-file/.gitignore
- main/tests/test-projects/symlinked-source-file/test-symlinked-file/Program.cs
- main/tests/test-projects/symlinked-source-file/test-symlinked-file/Properties/AssemblyInfo.cs
- main/tests/test-projects/symlinked-source-file/test-symlinked-file/SymlinkedFileData.txt
- main/tests/test-projects/symlinked-source-file/test-symlinked-file/test-symlinked-file.csproj
- main/tests/test-projects/symlinked-source-file/test-symlinked-file/test-symlinked-file.sln
see individual commits
Fixes VSTS #677869 - [Feedback] VS 2017 + Unity + Mac OS high sierra (10.13.4) soft links not working
> [Ide] Fix handling of symlinks in MonoDevelop workspace

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.ProjectSystemHandler.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Tests.csproj
- main/tests/Ide.Tests/MonoDevelop.Ide.TypeSystem/TypeSystemServiceTests.cs
- main/tests/test-projects/symlinked-source-file/SymlinkedFile.cs
- main/tests/test-projects/symlinked-source-file/test-symlinked-file/.gitignore
- main/tests/test-projects/symlinked-source-file/test-symlinked-file/Program.cs
- main/tests/test-projects/symlinked-source-file/test-symlinked-file/Properties/AssemblyInfo.cs
- main/tests/test-projects/symlinked-source-file/test-symlinked-file/SymlinkedFileData.txt
- main/tests/test-projects/symlinked-source-file/test-symlinked-file/test-symlinked-file.csproj
- main/tests/test-projects/symlinked-source-file/test-symlinked-file/test-symlinked-file.sln
see individual commits
Fixes VSTS #677869 - [Feedback] VS 2017 + Unity + Mac OS high sierra (10.13.4) soft links not working
> [7.7][Ide] Fix handling of symlinks in MonoDevelop workspace

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CompletionProvider/DelegateCompletionProvider.cs
Backport of #6027.
/cc @mkrueger
> [release-7.7] Fixes issue #6021 Overload completion called on background thread

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/SearchResult.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.FindInFiles/SearchResultWidgetTests.cs
Backport of #6024.
/cc @mkrueger
> [release-7.7] Fixes issue #6015 Find references shows invalid search results.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/SearchResult.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.FindInFiles/SearchResultWidgetTests.cs
Backport of #6024.
/cc @mkrueger
> [release-7.6] Fixes issue #6015 Find references shows invalid search results.

- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/TextEditorData.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/SearchResult.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.FindInFiles/SearchResultWidgetTests.cs
Backport of #5937.
/cc @mkrueger
Fixes issue #6015 Find references shows invalid search results
> [release-7.7] Fixes VSTS Bug 672522: Need Performance improvement on \u0022Search in

- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/TextEditorData.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/SearchResult.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.FindInFiles/SearchResultWidgetTests.cs
Backport of #5937.
/cc @slluis 
Fixes issue  #6015 Find references shows invalid search results
> [release-7.6] Fixes VSTS Bug 672522: Need Performance improvement on \u0022Search in

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Tests.csproj
- main/tests/Ide.Tests/MonoDevelop.Ide.TypeSystem/TypeSystemServiceTests.cs
- main/tests/test-projects/symlinked-source-file/SymlinkedFile.cs
- main/tests/test-projects/symlinked-source-file/test-symlinked-file/.gitignore
- main/tests/test-projects/symlinked-source-file/test-symlinked-file/Program.cs
- main/tests/test-projects/symlinked-source-file/test-symlinked-file/Properties/AssemblyInfo.cs
- main/tests/test-projects/symlinked-source-file/test-symlinked-file/SymlinkedFileData.txt
- main/tests/test-projects/symlinked-source-file/test-symlinked-file/test-symlinked-file.csproj
- main/tests/test-projects/symlinked-source-file/test-symlinked-file/test-symlinked-file.sln
see individual commits
Fixes VSTS #677869 - [Feedback] VS 2017 + Unity + Mac OS high sierra (10.13.4) soft links not working
> [7.6][Ide] Fix handling of symlinks in MonoDevelop workspace

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/FindReplace.cs
> Fixes issue #5997 Error while search: OperationCanceled in

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/FindReplace.cs
Backport of #6032.
/cc @mkrueger
> [release-7.7] Fixes issue #5997 Error while search: OperationCanceled in

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ExceptionCaughtDialog.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/Styles.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Styles.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.UI.cs
- main/src/core/MonoDevelop.Ide/gtkrc.mac
- main/src/core/MonoDevelop.Ide/gtkrc.mac-dark
- main/src/core/MonoDevelop.Ide/gtkrc.win32
- main/src/core/MonoDevelop.Ide/gtkrc.win32-dark
Several a11y color contrast fixes to the IDE and Exception Caught Dialog.
> Accessibility: Color Contrast Fixes

- main/src/addins/MonoDevelop.Packaging/MonoDevelop.Packaging.Tests/MonoDevelop.Packaging.Tests/ProjectTemplateTests.cs
> [master] Disable failing test: CreateMultiPlatformProjectFromTemplateWithPCLOnly

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
See related: https://github.com/mono/monodevelop/pull/6050
> Don't deploy Gtk binaries to output.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/LogView.cs
Backport of #6047.
/cc @Therzok
> [release-7.7] [Output Pad] Fix nothing being written and monitors not being reused

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ExceptionCaughtDialog.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/Styles.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Styles.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.UI.cs
- main/src/core/MonoDevelop.Ide/gtkrc.mac
- main/src/core/MonoDevelop.Ide/gtkrc.mac-dark
- main/src/core/MonoDevelop.Ide/gtkrc.win32
- main/src/core/MonoDevelop.Ide/gtkrc.win32-dark
Backport of #6034.
/cc @slluis
> [Fixes VSTS #648200](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/648200)
> [Fixes VSTS #648202](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/648202)
> [Fixes VSTS #648203](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/648203)
> [Fixes VSTS #648205](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/648205)
> [Fixes VSTS #648207](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/648207)
> [release-7.7] Accessibility: Color Contrast Fixes

- main/src/addins/MacPlatform/Dialogs/MacAlertDialogHandler.cs
- main/src/addins/MacPlatform/Dialogs/MacCommonFileDialogHandler.cs
- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/addins/MacPlatform/MainToolbar/RunButton.cs
- main/src/addins/MacPlatform/MainToolbar/StatusBar.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/IdeTheme.cs
Fixes VSTS #682823
Fixes VSTS #677025
Fixes VSTS #676679
> [Ide] Dark theme support fixes for Mojave

- main/src/addins/MacPlatform/Dialogs/MacAlertDialogHandler.cs
- main/src/addins/MacPlatform/Dialogs/MacCommonFileDialogHandler.cs
- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/addins/MacPlatform/MainToolbar/RunButton.cs
- main/src/addins/MacPlatform/MainToolbar/StatusBar.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/IdeTheme.cs
Backport of #5943.
Fixes VSTS #682823
Fixes VSTS #677025
Fixes VSTS #676679
/cc @sevoku
> [release-7.7] [Ide] Dark theme support fixes for Mojave

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.PickMembersService/PickMembersDialog.cs
Backport of #5604.
/cc @Therzok
> [release-7.6] Fixes VSTS Bug 659996: [Feedback] VS Mac 2017 - Pick members to

- main/src/addins/MacPlatform/Dialogs/MacAlertDialogHandler.cs
- main/src/addins/MacPlatform/Dialogs/MacCommonFileDialogHandler.cs
- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/addins/MacPlatform/MainToolbar/RunButton.cs
- main/src/addins/MacPlatform/MainToolbar/StatusBar.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/IdeTheme.cs
Backport of #5943.
Fixes VSTS #682823
Fixes VSTS #677025
Fixes VSTS #676679
/cc @sevoku
> [release-7.6] [Ide] Dark theme support fixes for Mojave

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/OblivionStyle.json
Backport of #6036.
/cc @mkrueger
> [release-7.7] Fixes #6035 Fix oblivion color style

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CompletionProvider/DelegateCompletionProvider.cs
Backport of #5970.
/cc @slluis
> [release-7.7] Fixes issue #5813 Editor IntelliSense/Code Generation Bugs.

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpTextEditorIndentation.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding/CSharpTextEditorIndentationTests.cs
Backport of #5957.
/cc @mkrueger
> [release-7.7] Fixes issue #5951 Indentation after end of method

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Services.cs
Backport of #5902.
/cc @slluis
> [release-7.7] [Ide] Track unhandled exceptions

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CSharpCompletionTextEditorExtension.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding/CSharpCompletionTextEditorTests.cs
Backport of #5980.
/cc @slluis
> [release-7.7] Fixes issue #5816 Completion Suggestion Mode doesn\u0027t work as expected

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CSharpCompletionTextEditorExtension.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding/CSharpCompletionTextEditorTests.cs
in collection initializers
> [Fixes GitHub #5816](https://github.com/mono/monodevelop/issues/5816)
> Fixes issue #5816 Completion Suggestion Mode doesn't work as expected

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/ExtensibleTextEditor.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeTemplates/ExpansionObject.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Editor/CodeSnippetTests.cs
the editor
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/685153
> [Fixes VSTS #685153](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/685153)
> Fixes VSTS Bug 685153: Some C# templates do not work when invoked in

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpFormattingProfileDialog.cs
Backport of #6083.
/cc @mkrueger
> [release-7.7] Fixes VSTS Bug 690182: [Feedback] sorting usings dosen\u0027t work on vs

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/ExtensibleTextEditor.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeTemplates/ExpansionObject.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Editor/CodeSnippetTests.cs
Backport of #5983.
/cc @mkrueger
> [release-7.7] Fixes VSTS Bug 685153: Some C# templates do not work when invoked in

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs
Backport of #6064.
/cc @slluis
> [release-7.7] Fix VSTS 674288.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Services.cs
Backport of #5902.
/cc @slluis
> [release-7.6] [Ide] Track unhandled exceptions

- main/src/core/MonoDevelop.Startup/app.config
Backport of #6094.
/cc @Therzok
> [release-7.7] Fix binding redirect.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/EditorConfigService.cs
It's a similiar issue than the original one.
> Fixes issue #5790 ArgumentNullException in EditorConfigCache

- main/src/addins/MacPlatform/Interop.cs
- main/src/addins/MacPlatform/KernelInterop.cs
- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/addins/MacPlatform/MacPlatform.csproj
- main/src/addins/MacPlatform/MacTelemetryDetails.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/DesktopService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/PlatformMemoryStatusEventArgs.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Services.cs
Backport of #6070.
/cc @Therzok
> [Fixes  VSTS #633545](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/633545)
> [release-7.6] [Ide] Report virtual memory statistics on OS pressure event

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextEditorKeyPressTimings.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Instrumentation/BucketTimings.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/CompletionStatistics.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Core.Instrumentation/BucketTimingsTests.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Core.Tests.csproj
Fixes VSTS #675547 - Bucketize intellisense telemetry
> [Completion] Add bucketing to timing events

- main/src/addins/MacPlatform/Interop.cs
- main/src/addins/MacPlatform/KernelInterop.cs
- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/addins/MacPlatform/MacPlatform.csproj
- main/src/addins/MacPlatform/MacTelemetryDetails.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/DesktopService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/PlatformMemoryStatusEventArgs.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Services.cs
Backport of #6070.
/cc @Therzok
> [Fixes  VSTS #633545](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/633545)
> [release-7.7] [Ide] Report virtual memory statistics on OS pressure event

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/EditorConfigService.cs
Backport of #6099.
/cc @mkrueger
> [release-7.7] Fixes issue #5790 ArgumentNullException in EditorConfigCache

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/FileWatcherService.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/FileWatcherTests.cs
Backport of #6110.
/cc @mrward
> [Fixes  VSTS #692174](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/692174)
> [release-7.6] [Core] Fix file not reloaded when changed externally

- main/src/addins/MonoDevelop.AspNetCore/Properties/MonoDevelop.AspNetCore.addin.xml
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Templating/DotNetCoreProjectTemplateStringTagProvider.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Templating/DotNetCoreProjectTemplateWizard.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Templating/DotNetCoreProjectTemplateWizardPage.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectSupportedTargetFrameworksTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateStringTagProviderTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateWizardTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreNotInstalledDialog.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectSupportedTargetFrameworks.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdkInstalledCondition.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/TargetFrameworkExtensions.cs
- main/src/addins/MonoDevelop.DotNetCore/Properties/MonoDevelop.DotNetCore.addin.xml
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/677546
> [DotNetCore] Add support for .NET Core 2.2

- main/src/addins/MonoDevelop.AspNetCore/Properties/MonoDevelop.AspNetCore.addin.xml
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Templating/DotNetCoreProjectTemplateStringTagProvider.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Templating/DotNetCoreProjectTemplateWizard.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Templating/DotNetCoreProjectTemplateWizardPage.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectSupportedTargetFrameworksTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateStringTagProviderTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateWizardTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreNotInstalledDialog.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectSupportedTargetFrameworks.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdkInstalledCondition.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/TargetFrameworkExtensions.cs
- main/src/addins/MonoDevelop.DotNetCore/Properties/MonoDevelop.DotNetCore.addin.xml
Backport of #6112.
/cc @slluis
> [Fixes  VSTS #677546](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/677546)
> [release-7.7] [DotNetCore] Add support for .NET Core 2.2

- main/src/addins/MonoDevelop.UnitTesting/Gui/TestPad.cs
- main/src/addins/MonoDevelop.UnitTesting/Services/UnitTestService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/LogView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads/DefaultMonitorPad.cs
Backport of #6116.
/cc @mkrueger
> [release-7.7] Fixes issue #6014 [Regression] Unit-tests execution

- main/src/addins/MacPlatform/MacInterop/KeyCodes.cs
- main/src/addins/MacPlatform/MacPlatform.csproj
- main/src/addins/MacPlatform/MainToolbar/MainToolbar.cs
- main/src/addins/MacPlatform/MainToolbar/RunButton.cs
- main/src/addins/MacPlatform/MainToolbar/SelectorView.cs
- main/src/addins/MacPlatform/MainToolbar/StatusBar.cs
- main/src/addins/WindowsPlatform/WindowsPlatform/MainToolbar/WPFToolbar.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/IMainToolbarView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbar.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DefaultWorkbench.cs
Backport of #6076.
/cc @iainx
> [Fixes  VSTS #648190](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/648190)
> [release-7.7] Improve shift-tab experience in the toolbar

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/StartupInfo.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Ide.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdePreferences.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
- main/src/core/MonoDevelop.Ide/options/MonoDevelopProperties.xml
Backport of #6051.
/cc @iainx
> [Fixes  VSTS #678313](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/678313)
> [release-7.7] [Telemetry] Add the correct StartupType values for the startup event

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
> [Telemetry] Fix null reference when opening solutions from finder

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
Backport of #6134.
/cc @iainx
> [Fixes  VSTS #692948](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/692948)
> [release-7.7] [Telemetry] Fix null reference when opening solutions from finder

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpPathExtension.fs
> Fix NRE when getting ConfigurationSelector

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpPathExtension.fs
Backport of #6159.
/cc @nosami @nosami
Description of #6159:
fixes VSTS #694965
> [release-7.7] Fix NRE when getting ConfigurationSelector

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CompletionProvider/DelegateCompletionProvider.cs
+= if corresponding method has been changed causes code generation to
fire again
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/693143
There is a code refactoring querying the code changes from the
completion items in that case. This shouldn't trigger the insert mode.
> Fixes VSTS Bug 693143: Reentering handler after code generation from

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpProjectFileNodeExtension.fs
Backport of #6169.
/cc @nosami @nosami
Description of #6169:
Also check that drag node is not the same as drop node.
Fixes VSTS #694596
> [release-7.7] [F#] Fix CanDropNode so that it only works within F# projects

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpPathExtension.fs
Re: VSTS #694766
> [Related:  VSTS #694965](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/694965)
> Guard against project parent solution being null.

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpPathExtension.fs
Backport of #6173.
/cc @nosami @nosami
Description of #6173:
Re: VSTS #694766
> [release-7.7] Guard against project parent solution being null.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.UI.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.cs
So that Voiceover announces the relation between categories and
subcategories.
Fixes VSTS #648743
> Display project subcategories as children of categories

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectSupportedTargetFrameworksTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateWizardTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreSdkInstalledConditionTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.csproj
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectSupportedTargetFrameworks.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdk.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdkInstalledCondition.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/MonoRuntimeInfoExtensions.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/694494
> [DotNetCore] Support .NETStandard 2.0 when new enough Mono is installed

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.UI.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.cs
So that VoiceOver can understand the hierarchy
Fixes VSTS #648978
> Render templates as children of categories

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.UI.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.cs
Backport of #6188.
/cc @slluis @nosami
Description:
So that VoiceOver can understand the hierarchy
Fixes VSTS #648978
> [release-7.7] Render templates as children of categories

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Services.cs
Include Time to code event if a file is opened as well
Fixes VSTS #684796
> [Telemetry] Time to Code for file open

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CompletionProvider/DelegateCompletionProvider.cs
Backport of #6155.
/cc @mkrueger @mkrueger
Description of #6155:
+= if corresponding method has been changed causes code generation to
fire again
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/693143
There is a code refactoring querying the code changes from the
completion items in that case. This shouldn't trigger the insert mode.
> [release-7.7] Fixes VSTS Bug 693143: Reentering handler after code generation from

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextEditorKeyPressTimings.cs
- main/src/core/MonoDevelop.TextEditor.Tests/Mono.TextEditor.Tests/TextEditorKeyPressTimingsTests.cs
To help pin down possible slowdowns in the editor
Fixes VSTS 675548 - Research typing delays
> [Editor] Add counter information and various data points

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.PreviewVisualizers/PreviewVisualizerWindow.cs
on Debug Preview Visualizer Window. Fixes #648992
> Add accessibility attributes to close button

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.PreviewVisualizers/PreviewVisualizerWindow.cs
Backport of #6213.
/cc @nosami 
Description:
on Debug Preview Visualizer Window. Fixes #648992
> [release-7.7] Add accessibility attributes to close button

- main/src/addins/MonoDevelop.HexEditor/Mono.MHex/HexEditorDebugger.cs
> [A11y] Set the accessibility attributes of the group width combobox

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/FoldMarkerMargin.cs
This should improve typing performance in big files
Fixes vsts #620363
> [Accessibility] Update the accessibility folds on a 5second timer

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextEditorKeyPressTimings.cs
- main/src/core/MonoDevelop.TextEditor.Tests/Mono.TextEditor.Tests/TextEditorKeyPressTimingsTests.cs
Backport of #6137.
/cc @Therzok 
Description:
To help pin down possible slowdowns in the editor
Fixes VSTS 675548 - Research typing delays
> [release-7.6] [Editor] Add counter information and various data points

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextEditorKeyPressTimings.cs
- main/src/core/MonoDevelop.TextEditor.Tests/Mono.TextEditor.Tests/TextEditorKeyPressTimingsTests.cs
Backport of #6137.
/cc @Therzok 
Description:
To help pin down possible slowdowns in the editor
Fixes VSTS 675548 - Research typing delays
> [release-7.7] [Editor] Add counter information and various data points

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
> [Ide] Fix some odd grammar in a dialog box

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
Backport of #6262.
/cc @iainx 
Description:
Just fixes some weird grammar
> [release-7.7] [Ide] Fix some odd grammar in a dialog box

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeTemplates/MonoDevelop-templates.xml
VSWindows
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/699559
> Fixes VSTS Bug 699559: Update C# prop snippet to be consistent with

- main/src/addins/MonoDevelop.UnitTesting/Services/UnitTestService.cs
> Fixes issue #6147 Build project before executing unit tests now

- main/src/addins/MonoDevelop.UnitTesting/Services/UnitTestService.cs
Backport of #6274.
/cc @mkrueger 
Description:
prompts
> [release-7.7] Fixes issue #6147 Build project before executing unit tests now

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeActionEditorExtension.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeFixMenuService.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/FixAllPreviewDialog.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.csproj
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Styles.cs
Backport of #6006.
Description:
Current issues:
* IDEXXXX fixes do not work, not sure why, will have to investigate
* There's a minor length check issue when a code fix changes the line count
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/677579
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/645577
> [Fixes  VSTS #698134](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/698134)
> [release-7.7] FixAll dialog implementation

- main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.Tests/MonoDevelop.UnitTesting.Tests/VsTestUnitTestTests.cs
- main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.VsTest/VsTestNamespaceTestGroup.cs
- main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.VsTest/VsTestUnitTest.cs
application, the application will crash with a stack trace that seems
to try to recursively add unit test over 85,000 times
https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/701330
> Fixes VSTS Bug 701330: DTS: When adding Unit Test into the

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CSharpCompletionTextEditorExtension.IDebuggerExpressionResolver.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/NR5CompatibiltyExtensions.cs
NR5CompatibiltyExtensions.GetFullName
> Fixes issue #6281 NullReferenceException calling

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CSharpCompletionTextEditorExtension.IDebuggerExpressionResolver.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/NR5CompatibiltyExtensions.cs
Backport of #6291.
/cc @mkrueger 
Description:
NR5CompatibiltyExtensions.GetFullName
> [release-7.7] Fixes issue #6281 NullReferenceException calling

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CSharpCompletionTextEditorExtension.IDebuggerExpressionResolver.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/NR5CompatibiltyExtensions.cs
Backport of #6291.
Description:
NR5CompatibiltyExtensions.GetFullName
> [release-7.6] Fixes issue #6281 NullReferenceException calling

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.UI.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.cs
> Allow template selection to work with tree

- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/TemplateTests.fs
Related PRs:
https://github.com/xamarin/md-addins/pull/3633
https://github.com/xamarin/md-addins/pull/3703
> VSTS 691307: disable F# forms app tests

- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/TemplateTests.fs
Backport of #6279.
/cc @olegoid 
Description:
Related PRs:
https://github.com/xamarin/md-addins/pull/3633
https://github.com/xamarin/md-addins/pull/3703
> [release-7.7] VSTS 691307: disable F# forms app tests

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.cs
> Use the correct treemodel to walk

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.UI.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.cs
Backport of #6299.
/cc @slluis @nosami
Description:
Fixes VSTS #702771
> [release-7.7] Allow template selection to work with tree

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Xwt/XwtThemedPopup.cs
Requires mono/xwt#856
Fixes VSTS #690353
> [Ide][Mac] Fix Popup rendering on Mojave

- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/PlatformService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/OptionsDialog.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/DesktopService.cs
> [A11y] Don't expand the sidebar items if using full keyboard control

- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/PlatformService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/OptionsDialog.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/DesktopService.cs
Backport of #5540.
Description:
Fixes VSTS #646431
> [release-7.7] [A11y] Don\u0027t expand the sidebar items if using full keyboard control

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextEditorKeyPressTimings.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/StyledSourceEditorOptions.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/CommonTextEditorOptions.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/ITextEditorOptions.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/TextEditorOptions.cs
keeps being reset in 7.6
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/701970
> Fixes VSTS Bug 701970: [Feedback] "Show Invisible Characters" setting

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextEditorKeyPressTimings.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/StyledSourceEditorOptions.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/CommonTextEditorOptions.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/ITextEditorOptions.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/TextEditorOptions.cs
Backport of #6314.
Description:
keeps being reset in 7.6
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/701970
> [release-7.7] Fixes VSTS Bug 701970: [Feedback] \u0022Show Invisible Characters\u0022 setting

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/701972
Cursors get disposed on destroy. The TextViewMargin tried to share the
same cursor objects (as only margin which changes the cursor).
> Fixes VSTS Bug 701972: [Feedback] Mouse Cursor is always an arrow

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Xwt/XwtThemedPopup.cs
Backport of #6341.
/cc @mkrueger 
Description:
> [release-7.6] Fixes issue #6339 XwtThemedPopup crashes on linux

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Xwt/XwtThemedPopup.cs
Backport of #6341.
/cc @mkrueger 
Description:
> [release-7.7] Fixes issue #6339 XwtThemedPopup crashes on linux

- main/src/addins/MonoDevelop.WebReferences/MonoDevelop.WebReferences.Commands/WebReferenceCommandHandler.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/681290
> [WebReferences] Don't show "Add web reference" for .NET Core projects

- main/src/addins/MonoDevelop.DotNetCore/Properties/MonoDevelop.DotNetCore.addin.xml
Fixes VSTS #583077 - Possible copy paste error in dotnet core options panels
> [DotNetCore] Fix copy paste error in options panel

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/BlockStructureFoldingTextEditorExtension.cs
Move the block structure computation off the UI thread and only trigger the actual UI
update there.
Should fix some choppiness related to typing.
Fixes VSTS #700199 - BlockStructureFoldingTextEditorExtension is running on UI thread
> [Ide] Optimize BlockStructureFolding by making it not run on the UI thread

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebugCommands.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/ProjectCommands.cs
> Papercut - specialize labels of run/debug commands

- main/src/addins/MonoDevelop.DotNetCore/Properties/MonoDevelop.DotNetCore.addin.xml
Backport of #6350.
/cc @Therzok 
Description:
Fixes VSTS #583077 - Possible copy paste error in dotnet core options panels
> [release-7.7] [DotNetCore] Fix copy paste error in options panel

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/BlockStructureFoldingTextEditorExtension.cs
Backport of #6349.
/cc @Therzok 
Description:
Move the block structure computation off the UI thread and only trigger the actual UI
update there.
Should fix some choppiness related to typing.
Fixes VSTS #700199 - BlockStructureFoldingTextEditorExtension is running on UI thread
> [release-7.7] [Ide] Optimize BlockStructureFolding by making it not run on the UI thread

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ExceptionCaughtDialog.cs
> Voiceover should read out stacktrace contents

- .editorconfig
Fixes VSTS #707438 - Add more editorconfig options to monodevelop editorconfig
> Update editorconfig for accessibility modifiers

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CSharpCompletionTextEditorExtension.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding/CSharpCompletionTextEditorTests.cs
pressed by default
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/705110
> Fixes VSTS Bug 705110: Code suggestion does wrong thing when enter is

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
- main/src/core/MonoDevelop.Ide/packages.config
Backport of #6381.
/cc @Therzok 
Description:
Fixes VSTS #632878 - Update yamldotnet nuget
> [release-7.7] Update YamlDotNet

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
- main/src/core/MonoDevelop.Ide/packages.config
- main/src/core/MonoDevelop.Startup/app.config
Fixes VSTS #632878 - Update yamldotnet nuget
> [7.6]Update YamlDotNet

- main/src/addins/Xml/Editor/BaseXmlEditorExtension.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/DocumentContext.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs
- main/tests/IdeUnitTests/TextEditorExtensionTestBase.cs
Backport of #6254.
Description:
NullReferenceException: Object reference not set to an instance of an
object
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/699450
> [release-7.6] Fixes VSTS Bug 699450: [Feedback] Error creating file -

- main/src/addins/Xml/Editor/BaseXmlEditorExtension.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/DocumentContext.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs
- main/tests/IdeUnitTests/TextEditorExtensionTestBase.cs
NullReferenceException: Object reference not set to an instance of an
object
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/699450
> Fixes VSTS Bug 699450: [Feedback] Error creating file -

- main/src/addins/Xml/Editor/BaseXmlEditorExtension.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/DocumentContext.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs
- main/tests/IdeUnitTests/TextEditorExtensionTestBase.cs
Backport of #6254.
Description:
NullReferenceException: Object reference not set to an instance of an
object
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/699450
> [release-7.7] Fixes VSTS Bug 699450: [Feedback] Error creating file -

- main/src/core/MonoDevelop.Startup/app.config
Fixes VSTS #708456 - Missing binding redirect after yamldotnet bump
> Add YamlDotNet binding redirects

- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/Cecil/EventDefinitionNodeBuilder.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/Cecil/FieldDefinitionNodeBuilder.cs
when hovering mouse over the method/ctor names
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/705313
> Fixes VSTS Bug 705313: Assembly Explorer listing changes method name

- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/Cecil/EventDefinitionNodeBuilder.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/Cecil/FieldDefinitionNodeBuilder.cs
Backport of #6390.
/cc @mkrueger 
Description:
when hovering mouse over the method/ctor names
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/705313
> [release-7.7] Fixes VSTS Bug 705313: Assembly Explorer listing changes method name

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests.csproj
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateTests.cs
- main/tests/IdeUnitTests/IdeUnitTests.csproj
- main/tests/IdeUnitTests/ProjectTemplateTest.cs
And make .NET Core tests use it, for creating projects from templates
and building them.
> [Tests] Add ProjectTemplateTest helper class

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/TextMarker/SmartTagMarginMarker.cs
Backport of #6421.
/cc @mkrueger 
Description:
> [release-7.7] Fixes issue #6414 Enabling/Disabling breakpoint opens quick fixes menu

- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/AssemblyLoader.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/DisplayBinding.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/Cecil/AssemblyNodeBuilder.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/DesktopService.cs
files) to projects - VS Mac hangs indefinitely
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/709244
> Fixes VSTS Bug 709244: [Feedback] Cannot add .bat (Windows Batch

- version-checks
Updated reference from/to: https://github.com/xamarin/md-addins/compare/8d1c27a21f016db2327c647505698c2ff91bc41b...c114276813ea8f259a34bc54b015d7bf711d402b
https://github.com/xamarin/md-addins/commit/c114276813ea8f259a34bc54b015d7bf711d402b [release-7.7] Bump xamarin/designer
> Updated reference to xamarin/md-addins@c114276

- version-checks
Updated reference to xamarin/md-addins@a3ab806
> Updated reference to xamarin/md-addins@a3ab806

- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/AssemblyLoader.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/DisplayBinding.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/Cecil/AssemblyNodeBuilder.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/DesktopService.cs
Backport of #6427.
/cc @mkrueger 
Description:
files) to projects - VS Mac hangs indefinitely
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/709244
> [release-7.7] Fixes VSTS Bug 709244: [Feedback] Cannot add .bat (Windows Batch

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
The previous wording was not grammatically correct and sounded really awkward.
> [Ide] Fixed wording of the confirm-delete dialog when removing a file

- version-checks
Updated reference to xamarin/md-addins@4eb7bc2
> [Fixes  VSTS #675520](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/675520)
> [Fixes  VSTS #675548](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/675548)
> Updated reference to xamarin/md-addins@4eb7bc2

- version-checks
Updated reference to xamarin/md-addins@cf23b11
> Updated reference to xamarin/md-addins@cf23b11

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeTemplates/MonoDevelop-templates.xml
Backport of #6263.
Description:
VSWindows
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/699559
> [release-7.7] Fixes VSTS Bug 699559: Update C# prop snippet to be consistent with

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CompletionProvider/DelegateCompletionProvider.cs
pressed after stray arrow key
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/705119
> Fixes VSTS Bug 705119: Code suggestion does wrong thing when ( is

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.UnitTests/UnitTestTextEditorExtension.cs
TestCase ()
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/713031
Enum flag datatypes make that case a bit more complex to handle.
> Fixes VSTS Bug 713031: Editor "Unit test integration" does not handle

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Commands/PublishToFolderCommandHandler.cs
- main/src/addins/MonoDevelop.AspNetCore/Properties/MonoDevelop.AspNetCore.addin.xml
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/ProjectPadContextMenu.addin.xml
- When does not support Folder Publishing then sets item to Visible = false
Fixes VSTS #715107
Fixes #6465  
Fixes #6468
> [AspNetCore] Properly disables folder publishing

- version-checks
Updated reference to xamarin/md-addins@d401369
> [Fixes  VSTS #713319](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/713319)
> [Fixes  VSTS #714217](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/714217)
> Updated reference to xamarin/md-addins@d401369

- main/src/addins/MonoDevelop.UnitTesting/Gui/TestResultsPad.cs
amounts of text are shown
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/713024
> Bug 713024: "Test Results" pane has bad performance when very large

- main/src/addins/Xml/Completion/XmlCompletionData.cs
- main/src/addins/Xml/Tests/CodeCompletion/XmlCodeCompletionTests.cs
- main/src/addins/Xml/Tests/MonoDevelop.Xml.Tests.csproj
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
- main/tests/IdeUnitTests/TestViewContent.cs
Backport of #5630.
/cc @slluis @DavidKarlas
Description:
This fixes #4969 and also adds unit test
> [release-7.7] Fix #4969

- version-checks
Updated reference to xamarin/md-addins@53e2843
> Updated reference to xamarin/md-addins@53e2843

- version-checks
Updated reference to xamarin/md-addins@44d3c4d
> Updated reference to xamarin/md-addins@44d3c4d

- version-checks
Updated reference to md-addins: https://github.com/xamarin/md-addins/compare/8061fc73aa1129d403147bb67d6ec6aa4d8ecca5...1e753b6ebc205af7752ab947a5bfcd118cd66ca3
... which in turn picks up this:
https://github.com/xamarin/md-addins/commit/1e753b6ebc205af7752ab947a5bfcd118cd66ca3 - [release-7.6] Bump xamarin/designer (#3808)
https://github.com/xamarin/md-addins/commit/bbde437e4716c14d7617d9543d48a13522ff449e - 
Merge pull request #3773 from xamarin/release-7.6-greg-customer-deplo…
https://github.com/xamarin/md-addins/commit/af8c55c12a7e250046c9ad276ab3706b45ee6606 - 
[Android] Handle NRE's when sending deployment telemetry.
> Updated reference to xamarin/md-addins@1e753b6

- version-checks
Updated reference to xamarin/md-addins@bc9b985
> Updated reference to xamarin/md-addins@bc9b985

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Commands/PublishToFolderBaseCommandHandler.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Dialogs/PublishToFolderDialog.cs
- Changes Dialog's button order
- Browse button label
- Animated icon when publishing
> [AspNetCore] Few UI fixes

- version-checks
Updated reference to xamarin/md-addins@da744b9
> Updated reference to xamarin/md-addins@da744b9

- version-checks
Updated reference to xamarin/md-addins@45486a8
> Updated reference to xamarin/md-addins@45486a8

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/LogView.cs
Backport #6533 to `release-7.7`
Fixes VSTS #705935
> [7.7][Ide] Reset LogView cookie only when cleared for reusing

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Commands/PublishToFolderBaseCommandHandler.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Dialogs/PublishToFolderDialog.cs
Backport of #6507.
Description:
- Changes Dialog's button order
- Browse button label
- Animated icon when publishing
> [release-7.7] [AspNetCore] Few UI fixes

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpFormatter.cs
- main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/MonoDevelopContainedDocument.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeFormatting/AbstractCodeFormatter.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeFormatting/CodeFormatter.cs
> Fixes issue #6238 Indent correcting taking up too much time on large

- main/src/addins/GnomePlatform/GnomePlatform.cs
Credits to @madmiraal for the solution
Fixes #6484
> Fix xfce4 terminal runner

- main/src/addins/MonoDevelop.UnitTesting/Services/UnitTestService.cs
times on solution open
ProjectOperations_PackageReferencesModified already contained the
solution for rebuilding. Moved that up to RebuildTests.
> Fixes VSTS User Story 700296: UnitTestService rebuilds tests multiple

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbarController.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/SearchPopupWindow.cs
> [Ide] Fix NRE in main toolbar if search popup has been disposed

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.AnalysisCore/Gui/ResultTooltipProvider.FloatingQuickFixIconWidget.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.AnalysisCore/Gui/ResultTooltipProvider.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeActionContainer.cs
Fixes VSTS #713677 - Lightbulb Experience - Icon shows as wrench for removing usings; should be lightbulb
Fixes VSTS #713688 - Lightbulb Experience - Icon shows as error bulb for unused variables; should be lightbulb
> QuickFix icon fixes

- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/Cecil/MethodDefinitionNodeBuilder.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/Cecil/PropertyDefinitionNodeBuilder.cs
for properties
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/726012
> Fixes VSTS Bug 726012: [Feedback] Assembly browser shows wrong icon

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.AnalysisCore/Gui/ResultTooltipProvider.FloatingQuickFixIconWidget.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.AnalysisCore/Gui/ResultTooltipProvider.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeActionContainer.cs
Fixes VSTS #713677 - Lightbulb Experience - Icon shows as wrench for removing usings; should be lightbulb
Fixes VSTS #713688 - Lightbulb Experience - Icon shows as error bulb for unused variables; should be lightbulb
Backport of #6562.
> [release-7.7] QuickFix icon fixes

- main/msbuild/MonoDevelop.BeforeCommon.targets
Fixes VSTS #729042 - Bump C# language version to 7.3
> [Build] Bump language version to C# 7.3

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/FileTemplateTagsModifier.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/SingleFileDescriptionTemplate.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Templates/SingleFileDescriptionTemplateTests.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Tests.csproj
- Checks if the user has entered or not the extension explicitly
- Detects when there is a suffix like Resources.es.resx
Fixes VSTS Bug 579048
> [Core] Fixes VSTS Bug 579048

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeActionEditorExtension.cs
incorrectly for a single line of recommendations
https://dev.azure.com/devdiv/DevDiv/_workitems/edit/723420
VS.NET takes the whole line into account for fixes - but for
refactorings it's using the caret position.
The fixes are sorted by the distance of the caret position.
Backport of #6620.
/cc @mkrueger
> [release-7.7] Fixes VSTS Bug 723420: Light bulb - Numerous light bulbs show up

- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/TextDocument.cs
commenting a collapsed method
Bug 729390: [Feedback] Display updates partially when commenting a
collapsed method
> Fixes VSTS Bug 729390: [Feedback] Display updates partially when

- main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding.Refactoring/CSharpCodeActionEditorExtensionTests.cs
Fixes VSTS #724319 - Method level fixes show up throughout method body
> [7.7] Bump RefactoringEssentials to bring in code refactoring fixes

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/RefactoringPreviewTooltipWindow.cs
Tagging classifiers require to be run on the UI thread for them to work.
Move markup items on the UI thread, and only do simple text diffing on a background
thread
Fixes VSTS #677991 - Refactoring diff calculation needs to happen on the UI thread
> [Refactoring] Compute markup items on the UI thread

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextEditorViewContent.cs
Fixes VSTS #732827 - Can't open .targets files
> [Editor] Try/catch when trying to parse foldings

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/MenuButton.cs
> [A11y] Make the MenuButton have a menu button role

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
The calculation has changed to fix another bug but the spacing was too high. This should correct it
> Fixes issue #6649 Line height has changed in v8.0

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeVersionInfo.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProductInformationProvider.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/RuntimeVersionInfo.cs
re VSTS #730149 (https://github.com/xamarin/md-addins/pull/3884)
> Remove AppId where it is available from updateinfo

- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.WelcomePage/WelcomePageService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/MessageService.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/737147
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/737155
> Few fixes for Start page integration

- main/src/addins/MacPlatform/MacPlatform.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/737157
> [MacPlatform] Close workspace when IDE window is closed

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.OptionPanels/IDEStyleOptionsPanel.cs
> [8.0][Ide] Close preferences when restarting for a style change

- main/src/addins/MacPlatform/Dialogs/MacAddFileDialogHandler.cs
- main/src/addins/MacPlatform/Dialogs/MacAlertDialogHandler.cs
- main/src/addins/MacPlatform/Dialogs/MacOpenFileDialogHandler.cs
- main/src/addins/MacPlatform/Dialogs/MacSelectFileDialogHandler.cs
- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/PlatformService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.UI.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/DesktopService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/MessageService.cs
This adds initial (not perfect, not complete) support for native MessageService parents.
Fixes VSTS #737184
> [Ide][MessageService] Allow messages to have a native parent by default

- main/src/addins/MonoDevelop.UnitTesting/Services/UnitTestService.cs
times on solution open
ProjectOperations_PackageReferencesModified already contained the
solution for rebuilding. Moved that up to RebuildTests.
Backport of #6405.
/cc @mkrueger
> [release-7.7] Fixes VSTS User Story 700296: UnitTestService rebuilds tests multiple

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbarController.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/SearchPopupWindow.cs
Backport of #6535.
/cc @sevoku 
Description:
Fixes VSTS #682796
> [release-7.7] [Ide] Fix NRE in main toolbar if search popup has been disposed

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CSharpCompletionTextEditorExtension.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding/CSharpCompletionTextEditorTests.cs
pressed by default
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/705110
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/738519
Backport of #6368.
/cc @Therzok @mkrueger
> [release-7.7] Fixes VSTS Bug 705110: Code suggestion does wrong thing when enter is

- main/src/addins/MacPlatform/Dialogs/MacAlertDialogHandler.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AtkCocoaHelper/AtkCocoaHelperMac.cs
> [A11y] Remove focus from the NSAlert dialog when it is closed

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/CodeGenerationPanel.cs
directives first setting does not save
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/737175
> Fixes VSTS Bug 737175: Unchecking the Organize Using > Place System

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.AnalysisCore/Gui/ResultTooltipProvider.FloatingQuickFixIconWidget.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/TextMarker/SmartTagMarginMarker.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/736871
> Fixes VSTS Bug 736871: TextEditor lightbulb menu popover: low-res icon

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AtkCocoaHelper/AtkCocoaHelperMac.cs
editor using VoiceOver
MonoDevelop line numbers ar 1 based.
> Fixes issue #5887 FATAL ERROR when trying to navigate inside the

- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/NativeViewHelper.cs
* Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/737203
* Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/737145
> More Preview1 fixes for WelcomeWindow implementation

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpTextPasteHandler.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/Features/IndentationTests/TextPasteIndentEngineTests.cs
> [release-7.7] Fixes issue #6641 Pasting verbatim strings removes double quotes

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/CodeGenerationPanel.cs
directives first setting does not save
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/737175
Backport of #6720.
> [release-7.7] Fixes VSTS Bug 737175: Unchecking the Organize Using \u003e Place System

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpTextEditorIndentation.cs
semicolon palcement
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/756088
> Fixes VSTS Bug 756088: Smart semicolon placement causes incorrect

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Dialogs/PublishToFolderDialog.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Tests/MonoDevelop.AspNetCore.Tests.csproj
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Tests/MonoDevelop.AspNetCore.Tests/PublishProfileTests.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Tests/Properties/AssemblyInfo.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.csproj
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests.csproj
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/740318
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/740321
> [PublishToFolder] Sorts out default destination folder

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpTextEditorIndentation.cs
semicolon palcement
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/756088
Backport of #6832.
/cc @mkrueger
> [release-7.8] Fixes VSTS Bug 756088: Smart semicolon placement causes incorrect

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Dialogs/PublishToFolderDialog.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Tests/MonoDevelop.AspNetCore.Tests.csproj
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Tests/MonoDevelop.AspNetCore.Tests/PublishProfileTests.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Tests/Properties/AssemblyInfo.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.csproj
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests.csproj
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/740318
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/740321
Backport of #6828.
> [release-7.8] [PublishToFolder] Sorts out default destination folder

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/ProjectFileEntry.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/754804
> [Ide] Added a11y to ProjectFileEntry's "..." button

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpIndentationTracker.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding/CSharpTextEditorIndentationTests.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/753551
> Fixes VSTS Bug 753551: Using statement indenting

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpIndentationTracker.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding/CSharpTextEditorIndentationTests.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/753551
Backport of #6809.
/cc @mkrueger
> [release-7.8] Fixes VSTS Bug 753551: Using statement indenting

- main/src/addins/MacPlatform/MacInterop/LaunchServices.cs
> Add option to ApplicationStartInfo to hide from Recent Apps

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpTextPasteHandler.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/769309
> Fixes VSTS Bug 769309: Exception while pasting code

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpTextPasteHandler.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/769309
Backport of #6909.
/cc @mkrueger
> [release-7.8] Fixes VSTS Bug 769309: Exception while pasting code

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/IconMargin.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/TextDocument.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/769515
The cause was that the line segment markers weren't unparented but I
fixed the crash in IconMargin as well.
> Fixes VSTS Bug 769515: Exception in OnMarkerRemoved

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/IconMargin.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/TextDocument.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/769515
The cause was that the line segment markers weren't unparented but I
fixed the crash in IconMargin as well.
Backport of #6907.
/cc @mkrueger
> [release-7.8] Fixes VSTS Bug 769515: Exception in OnMarkerRemoved

- main/src/core/MonoDevelop.Ide/ExtensionModel/Commands.addin.xml
- main/src/core/MonoDevelop.Ide/ExtensionModel/MainMenu.addin.xml
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/ProjectCommands.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/ProjectNodeBuilder.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/ProjectPadContextMenu.addin.xml
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.OptionPanels/SolutionRunConfigurationsPanel.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/NewSolutionRunConfigurationDialog.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/669199
> [Ide] Add "Set startup projects" command

- main/src/addins/CSharpBinding/CSharpBinding.addin.xml
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Refactoring/RefactoryCommands.cs
Fixes VSTS #755411 - [Feedback] Custom key bindings for Remove Unused and Sort (Usings) Don't Work
> [C#] Fix Remove Unused Imports keybinding

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/InformationPopoverWidget.cs
> [Ide] Fix InformationPopover flickering in nested dialogs

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextEditorViewContent.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/770920
Backport of #6924.
> [release-7.8] Fixes VSTS Bug 770920: NRE in TextDocument.Rename

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.AnalysisCore/Gui/ResultsEditorExtension.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/770474
> Fixes VSTS Bug 770474: NRE in ResultsEditorExtension

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Composition/CompositionManager.Caching.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Composition/CompositionManager.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Services.cs
Fixes VSTS #773841 - Add counter mapping for composition counters
> [Composition] Unify counters and make data processable

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.AnalysisCore/Gui/ResultsEditorExtension.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/774374
> Fixes VSTS Bug 774374: Exception while removing a marker

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreMSBuildProjectTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreMSBuildProject.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdk.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdkPaths.cs
- Prevents NRE when explicit references
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/765999
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/768376
> [netcore]  Better SDK References handling

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/OSXEditor.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/770919
Backport of #6945.
> [release-7.8] Fixes Bug 770919: NRE in OSXEditor.GetLineHeight

- main/src/core/MonoDevelop.Ide/Gui/MonoDevelop.Ide.Gui.OptionPanels.LoadSavePanelWidget.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.OptionPanels/LoadSavePanel.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdePreferences.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/729583
> Add IDE startup preferences

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.AnalysisCore/Gui/ResultsEditorExtension.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/770474
Backport of #6958.
/cc @mkrueger
> [master] Fixes VSTS Bug 770474: NRE in ResultsEditorExtension

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/RefactoringPreviewTooltipWindow.cs
RefactoringPreviewTooltipWindow.MeasureLine
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/776264
> Fixes VSTS Bug 776264: Pango-Critical in

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor.Utils/ClipboardColoredText.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/TextEditorData.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/InternalExtensionAPI/ITextEditorImpl.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextEditor.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/SearchResult.cs
disposed
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/774516
> Fixes VSTS Bug 774516: Exception in editor: TextEditorData was
