- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor.Theatrics/Actor.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor.Theatrics/Stage.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/FoldMarkerMargin.FoldMarkerMarginDrawer.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/FoldMarkerMargin.VSCodeFoldMarkerMarginDrawer.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/FoldMarkerMargin.VSNetFoldMarkerMarginDrawer.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/FoldMarkerMargin.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/Margin.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.csproj
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/DefaultSourceEditorOptions.cs
https://github.com/mono/monodevelop/issues/4566
Should match the VS.NET default options.
> Fixes issue #4566 Enabling code folding by default

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.SpanUpdateListener.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/TextDocument.cs
TextViewMargin.SpanUpdateListener was listening to Document_TextChanging, but calling Layout code that assumed that the currentSnapshot is the new snapshot.
At the time TextChanging is called the currentSnapshot has not been updated yet and still points to the old snapshot. If the new code tries to apply the new changes against the old snapshot they will get corrupt data.
Instead, as a tactical fix for 15.7 introduce a new internal event, TextChangedHighPriority, which is analogous to the same-named event of VS Editor, which is raised immediately after the currentSnapshot has been updated and it is what the layout code expects.
Long term, the right fix would be to move off TextDocument.TextChanging/TextChanged events entirely and listen to the appropriate events of ITextBuffer.
> Fix VSTS 609859 - access the correct snapshot on text change

- main/src/addins/Deployment/MonoDevelop.Deployment/MonoDevelop.Deployment.Gui/SourcesZipEditorWidget.cs
- main/src/addins/Deployment/MonoDevelop.Deployment/MonoDevelop.Deployment.Targets/SourcesZipPackageBuilder.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildFileFormat.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/SlnFileFormat.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectConvertTool.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/SelectFileFormatDialog.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/ExportSolutionDialog.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/TestProjectsChecks.cs
- main/tests/test-projects/project-includes-props/ConsoleProject/ConsoleProject.csproj
Clean up MSBuildFileFormat to obsolete unused and invalid members, and fix various places in the code that depended on these invalid values.
As an example, here's what project export looked like before the patch:
```
mikayla@neptune:~/code/monodevelop$ /Applications/Visual\ Studio.app/Contents/MacOS/vstool project-export -l ~/Projects/HelloConsole/HelloConsole.sln 
Target formats:
1. MSBuild
2. MSBuild
3. MSBuild
4. MSBuild
5. MSBuild
```
Here's what it looks like after the patch:
```
mikayla@neptune:~/code/monodevelop$ mono main/build/bin/mdtool.exe project-export -l ~/Projects/HelloConsole/HelloConsole.sln 
Target formats:
1. MSBuild12 (Visual Studio 2012+)
2. MSBuild10 (Visual Studio 2010)
3. MSBuild08 (Visual Studio 2008)
4. MSBuild05 (Visual Studio 2005)
```
This also adds a …
> Clean up MSBuildFileFormat

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.SpanUpdateListener.cs
- main/src/addins/MonoDevelop.SourceEditor2/VSEditor/TagBasedSyntaxHighlighting.cs
Reverting the fix that killed C# highlighting in Razor and just use try/catch to suppress crashes.
> Prevent crashes and bring back C# highlighting in Razor

- main/src/addins/MacPlatform/MainToolbar/SelectorView.cs
`NSPathControl` expects it's url to be encoded and escaped using `NSString.CreateStringByAddingPercentEscapes`. Simple encoding with System.Uri does not work.
> [610547][Mac] Fix device selection with special characters

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Features/AutoInsertBracket/AbstractTokenBraceCompletionSession.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/EditActions.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/EditSession.cs
- main/src/core/MonoDevelop.TextEditor.Tests/Mono.TextEditor.Tests.DefaultEditActions/DeleteActionTests.cs
braces above it in .cs file
The skip char session backspace behavior is already covered inside
SkipCharSessionTests.
> Fixes VSTS 609809: Closing curly brace removed on deleting curly

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputTreeCellView.cs
Fixes unexpected issues breaking current treeview click tunneling behaviour.
We only want break this behaviour in cases where our label exceeded the size of the current treeview. 
Fixes
https://devdiv.visualstudio.com/DevDiv/Xamarin%20VS%20for%20Mac/_workitems/edit/602813
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/602872
> Fixes unexpected issues breaking current treeview click tunneling behaviour

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CSharpCompletionData.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/RoslynCompletionData.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/KeyDescriptor.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding/CSharpCompletionTextEditorTests.cs
which is added to existing .net console project.
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/611923
> Fixes VSTS 611923: Unable to add declarations to an empty C# file

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MetadataReferenceCache.cs
When a project referenced another project and the referenced assembly
changed a Reference MSBuild item would be added to the project. This
would result in unwanted Reference MSBuild items being added since
the ProjectReference was all that was needed.
Changed the MetadataReferenceCache so it no longer calls TryApplyChanges
on the MonoDevelopWorkspace which would result in the project being
modified. Now OnMetadataReferenceRemoved and OnMetadataReferenceAdded
are called which just updates the metadata so code completion is
up to date based on the latest assemblies.
Fixes VSTS #613601 - Duplicate references added on rebuilding project
> [Ide] Fix duplicate references added to project

- Makefile
It's not regenerated ordinarily, causing `make dist` to include a "wrong" file if switching branches. Fixes occasional accidental bad Help/About versions
> Always regenerate BuildVariables.cs in `make dist`

- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Execution/RemoteProcessConnection.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
- main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.Formats.MSBuild/ProjectBuilder.v4.0.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/ProjectBuildTests.cs
- main/tests/test-projects/builder-manager-tests/crasher/ConsoleProject.csproj
- main/tests/test-projects/builder-manager-tests/crasher/Program.cs
- main/tests/test-projects/builder-manager-tests/crasher/Properties/AssemblyInfo.cs
When aborting pending messages, do it outside the message waiters lock,
since that can cause new messages to be posted from the thread that has
the lock, modify the messageWaiters collection, and break everything.
Also make sure no new messages are queued after the connction has
been disposed.
Fixes VSTS bug #580790 - The stable monodevelop version crashes very frequently.
Fixes VSTS bug #605244 - Fatal error on opening solution created in windows on mac
> Fix concurrency issues in RemoteProcessConnection

- main/src/addins/CSharpBinding/MonoDevelop.CSharp/ProjectSearchCategory.cs
Fixes VSTS #612896 - NavigateTo type filter isn't working
master counterpart is here: https://github.com/mono/monodevelop/pull/4585/commits/1e6339a5951927adf54fe492029c9c337a63a209
> [C#] Fix type filter not working

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MetadataReferenceCache.cs
Backport of #4758.
/cc @mrward
Fixes the duplicate references added to the project. Also verified that directly referencing a .dll updates the type system information for code completion when the .dll is modified or deleted.
> [d15-7] [Ide] Fix duplicate references added to project

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/MonoTextEditor.ITextView.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.csproj
- main/src/addins/MonoDevelop.SourceEditor2/VSEditor/Text/Impl/WpfToolTipAdornment/BaseWpfToolTipPresenter.cs
- main/src/addins/MonoDevelop.SourceEditor2/VSEditor/Text/Impl/WpfToolTipAdornment/MouseTrackingWpfToolTipPresenter.cs
- main/src/addins/MonoDevelop.SourceEditor2/VSEditor/Text/Impl/WpfToolTipAdornment/ViewElementFactories/WpfObjectViewElementFactory.cs
Main problem was in file MouseTrackingWpfToolTipPresenter.cs where Xwt.Toolkit.CurrentEngine.WrapWidget was called on editor, I assumed in past any native object can be wrapped as needed, but it seems like only new(widgets without parents can be wrapped) so we can't act like Editor is Xwt object, instead handle everything is Gtk...
I also noticed that we were missing new ViewElementFactory(one for object) which I added now, very primitive for now, just so it's not empty popup.
Rest of changes are related to making sure MouseLeave and MouseMove events work for both, popup.Content and IMdTextView.VisualElement correctly.
> Fix 614155: Text editor rendering breaks in master

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/MonoDevelopBuildIntegratedRestorer.cs
On opening a solution containing projects that use PackageReferences
the restore that runs was forcing a restore for each project. This
resulted in the project.assets.json file being re-generated and
the projects being re-evaluated. Now if the package references have
not changed a no-op restore will occur. This makes the restore much
faster on opening a solution. It also prevents NuGet going online to
fetch NuGet package information if a wildcard is used for a
PackageReference or if the version cannot be found. In the Package
Console when a no-op restore occurs you will see the following
messages:
Assets file has not changed. Skipping assets file writing.
No-Op restore. The cache will not be updated.
Fixes VSTS #614192 - NuGet Restore is never a no-op
> [NuGet] Support no-op restores on opening a solution

- main/src/addins/MonoDevelop.WebReferences/MonoDevelop.WebReferences.WS/WebServiceDiscoveryResultWS.cs
Adding a .NET 2.0 Web Services web reference would add a file to
the project using a background thread. For ASP.NET Core MVC projects
that use a .cshtml file this would result in an error message:
The web reference could not be added
'DotNetProject_Modified' must be called on the foreground thread.
Fixes VSTS #615584 - Cannot add web reference to ASP.NET Core MVC
project
> [WebReferences] Fix background thread used when adding file to project

- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/Interactive.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpInteractivePad.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/FileService.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/InteractiveSession.fs
- main/external/fsharpbinding/MonoDevelop.FSharpi.Service/Program.fs
Fixes VSTS #615186
We now send the filename of the active document along with the user
input on each invocation.
This also means that __SOURCE_FILE__ works now too.
> Fix initial output message in F# interactive

- main/src/addins/CSharpBinding/CSharpBinding.csproj
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CSharpCompletionTextEditorExtension.IDebuggerCompletionProvider.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CSharpCompletionTextEditorExtension.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.csproj
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebuggerConsoleView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebuggingService.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ExpressionEvaluatorDialog.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/IDebuggerCompletionProvider.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValueTreeView.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding.Tests.csproj
- main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding/CSharpCompletionTextEditorTests.cs
This commit adds new `MonoDevelop.Debugger.IDebuggerCompletionProvider` interface that can be implemented on EditorExtensions which allows each language extension to provide enhanced code completion items for debugger.
So users of debugger code completion (Immidiate pad, Expresson evaluator, Watchpad...) now use new `DebuggingService.GetCompletionDataAsync` method which first attempts to use `IDebuggerCompletionProvider` implementation and if that fails, falls back to old way of using debugger locals.
C# implementation is mimicking what VS does, which is, add `;` around expression at end of where execution stopped(also handles special cases like when we stop at end of method on `}` to place it before `}`) and calls Roslyn code completion with updated solution.
> Fix 528282: Immediate window completion only contains locals

- main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.VsTest/VsTestAdapter.cs
Instead of adding new option to preferences and make it even more bloated, I decided to set timeout to maximum possible value. User can always cancel execution of unit test from IDE so there is no upside to having timeout from IDE. It would only confuse new users who would need to find setting and update to bigger value...
> Fix #3513: TestSessionTimeout is not configurable

- main/src/addins/CSharpBinding/CSharpBinding.addin.xml
It was being loaded for all mime types. Now the mimeTypes will be respected.
Bug https://github.com/mono/mono-addins/issues/116 is a suggestion to add a warning to prevent such errors in the future.
> Fix mimeTypes attribute on CSharpAutoInsertBracketHandler.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/ExtensibleTreeView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/NodeCommandHandler.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/FolderNodeBuilder.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/SolutionFolderFileNodeBuilder.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/SolutionFolderNodeBuilder.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/SolutionNodeBuilder.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/SystemFile.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/SystemFileNodeBuilder.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/NewFileDialog.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/FileTemplate.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/SingleFileDescriptionTemplate.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
Fixes issue #4775 - Cannot add new file to solution items
Fixes issue #4774 - Cannot rename solution items
> Implement "add new" and "rename" for solution folder files

- main/src/addins/MonoDevelop.SourceEditor2/VSEditor/Language/Impl/QuickInfo/QuickInfoTextViewCreationListener.cs
Disable the Roslyn-based Quick Info for now for C#, because it conflicts with the MonoDevelop one.
We will reenable it later as part of moving to VS Editor.
Also fixes https://github.com/mono/monodevelop/issues/4818
> Fix https://github.com/mono/monodevelop/issues/4816 (disable Roslyn Quick Info)

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.AnalysisCore/AnalysisCommands.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.AnalysisCore/MonoDevelopWorkspaceDiagnosticAnalyzerProviderService.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeActionPanelWidget.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeFixMenuService.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeIssues/CodeDiagnosticRunner.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeIssues/CodeIssuePanelWidget.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/AnalyzeWholeSolutionHandler.cs
`HostDiagnosticAnalyzerPackage` was fully created when `MonoDevelopWorkspaceDiagnosticAnalyzerProviderService` was requested which is requested from UI thread by `ICodeFixService` which is requested by `CodeActionEditorExtension`. To fix this I moved creation to Threadpool and changed `Options` field that was requested from multiple sources inside MonoDevelop to `GetOptionsAsync` so it returns options only once they are loaded. Notice that `GetHostDiagnosticAnalyzerPackages` is called from threadpool, so even if creating `HostDiagnosticAnalyzerPackage` takes long time it won't block UI.
Fixes VSTS 593833.
> Fix 593833: Showing a document does MEF work on the UI thread

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Features/AutoInsertBracket/AbstractTokenBraceCompletionSession.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/EditSession.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Editor/SkipCharSessionTests.cs
when `}` is deleted
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/615849
> Fixes VSTS Bug 615849: Automatic matching brace completion deletes `{`

- main/build/MacOSX/Info.plist.in
- main/build/MacOSX/monostub.mm
See: https://openradar.appspot.com/radar?id=4960317826138112
This means that anything loc related should be using localizations from bundle,
and leave NSLocale to do its own job
Fixes VSTS #587766 - Chinese langauge not reflected in VSfM when selected from the system language.
Fixes VSTS #591373 - [Feedback] After adding Japanese keyboard input, some context menu items are in Japanese, even though the preferred system language is Portuguese and Visual Studio for Mac UI Language is set to default
Fixes VSTS #591378 - [Feedback] Default UI Language preference does not reflect system settings
> [Loc] Possible fix at many localizations issues with have

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.Helpers/FakeNuGetProjectContext.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.csproj
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/UpdateXamarinFormsBuildTest.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/DotNetCoreNuGetProject.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
- main/tests/test-projects/FormsUpdatePackageRef/FormsUpdatePackageRef.sln
- main/tests/test-projects/FormsUpdatePackageRef/LibraryProject/LibraryProject.csproj
- main/tests/test-projects/FormsUpdatePackageRef/LibraryProject/Properties/AssemblyInfo.cs
- main/tests/test-projects/FormsUpdatePackageRef/NetStandardProject/Class1.cs
- main/tests/test-projects/FormsUpdatePackageRef/NetStandardProject/NetStandardProject.csproj
- main/tests/test-projects/FormsUpdateTest/FormsUpdateTest.sln
- main/tests/test-projects/FormsUpdateTest/LibraryProject/LibraryProject.csproj
- main/tests/test-projects/FormsUpdateTest/LibraryProject/MyClass.cs
- main/tests/test-projects/FormsUpdateTest/LibraryProject/Properties/AssemblyInfo.cs
- main/tests/test-projects/FormsUpdateTest/LibraryProject/packages.config
- main/tests/test-projects/FormsUpdateTest/PclProject/MyPage.xaml
- main/tests/test-projects/FormsUpdateTest/PclProject/MyPage.xaml.cs
- main/tests/test-projects/FormsUpdateTest/PclProject/PclProject.csproj
- main/tests/test-projects/FormsUpdateTest/PclProject/Properties/AssemblyInfo.cs
- main/tests/test-projects/FormsUpdateTest/PclProject/packages.config
This problem was fixed in Xamarin Studio 5.8 ac84628
and seems to have re-surfaced. On updating Xamarin.Forms in a solution
that contains multiple projects that use it the build would sometimes
fail with errors like:
Could not load file or assembly 'Xamarin.Forms.Xaml,
Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' or one of
its dependencies.
Error XF002: Xamarin.Forms tasks do not match targets. Please
ensure that all projects reference the same version of
Xamarin.Forms, and if the error persists, please restart the IDE.
The old MSBuild tasks and targets were being used after they have
been updated. Now when an MSBuild import has changed in a project
the remote MSBuild host is shutdown to ensure the correct tasks are
used.
Fixes VSTS #576301 - Getting "Could not load file or …
> [NuGet] Fix build error after updating Xamarin.Forms NuGet package 

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.DevCertInstaller/Program.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/DotNetCoreDevCertsTool.cs
With Xamarin.Mac 4.5.0.280 or later being used by the IDE, when the
ASP.NET Core addin tries to install the HTTPS development certificate
the Mac message dialog that asks for the username and password will
now show:
dotnet-dev-certs wants to make changes.
If an older Xamarin.Mac version is used by the IDE then the previous
behaviour occurs where the dialog asking for the username and
password shows:
mono-sgen64 wants to make changes.
Fixes VSTS #573860 - Add custom message when asking for credentials
to install HTTPS certificate
> [AspNetCore] Add custom message for credentials prompt to install cert

- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor.Utils/CompressingTreeList.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/DiffTracker.cs
Can't repro the issue but the diff tracker relied on text
changing/text changed pairs which is kind of broken in the current
editor. Reworked it so that only the text changed event is used &
handled the exception from the log.
> Fixes VSTS 616981: [Feedback] VSMac Freezes When Saving A file

- main/build/MacOSX/Info.plist.in
- main/build/MacOSX/monostub.mm
Backport of #4798.
/cc @slluis
Fixes VSTS #587766 - Chinese langauge not reflected in VSfM when selected from the system language.
Fixes VSTS #591373 - [Feedback] After adding Japanese keyboard input, some context menu items are in Japanese, even though the preferred system language is Portuguese and Visual Studio for Mac UI Language is set to default
> [d15-7] [Loc] Possible fix at many localizations issues with have

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/MonoTextEditor.cs
This fixes broken-looking indentation for RTL languages like
Hebrew. It also fixes another issue I observed where inserting
text after a // comment in Hebrew would actually insert it
before the comment.
Fixes VSTS #577636
> [TextEditor] Set editor container's text direction as LTR

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
If the configuration has not changed and the project has not been
modified then the files returned from Project.GetSourceFilesAsync
will be returned from a cached result. This prevents the project
being re-evaluated each time this method is called.
Currently repeated calls to GetSourceFilesAsync only occur when
the project has files that need to be generated. The project's
PerformGeneratorAsync method calls GetProjectFileTimestamps which
then calls GetSourceFilesAsync. Note that the GetProjectFileTimestamps
will most likely be removed with the file watcher integration since
it is only used to programmatically generate FileService.FileChanged
events which would be automatically generated by the file watcher.
Fixes VSTS #620341 - Cache evaluated source files.
> [Core] Cache evaluated source files

- main/src/core/MonoDevelop.Ide/ExtensionModel/StockIcons.addin.xml
Spinners frames now take 40ms instead of previous 60ms – and some were even at default 200ms.
> Spinner speed increase

- main/tests/test-projects/FormsUpdatePackageRef/NetStandardProject/NetStandardProject.csproj
Change the .NET Standard project to use .NET Standard 1.6 instead of
2.0. The test now works when .NET Core 2.0 SDK is not installed. This
fixes the UpdateXamarinFormsNuGetPackageReference_ThenBuild test which
was failing Wrench.
> [NuGet] Fix test failing on Wrench

- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Instrumentation/TimeCounter.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/CompletionStatistics.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/CompletionTextEditorExtension.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Services.cs
Code completion timing statis are captured and sent when the document
is closed. The timings include:
1. How long the first code completion took in milliseconds.
2. Minimum code completion time.
3. Maximum code completion time.
4. Average code completion time.
5. Counts of the number of failures, cancellations or successful
code completion events.
Fixes VSTS #620251 - Convert completion telemetry to use statistics
to avoid sending many messages
Requires md-addins change.
> [Ide] Add code completion stats counter

- main/src/addins/MonoDevelop.SourceEditor2/VSEditor/TagBasedSyntaxHighlighting.cs
Update)
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/621570
Tried to add a tagger but it was a very complex approach and
interfered with the c# tagger - overall this is way more efficient
than re evaluating the syntax tree again and works for any tag based
language not just for one.
> Fixes VSTS 621570: [Feedback] TODO doesn't highlight (worked before

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/MonoTextEditor.ITextView.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs
Problem was that Semantic highligthing was generated only for text visible on screen + few lines before and after
But since MonoTextEditor didn't report `LayoutChanged` events SemanticTagger didn't know it needs to update classifications for new area of file hence it didn't work
With this change we notify hence it works...
> Fixes missing semantic highlighting after switch to TagBasedSyntaxHightligthing after scrolling

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices.Options/MonoDevelopGlobalOptionPersister.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices.Options/RoslynPreferences.Properties.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.RoslynServices.Options/MonoDevelopOptionPersisterTests.cs
Any enum, string or bool value is allowed. Resort to querying FromXElement via reflection on all types and let roslyn bail if anything's wrong
Also, handle a few more test cases
Fixes log spew like
```
ERROR [2018-05-26 02:24:02Z]: Failed to deserialize type: Microsoft.CodeAnalysis.CodeStyle.CodeStyleOption`1[System.String] value: <CodeStyleOption SerializationVersion="1" Type="String" Value="public,private,protected,internal,static,extern,new,virtual,abstract,sealed,override,readonly,unsafe,volatile,async" DiagnosticSeverity="Hidden" />
System.Runtime.Serialization.SerializationException: Serialization error.
at MonoDevelop.Ide.RoslynServices.Options.MonoDevelopGlobalOptionPersister.Deserialize (System.Object value, System.Type optionType) [0x001b0] in …
```
> [Ide] Make option deserialization a bit more permissive

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
'...' associated with a compile error
Seems that the clip rectangle is forgotten for the textViewCr when
drawing on other Contexts occur in some - but not all - cases. Moving
the clipping to the text view margin (where it belongs to btw.)
corrects the behavior.
> Fixes issue #4906 Gutter on the left corrupts when you hover over the

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputTreeCellView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputWidget.cs
Our renderer has some issues in managing click events:
* we are handling clicks in renderer and from calling controls, we added additional check to ensure the click is not a managed area only from renderer.
* added a small delay in user click to ensure our renderer is in the correct state
* fixes pipeline order calculating bounds while clicking the expander
Fixes Bugs:
* Output Disclosure Toggles Twice
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/607739
* Flickering observed while expanding code at build output file
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/618855
* After eye marking, sometimes marker jumps at first position inspite of expanding at same location even as space is available
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/619625
* Output Text …
> Fixes unwanted states using a Expander in CellRenderer

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/ExtensibleTextEditor.cs
Before we shift-left or shift-right to select, ensure that the preedit
buffer is committed or the selection can be in the wrong place and
mess things up.
Fixes VSTS #617555
Also commit the preedit string on mouse click. This fixes issues with
text selection when you try to select the last visible character when
there is a preedit string (described in VSTS #617559) and also another
bug I observed that isn't in VSTS where if you click elsewhere in the
text editor while there is a preedit string then text gets moved in a way
that looks very jarring and unpredictable to the user.
Fixes VSTS #617559
> [TextEditor] Ensure preedit is committed before selecting left/right

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs
After a recent change to use Roslyn's SourceTextContainer instead of MonoDevelopSourceTextContainer the text container for an additional document such as .css started being reused across both MonoDevelopWorkspace and WebEditorsRoslynWorkspace. As a result the MonoDevelopWorkspace was overwriting the workspace registration on the document and WebEditorsRoslynWorkspace wasn't finding the document in its workspace.
The problem effectively was because the document belonged to two workspaces at the same time but the registration only allows a single document. This explains why after reopening the document intellisense came back - this is because the association with WebEditorsRoslynWorkspace was restored as the document got readded.
This should fix quite a few issues such as 623772 and 623774. …
> Fix VSTS 623772: IntelliSense in CSS, Json, etc.

- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/TextDocument.cs
This change was added for some reason I don't remember when we
were using a TextEditor to display the .binlog file, and was left in the
structured-build-output PR.
> [TextEditor] Remove leftover change from structured-build-output

- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Setup/AddinSetupService.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core/Runtime.cs
I've added an SSL certificate for [addins.monodevelop.com](https://addins.monodevelop.com), so we can switch the default generated repo URL from `http` to `https`.
> Switch addins.monodevelop.com to HTTPS

- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Instrumentation/TimeCounter.cs
Always log trace messages in TimeCounter if logging is enabled.
> Fix logging issue in timers

- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Instrumentation/TimeCounter.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
It's not really clear what is purpose of `AdditionalDocuments`. I can't find any use case in Roslyn source code(or MonoDevelop). I also debugged VS Windows and checked on MonoDevelop.Ide.csproj and Wpf application from template, neither had any `AdditionalDocuments`. Problem was at https://github.com/dotnet/roslyn/blob/5b113ae/src/Workspaces/Core/Portable/Workspace/Solution/ProjectState.cs#L202 which iterates over all documents and additionalDocuments and checks for latest version to see if compilation needs to be recalculated. In case of MonoDevelop.Ide.csproj documents were ~1k and additionalDocuments were ~2.8k(.png and other files).
"C#: Got completions" went from  ~1second to ~40ms.
I suspect also other cases where Semantic Model is requested will be faster.
I also added …
> Fix slow code completion caused by AdditionalDocuments

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
Fixes VSTS #625468 - Git switch branch - Gtk operation being done on background thread
> [Git] Fix UI thread operations on the bg thread

- .editorconfig
Stop suggesting use of var in nonapparent cases. Still allow it. Gets rid of huge amounts of annoying suggestions in the editor.
> Remove some editorconfig var suggestions

- main/build/MacOSX/Info.plist.in
Fixes VSTS #626970 - Structured Log - Missing IDE mapping in Finder
> [Mac] Add binlog to the list of file types handled by the IDE

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
introduced with the fix of #4906 it's not needed AFAICT - it just
produced the side effect with the overlay controls.
> Fixes issue #5014 Search window is overdrawn The reset clip call got

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProjectInstance.cs
On opening a SDK style project sometimes a null reference exception
was logged.
```
System.NullReferenceException: Object reference not set to an instance
of an object
at MonoDevelop.Projects.MSBuild.DefaultMSBuildEngine+<FindGlobItemsIncludingFile>d__85.MoveNext ()
in MonoDevelop.Projects.MSBuild/DefaultMSBuildEngine.cs:1441
at System.Linq.Enumerable+WhereEnumerableIterator`1[TSource].MoveNext ()
in System/Linq/Where.cs:140
at MonoDevelop.Projects.Project.OnFileCreatedExternally (System.String fileName)
in MonoDevelop.Projects/Project.cs:4293
at MonoDevelop.Projects.Project+<>c__DisplayClass338_0.<OnFileCreated>b__0 ()
in MonoDevelop.Projects/Project.cs:4258
```
This was difficult to reproduce. In the end adding a Thread.Sleep in
MSBuildProjectInstance's Dispose and Evaluate methods …
> [Core] Fix null reference when opening SDK style project

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/TextEditorData.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Text/TextChangeEventArgs.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/CompletionController.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/CompletionWindowManager.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/ICompletionWidget.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/CompletionTextEditorExtension.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/KeyDescriptor.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/InternalExtensionAPI/ITextEditorImpl.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding/CSharpCompletionTextEditorTests.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding/NamedArgumentCompletionTests.cs
The virtual indent behavior was quite broken in the completion window
case. This should stop virtual indent to interfere with completion and
indent should be corrected after the completion session ends.
> Fixes issue #5025 Text loses indentation when typing

- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/SystemAssemblyService.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Core.Assemblies/SystemAssemblyServiceTests.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/ProjectTests.cs
- main/tests/test-projects/iOSImmutableCollections/iOSImmutableCollections.sln
- main/tests/test-projects/iOSImmutableCollections/iOSImmutableCollections/MyClass.cs
- main/tests/test-projects/iOSImmutableCollections/iOSImmutableCollections/Properties/AssemblyInfo.cs
- main/tests/test-projects/iOSImmutableCollections/iOSImmutableCollections/iOSImmutableCollections.csproj
With a Xamarin.iOS project that uses an assembly that is compiled
for .NET Standard, such as the assembly used in the
System.Collections.Immutable NuGet package, the facade assemblies
were not being included in the list of referenced assemblies given
to the type system. This then resulted in the text editor showing
errors even though the project could be compiled without succesfully.
The error displayed was similar to:
The type 'ValueType' is defined in an assembly that is not
referenced. You must add a reference to assembly 'netstandard,
Version=2.0.0.0, Culture=neutral, PublicKeytoken=cc7b1dffcd2ddd51'.
A short term fix has been added here. A check is made to determine if
the assembly referencing netstandard and if so the facade assemblies
are included. Previously only a check was made …
> [Core] Fix editor errors when .NET Standard assembly referenced

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/WorkspaceObject.cs
Previously, this was done of the temporary extension chain, but it was removed in a cleanup.
> [ExtensionChain] Fix default insertion position setting

- main/src/addins/CSharpBinding/MonoDevelop.CSharp/SignatureMarkupCreator.cs
I cannot reproduce the exact issue but this invalid format string resulted in errors logged on the console output.
> [csharp] Fix invalid string format in SignatureMarkupCreator.

- main/src/addins/Xml/Completion/XmlMultipleClosingTagCompletionData.cs
- main/src/addins/Xml/Completion/XmlTagCompletionData.cs
- main/src/addins/Xml/Editor/BaseXmlEditorExtension.cs
Added `.` to ignored commit characters for closing element completion. Reason for this is that `.` can be part of element name...
Also moved `...` in front of element name because:
a) it's more correct since other elements are inserted before
b) because general code completion logic has weird rule to "ignore" `IsCommitCharacter` if `DisplayText` ends with `.`
Also found bug with `InsertCompletionText` that was attempting to fix caret position but failed, but also failed at inserting text by not removing existing text.
> Fix VSTS 605711: Incorrect XAML completion for </ContentPage.Re

- main/src/addins/MonoDevelop.UnitTesting.NUnit/MonoDevelop.UnitTesting.NUnit/NUnitProjectTestSuite.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/AssemblyReference.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs
Updates metadata on the implicit assembly references to match MSBuild, and use this to correctly filter out facades and implicit framework assemblies from the NUnit support libraries.
> Filter facades from NUnit support libs

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ItemCollection.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/DotNetCoreProjectTests.cs
Creating a new Xamarin.Forms .NET Standard project and then
modifing the .xaml to add new named UI items would result in no
intellisense in the .xaml.cs file until the solution was closed
and re-opened. The problem was that the .xaml and .xaml.cs files
were being removed from the ProjectFileCollection's files lookup
list when the project was re-evaluated. On re-evaluation after
the NuGet restore is first done the old MSBuild items for the
.xaml and .xaml.cs file have the wrong metadata, so they need
to be removed, whilst new MSBuild items with the updated metadata
need to be added. To fix this when re-evaluating the items are now
removed first and then added to prevent the newly added items being
removed incorrectly since they have the same filenames.
Fixes VSTS #615578 - Intellisense …
> [Core] Fix .xaml.cs intellisense in new Forms .NET Standard project

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs
- main/tests/test-projects/aspnetcore/aspnetcore.csproj
Adding a new .html file to the wwwroot folder of an ASP.NET Core
project would add the file as a None item instead of a Content
item. This would result in the .html file not being used when
publishing the project. If you use use 'dotnet publish' the
publish directory would not contain the .html file. ASP.NET Core
projects have different build actions for files based on where they
are added. An .html file in the root directory would be a None item
whilst a .html file in the wwwroot directory would be a Content item
by default. To fix this the default build action for a file is
determined from the file glob information available from the .NET
Core SDK.
Fixes VSTS #627227 - Publish the project, content is not the same
as the localhost page.
> [DotNetCore] Fix default build action for new file

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/ExtensibleTextEditor.cs
This is https://github.com/mono/monodevelop/pull/4913 but for 15.7
Before we shift-left or shift-right to select, ensure that the preedit
buffer is committed or the selection can be in the wrong place and
mess things up.
Fixes VSTS #617555
Also commit the preedit string on mouse click. This fixes issues with
text selection when you try to select the last visible character when
there is a preedit string (described in VSTS #617559) and also another
bug I observed that isn't in VSTS where if you click elsewhere in the
text editor while there is a preedit string then text gets moved in a way
that looks very jarring and unpredictable to the user.
Fixes VSTS #617559
> [15.7] [TextEditor] Ensure preedit is committed before selecting left/right

- main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.MSBuild/BuildEngine.cs
- main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.MSBuild/ProjectBuilder.cs
Optimizes MSBuild evaluation by reducing the total number of evaluations and reusing the same project collection when evaluating.
> [MSBuild] Use the global collection when evaluating projets

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/DotNetCoreNuGetProjectTests.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/PackageReferenceNuGetProjectTests.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/DotNetCoreNuGetProject.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageReferenceNuGetProject.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/ProjectPackageReference.cs
On updating a NuGet PackageReference the old PackageReference was
removed from the project and then a new PackageReference was added.
This resulted in any custom MSBuild properties associated with the
PackageReference being removed. Now on updating a NuGet package the
version of the existing PackageReference is updated.
Fixes VSTS #568994 - Updating PackageReference removes metadata
> [NuGet] Fix updating PackageReference removes metadata

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
Creating a new ASP.NET Core 2.1 Angular project from the command line,
then opening it into the IDE, and building it would result in the
IDE hanging.
On building an ASP.NET Core 2.1 Angular project (also React.js and
Redux) will attempt to run an npm install. This results in thousands
of files being created in the node_modules directory. These files
being created resulted in the UI thread being used to check to
see if the file needed to be automatically added to the project
and resulted in a hang of the IDE. This check has been moved off
the UI thread when files are created which prevents the UI hang.
Also adding some code to ignore temporary files which are
generated by the text editor on saving (e.g. '.#MyClass.cs) which
broke TextFileUtility_WriteText_FileNotRemovedAndAddedBackToProject …
> [Core] Fix UI hang when building ASP.NET Core 2.1 Angular project

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/TagCommentsTextEditorExtension.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/Tag.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Tasks/CommentTasksProviderTests.Controller.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Tasks/CommentTasksProviderTests.cs
Fixes VSTS #626731 - Line/col for TODO issues is off by 1
> [TODO] Fix off by 1 indices in todo comments

- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/TemplateTests.fs
Backport of #5099.
/cc @nosami
> [release-7.6] Omitting TargetFramework causes latest Android SDK to be used

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/DotNetCoreDevCertsTool.cs
The dev certs console app needs to be run with mono64 otherwise it
crashes since it uses 64 bit Xamarin.Mac.
```
at (wrapper managed-to-native) Security.Authorization.AuthorizationCreate (Security.AuthorizationItemSet*,Security.AuthorizationItemSet*,Security.AuthorizationFlags,intptr&) <0x00012>
at Security.Authorization.Create (Security.AuthorizationParameters,Security.AuthorizationEnvironment,Security.AuthorizationFlags) [0x001f8] in <1d35452d95a94ac5bbd68a29ad6a434d>:0
at MonoDevelop.AspNetCore.DevCertInstaller.MainClass.Run (string,string,string) [0x00031] in <bde88a041aeb46609477112e419aea87>:0
at MonoDevelop.AspNetCore.DevCertInstaller.MainClass.Main (string[]) [0x00031] in <bde88a041aeb46609477112e419aea87>:0
at (wrapper runtime-invoke) …
```
> [AspNetCore] Fix dev certs console app being run with mono32

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpSymbolHelper.fs
notCtorOrProp was returning true for a property. This was causing the
`Val` active pattern to return true for properties.
Fixes VSTS #585696 (#4226)
> Fix Get Implementing Symbols

- main/src/addins/MonoDevelop.SourceEditor2/VSEditor/TagBasedSyntaxHighlighting.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Editor/Commands/CodeCommentTests.cs
Problem was that in case of start/end of line where Roslyn didn’t report any specific highlighting we used defaultScope, problem with that was that after switch from RoslynClassifier to TagBased one I used Foreground which didn’t stack on top of “sources.cs”. So now `defaultScopeStack` is set correctly, and to better match with RoslynClassifier I also re-introduced userScope.
Also includes unit tests
> Fix #4822: Fixing code comment command for all cases

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/TagCommentsTextEditorExtension.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/Tag.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Tasks/CommentTasksProviderTests.Controller.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Tasks/CommentTasksProviderTests.cs
Backport of #5101.
/cc @Therzok
> [release-7.6] [TODO] Fix off by 1 indices in todo comments

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/DefaultMSBuildEngine.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildEvaluationContext.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/ProjectLoadSaveTests.cs
- main/tests/test-projects/ImportCircularDependency/FirstImport.targets
- main/tests/test-projects/ImportCircularDependency/ImportCircularDependency.csproj
- main/tests/test-projects/ImportCircularDependency/ImportCircularDependency.sln
- main/tests/test-projects/ImportCircularDependency/SecondImport.targets
If project has an import which caused a circular dependency a
stackoverflow exception would be thrown. Circular dependencies are
now detected and an error is reported to the user indicating the
problem.
Fixes VSTS #569959 - attempt to load a project with conflicting
custom SDKs results in StackOverflowException
> [Core] Detect circular dependencies between MSBuild imports

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreMSBuildProjectTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreMSBuildProject.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProject.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildPropertyGroup.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/DotNetCoreProjectTests.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/MSBuildProjectTests.cs
- main/tests/test-projects/DotNetCoreNoMainPropertyGroup/Directory.Build.props
- main/tests/test-projects/DotNetCoreNoMainPropertyGroup/DotNetCoreNoMainPropertyGroup.sln
- main/tests/test-projects/DotNetCoreNoMainPropertyGroup/DotNetCoreNoMainPropertyGroup/DotNetCoreNoMainPropertyGroup.csproj
- main/tests/test-projects/DotNetCoreNoMainPropertyGroup/DotNetCoreNoMainPropertyGroup/Program.cs
Handle the missing main property group when loading and saving a
project. Previously a null reference would occur in several places
on loading.
Fixes VSTS #567738 - NullReferenceException loading sdk-style project
with no TargetFramework
> [Core] Allow loading of SDK style projects without TargetFramework  

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.Helpers/RestoreTestBase.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.csproj
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/DotNetCoreRestoreTests.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/UpdateXamarinFormsBuildTest.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/DotNetProjectProxy.cs
- main/tests/test-projects/DotNetCoreFSharpCore45/DotNetCoreFSharpCore45.fsproj
- main/tests/test-projects/DotNetCoreFSharpCore45/DotNetCoreFSharpCore45.sln
Creating a F# .NET Core console project, then installing FSharp.Core
4.5.0, would result in FSharp.Core 4.3.4 being used and displayed
in the Dependencies folder. FSharp.Core 4.3.4 is the NuGet package
implicitly added by the F# .NET Core SDK and was being used by
the project instead of the PackageReference in the project.
PackageReferences in the project will now override any implicitly
added NuGet packages which is the behaviour of dotnet restore on
the command line.
Fixes VSTS #636604 - Adding FSharp.Core 4.5.0 NuGet package restores
4.3.4 in .NET Core project
> [NuGet] Fix wrong FSharp.Core NuGet package restored

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs
With an unsaved file open in the text editor, running the project
would not trigger a build after the file was saved. The problem
was that the file watcher file change event happened after the
FastCheckNeedsBuild was checked so no build occurred. To fix this
the Document now uses the FileService.NotifyFileChanged to force
a file notification to occur on saving the file so the
FastCheckNeedsBuild is updated before checking if a build is needed.
> [Ide] Fix build not being done when file is unsaved

- main/src/addins/MacPlatform/MacTelemetryDetails.cs
Wrap GetLoginTime and related code in a try catch so that if there's an issue
the details still get set up correctly
Fixes VSTS #637410
FIxes VSTS #637958
> [Telemetry] Protect the GetLoginTime

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpBinding.addin.xml
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Extensions/FileTypeCondition.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/ExtensibleTreeView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/ProjectPadContextMenu.addin.xml
Allow FileType conditions on the solution tree context menu, and use this to limit F# commands to F# files.
> Solution context filetype condition

- main/src/core/MonoDevelop.Core/MonoDevelop.Core/LoggingService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices/MonoDevelopErrorReportingService.cs
Fixes #5170 - Show stack trace in exception bar does not show display any information
> [Roslyn] Fix show stacktrace not showing the exception

- main/src/core/MonoDevelop.Core/MonoDevelop.Core/LoggingService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices/MonoDevelopErrorReportingService.cs
Backport of #5199.
Fixes #5170 - Show stack trace in exception bar does not show display any information
/cc @slluis
> [release-7.6] [Roslyn] Fix show stacktrace not showing the exception

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputTreeCellView.cs
Steps to reproduce:
1. Build a solution and open Build Output tab;
2. Navigate to a tree summary and hover Errors or Warnings indicator. You will see an inconsistent cursor on hover. Indicators are links so interaction needs to be the same as with path links.
Fixes Bug #619943
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/619943
> [StructuredBuildOutput] Fixes Summary Links Cursor Display

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/Projection/Projection.cs
input
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/627039
Can't reproduce the issue however that patch ensures that the edit
operation in the main buffer works - a projection buffer could not be
updated but will be corrected on the next parse event.
> Fixes Bug 627039: Editor occasionally becomes unresponsive to user

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DocumentRegistry.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Editor/DocumentReloadTests.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Tests.csproj
Right clicking a MyClass definition, selecting Refactoring - Rename,
specifying a new name for the class and opting in to rename the file
at the same time would result in the text editor showing a message
indicating the file has changed outside the IDE and allows the file
to be reloaded.
The problem was that the refactoring renames the file and changes
the last saved date of the file. When the rename occurs the file
watcher generates a change event for the new file and the last saved
time of the document was not updated in the DocumentRegistry so the
text editor believed the file had been changed outside the IDE. To
handle this when the document's filename has been changed the last
saved date is updated in the DocumentRegistry since a rename could
affect this date.
Fixes VSTS #637706 - …
> [Ide] Fix renaming a class asks to reload the file

- main/src/core/MonoDevelop.Core/MonoDevelop.Core/FileService.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core/Runtime.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/PlatformService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/LocalizationService.cs
Needs mono-addins change.
- AddinManager has a new AddinAssembliesLoaded event which is logged in debug mode.
- Fixes VSTS #640897 - Mime Types loaded on startup
- Fixes VSTS #640899 - FileService loads file system extensions on startup
- Fixes VSTS #641263 - LocationService loads addins on startup
- Fixes VSTS #591639 - Log addin load stacktraces to have a baseline of where an addin is loaded
With the above changes addins are still being loaded by the CommandManager (due to string translations), pad NodeBuilders and startup handlers. So startup is doing less but the addin assemblies are still being loaded.
> [Ide] Addin startup logging and lazy loading

- main/tests/Ide.Tests/MonoDevelop.Ide.Editor/DocumentReloadTests.cs
The new DocumentReloadTests class added was not disposing the
Document it created which could cause tests to fail.
> [Ide.Tests] Ensure Document is disposed

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopAddMetadataReferenceCodeActionOperationFactoryWorkspaceService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
AddMissingReferenceCodeAction uses a specialized service in the case
of system assemblies.
For other cases file & project references the workspace is queried
directly.
> Fixes issue #5246 Add Reference quick fix does not add a reference The

- main/src/addins/PerformanceDiagnostics/PerformanceDiagnostics/Commands.cs
- main/src/addins/PerformanceDiagnostics/PerformanceDiagnostics/Properties/PerformanceDiagnostics.addin.xml
- main/src/addins/PerformanceDiagnostics/PerformanceDiagnostics/UIThreadMonitor.cs
- main/src/addins/PerformanceDiagnostics/UIThreadMonitorDaemon/Program.cs
The UI thread monitor console application now has a way to check for
the IDE's UI thread hanging without profiling the process. It will
create a file to indicate a hang is occurring. This file will be
used by the IDE when reporting the previous shutdown reason.
Needs md-addins changes.
Fixes VSTS #619945
Not implemented:
> [PerformanceDiagnostics] Add UI hang detection for telemetry

- main/src/addins/PerformanceDiagnostics/PerformanceDiagnostics/Commands.cs
- main/src/addins/PerformanceDiagnostics/PerformanceDiagnostics/Properties/PerformanceDiagnostics.addin.xml
- main/src/addins/PerformanceDiagnostics/PerformanceDiagnostics/UIThreadMonitor.cs
- main/src/addins/PerformanceDiagnostics/UIThreadMonitorDaemon/Program.cs
The UI thread monitor console application now has a way to check for
the IDE's UI thread hanging without profiling the process. It will
create a file to indicate a hang is occurring. This file will be
used by the IDE when reporting the previous shutdown reason.
Needs md-addins changes.
Fixes VSTS #619945
> [release-7.6] Add UI hang detection for telemetry

- main/src/addins/GnomePlatform/GnomePlatform.cs
Konsole no longer supports the --caption argument, remove it entirely as there is no replacement.
Stops "Cannot connect to the debugger" errors under KDE.
Fixes #4627
> Remove --caption from KdeTerminalRunner

- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Instrumentation/TimerCounter.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Core/InstrumentationTests.cs
If a new CounterMetadata is created and it is a value type, by querying
the property without setting it first, we would crash because
Convert.ToType does not handle that scenario
> [Instrumentation] Fix possible crash when converting null to value type

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildFileFormatException.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProject.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/MSBuildProjectTests.cs
Include the filename in the error message when a project or an
imported MSBuild project cannot be loaded. This will help locate the
problem. If there is invalid xml, for example, previously you would
see an error about the xml being invalid but there would be no
information about what file has the invalid xml.
Fixes VSTS #640783 - Failure while evaluating MSBuild project
Before:
After:
In the above screenshots the project filename is displayed. Here you could say that the information is not required in this case since the project file has the error. However if the project is in an imported MSBuild project file somewhere else, say Xamarin.iOS.targets, the error message would indicate which file needs to be looked at.
> [Core] Improve error information on project load failure

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlService.cs
See individual commits. Prevents bricking of IDE that happens due to exception propagation from VersionControlService into users.
> [VCS] Fix exception propagation from VersionControlService

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/StatusView.cs
The fix is two fold, once the current info needed to be passed
to the command update handlers used by the context menu.
Then, there was a bug surrounding select all and clicking in the tree,
which would make nodes in the tree unselectable.
Fixes VSTS #621178 - [Feedback] Source Control selection in "Tools -> Options -> Source Control" is lost when opening context menu.
> [VCS] Fix Review and Commit selection persisting through context menu

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/SyntaxHighlightingService.cs
- main/src/core/MonoDevelop.TextEditor.Tests/Mono.TextEditor.Tests/SyntaxHighlightingTests.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Editor/SyntaxHighlightingTest_TextMate.cs
When quickly scanning the TextMate Json file for fileTypes, properly parse the file type regardless whether it starts with a dot or not.
Fix VSTS 642869
> Fix syntax highlighting not showing for some languages (TypeScript).

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/SyntaxHighlightingService.cs
- main/src/core/MonoDevelop.TextEditor.Tests/Mono.TextEditor.Tests/SyntaxHighlightingTests.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Editor/SyntaxHighlightingTest_TextMate.cs
Backport of #5291.
Fixes VSTS 642869
/cc @slluis
> [release-7.6] Fix syntax highlighting not showing for some languages (TypeScript).

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Composition/CompositionManager.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/PlatformService.cs
This API is useful for cases where you want to lazily query a service which you use later on.
> Surface lazy methods for CompositionManager

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Features/GotoDefinition/GotoDefinitionService.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Navigation/Counters.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Navigation/FindDerivedSymbolsHandler.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Navigation/FindExtensionMethodsHandler.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Navigation/FindImplementingMembersHandler.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Navigation/FindMemberOverloadsHandler.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Refactoring/FindReferencesHandler.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Refactoring/GotoBaseDeclarationHandler.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/BackgroundPackageActionRunnerTests.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/TestableInstrumentationService.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageManagementInstrumentationService.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/RefactoringService.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextEditorKeyPressTimings.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/Counters.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/Repository.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Instrumentation/Counter.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Instrumentation/TimeCounter.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Instrumentation/TimerCounter.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectService.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionItem.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/CompletionStatistics.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/MicrosoftTemplateEngineProjectTemplatingProvider.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/ProjectTemplate.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Ide.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/RootWorkspace.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Services.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Core/InstrumentationTests.cs
Use CounterMetadata subclasses so that metadata properties aren't reduced to
strings and will be placed into the correct property or measures bag
Fixes VSTS #633544
> [Telemetry] Use CounterMetadata subclasses

- main/tests/StressTest/StressTest.csproj
Revert some of the changes made in c1bf0a04fceb68ce5c8e9942cbe2ee7465f272ff
so the StressTest solution can be compiled on its own. The build was
failing due the OutputPath not being defined for the project.
> [StressTest] Fix build

- main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/MonoDevelopContainedDocument.cs
Fix VSTS 585147
Code in TryGetWhitespaceGroup() didn't take tab characters `\t` into account.
> Fix VSTS 585147: Code in indented @{} block jumps up a line when committed

- main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/MonoDevelopContainedDocument.cs
> [release-7.6] Fix VSTS 585147: Code in indented @{} block jumps up a line when committed

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.AnalysisCore/Gui/AnalysisOptionsPanel.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices.Options/RoslynPreferences.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.RoslynServices.Options/FullSolutionAnalysisTests.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Tests.csproj
This might improve CPU consumptions while loading the roslyn project.
This is disabled by default for C# in VSWindows, so we should do the same.
Fixes VSTS #643384 - Roslyn Closed File Diagnostic is toggled on by default for C#
> [Roslyn] Disable ClosedFileDiagnostic for C# by default

- main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/MonoDevelopContainedDocument.cs
This doesn't fix any bug, just something to be consistent with the Windows original of this source code.
See https://github.com/dotnet/roslyn/pull/28268.
We don't need this in release-7.6.
> Use the proper new line setting from the editor.

- main/src/addins/MonoDevelop.UnitTesting.NUnit/NUnit3Runner/NUnit3Runner.csproj
The NUnit3 test runner was being created with the filename:
NUnit3Runner.exe instead of NUnitRunner.exe so the IDE test runner
would fail to start this process. Changed the assembly name to
NUnitRunner.
Fixes VSTS #645844 - NUnit 3 integration broken because of misnamed
runner
> [NUnit] Fix NUnit3 test runner name

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Gui/DotNetCoreRuntimeOptionsPanelWidget.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Commands/RestorePackagesInProjectHandler.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/ProjectTargetFrameworkMonitorTests.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageManagementServices.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/ProjectTargetFrameworkChangedEventArgs.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/ProjectTargetFrameworkMonitor.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/RestoreNuGetPackagesInNuGetIntegratedProject.cs
Changing the target framework of a .NET Core project in project
options would not trigger a NuGet package restore. After doing this
if the project file was edited in the text editor and saved the
packages would not be restored. This was because the file watcher
integration changed the logic around file reloads. The .NET Core addin
was setting the Project.NeedsReload flag to true and then calling
FileService.NotifyFileChanged to force a file reload of the project.
This no longer works since the file watcher is not responsible for
triggering the reload based on file events that happen outside the
IDE. To force a reload in the IDE there are Reload methods available
on the Project itself. To solve this problem this old logic has been
removed and now when the target framework of the project is …
> [DotNetCore] Fix project not restored on target framework being changed

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/MSBuildOutputProcessor.cs
Backport of #5377.
/cc @rodrmoya
> [release-7.6] [BuildOutput] Use Array.IndexOf instead of LINQ\u0027s .Contains

- main/src/addins/CSharpBinding/CSharpBinding.addin.xml
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.addin.xml
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.addin.xml
- main/src/core/MonoDevelop.Ide/ExtensionModel/MonoDevelop.Ide.addin.xml
There were two legacy extension points: MefHostServices and PlatformMefHostServices. There is no need to differentiate.
I will remove the two legacy extension points in 16.0 after we make sure nobody external uses them.
> Unify on MonoDevelop/Ide/Composition extension point.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Composition/CompositionManager.Caching.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Composition/CompositionManager.CachingTests.cs
Fixes a crash that happened on my machine because for some reason the MEF cache control deserialized as null. Guessing it was because of a format change?
> Fix crash in MEF cache deserialization

- main/src/addins/MonoDevelop.SourceEditor2/VSEditor/.editorconfig
It's important to preserve the original formatting of the VS codebase, so it's easier to sync sources back and forth.
> Add an .editorconfig to the VSEditor folder

- main/src/addins/MacPlatform/Dialogs/MacAlertDialogHandler.cs
VSTS issue:
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/632539?src=alerts&src-action=cta
Related PR in md-addins:
https://github.com/xamarin/md-addins/pull/3330
Related PR in maciostools:
https://github.com/xamarin/maciostools/pull/133
For example, here we show a clickable link and instead of plain markdown (<a href='...'>...</a>):
> Fixes VSTS: 632539 - Allow native mac dialogs to render formatted strings

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/IdeTheme.cs
With HighSierra [NSNotificationCenter observer handling has been
redeisgned](https://developer.apple.com/library/archive/releasenotes/Foundation/RN-Foundation/index.html#10_11NotificationCenter) and now observers are removed automatically during finalization.
However the actual NSWindow.WillCloseNotification might be raised
after the window has been finalized and removing the observer manually
would result in a hard native crash, hence we need to treat
window closed winows differently depending on the macOS version.
> [Ide][Mac] Fix closed window handling in IdeTheme

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.UnitTests/UnitTestTextEditorExtension.cs
- main/src/addins/MonoDevelop.UnitTesting.NUnit/MonoDevelopNUnit.addin.xml
- main/src/addins/MonoDevelop.UnitTesting/Services/AbstractUnitTestEditorExtension.cs
- main/src/addins/MonoDevelop.UnitTesting/Services/UnitTestMarkersExtension.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding/UnitTesteditorIntegrationTests.cs
the text editor. No dot next to it.
TODO: Merge interfaces in the next AP break.
> Fixes issue #3869 "[TestCaseSource ("xzy")]" isn't seen as a test in

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputNode.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputTreeCellView.cs
This PR fixes rendendering in diagnostic and normal mode
Removed the old format in diagnostic 00:02.748 to use
2.341s rounding 1 decimal in case de normal and 3 decimal
in case of diagnostic.
Example: 0.94 displays as 0.9, 0.95 displays as 1.0
Before | After
------------ | -------------
00:00.001 | .001s
00:02.341 | 2.341s
1:50.211 | 1m 50.001s
Fixes Bug #636828
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/636828
Fixes Bug #636830
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/636830
> [StructuredOutput] Fixes rounding rendering duration time

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputTreeCellView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputWidget.cs
This improves the current code selecting characters in structured build output, fixing the issue selecting last character and encapsulating some code related to selection in a reusable agnostic class [TextSelectionManager](https://github.com/mono/monodevelop/blob/e22993eb6eee3deca8cf3de5215532d414b3e37c/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputTreeCellView.cs#L117-L187).
Fixes Bug #603558
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/603558
> [StructuredOutput] Fixes select last character in node title

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/Tag.cs
In cases where todo comments didn't have a colon,
we'd log an exception
Fixes VSTS #645581 [Feedback] TODO comments stopped working in latest beta
> [TODO] Fix todo comments not showing up in some cases

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/CheckoutCommand.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlService.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlTask.cs
This was a race condition. the UI lock-up would happen when dispose
would finish before the EndTask did.
The reason here is that the Dispose() method on ProgressMonitor
does not take into account the monitor's synchronization context.
See https://github.com/mono/monodevelop/issues/4751
Second attempt at:
Fixes VSTS #641132 - [Feedback] Visual Studio Mac checkout functionality freezes entire program
Fixes VSTS #619788 - Error when cloning new Git repository locks IDE main menu
> [VCS] Fixup more UI thread semantics and make Wakeup use the UI context

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/EditorConfigService.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Editor/EditorConfigTests.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Tests.csproj
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/643536
The real issue here was that the editor config tests got broken and a
break was unrecognized.
> Fixes VSTS Bug 643536: XAML & .EditorConfig issues

- main/src/addins/MacPlatform/Dialogs/MacAlertDialogHandler.cs
This PR fixes alert parent handling if the parent is a native (non Gtk) window, `GtkQuartz.FocusWindow(Gtk.Window)` fails in this case.
> [Ide][Mac] Fix parent window handling in MacAlertDialogHandler

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/ExtensibleTextEditor.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Actions/SelectionActions.cs
This is a follow-up to https://github.com/mono/monodevelop/pull/5083
That PR fixed the issue when holding shift and pressing an arrow key
to change the selection when a multi-key language such as Korean is
being used, but the issue persists when changing the selection in
other ways. For example, Cmd-Shift-Left arrow key will cause the
selection to move back as expected, but it will drop the last character
of the selection (and then when you unselect the buffer will be
broken in totally unexpected ways).
This PR committs the preedit for the necessary action, plus all other
selection actions to be on the safe side.
Fixes VSTS #635558
> [Editor] Ensure preedit committed before all selections actions

- main/src/addins/CSharpBinding/MonoDevelop.CSharp/CSharpNavigationTextEditorExtension.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/AbstractNavigationExtension.cs
mouse Fixes issue #4389 Cmd-click navigation sometimes gets stuck
Improved the reliablility of teh cmd navigation. There were duplicate
hover segments and some possible issues with the event system that may
have caused #4389.
> Fixes issue #4390 Cmd does not light up navigation for symbol under

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/MdTextViewLineCollection.MdTextViewLine.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/MdTextViewLineCollection.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/MonoTextEditor.ITextView.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/ExtensibleTextEditor.cs
In theory we could switch to all vs.net editor operations however
we've many mac behavior commands built in so we would break some mac
specific behavior. But it's ok for ctrl+left/right there are no mac
specifics here.
> Fixes issue #4110 Inconvenient behavior of Ctrl+Right and Ctrl+Left

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CompletionProvider/RegexCompletionProvider.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/Features/Completion/RegexCompletionProviderTests.cs
The tests tested the wrong thing verbatim <--> non verbatim cases were
swapped.
> Fixes issue #5489 C# completion improperly escapes \ within @ strings

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.SolutionItemBuildBatch.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
Creating a new project and then running it does not build the
project first. There was a change made to the ProjectOperations
around building which is relying on the project model implementing
GetExecutionDependencies. This has not been implemented anywhere
in the code. So nothing was being built. The use of
GetExecutionDependencies has removed for now so projects are
compiled.
Fixes VSTS #652873 - Outdated Build dialog is no longer displayed
> [Ide] Fix no build on running a project

- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/TemplateTests.fs
- main/src/addins/MonoDevelop.Packaging/MonoDevelop.Packaging.Tests/MonoDevelop.Packaging.Tests/AddPlatformImplementationTests.cs
- main/src/addins/MonoDevelop.Packaging/MonoDevelop.Packaging.Tests/MonoDevelop.Packaging.Tests/ProjectTemplateTests.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/ISolutionItemDescriptor.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/ProjectDescriptor.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/ProjectTemplate.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/ProjectTemplatingProvider.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/SingleFileDescriptionTemplate.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/SolutionDescriptor.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/SolutionItemDescriptor.cs
- main/tests/Ide.Tests/ProjectTemplateTests.cs
Creating a Xamarin.Mac project inside a directory with other existing
projects could cause the project to be created without any files added
to the project but the files were created on disk.
The problem is that the ProjectDescriptor.InitializeItem method was
an async void method and when the Info.plist was created it called
into the EditorConfigService.GetEditorConfigContext when then called
codingConventionsManager.GetConventionContextAsync which presumably
was using a Task.Run in certain cases. This meant the UI thread was
unblocked and New Project dialog would then save the project before
all the files were created. Resulting in the files not being added
to the project file.
To fix this the InitializeItem method now returns a Task that is
awaited. One problem here that is not fixed is …
> [Ide] Fix no files added to new project 

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/ProjectTemplate.cs
The language name for a NuGet packaging project is not set, since
it does not have a language. This was causing a null reference
exception to be logged by the telemetry when it attempted to call
ToString() on the value.
Fixes VSTS #655218 - Null reference exception logged on creating a
NuGet packaging project
> [Ide] Fix null ref logged by telemetry when creating NuGet project

- main/src/addins/PerformanceDiagnostics/PerformanceDiagnostics/UIThreadMonitor.cs
The UI thread hang console app was being started without quoting
the path to the executable so it was failing to start when inside
a path with a space, such as from within the 'Visual Studio.app'
bundle.
Fixes VSTS #655338 - Exception on quit
> [PerformanceDiagnostics] Fix UI thread hang app not starting

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Ide.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
Showing the welcome page delays loading the IDE (querying the welcome page
service and so on).
Fixes VSTS #652347 - Welcome page should not show when loading a solution from finder
Still working on the UX, trying to get the welcome page to show while the workspace is loading, but also trying to prevent a race.
> [Ide] Don't show welcome page when opening a specific item

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/SdiWorkspaceWindow.cs
With unsaved changes in the text editor, and the IDE crashes, on
re-starting the IDE, and opening the solution containing the file
that was unsaved, the editor was not showing the 'An autosave file
has been found for this file' message in the text editor. Instead the
text editor was showing a message saying that the file had been
changed outside the IDE. The Keep Changes button if clicked would
result in an empty file in the text editor and the file changes
would be lost.
The problem was that on loading the file with an associated autosave
file the last write time was being updated which caused the file
watcher to raise a file changed event. This then caused the
autosave message to be replaced with the file has been changed
outside the IDE message. The SdiWorkspaceWindow's SetTitleEvent …
> [Ide] Fix autosave not loading autosaved file

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/MdTextViewLineCollection.MdTextViewLine.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/MdTextViewLineCollection.cs
Fix VSTS 645599 (ArgumentOutOfRange in Razor)
Update MdTextViewLineCollection to the latest editor Snapshot when buffer changes. We've had a number of issues in TagBasedSyntaxHighlighting where some lines were partially translated to the latest snapshot, but created a discrepancy because a SnapshotSpan would be tracked to latest, but a DocumentLine wouldn't get translated.
Now we re-add the lines we want to reuse against the latest snapshot, and the changed lines would be added later by the layout engine.
Removing the incorrect fix to translate lines as it didn't properly translate the DocumentLine of an MdTextViewLine.
> Fix VSTS 656752 (Classification doesn't update)

- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/CaretImpl.ITextCaret.cs
Our ITextCaret.ContainingTextViewLine implementation was wrong, it was taking a virtual position, not buffer position, returning null.
Separate issue: when we were in virtual space, and the editor was set to Tabs, the col calculation was incorrect. Didn't divide by TabSize and increment by 1.
> Fix VSTS 645707: HTML tag smart indent doesn't work with Tabs

- main/src/core/MonoDevelop.Startup/app.config
Looks like we ship 1.1.28.0 in the app bundle, but some .dlls reference a smaller version.
> Add binding redirect for Microsoft.Diagnostics.Tracing.EventSource.dll.

- main/msbuild/MonoDevelop.BeforeCommon.targets
This allows us to use newer features like default literal,
new valuetype ref semantics, private protected, stackalloc arrays
> Always set the LangVersion to latest for C#

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeTemplates/MonoDevelop-templates.xml
templates don't make much sense they contain ')' and that's why they
may interfere with the closing char ')'.
> Fixes issue #5521 Code completion incorrectly inserts code These

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextEditor.cs
Fixes VSTS #657369 - EditorConfig context is queried even for files which will not use it
> [Editor] Simplify editor config context querying a bit

- main/src/addins/MonoDevelop.Packaging/MonoDevelop.Packaging.Tests/MonoDevelop.Packaging.Tests/ProjectTemplateTests.cs
https://github.com/mono/monodevelop/issues/5602 tracks fixing and reenabling.
> Disable failing test: CreateMultiPlatformProjectFromTemplateWithPCLOnly

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.PickMembersService/PickMembersDialog.cs
override for a class window doesn't render options correctly
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/659996
Can't reproduce what's seen in the screenshot howover this test case
fails for me which is fixed by that patch.
> Fixes VSTS Bug 659996: [Feedback] VS Mac 2017 - Pick members to

- main/src/core/MonoDevelop.Ide/Gui/MonoDevelop.Ide.Gui.OptionPanels.BuildPanelWidget.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.OptionPanels/BuildPanel.cs
This was removed because structured build output was going to be the
only way to view the output, and it needed diagnostics build always, but
that adds some problems with the old build output on large projects,
which make the output be truncated, so quite useless.
Fixes https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/645913
> [Ide] Add "log verbosity" setting back

- main/src/addins/CSharpBinding/CSharpBinding.csproj
- main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/ExtensionMethods.cs
- main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/MonoDevelopContainedDocument.cs
- main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/RoslynCompletionPresenterSession.View.cs
The first call may fail with the ArgumentException coming from Mono due to ConditionalWeakTable
reentrancy, however by that time the table will have already been populated.
Subsequent call should not hit this problem and should succeed.
TODO: remove when https://github.com/dotnet/roslyn/issues/28256 is fixed.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/662639.
> Temp workaround for VSTS 662639.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
When building for a multi-project run config, only build the executing projects, not the whole solution.
> Only build executing projects

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/TypeSystemService.cs
- main/tests/Ide.Tests/MonoDevelop.Ide/TypeSystemServiceTests.cs
If a parser takes a long time to parse a project this can result in
out of date information being used by the type system. Now a check
is made to see if the token was cancelled and the parsed projection
is ignored in this case.
Also added a TypeSystemService test for the projection being cancelled.
Partial fix for VSTS #663898 - Failing Xamarin.Forms tests
> [Ide] Prevent out of date projections being used

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads/ErrorListPad.cs
Since we're not creating the button now, unsubscribing an event from
it just makes the app crash, so disable this code also.
> [Ide] Disable some more code for new build output

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/ProjectDescriptor.cs
- main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.MSBuild/ProjectBuilder.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/ProjectBuildTests.cs
- main/tests/test-projects/ImportedOutputPathProperty/ImportedOutputPathProperty.csproj
- main/tests/test-projects/ImportedOutputPathProperty/ImportedOutputPathProperty.props
- main/tests/test-projects/ImportedOutputPathProperty/ImportedOutputPathProperty.sln
- main/tests/test-projects/ImportedOutputPathProperty/ImportedPlatformOutputPathProperty.csproj
- main/tests/test-projects/ImportedOutputPathProperty/ImportedPlatformOutputPathProperty.props
- main/tests/test-projects/ImportedOutputPathProperty/ImportedPlatformOutputPathProperty.sln
- main/tests/test-projects/ImportedOutputPathProperty/MyClass.cs
- main/tests/test-projects/ImportedOutputPathProperty/Properties/AssemblyInfo.cs
With a project that has an import that defines a property based on
the configuration the build location of the assembly would be
incorrect.
Project file:
<Project ...>
<Import Project="Imported.props" />
<PropertyGroup>
<Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
<Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
<OutputPath>$(OutputBase)\Common</OutputPath>
</PropertyGroup>
Imported.props:
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
<PropertyGroup>
<TargetDir>target</TargetDir>
<OutputBase>$([System.IO.Path]::Combine($(TargetDir), $(Configuration)))</OutputBase>
</PropertyGroup>
</Project>
When building the above project, with the debug configuration
selected, the assembly would be built into the …
> [Core] Fix incorrect build location with imported config based property

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
With "Run project if build completed with warnings" set to true in
Preferences a project would not be run if the build had warnings.
The preferences setting had the opposite effect since it was being
treated as though it indicated the run should be cancelled when it
was true.
Fixes VSTS #667156 - [VSM] Project is not built and started to run
after Toolbar -> Run hit
> [Ide] Fix project not being run when it has warnings

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.DocumentMap.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.MetadataReferenceHandler.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.OpenDocumentsData.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.ProjectData.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.ProjectDataMap.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.ProjectSystemHandler.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.ProjectionData.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.Shims.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/TypeSystemService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
- main/tests/Ide.Tests/MonoDevelop.Ide.Tests.csproj
- main/tests/Ide.Tests/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspaceDocumentMapTests.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspaceOpenDocumentDataTests.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspaceProjectDataMapTests.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspaceProjectDataTests.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspaceProjectionDataTests.cs
This splits functionality in MDWorkspace into logical components and makes them testable.
TODO:
> Refactor MonoDevelopWorkspace into logical components

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/TypeSystemService.cs
If a parser takes a long time to parse a project this can result in
out of date information being used by the type system. Now a check
is made to see if the token was cancelled and the parsed projection
is ignored in this case.
Partial fix for VSTS #663898 - Failing Xamarin.Forms tests
> [release-7.6][Ide] Prevent out of date projections being used

- main/src/core/MonoDevelop.Ide/ExtensionModel/MimeTypes.addin.xml
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/SyntaxHighlighting.cs
- main/src/core/MonoDevelop.TextEditor.Tests/Mono.TextEditor.Tests/SyntaxHighlightingTests.cs
highlighting errors
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/665407
Was caused by an isanity check to prevent infinite loops.
Unfortunately it's not so easy to determine state changes that way in
complex grammars. However there is another one implemented : timeouts.
That's enough to prevent infinite loops so this is not really needed
anymore.
> Fixes VSTS Bug 665407: TypeScript/JavaScript TextMate syntax

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/SearchResult.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/SearchResultWidget.cs
Solution" results, UI delays and unresponsiveness
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/650534
The old implementation created a huge number of text editor objects
which is not efficient anymore. Instead now one text editor object is
re-used. However the search result data is cached querying the text
editor is expensive.
> Fixes VSTS Bug 650534: [Feedback] High CPU usage viewing "Search in

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpTextPasteHandler.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeActionEditorExtension.cs
code from docs sample
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/669030
Without beeing able to reprodue the issue I can only guard against the
span out of range case. Getting no refactorings at a position
shouldn't produce visible crashes.
> Fixes vsts Bug 669030: [Feedback] VSMac 7.6 UI Blitz after pasting c#

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Tasks/CommentTasksProvider.cs
When notifying about comment tasks changes, some cached
tasks might have become invalid. Let the CommentTasksProvider
skip tasks with invalid document or project,
resulting in a null CommentTaskChange.
Fixes VSTS #670781
> [Ide] Fix NRE in CommentTasksView

- main/src/core/MonoDevelop.Core/MonoDevelop.Core/Properties.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Core.Tests.csproj
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Core/PropertyTests.cs
Backport of #5762
If the property value was a Properties instance then the values
would not be saved if the original property did not exist in the
saved properties file. This was because the Properties class was
checking the property values against its list of default values and
not serializing them if there is a match. This check did not work
for values which are Properties since they are the default value
if the property did not originally exist. This resulted in the
value not being saved.
Changed the code to special case Properties being used as a value so
a check is made to see if it contains only default values instead
of not being saved.
Fixes VSTS #669533 - Editor font settings cannot be saved.
> [release-7.6][Core] Fix properties not being saved.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.ProjectSystemHandler.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/TypeSystemService_WorkspaceHandling.cs
- main/tests/Ide.Tests/MonoDevelop.Ide/TypeSystemServiceTests.cs
- Fixes type system not reloading solution when project modified
- Fixes text editor errors on adding .NET Core project to solution
- Fix text editor errors after creating new .NET Core project
Occasionally on creating a new .NET Core project the text editor
would show errors such as "Predefined type 'System.Object' is not
defined or imported." as though the project had no references. This
can also happen on adding a new .NET Core project to an existing
solution. Both of these seem to be caused by the type system being
out of sync since it did not always process project modify events
when they occurred.
Fixes VSTS #635423 - Error after creating new .NET Core project
> [Ide] Fix text editor errors after creating new .NET Core project

- main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.MSBuild/BuildEngine.cs
This disables binlog writing, as mono has a bug in deflatestream causing the builder to crash on finalization.
https://github.com/mono/mono/issues/9142
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/669032, but I've been unable to reliably repro it.
> [MSBuild] Disable binlog writing in 7.6

- main/src/addins/MonoDevelop.AspNetCore/Properties/MonoDevelop.AspNetCore.addin.xml
Change the order of the project templates to match Visual Studio 2017
on Windows.
From:
ASP.NET Core Empty
ASP.NET Core Web App (MVC)
ASP.NET Core Web API
ASP.NET Core Web App
To:
ASP.NET Core Empty
ASP.NET Core Web API
ASP.NET Core Web App
ASP.NET Core Web App (MVC)
Fixes VSTS #671649 - Update ordering of projects in New Project to
match ordering in VS2017
> [AspNetCore] Change project template order in New Project dialog

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/MdTextViewLineCollection.MdTextViewLine.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/MdTextViewLineCollection.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/MonoTextEditor.ITextView.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/CaretImpl.ITextCaret.cs
Fix VSTS 657666 (HTML: ArgumentOutOfRange when inserting new line between `<div>` and `</div>`)
There was a window after a buffer change where we didn't reuse any of the text view lines, so the text view line collection was empty. At that time someone was getting the line the caret was on, resulting in an argument out of range. We now check for that situation by inserting a line on demand when it is requested.
In VS the ITextView.GetTextViewLineContainingBufferPosition() always returns a text view line for a given position (as long as the requested position is on the current snapshot). In our world we were returning null in a lot of situations.
Synchronize the MultiSelectionBroker with Caret.
In VS Editor 15.8 the MultiSelectionBroker is the single source of truth about carets and …
> Fix VSTS 657666 (HTML: ArgumentOutOfRange when inserting new line between <div> and </div>)

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/CompletionWindowManager.cs
It is used by WebTools.
Longer term there's the bug tracking figuring out whether we can get rid of this, but for now we need this back: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/673887
> Bring back CompletionWindowManager.WordCompleted event

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/SyntaxHighlightingService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/VSCodeImport/xml/syntaxes/xaml.json
In 7.6 some logic was changed in SyntaxHighligthingService.cs to do `return name != null && scopeName != null;`(before it just returned `true`) since `xaml.json` has `scopeName` on 2nd line it failed... Hence now we read for new format also 1st and 2nd line.
Also some logic around regex changed so I made few changes to xaml.json to support new regex rules.
> Fix 668995: [Feedback] Xaml Syntax Highlighting Has Reverted in 7.6 (2190)

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpIndentationTracker.cs
We had a first-chance MEF composition exception because we were expecting a single ISmartIndentProvider, but getting 5 instead. The right way to do this is to get an ISmartIndentationService and use that instead. This service will aggregate various ISmartIndentProviders and use the right one for the right view.
There were some editor problems because of this - smart indent not working, etc.
> Fix usage of ISmartIndent MEF component.

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/MonoTextEditor.ITextView.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/CaretImpl.ITextCaret.cs
There was a problem in the logic where we synchronized the caret with the latest position of the MultiSelectionBroker.
We should first set the caret to the new position, then synchronize the MultiSelectionBroker to it. The ordering was wrong, causing smart indent not working.
> Fix VSTS 674296 - fix sync with MultiSelectionBroker.

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeActionEditorExtension.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeFixMenuService.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/QuickFixMenuHandler.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/MDMenuItem.cs
text is generated by roslyn but it's possible to add a header item for
the fix all items. OTOH the items would become to large when using the
full title in one line.
Best solution would probably be to just move the code fixes & issues
out of the context menu to a custom popup dialog. But that's a user
impact that's beyond the scope of the bug report.
> Fixes issue #5360 Not obvious which "fix all" is which The fix all

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/CompletionController.cs
There was a special case where if the char is punctuation and the current completion list item ends in that char then it used to commit completion.
Now we detect the situation where if we're in a Json editor and the completion is one of three Json special completions " ", { } or [ ] and we press either " [ or { then we hide completion, send the char through to the editor and don't commit.
This fixes the problem because it lets Brace Completion commit the second character and lets user overtype it if they type it manually.
> Fix VSTS 634581 (triple """ in Json)

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/SearchResult.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.FindInFiles/SearchResultWidgetTests.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Tests.csproj
that contains the search term is too long.
Backport of #5845
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/676591
(cherry picked from commit d52b994728e8b9d6e7172c673ae8e82c70c6b8c7)
> [7.6] Fixes VSTS Bug 676591: Search results displayed as empty when line

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeTemplates/CodeTemplateService.cs
Previously if the user had a malformed snippet in the snippet directory we would end up not loading any snippets.
Now we tolerate a malformed snippet file, report which file is malformed and continue loading other snippets.
Also defend against other filesystem errors when reading snippets files.
> Fix VSTS 641286: make snippet loading resilient

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
When opening document/switching between documents `InformDocumentOpen` is called which calls `InternalInformDocumentOpen` 1st on documentId with correct ProjectId(by correct I mean selected project, and then other projects) which results in Roslyn setting last project(so "not correct") as editing one... Which results in wrong highlighting... VS Window uses `OnDocumentContextUpdated` to update document when switching between projects, hence to keep changes to minimal and not rely on order of opening and hope that that will do right thing, we just call `OnDocumentContextUpdated` at end of opening sequence.
> Fix #5779: [VSfM] Wrong sections visually commented out with preprocessor directives

- main/src/addins/MacPlatform/MainToolbar/AwesomeBar.cs
- main/src/addins/MacPlatform/MainToolbar/NSFocusButton.cs
- main/src/addins/MacPlatform/MainToolbar/SelectorView.cs
- main/src/addins/MacPlatform/MainToolbar/StatusBar.cs
Allow focussing action icons in the status bar with the keyboard.
> Fixes VSTS [#648188](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/648188)
> [a11y] Fix keyboard focus for statusbar action icons

- main/src/core/MonoDevelop.Ide/Gui/MonoDevelop.Ide.Projects.GtkProjectFolderPreviewWidget.cs
Tabbing on the final page of the New Project dialog would lose
the focus for one key press when tabbing from the text boxes and
check boxes on  the left hand side to the buttons at the bottom of
the page. The focus was being given to the scrolled window widget
in the folder preview. The scrolled window widget has been set to
no longer accept focus has so tabbing around the final page goes
from the text boxes/check boxes to the buttons on the bottom of the
page without losing visual indication where the focus is.
Fixes VSTS 646432 - Accessibility: Keyboard: Loss of focus is
observed in "Configure your new Audio Unit Extension" window
> [Ide] Fix focus disappearing on tab key press in New Project dialog

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopMetadataReference.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.ProjectData.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.ProjectDataMap.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.ProjectSystemHandler.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.TypeSystem/MonoDevelopMetadataReferenceManager.MetadataReferenceCacheTests.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspaceProjectDataTests.cs
[Ide] MetadataReferenceCache now removes the right snapshots
Previously, if the same metadata reference was reused between
multiple projects, we would fall in the problem of a snapshot
being updated on one metadata reference update, that means that
future metadata reference updates would try to remove the new one
from their store.
Send over the old and current snapshots to all event handler subscribers
to ensure we're removing and adding the right ones.
> VSTS #669418 - CheckProjectHasMetadataReference Exception

- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/ICustomTooltipToolboxNode.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/TextToolboxNode.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/Toolbox.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/ToolboxWidget.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.csproj
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/CodePreviewWindow.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/CodeSegmentPreviewWindow.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.QuickTasks/QuickTaskOverviewMode.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.csproj
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/ClipboardRingService.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs
Fixes #5709. Item titles are no longer ellipsized to 16 chars, and the tooltip shows a decent sized snippet.
> Improve clipboard ring display in toolbox

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopMetadataReference.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.TypeSystem/MonoDevelopMetadataReferenceManager.MetadataReferenceCacheTests.cs
Previously, if the same metadata reference was reused between
multiple projects, we would fall in the problem of a snapshot
being updated on one metadata reference update, that means that
future metadata reference updates would try to remove the new one
from their store.
Send over the old and current snapshots to all event handler subscribers
to ensure we're removing and adding the right ones.
Fixes VSTS #669418 - CheckProjectHasMetadataReference Exception
> [Ide] MetadataReferenceCache now removes the right snapshots

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/DefaultAutoInsertBracketHandler.cs
DefaultAutoInsertBracketHandler was conflicting with BraceCompletion for JS/TS.
Turn it off for JS and TS mime types to let BraceCompletion do its job.
Porting https://github.com/mono/monodevelop/pull/5911 to release-7.6.
> Fix VSTS 673077: JS: incorrect line break/smart indent on ENTER

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Refactoring/RefactoryCommands.cs
Fixes VSTS #677558 - Refactoring Contextual Menu Changes
> [C#] Move Rename command into top level contextual menu

- main/src/addins/MacPlatform/MainToolbar/RunButton.cs
- main/src/addins/MacPlatform/MainToolbar/SelectorView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbar.cs
As proposed in #4805 , this PR adds tooltips to the "Run" button and "Configuration" selectors (for Mac and Gtk) in the main toolbar. Additionally, the tooltip text is used for `AccessibilityHelp` on Mac.
Fixes issue #4805
> Add missing main toolbar tooltips

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Refactoring/RefactoryCommands.cs
Backport of #5918.
/cc @Therzok
Fixes VSTS #677558 - Refactoring Contextual Menu Changes
> [release-7.7] [C#] Move Rename command into top level contextual menu

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.UI.cs
New Project Dialog accessibility: Translate the cancel button label using `GettextCatalog` instead of using the built in Gtk translation.
> Fixes VSTS [#648956](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/648956)
> [Ide][a11y] Fix Cancel button label in new project dialog

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeTemplates/CodeTemplateService.cs
I've noticed another case when reading a corrupted/unsupported snippet would throw and lose all other snippets.
> Report an error and avoid exception when snippet version is unsupported.

- main/build/MacOSX/monostub-utils.h
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitVersionControl.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/Repository.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlService.cs
This PR aims to add a few things:
* Counter support for VCS
* Unification of the code that handles repository creation, caching instances at the version control service layer (making number of Svn repositories created match the number of Git repositories in equivalent scenarios)
* Proper reporting of the Repositories counter.
* Removing the hard dependency of Xcode for svn support, allowing a fallback to CommandLineTools version
> [VCS] Improve counter infrastructure and logic behind it

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/FilePathExtensions.cs
After this change, any existing VB.Net .Net Core Project can be loaded, it can be fully edited, built (with a user custom “dotnet build” build action) and run.
> [DotNetCore] Allow opening existing VB.Net Projects

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CompletionProvider/DelegateCompletionProvider.cs
This ensures that insertion mode is only called for the currently
opened document in the real editor and not for a preview. However the
bug described seems already to be fixed with one of the recent roslyn
updates but guarding against that case improves this code.
> Fixes issue #5813 Editor IntelliSense/Code Generation Bugs.

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpTextPasteHandler.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/Features/IndentationTests/TextPasteIndentEngineTests.cs
Backport of #6030.
/cc @mkrueger
> [release-7.7] Fixes issue #6029 Cut and paste is broken in the editor

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/LogView.cs
The cookie was set before clear was called, making it not write anything.
> [Output Pad] Fix nothing being written and monitors not being reused

- main/src/addins/MonoDevelop.Packaging/MonoDevelop.Packaging.Tests/MonoDevelop.Packaging.Tests/ProjectTemplateTests.cs
> [release-7.7] [master] Disable failing test: CreateMultiPlatformProjectFromTemplateWithPCLOnly

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/RoslynCompletionData.cs
In cases when the selected completion list item has no description we don't show anything instead of showing an empty yellow rectangle.
> Fix VSTS 611401: empty completion item description should not be shown.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutput.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputNode.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputWidget.cs
- main/tests/Ide.Tests/MonoDevelop.Ide/BuildOutputTests.cs
Fixes part of 
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/632363 by adding quite a noticeable performance improvement, which at least clearly showed where the problem is (synchronous search of the whole tree, node by node, which, on a 16.4MB .binlog, took 18 of 19 seconds for the whole operation, including several searches being started/canceled and (a single) UI refresh).
> Improve BuildOutput search's performance

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs
Need to set RootWindow.Visible to true otherwise the editor may not be focused. The symptoms for this problem are: caret is in the Editor and not blinking. Clicking in the Editor doesn't fix it. Only fix is to move focus outside the app and bring the focus back.
> [Fixes VSTS #674288](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/674288)
> Fix VSTS 674288.

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpFormattingProfileDialog.cs
for mac
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/690182
Note: Style options are in the text editor c# options and not
policies. This category was a left over from nrefactory style options.
> Fixes VSTS Bug 690182: [Feedback] sorting usings dosen't work on vs

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/RoslynCompletionData.cs
Backport of #6080.
/cc @slluis
> [release-7.7] Fix VSTS 611401: empty completion item description should not be shown.

- main/src/addins/MacPlatform/Interop.cs
- main/src/addins/MacPlatform/KernelInterop.cs
- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/addins/MacPlatform/MacPlatform.csproj
- main/src/addins/MacPlatform/MacTelemetryDetails.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/DesktopService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/PlatformMemoryStatusEventArgs.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Services.cs
This commit adds the following data into the IDE:
* Application/System compressed memory
* System minimum memory until compression/swap is being used
* Application virtual memory and free system virtual memory
The following data can be used to create thresholds through which
to decide whether the application is suffering from memory pressure
or not.
Fixes VSTS #633545 - Telemetry: research memory pressure event
> [Ide] Report virtual memory statistics on OS pressure event

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionFolder.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/FileWatcherTests.cs
- main/tests/test-projects/ProjectInSolutionFolder/ProjectInSolutionFolder.csproj
- main/tests/test-projects/ProjectInSolutionFolder/ProjectInSolutionFolder.sln
Backport of #6078
When a project inside a solution folder was modified outside the IDE
it was not reloaded. The Solution's ItemReloadRequired event was not
fired for projects inside a solution folder so the workspace was not
reloading them.
Fixes VSTS #669787 - Switching branch outside of IDE does not trigger
project reload
Fixes #6013 - Modifying .csproj file that is inside SolutionFolder
doesn't reload project
> [release-7.6][Core] Fix project in solution folder not reloaded

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpBinding.addin.xml
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateTests.cs
> FsharpBinding: uppercase F# project GUID to be consistent with VS4win

- main/src/addins/MonoDevelop.UnitTesting/Gui/TestPad.cs
- main/src/addins/MonoDevelop.UnitTesting/Services/UnitTestService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/LogView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads/DefaultMonitorPad.cs
The multiple application output window got introduced by
65c5f17f86fc77f8add6c6090aa526c2cb2a6009 that introduced that an in
progress output window can't be re used. Ending the progress on
dispose as well fixes that issue for unit tests.
> Fixes issue #6014 [Regression] Unit-tests execution

- main/src/addins/MacPlatform/MacInterop/KeyCodes.cs
- main/src/addins/MacPlatform/MacPlatform.csproj
- main/src/addins/MacPlatform/MainToolbar/MainToolbar.cs
- main/src/addins/MacPlatform/MainToolbar/RunButton.cs
- main/src/addins/MacPlatform/MainToolbar/SelectorView.cs
- main/src/addins/MacPlatform/MainToolbar/StatusBar.cs
- main/src/addins/WindowsPlatform/WindowsPlatform/MainToolbar/WPFToolbar.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/IMainToolbarView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbar.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DefaultWorkbench.cs
Correctly implement shift-tab behaviour in the selector
Correctly shift tab into the toolbar, landing on the searchbar instead of the run button
Shift tab out of the toolbar, back into the Gtk widgets.
Fix VSTS #648190
> Improve shift-tab experience in the toolbar

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
Don't null the timer until after the time has been recorded
fixes VSTS #692948
> [Telemetry] Fix null reference when opening sln from command line 7.6

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSystemInformation.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/NuGetSystemInformation.cs
- main/src/core/MonoDevelop.Ide/ExtensionModel/MonoDevelop.Ide.addin.xml
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Updater/UpdateInfo.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeVersionInfo.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProductInformationProvider.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/RuntimeVersionInfo.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/UpdateInfo.cs
Consolidating ISystemInformation, UpdateInfoExtensionNode and
IUpdateInfoGenerator into ProductInformationProvider so that we only
have one way to retrieve product information.
Fixes VSTS #664616
> Report _from_ version in addition to _to_ version

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
Use a separate timer so that the total duration is reported correctly.
Fixes VSTS #695000.
> [Telemetry] Don't reset the startup timer

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
Backport of #6164.
/cc @iainx @iainx
Description of #6164:
Use a separate timer so that the total duration is reported correctly.
Fixes VSTS #695000.
> [release-7.7] [Telemetry] Don\u0027t reset the startup timer

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpProjectFileNodeExtension.fs
Also check that drag node is not the same as drop node.
Fixes VSTS #694596
> [F#] Fix CanDropNode so that it only works within F# projects

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Commands/PackagesCommandHandler.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Commands/UpdateAllPackagesInProjectHandler.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Commands/UpdateAllPackagesInSolutionHandler.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.Helpers/FakeNuGetAwareProject.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.csproj
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/DotNetProjectExtensionsTests.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/DotNetProjectExtensions.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/SolutionExtensions.cs
The Update menu was enabled if the project used PackageReferences but
had none in the project. Without any PackageReferences in the
project there is nothing to update. The check to see if the Update
menu is enabled has been changed to make sure the project has
PackageReferences in the project file, not just imported
PackageReferences. Also extended this logic to be used by the Update
NuGet Packages menu which is used to update packages for the solution.
Fixes VSTS #656994 - Update and restore button/menu should be disabled
for SDK NuGet for .NET core projects
> [NuGet] Fix Update menu enabled when project has no PackageReferences

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Commands/PackagesCommandHandler.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Commands/UpdateAllPackagesInProjectHandler.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Commands/UpdateAllPackagesInSolutionHandler.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.Helpers/FakeNuGetAwareProject.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.csproj
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/DotNetProjectExtensionsTests.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/DotNetProjectExtensions.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/SolutionExtensions.cs
Backport of #6166.
/cc @mrward @mrward
Description of #6166:
The Update menu was enabled if the project used PackageReferences but
had none in the project. Without any PackageReferences in the
project there is nothing to update. The check to see if the Update
menu is enabled has been changed to make sure the project has
PackageReferences in the project file, not just imported
PackageReferences. Also extended this logic to be used by the Update
NuGet Packages menu which is used to update packages for the solution.
Fixes VSTS #656994 - Update and restore button/menu should be disabled
for SDK NuGet for .NET core projects
> [release-7.7] [NuGet] Fix Update menu enabled when project has no PackageReferences

- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Instrumentation/TimerCounter.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Services.cs
Backport of #6178.
/cc @iainx 
Description:
Includes extra metadata on the buildanddeploy event:
- ProjectID
- ProjectType
- ProjectFlavor
- BuildTime
BuildTime is the length of time the build process took.
Fixes VSTS #675546
> [release-7.6] [Telemetry] Classify Build/Run events by project type

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.UI.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.cs
Backport of #6185.
/cc @slluis @nosami
Description:
So that Voiceover announces the relation between categories and
subcategories.
Fixes VSTS #648743
> [release-7.7] Display project subcategories as children of categories

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
Backport of #6160.
Description:
Handle the syntax mode changes on the main thread so that DisposeLayoutDict is called from the main thread and it won't throw an exception
Fixes VSTS #694980
> [release-7.7] [TextEditor] Handle syntax mode changes on main thread

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
Backport of #6160.
Description:
Handle the syntax mode changes on the main thread so that DisposeLayoutDict is called from the main thread and it won't throw an exception
Fixes VSTS #694980
> [release-7.6] [TextEditor] Handle syntax mode changes on main thread

- main/src/addins/MonoDevelop.SourceEditor2/VSEditor/TagBasedSyntaxHighlighting.cs
.cs file
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/695076
Now the classification call gets properly canceled.
> Fixes VSTS Bug 695076: Highlighting delay moving lines up or down in

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Services.cs
Backport of #6193.
/cc @iainx 
Description:
Include Time to code event if a file is opened as well
Fixes VSTS #684796
> [release-7.7] [Telemetry] Time to Code for file open

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSystemInformation.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/NuGetSystemInformation.cs
- main/src/core/MonoDevelop.Ide/ExtensionModel/MonoDevelop.Ide.addin.xml
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Updater/UpdateInfo.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeVersionInfo.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProductInformationProvider.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/RuntimeVersionInfo.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/UpdateInfo.cs
Backport of #6108.
/cc @nosami @nosami
Description of #6108:
Consolidating ISystemInformation, UpdateInfoExtensionNode and
IUpdateInfoGenerator into ProductInformationProvider so that we only
have one way to retrieve product information.
Fixes VSTS #664616
> [release-7.7] Report _from_ version in addition to _to_ version

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
Fixes a crash if we try to set the restart property
> [Telemetry] Don't use the PropertyService before runtime is initialised

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
Backport of #6208.
/cc @iainx 
Description:
Fixes a crash if we try to set the restart property
> [release-7.7] [Telemetry] Don\u0027t use the PropertyService before runtime is initialised

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
Backport of #6208.
/cc @iainx 
Description:
Fixes a crash if we try to set the restart property
> [release-7.6] [Telemetry] Don\u0027t use the PropertyService before runtime is initialised

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectSupportedTargetFrameworksTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateWizardTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreSdkInstalledConditionTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.csproj
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectSupportedTargetFrameworks.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdk.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdkInstalledCondition.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/MonoRuntimeInfoExtensions.cs
Backport of #6154.
/cc @rodrmoya 
Description:
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/694494
> [release-7.7] [DotNetCore] Support .NETStandard 2.0 when new enough Mono is installed

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Tooltips/LanguageItemTooltipProvider.cs
SignatureMarkupCreator.cs:238 Shouldn't happen in monodevelop core
since entity is checked in c# ambience (the only point where this
method is called in monodevelop).
> Fixes issue #5994 ArgumentNull: entity in

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Tooltips/LanguageItemTooltipProvider.cs
Backport of #6226.
/cc @mkrueger 
Description:
SignatureMarkupCreator.cs:238 Shouldn't happen in monodevelop core
since entity is checked in c# ambience (the only point where this
method is called in monodevelop).
> [release-7.7] Fixes issue #5994 ArgumentNull: entity in

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
opened.
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/694579
The pango font is always valid - it fails back to a default version.
Using the font name is not safe.
> Fixed VSTS Bug 694579: [Feedback] The file '[redacted]' could not be

- main/src/addins/MacPlatform/KernelInterop.cs
- main/src/addins/MacPlatform/MacTelemetryDetails.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/IPlatformTelemetryDetails.cs
This PR has a few changes:
* Keeps track of the number of physical and logical CPU cores
* We now have a way on the mac host to query the current CPU load information
* Expose the API into IPlatformTelemetryDetails so it can be queried.
> [RFC] Host CPU load counters

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputTreeCellView.cs
This PR needs a fix in Xwt, for some reason treeView?.HasFocus is not giving me a right value (is allways in false).
@sevoku could you open a issue related to this? I was investigating but no idea why it's failing.
Fixes Bug #620734
> [StructuredOutput] Fixes TextColor in unfocused selected row

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.Visualizer/ValueVisualizerDialog.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ExceptionCaughtDialog.cs
Backport of #6267.
/cc @nosami 
Description:
Stop the escape key closing both the Value Visualizer dialog and the
Exception caught dialog
Fixes VSTS #648194
> [release-7.7] Prevent esc key propagation in Visualizer dialog

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.Visualizer/ValueVisualizerDialog.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ExceptionCaughtDialog.cs
Stop the escape key closing both the Value Visualizer dialog and the
Exception caught dialog
Fixes VSTS #648194
> Prevent esc key propagation in Visualizer dialog

- main/src/addins/Xml/Editor/BaseXmlEditorExtension.cs
closing tag completion in XAML IntelliSense closes the completion
window
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/694576
That behavior was implemented on purpose for some reason but I agree
to the bug reporter that changing the behavior that way there is not
wanted.
> Fixed Bug 694576: [Feedback] Pressing "Arrow Down" to choose the

- main/src/addins/MacPlatform/KernelInterop.cs
- main/src/addins/MacPlatform/MacTelemetryDetails.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/IPlatformTelemetryDetails.cs
Backport of #6206.
/cc @Therzok 
Description:
This PR has a few changes:
* Keeps track of the number of physical and logical CPU cores
* We now have a way on the mac host to query the current CPU load information
* Expose the API into IPlatformTelemetryDetails so it can be queried.
> [release-7.7] [RFC] Host CPU load counters

- main/src/addins/MonoDevelop.SourceEditor2/VSEditor/TagBasedSyntaxHighlighting.cs
Fixes VSTS #700077 - Listening to batched tags changed causes way too many line updates
A trace like:
```
1.33%   HandlerInternal  •  2,414 ms  •  161 calls  •  MonoDevelop.Ide.DispatchService+GtkSynchronizationContext+TimeoutProxy.HandlerInternal(IntPtr)
1.08%   cctor>b__20_0  •  1,961 ms  •  24 calls  •  Microsoft.VisualStudio.Threading.JoinableTaskFactory+SingleExecuteProtector+<>c.cctor>b__20_0(Object)
1.08%   MoveNext  •  1,960 ms  •  24 calls  •  Microsoft.VisualStudio.Utilities.JoinableTaskHelper+<>c__DisplayClass4_0+<<RunOnUIThread>b__0>d.MoveNext
1.08%   RaiseBatchedTagsChanged  •  1,959 ms  •  24 calls  •  Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.RaiseBatchedTagsChanged
1.08%   RaiseEvent  •  1,959 ms  •  24 calls  • …
```
> [Editor] Fix some performance issue happening on classification changes

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/IInfoBarHost.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/InfoBar.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DefaultWorkbench.cs
Deduplicate infobar items from showing. This allows for users
to safely use AddInfoBar at any point.
Fixes VSTS #685084 - Limit and deduplicate refactoring error info bars
> [Ide] Add a way for the infobar to deduplicate items

- main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.Tests/MonoDevelop.UnitTesting.Tests/VsTestUnitTestTests.cs
- main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.VsTest/VsTestNamespaceTestGroup.cs
- main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.VsTest/VsTestUnitTest.cs
Backport of #6288.
/cc @mkrueger 
Description:
application, the application will crash with a stack trace that seems
to try to recursively add unit test over 85,000 times
https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/701330
> [release-7.7] Fixes VSTS Bug 701330: DTS: When adding Unit Test into the

- main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.Tests/MonoDevelop.UnitTesting.Tests/VsTestUnitTestTests.cs
- main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.VsTest/VsTestNamespaceTestGroup.cs
- main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.VsTest/VsTestUnitTest.cs
Backport of #6288.
/cc @mkrueger 
Description:
application, the application will crash with a stack trace that seems
to try to recursively add unit test over 85,000 times
https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/701330
> [release-7.6] Fixes VSTS Bug 701330: DTS: When adding Unit Test into the

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/IInfoBarHost.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/InfoBar.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DefaultWorkbench.cs
Deduplicate infobar items from showing. This allows for users
to safely use AddInfoBar at any point.
Fixes VSTS #685084 - Limit and deduplicate refactoring error info bars
> [7.7][Ide] Add a way for the infobar to deduplicate items

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Xwt/XwtThemedPopup.cs
Backport of #6145.
/cc @sevoku 
Description:
Requires mono/xwt#856
Fixes VSTS #690353
> [release-7.7] [Ide][Mac] Fix Popup rendering on Mojave

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Xwt/XwtThemedPopup.cs
Backport of #6145.
/cc @sevoku 
Description:
Requires mono/xwt#856
Fixes VSTS #690353
> [release-7.6] [Ide][Mac] Fix Popup rendering on Mojave

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
Backport of #6313.
Description:
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/701972
Cursors get disposed on destroy. The TextViewMargin tried to share the
same cursor objects (as only margin which changes the cursor).
> [release-7.7] Fixes VSTS Bug 701972: [Feedback] Mouse Cursor is always an arrow

- main/build/MacOSX/monostub.mm
Fixes VSTS #705976 - Temporarily disable Mono hybrid suspend
> [Mac] Disable hybrid suspend until the XamMac GC hang is fixed

- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/PlatformService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/ThermalMonitor.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/DesktopService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/PlatformThermalStatusEventArgs.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Services.cs
- main/tests/MacPlatform.Tests/MacPlatform.Tests.csproj
- main/tests/MacPlatform.Tests/ThermalMonitorTests.cs
This monitor is used to tell the application when the host's fan
rotation speed changes due to temperature increase
Fixes VSTS #698542 - Use Thermal monitoring and battery source to improve performance
TODO: tests
> [Mac, Ide] Add ThermalMonitor implementation.

- main/build/MacOSX/monostub.mm
Backport of #6327.
Description:
Fixes VSTS #705976 - Temporarily disable Mono hybrid suspend
> [release-7.7] [Mac] Disable hybrid suspend until the XamMac GC hang is fixed

- main/build/MacOSX/monostub.mm
Backport of #6327.
Description:
Fixes VSTS #705976 - Temporarily disable Mono hybrid suspend
> [release-7.6] [Mac] Disable hybrid suspend until the XamMac GC hang is fixed

- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Ide.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
Do not trigger showing the welcome page until the app is idle,
so as to not load the welcome page when a solution is passed to the app.
This improves startup time for solutions/documents loaded from finder
Fixes VSTS #652347 - Welcome page should not show when loading a solution from finder
> [WelcomePage] Show it when the app goes idle

- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/PlatformService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/ThermalMonitor.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/DesktopService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/PlatformThermalStatusEventArgs.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Services.cs
- main/tests/MacPlatform.Tests/MacPlatform.Tests.csproj
- main/tests/MacPlatform.Tests/ThermalMonitorTests.cs
Backport of #6219.
/cc @Therzok 
Description:
This monitor is used to tell the application when the host's fan
rotation speed changes due to temperature increase
Fixes VSTS #698542 - Use Thermal monitoring and battery source to improve performance
TODO: tests
> [release-7.7] [Mac, Ide] Add ThermalMonitor implementation.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopFrameworkAssemblyPathResolver.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
- main/tests/Ide.Tests/MonoDevelop.Ide.RoslynServices/MonoDevelopFrameworkAssemblyPathResolverFactoryTests.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Tests.csproj
- main/tests/Ide.Tests/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspaceTests.cs
- main/tests/test-projects/workspace-metadata-references/library-project-net461/MyClass.cs
- main/tests/test-projects/workspace-metadata-references/library-project-net461/Properties/AssemblyInfo.cs
- main/tests/test-projects/workspace-metadata-references/library-project-net461/library-project-net461.csproj
- main/tests/test-projects/workspace-metadata-references/library-project/MyClass.cs
- main/tests/test-projects/workspace-metadata-references/library-project/Properties/AssemblyInfo.cs
- main/tests/test-projects/workspace-metadata-references/library-project/library-project.csproj
- main/tests/test-projects/workspace-metadata-references/workspace-metadata-references.sln
- main/tests/test-projects/workspace-metadata-references/workspace-metadata-references/Program.cs
- main/tests/test-projects/workspace-metadata-references/workspace-metadata-references/Properties/AssemblyInfo.cs
- main/tests/test-projects/workspace-metadata-references/workspace-metadata-references/workspace-metadata-references.csproj
> Fixes issue #6061 Add using writes the wrong reference down for a

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebugCommands.cs
Start Without Debugging followed by Start Debugging for an aspnet
app was failing because the original application was still running
in the background on port 5001.
This fixes that by requesting to stop the original application before
launching the new one.
Fixes VSTS #664768
> Fixes exception for aspnet app when debugging

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeTemplates/CodeTemplate.cs
files leads to poorly formatted code
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/685144
Couldn't reproduce the issue however the screencast shows that the
start indentation is not corrected - this change forces the correction
beforehand and should prevent what's seen in the screencast.
> Fixes VSTS Bug 685144: Invoking some snippets from toolbox in .cs

- main/build/MacOSX/Makefile.am
- main/build/MacOSX/monostub.mm
This commit tells mono to report any kind of hang in mono
due to gc hybrid suspend, as opposed to just hanging, as it currently does.
Usable to report bugs to runtime time team about hybrid suspend.
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/703564
> [Fixes  VSTS #703564](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/703564)
> [Mac] Make stub launcher configure mono hybrid suspend

- main/src/core/MonoDevelop.Ide/gtkrc.mac-dark
> Dark .gtkrc update: default button color contrast increase (for better a11y)

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/PackageManagementLoggerTests.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/MonoDevelopBuildIntegratedRestorer.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageManagementLogger.cs
Creating an xUnit .NET Core test projet named 'xunit' would fail to
restore since there is a package reference cycle between the project
and the xunit NuGet package. Whilst the error message has been
improved in NuGet 4.7 to show there is a cycle this information is
buried in the Package Console output and all you would see was just
Restore failed. Now the error information is shown at the end of the
Package Console as a summary of the failures to make it easier to
see what failed. Now for the xunit project you will see the following
at the end of the Package Console output:
Cycle detected.
xunit -> xunit (>= 2.3.1).
Restore failed.
Fixes VSTS #650078 - Restore failed for xunit.
> [NuGet] Show summary of NuGet restore errors

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.AnalysisCore/Gui/ResultTooltipProvider.RectangleMarker.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.csproj
Mono.Cairo.dll on Windows doesn't have Context.SetSourceColor() so we have to emulate it using an extension method so that MonoDevelop can build on Windows.
> Make sure MD.Refactoring builds on Windows.

- version-checks
Updated reference to xamarin/md-addins@1b16d82
https://github.com/xamarin/ios-sim-sharp/compare/ba9197fd6ea9c2ee7c912cea9cb871b0bd6117af...452bd90ccd751c70c55e43f1b30d5aa445690a0e
[452bd90](https://github.com/xamarin/ios-sim-sharp/commit/452bd90ccd751c70c55e43f1b30d5aa445690a0e) [build] re-default to setting MODERN_XCODE_ONLY on Mojave
[c06b737](https://github.com/xamarin/ios-sim-sharp/commit/c06b7372b63a3af5340b385cd0fdc588e74136d4) Revert "[build] Default MODERN_XCODE_ONLY when on Mojave"
> Updated reference to xamarin/md-addins@1b16d82

- main/src/addins/MonoDevelop.DotNetCore/Properties/MonoDevelop.DotNetCore.addin.xml
In project options the Build - General page was missing the
Code Generation and Language Options sections. The Build - Compiler
page was missing completely. Affected .NET Core projects where
the solution was using the Visual Studio on Windows guid for
.NET Core projects 9A19103F-16F7-4668-BE54-9A1E7A4F7556. Using this
guid meant the projects were not being identified as C# projects
so the project options dialog was missing some sections.
Fixes VSTS #712224 - .NET Core project options panel missing sections
> [DotNetCore] Fix missing sections in project options

- main/src/addins/MonoDevelop.DotNetCore/Properties/MonoDevelop.DotNetCore.addin.xml
Backport of #6433.
/cc @mrward 
Description:
In project options the Build - General page was missing the
Code Generation and Language Options sections. The Build - Compiler
page was missing completely. Affected .NET Core projects where
the solution was using the Visual Studio on Windows guid for
.NET Core projects 9A19103F-16F7-4668-BE54-9A1E7A4F7556. Using this
guid meant the projects were not being identified as C# projects
so the project options dialog was missing some sections.
Fixes VSTS #712224 - .NET Core project options panel missing sections
> [release-7.7] [DotNetCore] Fix missing sections in project options

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/DotNetProjectProxy.cs
.NET Core 2.2 preview 3 SDK now uses implicit package versions.
The package references loaded by the project model do not have the
version metadata directly applied. This results in the wrong version
being restored by NuGet. For a .NET Core 2.1 project this resulted in
a restore warning:
```
Project dependency Microsoft.NETCore.App does not contain an inclusive
lower bound. Include a lower bound in the dependency version to ensure
consistent restore results.
```
And a build error:
```
Error: NETSDK1061: The project was restored using Microsoft.NETCore.App
version 1.0.0, but with current settings, version 2.1.0 would be used
instead.
```
Added a workaround to find the implicit version and apply it to the
package reference so the correct version is restored by NuGet.
Fixes VSTS #707944 - …
> [DotNetCore] Handle implicit package reference versions

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/DotNetProjectProxy.cs
Backport of #6415.
/cc @mrward 
Description:
.NET Core 2.2 preview 3 SDK now uses implicit package versions.
The package references loaded by the project model do not have the
version metadata directly applied. This results in the wrong version
being restored by NuGet. For a .NET Core 2.1 project this resulted in
a restore warning:
```
Project dependency Microsoft.NETCore.App does not contain an inclusive
lower bound. Include a lower bound in the dependency version to ensure
consistent restore results.
```
And a build error:
```
Error: NETSDK1061: The project was restored using Microsoft.NETCore.App
version 1.0.0, but with current settings, version 2.1.0 would be used
instead.
```
Added a workaround to find the implicit version and apply it to the
package reference so the correct version …
> [release-7.7] [DotNetCore] Handle implicit package reference versions

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/DotNetProjectProxy.cs
Backport of #6415.
Description:
.NET Core 2.2 preview 3 SDK now uses implicit package versions.
The package references loaded by the project model do not have the
version metadata directly applied. This results in the wrong version
being restored by NuGet. For a .NET Core 2.1 project this resulted in
a restore warning:
```
Project dependency Microsoft.NETCore.App does not contain an inclusive
lower bound. Include a lower bound in the dependency version to ensure
consistent restore results.
```
And a build error:
```
Error: NETSDK1061: The project was restored using Microsoft.NETCore.App
version 1.0.0, but with current settings, version 2.1.0 would be used
instead.
```
Added a workaround to find the implicit version and apply it to the
package reference so the correct …
> [release-7.6] [DotNetCore] Handle implicit package reference versions

- main/src/addins/MacPlatform/MacTelemetryDetails.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextEditorKeyPressTimings.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/IPlatformTelemetryDetails.cs
- main/src/core/MonoDevelop.TextEditor.Tests/Mono.TextEditor.Tests/TextEditorKeyPressTimingsTests.cs
Read each commit and commit message separately as details are layered in.
* Implement a test to assert/ensure event times with sub-millisecond precision
* Allow `IPlatformTelemetryDetails` to provide event times
* Support sub-millisecond precision when dealing with time accumulation in `TextEditorKeyPressTimings`
**TL;DR:** Telemetry timings now have sub-millisecond precision on macOS (e.g. an event that was previously truncated to 2ms may now be more accurately reported as say 2.9708ms).
Fixes VSTS #714180
> Support sub-millisecond precision for editor telemetry event timing

- main/src/addins/MacPlatform/MacTelemetryDetails.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextEditorKeyPressTimings.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/IPlatformTelemetryDetails.cs
- main/src/core/MonoDevelop.TextEditor.Tests/Mono.TextEditor.Tests/TextEditorKeyPressTimingsTests.cs
Backport of #6452.
/cc @Therzok @abock
Description:
Read each commit and commit message separately as details are layered in.
* Implement a test to assert/ensure event times with sub-millisecond precision
* Allow `IPlatformTelemetryDetails` to provide event times
* Support sub-millisecond precision when dealing with time accumulation in `TextEditorKeyPressTimings`
**TL;DR:** Telemetry timings now have sub-millisecond precision on macOS (e.g. an event that was previously truncated to 2ms may now be more accurately reported as say 2.9708ms).
Fixes VSTS #714180
> [release-7.7] Support sub-millisecond precision for editor telemetry event timing

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/ExtensibleTreeView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/IPadContainer.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Pad.cs
No pad user preferences were being saved. This was because the
preferences were being requested from the PadWindow through its
GetMementoCapable method. This was generally returning null since the
PadWindow's content field is not set. Changed the Pad so it checks
the PadCodon's Content implements IMementoCapable instead. This
ensures pad user preferences are stored with the solution's user
preferences.
Fixes VSTS #699562 - Show All Files is not persisted
> [Ide] Show all files option is not remembered for solution

- main/src/core/MonoDevelop.Startup/app.config
Backport of #6394.
/cc @Therzok 
Description:
Fixes VSTS #708456 - Missing binding redirect after yamldotnet bump
> [release-7.7] Add YamlDotNet binding redirects

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DefaultWorkbench.cs
The crash trace listed in the bug report doesn't say what the exception that caused the crash was, and I've
not been able to reproduce it, so I'll added a null check and a type check.
Fixes VSTS #706884
> [IDE] Fix a crash when closing a docknotebook tab

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Commands/PublishToFolderProfilesCommandHandler.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/ProjectExtensions.cs
- This prevents a DirectoryNotFound exception since we are always enumerating (and assuming) that such directory exists.
> [AspNetCore] Checks publish profiles directory 

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DefaultWorkbench.cs
Backport of #6413.
Description:
The crash trace listed in the bug report doesn't say what the exception that caused the crash was, and I've
not been able to reproduce it, so I'll added a null check and a type check.
Fixes VSTS #706884
> [release-7.7] [IDE] Fix a crash when closing a docknotebook tab

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Commands/PublishToFolderCommandHandler.cs
- main/src/addins/MonoDevelop.AspNetCore/Properties/MonoDevelop.AspNetCore.addin.xml
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/ProjectPadContextMenu.addin.xml
Backport of #6466.
/cc @jtorres 
Description:
- When does not support Folder Publishing then sets item to Visible = false
Fixes VSTS #715107
Fixes #6465  
Fixes #6468
> [release-7.7] [AspNetCore] Properly disables folder publishing

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Commands/PublishToFolderProfilesCommandHandler.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/ProjectExtensions.cs
Backport of #6461.
Description:
- This prevents a DirectoryNotFound exception since we are always enumerating (and assuming) that such directory exists.
> [release-7.7] [AspNetCore] Checks publish profiles directory 

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/FoldMarkerMargin.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.QuickTasks/QuickTaskStrip.cs
Delay the accessibility updating for the quick task strip for 5 seconds to prevent unnecessary updates
> Delay accessibility updates

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextEditor.cs
VSTS issue: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/706004
Related PR:
https://github.com/xamarin/designer/pull/1353
> Expose InformLoadComplete in `TextEditor` needed to fix VSTS 706004

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextEditor.cs
Backport of #6494.
/cc @sgmunn @olegoid
Description:
VSTS issue: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/706004
Related PR:
https://github.com/xamarin/designer/pull/1353
> [release-7.7] Expose InformLoadComplete in `TextEditor` needed to fix VSTS 706004

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/FoldMarkerMargin.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.QuickTasks/QuickTaskStrip.cs
Backport of #6470.
/cc @Therzok @iainx
Description:
Delay the accessibility updating for the quick task strip for 5 seconds to prevent unnecessary updates
> [release-7.7] Delay accessibility updates

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/ViewContent.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs
When working with symlinked on disk files in a project, there's a
few things which were not handled correctly.
When a project references a symlink, we should keep the original
symlink information around so that it can be used when looking up
a for a Project containing a file or a file in general in a project.
Added in an OriginalFile property that is used to recover the original
file name, before resolving a symlink, that can be used by the typesystem
to figure out which project the file belongs to.
Fixes VSTS #700204 - Symlinked files do not have correct define constants
> [Ide] Properly handle symlinks at workbench level

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
It is already requested in one of the InitComplete handlers,
thus it is already computed. No need to create a task just
for querying a lazy value.
> [Ide] De-asynchronify Creating startup metadata

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/TextDocument.cs
This PR adds two tweaks to the current integration with the Visual Studio text model:
- It integrates with the `GetContent<T>` machinery so that an underlying `ITextDocument` instance can be queried from a `TextEditor` instance
- If fixes `ITextDocument` lifecycle when the parent document is disposed so that the corresponding event in `ITextDocumentFactoryService` is fired properly
Ultimately those two changes help us share our integration code between Visual Studio Windows and VSMac.
> Visual Studio text model tweaks

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/SdiWorkspaceWindow.cs
When a widget is not a container, c?.Children?.Length != 0 is true (because Length is `null` which is not 0), and so we were falling through to the `foreach` and null ref-ing on `c.Children`.
Also use pattern matching to simplify code a bit while I'm here.
Rename `GetFocussableWidgets` -> `GetFocusableWidgets`.
> Fix GetFocussableWidgets()

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/LogView.cs
The `Cookie` should not be reset on a regular `Clear()` (i.e. Clear pad button clicked) but only when the pad is being cleared by a new consumer wanting to reuse an existing output pad.
Fixes VSTS #705935
> [Ide] Reset LogView cookie only when cleared for reusing

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/Gui/MonoDevelop.VersionControl.Git.CredentialsDialog.cs
There's a label right below it which contains the URL
Fixes VSTS #720573 - Git Credentials Pop up Window Text Defect
> [Git] Remove superfluous {0} from label

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Diagnostics/MonoTODO/MonoTODODiagnosticAnalyzer.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeIssues/CodeDiagnosticRunner.cs
Backport of #6485.
/cc @Therzok 
Description:
This PR has three main changes:
* Logs any kind of analyzer errors
* Optimizes MonoTODO attribute searching for TODO attribute by avoiding querying multiple times
* Ports over most analyzers to IOperation which does analysis on already bound nodes, so it doesn't try to run and return an invalid symbol while typing. This improves CPU usage in the background by a big margin.
On Main.sln with just Project.cs open, analyzer runtime is down by 8 minutes, from a total (not just analyzers) of 20 mins of CPU time in background to 12mins.
Fixes VSTS #714351 - Analyzer driver errors are not logged
Fixes VSTS #718955 - Review analyzers which bind symbols while typing
Fixes VSTS #718958 - [Analyzer] MonoTODO is doing useless searching
> [release-7.7] Optimize analyzers across the IDE

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.PropertyGrid/PropertyEditorCell.cs
There is a crash in the PropertyCell value getter, which this try catch will
work around
Fixes VSTS #706892
> [IDE] Wrap the PropertyCell Value getter in a try catch block

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.addin.xml
The global command and the project context menu command were worded differently, and the context menu command did not use the work NuGet, which causes discoverability issues.
> [NuGet] Make add packages commands consistent

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.AnalysisCore/Gui/ResultsEditorExtension.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.QuickTasks/QuickTaskOverviewMode.cs
QuickTaskMargin is drawed in a background buffer which blit shouldn't take much time anyways.
> Fixes issue #6559 Caret location in quick fix margin is incorrect

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.AnalysisCore/Gui/ResultsEditorExtension.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.AnalysisCore/Result.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs
- main/src/addins/MonoDevelop.SourceEditor2/VSEditor/TagBasedSyntaxHighlighting.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/ISyntaxHighlighting.cs
Found 2 problems:
+ Tag based syntax highlighting always updates on text change 
+ Analysis Markers don't reuse objects and creates a lot of allocations and markers. Reusing markers helps a lot every add/remove causes redrawing.  
This PR only reuses the markers before the text change - however markers beyond the text change could be reused as well but I need more time implementing that - I'll update on this PR.
> Master optimize drawing

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests.csproj
This was causing none of the NuGet addin tests to be run. In the
unit test output from running vstool would show an error about
failing to load NuGet.Versioning since the .NET Core tests were
copying the old assembly into the build/tests directory:
```
Could not load file or assembly 'NuGet.Versioning, Version=4.7.0.5,
Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its
dependencies.
```
> [DotNetCore.Tests] Fix old NuGet.Versioning being used by tests

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices/RoslynFileLogger.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices/RoslynLogger.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices/RoslynService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
Move FatalError registration into RoslynService initialization.
Add a new RoslynFileLogger class that writes everything roslyn reports
into its own log file.
Keep the old one for database exceptions so we catch them in the ide log
Fixes VSTS #679463 - Log everything that roslyn reports to the log file
> [Ide] Improve roslyn logging infrastructure

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.Braces/BraceCompletionManager.cs
VSEditor model did not reflect the changes done to the matching brace in the
IDE preferences
Fixes VSTS #703893 - Matching brace is inserted even though option is disabled
> [Editor] Fix runtime toggling of insert matching brace

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/InfoBar.cs
The hyphen should only be added when the item is a hyperlink
following the description
Fixes VSTS #723318 - InfoBar shows a hyphen between the text and the first item if that item is a link
> [Ide] Don't add a hyphen if the first item is not a hyperlink

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeActionEditorExtension.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/Change.cs
same editor is added twice to the refactoring operation and balances
out undo groups.
> Fixes issue #6482 Cannot rename public types This prevents that the

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeActionEditorExtension.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/Change.cs
same editor is added twice to the refactoring operation and balances
out undo groups.
Backport of #6490.
> [release-7.7] Fixes issue #6482 Cannot rename public types This prevents that the

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.Braces/BraceCompletionManager.cs
VSEditor model did not reflect the changes done to the matching brace in the
IDE preferences
Fixes VSTS #703893 - Matching brace is inserted even though option is disabled
Backport of #6591.
> [release-7.7] [Editor] Fix runtime toggling of insert matching brace

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/InfoBar.cs
The hyphen should only be added when the item is a hyperlink
following the description
Fixes VSTS #723318 - InfoBar shows a hyphen between the text and the first item if that item is a link
Backport of #6593.
> [release-7.7] [Ide] Don\u0027t add a hyphen if the first item is not a hyperlink

- main/src/addins/GnomePlatform/GnomePlatform.cs
When there is no `XDG_CURRENT_DESKTOP` set, `Environment.GetEnvironmentVariable` will return `null` causing subsequent `IndexOf` to throw `NullReferenceException`.
> Fix probing for a terminal.

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeActionEditorExtension.cs
incorrectly for a single line of recommendations
https://dev.azure.com/devdiv/DevDiv/_workitems/edit/723420
VS.NET takes the whole line into account for fixes - but for
refactorings it's using the caret position.
The fixes are sorted by the distance of the caret position.
> Fixes VSTS Bug 723420: Light bulb - Numerous light bulbs show up

- main/src/addins/MacPlatform/MacInterop/Keychain.cs
- main/tests/MacPlatform.Tests/KeychainTests.cs
When requesting a keychain item, we need to append a null byte.
When adding one, we don't.
Fixes VSTS #729363 - Visual Studio for Mac prompts for Git Credentials every time "Update Solution" or "Push Changes" is called
> [Git] Fix prompt over and over for keychain items

- main/src/addins/MacPlatform/MacInterop/Keychain.cs
- main/tests/MacPlatform.Tests/KeychainTests.cs
When requesting a keychain item, we need to append a null byte.
When adding one, we don't.
Fixes VSTS #729363 - Visual Studio for Mac prompts for Git Credentials every time "Update Solution" or "Push Changes" is called
Backport of #6619.
> [release-7.7] [Git] Fix prompt over and over for keychain items

- main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding.Refactoring/CSharpCodeActionEditorExtensionTests.cs
RE was bumped again, bringing in the changes to code refactorings
Fix the test that was failing
> [C#] Fix failing tests, C# test suite should no longer timeout

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/ContextMenuTreeView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/ExtensibleTreeView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/TreeNodeNavigator.cs
Sometimes when right clicking the project and selecting Add - New
Folder the project tree node is selected and made editable instead
of the new folder. The ContextMenuTreeView registers a tree view
SelectFunction in its OnButtonPressEvent which disables selection.
Sometimes there is no corresponding OnButtonReleaseEvent to undo
this SelectFunction so the TreeNodeNavigator cannot select the
new folder node that has been added. Now the TreeNodeNavigator
forces the SelectFunction to be reset before selecting a
tree node.
Fixes VSTS #721437 - Can't focus on a folder and name it during
creation.
> [Ide] Fix new folder not being selected in Solution pad

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CSharpCompletionTextEditorExtension.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/ImportSymbolCompletionData.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/RoslynCompletionData.cs
Intellisense, it does not trim the Attribute name
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/729414
During investigating that bug I've seen that the import symbol
completion data doesn't have the tooltip code implemented. Added
tooltip code for this kind of completion data in conjunction with the
bug fix.
> Fixes VSTS Bug 729414: [Feedback] When adding an attribute via

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
- main/tests/performance/MonoDevelop.PerformanceTesting/MonoDevelop.PerformanceTesting.csproj
- main/tests/performance/MonoDevelop.PerformanceTesting/Properties/AssemblyInfo.cs
Fixes VSTS #734934 - Missing System.Composition.Convention
> [Build] Fixup warnings showing up at build time

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/MdTextViewLineCollection.MdTextViewLine.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Actions/CaretMoveActions.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Actions/DeleteActions.cs
- main/src/core/MonoDevelop.TextEditor.Tests/Mono.TextEditor.Tests.DefaultEditActions/CaretMoveActionTests.cs
getting deleted when trying to delete keywords︐ ,︒,︑,︓,︔ ,︕ ,︖ ,︗
,︘,︙, from keyboard
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/734863
The utf32 surrogate check was a bit more complex.
> Fixes VSTS Bug 734863: Inverted comma (one more character) is also

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/MicrosoftTemplateEngine.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/TemplatingService.cs
Failing to access the ~/.templateengine folder due to permissions
or not owning the files would result in the New Project dialog not
opening when trying to create a new project. Now a message dialog
is displayed showing the error before the New Project dialog is
opened.
Also moved the initialization of the templating engine out of the
constructor, to prevent the underlying error being hidden by a
TypeInitializationException. Initialization is now attempted each
time the templates are accessed in case the underlying error has
been fixed whilst the IDE is running.
Fixes VSTS #725161 - Failed to open New Project Dialog. Access to the
path "/Users/user/.templateengine/Visual Studio/7.0/..." is denied.
> [Ide] Improve error handling when loading project templates

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageCompatibilityHandler.cs
If a project had both a PackageReference and a packages.config file
the package compatiblity checker would run and fail with a null
reference exception. It was treating the project as though it was
using a packages.config file, when it should be treated as a
PackageReference project.
Fixes VSTS #734876 - NRE in package manager when updating target
framework
> [NuGet] Fix null reference exception in compatiblity checker

- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/Helpers/NativeViewHelper.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/MacToolboxViewItems.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/MacToolboxWidgetDataSource.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.csproj
Toolbox allows items with markup. In this PR we added support for cover this, this introduces a new problem with accessibility, we need remove the formatted tags to read correctly the content over VoiceOver.
Fixes Bug https://devdiv.visualstudio.com/DevDiv/_workitems/edit/735244
>  Process markup from formatted text to attributedstring in MacToolboxViewItems

- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/FileCommands.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Extensions/IdeCustomizer.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DefaultWorkbench.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.UI.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.WelcomePage/IWelcomeWindowProvider.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.WelcomePage/WelcomePageService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Ide.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/MessageService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
If there's a dialog provider for the welcome page, prefer that, and only use
Widget version of it as a fallback. And when so, give control to that
window, hiding the main window.
Also fixes behavior of closing the main window on Mac, which should keep
the app menu bar available to the user.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/561910
> [Ide] Add support for Welcome dialog providers

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProductInformationProvider.cs
Backport of #6686.
/cc @nosami
> [release-8.0] UpdateInfo can be null when the app bundle is not being used

- main/src/addins/MacPlatform/MacPlatform.csproj
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/MacToolbox.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/MacToolboxViewItems.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/MacToolboxWidget.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.csproj
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/NSLabel.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/NSLine.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/NSStackViewExtensions.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/NativeViewHelper.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
These are used both in the new Cocoa Toolbox, as well as in md-addins (PR coming), and, as we add more Cocoa native code, in other places.
> Put common Cocoa helpers/classes in a common place

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads/SolutionPad.cs
If the SolutionPad is initialized when the RootWorkspace's
FirstWorkspaceItemOpened event is fired a solution would be opened
twice in the Solution pad. When the SolutionPad is initialized it
adds the RootWorkspace Items to the tree view. When the RootWorkspace's
WorkspaceItemOpened is fired the SolutionPad then adds that item to
the tree view. To handle this a check is now made to ensure the
item opened is not already in the tree.
Fixes VSTS #736893 - Solution/project duplicated in project tree
> [Ide] Prevent duplicate solution in Solution pad

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageCompatibilityHandler.cs
If a project had both a PackageReference and a packages.config file
the package compatiblity checker would run and fail with a null
reference exception. It was treating the project as though it was
using a packages.config file, when it should be treated as a
PackageReference project.
Fixes VSTS #734876 - NRE in package manager when updating target
framework
Backport of #6671.
/cc @mrward
> [release-7.7] [NuGet] Fix null reference exception in compatiblity checker

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/EditorConfigService.cs
The EditorConfigService was creating a file watcher for .editorconfig
files in every project directory and all directories back to the
root directory. Creating too many CoreFX FileSystemWatchers can
result in http requests failing with an error similar to:
Error: SecureChannelFailure (Unable to write data to the transport
connection: The socket is not connected.)
To avoid this problem the FileWatcherService is used and only if
a .editorconfig file is found is a file watcher created for that
directory. If the .editorconfig file is in the project or solution
directory then this will result in a single file watcher created
for the solution, instead of multiple file watchers.
Fixes VSTS #738596 - Http requests do not work after the IDE has
been opened a while
> [Ide] Reduce file watchers used by EditorConfigService

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.Braces/BraceCompletionEditorExtension.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.Braces/BraceCompletionManagerFactory.cs
For some reason, MS.VS.Text.Impl brace completion manager ended up
being used.
Changing the property key ensures our brace completion manager is used.
Fixes VSTS #738348 - [Feedback] VS for Mac is inserting matching braces even though the option is disabled.
> [Editor] Fix brace completion options not working

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/EditorConfigService.cs
The EditorConfigService was creating a file watcher for .editorconfig
files in every project directory and all directories back to the
root directory. Creating too many CoreFX FileSystemWatchers can
result in http requests failing with an error similar to:
Error: SecureChannelFailure (Unable to write data to the transport
connection: The socket is not connected.)
To avoid this problem the FileWatcherService is used and only if
a .editorconfig file is found is a file watcher created for that
directory. If the .editorconfig file is in the project or solution
directory then this will result in a single file watcher created
for the solution, instead of multiple file watchers.
Fixes VSTS #738596 - Http requests do not work after the IDE has
been opened a while
Backport of #6705.
/cc @slluis …
> [release-7.7] [Ide] Reduce file watchers used by EditorConfigService

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.Braces/BraceCompletionEditorExtension.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.Braces/BraceCompletionManagerFactory.cs
For some reason, MS.VS.Text.Impl brace completion manager ended up
being used.
Changing the property key ensures our brace completion manager is used.
Fixes VSTS #738348 - [Feedback] VS for Mac is inserting matching braces even though the option is disabled.
Backport of #6711.
> [release-8.0-p1-sr1] [Editor] Fix brace completion options not working

- main/tests/Ide.Tests/MonoDevelop.Ide.TypeSystem/MonoDevelopMetadataReferenceManager.MetadataReferenceCacheTests.cs
Not sure how this test ever passed. The logging of the test suite
shows that the workspace item was never added to the filewatcher
cone.
> [Ide] Fix failing tests in MetadataReferenceManager

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/LanguageCellRenderer.cs
The size of the language button cell renderer did not increase its
size for any text it needed to contain.
Also increased the padding on the right hand side so the button
has some space before the end of the row.
Also changed the button so it expands to the left instead of the
right, for example when switching from C# to VB.NET.
With these changes the behaviour and UI is back to how things
worked in version 7.0.
Fixes VSTS 738565 - C#/F# chooser in New Project should be moved a few
pixels leftward
This change prevents the language button from being truncated, as shown below:
Expansion of the button to the left matches the behaviour in 7.0.
> [Ide] Fix New Project dialog's language selector being truncated

- main/src/addins/MacPlatform/MacTelemetryDetails.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
TimeSinceLogin and TimeSinceMachineStart were passing the seconds portion of
the count instead of the total number of seconds. This has been changed to
milliseconds now report milliseconds as well.
Fixes VSTS #720395
> [Telemetry] Pass the total number of milliseconds for TimeSinceLogin

- main/src/addins/MacPlatform/MacTelemetryDetails.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
TimeSinceLogin and TimeSinceMachineStart were passing the seconds portion of
the count instead of the total number of seconds. This has been changed to
milliseconds now report milliseconds as well.
Fixes VSTS #720395
Backport of #6741.
> [release-7.7] [Telemetry] Pass the total number of milliseconds for TimeSinceLogin

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.Helpers/RestoreTestBase.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/DotNetCoreRestoreTests.cs
- main/tests/test-projects/restore-netcore-offline/NuGet.config
- main/tests/test-projects/restore-netcore-offline/dotnetcoreconsole.csproj
- main/tests/test-projects/restore-netcore-offline/dotnetcoreconsole.sln
Tests for the regression in NuGet 4.9 so it is found earlier than
during a manual test. NuGet restore should not go online to download
packages for a .NET Core 2.1 project when the 2.1 sdk is installed.
The NuGet fallback folder should be used. This test disables all
online nuget package sources, changes the global packages cache to
a temporary directory, and then tries to restore a .NET Core 2.1
console project. With NuGet 4.9 this new test fails to restore
with the error:
Unable to resolve 'Microsoft.NETCore.App (>= 2.1.0)' for '.NETCoreApp,Version=v2.1'.
> [NuGet] Add offline .NET Core project restore test

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/NuGetSdkResolverTests.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.addin.xml
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageManagementServices.cs
Opening a project that required the NuGet sdk resolver would
fail with an error about failing to load a NuGet assembly.
Could not load file or assembly 'NuGet.Commands, Version=4.8.0.1,
Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its
dependencies.
The MSBUILD_NUGET_PATH environment variable is not supported in
a more recent NuGet sdk resolver, after it moved out of MSBuild
source code repository into NuGet's source code repository.
Before the NuGet 4.8 update the NuGet sdk resolver would find
the NuGet assemblies that it required, and were not already
loaded by the IDE, in its working directory. Latest NuGet sdk
resolvers are now included in the msbuild bin directory next to
the NuGet assemblies. Now after updating to NuGet 4.8 the sdk
resolver would fail to load the NuGet …
> [release-7.7][NuGet] Fix NuGet sdk resolver

- main/src/addins/MacPlatform/MacTelemetryDetails.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/GtkWorkarounds.cs
Fixes VSTS #739030 - [Feedback] Visual Studio Community 7.7 for Mac - crahses when holding down cursor key
> [Ide] Try fixing random crasher in gdk event finalizer

- main/tests/Ide.Tests/MonoDevelop.Ide.TypeSystem/MonoDevelopMetadataReferenceManager.MetadataReferenceCacheTests.cs
Not sure how this test ever passed. The logging of the test suite
shows that the workspace item was never added to the filewatcher
cone.
Backport of #6715.
/cc @Therzok
> [release-7.7] [Ide] Fix failing tests in MetadataReferenceManager

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.AnalysisCore/Gui/ResultTooltipProvider.RectangleMarker.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.csproj
Mono.Cairo.dll on Windows doesn't have Context.SetSourceColor() so we have to emulate it using an extension method so that MonoDevelop can build on Windows.
Backport of #6424.
> [release-7.7] Make sure MD.Refactoring builds on Windows.

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpProject.fs
Fixes VSTS #748732 (#6757)
Backport of #6764.
/cc @nosami
> [release-7.7] Set Roslyn Language Name for F# projects

- main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.Tests/MonoDevelop.UnitTesting.Tests/VsTestUnitTestTests.cs
- main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.VsTest/VsTestUnitTest.cs
test explorer if string has a period at the end.
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/731943
> Fixes VSTS Bug 731943: [Feedback] xUnit Fact DisplayName not shown in

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpIndentationTracker.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding/CSharpTextEditorIndentationTests.cs
method parameter to a new line, it no longer aligns the parameter to
the previous parameters column.
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/740691
See feedback ticket:
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/740051
This behavior +1 indent is correct - it's the same than in vs.net.
> Fixes VSTS Bug 740691: [Feedback] Regression (C#): When I move a

- main/src/addins/MonoDevelop.UnitTesting.NUnit/MonoDevelop.UnitTesting.NUnit/NUnitTestCase.cs
- main/src/addins/MonoDevelop.UnitTesting.NUnit/MonoDevelop.UnitTesting.NUnit/NUnitTestSuite.cs
- main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.Tests/MonoDevelop.UnitTesting.Tests/VsTestUnitTestTests.cs
- main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.VsTest/VsTestNamespaceTestGroup.cs
- main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.VsTest/VsTestTestClass.cs
- main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.VsTest/VsTestUnitTest.cs
- main/src/addins/MonoDevelop.UnitTesting/Services/AbstractUnitTestEditorExtension.cs
- main/src/addins/MonoDevelop.UnitTesting/Services/UnitTest.cs
- main/src/addins/MonoDevelop.UnitTesting/Services/UnitTestService.cs
integration ("Unit test [name] could not be loaded")
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/729387
TestID is not arbitrary or optional. It's the fully qualified test
name in the source code.
> Fixes VSTS Bug 729387: [Feedback] Broken text editor unit test

- main/src/addins/MonoDevelop.UnitTesting.NUnit/MonoDevelop.UnitTesting.NUnit/NUnitTestCase.cs
- main/src/addins/MonoDevelop.UnitTesting.NUnit/MonoDevelop.UnitTesting.NUnit/NUnitTestSuite.cs
- main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.Tests/MonoDevelop.UnitTesting.Tests/VsTestUnitTestTests.cs
- main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.VsTest/VsTestNamespaceTestGroup.cs
- main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.VsTest/VsTestTestClass.cs
- main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.VsTest/VsTestUnitTest.cs
- main/src/addins/MonoDevelop.UnitTesting/Services/AbstractUnitTestEditorExtension.cs
- main/src/addins/MonoDevelop.UnitTesting/Services/UnitTest.cs
- main/src/addins/MonoDevelop.UnitTesting/Services/UnitTestService.cs
integration ("Unit test [name] could not be loaded")
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/723605
TestID is not arbitrary or optional. It's the fully qualified test
name in the source code.
Backport of #6735.
/cc @mkrueger
> [release-7.7] Fixes VSTS Bug 729387: [Feedback] Broken text editor unit test

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/CellRendererImage.cs
- main/src/core/MonoDevelop.Ide/gtkrc.mac
Use the default Mac unfocused background colour for treeview rows, except in the
solution pad tree view, because the default colour clashes with the custom
background colour. A property has been added to the CellRendererImage so that
it will ignore the selected icon when the treeview is unfocused
Fixes VSTS #648196
> [A11y] Use the default Mac unfocused background colour for treeview rows

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CSharpCompletionTextEditorExtension.cs
The semantic model might not contain a valid symbol at a given
syntax node which can happen in code that's not compilable.
Prevent that by adding a nullcheck
Fixes VSTS #714055 - AddImportCompletionData null reference exception
Backport of #6781.
/cc @Therzok
> [release-7.7] [C#] Fix NRE in completion querying

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.CodeGeneration/AbstractGenerateAction.cs
- In this [commit](https://github.com/mono/monodevelop/commit/6afd30f28a114ac5c717b52eba08e2876e29707f) we removed insert the data at caret, as a results CodeCompletion was throwing a unhandled exception due to a IndexOutOfBounds exception when calling `formattingService.GetFormattingChangesAsync`
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/752764
> [CodeCompletion] Fixes IndexOutOfBounds exception

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.CodeGeneration/AbstractGenerateAction.cs
- In this [commit](https://github.com/mono/monodevelop/commit/6afd30f28a114ac5c717b52eba08e2876e29707f) we removed insert the data at caret, as a results CodeCompletion was throwing a unhandled exception due to a IndexOutOfBounds exception when calling `formattingService.GetFormattingChangesAsync`
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/752764
Backport of #6791.
/cc @slluis @jtorres
> [release-7.7] [CodeCompletion] Fixes IndexOutOfBounds exception

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.addin.xml
Xamarin.Ide uses this assembly and may need it to be registered. When running some tests via `mdtool` I have seen a failure to load the ide addin because this was not found.
> [Nuget] Add import NuGet.common.dll

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads/ErrorListPad.cs
Normally in Gtk if you focus a table and shift-tab the focus goes to the headers
but in the Errors pad, because the focus chain for the pad is set to be the
logView, the shift-tab focus breaks.
unsetting the focus chain fixes the header navigation issue, but stops the
logView being automatically focused. I have tried about 5 different ways to
make the logView still be the default focus, but none of them worked.
Discussing it with Sevo, we decided that making the logView the default focus
didn't really make sense anyway, so I've removed that.
Fixes VSTS #515118
> [A11y] Make the headers on the error pad accessible from the keyboard

- main/build/MacOSX/Info.plist.in
With Mojave, an application cannot use AppleScript without the user granting it
permission, and the application will not ask for permission without this key
being present
Fixes VSTS #762097
> [Mac] Add NSAppleEventsUsageDescription key

- main/build/MacOSX/Info.plist.in
With Mojave, an application cannot use AppleScript without the user granting it
permission, and the application will not ask for permission without this key
being present
Fixes VSTS #762097
Backport of #6807.
/cc @iainx
> [release-7.7] [Mac] Add NSAppleEventsUsageDescription key

- main/build/MacOSX/Info.plist.in
With Mojave, an application cannot use AppleScript without the user granting it
permission, and the application will not ask for permission without this key
being present
Fixes VSTS #762097
Backport of #6807.
> [release-7.8] [Mac] Add NSAppleEventsUsageDescription key

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests.csproj
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs
- main/tests/test-projects/netstandard-sdk/Class1.cs
- main/tests/test-projects/netstandard-sdk/netstandard-sdk.csproj
- main/tests/test-projects/netstandard-sdk/netstandard-sdk.sln
With two sdk projects, Lib1 and Lib2, where Lib1 has its output
assembly signed, then in Lib2 any use of any types from Lib1 would
show errors in the text editor after the solution was built. Errors
similar to:
The type 'Class1' exists in both 'Lib1, Version=0.0.0.0, Culture=Neutral, PublicKeyToken='
and 'Lib2, Version=1.0.0.0, Culture=neutral, PublicKeyToken='
This was because the generated AssemblyInfo.cs file which exists in
the obj directory was available to the type system so there was a
mismatch in the assembly information from the assembly .dll on disk
and the project information which resulted in Roslyn creating two
references. The generated AssemblyInfo.cs file is now returned to
the type system when it calls Project.GetSourceFilesAsync.
Fixes VSTS #753821 - Inline type …
> [DotNetCore] Fix type resolution errors for signed projects

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CSharpCompletionTextEditorExtension.cs
The semantic model might not contain a valid symbol at a given
syntax node which can happen in code that's not compilable.
Prevent that by adding a nullcheck
Fixes VSTS #714055 - AddImportCompletionData null reference exception
> [C#] Fix NRE in completion querying

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CSharpCompletionTextEditorExtension.cs
The semantic model might not contain a valid symbol at a given
syntax node which can happen in code that's not compilable.
Prevent that by adding a nullcheck
Fixes VSTS #714055 - AddImportCompletionData null reference exception
Backport of #6781.
/cc @Therzok
> [release-7.8] [C#] Fix NRE in completion querying

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Highlighting/HighlightUsagesExtension.cs
ActiveDocument does not necessarily point to the document/editor the extension
uses.
Fixes VSTS #761527 - Roslyn fatal exception (System.ArgumentOutOfRangeException)
> [Ide] Possibly fix wrong document being used in HighlightUsages

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreCertificateManager.cs
- main/src/addins/MonoDevelop.AspNetCore/Properties/MonoDevelop.AspNetCore.addin.xml
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Gui/DotNetCoreSdkLocationPanel.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Templating/DotNetCoreProjectTemplateStringTagProvider.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Templating/DotNetCoreProjectTemplateWizard.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Templating/DotNetCoreProjectTemplateWizardPage.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests.csproj
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectSupportedTargetFrameworksTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateWizardTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreSDKResolverTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreNotInstalledDialog.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectSupportedTargetFrameworks.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreRuntime.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdk.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdkInstalledCondition.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdkPaths.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/MonoRuntimeInfoExtensions.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/TargetFrameworkExtensions.cs
- main/src/addins/MonoDevelop.DotNetCore/Properties/MonoDevelop.DotNetCore.addin.xml
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.Helpers/RestoreTestBase.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/DotNetCoreRestoreTests.cs
- main/tests/IdeUnitTests/ProjectTemplateTest.cs
*NOTE: Work In Progress....*
*Rebased (Dec. 18th)*
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/695014
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/729967
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/729979
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/727333
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/729984
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/752729
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/757629
- when global.json is renamed to ie.e global1.json it's not caught by `FileChanged`
- .NET core 3.0 aka.ms is still not available [here](https://github.com/mono/monodevelop/compare/netcoreapp30?expand=1#diff-45fb0e36ce58ce6f9f6622d7a63f948eR41)
- Mono runtime version is …
> [netcore30] Implements netcoreapp30

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Highlighting/HighlightUsagesExtension.cs
ActiveDocument does not necessarily point to the document/editor the extension
uses.
Fixes VSTS #761527 - Roslyn fatal exception (System.ArgumentOutOfRangeException)
Backport of #6825.
> [release-7.8] [Ide] Possibly fix wrong document being used in HighlightUsages

- main/src/addins/MacPlatform/MainToolbar/SearchBar.cs
The searchbar would indiscriminately trigger FocusOut events every
time the window was focused out. That would cause the focus to move
to the next responder when tabbing out.
Fixes VSTS #754535 - Focusing out/into VisualStudio changes the default focused element on the UI
Backport of #6845.
/cc @Therzok
> [release-7.8] [Ide] Fix focus problem when tabbing out of the IDE

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Gui/DotNetCoreSdkLocationWidget.UI.cs
- Fix voice over not reading SDK location label in preferences
The .NET Core SDK location text box was not linked to its label so the
location was not being read by Voice Over.
- Add accessibility title for browse button in sdk location
In preferences the button to browse for a .NET Core SDK location
now has an accessibility title and description.
- Fix accessibility image title in .NET Core sdk location
The .NET Core command line tick/cross image did not have an accessible
label or description. The other tick/cross images for sdk and runtimes
did have this available.
Fixes VSTS #752796 - Accessibility: Voice over is not reading the label for
Location field
> [DotNetCore] Accessibility - Voice over in .NET Core SDK Location preferences

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/MultiConfigItemOptionsPanel.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.OptionPanels/CommonAssemblySigningPreferences.cs
- Fixes VSTS #754211 - Accessibility: Project Options Build Assembly
Signing: Voice over is not reading label for Configuration and Platform
fields
- Fixes VSTS #754272 - Accessibility: Project Options Build Assembly
Signing: Voice over is reading name of the Strong Name File text field
twice
> [Ide] Accessibility - Assembly Signing project options page

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Tests/MonoDevelop.AspNetCore.Tests.csproj
Previous ProjectGuid is repeated, turning back the original one.
> [AspNetCore] Fixes wrong ProjectGuid

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkProjectConfigurationWidget.cs
When the Solution Name text box had focus there was no accessibility
label set for the text box so Voice Over would not read the label text.
Fixes VSTS #754349 - Accessibility New Project Dialog: Voice over is
not reading the Label name for “Solution name” in configure app window
> [Ide] Fix accessibility solution text box label in new project dialog

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/SelectReferenceDialog.cs
The Remote button which is used to remove the selected references
could not get keyboard focus. This is now enabled. Note that the Remove
button still does not get focus if it is clicked only if you tab to
it.
Fixes VSTS #750234 - Accessibility: Remove ‘X’ button is not accessible
through keyboard
> [Ide] Remove button not keyboard accessible in Edit References dialog

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Tests/MonoDevelop.AspNetCore.Tests.csproj
Previous ProjectGuid is repeated, turning back the original one. 
Backport of #6881.
/cc @jtorres
> [release-7.8] [AspNetCore] Fixes wrong ProjectGuid

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.AnalysisCore/Gui/ResultsEditorExtension.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.AnalysisCore/Result.cs
operation could leave the editor in a half updated state. This should
prevent that from happening.
+ Fixed a bug where the quick task update was broken.
> Fixes issue #6730 [8.0p1] C# error squiggles never go away A canceled

- main/src/addins/MonoDevelop.HexEditor/Mono.MHex/HexEditor.cs
- main/src/addins/MonoDevelop.HexEditor/Mono.MHex/HexEditorDebugger.cs
- main/src/addins/MonoDevelop.HexEditor/Mono.MHex/SimpleEditMode.cs
- main/src/addins/MonoDevelop.HexEditor/MonoDevelop.HexEditor/HexEditorVisualizer.cs
HexEditor was completely broken because we where setting Sensitive = false, this means all the signals were not working including Focus and Accessibility.
I added a ReadOnly state to the control and included a feature to announce the current character selected.
NOTE: VoiceOver Announcement needs a little delay between calls
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/648994
Intrucctions to test de issue:
1) Open any console application
2) Set a break point after a declaration of a string variable
3) Inspect this string variable and click in the "pencil icon" to show the "Value Visualizer" panel
4) click on HexEdit button
5) Enable VoiceOver and change the selected item with CAPSLOCK + Arrow keys
6) VoiceOver should set the HexEditor and announce the hexadecimal value …
> [a11] Fixes VoiceOver to announce hexadecimal content

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads/MonodocTreePad.cs
Don't trigger MonoDoc when selection changes
Allow rows to be expanded by the keyboard
Fixes VSTS #753478
Fixes VSTS #753484
> [A11y] Accessibility fixes for the Help Pad

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.OptionPanels/CustomCommandWidget.cs
Keyboard focus was moving from the custom command combo box to the
first text entry in the new custom command just created. The keyboard
focus now stays on the combo box after an item is selected from its
list.
Fixes VSTS #753595 - Accessibility: Project Options Custom Commands:
After selecting any option in Select a project Operation drop down focus
is going to command text field. It should stay on the same control
> [Ide] Fix focus after adding new custom command in project options

- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/MacToolboxWidget.cs
FrameChangedNotification executes more often than the normal expected with the frame change. 
Because this problem we changed to use SetFrameSize method which is called the times we expect.
The average time it takes to load is not very significant, since elements are virtualized and only the ones on the screen are rendered, but something improves.
NOTE: in the screenshots "RedrawItems" = Frame Resize Items
Before:
After:
>  Improves the number of calls resizing ToolboxItems

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Tabstrip.cs
Inserted tabs may bump previous tabs to the right, so update all the bounds
Fixes VSTS #752791
> [A11y] Update the bounds of the Tabstrip tabs when one is inserted

- main/src/addins/MonoDevelop.HexEditor/Mono.MHex/HexEditor.cs
- main/src/addins/MonoDevelop.HexEditor/Mono.MHex/HexEditorDebugger.cs
- main/src/addins/MonoDevelop.HexEditor/Mono.MHex/SimpleEditMode.cs
- main/src/addins/MonoDevelop.HexEditor/MonoDevelop.HexEditor/HexEditorVisualizer.cs
HexEditor was completely broken because we where setting Sensitive = false, this means all the signals were not working including Focus and Accessibility.
I added a ReadOnly state to the control and included a feature to announce the current character selected.
NOTE: VoiceOver Announcement needs a little delay between calls
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/648994 - Accessibility: Voiceover: MAS4.2.1: Voiceover doesn't announce the hexadecimal content in "Value Visualizer" window
Intrucctions to test de issue:
1) Open any console application
2) Set a break point after a declaration of a string variable
3) Inspect this string variable and click in the "pencil icon" to show the "Value Visualizer" panel
4) click on HexEdit button
5) Enable VoiceOver and change the …
> [release-7.8] [a11] Fixes VoiceOver to announce hexadecimal content

- main/src/addins/MonoDevelop.Packaging/Gui/MonoDevelop.Packaging.Gui.GtkNuGetPackageMetadataOptionsPanelWidget.cs
- main/src/addins/MonoDevelop.Packaging/MonoDevelop.Packaging.Gui/GtkNuGetPackageMetadataOptionsPanelWidget.cs
**Fix language metadata accessibility in project options**
Tabbing to the language combo box in project options - NuGet Package -
Metadata would not announce the label associated with the combo box
with Voice Over. The problem is that the combo box with an enabled
text entry does not work well with the accessibility library. To
fix this the combo box no longer allows free text entry. If no
language is selected then 'None' is displayed.
Fixes VSTS #753486 - Accessibility: NuGet Package Metadata: Voice
Over is not reading the label of the "Language" combo box.
Fixes VSTS #753489 - Usability: NuGet Package Metadata: Text area
inside the "Language" combo box does not serves any purpose and seems
not to be useful in this scenario.
**Show language display name in project options for metadata** …
> [Packaging] Accessibility - NuGet packaging metadata

- main/src/addins/MonoDevelop.Packaging/MonoDevelop.Packaging.Gui/GtkProjectNuGetBuildOptionsPanelWidget.cs
In project options - NuGet Package - Build the check box to enable creation
of a NuGet package at build time will show a warning label if there is no
associated package metadata defined for the project. This warning label was
not being read by voice over when the check box is selected. Now the
accessibility text is updated and includes the warning text if it is applies
so this is now read by voice over when the check box is selected.
Fixes VSTS #753475 - Accessibility: Voice Over is not reading the alert text
revealed after the "Create a NuGet Package" checkbox is checked.
> [Packaging] Fix voice over not reading warning label in project options

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/SearchEntry.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/FindInFilesDialog.cs
- Fixed Voice Over reading accessibility text for some UI controls.
- Fixed Voice Over Look in combo box not reading label text.
- Fixed ellipsis used in browse button.
- Fixed Voice Over not describing browse button.
- Fixed Voice Over saying 'Search' for the File Mask text entry.
Still a problem with the combo box with enabled text entry which is
not fixed here. This may be fixed in AtkCocoa at some point.
Otherwise the dialog would need to be changed to use a MenuButton.
Fixes VSTS #752731 - Accessibility: Voice Over is not reading the
labels for text fields
> [Ide] Fix accessibility Voice Over problems in Find in Files dialog

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Highlighting/HighlightUsagesExtension.cs
ActiveDocument does not necessarily point to the document/editor the extension
uses.
Fixes VSTS #761527 - Roslyn fatal exception (System.ArgumentOutOfRangeException)
Backport of #6825.
> [release-7.7] [Ide] Possibly fix wrong document being used in HighlightUsages

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/PolicyOptionsPanel.cs
The standardard header options panel and the .NET naming policy
options panel would cause Voice Over to read the accessibility text
multiple times when using the arrow keys. The parent policy options
class now wraps the Gtk.VBox in a Gtk.Bin which fixes the problem.
Fixes VSTS #752365 - Accessibility: Voice Over is reading few controls
(Warning and the content provided after that icon) twice when user is
navigating using "Control + Option + Right arrow".
Fixes VSTS #753328 - Accessibility: Net Naming Policies: Voice Over is
reading few controls(Warning and the content provided after that icon)
twice when user is navigating using "Control + Option + Right arrow".
> [Ide] Fix Voice Over reading UI controls multiple times in options

- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Styles.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeTemplates/CodeTemplatePanel.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Styles.cs
- main/src/core/MonoDevelop.Ide/gtkrc
- main/src/core/MonoDevelop.Ide/gtkrc.mac
- main/src/core/MonoDevelop.Ide/gtkrc.mac-dark
- main/src/core/MonoDevelop.Ide/gtkrc.win32
- main/src/core/MonoDevelop.Ide/gtkrc.win32-dark
These two commits fix color accessibility issues in these areas:
- Secondary (gray) text color now matches required 4.5:1.
- New macOS selection background which follows changes in macOS Mojave.
Fixes VSTS #612400
Fixes VSTS #754225
> Gtkrc a11y fixes

- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/CodeTemplateToolboxProvider.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/IToolboxProvider.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/MacToolbox.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/ToolboxService.cs
- main/src/addins/MonoDevelop.GtkCore/MonoDevelop.GtkCore.GuiBuilder/ToolboxProvider.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/ClipboardRingService.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs
This fix fixes the possibility to delete items from external toolbox providers (like for example clipboard copied items). Right now this deletion was doing nothing and was confusing the user.
Fixes VSTS #598533 - Unable to delete entries from Toolbox Clipboard Ring https://devdiv.visualstudio.com/DevDiv/_workitems/edit/598533
To test the bug:
1) Open a project
2) Select and copy from the clipboard any text from Source Editor
3) A new item should appear in the Toolbox in a new section called Clipboard Ring
4) Click right button and select Remove menu item
Probably this PR will break the current API
> Adds implementation to remove items in Toolbox Dynamic Providers

- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/TextEditorData.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/ISyntaxHighlighting.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/770635
At least it'll help to find the real cause. Added segment == null
check which is a guess which would expose an issue in the syntax mode
implemention. From where that method is called line is always != null.
Backport of #6922.
> [release-7.8] Fixes VSTS Bug 770635: NRE in TextEditorData.GetChunks

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/TextEntryWithCodeCompletion.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/KeyDescriptor.cs
Replace the Gtk specific code with Xwt equivalents
> [Debugger] Remove Gtk use from the New Breakpoint dialog

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/Extensions.cs
Now that we have a separate window (Start Window), we need to make
sure we show the main window if it's not visible for operations that
rely on the main window being shown, like is the case for Run->Debug
Application.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/770996
> [Debugger] Show main window when debugging app

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.PropertyGrid.Editors/EventEditor.cs
In case of crating an Event editor with a instance that desn't inherit from IComponent this thows a NRE breaking the IDE.
This commit, returns null creating this Editor which is covered by the current implementation
> Fixes NRE in case of bind a instance non IComponent

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.addin.xml
Xamarin.Ide uses this assembly and may need it to be registered. When running some tests via `mdtool` I have seen a failure to load the ide addin because this was not found.
Backport of #6795.
/cc @mrward @sgmunn
> [release-7.8] [Nuget] Add import NuGet.common.dll

- main/src/addins/MacPlatform/MainToolbar/SelectorView.cs
Fixes VSTS 648190 - Accessibility: Keyboard: MAS2.4.3: Focus order is inappropriate while navigating in reverse order in the toolbar.
https://devdiv.visualstudio.com/DevDiv/_queries/edit/648190/?triage=true
To test the issue:
- Open VS4Mac
- Click on the Global Search box
- Press Shift + Tab/Tab to move the focus between the views
- Ensure you can access all buttons in the correct order
>  Fixes calculate of the next focused view in SelectorView

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.ProjectData.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.ProjectDataMap.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.ProjectSystemHandler.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/TypeSystemService.cs
We were using a sync lock on async/await transitioning between threads (i.e. marshal to UI thread).
That caused code to cause a hang, because the UI thread was already locking on the data structure and waiting
for the background thread to release.
Introduce a SemaphoreSlim async lock that can be used instead.
Should fix problems like the above stacktrace:
```
"GUI Thread"  at <unknown> <0xffffffff>
at (wrapper managed-to-native) object.__icall_wrapper_mono_monitor_enter_v4_internal (object,intptr) [0x00008] in <98fac219bd4e453693d76fda7bd96ab0>:0
at MonoDevelop.Ide.TypeSystem.MonoDevelopWorkspace/ProjectDataMap.GetData (Microsoft.CodeAnalysis.ProjectId) [0x00000] in /Users/vsts/agent/2.144.0/work/1/s/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace. …
```
> Locking hierarchy changes in MonoDevelopWorkspace

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Composition/CompositionManager.Caching.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Composition/CompositionManager.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Composition/CompositionManager.CachingTests.cs
All assemblies now register their referenced assemblies into the composition cache file
(with the exception of assemblies which cannot be found, which will be reported
anyway by the MEF discovery error reporting).
With this, we can now invalidate the cache on assembly dependency changes and
on GAC changes (i.e. mono upgrade)
Fixes VSTS #734010 - MEF cache should invalidate on framework or dependency changes
> [MEF] Add metadata about referenced assemblies into the MEF cache

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/DotNetCoreRestoreTests.cs
- main/tests/test-projects/restore-netcore-offline/dotnetcoreconsole.csproj
2.1 is the version we ship, as it's the latest stable LTS, and is the one
we provision in CI, so make sure all tests are ran on the officially
supported .NET Core version.
> [Tests] Move restore-netcore-offline test project back to 2.1

- main/tests/test-projects/restore-netcore-offline/dotnetcoreconsole.csproj
2.1 is the version we ship, as it's the latest stable LTS, and is the one
we provision in CI, so make sure all tests are ran on the officially
supported .NET Core version.
Backport of #7005.
/cc @rodrmoya
> [release-7.8] [Tests] Move restore-netcore-offline test project back to 2.1

- main/src/addins/CSharpBinding/CSharpBinding.addin.xml
- main/src/addins/CSharpBinding/CSharpBinding.csproj
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Parser/CSharpFoldingParser.cs
Seems that the folding parser was still used for that. This is the easiest solution to the issue. 
Query that info before the opening can lead to long delays - folding it afterwards leads to screen updates/unwanted scrolling.
Another viable option would be to remove this functionality @slluis  what do you say to that ?
As far as I can see VS.NET does not offer that. 
Maybe we can remove that and make an external addin out of it ? I think this may be a doable option - then ppl who want that can just install it using the addin functionality.
> Bug 746222: [Feedback] Fold Regions By Default has no effect

- main/src/addins/MacPlatform/MainToolbar/SelectorView.cs
PathSelectorView has 3 "sections", one of them being, for some kind of
projects/setups, hidden, but the code was assuming all of them were
always visible when responding to responder chain events. Now make sure
only visible items are processed so that there is never focus loss.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/753499
> [MacPlatform] Ignore hidden items in responder chain

- main/src/core/MonoDevelop.Ide/ExtensionModel/Commands.addin.xml
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/NewFolderDialog.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/FolderNodeBuilder.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
Due to various problems with the Solution window when adding a new
folder directly into the tree and then editing the label, instead
a New Folder dialog is used when creating a new folder for a project.
Fixes VSTS #721437 Can't focus on a folder and name it during creation.
Needs a UI review. Is using a separate message alert for errors OK or should an icon + text be in the dialog itself?
Also has some voice over problems since the native XWT toolkit is being used - there is a bug open for one problem about not announcing the label for the text box - also seeing odd behaviour with the alert message being in the wrong position and the text is not selected, unlike over alert dialogs.
> [Ide] Add New Folder dialog for adding new folders

- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/ToolboxPad.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/GtkWorkarounds.cs
Fixes VSTS #783919 - Unable to Drag and Drop controls to Main.storyboard via search from Tool Box
Backport of #7024.
/cc @Therzok
> [release-7.8] [Toolbox] Fix event ownership, double free and assertion on trying to free a null event

- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/ToolboxPad.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/GtkWorkarounds.cs
Fixes VSTS #783919 - Unable to Drag and Drop controls to Main.storyboard via search from Tool Box
> [Toolbox] Fix event ownership, double free and assertion on trying to free a null event

- .gitignore
- main/tests/StressTest/Mono.Profiling.Log/LogEnums.cs
- main/tests/StressTest/Mono.Profiling.Log/LogEventVisitor.cs
- main/tests/StressTest/Mono.Profiling.Log/LogEvents.cs
- main/tests/StressTest/Mono.Profiling.Log/LogProcessor.cs
- main/tests/StressTest/Mono.Profiling.Log/LogStreamHeader.cs
- main/tests/StressTest/MonoDevelop.StressTest/ProfilerProcessor.cs
- main/tests/StressTest/MonoDevelop.StressTest/StressTestApp.cs
- main/tests/StressTest/StressTest.csproj
Changes under `main/tests/StressTest/Mono.Profiling.Log/` are just copied files from mono repo.
Changes in `ProfilerProcessor.cs` are mostly just modernization of arguments.
Change to include TargetFrameworks.props in StressTest.csproj is actual fix actually.
`ReportMemoryUsage (-1);` is to take heapshot/show memory even before 1st iteration.
> Fix strees test and improvements to memory profiling

- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/IToolboxWidget.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/MacToolbox.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/MacToolboxWidget.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/ToolboxPad.cs
This PR fixes ensure we set the correct selected element in Toolbox to start a drag and drop operation
When we were filtering the toolbox was not correctly updating this.
Fixes VSTS #783919 - Unable to Drag and Drop controls to Main.storyboard via search from Tool Box
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/783919
To test the issue:
1) Create iOS single view application and open main.storyboard
2) Drag any control from toolbox (Lets say Button) to storyboard file
3) Then search (Type Label) any other control from Toolbox - search and try to drag to storyboard file
> [Toolbox] Fixes toolboxService is allways in sync with toolbox selected item

- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/IToolboxWidget.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/MacToolbox.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/MacToolboxWidget.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/ToolboxPad.cs
This PR fixes ensure we set the correct selected element in Toolbox to start a drag and drop operation
When we were filtering the toolbox was not correctly updating this.
Fixes VSTS #783919 - Unable to Drag and Drop controls to Main.storyboard via search from Tool Box
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/783919
To test the issue:
1) Create iOS single view application and open main.storyboard
2) Drag any control from toolbox (Lets say Button) to storyboard file
3) Then search (Type Label) any other control from Toolbox - search and try to drag to storyboard file
> [release-7.8] [Toolbox] Fixes toolboxService is allways in sync with toolbox selected item 

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/BlameView.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/BlameWidget.cs
This issue, allow switch between Source code and Authors tab and respect the current line selected with the same scroll position
Fixes VSTS #596859 - usability: switching to Authors tab should jump to the context line, not to "cached" line state
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/596859
> [VersionControl] Matches scrollarea in authors tab with its source editor

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/StatusView.cs
MERP / Dr Watson shows this as one of the most frequent crashes seen in VSMac
```
Fault:       Crash
thread 0:
NativeFrames:0
System.Core.dll!Enumerable.Where+ffffffff
MonoDevelop.VersionControl.dll!StatusView.<StartUpdate>b__53_0+f8
mscorlib.dll!QueueUserWorkItemCallback.WaitCallback_Context+d
mscorlib.dll!ExecutionContext.RunInternal+71
mscorlib.dll!ExecutionContext.Run+0
mscorlib.dll!QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem+21
mscorlib.dll!ThreadPoolWorkQueue.Dispatch+74
mscorlib.dll!_ThreadPoolWaitCallback.PerformWaitCallback+0
```
StartUpdate can be called from multiple locations:  StatusView.Init,
StatusView.OnShowRemoteStatusClicked, StatusView.OnRefresh,
StatusView.OnFileStatusChanged, …
> Add a lock to version control file list status view updates

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AtkCocoaHelper/AtkCocoaHelperMac.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/Messaging.cs
By using native NSMutableArrays we avoid copying a lot of arrays between
native and managed, thus avoid a lot of GC pressure that can happen while
modifying a11y properties.
> [A11y] Fix up memory pressure caused by lots of arrays being created

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/DiffView.cs
MERP is showing this to be one of the most frequent crashes in VSMac
```
What do    Fault:       Crash
thread 0:
NativeFrames:0
mscorlib.dll!StreamReader..ctor+7d
mscorlib.dll!StreamReader..ctor+0
mscorlib.dll!StreamReader..ctor+0
mscorlib.dll!0+ffffffff (UNKNOWN METHOD TOKEN)
mscorlib.dll!File.ReadAllText+0
2e1bd13d-1d4c-4710-a616-e6c613c698ed!60001e3+ffffffff (UNKNOWN MVID)
2e1bd13d-1d4c-4710-a616-e6c613c698ed!600004a+ffffffff (UNKNOWN MVID)
MonoDevelop.VersionControl.dll!DiffView.get_Control+1d
MonoDevelop.Ide.dll!60057d3+8 (UNKNOWN METHOD TOKEN)
MonoDevelop.Ide.dll!Tab.OnActivated+a
MonoDevelop.Ide.dll!Tab.set_Active+f
MonoDevelop.Ide.dll!Tabstrip.set_ActiveTab+28
MonoDevelop.Ide.dll!Tabstrip.OnButtonPressEvent+8 …
```
> Catch errors when setting repository text in the diff view

- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Core/ProgressMonitorTests.cs
This should make the test able to handle the difference in call counts that is introduced by updating to a newer version of mono. I wasn't able to identify what specific file changed (since we have 8000 different TextWriters in-tree) but the change in call counts matches what I see in the corefx source.
Hard to test locally so MD CI should tell me whether this works against older BCL, and then the other CI I hit the bug on will tell me whether I've fixed the issue...
> Update TestLogSynchronizationContextThroughWrites to work against both old and new BCL TextWriter implementations

- main/build/MacOSX/Info.plist.in
When a request was made for a non-secure http url, such as when trying
to use the debugger image visualizer with a Xamarin.Forms UriImageSource,
the image would not be displayed on the Mac when using Xamarin.Mac's
NSUrlSessionHandler with the HttpClient. In the Application Output
you would see an error:
Failed to load image: System.Net.WebException: The resource could not
be loaded because the App Transport Security policy requires the use
of a secure connection.
To allow non-secure http requests the NSAppTransportSecurity property
has been set to NSAllowsArbitraryLoads in the Info.plist file.
Fixes VSTS #776217 - [NSURLSession] Image from Xamarin.Forms.UriImageSource
is not displayed in the debugger’s visualiser window when debugging a
Xamarin.Forms application
> [Mac] Allow non-secure http requests when NSUrlSession used

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.AnalysisCore/Gui/ResultsEditorExtension.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding.Refactoring/CSharpResultsEditorExtensionTests.cs
t's possible that the cancellation finish gets in the way of the new
idle handler. At least it all runs now on the UI thread and the
updaters are all canceled properly on dispose and before the new one
is started.
> Fixes VSTS Bug 786750: Error squiggles are sometimes not up to date

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/LogView.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/LogWidget.cs
This fix solves how we handle Copy command in Log window.
It takes into account the selected element and sets the correct text into the clipboard.
Fixes VSTS #790406 - Log view: Copy command doesn’t respect the focus and always copies the diff of the selected entry (should copy selected text, if any selected in the log description)
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/790406
> [SourceControl] Fixes Copy Command in Log window based in view selected

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValueTreeView.cs
MERP / DR Watson shows this as one of the most frequent crashes in VSMac
```
Fault:       Crash
thread 0:
NativeFrames:0
MonoDevelop.Debugger.dll!ObjectValueTreeView.UnregisterValue+0
MonoDevelop.Debugger.dll!ObjectValueTreeView.RefreshRow+13
MonoDevelop.Debugger.dll!ObjectValueTreeView.OnButtonPressEvent+89
40f46e55-eb67-454a-b904-dc9e5644a3a1!6003ba7+16 (UNKNOWN MVID)
```
Ensure that object value can never be null when calling UnregisterValue. It was
checked from some call sites previously, but not all.
> Harden the null checking around unregistering object val in debugger

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/DockContainer.cs
MERP / Dr Watson show this as one of the most frequent crashes in VSMac
```
Fault:       Crash
thread 0:
NativeFrames:0
MonoDevelop.Ide.dll!DockContainer.UpdatePlaceholder+20
MonoDevelop.Ide.dll!DockFrame.UpdatePlaceholder+0
MonoDevelop.Ide.dll!DockItemTitleTab.OnMotionNotifyEvent+d0
40f46e55-eb67-454a-b904-dc9e5644a3a1!6003c23+16 (UNKNOWN MVID)
```
which points to `placeholderWindow.AllowDocking = allowDocking;` as the line
that is failing.
It isn't obvious at all how placeholderWindow could ever be null at this point.
(I don't see access to the placeholderWindow field from threads other than the
UI), so I have just made the method more robust.
> Defensive programming in Dock Container

- main/src/addins/MonoDevelop.UnitTesting/Services/SolutionFolderTestGroup.cs
Fixed problem deleting project folder. If the project uses Version Control (Git), the changes in the Commit view were not reflected.
The problem was disposing the `SolutionFolderTestGroup`. After failing here, the changes in the Commit view were not notified.
Fixes gh #7107
> [UnitTesting] Fix NRE when disposing

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
To avoid the `LibGit2Sharp.AmbiguousSpecificationException: More than one file matches the pathspec` problems, added the following changes:
- Use the parameter `DisablePathSpecMatch` getting the folder status. More information: https://github.com/libgit2/libgit2sharp/blob/master/LibGit2Sharp/StatusOptions.cs#L86
- Added the file validation (not directory) getting the file status.
Fixes gh #7109
> [VersionControl] Fix error getting File Status (Git)

- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Core.Assemblies/SystemAssemblyServiceTests.cs
see https://github.com/xamarin/md-addins/pull/4200
this fixes the expected version of xwt.dll when running tests.
> [Core] Fix version of Xwt that should be expected when running tests

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CompletionProvider/DelegateCompletionProvider.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/RoslynCompletionData.cs
Assert.That(tes pops up a Create method dialog that gets in the way
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/763702
The old CompletionWindowManager hack doesn't work in this case - so I
introduced a pseudo-parameter (can't change that API or use it in any
sane way). A roslyn refactoring is requesting now the changes and that
happens during completion as well - that's why the insert windows are
popping up. This prevents that from happening.
> Fixes VSTS Bug 763702: [Feedback] Using NUnit, typing inside

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitConfigurationDialog.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
We get an error trying to fetch the path to a remote branch. If a branch is selected, we will look for the parent element to obtain the appropriate path.
Fixes gh #7104
> [VersionControl] Fixed error fetching from Git server

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Dialogs/SelectRepositoryDialog.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/UrlBasedRepositoryEditor.cs
If the Checkout dialog is opened and the button is pressed (without entering an URL), it starts by trying to delete the content of the Target Directory folder. 
Disabled Checkout button without a repository Url.
Fixes gh #7120
> [VersionControl] Add validations to Checkout process

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/GtkNotebookResult.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/GtkTreeModelResult.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/GtkWidgetResult.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/NSObjectResult.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/ObjectResult.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AppQuery.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AppResult.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestClientSession.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestSession.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopPersistentStorageLocationService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.ProjectDataMap.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspaceProjectDataMapTests.cs
- main/tests/StressTest/MonoDevelop.StressTest/StressTestApp.cs
- main/tests/UserInterfaceTests/Ide.cs
This mitigates the leak that happen at the workspace level by making the leak really small (just the workspace instance with no data in it).
This should help with our current situation where we leak ~everything.
There's still a few leaks here and there, but I'll open a different PR for that, as I have automated the leak retention process using the stress test tool.
Fixes VSTS #788777 - Change the MonoDevelopWorkspace model to have a primary and secondary workspaces
Should supersede https://github.com/mono/monodevelop/pull/7159
> [Roslyn] Fixes multiple leaks in the workspace integration

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/CheckoutCommand.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/MessageService.cs
Using `MessageService.RunCustomDialog` we got an exception (Null) under certain situations. For example: Trying to open the Checkout dialog without open any solution, etc. The problem is that `RootWindow` in `MessageService` is null.
Fixed by changing validation in WelcomePage that affects the RootWindow search in `MesageService`.
Fixes gh #7108
> Fixed error opening Dialogs using MessageService

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Tabstrip.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextEditor.cs
MERP shows this stacktrace as one of the most frequent crashes in VSMac
```
Fault:       Crash
thread 0:
NativeFrames:0
MonoDevelop.SourceEditor.dll!SourceEditorView.MonoDevelop.Ide.Editor.ITextEditorImpl.get_EditorExtension+0
MonoDevelop.Ide.dll!TextEditor.GetContents+21
Xamarin.AndroidDesigner.MonoDevelop.dll!LayoutSourceEditorView.OnGetContents+31
MonoDevelop.Ide.dll!BaseViewContent.GetContents+0
MonoDevelop.Ide.dll!BaseViewContent.GetContent+0
Xamarin.AndroidDesigner.MonoDevelop.dll!AndroidDesignerView.OnGetContent+1c
MonoDevelop.Ide.dll!6005794+1e (UNKNOWN METHOD TOKEN)
System.Core.dll!Enumerable.TryGetFirst+ffffffff
System.Core.dll!Enumerable.FirstOrDefault+ffffffff
MonoDevelop.Ide.dll!BaseViewContent.GetContent+0 …
```
> Check for disposed TextEditor when retrieving GetContents<T>

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/CaretImpl.ITextCaret.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/CaretImpl.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/Caret.cs
launchSettings.json
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/749965
PositionChanged_ITextCaret tried to calculate an old caret position
using the current buffer - that may fail on certain buffer changed
events. Now the coordinates are calculated using the snapshot which
was valid to the former caret location.
> Fixes VSTS Bug 749965: Fatal error on copy + paste in

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/BlameWidget.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/VersionControl.addin.xml
In the Authors tab, there is a history of all the users that modified the file in the right panel.
When we press Show "authors before this change", our context has changed with new information, but there is no way to go back to the author's page.
This PR adds a new command to go back  to previous blame
Fixes VSTS #790407 - Blame view: no way back in history (once you select to show blame before the current, you can’t come back)
https://devdiv.visualstudio.com/DevDiv/_queries/edit/790407/?triage=true
> [SourceControl] Add a new command to go back  to previous blame

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/OnTheFlyFormattingPanel.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices.Options/RoslynPreferences.Properties.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices.Options/RoslynPreferences.cs
Fixes VSTS #795488 - Serialization error on enabling paste on format for
editor
> Use bound configuration properties for OnTheFlyFormatting options

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/EditBranchDialog.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitConfigurationDialog.cs
The first thing I considered is to add validations in the name of branches. Libgit2 has a method for it: https://libgit2.org/libgit2/#HEAD/group/reference/git_reference_is_valid_name
But we are using it: http://source.monodevelop.com/#MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/EditBranchDialog.cs,126
With this changes, show an error message to notify the user that there has been a problem creating the branch.
Fixes gh #7106
> [VersionControl] Error creating branches 

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/SdiWorkspaceWindow.cs
and don't SelectWindow, which would result in an infinite loop
activating the tab and selecting the window over and over again.
Fixes VSTS #797754
Backport of #7200.
/cc @sevoku
> [release-7.8] [Ide] Just let the content GrabFocus when document tab is activated

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/SdiWorkspaceWindow.cs
and don't SelectWindow, which would result in an infinite loop
activating the tab and selecting the window over and over again.
Fixes VSTS #797754
> [Ide] Just let the content GrabFocus when document tab is activated

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/Repository.cs
Fixes and error validation paths publishing a project to a Git repository. 
Fixes also another issue trying to publish a project and canceling the process. In these cases the folder .git was created and MD manage the project as if it were under VCS.
Fixes gh #7175 
Fixes gh #7163
> [VersionControl] Fixes an error publish a project to Git

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
After the LibGit2 update focusing out of the credentials dialog and back causes a deadlock in the Push operation, because the operation is blocking and lets solution node updaters (on main IDE focus in) wait until it finishes.
Fixes VSTS #798005
> [Git] Pushing should not be blocking

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Tasks/CommentTasksProvider.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.ProjectSystemHandler.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/TypeSystemService_WorkspaceHandling.cs
If a Workspace is disposed before load is finished, we would have a NRE on trying to add to the ConcurrentDictionary. Prevent that from happening.
Fixes VSTS 797986 - Unloading a solution while it's being loaded by the roslyn workspace can lead to NRE
> [Roslyn] Fix NRE of solution when cancelling load

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/DotNetCoreNuGetProjectTests.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/DotNetCoreNuGetProject.cs
Handle a project being disposed when checking to see if it supports
NuGet. A disposed project will have a null MSBuildProject property.
Fixes VSTS #797960 - Null reference in DotNetCoreNuGetProject
> [NuGet] Fix possible NullReferenceException

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.csproj
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/CheckForNuGetPackageUpdatesTaskRunner.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/ExceptionExtensions.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageManagementEventsMonitor.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/UpdatedNuGetPackagesProvider.cs
Check the exception is not an OperationCanceledException when logging
failures on NuGet restore and check for updates.
Fixes VSTS #797961 - Task canceled error logged when checking for
updates
> [NuGet] Do not log errors for canceled tasks

- main/src/addins/VersionControl/MonoDevelop.VersionControl/Gui/MonoDevelop.VersionControl.Views.LogWidget.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/LogView.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/LogWidget.cs
Replaces the current Gtk menu to use a native one.
Fixes VSTS #790405 - [Source Control] Log view: no native context menus
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/790405
> [SourceControl] Adds a Native a contextual menu in Log Window

- main/src/addins/VersionControl/MonoDevelop.VersionControl/Gui/MonoDevelop.VersionControl.Views.LogWidget.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/LogView.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/LogWidget.cs
Replaces the current Gtk menu to use a native one.
Fixes VSTS #790405 - [Source Control] Log view: no native context menus
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/790405
Backport of #7165.
> [release-8.0-integration] [SourceControl] Adds a Native a contextual menu in Log Window

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.UI.cs
Doing so means the dialog is visible before actually running it via
MessageService, which tries to retrieve the current focused window,
which would be the NPD dialog itself, completely breaking the
child window positioning code.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/796030
> [Ide] Don't show NPD in its "constructor"

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.UI.cs
Doing so means the dialog is visible before actually running it via
MessageService, which tries to retrieve the current focused window,
which would be the NPD dialog itself, completely breaking the
child window positioning code.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/796030
Backport of #7232.
/cc @rodrmoya
> [release-8.0-integration] [Ide] Don\u0027t show NPD in its \u0022constructor\u0022

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AtkCocoaHelper/AtkCocoaHelperMac.cs
```
=================================================================
Managed Stacktrace:
=================================================================
at MonoDevelop.Components.Mac.Messaging:IntPtr_objc_msgSend <0x00064>
at MonoDevelop.Components.AtkCocoaHelper.AtkCocoaMacExtensions:AddElementToTitle <0x000ba>
at MonoDevelop.Ide.WelcomePage.WelcomePageSection:SetTitledWidget <0x000ca>
at MonoDevelop.Ide.WelcomePage.WelcomePageRecentProjectsList:RecentFilesChanged <0x0033a>
at MonoDevelop.Ide.WelcomePage.WelcomePageRecentProjectsList:.ctor <0x0022a>
at MonoDevelop.Ide.WelcomePage.DefaultWelcomePage:BuildContent <0x006ea>
at MonoDevelop.Ide.WelcomePage.WelcomePageWidget:.ctor <0x001f9>
at MonoDevelop.Ide.WelcomePage.DefaultWelcomePage:.ctor <0x0001a>
at …
```
> [release-8.0-integration] Fix Add/Remove Element to Title selector

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AtkCocoaHelper/AtkCocoaHelperMac.cs
```
=================================================================
Managed Stacktrace:
=================================================================
at MonoDevelop.Components.Mac.Messaging:IntPtr_objc_msgSend <0x00064>
at MonoDevelop.Components.AtkCocoaHelper.AtkCocoaMacExtensions:AddElementToTitle <0x000ba>
at MonoDevelop.Ide.WelcomePage.WelcomePageSection:SetTitledWidget <0x000ca>
at MonoDevelop.Ide.WelcomePage.WelcomePageRecentProjectsList:RecentFilesChanged <0x0033a>
at MonoDevelop.Ide.WelcomePage.WelcomePageRecentProjectsList:.ctor <0x0022a>
at MonoDevelop.Ide.WelcomePage.DefaultWelcomePage:BuildContent <0x006ea>
at MonoDevelop.Ide.WelcomePage.WelcomePageWidget:.ctor <0x001f9>
at MonoDevelop.Ide.WelcomePage.DefaultWelcomePage:.ctor <0x0001a>
at …
```
> Fix Add/Remove Element to Title selector

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/MergeView.cs
Hiddes merge tab in case of no conflicting file
Fixes VSTS #790409 - Merge view: should be hidden if there is no merge pending for the current file
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/790409
> [SourceControl] Hiddes merge tab in case of no conflicting file

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/MergeView.cs
Hiddes merge tab in case of no conflicting file
Fixes VSTS #790409 - Merge view: should be hidden if there is no merge pending for the current file
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/790409
Backport of #7177.
> [release-8.0-integration] [SourceControl] Hiddes merge tab in case of no conflicting file

- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/MessageService.cs
This PR fixes NRE trying to show the TextQuestionDialog because expects a Gtk window but it's getting an NSWindow.  
Just fixed GetParentForModalWindow to also check NSApplication.SharedApplication.ModalWindow and RunCustomDialog now calls CenterWindow.
Probably with this change is also **fixed focus the parent view in natives modal views**, because the parent was not well calculated.
Fixes Bug #802168 - Android app archive and publishing is broken - fails at MessageService.GetPassword.
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/802168
> Fixes Open current TextQuestionDialog using centralized RunCustomDialog

- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/MessageService.cs
This PR fixes NRE trying to show the TextQuestionDialog because expects a Gtk window but it's getting an NSWindow.  
Just fixed GetParentForModalWindow to also check NSApplication.SharedApplication.ModalWindow and RunCustomDialog now calls CenterWindow.
Probably with this change is also **fixed focus the parent view in natives modal views**, because the parent was not well calculated.
Fixes Bug #802168 - Android app archive and publishing is broken - fails at MessageService.GetPassword.
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/802168
Backport of #7265.
> [release-8.0-integration] Fixes Open current TextQuestionDialog using centralized RunCustomDialog

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Dialogs/SelectRepositoryDialog.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/MessageService.cs
When we were opening the SelectRepositoryDialog (Checkout menu), this window was appearing always on top of all other system windows, this was because we were not set correctly the Parent in this GTK.Dialog when the parent window was native because this parent was null.
Included the case in our RunCustomDialog from MessageService, to handle this in all dialogs with the same problem.
Also Removed Minimize and Maximize button from the window toolbar 
Fixes VSTS #801733 - [x] When cloning a git repo starting from GTC, SCC dialogs appear on top of other apps.
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/801733
Fixes VSTS #801737 - - [x] Select Repository doesn't re-appear after being hidden and reactivated (staring with GTC) …
> Fixes remove minimize and maximize from SelectRepositoryDialog + allways on top

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Dialogs/SelectRepositoryDialog.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/MessageService.cs
When we were opening the SelectRepositoryDialog (Checkout menu), this window was appearing always on top of all other system windows, this was because we were not set correctly the Parent in this GTK.Dialog when the parent window was native because this parent was null.
Included the case in our RunCustomDialog from MessageService, to handle this in all dialogs with the same problem.
Also Removed Minimize and Maximize button from the window toolbar 
Fixes VSTS #801733 - [x] When cloning a git repo starting from GTC, SCC dialogs appear on top of other apps.
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/801733
Fixes VSTS #801737 - - [x] Select Repository doesn't re-appear after being hidden and reactivated (staring with GTC) …
> [release-8.0-integration] Fixes remove minimize and maximize from SelectRepositoryDialog + allways on top

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpSymbolHelper.fs
> Retrieve editor markup on the UI thread. Fixes F# tooltips.

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.Visualizer/TextVisualizer.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ExceptionCaughtDialog.cs
Change focus from current selected object was broken in  "Exception Caught" window.
This fix allows navigating between views pressing tab key in both directions and changes link labels to use buttons, which are more accessibility friendly and focusable.  
Fixes VSTS #646443 Accessibility: Keyboard: MAS2.1.1: "Stacktrace, Properties" buttons and the contents under "Stacktrace" button and "More information" link in "Exception Caught" window is not accessible using keyboard.
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/646443
Fixes VSTS #646442  Accessibility: Keyboard: MAS2.4.3: Focus order is inappropriate in "Exception Caught" window
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/646442
Exception Caught dialog changes depending the exception catched, but a good exception …
> Fixes broken focus chain in "Exception Caught" window

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpSymbolHelper.fs
Fixes VSTS #802684 (#7254)
Backport of #7282.
/cc @nosami
> [release-7.8] Retrieve editor markup on the UI thread. Fixes F# tooltips.

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlService.cs
Fixes `Could not query Git repository reference` errors and avoids creating several repository instances in parallel, where only one is required to be reused from the cache later.
Fixes VSTS #806706
> [VersionControl] Synchronize VersionControlService cache access

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlService.cs
Fixes `Could not query Git repository reference` errors and avoids creating several repository instances in parallel, where only one is required to be reused from the cache later.
Fixes VSTS #806706
Backport of #7270.
/cc @sevoku
> [release-8.0-integration] [VersionControl] Synchronize VersionControlService cache access

- main/src/addins/MacPlatform/MacInterop/Keychain.cs
- main/src/addins/MacPlatform/MacProxyCredentialProvider.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Tests.csproj
- main/tests/Ide.Tests/MonoDevelop.Ide/BaseCredentialsProviderTests.cs
- main/tests/MacPlatform.Tests/CredentialsProviderTests.cs
- main/tests/MacPlatform.Tests/KeychainTests.cs
- main/tests/MacPlatform.Tests/MacPlatform.Tests.csproj
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Core.Tests.csproj
- main/tests/WindowsPlatform.Tests/CredentialsProviderTests.cs
- main/tests/WindowsPlatform.Tests/WindowsPlatform.Tests.csproj
Actually, the keychain implementation (macOS) has several issues:
- Missing protocols (especially "https" for Git and Azure DevOps)
- The URL Path part is not stored correctly
Due to these issues, we can not update an existing keychain item sometimes, and generate new ones on each query, the service always returns the first entry for a service. 
We have changed the implementation of KeyChain to use the security APIs of Xamarin.Mac directly.
Fixes #795844
> [VersionControl] Fixes error in PasswordService; refuses to (re)store Git Credentials

- main/src/addins/MacPlatform/MacInterop/Keychain.cs
- main/src/addins/MacPlatform/MacProxyCredentialProvider.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Tests.csproj
- main/tests/Ide.Tests/MonoDevelop.Ide/BaseCredentialsProviderTests.cs
- main/tests/MacPlatform.Tests/CredentialsProviderTests.cs
- main/tests/MacPlatform.Tests/KeychainTests.cs
- main/tests/MacPlatform.Tests/MacPlatform.Tests.csproj
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Core.Tests.csproj
- main/tests/WindowsPlatform.Tests/CredentialsProviderTests.cs
- main/tests/WindowsPlatform.Tests/WindowsPlatform.Tests.csproj
Actually, the keychain implementation (macOS) has several issues:
- Missing protocols (especially "https" for Git and Azure DevOps)
- The URL Path part is not stored correctly
Due to these issues, we can not update an existing keychain item sometimes, and generate new ones on each query, the service always returns the first entry for a service. 
We have changed the implementation of KeyChain to use the security APIs of Xamarin.Mac directly.
Fixes #795844
Backport of #7278.
> [release-8.0-integration] [VersionControl] Fixes error in PasswordService; refuses to (re)store Git Credentials

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.MetadataReferenceHandler.cs
These are not needed, as they're handled via in-memory compilation. This should improve performance and prevent recompiling of the assembly on editing a root project
> Remove MetadataReferences from ProjectReferences

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.ProgressMonitoring/MessageDialogProgressMonitor.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
Adding an existing folder, that does not exist inside the project and
has more than 10 files, was opening a progress monitor dialog in front
of the confirmation dialog asking how to copy the files into the
project. A change to the MessageDialogProgressMonitor affected its
parent causing it to appear above the confirmation dialog. To fix this
the MessageDialogProgressMonitor now has a constructor that takes the
parent window.
Fixes VSTS #807518 - New ASP.NET Core Empty > .NET Core 2.x project,
add Existing Folder "bootstrap-4.3.1-dist", "Adding files..." dialog
in the front.
> [Ide] Fix progress dialog in front of confirmation dialog

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.MetadataReferenceHandler.cs
These are not needed, as they're handled via in-memory compilation. This should improve performance and prevent recompiling of the assembly on editing a root project
Backport of #7306.
/cc @Therzok
> [release-8.0-integration] Remove MetadataReferences from ProjectReferences

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.ProgressMonitoring/MessageDialogProgressMonitor.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
Adding an existing folder, that does not exist inside the project and
has more than 10 files, was opening a progress monitor dialog in front
of the confirmation dialog asking how to copy the files into the
project. A change to the MessageDialogProgressMonitor affected its
parent causing it to appear above the confirmation dialog. To fix this
the MessageDialogProgressMonitor now has a constructor that takes the
parent window.
Fixes VSTS #807518 - New ASP.NET Core Empty > .NET Core 2.x project,
add Existing Folder "bootstrap-4.3.1-dist", "Adding files..." dialog
in the front.
Backport of #7303.
> [release-8.0-integration] [Ide] Fix progress dialog in front of confirmation dialog

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlService.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlSystem.cs
In case of use Git and Tfvc VCS in the same folder, order the VCS by name alphabetically. By doing this, we prioritize the use of Git in these cases. 
We should analyze how to improve this situation in future versions. Show some type of selector or maybe include a new parameter in the Version Control configuration.
Fixes VSTS #801910
> [Version Control] Manage multiple VCS in the same path

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlService.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlSystem.cs
In case of use Git and Tfvc VCS in the same folder, order the VCS by name alphabetically. By doing this, we prioritize the use of Git in these cases. 
We should analyze how to improve this situation in future versions. Show some type of selector or maybe include a new parameter in the Version Control configuration.
Fixes VSTS #801910 
Backport of #7286.
/cc @slluis @jsuarezruiz
> [release-8.0-integration] [Version Control] Manage multiple VCS in the same path

- main/src/addins/MonoDevelop.Packaging/MonoDevelop.Packaging/NuGetPackageMetadata.cs
The Copyright NuGet package metadata in project options - NuGet
Package - Metadata was not being read nor written.
Fixes VSTS #807733 - NuGet Copyright metadata not saved
> [Packaging] Fix copyright metadata not being saved.

- main/src/addins/MonoDevelop.Packaging/MonoDevelop.Packaging/NuGetPackageMetadata.cs
The Copyright NuGet package metadata in project options - NuGet
Package - Metadata was not being read nor written.
Fixes VSTS #807733 - NuGet Copyright metadata not saved
Backport of #7333.
> [release-8.0-integration] [Packaging] Fix copyright metadata not being saved.

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git.csproj
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitCredentials.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/IGitCredentialsProvider.cs
To support Git repositories hosted on Azure DevOps we need to support auth using (without use basic auth with username and password) a PAT (Personal Access Token).
Fixes VSTS #706903
> [VersionControl] Added support to auth using PAT in Azure DevOps

- main/tests/WindowsPlatform.Tests/WindowsPlatform.Tests.csproj
It appears [this](https://github.com/mono/monodevelop/commit/86db65afabcef60c749427abef7ff99b4b4260cb) commit missed the reference for IdeUnitTests. This has broken the ability to run winbuild.bat
**Currently on Windows, running winbuild.bat will result in the following message:**
>    "C:\temp\monodevelop\main\Main.sln" (default target) (1:2) ->
>        "C:\temp\monodevelop\main\tests\WindowsPlatform.Tests\WindowsPlatform.Tests.csproj" (default target) (84:6) ->
>        (CoreCompile target) ->
>          CredentialsProviderTests.cs(32,3): error CS0012: The type 'IdeTestBase' is defined in an assembly that is not
>        referenced. You must add a reference to assembly 'IdeUnitTests, Version=0.0.0.0, Culture=neutral, PublicKeyToken
>        =3ead7498f347467b'. …
> Added Missing IDE Unit Tests Reference

- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Ide.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Services.cs
Instead of using a timer that isn't very accurate, track whether or not a
file load was initiated by the FileManager by passing a boolean to the events
Fixes VSTS #806672 https://devdiv.visualstudio.com/DevDiv/_workitems/edit/806672
Backport of #7320.
> [release-8.0-integration] [IDE] Track whether a file load was initiated by the File Manager better

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DefaultWorkbench.cs
Deleting a directory outside the IDE would not close documents that
were open in the IDE. Deleting individual files outside the IDE
that corresponded to open documents were closed correctly. The problem
was that the file service events for a directory being deleted do
not indicate a directory was removed so the existing logic was being
bypassed. To handle this, when a deletion event is processed, if no
exact filename match is found, then a check is made to see if the
deleted item matches a parent directory for any open view. If there
is a match then the document is closed.
Fixes VSTS #823237 Document not closed when parent directory removed
> [Ide] Close open documents if parent directory is removed externally

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/TypeSystemService_WorkspaceHandling.cs
The way cancellation was previously registered in the method would easily lead to InvalidOperationException being thrown since the registration on the cancellation token was kept indefinitely. As such disposing the token source after the taskSource has long been completed would throw.
With this patch we keep and dispose the cancellation token registration as soon as possible and switch every TaskCompletionSource access to the `Try` pattern to avoid spurious failures.
> [Ide] Prevent InvalidOperationException when calling GetCodeAnalysisProjectAsync with a token

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/TypeSystemService_WorkspaceHandling.cs
The way cancellation was previously registered in the method would easily lead to InvalidOperationException being thrown since the registration on the cancellation token was kept indefinitely. As such disposing the token source after the taskSource has long been completed would throw.
With this patch we keep and dispose the cancellation token registration as soon as possible and switch every TaskCompletionSource access to the `Try` pattern to avoid spurious failures.
Backport of #7356.
/cc @slluis @garuma
> [release-8.0-integration] [Ide] Prevent InvalidOperationException when calling GetCodeAnalysisProjectAsync with a token

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/EventBoxTooltip.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/InformationPopoverWidget.cs
This is needed for Android and iOS addins which expect to be able
to use markup in tooltips.
> [Ide] Fixed InformationPopoverWidget and EventBoxTooltip to allow Markup.

- main/build/MacOSX/monostub.mm
This is needed because of the MSBuild/NuGet bumps done in Mono to support
the latest 2.1, 2.2 and 3.0 SDKs, which are MSBuild16/NuGet5-based. With
old Mono versions, even basic builds will fail with all sort of packaging,
missing targets, etc issues.
> Bump minimum Mono version

- main/build/MacOSX/monostub.mm
This is needed because of the MSBuild/NuGet bumps done in Mono to support
the latest 2.1, 2.2 and 3.0 SDKs, which are MSBuild16/NuGet5-based. With
old Mono versions, even basic builds will fail with all sort of packaging,
missing targets, etc issues.
Backport of #7439.
/cc @rodrmoya
> [release-8.1] Bump minimum Mono version

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/DefaultWorkbench.cs
It is handled, so it is not a crash.
Backport of #7465.
/cc @slluis
> [release-8.1] Fix NRE at startup

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/RoslynDocumentExtension.cs
Fixes VSTS #888272 - InitializeExtensionChain() called twice on editor start
> Avoid unnecessary editor extension chain reinitializaiton

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/RoslynDocumentExtension.cs
Fixes VSTS #888272 - InitializeExtensionChain() called twice on editor start
Backport of #7464.
/cc @slluis
> [release-8.1] Avoid unnecessary editor extension chain reinitializaiton

- main/msbuild/MonoDevelop.AfterCommon.props
This new property is supported now in the macios API analyzer, and is used to detect
when we don't have a PList in the project.
Fixes VSTS #833279 - Run MacCoreApiIssue Analyzer for MonoDevelop and Addins
> Add property to signal xamarin.mac analyzer

- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/CodeTemplateToolboxProvider.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/ToolboxService.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentController.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentViewContainer.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/GtkShellDocumentViewContainerSplit.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Gui.Documents/DocumentViewVisibilityTests.cs
- main/tests/IdeUnitTests/MockShellDocumentViewContent.cs
Fix several toolbox issues:
* SourceEditorView.cs, CodeTemplateToolboxProvider.cs: In the old editor, use a private
toolbox provider for snippets. The global provider tries to get the
editor from the consumer, and that's not possible anymore.
* ToolboxService.cs: Support views that provide several
IToolboxDynamicProvider instances.
* Document.cs, DocumentController.cs: Added GetContent() method to
DocumentController to get the content for the active view hierarchy.
Removed some duplicated code in Document.
* DocumentView.cs, DocumentViewContainer.cs: When a view gets the focus, make sure it
is set as active. This is important when in Split mode, since now
clicking in the different views of the split will set it as active.
Also fixed some focus issues with tab views. When switching between …
> Fix several toolbox issues

- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/CodeTemplateToolboxProvider.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/ToolboxService.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentController.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentViewContainer.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/GtkShellDocumentViewContainerSplit.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Gui.Documents/DocumentViewVisibilityTests.cs
- main/tests/IdeUnitTests/MockShellDocumentViewContent.cs
Fix several toolbox issues:
* SourceEditorView.cs, CodeTemplateToolboxProvider.cs: In the old editor, use a private
toolbox provider for snippets. The global provider tries to get the
editor from the consumer, and that's not possible anymore.
* ToolboxService.cs: Support views that provide several
IToolboxDynamicProvider instances.
* Document.cs, DocumentController.cs: Added GetContent() method to
DocumentController to get the content for the active view hierarchy.
Removed some duplicated code in Document.
* DocumentView.cs, DocumentViewContainer.cs: When a view gets the focus, make sure it
is set as active. This is important when in Split mode, since now
clicking in the different views of the split will set it as active.
Also fixed some focus issues with tab views. When switching between …
> [release-8.1] Fix several toolbox issues

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/DotNetCoreNuGetProjectTests.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.csproj
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/ConditionalPackageReferenceHandler.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/DotNetCoreNuGetProject.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/IPropertySetExtensions.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageManagementMSBuildExtension.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/ProjectPackageReference.cs
A NuGet package being installed into a multi-target framework project
may not support all frameworks. When this happens the PackageReference
will now be added with a condition so the NuGet package is not used
for frameworks that are not supported.
```
<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup>
<TargetFrameworks>net472;netstandard1.2</TargetFrameworks>
</PropertyGroup>
<ItemGroup Condition="'$(TargetFramework)' == 'net472'">
<PackageReference Include="EntityFramework" Version="6.2.0" />
</ItemGroup>
</Project>
```
Note that NuGet does not support updating a NuGet package with a
condition. Visual Studio on Windows also shows an error about the NuGet
package being incompatible on updating it if it only supports certain
frameworks.
Fixes VSTS #572317 - Make adding PackageReferences to …
> [NuGet] Support partial installs into multi-target projects

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
If an existing file is copied or moved into a project then the
default build action from the project may be incorrect if the file
uses file globs. DefaultMSBuildEngine's FindGlobItemsIncludingFile
will not find a match if the file does not exist at the target
location. To fix this, if no build action was explicitly set when
adding an existing file to the project, the build action is
refreshed after the file has been copied or moved to the target
location.
This allows an existing .xaml file to be added to a Xamarin.Forms
.NET Standard project and for it to be added as an EmbeddedResource
instead of a None item.
Fixes VSTS 813456 - XAML files added are not actually added
> [Ide] Refresh build action when adding existing files to project

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdkPaths.cs
Although multi targeting is still not supported, by supporting unknowns SDKs -like MSBuild.Sdk.Extras- allows that projects to be built and ran and removes error message.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/849421
> [DotNetCore] Supports unknowns SDK

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdkPaths.cs
Although multi targeting is still not supported, by supporting unknowns SDKs -like MSBuild.Sdk.Extras- allows that projects to be built and ran and removes error message.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/849421
Backport of #7460.
> [release-8.1] [DotNetCore] Supports unknowns SDK

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
large amount of (handled) exceptions
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/849520
Not sure if the stack trace can happen because it's from an former
version and I couldn't find any in my log. But I added some bounds
checking in case the highlighting engine gives a chunk that's no
longer inside the text bounds.
> Fixes VSTS Bug 849520: TextViewMargin.CreateLinePartLayout creates a

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
If an existing file is copied or moved into a project then the
default build action from the project may be incorrect if the file
uses file globs. DefaultMSBuildEngine's FindGlobItemsIncludingFile
will not find a match if the file does not exist at the target
location. To fix this, if no build action was explicitly set when
adding an existing file to the project, the build action is
refreshed after the file has been copied or moved to the target
location.
This allows an existing .xaml file to be added to a Xamarin.Forms
.NET Standard project and for it to be added as an EmbeddedResource
instead of a None item.
Fixes VSTS 813456 - XAML files added are not actually added
Backport of #7469.
/cc @mrward
> [release-8.1] [Ide] Refresh build action when adding existing files to project

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
large amount of (handled) exceptions
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/849520
Not sure if the stack trace can happen because it's from an former
version and I couldn't find any in my log. But I added some bounds
checking in case the highlighting engine gives a chunk that's no
longer inside the text bounds.
Backport of #7457.
> [release-8.1] Fixes VSTS Bug 849520: TextViewMargin.CreateLinePartLayout creates a

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/ExtensibleTreeView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/SdiWorkspaceWindow.cs
Fixes VSTS #889280 - Cannot move between xaml files
Fixes VSTS #889281 - IDE crashes when clicking on a document tab to swap
documents
> Fix NRE when switching documents

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices/MonoDevelopErrorLoggerService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices/MonoDevelopExtensionManager.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
Fixes VSTS #842187 - Only show analyzer infobar for debug builds
Fixes VSTS #824924 - [Feedback] CSharpAddImportCodeFixProvider error
> [8.1] Implement custom infobar handler for analyzer errors

- main/src/addins/AspNet/WebForms/WebFormsToolboxNode.cs
- main/src/addins/ChangeLogAddIn/ChangeLogAddIn.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebugCommands.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebuggingService.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/ToolboxService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbarController.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/CustomStringTagProvider.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/EditCommands.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/FileCommands.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/ViewCommands.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/WindowCommands.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/FindInFilesDialog.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/Scope.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Navigation/NavigationHistoryService.cs
Reviewed calls to GetContent and changed several calls to limit the scope
to the current active view.
For ToolboxService, changed the scope to look for provider in all document.
Fixes VSTS #866686 - Xamarin.Forms previewer does not show toolbox content
> Fix scope of GetContent() for several views

- main/src/addins/AspNet/WebForms/WebFormsToolboxNode.cs
- main/src/addins/ChangeLogAddIn/ChangeLogAddIn.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebugCommands.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebuggingService.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/ToolboxService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbarController.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/CustomStringTagProvider.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/EditCommands.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/FileCommands.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/ViewCommands.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/WindowCommands.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/FindInFilesDialog.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/Scope.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Navigation/NavigationHistoryService.cs
Reviewed calls to GetContent and changed several calls to limit the scope
to the current active view.
For ToolboxService, changed the scope to look for provider in all document.
Fixes VSTS #866686 - Xamarin.Forms previewer does not show toolbox content
Backport of #7494.
/cc @slluis
> [release-8.1] Fix scope of GetContent() for several views

- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/CodeTemplateToolboxProvider.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/MacToolboxWidget.cs
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/CocoaTextViewContent.cs
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/CocoaTextViewImports.cs
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/MonoDevelop.TextEditor.Cocoa.csproj
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/SnippetsInToolbox/SnippetToolboxNode.cs
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/TextViewContent.Toolbox.cs
Changed logic in CodeTemplateToolboxProvider to not execute for new editor since code expects `document.Editor` to not be `null`
Main change is in TextViewContent.Toolbox which now makes new editor ViewContent aware of `IToolboxConsumer` and in `CocoaTextViewContent` which actually converts templates that `IExpansionManager` returns to Toolbox items
> Fixes 866554: Enable Snippets within Toolbox

- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/CodeTemplateToolboxProvider.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/MacToolboxWidget.cs
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/CocoaTextViewContent.cs
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/CocoaTextViewImports.cs
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/MonoDevelop.TextEditor.Cocoa.csproj
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/SnippetsInToolbox/SnippetToolboxNode.cs
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/TextViewContent.Toolbox.cs
Changed logic in CodeTemplateToolboxProvider to not execute for new editor since code expects `document.Editor` to not be `null`
Main change is in TextViewContent.Toolbox which now makes new editor ViewContent aware of `IToolboxConsumer` and in `CocoaTextViewContent` which actually converts templates that `IExpansionManager` returns to Toolbox items
Backport of #7470.
/cc @sandyarmstrong @DavidKarlas
> [release-8.1] Fixes 866554: Enable Snippets within Toolbox

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/MonoTextEditor.ITextView.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs
The ITextView implementation relied on the ActiveDocumentChanged
event to be raised after the editor is fully initialized. The handler of that
event would call QueueAggregateFocusCheck() to update the focus
status of the text view.
Since views are now loaded asynchronously, ActiveDocumentChanged is now raised
before the editor is loaded, so QueueAggregateFocusCheck is not called.
To fix this issue, QueueAggregateFocusCheck is now explicitly called once
the editor is initialized.
Fixes VSTS #807522 - [WebToolsE2E][VSforMac]Type keyword in cshtml file, there
is no intellisense.
> Fix focus notification issue with the old editor

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/MonoTextEditor.ITextView.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs
The ITextView implementation relied on the ActiveDocumentChanged
event to be raised after the editor is fully initialized. The handler of that
event would call QueueAggregateFocusCheck() to update the focus
status of the text view.
Since views are now loaded asynchronously, ActiveDocumentChanged is now raised
before the editor is loaded, so QueueAggregateFocusCheck is not called.
To fix this issue, QueueAggregateFocusCheck is now explicitly called once
the editor is initialized.
Fixes VSTS #807522 - [WebToolsE2E][VSforMac]Type keyword in cshtml file, there
is no intellisense.
Backport of #7514.
/cc @slluis
> [release-8.1] Fix focus notification issue with the old editor

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/DockBar.cs
Hiding and showing a dock item causes any hovers within the next 1.5seconds to be ignored.
It's possible to move into the dockbar to try to show a new pad within that 1.5 seconds, causing the pad to not appear.
Fix this by only disable the hover when showing the pad, not hiding.
Fixes VSTS #851588
> [Dock] Don't disable hover when hiding a dock item

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs
Fixes VSTS #832026 - Double click in Search Results for XAML file does not
set focus to the edit window
> Fix document focus issues

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs
Fixes VSTS #832026 - Double click in Search Results for XAML file does not
set focus to the edit window
Backport of #7529.
/cc @slluis
> [release-8.1] Fix document focus issues

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/DockBar.cs
Hiding and showing a dock item causes any hovers within the next 1.5seconds to be ignored.
It's possible to move into the dockbar to try to show a new pad within that 1.5 seconds, causing the pad to not appear.
Fix this by only disable the hover when showing the pad, not hiding.
Fixes VSTS #851588
Backport of #7532.
> [release-8.1] [Dock] Don\u0027t disable hover when hiding a dock item

- main/src/addins/MacPlatform/MacPlatform.cs
Some Version Control dialogs appeared in the top left corner of the screen (like create Stash or manage Stashes).
Fixed passing the Parent.
Fixes VSTS #825038
> [Shell] Fix wrong initial position of some Dialogs

- main/src/addins/MacPlatform/MacPlatform.cs
Some Version Control dialogs appeared in the top left corner of the screen (like create Stash or manage Stashes).
Fixed passing the Parent.
Fixes VSTS #825038
Backport of #7519.
/cc @slluis @jsuarezruiz
> [release-8.1] [Shell] Fix wrong initial position of some Dialogs

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.AnalysisCore/Gui/ResultsEditorExtension.cs
Preview crash
https://dev.azure.com/devdiv/DevDiv/_workitems/edit/825007
I doubt that this is responsible for the crash but it ensures, that
newMarkers is always != null at that point of the IdleHandler.
> Fixes VSTS Bug 825007: [Feedback] Log files for Visual Studio 2019

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.AnalysisCore/Gui/ResultsEditorExtension.cs
Preview crash
https://dev.azure.com/devdiv/DevDiv/_workitems/edit/825007
I doubt that this is responsible for the crash but it ensures, that
newMarkers is always != null at that point of the IdleHandler.
Backport of #7538.
> [release-8.1] Fixes VSTS Bug 825007: [Feedback] Log files for Visual Studio 2019

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.Visualizer/ValueVisualizerDialog.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebuggingService.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ImmediatePad.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/LocalsPad.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValuePad.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValueTreeView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/WatchPad.cs
When a user changes the value of a variable in 1 debugger pad
(Immediate, Watch, or Locals), make sure the value change(s) are
reflected in the other pads as well.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/806732/
> [8.1][Debugger] Keep variable values synchronized across all debugger pads

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/SdiWorkspaceWindow.cs
Don't change the first responder of the document being focused if it is
already a child of the main view.
Fixes VSTS #847834 - Go To Declaration causes editor to lose focus
> Fix focus issue with navigation

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/SdiWorkspaceWindow.cs
Don't change the first responder of the document being focused if it is
already a child of the main view.
Fixes VSTS #847834 - Go To Declaration causes editor to lose focus
Backport of #7548.
/cc @slluis
> [release-8.1] Fix focus issue with navigation

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/TextViewContent.Commands.cs
Only look for a find presenter when querying about find
commands.
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/890051
> TextViewContent: Clean up CanHandleCommand

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.WelcomePage/WelcomePageService.cs
The WelcomePageService's Initialize method and the DefaultWorkbench's
InitializeWorkspace both attempt to configure the global main menu
asynchronously. If the WelcomePageService configured the main menu
before the command service was initialized in IdeApp the native Mac
menu was not available. A null reference exception was logged:
```
Could not install global menu
at MonoDevelop.MacIntegration.MacPlatformService.InitApp (MonoDevelop.Components.Commands.CommandManager commandManager) [0x00009] in /Users/vsts/agent/2.150.3/work/1/s/monodevelop/main/src/addins/MacPlatform/MacPlatform.cs:483
at MonoDevelop.MacIntegration.MacPlatformService.SetGlobalMenu (MonoDevelop.Components.Commands.CommandManager …
```
> [Ide] Fix native macOS menu not used

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.WelcomePage/WelcomePageService.cs
The WelcomePageService's Initialize method and the DefaultWorkbench's
InitializeWorkspace both attempt to configure the global main menu
asynchronously. If the WelcomePageService configured the main menu
before the command service was initialized in IdeApp the native Mac
menu was not available. A null reference exception was logged:
```
Could not install global menu
at MonoDevelop.MacIntegration.MacPlatformService.InitApp (MonoDevelop.Components.Commands.CommandManager commandManager) [0x00009] in /Users/vsts/agent/2.150.3/work/1/s/monodevelop/main/src/addins/MacPlatform/MacPlatform.cs:483
at MonoDevelop.MacIntegration.MacPlatformService.SetGlobalMenu (MonoDevelop.Components.Commands.CommandManager …
```
> [release-8.1] [Ide] Fix native macOS menu not used

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/TextViewContent.Commands.cs
Only look for a find presenter when querying about find
commands.
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/890051
Backport of #7546.
> [release-8.1] TextViewContent: Clean up CanHandleCommand

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/NewProjectConfiguration.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Templates/FinalProjectConfigurationTests.cs
The New Project dialog has extra rules for the project name and
solution name on the final page of the dialog, such as not allowing
spaces. The generation of a valid project and solution name from the
app name specified in a project template wizard used different logic
so the names shown on the final page may still be considered invalid
on the final page. For example AppName='Hello, Mac' in the Cocoa App
project templates generates a project and solution name of 'Hello,Mac'
which the New Project dialog considers invalid.
To prevent this the same logic is now used when generating a valid
project and solution name from the project template wizard's app name.
Fixes VSTS #825164 - VS4M partially renames the project but it's still
invalid
> [Ide] Generate valid project name from app name

- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/AssemblyBrowserViewContent.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/AssemblyBrowserWidget.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/AssemblyLoader.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/AssemblyReferenceFolder.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/IAssemblyBrowserNodeBuilder.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/AssemblyBrowserTypeNodeBuilder.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/Cecil/AssemblyNodeBuilder.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/Cecil/EventDefinitionNodeBuilder.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/Cecil/FieldDefinitionNodeBuilder.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/Cecil/MethodDefinitionNodeBuilder.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/Cecil/PropertyDefinitionNodeBuilder.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/Cecil/TypeDefinitionNodeBuilder.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/NamespaceBuilder.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/Roslyn/RoslynMemberNodeBuilder.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/860954
Loading type system in background and removing the lock fixes the
issue. Locking is not needed because immutable data structures are
used now.
When opening a "blank" assembly browser the list of referenced
assemblies can be very long -esp. for .NET core projects it's better
not loading the referenced assemblies of all projects. It's a bit
unrelated but loadung such many assemblies can cause a very long load
time as well.
Even if it's not a hang it's basically "assembly browser does not do
anything" experience.
> Fixes VSTS Bug 860954: Go To Definition causes a lengthy UI hang

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbarController.cs
crashes
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/893674
Bug got introduced by the new editor changes. Pattern.Column == 0 was
the problem so the SnapshotPoint got negative and that explains the
line -1 problem as well.
> Fixes VSTS Bug 893674: [Feedback] Goto line jumps to wrong line or

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbarController.cs
crashes
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/893674
Bug got introduced by the new editor changes. Pattern.Column == 0 was
the problem so the SnapshotPoint got negative and that explains the
line -1 problem as well.
Backport of #7581.
/cc @mkrueger
> [release-8.1] Fixes VSTS Bug 893674: [Feedback] Goto line jumps to wrong line or

- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/MonoDevelop.FSharp.Tests.fsproj
- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/GLibLogging.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Gui/GLibLoggingTests.cs
- main/tests/MacPlatform.Tests/MacPlatform.Tests.csproj
- main/tests/MacPlatform.Tests/MacPlatformTest.cs
We need to throw the exceptions, otherwise nothing processes stacktrace information properly, which is only set by the runtime
Fixes VSTS #890423 - [Telemetry] VS for Mac should log GTK fatal errors to telemetry
> [Ide] Add proper handling of gtk/objc exceptions

- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/AssemblyBrowserViewContent.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/AssemblyBrowserWidget.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/AssemblyLoader.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/AssemblyReferenceFolder.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/IAssemblyBrowserNodeBuilder.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/AssemblyBrowserTypeNodeBuilder.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/Cecil/AssemblyNodeBuilder.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/Cecil/EventDefinitionNodeBuilder.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/Cecil/FieldDefinitionNodeBuilder.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/Cecil/MethodDefinitionNodeBuilder.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/Cecil/PropertyDefinitionNodeBuilder.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/Cecil/TypeDefinitionNodeBuilder.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/NamespaceBuilder.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/Roslyn/RoslynMemberNodeBuilder.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/860954
Loading type system in background and removing the lock fixes the
issue. Locking is not needed because immutable data structures are
used now.
When opening a "blank" assembly browser the list of referenced
assemblies can be very long -esp. for .NET core projects it's better
not loading the referenced assemblies of all projects. It's a bit
unrelated but loadung such many assemblies can cause a very long load
time as well.
Even if it's not a hang it's basically "assembly browser does not do
anything" experience.
Backport of #7491.
> [release-8.1] Fixes VSTS Bug 860954: Go To Definition causes a lengthy UI hang

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.csproj
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/FrameworkReference.cs
.NET Core 3.0 introduces a FrameworkReference MSBuild item which
represents a set of assemblies that version with the project's
target framework. Adding a new ProjectItem for the FrameworkReference
ensures it is not shown in red as an UnknownProjectItem.
Fixes VSTS #887910 - Create ASP.NET Core xUnit Test ~ 3.0 Project, run
workaround, the color of Microsoft.AspNetCore.App color file is red.
> [DotNetCore] Hide FrameworkReference items in Solution window.

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.csproj
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/FrameworkReference.cs
.NET Core 3.0 introduces a FrameworkReference MSBuild item which
represents a set of assemblies that version with the project's
target framework. Adding a new ProjectItem for the FrameworkReference
ensures it is not shown in red as an UnknownProjectItem.
Fixes VSTS #887910 - Create ASP.NET Core xUnit Test ~ 3.0 Project, run
workaround, the color of Microsoft.AspNetCore.App color file is red.
Backport of #7571.
/cc @mrward
> [release-8.1] [DotNetCore] Hide FrameworkReference items in Solution window.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.ProjectSystemHandler.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/TypeSystemService.cs
If a NuGet restore is cancelled then the type system may stop
processing if it is frozen waiting for the restore to finish since a
TaskCanceledException would be thrown.
To avoid this the TypeSystemService.FreezeTask is used inside a
try/catch so any exceptions can be ignored. Whether the NuGet restore
is cancelled or fails should not stop the type system from getting
project information.
Fixes VSTS #891329 - Handle cancelling NuGet restore whilst type
system is waiting for restore
> [Ide] Handle NuGet restore cancelled whilst type system frozen

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.ProjectSystemHandler.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/TypeSystemService.cs
If a NuGet restore is cancelled then the type system may stop
processing if it is frozen waiting for the restore to finish since a
TaskCanceledException would be thrown.
To avoid this the TypeSystemService.FreezeTask is used inside a
try/catch so any exceptions can be ignored. Whether the NuGet restore
is cancelled or fails should not stop the type system from getting
project information.
Fixes VSTS #891329 - Handle cancelling NuGet restore whilst type
system is waiting for restore
Backport of #7557.
/cc @mrward
> [release-8.1] [Ide] Handle NuGet restore cancelled whilst type system frozen

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.Helpers/FakeProject.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/ProjectTargetFrameworkMonitorTests.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/IProject.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageManagementSdkProjectExtension.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/ProjectProxy.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/ProjectTargetFrameworkMonitor.cs
[NuGet] Restore only projects affected when target framework changed
When the target framework changed in a .NET Core project all .NET
Core projects in the soluton were restored. Now only the project and
any of its transitive project references are restored.
Fixes VSTS #895149 - Target Framework change in one project restores
all .NET Core projects
[NuGet] Fix adding non-sdk style project triggering NuGet restore
Adding a new non-sdk style project to md-addins would cause a NuGet
restore to run multiple times. The problem was that the Xamarin.Mac
SDK style projects change their target framework on re-evaluation from
.NET to Xamarin.Mac. This was causing the .NET Core project extension
to run a restore for all sdk style projects in the solution, multiple
times. To avoid this the target …
> [NuGet] Fix multiple NuGet restores run on target framework changed

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/TextViewContent.cs
Instead the task of disposing it should be left to the document model registry. In case where said instance is shared, the manual dispose would corrupt the version still stored inside the registry causing all sorts of failures when reopening documents.
> [TextEditor] Don't manually dispose the TextDocument instance.

- main/msbuild/MDBuildTasks/MDBuildTasks.csproj
`/home/directhex/Projects/monodevelop/main/msbuild/MDBuildTasks/MDBuildTasks.csproj : error : /usr/share/dotnet/sdk/2.2.204/Sdks/Microsoft.Net.Sdk/Sdk not found. Check that a recent enough .NET Core SDK is installed and/or increase the version specified in global.json.`
> Fix casing error

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/TextViewContent.Commands.cs
The previous fix for https://devdiv.visualstudio.com/DevDiv/_workitems/edit/890051 was subtly incorrect. It prevented the control flow for find commands from falling through. Turns out when Find is not focused the control flow needs to fall through to the default.
A different way to fix it is to check TextView for null to avoid the NullReferenceException from 890051.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/893794 - Unable to search in text editor with inline search
> Fix Find commands availability.

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/Properties/MonoDevelop.TextEditor.addin.xml
- main/src/core/MonoDevelop.Ide/ExtensionModel/MainMenu.addin.xml
Verbiage and default shortcuts taken from Windows.
Fixes: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/801922
Backport of #7585.
> [release-8.1] TextEditor: Map and menu for multi-caret commands

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/TextViewContent.Commands.cs
The previous fix for https://devdiv.visualstudio.com/DevDiv/_workitems/edit/890051 was subtly incorrect. It prevented the control flow for find commands from falling through. Turns out when Find is not focused the control flow needs to fall through to the default.
A different way to fix it is to check TextView for null to avoid the NullReferenceException from 890051.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/893794 - Unable to search in text editor with inline search
Backport of #7610.
/cc @abock @KirillOsenkov
> [master] Fix Find commands availability.

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/PackageSourceViewModelTests.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageSourceViewModel.cs
After updating to NuGet 5 it was not possible to add, remove or update
package sources in Preferences if a package source had a username and
password associated with it. The problem was that the package source
url was being used when saving the username and password information
in the packageSourceCredentials section in the NuGet.Config file. This
resulted in an invalid xml element name so the save would fail. In
NuGet 4.8 the PackageSourceCredential.Source was not used when saving
the NuGet.Config file. With NuGet 4.9 and later it is being used.
However it is not the source url but the source name.
Fixes VSTS #857001 - Unable to update NuGet package sources
> [NuGet] Fix being unable to add or update NuGet package sources

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/PackageSourceViewModelTests.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageSourceViewModel.cs
After updating to NuGet 5 it was not possible to add, remove or update
package sources in Preferences if a package source had a username and
password associated with it. The problem was that the package source
url was being used when saving the username and password information
in the packageSourceCredentials section in the NuGet.Config file. This
resulted in an invalid xml element name so the save would fail. In
NuGet 4.8 the PackageSourceCredential.Source was not used when saving
the NuGet.Config file. With NuGet 4.9 and later it is being used.
However it is not the source url but the source name.
Fixes VSTS #857001 - Unable to update NuGet package sources
Backport of #7624.
/cc @mrward
> [release-8.1] [NuGet] Fix being unable to add or update NuGet package sources

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebuggingService.cs
Opening the breakpoint dialog to create an exception catchpoint or a
function breakpoint the completion list window for exception types
would appear behind the dialog.
Making the breakpoint dialog's parent window to be the main IDE window
fixes this problem.
Fixes issue #7628 - Exception class completion popup is hidden under
the window
> [Debugger] Fix completion list window behind breakpoint dialog

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.PropertyGrid/PropertyGridTable.cs
This issue was detected by Watson, and probably could be related call EndEditing 2 times and we don't check for null the currentEditor.
I'm not completely sure about the fix, because at the end we refresh 2 times the grid, maybe we could don't allow call EndEditing 2 times?
Fixes VSTS #861004 - [Watson] System.NullReferenceException in MonoDevelop.Components.PropertyGrid.PropertyGridTable::EndEditing (System.NullReferenceException_MonoDevelop.Ide.dll)
> [PropertyGrid] Fixes NRE on a second call to EndEditing and currentEditor is null

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.PropertyGrid/PropertyGridTable.cs
This issue was detected by Watson, and probably could be related call EndEditing 2 times and we don't check for null the currentEditor.
I'm not completely sure about the fix, because at the end we refresh 2 times the grid, maybe we could don't allow call EndEditing 2 times?
Fixes VSTS #861004 - [Watson] System.NullReferenceException in MonoDevelop.Components.PropertyGrid.PropertyGridTable::EndEditing (System.NullReferenceException_MonoDevelop.Ide.dll)
Backport of #7642.
> [release-8.1] [PropertyGrid] Fixes NRE on a second call to EndEditing and currentEditor is null

- main/build/MacOSX/Info.plist.in
- main/build/MacOSX/Makefile.am
- main/build/MacOSX/check-xm-extern.sh
- main/build/MacOSX/monostub-test.m
- main/build/MacOSX/monostub-utils.h
- main/build/MacOSX/monostub.mm
* Removes a lot of `char *` <-> `NSString` conversions
* Reduces code duplication
* Removes unused defines
* Removes code which could simply invoke mono API
> Cleanup monostub launcher code

- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/addins/MacPlatform/MainToolbar/StatusBar.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebugCommands.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/Extensions.cs
- main/src/addins/MonoDevelop.UnitTesting/Services/UnitTestService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestSession.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbarCommandHandlers.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/StatusArea.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/ViewCommands.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentController.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/DefaultWorkbench.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/StatusBar.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/WorkbenchStatusBar.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.WelcomePage/WelcomePageService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Ide.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/RootWorkspace.cs
- main/tests/StressTest/MonoDevelop.StressTest/Program.cs
- main/tests/StressTest/MonoDevelop.StressTest/StressTestApp.cs
- main/tests/StressTest/ResultParser/Program.cs
- main/tests/UserInterfaceTests/Workbench.cs
- main/tests/ui/MonoDevelop.UserInterfaceTesting/MonoDevelop.UserInterfaceTesting/Workbench.cs
Don't initialize DefaultWorkbench until it is shown for the first time. One problem is that the status bar is used before the workbench is shown, so added a wrapper class that will work as a dummy status bar until the real one is shown. Improve UI responsiveness when running startup handlers. Delay initialization of package service until the first solution is opened.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/889788
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/888567
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/888564
> Improve UI responsiveness at startup

- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/addins/MacPlatform/MainToolbar/StatusBar.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebugCommands.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/Extensions.cs
- main/src/addins/MonoDevelop.UnitTesting/Services/UnitTestService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestSession.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbarCommandHandlers.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/StatusArea.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/ViewCommands.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentController.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/DefaultWorkbench.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/StatusBar.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/WorkbenchStatusBar.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.WelcomePage/WelcomePageService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Ide.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/RootWorkspace.cs
- main/tests/StressTest/MonoDevelop.StressTest/Program.cs
- main/tests/StressTest/MonoDevelop.StressTest/StressTestApp.cs
- main/tests/StressTest/ResultParser/Program.cs
- main/tests/UserInterfaceTests/Workbench.cs
- main/tests/ui/MonoDevelop.UserInterfaceTesting/MonoDevelop.UserInterfaceTesting/Workbench.cs
Don't initialize DefaultWorkbench until it is shown for the first time. One problem is that the status bar is used before the workbench is shown, so added a wrapper class that will work as a dummy status bar until the real one is shown. Improve UI responsiveness when running startup handlers. Delay initialization of package service until the first solution is opened.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/889788
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/888567
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/888564
Backport of #7525.
/cc @slluis
> [release-8.1] Improve UI responsiveness at startup

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/Scope.cs
re-opening solution This is better than forcing the load, if many
files are open forcing to load all at once without need is worse than
the possibility to load a file twice.
> Fixes issue #7561 Find in files - open files - returns no results on

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/Scope.cs
re-opening solution This is better than forcing the load, if many
files are open forcing to load all at once without need is worse than
the possibility to load a file twice.
Backport of #7647.
> [release-8.1] Fixes issue #7561 Find in files - open files - returns no results on

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/Commands.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitConfigurationDialog.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitService.cs
The problem is that when changing branches we unload and load the solution. When doing unload we dispose the repository. Depending on the solution and its size (and therefore, the time to load) we sometimes try to access the repository (for example, obtain remote branches) before re-instantiating the repository. We obtain:
```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'GitRepository'.
at MonoDevelop.VersionControl.Git.GitRepository.EnsureInitialized () [0x0000b] in /Users/jsuarez/Documents/Projects/MonoDevelop/monodevelop/main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs:442 
at MonoDevelop.VersionControl.Git.GitRepository.RunSafeOperation[T] (System.Func`1[TResult] action) [0x00001] in …
```
> [Version Control] Changing between branches we stopped seeing the list of available branches

- main/build/MacOSX/monostub.mm
If started from a Xamarin.Mac app, this env var is set pointing to a (maybe)
non-existing folder (~/Library/Application Support/Whatever), which causes
code that tries to access the registry fail if that folder doesn't exist. So,
since we want to use Mono's registry, make sure the env var is cleaned up
on startup.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/896438
> [release-8.1] [Mac] Cleanup MONO_REGISTRY_PATH on startup

- main/build/MacOSX/monostub.mm
If started from a Xamarin.Mac app, this env var is set pointing to a (maybe)
non-existing folder (~/Library/Application Support/Whatever), which causes
code that tries to access the registry fail if that folder doesn't exist. So,
since we want to use Mono's registry, make sure the env var is cleaned up
on startup.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/896438
> [Mac] Cleanup MONO_REGISTRY_PATH on startup

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/Commands.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitConfigurationDialog.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitService.cs
The problem is that when changing branches we unload and load the solution. When doing unload we dispose the repository. Depending on the solution and its size (and therefore, the time to load) we sometimes try to access the repository (for example, obtain remote branches) before re-instantiating the repository. We obtain:
```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'GitRepository'.
at MonoDevelop.VersionControl.Git.GitRepository.EnsureInitialized () [0x0000b] in /Users/jsuarez/Documents/Projects/MonoDevelop/monodevelop/main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs:442 
at MonoDevelop.VersionControl.Git.GitRepository.RunSafeOperation[T] (System.Func`1[TResult] action) [0x00001] in …
```
> [release-8.1] [Version Control] Changing between branches we stopped seeing the list of available branches

- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/GLibLogging.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Gui/GLibLoggingTests.cs
- main/tests/MacPlatform.Tests/MacPlatformTest.cs
- main/tests/UnitTests/CapturingLogger.cs
- main/tests/UnitTests/UnitTests.csproj
Log files use Exception.ToString() for string formatting, thus do not benefit from our improved stacktrace gathering for native exceptions
Fix that by overriding the tostring method
Fixes VSTS #897159 - GLib Error Logging does not include stack trace
> [Logging] Fix stacktraces not being written to log files

- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/GLibLogging.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Gui/GLibLoggingTests.cs
- main/tests/MacPlatform.Tests/MacPlatformTest.cs
- main/tests/UnitTests/CapturingLogger.cs
- main/tests/UnitTests/UnitTests.csproj
Log files use Exception.ToString() for string formatting, thus do not benefit from our improved stacktrace gathering for native exceptions
Fix that by overriding the tostring method
Fixes VSTS #897159 - GLib Error Logging does not include stack trace
Backport of #7663.
/cc @Therzok
> [release-8.1] [Logging] Fix stacktraces not being written to log files

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Tabstrip.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentManager.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/GtkShellDocumentViewContainer.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/GtkShellDocumentViewContainerSplit.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/GtkShellDocumentViewContainerTabs.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/GtkShellDocumentViewItem.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/SdiWorkspaceWindow.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Styles.cs
When a tabbed view has attached views, there is a tab stacking effect
that is very confusing.
To avoid this problem, when a tabbed view has a child that also has
tabs, the tabs are now shown in the parent's tab area, next to the
parent's tabs.
Before:
After:
Fixes VSTS# 893310 - New split view results in stacked tabs with the
same name
> Fix tab stacking issue in designers

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Tabstrip.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentManager.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/GtkShellDocumentViewContainer.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/GtkShellDocumentViewContainerSplit.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/GtkShellDocumentViewContainerTabs.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/GtkShellDocumentViewItem.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/SdiWorkspaceWindow.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Styles.cs
When a tabbed view has attached views, there is a tab stacking effect
that is very confusing.
To avoid this problem, when a tabbed view has a child that also has
tabs, the tabs are now shown in the parent's tab area, next to the
parent's tabs.
Before:
After:
Fixes VSTS# 893310 - New split view results in stacked tabs with the
same name
Backport of #7667.
/cc @slluis
> [release-8.1] Fix tab stacking issue in designers

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentManager.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/FileDocumentController.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Gui.Documents/DocumentManagerTests.cs
Fixed the logic that determines if a document can be reused or not, it didn't work properly when opening a document using a custom model descriptor.
Also adjusted the logic for reusing file documents and added unit tests.
Fixes bug #891266 - Assembly browser back/forward navigation opens new Assembly Browser window
> Fix document reuse logic

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentManager.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/FileDocumentController.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Gui.Documents/DocumentManagerTests.cs
Fixed the logic that determines if a document can be reused or not, it didn't work properly when opening a document using a custom model descriptor.
Also adjusted the logic for reusing file documents and added unit tests.
Fixes bug #891266 - Assembly browser back/forward navigation opens new Assembly Browser window
Backport of #7684.
/cc @slluis
> [release-8.1] Fix document reuse logic

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreExecutionCommand.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/850047
Derive AspNetCoreExecutionCommand from DotNetCoreExecutionCommand as they are identical apart from the ApplicationURLs property.
This change enables the external console handling code in DotNetCoreProjectExtension::OnExecuteDotNetCoreCommand to work correctly with all .Net Core projects.
> Enable ASP.Net Core projects to run on external console

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/NoSourceView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentController.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentManager.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/SdiWorkspaceWindow.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Gui.Documents/DocumentManagerTests.cs
- main/tests/IdeUnitTests/MockShellWindow.cs
When opening a document, the view may take long time to initialize (for example when loading a designer). This used to delay the whole document initialization sequence. During that initialization the corresponding tab in the shell was already visible, and that caused some bugs since there was
code expecting a fully initialized document.
Two things have been done to solve this problem. First, the document initialization doesn't wait anymore for the view to be initialized, so that when the tab is show, the document initialization is complete. Second, checks have been added to the Document and SdiWorkspaceWindow classes
to properly handle documents that don't yet have a view.
Also removed obsolete WorkbenchWindow api.
Fixes VSTS #889288 - Opening a document does not focus the new document …
> Fix issues when opening a document

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/NoSourceView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentController.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentManager.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/SdiWorkspaceWindow.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Gui.Documents/DocumentManagerTests.cs
- main/tests/IdeUnitTests/MockShellWindow.cs
When opening a document, the view may take long time to initialize (for example when loading a designer). This used to delay the whole document initialization sequence. During that initialization the corresponding tab in the shell was already visible, and that caused some bugs since there was
code expecting a fully initialized document.
Two things have been done to solve this problem. First, the document initialization doesn't wait anymore for the view to be initialized, so that when the tab is show, the document initialization is complete. Second, checks have been added to the Document and SdiWorkspaceWindow classes
to properly handle documents that don't yet have a view.
Also removed obsolete WorkbenchWindow api.
Fixes VSTS #889288 - Opening a document does not focus the new document …
> [release-8.1] Fix issues when opening a document

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/TypeSystemService_WorkspaceHandling.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/889145 - [WebToolsE2E][VSforMac]First time to add MVC View Page file(.cshtml), the intellisense and colorization doesn't work at once and shows un-save state. It needs to reopen or insert.
When a project is reloaded the C# buffers we added manually are lost, and so we need to keep track of them and readd them on each reload. This explains why we lost classification and other Roslyn features for C# chunks of .cshtml files when a project was reloaded while a .cshtml file was open.
> Preserve C# documents added by Razor when reloading a project.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/TypeSystemService_WorkspaceHandling.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/889145 - [WebToolsE2E][VSforMac]First time to add MVC View Page file(.cshtml), the intellisense and colorization doesn't work at once and shows un-save state. It needs to reopen or insert.
When a project is reloaded the C# buffers we added manually are lost, and so we need to keep track of them and readd them on each reload. This explains why we lost classification and other Roslyn features for C# chunks of .cshtml files when a project was reloaded while a .cshtml file was open.
Backport of #7675.
> [master] Preserve C# documents added by Razor when reloading a project.

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreExecutionCommand.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/850047
Derive AspNetCoreExecutionCommand from DotNetCoreExecutionCommand as they are identical apart from the ApplicationURLs property.
This change enables the external console handling code in DotNetCoreProjectExtension::OnExecuteDotNetCoreCommand to work correctly with all .Net Core projects.
Backport of #7692.
> [release-8.1] Enable ASP.Net Core projects to run on external console

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/Commands.cs
Fixes VSTS Bug 895925: Version Control > Authors jumps to wrong tab
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/895926
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/895925
These two are very similiar. That patch fixes blame command as well.
The command handlers for these were not implemented and simply fell
back to the diff command handler.
> Fixes VSTS Bug 895926: Version Control > Log jumps to wrong tag

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/Commands.cs
Fixes VSTS Bug 895925: Version Control > Authors jumps to wrong tab
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/895926
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/895925
These two are very similiar. That patch fixes blame command as well.
The command handlers for these were not implemented and simply fell
back to the diff command handler.
Backport of #7679.
/cc @mkrueger
> [release-8.1] Fixes VSTS Bug 895926: Version Control \u003e Log jumps to wrong tag

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeActionEditorExtension.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/TagCommentsTextEditorExtension.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.WelcomePage/WelcomePageService.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/861121 - "System.NullReferenceException" when closing a solution while a json file is open & the solution doesn't close.
This is the MonoDevelop side of the fix for 861121. For non-C# files they could still be a part of WebEditorRoslynWorkspace, and not MonoDevelopWorkspace, and we need to gracefully deal with that.
> Fix some NullReferences in Json files

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeActionEditorExtension.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/TagCommentsTextEditorExtension.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.WelcomePage/WelcomePageService.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/861121 - "System.NullReferenceException" when closing a solution while a json file is open & the solution doesn't close.
This is the MonoDevelop side of the fix for 861121. For non-C# files they could still be a part of WebEditorRoslynWorkspace, and not MonoDevelopWorkspace, and we need to gracefully deal with that.
Backport of #7700.
/cc @slluis @KirillOsenkov
> [master] Fix some NullReferences in Json files

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AtkCocoaHelper/AtkCocoaHelperMac.cs
If we try to call a null func<> then we'll get an NRE, so check they're set and warn if not.
Fixes VSTS #780731
> [A11y] Check the functions have been set correctly before calling

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AtkCocoaHelper/AtkCocoaHelperMac.cs
If we try to call a null func<> then we'll get an NRE, so check they're set and warn if not.
Fixes VSTS #780731
Backport of #7650.
/cc @iainx
> [release-8.1] [A11y] Check the functions have been set correctly before calling

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/Properties/MonoDevelop.TextEditor.Cocoa.addin.xml
This is the PR to light up the Go To Line functionality in the IDE, implemented in https://github.com/xamarin/vs-editor-core/pull/319. 
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/733501
Backport of #7714.
> [release-8.1] Fixes VSTS 733501: Go To Line Number

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/Properties/MonoDevelop.TextEditor.Cocoa.addin.xml
This is the PR to light up the Go To Line functionality in the IDE, implemented in https://github.com/xamarin/vs-editor-core/pull/319. 
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/733501
> Fixes VSTS 733501: Go To Line Number

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.WelcomePage/WelcomePageService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Ide.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
GetToCode includes a setting configuration with 3 options : Allways show Startwindow, Load previous solutions on startup and show empty environtment
Looks like in recent changes we stop using this flag to shop the dialog and we were allways showing it.
This PR allows check this flag from the WelcomeService on the initialization
Fixes VSTS #894451 - Start window shown despite preference setting to display empty environment on load
> [GetToCode] Uses hideWelcomePage flag in WelcomePageService

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.WelcomePage/WelcomePageService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Ide.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
GetToCode includes a setting configuration with 3 options : Allways show Startwindow, Load previous solutions on startup and show empty environtment
Looks like in recent changes we stop using this flag to shop the dialog and we were allways showing it.
This PR allows check this flag from the WelcomeService on the initialization
Fixes VSTS #894451 - Start window shown despite preference setting to display empty environment on load
Backport of #7705.
> [release-8.1] [GetToCode] Uses hideWelcomePage flag in WelcomePageService

- main/src/addins/MonoDevelop.Debugger.VSCodeDebugProtocol/MonoDevelop.Debugger.VsCodeDebugProtocol/VSCodeDebuggerSession.cs
Copy of https://github.com/mono/monodevelop/pull/7408 for CI
Fixes VSTS #754386
'On a Mac, .NET Core debugger breaks on each exception, even if it is disabled in settings. For example, I want to break on a NullReferenceException, but the debugger stops on InvalidOperationException, Exception, ArgumentException etc.'
> Vsdbg exceptions

- main/src/addins/MacPlatform/MacPlatform.cs
- main/tests/MacPlatform.Tests/MemoryMonitorTests.cs
Processing this on a background thread will cause an AppKit NSEventThread to spin up on a background thread, which would never finish running
This thread would also be running at 100% CPU, causing a specific thread to loop and burn until the process ends
Fixes VSTS #894581 - VS Mac processes still running after quitting the app?
Fixes VSTS #802626 - [Feedback] VS usually consumes an entire CPU core when idle, killing battery life (and making my lap hot)
> [Mac] Use the main DispatchQueue when processing memory pressure events

- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/GLibLogging.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Gui/GLibLoggingTests.cs
This PR fixes up exception handling so we always and properly attach stacktraces under mono.
Also, fixes stacktraces for non-error glib events
> Handle exceptions coming in from glib and objc in a better way

- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/GLibLogging.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Gui/GLibLoggingTests.cs
This PR fixes up exception handling so we always and properly attach stacktraces under mono.
Also, fixes stacktraces for non-error glib events
Backport of #7733.
> [release-8.1] Handle exceptions coming in from glib and objc in a better way

- main/src/addins/MacPlatform/MacPlatform.cs
- main/tests/MacPlatform.Tests/MemoryMonitorTests.cs
Processing this on a background thread will cause an AppKit NSEventThread to spin up on a background thread, which would never finish running
This thread would also be running at 100% CPU, causing a specific thread to loop and burn until the process ends
Fixes VSTS #894581 - VS Mac processes still running after quitting the app?
Fixes VSTS #802626 - [Feedback] VS usually consumes an entire CPU core when idle, killing battery life (and making my lap hot)
Backport of #7734.
/cc @Therzok
> [release-8.1] [Mac] Use the main DispatchQueue when processing memory pressure events

- main/src/addins/MacPlatform/MacPlatform.cs
- main/tests/MacPlatform.Tests/MacPlatformTest.cs
The app crashes before the handler is reached, fix this by reporting it as fatal - usually the app really just does crash.
> [Mac] ObjCMarshalledException is still not reported right

- main/src/addins/MacPlatform/MacPlatform.cs
- main/tests/MacPlatform.Tests/MacPlatformTest.cs
The app crashes before the handler is reached, fix this by reporting it as fatal - usually the app really just does crash.
Backport of #7742.
/cc @Therzok
> [release-8.1] [Mac] ObjCMarshalledException is still not reported right

- main/src/addins/MacPlatform/MacInterop/Carbon.cs
Doesn't affect the code, but matches results of NSWorkspace.DidLaunchApplicationNotification.
> Fix the binding definition of the ProcessSerialNumber struct

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.cs
The way Gtk treats double/triple clicks is breaking something in Xwt and crashing when triple clicking on the language
button
Fixes VSTS #849556
> [IDE] only popup the menu on single clicks.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.cs
The way Gtk treats double/triple clicks is breaking something in Xwt and crashing when triple clicking on the language
button
Fixes VSTS #849556
Backport of #7748.
/cc @iainx
> [release-8.1] [IDE] only popup the menu on single clicks.

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/BreakpointManager.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/Tags/AbstractCurrentStatementTagger.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebuggingService.cs
This is two part fix, part is in DebuggingService which is updating actual breakpoint to new file
And other part is in new editor breakpoint integration which now doesn't use `readonly string file` but instead `textDocument.FilePath` which is mutable and updates when file is renamed and also listens for additional event.
> Fix 895583: Breakpoints not visible after renaming file

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/LogView.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/893213
Added method in the LogView to sanitize the logging text output from the node.js service for the Angular/Bootstrap functionality in the ASP.Net Core Angular template.
The logging text contained ANSI/VT100 color escape sequences and some control characters, which were causing the pango text engine to slow down significantly in order to create custom glyphs with the control codes.
> Fix Application Output hang when using ASP.Net Core Angular template

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/LogView.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/893213
Added method in the LogView to sanitize the logging text output from the node.js service for the Angular/Bootstrap functionality in the ASP.Net Core Angular template.
The logging text contained ANSI/VT100 color escape sequences and some control characters, which were causing the pango text engine to slow down significantly in order to create custom glyphs with the control codes.
Backport of #7756.
> [release-8.1] Fix Application Output hang when using ASP.Net Core Angular template

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/DockContainer.cs
This issue was detected by Watson and I can't reproduce it, but my feeling: this is it happening with dock panels with AllowDocking = false (like the Solution Explorer).
This call FindDockGroupItem will end in NRE (id not found) if we try to dock this panel at the same time we the system is Splitting a groupview or an item is Removed for some reason (the collection is cleaned on this cases). 
Fixes VSTS #861013 - [Watson] System.NullReferenceException in MonoDevelop.Components.Docking.DockContainer::DockInPlaceholder (MonoDevelop.Ide.dll)
> [Watson] Fixes NRE when FindDockGroupItem doesn't find any item

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/DockContainer.cs
This issue was detected by Watson and I can't reproduce it, but my feeling: this is it happening with dock panels with AllowDocking = false (like the Solution Explorer).
This call FindDockGroupItem will end in NRE (id not found) if we try to dock this panel at the same time we the system is Splitting a groupview or an item is Removed for some reason (the collection is cleaned on this cases). 
Fixes VSTS #861013 - [Watson] System.NullReferenceException in MonoDevelop.Components.Docking.DockContainer::DockInPlaceholder (MonoDevelop.Ide.dll)
Backport of #7685.
> [release-8.1] [Watson] Fixes NRE when FindDockGroupItem doesn't find any item

- main/src/addins/MonoDevelop.Debugger/Gui/MonoDevelop.Debugger.DebugApplicationDialog.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkMacInterop.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/ProjectCommands.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Execution/ExecutionModeCommandService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/MessageService.cs
This fixes the way of we show dialogs in our Messaging.Service, seems BeginModalSession is not parenting correctly the child windows and provokes unexpected results like odd flashes when changing desktops (CMD + LEFT/RIGHT ARROW).
Also now like a child window is attached to it's parent and it moves accordingly with it
Fixes VSTS #823695 - About info flashes briefly if left open while switching desktops
Fixes VSTS #844450 - Run/RunWith/CustomParameters window flashes briefly if left open while switching desktops
Fixes VSTS #844452 - Project/Set Startup project flashes briefly if left open while switching desktops
Fixes VSTS #899539
> [GTC] Fixes current window child hierarchy (parents) using RunCustomDialog

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/ExpansionManager.cs
Fix 901091: Caret jumps to previous line after completing a prop snippet
Backport of #7774.
> [release-8.1] Fix 901093: Completing a snippet adds a newline

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentModel.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/FileDocumentController.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/FileModel.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/ModelRepresentation.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/TextBufferFileModel.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Gui.DocumentModels/FileModelTests.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Gui.DocumentModels/TextBufferFileModelTests.cs
The MimeType property was not properly set in some cases, such as when
creating a new file, or when saving a file with a new name and extension.
FileModel now ensures that the MimeType property is always up to date,
and TextBufferFileModel now updates the content type of the buffer
when creating a new document or when saving a document.
Fixes VSTS #825629 - No error message shows up in TypeScript files
Fixes VSTS #889145 - First time to add MVC View Page file(.cshtml), the intellisense and colorization doesn't work at once and shows un-save state. It needs to reopen or insert.
Fixes VSTS #894970 - Double quotes are not automatically matched after tapping the quote key
> Fix mime type assignment issues in FileModel

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentModel.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/FileDocumentController.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/FileModel.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/ModelRepresentation.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/TextBufferFileModel.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Gui.DocumentModels/FileModelTests.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Gui.DocumentModels/TextBufferFileModelTests.cs
The MimeType property was not properly set in some cases, such as when
creating a new file, or when saving a file with a new name and extension.
FileModel now ensures that the MimeType property is always up to date,
and TextBufferFileModel now updates the content type of the buffer
when creating a new document or when saving a document.
Fixes VSTS# 825629 - No error message shows up in TypeScript files
Backport of #7779.
/cc @slluis
> [release-8.1] Fix mime type assignment issues in FileModel

- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/AssemblyBrowserViewContent.cs
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/TextViewContent.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputViewContent.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentController.cs
The disposed token can be used by continue with calls that shouldn't
continue on disposed instances.
> [Ide] Added a disposed token to the document controller API.

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/BlameView.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/DiffView.cs
in "Changes" window
Fixes VSTS Bug 901464: Copy/paste is broken in "authors" tab (wrong text or nothing happens)
Fixes Bug 901463: Copy and paste is broken or copies wrong text in "Changes"
window
DiffView was still using the old SharpDevelop clipboard command system
for cut/copy/paste. Moved to monodevelop command handlers.
> Fixes VSTS Bug 901463: Copy and paste is broken or copies wrong text

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/BlameView.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/DiffView.cs
in "Changes" window
Bug 901463: Copy and paste is broken or copies wrong text in "Changes"
window
Fixes VSTS Bug 901464: Copy/paste is broken in "authors" tab (wrong text or nothing happens)
DiffView was still using the old SharpDevelop clipboard command system
for cut/copy/paste. Moved to monodevelop command handlers.
Backport of #7788.
/cc @mkrueger
> [release-8.1] Fixes VSTS Bug 901463: Copy and paste is broken or copies wrong text

- main/src/addins/CSharpBinding/MonoDevelop.CSharp/CSharpPathedDocumentExtension.DataProvider.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/DropDownBoxListWindow.cs
Just wanted to note, same problem is in old editor, and this fix fixes both.
Backport of #7791.
/cc @slluis @DavidKarlas
> [release-8.1] Fix 901424: After click in the document navigation editor doesn't get focus

- main/src/addins/CSharpBinding/MonoDevelop.CSharp/CSharpPathedDocumentExtension.DataProvider.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/DropDownBoxListWindow.cs
Just wanted to note, same problem is in old editor, and this fix fixes both.
> Fix 901424: After click in the document navigation editor doesn't get focus

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/SearchResultWidget.cs
…
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/905613
AppendFormat was wrong there - CopyData is already formatted.
AppendFormat can easily throw an exception depending on the text
copied. This patch fixes it.
> Fixes VSTS Bug 905613: [Feedback] Cannot Copy Results of Find in Files

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/TextSegmentMarker.cs
in debug
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/904321
Exception from feedback ticket :
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/896686
Produces many out of range exceptions in text segment marker. This
checks now for empty lines - can happen during an edit session when a
line is cleared. Exceptions in that case prevent further drawing in
that line. This is now changed and the drawing code is hardened
against exceptions in line markers.
> Fixes VSTS Bug 904321: [Feedback] Xamarin Android Breakpoint not work

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopMetadataReferenceManager.cs
By doing so, we ensure that any in-flight operation to update an assembly from disk must happen before we clear the caches.
> [Workspace] Swap the order of cache clearing in the manager.

- main/build/MacOSX/make-dmg-bundle.sh
With the move to Xcode 10.2, we need to build on Mojave bots, and there's
a bug (https://github.com/al45tair/dmgbuild/issues/10) that makes unmounting
time out on the bots, which is fixed by just retrying :/
> [Mac] Retry unmounting because of an issue in the Mojave bots

- main/build/MacOSX/make-dmg-bundle.sh
With the move to Xcode 10.2, we need to build on Mojave bots, and there's
a bug (https://github.com/al45tair/dmgbuild/issues/10) that makes unmounting
time out on the bots, which is fixed by just retrying :/
Backport of #7809.
/cc @rodrmoya
> [release-8.1] [Mac] Retry unmounting because of an issue in the Mojave bots
