mono/monodevelop

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor.Utils/ClipboardColoredText.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/TextEditorData.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/InternalExtensionAPI/ITextEditorImpl.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextEditor.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/SearchResult.cs
disposed
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/774516
Backport of #6955.
/cc @mkrueger
> [release-7.8] Fixes VSTS Bug 774516: Exception in editor: TextEditorData was

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.OptionPanels/RunConfigurationsList.cs
associated label provided for the edit fields.
> Fixes VSTS Bug 752769: Accessibility: No on-screen or programmatically

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/EditorTheme.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/SyntaxHighlightingService.cs
QuickTaskOverviewMode.DrawBreakpoints
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/778397
> Added debug code for VSTS Bug 778397: NRE in

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/LanguageCellRenderer.cs
Fixes VSTS #675356
Fixes VSTS #752336
Depends on https://github.com/mono/xwt/pull/912
> Fix some issues in the New Project Dialog

- main/src/addins/MonoDevelop.AspNetCore/Properties/MonoDevelop.AspNetCore.addin.xml
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/778567
> [AspNetCore] Update template names to match VS on Windows

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/ViewCommands.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/751356
> [Ide] Disable pads in menus when main window is not visible

- main/src/addins/CSharpBinding/CSharpBinding.addin.xml
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Refactoring/RefactoryCommands.cs
Fixes VSTS #755411 - [Feedback] Custom key bindings for Remove Unused and Sort (Usings) Don't Work
Backport of #6937.
/cc @Therzok
> [release-7.8] [C#] Fix Remove Unused Imports keybinding

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/EditorTheme.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/SyntaxHighlightingService.cs
QuickTaskOverviewMode.DrawBreakpoints
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/778397
Backport of #6975.
/cc @Therzok @mkrueger
> [release-7.8] Added debug code for VSTS Bug 778397: NRE in

- main/Main.sln
- main/src/tools/ExtensionTools/AddinDependencyTreeWidget.cs
- main/src/tools/ExtensionTools/AddinInfo.cs
- main/src/tools/ExtensionTools/AddinListWidget.cs
- main/src/tools/ExtensionTools/AddinRegistryExtensions.cs
- main/src/tools/ExtensionTools/Application.cs
- main/src/tools/ExtensionTools/ExtensionNodesWidget.cs
- main/src/tools/ExtensionTools/ExtensionPointsWidget.cs
- main/src/tools/ExtensionTools/ExtensionTools.csproj
- main/src/tools/ExtensionTools/HashSetExtensions.cs
- main/src/tools/ExtensionTools/LazyNotebook.cs
- main/src/tools/ExtensionTools/MonoDevelop.ExtensionTools.addin.xml
- main/src/tools/ExtensionTools/Properties/AssemblyInfo.cs
Fixes VSTS #643442 - Tool to vizualize addin behaviour
TODO list:
> [RFC] Initial implementation of extension tool

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/ApplyPolicyDialog.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/ExportProjectPolicyDialog.cs
not visible after Policy Combo Box
> Fixes VSTS Bug 753343: Accessibility: Apply Policies Dialog: Focus is

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.csproj
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/Instrumentation.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/Repository.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlService.cs
> [VCS] Add instrumentation counters to repository operations

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdk.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/779492
> [DotNetCore] Create a DotNetCoreSdkPaths instance per project

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.csproj
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/Instrumentation.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/Repository.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlService.cs
Backport of #6976.
/cc @sevoku
> [release-7.8] [VCS] Add instrumentation counters to repository operations

- main/src/addins/GnomePlatform/GnomePlatform.cs
> Try fix Linux NRE when running sdk-based .netframework projects

- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/TextDocument.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/767140
> Fixes VSTS Bug 767140: 7.7 has regressed in typing performance

- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/TextDocument.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/767140
Backport of #7029.
/cc @mkrueger
> [release-7.8] Fixes VSTS Bug 767140: 7.7 has regressed in typing performance

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectSupportedTargetFrameworks.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/786083
> [release-7.8] [DotNetCore] Fix version support condition

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/ApplyPolicyDialog.cs
not reading the label for Policy combo box, File text field
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/753365
> Fixes VSTS Bug 753365: Accessibility: Apply Policies: Voice over is

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextEditorViewContent.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/BaseViewContent.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/SdiWorkspaceWindow.cs
directly type
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/675488
> Fixes VSTS Bug 675488: [Feedback] Changing tab doesn't allow to

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextEditorViewContent.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/BaseViewContent.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/SdiWorkspaceWindow.cs
directly type
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/675488
Backport of #6988.
/cc @mkrueger
> [release-7.8] Fixes VSTS Bug 675488: [Feedback] Changing tab doesn\u0027t allow to

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.AnalysisCore/Gui/ResultsEditorExtension.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices/MonoDevelopProjectCacheHostServiceFactory.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
Fixes leaking of MonoDevelopWorkspace via different event handler registrations and cycles.
> Workspace and Editor leak fixes

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/ExportSolutionDialog.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/681358
> [Ide] Fix NRE in ExportSolutionDialog initialization

- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Core/ProgressMonitorTests.cs
Trying a PR from a branch on the monodevelop repo to see if CI actually runs. (See #7089)
> Update TestLogSynchronizationContextThroughWrites to make it possible to troubleshoot it when it fails

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs
Backport of #7093.
/cc @Therzok @mkrueger
> [master] [SourceEditor] Optimized drawing.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/EditorFormattingServiceTextEditorExtension.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/FoldingRegion.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding/AutoFormatIntegrationTests.cs
region opens when entering a directive
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/780196
> Fixes VSTS Bug 780196: [Feedback] ディレクティブの入力時に他のregionが開く-Another

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Navigation/FindImplementingMembersHandler.cs
project doesn't work
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/749554
> Fixes VSTS Bug 749554: Navigate->Implementing Members in ASP.NET Core

- main/tests/IdeUnitTests/IdeTestBase.cs
Needed for https://github.com/xamarin/md-addins/pull/4121
> [tests] Emit the IdeApp.Exiting event when shutting down the test runner

- main/src/addins/MacPlatform/MacPlatform.cs
This is a hack to fix the crasher in #7046, but we still need the right solution.
> Fix 785490 - Crash in Xwt.Mac

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AtkCocoaHelper/AtkCocoaHelperMac.cs
Should fix some crashes WRT a11y
Fixes VSTS #790820 - Crash on startup with Accessibility enabled
> Remove erroneous extra colons

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/RefactoringPreviewTooltipWindow.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/769480
Resize was missing.
> Fixes VSTS Bug 769480: Code fix preview window is too small

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/MdTextViewLineCollection.MdTextViewLine.cs
- main/src/addins/MonoDevelop.SourceEditor2/VSEditor/TagBasedSyntaxHighlighting.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/CaretImpl.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/790861
Backport of #7147.
/cc @mkrueger
> [master] Fixes VSTS Bug 790861: Text not redrawn when auto-formatting

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/MdTextViewLineCollection.MdTextViewLine.cs
- main/src/addins/MonoDevelop.SourceEditor2/VSEditor/TagBasedSyntaxHighlighting.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/CaretImpl.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/790861
> Fixes VSTS Bug 790861: Text not redrawn when auto-formatting

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/RefactoringPreviewTooltipWindow.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/769480
Resize was missing.
Backport of #7115.
/cc @mkrueger
> [release-7.8] Fixes VSTS Bug 769480: Code fix preview window is too small

- main/src/addins/MacPlatform/Dialogs/MacCommonFileDialogHandler.cs
- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/FileCommands.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/PlatformService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/CommonAboutDialog.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.ProgressMonitoring/MultiTaskDialogProgressMonitor.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/DesktopService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/MessageService.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/785446
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/737393
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/790724
> Fix some issues with Start Window<->Main Window interaction

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/EditRemoteDialog.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitConfigurationDialog.cs
Add URL validation adding a new remote in Git.
Fixes gh #7114
> [VersionControl] Add validations adding a new remote (Git)

- main/tests/Ide.Tests/MonoDevelop.Ide/BuildOutputTests.cs
See https://github.com/xamarin/md-addins/pull/4201
> [Tests] Fix Build Output feature toggle test

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitCommitDialogExtension.cs
Added email validation overriding the user in a git commit.
Fixes gh #7103
> [VersionControl] Validate email overriding user in git commit

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/TemplateWizard.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/681741
> [Ide] For Multiplatform projects, adds multi solution config

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeTemplates/CodeTemplate.cs
wrong code
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/789329
Backport of #7161.
/cc @mkrueger
> [master] Fixes VSTS Bug 789329: [VSM] Default code snippet \u0022indexer\u0022 insert

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.UI.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/MessageService.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/790724
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/751154
Needs https://github.com/xamarin/md-addins/pull/4205
> [Ide] Fix support for native parent windows in MessageService

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitCredentials.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/XwtCredentialsDialog.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/ProgressDialog.cs
* Improved dialog layout
* code improvements/fixes
* a11y + wording improvements
* ssh key selection logic fixes
* use new dialog for basic auth
> [Git] Improve new SSH key dialog and selection logic

- .gitmodules
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git.Tests/BaseGitRepositoryTests.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git.Tests/BaseRepositoryTests.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git.Tests/GitIntegrityTests.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/Commands.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitConfigurationDialog.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitNodeBuilderExtension.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitService.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitVersionControl.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/ProjectTemplateHandler.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/Repository.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionInfo.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionInfoCache.cs
This PR updates LibGit2Sharp and libgit2:
* libgit2: [0.26.8](https://github.com/libgit2/libgit2/releases/tag/v0.26.8) + [Blame Patch](https://github.com/libgit2/libgit2/compare/v0.26.8...mono:vs-8.0-v0.26.8)
* libssh2: [1.8.0](https://github.com/libssh2/libssh2/releases/tag/libssh2-1.8.0)
* LibGit2Sharp: [0.26](https://github.com/libgit2/libgit2sharp/releases/tag/v0.26) + [Blame/SSH Patches + Revert libgit2 v0.27 API changes](https://github.com/libgit2/libgit2sharp/compare/v0.26...mono:vs-8.0-v0.26) 
Fixes VSTS #781468
Fixes VSTS #604317
Fixes GH #7101
Fixes GH #7102
Fixes GH #7105
Fixes GH #7110
Fixes GH #7113
Fixes GH #7150
> Update LibGit2Sharp to v0.26

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/OptionsDialog.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/MessageService.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/796317
> [Ide] Retrieve Policies' parent window from DesktopService

- version-checks
Updated reference to xamarin/md-addins@b5a711d
> Updated reference to xamarin/md-addins@b5a711d

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/Repository.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlItem.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlService.cs
> [VersionControl] Improve Repository Disposing

- main/src/addins/MonoDevelop.DotNetCore/Properties/MonoDevelop.DotNetCore.addin.xml
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/801504
Backport of #7235.
/cc @rodrmoya
> [release-8.0-integration] [DotNetCore] Disable VBNet templates for 3.0 also

- main/src/addins/MonoDevelop.DotNetCore/Properties/MonoDevelop.DotNetCore.addin.xml
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/801504
> [DotNetCore] Disable VBNet templates for 3.0 also

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebugCommands.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/801643
> [Debugger] Disable debug commands when IDE window is not visible

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/FileCommands.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/ViewCommands.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/NewFileDialog.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.WelcomePage/WelcomePageCommands.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/MessageService.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/801647
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/801640
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/801906
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/801901
> More Start Window-related fixes

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/FileCommands.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/ViewCommands.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/NewFileDialog.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.WelcomePage/WelcomePageCommands.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/MessageService.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/801647
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/801640
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/801906
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/801901
Backport of #7237.
> [release-8.0-integration] More Start Window-related fixes

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebugCommands.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/801643
Backport of #7240.
/cc @rodrmoya
> [release-8.0-integration] [Debugger] Disable debug commands when IDE window is not visible

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/788012
> [NetCore] Sets starting working directory according to VS on Windows

- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/ToolboxPad.cs
We were not hiding the native view of the Toolbox when Window need show/hide contents
Fixes VSTS #790903 - Toolbox and Document Outline overlap each other
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/790903
Instructions to test the Fix:
1) Open any project
2) Focus any other Pad window from the same container like the Toolbox
3) Press directly the auto-hide button from the toolbox window to de-attach to the container
4) Press for a second time the auto-hide button to attach the toolbox window to the container
Expected: the selected item is your first selected item and the toolbox is not overlapping
>  Fixes hide/show native Toolbox when window shows/hides content 

- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/ToolboxPad.cs
We were not hiding the native view of the Toolbox when Window need show/hide contents
Fixes VSTS #790903 - Toolbox and Document Outline overlap each other
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/790903
Instructions to test the Fix:
1) Open any project
2) Focus any other Pad window from the same container like the Toolbox
3) Press directly the auto-hide button from the toolbox window to de-attach to the container
4) Press for a second time the auto-hide button to attach the toolbox window to the container
Expected: the selected item is your first selected item and the toolbox is not overlapping
Backport of #7247.
> [release-8.0-integration]  Fixes hide/show native Toolbox when window shows/hides content 

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/802785
> [Ide] Add --no-start-window argument

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/802785
Backport of #7261.
> [release-8.0-integration] [Ide] Add --no-start-window argument

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/ProgressDialog.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.ProgressMonitoring/MessageDialogProgressMonitor.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/802352
> [Ide] Retrieve ProgressDialog's parent from DesktopService

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/ProgressDialog.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.ProgressMonitoring/MessageDialogProgressMonitor.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/802352
Backport of #7249.
/cc @rodrmoya
> [release-8.0-integration] [Ide] Retrieve ProgressDialog's parent from DesktopService

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/788012
Backport of #7258.
/cc @slluis @jtorres
> [release-8.0-integration] [NetCore] Sets starting working directory according to VS on Windows

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/MessageService.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/802604
> [Ide] Fix centering of dialogs over native NSWindow's

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/MessageService.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/802604
Backport of #7264.
/cc @rodrmoya
> [release-8.0-integration] [Ide] Fix centering of dialogs over native NSWindows

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Templating/DotNetCoreProjectTemplateStringTagProvider.cs
- main/src/addins/MonoDevelop.DotNetCore/Properties/MonoDevelop.DotNetCore.addin.xml
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/803985
> [DotNetCore] Enable 2.1 NUnit projects

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Templating/DotNetCoreProjectTemplateStringTagProvider.cs
- main/src/addins/MonoDevelop.DotNetCore/Properties/MonoDevelop.DotNetCore.addin.xml
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/803985
Backport of #7288.
/cc @rodrmoya
> [release-8.0-integration] [DotNetCore] Enable 2.1 NUnit projects

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/PackageReferenceNuGetProjectTests.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageReferenceNuGetProject.cs
The NuGet addin API has a PackageReferenceAdded event and a
PackageReferenceRemoved. These were being raised if a project had
a packages.config file but not if the project used PackageReferences.
Fixes VSTS #807927 - Get the events working for an Android project
that uses PackageReferences
> [NuGet] Raise install/uninstall events for PackageReference projects

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/Repository.cs
Fixes VSTS #807496
(cherry picked from commit 638990987e13b4f7fdb153abd4c1f6c67b490500)
> [7.8][VersionControl] Fix ArgumentNullException when Publishing

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/PackageReferenceNuGetProjectTests.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageReferenceNuGetProject.cs
The NuGet addin API has a PackageReferenceAdded event and a
PackageReferenceRemoved. These were being raised if a project had
a packages.config file but not if the project used PackageReferences.
Fixes VSTS #807927 - Get the events working for an Android project
that uses PackageReferences
Backport of #7302.
/cc @mrward
> [release-8.0-integration] [NuGet] Raise install/uninstall events for PackageReference projects

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Ide.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/RootWorkspace.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Services.cs
Fixes VSTS #767147 - Add telemetry to measure time to intellisense available
> Add TimeToCode timer with intellisense data 

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentViewContainer.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/GtkShellDocumentViewContainer.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/IShellDocumentViewContainer.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Gui.Documents/DocumentViewVisibilityTests.cs
- main/tests/IdeUnitTests/MockShell.cs
- main/tests/IdeUnitTests/MockShellDocumentViewContainer.cs
- main/tests/IdeUnitTests/ServiceHelper.cs
Make sure ContentVisible is properly updated when switching between tab
and split modes.
Backport of #7438.
/cc @garuma @slluis
> [release-8.1] Fix issue in DocumentView.ContentVisible

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentViewContainer.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/GtkShellDocumentViewContainer.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/IShellDocumentViewContainer.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Gui.Documents/DocumentViewVisibilityTests.cs
- main/tests/IdeUnitTests/MockShell.cs
- main/tests/IdeUnitTests/MockShellDocumentViewContainer.cs
- main/tests/IdeUnitTests/ServiceHelper.cs
Make sure ContentVisible is properly updated when switching between tab
and split modes.
Backport of #7438.
/cc @garuma @slluis
> [release-8.1-preview2] Fix issue in DocumentView.ContentVisible

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.DockNotebook/PlaceholderWindow.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/DefaultWorkbench.cs
Fixes VSTS #849798 - NullReferenceException in SetTitle because
window.Document is null
> Fix NRE when opening file

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.DockNotebook/PlaceholderWindow.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/DefaultWorkbench.cs
Fixes VSTS #849798 - NullReferenceException in SetTitle because
window.Document is null
Backport of #7461.
/cc @slluis
> [release-8.1] Fix NRE when opening file

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/DefaultWorkbench.cs
It is handled, so it is not a crash.
> Fix NRE at startup

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/MimeTypePolicyOptionsSection.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/PolicyOptionsPanel.cs
(cherry picked from commit 1305cd61cc8a7d8cf7274f69162f0945aea6f06e)
> Fixes VSTS #857551 - [EN-US] Grammar Correction

- main/src/addins/CSharpBinding/CSharpBinding.csproj
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.ClassOutline/CSharpOutlineTextEditorExtension.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.ClassOutline/CSharpOutlineTextEditorExtensionProvider.cs
Added support for the new extensibility approach via MEF in the outline view.
> Fixes VSTS Bug 829199: [Feedback] Document Outline doesn't work with New Editor

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/SdiWorkspaceWindow.cs
Fixes VSTS #889280 - Cannot move between xaml files
Fixes VSTS #889281 - IDE crashes when clicking on a document tab to swap
documents
> [release-8.1] Fix NRE when switching documents

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/TextViewDisplayBinding.cs
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/889423
> TextEditor: Update name of new editor display binding

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/TextViewDisplayBinding.cs
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/889423
Backport of #7503.
> [release-8.1] TextEditor: Update name of new editor display binding

- main/src/addins/CSharpBinding/CSharpBinding.csproj
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.ClassOutline/CSharpOutlineTextEditorExtension.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.ClassOutline/CSharpOutlineTextEditorExtensionProvider.cs
Added support for the new extensibility approach via MEF in the outline view. 
Backport of #7468.
> [release-8.1] Fixes VSTS Bug 829199: [Feedback] Document Outline doesn't work with New Editor

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/866899
> Fixed VSTS Bug 866899: [Feedback] 'Find in files' in xaml page

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/866899
Backport of #7456.
/cc @mkrueger
> [release-8.1] Fixed VSTS Bug 866899: [Feedback] \u0027Find in files\u0027 in xaml page

- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/ToolboxPad.cs
Fixes VSTS #832344
Fixes VSTS #806779
> [Toolbox] Ensures only load toolbox if has min MacOS version

- main/src/addins/MonoDevelop.Debugger.VSCodeDebugProtocol/MonoDevelop.Debugger.VsCodeDebugProtocol/VSCodeDebuggerSession.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/698194/
> [Debugger] Implement Set Next Statement for the VsCode debugger backend

- main/src/addins/MonoDevelop.Debugger.VSCodeDebugProtocol/MonoDevelop.Debugger.VsCodeDebugProtocol/VSCodeDebuggerSession.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/698194/
Backport of #7443.
/cc @slluis @jstedfast
> [release-8.1] [Debugger] Implement Set Next Statement for the VsCode debugger backend

- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/TextDocument.cs
undone/redone in a xaml file
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/889278
> Fixes VSTS Bug 889278: Exceptions are thrown whenever a change is

- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/TextDocument.cs
undone/redone in a xaml file
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/889278
Backport of #7510.
/cc @mkrueger
> [release-8.1] Fixes VSTS Bug 889278: Exceptions are thrown whenever a change is

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/INewProjectDialogBackend.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/NewProjectController.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/TemplateWizardProvider.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/WizardPage.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Projects/DummyNewProjectDialogBackend.cs
Needed for https://github.com/xamarin/md-addins/pull/4606
> [Ide] Add ability for WizardPage's to request next page

- main/src/addins/MonoDevelop.DotNetCore/DotNetCoreDownloadUrl.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.csproj
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreNotInstalledDialog.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdk.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreVersion.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/DotNetCoreNuGetProjectTests.cs
- main/tests/test-projects/restore-netcore-offline/dotnetcoreconsole.csproj
Clearly specify what versions the user has to install, to avoid confusion.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/889382
> [DotNetCore] Improve SDK not supported message

- main/src/addins/MacPlatform/MacTelemetryDetails.cs
> [Mac] Add a null check for return from DetectStringEncoding

- main/src/addins/MacPlatform/MacTelemetryDetails.cs
Fixes VSTS #895289
Backport of #7593.
/cc @iainx
> [release-8.1] [Mac] Add a null check for return from DetectStringEncoding

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/TextViewContent.Toolbox.cs
> [release-8.1] Fix Windows build.

- version-checks
Updated reference to xamarin/md-addins@e2fe31d
> Updated reference to xamarin/md-addins@e2fe31d

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/INewProjectDialogBackend.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/NewProjectController.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/TemplateWizardProvider.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/WizardPage.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Projects/DummyNewProjectDialogBackend.cs
Needed for https://github.com/xamarin/md-addins/pull/4606
Backport of #7544.
/cc @rodrmoya
> [release-8.1] [Ide] Add ability for WizardPage\u0027s to request next page

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.DockNotebook/DockWindow.cs
When closing the floating window, only the first document of the notebook
was closed before returning from the close event handler.
The fix ensures that all documents are closed.
Fixes VSTS 895763 - Document close issue with floating documents
> Fix issue when closing floating document notebook

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.DockNotebook/DockWindow.cs
When closing the floating window, only the first document of the notebook
was closed before returning from the close event handler.
The fix ensures that all documents are closed.
Fixes VSTS 895763 - Document close issue with floating documents
Backport of #7603.
/cc @slluis
> [release-8.1] Fix issue when closing floating document notebook

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/Properties/MonoDevelop.TextEditor.addin.xml
- main/src/core/MonoDevelop.Ide/ExtensionModel/MainMenu.addin.xml
Verbiage and default shortcuts taken from Windows.
Fixes: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/801922
> TextEditor: Map and menu for multi-caret commands

- main/Directory.Build.props
> [release-8.1] Bump Roslyn to 3.1.0-beta4-19261-04

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.addin.xml
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/Properties/MonoDevelop.TextEditor.Cocoa.addin.xml
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/Properties/MonoDevelop.TextEditor.addin.xml
> [release-8.1] Fixes VSTS 843514: Go to Base Declaration is missing 

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/TextViewContent.Commands.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/896797
Backport of #7619.
> [release-8.1] TextEditor: Enable multi-caret commands during Find

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/TextViewContent.Commands.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/896797
> TextEditor: Enable multi-caret commands during Find

- main/src/addins/MonoDevelop.DotNetCore/DotNetCoreDownloadUrl.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.csproj
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreNotInstalledDialog.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdk.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreVersion.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/DotNetCoreNuGetProjectTests.cs
- main/tests/test-projects/restore-netcore-offline/dotnetcoreconsole.csproj
Clearly specify what versions the user has to install, to avoid confusion.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/889382
Backport of #7526.
/cc @rodrmoya
> [release-8.1] [DotNetCore] Improve SDK not supported message

- main/src/addins/MacPlatform/MainToolbar/ButtonBar.cs
> [Mac] Don't pass null to SetToolTip

- main/src/addins/MacPlatform/MainToolbar/ButtonBar.cs
Fixes VSTS #892065
Backport of #7622.
/cc @iainx
> [release-8.1] [Mac] Don\u0027t pass null to SetToolTip

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/Properties/MonoDevelop.TextEditor.addin.xml
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/896798
> TextEditor: Put multi-caret commands in "Text Editor" category

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/Properties/MonoDevelop.TextEditor.addin.xml
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/896798
Backport of #7632.
> [release-8.1] TextEditor: Put multi-caret commands in \u0022Text Editor\u0022 category

- version-checks
Updated reference to xamarin/md-addins@62a26fe
> Updated reference to xamarin/md-addins@62a26fe

- main/src/addins/MonoDevelop.Debugger.VSCodeDebugProtocol/MonoDevelop.Debugger.VsCodeDebugProtocol/VSCodeDebuggerSession.cs
- main/src/addins/MonoDevelop.Debugger.VSCodeDebugProtocol/MonoDevelop.Debugger.VsCodeDebugProtocol/VsCodeBacktrace.cs
- main/src/addins/MonoDevelop.Debugger.VSCodeDebugProtocol/MonoDevelop.Debugger.VsCodeDebugProtocol/VsCodeObjectSource.cs
- main/src/addins/MonoDevelop.Debugger.VSCodeDebugProtocol/MonoDevelop.Debugger.VsCodeDebugProtocol/VsCodeStackFrame.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.Tests/DebugTests.MonoDevelop.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.Tests/MonoDevelop.Debugger.Tests.csproj
This is a back-port of https://github.com/mono/monodevelop/pull/7531
> [8.1][NetCoreDebugger] Improved consistency w/ Sdb debugger and refactored unit tests

- main/tests/Ide.Tests/MonoDevelop.Ide/BuildOutputTests.cs
This needs https://github.com/xamarin/md-addins/pull/4657
> [Tests] Make BuildOutput feature toggle test be version agnostic

- main/tests/Ide.Tests/MonoDevelop.Ide/BuildOutputTests.cs
This needs https://github.com/xamarin/md-addins/pull/4657
Backport of #7626.
/cc @rodrmoya
> [release-8.1] [Tests] Make BuildOutput feature toggle test be version agnostic

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/TextViewContent.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/899337
> TextViewContent: API change to get file change notifications working again

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/TextViewContent.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/899337
Backport of #7668.
> [release-8.1] TextViewContent: API change to get file change notifications working again

- version-checks
Updated reference to xamarin/md-addins@e1f1828
Includes designer bump.
> Updated reference to xamarin/md-addins@e1f1828

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/RevertCommand.cs
> Grammar correction (en-US)

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/RevertCommand.cs
Fixes VSTS #857554
Backport of #7686.
> [release-8.1] Grammar correction (en-US)

- version-checks
Updated reference to xamarin/md-addins@9698fe8
https://github.com/xamarin/md-addins/compare/dc82569f1c2839d89d8f31ba3fba88dca42f14a5...9698fe8c04808355d4f32e70d0f955c1d89997ad
synchronizes versions of XA, XI and XM with VS 16.1
> Updated reference to xamarin/md-addins@9698fe8

- version-checks
Updated reference to xamarin/md-addins@3e94aa3
> Updated reference to xamarin/md-addins@3e94aa3

- version-checks
Updated reference to xamarin/md-addins@47fc5cd
> Updated reference to xamarin/md-addins@47fc5cd

- version-checks
Updated reference to xamarin/md-addins@98a0f51
> Updated reference to xamarin/md-addins@98a0f51

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Refactoring/NuGetPackageServicesProxy.cs
Remove more unnecessary or problematic uses of Runtime.RunInMainThread,
again due to Roslyn blocking the main thread, and then calling services
like this from async tasks it also blocks on.
Interesting note: the async call in GetInstalledVersions is actually
entirely synchronous, but we cannot change all the methods involved
because they are implementing interfaces from NuGet. So running it on
the threadpool is totally unnecessary, but protects us in case things
change in the future.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/900631
Backport of #7701.
> [release-8.1] Packaging: More thread-safety in NuGetPackageServicesProxy

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Refactoring/NuGetPackageServicesProxy.cs
Remove more unnecessary or problematic uses of Runtime.RunInMainThread,
again due to Roslyn blocking the main thread, and then calling services
like this from async tasks it also blocks on.
Interesting note: the async call in GetInstalledVersions is actually
entirely synchronous, but we cannot change all the methods involved
because they are implementing interfaces from NuGet. So running it on
the threadpool is totally unnecessary, but protects us in case things
change in the future.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/900631
> Packaging: More thread-safety in NuGetPackageServicesProxy

- version-checks
Updated reference to xamarin/md-addins@cdd7e39
> Updated reference to xamarin/md-addins@cdd7e39

- version-checks
Updated reference to xamarin/md-addins@e828b80
> Updated reference to xamarin/md-addins@e828b80

- version-checks
Updated reference to xamarin/md-addins@0b2e210
> Updated reference to xamarin/md-addins@0b2e210

- version-checks
Updated reference to xamarin/md-addins@b74dfd0
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/901707
> [release-8.1] Updated reference to xamarin/md-addins@b74dfd0

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
> [master] Fix build error on Windows in AccessibilityElementProxy.

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/MonoDevelop.TextEditor.Cocoa.csproj
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/Properties/MonoDevelop.TextEditor.Cocoa.addin.xml
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/ThemeToClassification.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/735633
> Integrate Changed lines margin and map used colors

- main/Makefile.am
This reverts commit 16d834a7ab2a43b0b603dd62190bf626e8940589.
cc @sandyarmstrong
> Revert "Also set nuget verbosity to quiet"

- main/build/MacOSX/Info.plist.in
- main/build/MacOSX/Makefile.am
> [Build] Bump minimum deployment OS version to 10.12

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/TreeNodeNavigator.cs
> [IDE] Handle null case when getting node name

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/TreeNodeNavigator.cs
Fixes VSTS #861007
Backport of #7750.
/cc @iainx
> [release-8.1] [IDE] Handle null case when getting node name

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/InternalExtensionAPI/ITextEditorImpl.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextEditor.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextEditorViewContent.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/TextBufferFileModel.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs
changes made to project
Fixes VSTS Bug 897623: Unable to save changes after undoing changes for reloaded file
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/866898
> Fixes VSTS Bug 866898: Project file not reloaded in editor after

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/InternalExtensionAPI/ITextEditorImpl.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextEditor.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextEditorViewContent.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/TextBufferFileModel.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs
changes made to project
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/866898
Backport of #7605.
> [release-8.1] Fixes VSTS Bug 866898: Project file not reloaded in editor after

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/ExpansionManager.cs
Fix 901091: Caret jumps to previous line after completing a prop snippet
> Fix 901093: Completing a snippet adds a newline

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/TfsSmartSubtransport.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/789402
> Fixes VSTS #789402: TfsSmartSession - should use HttpClientProvider

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpHighlightUsagesExtension.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/LanguageService.fs
backport of #7793
Fixes VSTS #904300
> Remove usage of GetTypedParseResultWithTimeout

- main/src/addins/CSharpBinding/CSharpBinding.csproj
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Debugger/CSharpBreakpointSpanResolver.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/BreakpointManager.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.csproj
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebuggingService.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DefaultBreakpointSpanResolver.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/IBreakpointSpanResolver.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/887700/
> [Debugger] Added new breakpoint span resolver for C#

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/TypeSystemService_WorkspaceHandling.cs
> Fix crash when switching configurations

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/TypeSystemService_WorkspaceHandling.cs
Fixes VSTS #910800
Backport of #7817.
/cc @slluis
> [release-8.1] Fix crash when switching configurations

- version-checks
Updated reference to xamarin/md-addins@77b0384
> Updated reference to xamarin/md-addins@77b0384

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
Fixes VSTS #892087
Backport of #7823.
/cc @slluis
> [release-8.1] Fix issue in generate new class refactoring

- version-checks
Updated reference to xamarin/md-addins@a3aa734
> Updated reference to xamarin/md-addins@a3aa734

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
> Fix issue in generate new class refactoring

- main/build/MacOSX/make-dmg-bundle.sh
This fixes 'make dmg' step in VSTS on the Mojave bot pool, where doing the
image generation in several steps, including mounting and unmounting, was
timing out.
> [Mac] Refactor DMG generation to just use a single hdiutil call

- main/tests/performance/MonoDevelop.Ide.PerfTests/Baseline_MonoDevelop.Ide.PerfTests.xml
- main/tests/performance/MonoDevelop.Ide.PerfTests/TestSolutionBuild.cs
- main/tests/performance/MonoDevelop.Ide.PerfTests/TestSolutionLoad.cs
- main/tests/performance/PerfTool/Program.cs
- main/tests/performance/PerfTool/TestSuiteResult.cs
Fixes VSTS #827654 - Enable performance tests in CI
> [Perf Tests] Enable perf tests in CI by updating baseline mechanism

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/MacSplitterWidget.cs
Make sure to remove the global GDK event filter when
the widget is removed from a superview or disposed, and
add a santiy check to the filter func, ensuring to restore
regular GDK operation.
Additionally recover GDK events after longer inactivity
to recover from the rare case when some other native
widget starts stealing events, so the drag mode never
ends, blocking GDK forever.
See #7762
> Harden the MacSplitterWidget GDK event filter

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/DropDownBoxListWindow.cs
Fixes VSTS #916199 - Crashes when selecting item on members DropDown list box
Backport of #7865.
/cc @slluis
> [release-8.1] Fix NRE in DropDownBoxListWindow

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/DropDownBoxListWindow.cs
Fixes VSTS #916199 - Crashes when selecting item on members DropDown list box
> Fix NRE in DropDownBoxListWindow

- version-checks
Updated reference to xamarin/md-addins@28de185
> Updated reference to xamarin/md-addins@28de185

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/DropDownBoxListWindow.cs
Fixes VSTS #916199 - Crashes when selecting item on members DropDown list box
Backport of #7865.
/cc @slluis 
Backport of #7866.
/cc @slluis @monojenkins
> [release-8.2-preview1] [release-8.1] Fix NRE in DropDownBoxListWindow

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentController.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/911693
Revert "[Ide] Added a disposed token to the document controller API."
This reverts commit 800c10b8d37ebc6aeb9367390bc3015244614701.
Backport of #7856.
> [release-8.2-preview1] Fixes VSTS Bug 911693: New document model dispose logic was regressed

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextEditorViewContent.cs
Fixes some issues I saw using the old editor.
Fixes VSTS #915554 - Old editor adds BOM to file on saving
> Fix old editor settings/issues

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/Scope.cs
> Fixes issue #7825 Unable to search in open files if assembly browser

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/ExtensibleTreeView.cs
dispose the old ones
https://github.com/mono/monodevelop/issues/7406
> Fixes issue #7406 NodeBuilder update due to condition changes do not

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/Scope.cs
> [release-8.1] Fixes issue #7825 Unable to search in open files if assembly browser

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/DefaultBlameViewHandler.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/DefaultDiffViewHandler.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/DefaultMergeViewHandler.cs
control not showing
https://dev.azure.com/devdiv/DevDiv/_workitems/edit/918645
Backport of #7902.
/cc @mkrueger
> [release-8.1] Fixes VSTS Bug 918645: [Feedback] Diff - Difference option in Version

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/DefaultBlameViewHandler.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/DefaultDiffViewHandler.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/DefaultMergeViewHandler.cs
control not showing
https://dev.azure.com/devdiv/DevDiv/_workitems/edit/918645
> Fixes VSTS Bug 918645: [Feedback] Diff - Difference option in Version

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/UrlBasedRepositoryEditor.cs
Avoid malformed URL error trying to checkout a repo.
Fixes VSTS #899950
> [Version Control] Validate repository url when trying to checkout

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/UrlBasedRepository.cs
Fix checkout error trying to use an url with spaces at the end
Fixes VSTS #901437
> [Version Control] Checkout problem using spaces at the end of the URL

- NuGet.config
Should improve nuget restore performance a bit.
> Comment out one NuGet source from config

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/UrlBasedRepositoryEditor.cs
Avoid malformed URL error trying to checkout a repo.
Fixes VSTS #899950
Backport of #7851.
> [release-8.2] [Version Control] Validate repository url when trying to checkout

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreExecutionCommand.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/890143
> Enable debugger extensions to support ASP.NET Core debugging

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_queries/edit/923054
> GtkNSViewHost: fix NRE in OnFocusOutEvent

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/ExceptionCaught/ExceptionCaughtAdornmentManager.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/923058
> [release-8.1] ExceptionCaughtAdornmentManager: catch and log exception

- version-checks
Updated reference to xamarin/md-addins@d529123
> Updated reference to xamarin/md-addins@d529123

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/FileCommands.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/RootWorkspace.cs
> Fixes issue #6270 Allow disabling the `solution already opened`

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/FileCommands.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/RootWorkspace.cs
> [release-8.2] Fixes issue #6270 Allow disabling the `solution already opened`

- version-checks
Updated reference to xamarin/md-addins@3a8ed64
> Updated reference to xamarin/md-addins@3a8ed64

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebugCommands.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/916578
> [Debugger] Don't clear NonUserBreakpoints when clearing all breakpoints

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSystemInformation.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/899144
> [DotNetCore] Don't offer .NET Core update if not installed already

- main/Directory.Build.props
FYI @sandyarmstrong
Changes since [2e7c46d683](https://www.github.com/dotnet/roslyn/commit/2e7c46d683):
- [Merge pull request #36345 from jasonmalinowski/unskip-test](https://www.github.com/dotnet/roslyn/pull/36345)
- [Add option to emit nullable metadata for public members only (#36398)](https://www.github.com/dotnet/roslyn/pull/36398)
- [Added null checks on F# external access services (#36469)](https://www.github.com/dotnet/roslyn/pull/36469)
- [Merge pull request #36465 from dotnet/revert-36006-extract_open_file_tracker](https://www.github.com/dotnet/roslyn/pull/36465)
- [Merge pull request #36463 from tmeschter/ShortenLongResourceID-190614](https://www.github.com/dotnet/roslyn/pull/36463)
- [Merge pull request #36462 from dotnet/dev/jorobich/add-wpf-reference](https://www.github.com/d …
> [release-8.2] Bump Roslyn to 3.2.0-beta4-19317-08

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSystemInformation.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/899144
Backport of #7970.
/cc @rodrmoya
> [release-8.2] [DotNetCore] Don't offer .NET Core update if not installed already

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreExecutionCommand.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/890143
Backport of #7932.
> [release-8.2] Enable debugger extensions to support ASP.NET Core debugging

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
because LibGit2Sharp (Ide closed)
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/901467
Running that as blocking operation could lead to locks/very long
delays running repository.Blame in locked context should fix a
possible multi threaded blame issue. However I couldn't reproduce the
issue.
Improved blame code a bit.
Backport of #7874.
> [release-8.2] Fixes VSTS Bug 901467: Suddenly and silently native crash in the IDE

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/UrlBasedRepository.cs
Fix checkout error trying to use an url with spaces at the end
Fixes VSTS #901437 
Backport of #7795.
> [release-8.2] [Version Control] Checkout problem using spaces at the end of the URL

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/OnTheFlyFormattingPanel.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices.Options/RoslynPreferences.cs
* ShowCompletionItemFilters (new UI landing in editor)
* TriggerOnDeletion (forced in old editor, configurable in new)
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/914033
> C#: Add some missing options

- main/src/tools/mdtool/mdtool.csproj
- main/src/tools/mdtool/src/mdtool.cs
> [mdtool] Call terminate when ending

- main/src/addins/MacPlatform/MainToolbar/MainToolbar.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbarController.cs
> [Mac] Align the search popup correctly when the app is in fullscreen mode

- main/src/addins/MacPlatform/MainToolbar/MainToolbar.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbarController.cs
Fixes VSTS #901009
Backport of #7955.
/cc @iainx
> [release-8.2] [Mac] Align the search popup correctly when the app is in fullscreen mode

- main/src/core/MonoDevelop.Ide/ExtensionModel/StockIcons.addin.xml
Add imageid for TaskList icon into StockIcons.addin.xml
For reference from KnownImageIds
https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.imaging.knownimageids.tasklist
> [Ide] Add imageid for TaskList icon

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
LibGit2Sharp.Core.NativeMethods:git_index_read
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/845601
Update is now suspended during rebase, cherry-pick & revert
operations. That should fix the index_read crash.
> Fixes VSTS Bug 845601: Fatal crash (MERP) in

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/Properties/MonoDevelop.TextEditor.addin.xml
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/832757
Backport of #7980.
> [release-8.2] TextEditor: Map folding commands 

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/Properties/MonoDevelop.TextEditor.addin.xml
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/832757
> TextEditor: Map folding commands 

- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/AssemblyBrowserWidget.cs
in
MonoDevelop.AssemblyBrowser.AssemblyBrowserWidget.<>c__XXX.<SetReferencedSegments>b__XXX()
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/935156
fixed a small issue on request new view as well.
> Fixes VSTS Bug 935156: [FATAL] System.NullReferenceException exception

- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/AssemblyBrowserWidget.cs
in
MonoDevelop.AssemblyBrowser.AssemblyBrowserWidget.<>c__XXX.<SetReferencedSegments>b__XXX()
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/935156
fixed a small issue on request new view as well.
Backport of #8008.
/cc @mkrueger
> [release-8.2] Fixes VSTS Bug 935156: [FATAL] System.NullReferenceException exception

- main/src/addins/MacPlatform/MainToolbar/MainToolbar.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbarController.cs
Fixes VSTS #901009
Backport of #7955.
/cc @iainx
> [release-8.1] [Mac] Align the search popup correctly when the app is in fullscreen mode

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Tasks/CommentTasksProvider.Legacy.cs
MonoDevelop.Ide.Tasks.LegacyDocumentExtension.<>c__XXX.<<Context_DocumentParsed>b__XXX.MoveNext()
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/935199
> Fixes VSTS Bug 935199: System.NullReferenceException exception in

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Tasks/CommentTasksProvider.Legacy.cs
MonoDevelop.Ide.Tasks.LegacyDocumentExtension.<>c__XXX.<<Context_DocumentParsed>b__XXX.MoveNext()
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/935199
Backport of #8011.
/cc @mkrueger
> [release-8.2] Fixes VSTS Bug 935199: System.NullReferenceException exception in

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/PlatformService.cs
exception in System.IO.FileStream..ctor()
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/935133
> Fixes VSTS Bug 935133: [FATAL] System.UnauthorizedAccessException

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/PlatformService.cs
exception in System.IO.FileStream..ctor()
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/935133
Backport of #8023.
/cc @mkrueger
> [release-8.2] Fixes VSTS Bug 935133: [FATAL] System.UnauthorizedAccessException

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
LibGit2Sharp.Core.NativeMethods:git_index_read
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/845601
Update is now suspended during rebase, cherry-pick & revert
operations. That should fix the index_read crash.
Backport of #7981.
/cc @mkrueger
> [release-8.2] Fixes VSTS Bug 845601: Fatal crash (MERP) in

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CompletionProvider/ProtocolMemberCompletionProvider.cs
Setting IsExclusive to true and ensuring our `ProtocolCompletionMemberProvider` gets called even after `override` keyword is already written. 
This change will ensure our completion data will get surfaced *alongisde* completion suggestions from the other exclusive provider, which is the actual override provider. There was a recent Roslyn change, starting from 16.2.P4 where exclusivity simply means grouping - showing all exclusive ones, not just whoever gets there first. Additionally, we are now ensuring our provider also gets called when there is an insertion/deletion going on (i.e. after the user writes override).
Note: This should only start actually working when we get the Roslyn change that includes the merge from [this PR](https://github.com/dotnet/roslyn/pull/36088), specifically …
> Fixes VSTS 896684: Override keyword does not show protocol completions

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CompletionProvider/ProtocolMemberCompletionProvider.cs
Setting IsExclusive to true and ensuring our `ProtocolCompletionMemberProvider` gets called even after `override` keyword is already written. 
This change will ensure our completion data will get surfaced *alongisde* completion suggestions from the other exclusive provider, which is the actual override provider. There was a recent Roslyn change, starting from 16.2.P4 where exclusivity simply means grouping - showing all exclusive ones, not just whoever gets there first. Additionally, we are now ensuring our provider also gets called when there is an insertion/deletion going on (i.e. after the user writes override).
Note: This should only start actually working when we get the Roslyn change that includes the merge from [this PR](https://github.com/dotnet/roslyn/pull/36088), specifically …
> [release-8.2] Fixes VSTS 896684: Override keyword does not show protocol completions

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeTemplates/CodeTemplate.cs
exception in
MonoDevelop.Ide.Editor.ReadonlyTextDocumentExtensions.GetTextBetween()
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/937024
> Fixes VSTS Bug 937024: [FATAL] System.InvalidOperationException

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeTemplates/CodeTemplate.cs
exception in
MonoDevelop.Ide.Editor.ReadonlyTextDocumentExtensions.GetTextBetween()
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/937024
Backport of #8070.
> [release-8.2] Fixes VSTS Bug 937024: [FATAL] System.InvalidOperationException

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/DiffView.cs
working as expected.
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/938343
> Fixes VSTS Bug 938343: [Feedback] Diff Option in Version Control not

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/DiffView.cs
working as expected.
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/938343
Backport of #8061.
> [release-8.1] Fixes VSTS Bug 938343: [Feedback] Diff Option in Version Control not

- main/src/addins/MonoDevelop.SourceEditor2/VSEditor/TagBasedSyntaxHighlighting.cs
exception in Microsoft.VisualStudio.Text.SnapshotSpan..ctor()
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/938323
Real fix was using the correct snapshot in the constructor: new
SnapshotSpan(snapshotLine.Snapshot, snapshotLine.Extent.Span); - using
the SnapShot from the text buffer may throw an exception.
> Fixes VSTS Bug 938323: [FATAL] System.ArgumentOutOfRangeException

- main/src/addins/MonoDevelop.SourceEditor2/VSEditor/TagBasedSyntaxHighlighting.cs
exception in Microsoft.VisualStudio.Text.SnapshotSpan..ctor()
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/938323
Real fix was using the correct snapshot in the constructor: new
SnapshotSpan(snapshotLine.Snapshot, snapshotLine.Extent.Span); - using
the SnapShot from the text buffer may throw an exception.
Backport of #8088.
> [release-8.2] Fixes VSTS Bug 938323: [FATAL] System.ArgumentOutOfRangeException

- main/src/addins/MacPlatform/MacPlatform.cs
> [A11y] Only show the VoiceOver notification once.

- main/src/addins/MacPlatform/MacPlatform.cs
Fixes VSTS #729402
Backport of #8048.
/cc @iainx
> [release-8.2] [A11y] Only show the VoiceOver notification once.

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/ExceptionCaught/ExceptionCaughtAdornmentManager.cs
> [release-8.2] Fix 923058: ArgumentOutOfRangeException in GetCharacterBounds

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Debugger/CSharpBreakpointSpanResolver.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/935126/
> [Debugger] Protect against NRE's in the CSharpBreakpointSpanResolver

- main/po/ca.po
- main/po/cs.po
- main/po/da.po
- main/po/de.po
- main/po/es.po
- main/po/fr.po
- main/po/gl.po
- main/po/hu.po
- main/po/id.po
- main/po/it.po
- main/po/ja.po
- main/po/ko.po
- main/po/messages.po
- main/po/nb.po
- main/po/nl.po
- main/po/pl.po
- main/po/pt.po
- main/po/pt_BR.po
- main/po/ru.po
- main/po/sl.po
- main/po/sv.po
- main/po/tr.po
- main/po/uk.po
- main/po/zh_CN.po
- main/po/zh_TW.po
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/938534
Backport of #8120.
/cc @rodrmoya
> [release-8.2] Update translations

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Navigation/TextFileNavigationPoint.cs
I'm not exactly sure how that exception happened(maybe TextBuffer of TextView changed). But with this change problem of snapshots coming from different textbuffers can't happen again.
Backport of #8073.
> [release-8.2] Fix 935197: Exception in TextFileNavigationPoint.OnDocumentClosing

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Navigation/TextFileNavigationPoint.cs
I'm not exactly sure how that exception happened(maybe TextBuffer of TextView changed). But with this change problem of snapshots coming from different textbuffers can't happen again.
> Fix 935197: Exception in TextFileNavigationPoint.OnDocumentClosing

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/DefaultWorkbench.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/RootWorkspace.cs
> [release-8.2] Fixes VSTS Bug 937036: [FATAL] System.NullReferenceException exception  in MonoDevelop.Ide.Gui.DefaultWorkbench.get_Memento()

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/DiffView.cs
working as expected.
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/938343
Backport of #8061.
/cc @mkrueger
> [release-8.2] Fixes VSTS Bug 938343: [Feedback] Diff Option in Version Control not

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.WelcomePage/WelcomePageService.cs
> [Ide] Add WelcomeWindow shown/hidden events

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.WelcomePage/WelcomePageService.cs
Fixes VSTS #853624
Backport of #8133
> [release-8.2] [Ide] Add WelcomeWindow shown/hidden events

- main/src/addins/MacPlatform/MacPlatform.cs
It turns out the answer to
// FIXME: could this block in rare cases?
was "No, it blocks every time", so make the delegate async and await on the call instead.
Also remove the old Carbon handler and move the important bits into the Cocoa handler instead as it hasn't been deprecated for at least a decade
Fixes VSTS #942401
Backport of #8143.
> [release-8.2] [Mac] Don't hang when terminating through the dock icon

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValueTreeView.cs
https://github.com/mono/monodevelop/commit/ef5ea322347547cb6d971b6097b41965312178e6 introduced a regression where we would load the children on a background thread.
That seems to race with debugger suspending/resuming. Go back to running on the UI thread. Also, fix up usage of the token source.
> [Debugger] Fix regression introduced when optimizing handlers

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValueTreeView.cs
https://github.com/mono/monodevelop/commit/ef5ea322347547cb6d971b6097b41965312178e6 introduced a regression where we would load the children on a background thread.
That seems to race with debugger suspending/resuming. Go back to running on the UI thread. Also, fix up usage of the token source.
Backport of #8034.
/cc @Therzok
> [release-8.2] [Debugger] Fix regression introduced when optimizing handlers

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/BreakpointManager.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/PinnedWatchStore.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.QuickTasks/QuickTaskOverviewMode.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs
Might fix https://devdiv.visualstudio.com/DevDiv/_workitems/edit/935168/
> [Debugger] Make sure to lock around BreakpointStore when using it

- main/src/addins/MonoDevelop.Debugger.VSCodeDebugProtocol/MonoDevelop.Debugger.VsCodeDebugProtocol/VSCodeDebuggerSession.cs
I previously "fixed" this to do StepInRequest but I was wrong.
> [Debugger] Fixed VSCodeDebuggerSession.OnNextInstruction

- main/external/fsharpbinding/paket.dependencies
- main/external/fsharpbinding/paket.lock
Backport of #8167.
/cc @sevoku @nosami
> [release-8.2-xcode11] Bump fantomas

- main/external/fsharpbinding/paket.dependencies
- main/external/fsharpbinding/paket.lock
Backport of #8167.
/cc @sevoku @nosami
> [release-8.2] Bump fantomas

- main/src/addins/MonoDevelop.Debugger.VSCodeDebugProtocol/MonoDevelop.Debugger.VsCodeDebugProtocol/VSCodeDebuggerSession.cs
I previously "fixed" this to do StepInRequest but I was wrong.
> [8.2][Debugger] Fixed VSCodeDebuggerSession.OnNextInstruction

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectSupportedTargetFrameworks.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/TargetFrameworkExtensions.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/943143
> [DotNetCore] Add support for .NETStandard 2.1 in .NET Core 3

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/CredentialsDialog.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
repo with username and password
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/940369
Password is not saved because of security issues. We can't just store
the hash we only can store it as text which is a security risk.
> Fixes VSTS Bug 940369: [Git] Preserve username when checking out a

- main/src/addins/MacPlatform/MainToolbar/SelectorView.cs
> [Mac] Use FirstOrDefault in case there is no matching configurations

- main/src/addins/MacPlatform/MainToolbar/SelectorView.cs
Fixes VSTS #941964
Backport of #8177.
/cc @iainx
> [release-8.2] [Mac] Use FirstOrDefault in case there is no matching configurations

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/GtkWorkarounds.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeInstanceConnection.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
Fixes VSTS #944831 - [FATAL] System.UnauthorizedAccessException exception in System.IO.File.Delete()
Fixes VSTS #938537 - [Watson] SIGABRT due to IdeInstanceConnection.StartListening
> [Mac] Remove IdeInstanceConnection socket on Mac when running from bundle

- main/Directory.Build.props
FYI @sandyarmstrong
Updating Roslyn to [15b43b3](https://github.com/dotnet/roslyn/commit/15b43b33901c88f68ef43f8314b5a2457716780d)
Changes since [2768eee](https://www.github.com/dotnet/roslyn/commit/2768eee)
- [Merge pull request #36973 from jasonmalinowski/tactical-fix-for-experimentation-service-deadlock](https://www.github.com/dotnet/roslyn/pull/36973)
- [Merge pull request #36793 from dotnet/release/dev16.2](https://www.github.com/dotnet/roslyn/pull/36793)
- [Merge pull request #36731 from jasonmalinowski/show-nullability-in-quick-info](https://www.github.com/dotnet/roslyn/pull/36731)
- [Revert "use the source instead of the name to find nuget packa. (#36802)](https://www.github.com/dotnet/roslyn/pull/36802)
- [Merge pull request #36764 from …
> Bump Roslyn to 3.2.0-beta4-19359-03

- version-checks
Updated reference to xamarin/md-addins@58d3874
> Updated reference to xamarin/md-addins@58d3874

- main/po/ca.po
- main/po/cs.po
- main/po/da.po
- main/po/de.po
- main/po/es.po
- main/po/fr.po
- main/po/gl.po
- main/po/hu.po
- main/po/id.po
- main/po/it.po
- main/po/ja.po
- main/po/ko.po
- main/po/messages.po
- main/po/nb.po
- main/po/nl.po
- main/po/pl.po
- main/po/pt.po
- main/po/pt_BR.po
- main/po/ru.po
- main/po/sl.po
- main/po/sv.po
- main/po/tr.po
- main/po/uk.po
- main/po/zh_CN.po
- main/po/zh_TW.po
Backport of #8200.
/cc @rodrmoya
> [master] Update translations

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Commands/PublishToFolderBaseCommandHandler.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/945334
> [DotNetCore] Enable "Publish to folder" command for all .NET Core projects

- main/tests/Ide.Tests/MonoDevelop.Ide/BuildOutputTests.cs
Simplifies and removes the delay cancellation in SearchCanBeCanceled test
Fixes VSTS #941229 - MonoDevelop.Ide.BuildOutputTests.CustomProject_SearchCanBeCanceled very unreliable
> [BuildOutput] Simplifies and removes delay cancellation in SearchCanBeCanceled test

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/BreakpointManager.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/PinnedWatchStore.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.QuickTasks/QuickTaskOverviewMode.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs
Might fix https://devdiv.visualstudio.com/DevDiv/_workitems/edit/935168/
Backport of #8146.
/cc @sgmunn @jstedfast
> [release-8.2] [Debugger] Make sure to lock around BreakpointStore when using it

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/TypeSystemService_WorkspaceHandling.cs
Main difference between `TypeSystemService.GetCodeAnalysisProjectAsync` and `TypeSystemService.GetCodeAnalysisProject` should be that `Async` version can be called before project/solution is fully loaded and `await` for it to be loaded and then return correct result, `non-Async` version should return project if currently or else `null`.
> Make `TypeSystemService.GetCodeAnalysisProjectAsync` return actual value when solution is still loading

- main/src/addins/GnomePlatform/GnomePlatform.cs
> [Linux] Attempt to fix unquoted mono on PATH breaking running

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/FolderNodeBuilder.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/948392
> [Projects] Deal correctly with DependsOnFile pointing to a folder

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/Properties/MonoDevelop.TextEditor.addin.xml
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/TextViewContent.Commands.cs
And map ExpandSelection properly
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/949285
> Map ShrinkSelection for new editor

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.csproj
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreNotInstalledInfoBar.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdk.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/697714
> [dotnetcore] Turns DotNetCoreNotInstalledDialog into a InfoBar

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebugValueWindow.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ExceptionCaughtDialog.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/DebuggerObjectValueNode.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Gtk/GtkObjectValueTreeView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/IObjectValueTreeView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/ObjectValueNode.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/ObjectValueNodeEventArgs.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/ObjectValueTreeViewController.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/PinnedWatchWidget.cs
It's not quite entirely there yet, but I think this makes the controller a bit more testable. There are still some quirks that need to be sorted out, like how the view is interacting with the stack frame and debugger service. Also, I noted that the frame in the GtlObjectValueTreeView wasn't being set anywhere so we either had something broken or there is old code that we've refactored that just doesn't get called anymore.
> Refactor to have the view send events and have the controller do more 'controlling'

- version-checks
Updated reference to xamarin/md-addins@d663a25
> Updated reference to xamarin/md-addins@d663a25

- main/tests/Ide.Tests/MonoDevelop.Ide/BuildOutputTests.cs
Simplifies and removes the delay cancellation in SearchCanBeCanceled test
Fixes VSTS #941229 - MonoDevelop.Ide.BuildOutputTests.CustomProject_SearchCanBeCanceled very unreliable
Backport of #8119.
> [release-8.2] [BuildOutput] Simplifies and removes delay cancellation in SearchCanBeCanceled test

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/Counters.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebuggingService.cs
Needed for https://devdiv.visualstudio.com/DevDiv/_workitems/edit/802365/
> [Debugger] Log telemetry for async ops that stall out

- version-checks
Updated reference to xamarin/md-addins@1e144f3
> Updated reference to xamarin/md-addins@1e144f3

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/MonoDevelop.TextEditor.Cocoa.csproj
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/Properties/MonoDevelop.TextEditor.Cocoa.addin.xml
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/ThemeToClassification.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/918990
> Editor: Add TaskTagger so TODOs get highlighted

- version-checks
Updated reference to xamarin/md-addins@c990de1
> Updated reference to xamarin/md-addins@c990de1

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/FileTabCommands.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/WorkbenchMemento.cs
> Adds persistency in tabs pinned from older project sessions

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.PerfTests/Baseline_MonoDevelop.Debugger.PerfTests.xml
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.PerfTests/SteppingTests.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/605632/
> [Debugger] Added perftest for debugger startup

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ThreadsPad.cs
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/937030
> [Debugger] Add null check for session

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Templating/DotNetCoreProjectTemplateStringTagProvider.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateStringTagProviderTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreVersion.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/953251
> [DotNetCore] Add support for new templates location in 3.0 preview8

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/DockBarItem.cs
brief mouse over
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/948354
MouseMotion now cancels and restarts the auto show timer so mouse
movement can't query the auto show at all anymore.
> Fixes VSTS Bug 948354: Unpinned docked pads appear unexpectedly after a

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.AnalysisCore/Gui/ResultsEditorExtension.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/DefaultSourceEditorOptions.cs
Fix for #6333 in the old editor code.
> Fixes issue #6333 Analyzers not retriggered on editorconfig change

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.Tests/BreakpointsAndSteppingTests.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.Tests/MonoDevelop.Debugger.Tests.csproj
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/BreakpointManager.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/BreakpointPad.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebugCommands.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebuggingService.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.QuickTasks/QuickTaskOverviewMode.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/949284
This removes all the locks around the breakpoint store now that it is thread safe and bumps to pick up the changes.
> Thread safe BreakpointStore

- version-checks
Updated reference to xamarin/md-addins@559d23b
> Updated reference to xamarin/md-addins@559d23b

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/ThemeToClassification.cs
Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/962445
> TextEditor: Allow opening C# files with certain custom themes

- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/MonoDevelop.FSharp.Tests.fsproj
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/MonoDevelop.FSharp.fsproj
Backport of #8322.
/cc @slluis @nosami
> [release-8.2] Attempt to fix tests

- main/src/core/MonoDevelop.Ide/ExtensionModel/Commands.addin.xml
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/ProjectNodeBuilder.cs
Change "Delete" to "Remove" in project context menu to make it consistent with the files context menu.
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/943365
> [Project Model] Change "Delete" to "Remove" for project context menu

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Options/UI/GridOptionPreviewControl.cs
Add handler for changed severity, update names from notificationPreference to severity for better consistency.
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/952602
> [Project Model] Save severity in C# code analysis

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateTests.cs
- main/tests/IdeUnitTests/ProjectTemplateTest.cs
See if this fixes the project template tests.
Temporary change - should not be needed when the packages
are published on nuget.org.
> [DotNetCore] Add custom .NET Core sdk package sources

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/BreakpointPropertiesDialog.cs
Fixes VSTS 754280
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/754280
> [Debugger] let voice over read the print expression warning icon

- main/src/core/MonoDevelop.Ide/ExtensionModel/Commands.addin.xml
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/ProjectNodeBuilder.cs
Change "Delete" to "Remove" in project context menu to make it consistent with the files context menu.
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/943365
Backport of #8314.
/cc @sgmunn @ketttY
> [release-8.3] [Project Model] Change "Delete" to "Remove" for project context menu

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Options/UI/GridOptionPreviewControl.cs
Add handler for changed severity, update names from notificationPreference to severity for better consistency.
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/952602
Backport of #8337.
/cc @sgmunn @ketttY
> [release-8.3] [Project Model] Save severity in C# code analysis

- CODEOWNERS
Backport of https://github.com/mono/monodevelop/pull/8412
> [release-8.3] CODEOWNERS: @mono/monodevelop-roslyn

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.WelcomePage/WelcomePageService.cs
> [Ide] Run all WelcomePageService operations on main UI thread

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.WelcomePage/WelcomePageService.cs
Fixes VSTS #957299
Backport of #8338.
/cc @sevoku
> [release-8.3] [Ide] Run all WelcomePageService operations on main UI thread

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.WelcomePage/WelcomePageService.cs
Fixes VSTS #957299
Backport of #8338.
/cc @sevoku
> [release-8.2] [Ide] Run all WelcomePageService operations on main UI thread

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/Gui/MonoDevelop.VersionControl.Git.UserGitConfigDialog.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitCommitDialogExtension.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Dialogs/CommitDialog.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.csproj
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/CommitDialogExtension.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/MessageService.cs
attempting to commit to Git
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/961599
MessageService was causing a stack Overflow it could add a dialog as
child to itself. However teh git commit dialog should set itself as
parent for the git config dialog.
Backport of #8354.
/cc @mkrueger
> [release-8.2] Fixes VSTS Bug 961599: [Feedback] Visual Studio crashes/exists when

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git.Tests/BaseGitRepositoryTests.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Subversion.Tests/RepositoryTests.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Subversion/MonoDevelop.VersionControl.Subversion/SubversionRepository.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/StatusView.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/Repository.cs
- main/src/addins/VersionControl/Subversion.Win32.Tests/RepositoryTests.cs
Status view can block for a long time - that patch fixes that issue.
Fixes VSTS #966637
> [VersionControl] GenerateDiff is now async.

- NuGet.config
Old vside.myget.org feeds will be deprecated soon.
> Move to the new public feeds for vssdk and vs-impl.

- CODEOWNERS
Backport of https://github.com/mono/monodevelop/pull/8441
> [release-8.3] CODEOWNERS: Roslyn area cleanups

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/ComparisonWidget.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/967445
Got replaced with tasks.
> Fixes VSTS Bug 967445: Remove background worker in comparison widget.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextEditor.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/SearchResult.cs
MonoDevelop.Ide.Editor.TextEditor.get_FileName()
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/958254
> Fixes VSTS Bug 958254: System.NullReferenceException exception in

- main/src/addins/MonoDevelop.AspNetCore/Properties/MonoDevelop.AspNetCore.addin.xml
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateTests.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/944139
> [AspNetCore] Add Worker Service template

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git.Tests/BaseGitRepositoryTests.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Subversion.Tests/RepositoryTests.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Subversion/MonoDevelop.VersionControl.Subversion/SubversionRepository.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/StatusView.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/Repository.cs
- main/src/addins/VersionControl/Subversion.Win32.Tests/RepositoryTests.cs
Status view can block for a long time - that patch fixes that issue.
Fixes VSTS #966637
Backport of #8382.
> [release-8.3] [VersionControl] GenerateDiff is now async.

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/StatusView.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/IgnoreCommand.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/PublishCommand.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/RevertCommand.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/RevertRevisionsCommands.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/UnlockCommand.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/UpdateCommand.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlFileSystemExtension.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlItem.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlNodeExtension.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlService.cs
> [release-8.3] Fixes VSTS Bug 964392: TaskCanceledExceptions being logged when a file is deleted

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextEditor.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/SearchResult.cs
MonoDevelop.Ide.Editor.TextEditor.get_FileName()
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/958254
Backport of #8384.
/cc @mkrueger
> [release-8.3] Fixes VSTS Bug 958254: System.NullReferenceException exception in

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/ComparisonWidget.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/967445
Got replaced with tasks.
Backport of #8448.
/cc @mkrueger
> [release-8.3] Fixes VSTS Bug 967445: Remove background worker in comparison widget.

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/CommonEditorAssetService.cs
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/CommonEditorAssetServiceFactory.cs
- main/src/core/MonoDevelop.Ide/ExtensionModel/StockIcons.addin.xml
> [release-8.3] Move CommonEditorAssetService to MonoDevelop

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/CreatePatchCommand.cs
This is just a workaround to make the command work again. We need
to redesign the API for patch creation.
Fixes VSTS #964105
> [VersionControl] Fix CreatePatchCommand calling UI from background thread

- main/msbuild/ReferencesVSEditor.Windows.props
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/ViewCommandHandlers.cs
Backport of #8402.
/cc @sandyarmstrong @Therzok
> [release-8.3] [Windows] Some fixes to assembly references

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.OptionPanels/RuntimeOptionsPanel.cs
Associate "Target framework" label with the combo box, so voice over will read it.
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/753569/
> [Project System] let VO read "Target framework"

- main/src/addins/MonoDevelop.AspNetCore/Properties/MonoDevelop.AspNetCore.addin.xml
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateTests.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/944139
Backport of #8458.
/cc @rodrmoya
> [release-8.3] [AspNetCore] Add Worker Service template

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebuggingService.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/953602
> [8.2][Debugger] Protect against null document text buffers

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreRunConfiguration.cs
Backport of #8492.
/cc @jtorres
> [master] Prevents API breakage

- main/src/addins/PerformanceDiagnostics/PerformanceDiagnostics/Commands.cs
- main/src/addins/PerformanceDiagnostics/PerformanceDiagnostics/PerformanceDiagnosticsAddIn.csproj
- main/src/addins/PerformanceDiagnostics/PerformanceDiagnostics/Properties/ReliabilityDiagnostics.addin.xml
DEBUG builds only, useful for debugging Mono/MERP behavior
> Add commands to induce contrived fatal scenarios

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebuggingService.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/953602
> [8.3][Debugger] Protect against null document text buffers

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebuggingService.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/953602
> [Debugger] Protect against null document text buffers

- main/src/addins/MacPlatform/MainToolbar/MainToolbar.cs
Search popup window was disappearing in fullscreen on a second monitor
Fixes VSTS #969968
> [Mac] Send the correct frame

- main/src/addins/ChangeLogAddIn/CommitDialogExtensionWidget.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Dialogs/CommitDialog.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/StatusView.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/VersionControlDocumentInfo.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/CreatePatchCommand.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/FileUpdateEventHandler.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/PublishCommand.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/Repository.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/RevertRevisionsCommands.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlDocumentController.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlItem.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DocumentRegistry.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/968422
Fixed the exceptions from the log. However the real problem seems to be the sgen crash in mono.
> Fixes VSTS Bug 968422: [Feedback] VS for Mac freezes on git revert

- main/src/addins/ChangeLogAddIn/CommitDialogExtensionWidget.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Dialogs/CommitDialog.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/StatusView.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/VersionControlDocumentInfo.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/CreatePatchCommand.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/FileUpdateEventHandler.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/PublishCommand.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/Repository.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/RevertRevisionsCommands.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlDocumentController.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlItem.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DocumentRegistry.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/968422
Fixed the exceptions from the log. However the real problem seems to be the sgen crash in mono.
Backport of #8476.
> [release-8.3] Fixes VSTS Bug 968422: [Feedback] VS for Mac freezes on git revert

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/CreatePatchCommand.cs
This is just a workaround to make the command work again. We need
to redesign the API for patch creation.
Fixes VSTS #964105
Backport of #8377.
/cc @Therzok @sevoku
> [release-8.3] [VersionControl] Fix CreatePatchCommand calling UI from background thread

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectSupportedTargetFrameworks.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdk.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreVersion.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/968797
> [release-8.2] [DotNetCore] Check for unsupported newest SDK versions

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreSDKResolverTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdkPaths.cs
> Check that SDK root path exists before versions

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
> [IDE] Handle an empty list of bindings as well as null

- main/msbuild/RoslynVersion.props
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.Braces/BraceCompletionManager.cs
Backport of https://github.com/mono/monodevelop/pull/8475
> [release-8.3] Update roslyn version to 3.3.0-beta3-19415-01

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ExceptionCaughtDialog.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/968326/
> [Debugger] Fixed hang when showing the ExceptionCaughtDialog

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Services.cs
Added Telemetry Counter to detect slow update command operations
Issue VSTS #623224
Backport of #8176
> [release-8.3] Added Telemetry Counter to detect slow update command operations

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Services.cs
Added Telemetry Counter to detect slow update command operations
Issue VSTS #623224
> Added Telemetry Counter to detect slow update command operations

- main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.VsTest/VsTestTestClass.cs
- main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.VsTest/VsTestUnitTest.cs
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/973891/
> [Test Tools] let unit tests support "Show Test Source Code"

- main/msbuild/RoslynVersion.props
Changes since [3.3.0-beta3-19415-01](https://www.github.com/dotnet/roslyn/commit/f5ba9f2):
- [Merge pull request #38259 from dotnet/dev/riarenas/add-stages-properties](https://www.github.com/dotnet/roslyn/pull/38259)
- [Restore constraint checking for reduced extension methods. (#38109)](https://www.github.com/dotnet/roslyn/pull/38109)
- [Add nullability information to extract method (#37851)](https://www.github.com/dotnet/roslyn/pull/37851)
- [Merge pull request #38185 from JoeRobich/enable-bindsymbolinotherfile](https://www.github.com/dotnet/roslyn/pull/38185)
- [Merge pull request #38045 from mavasani/UnusedRefParamFixes](https://www.github.com/dotnet/roslyn/pull/38045)
- [Merge pull request #38038 from jasonmalinowski/remove-nullable-attributes-when-generating-code](https://www.github. …
> Bump Roslyn to 3.3.1-beta3-19426-02

- main/msbuild/RoslynVersion.props
Changes since [3.3.0-beta3-19415-01](https://www.github.com/dotnet/roslyn/commit/f5ba9f2):
- [Merge pull request #38259 from dotnet/dev/riarenas/add-stages-properties](https://www.github.com/dotnet/roslyn/pull/38259)
- [Restore constraint checking for reduced extension methods. (#38109)](https://www.github.com/dotnet/roslyn/pull/38109)
- [Add nullability information to extract method (#37851)](https://www.github.com/dotnet/roslyn/pull/37851)
- [Merge pull request #38185 from JoeRobich/enable-bindsymbolinotherfile](https://www.github.com/dotnet/roslyn/pull/38185)
- [Merge pull request #38045 from mavasani/UnusedRefParamFixes](https://www.github.com/dotnet/roslyn/pull/38045)
- [Merge pull request #38038 from jasonmalinowski/remove-nullable-attributes-when-generating-code](https://www.github. …
> [release-8.3] Bump Roslyn to 3.3.1-beta3-19426-02

- main/external/fsharpbinding/MonoDevelop.FSharp.Shared/Lexer.fs
- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/LexerTests.fs
- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/MonoDevelop.FSharp.Tests.fsproj
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpTokens.fs
Fixes VSTS #963356
Make Lexer.parseLine tail recursive and remove mutable state
> [F#] Fix parsing of long lines

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
Fixes VSTS #972230
Backport of #8541.
/cc @iainx
> [release-8.3] [IDE] Handle an empty list of bindings as well as null

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
This will probably not solve the crasher. We really need
to use a single threaded scheduler for all git operations.
Probably doesn't fix VSTS #975668
> [Git] Try to avoid libgit2 crashing on Dispose

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
This will probably not solve the crasher. We really need
to use a single threaded scheduler for all git operations.
Probably doesn't fix VSTS #975668
Backport of #8590.
/cc @sevoku
> [release-8.3] [Git] Try to avoid libgit2 crashing on Dispose

- main/src/core/MonoDevelop.Ide/ExtensionModel/StockIcons.addin.xml
On Windows:
On Mac:
md-reference image:
KnownImageId.Reference image:
Id:
> Icons: Map md-reference to KnownImageIds.Reference

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreCertificateManager.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/DotNetCoreDevCertsTool.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/965393
> [AspNetCore] Fix incorrect command line in certificate message

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
Fixes VSTS #972230
Backport of #8541.
/cc @iainx
> [release-8.2] [IDE] Handle an empty list of bindings as well as null

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.addin.xml
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.csproj
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/RoslynInformationProvider.cs
Fixes VSTS #910296 - Include version of Roslyn in about dialog
> [Ide] Add roslyn information to the about page

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreRunConfiguration.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/975464
> [AspNetCore] Instantiate CurrentProfile in all constructors

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreRunConfiguration.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/975464
Backport of #8612.
/cc @rodrmoya
> [release-8.3] [AspNetCore] Instantiate CurrentProfile in all constructors

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreCertificateManager.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/DotNetCoreDevCertsTool.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/965393
Backport of #8595.
/cc @rodrmoya
> [release-8.3] [AspNetCore] Fix incorrect command line in certificate message

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices/MonoDevelopDocumentTrackingService.cs
System.Linq.Enumerable.OfType[DocumentControllerExtension]()
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/958221
Split part of https://github.com/mono/monodevelop/pull/8340
> Fixes VSTS Bug 958221: System.ArgumentNullException exception in

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlDocumentController.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentView.cs
This reverts commit 77fc472178cb7a57c22ff189c818bc30d6e54104 introduced in #8476
Fixes VSTS #977977
> Revert "[VersionControl] Document controller now reacts on file status change."

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices/MonoDevelopDocumentTrackingService.cs
System.Linq.Enumerable.OfType[DocumentControllerExtension]()
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/958221
Split part of https://github.com/mono/monodevelop/pull/8340
Backport of #8641.
/cc @Therzok
> [release-8.3] Fixes VSTS Bug 958221: System.ArgumentNullException exception in

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/DarkStyle.json
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/HCDarkStyle.json
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/LightStyle.json
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/974480
Backport of #8656.
> [master] Fix bold theme and some other issues in CSS themes.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/DarkStyle.json
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/HCDarkStyle.json
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/LightStyle.json
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/974480
> Fix bold theme and some other issues in CSS themes.

- main/src/addins/PerformanceDiagnostics/PerformanceDiagnostics/Commands.cs
- main/src/addins/PerformanceDiagnostics/PerformanceDiagnostics/Properties/ReliabilityDiagnostics.addin.xml
Changed 'induce managed crash' to be a proper not-ui thread crasher
> Add debug command for ui thread crash

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git.Tests/BaseGitRepositoryTests.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitConfigurationDialog.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitService.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Subversion/MonoDevelop.VersionControl.Subversion/SubversionRepository.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/BlameView.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/BlameWidget.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/DiffView.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/Repository.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlFileSystemExtension.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionInfo.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionInfoCache.cs
We need to offset based on hunk inserted/removed lengths
Fixes VSTS 978853 - [VersionControl] GitRepository: Error retrieving history System.ArgumentException: Offset and length were out of bounds
Fixes VSTS #977874 - Renaming file makes intellisense disapear when project has .git
Fixes VSTS #787121 - [Watson] Git commands are run on the UI thread, causing the UI to hang
> [Git] Unbreak the addin

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreVersionTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSystemInformation.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreVersion.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/981132
> Parse revision number out of .NET Core SDK preview version

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.csproj
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreRuntimeSystemInformation.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSystemInformation.cs
- main/src/addins/MonoDevelop.DotNetCore/Properties/MonoDevelop.DotNetCore.addin.xml
Backport of #8625.
/cc @nosami @rodrmoya
> [release-8.3] [DotNetCore] Add .NET Core runtime "component"

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreExecutionHandler.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/983425
> Allow relative urls to start with "/"

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreExecutionHandler.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/983425
Backport of #8732.
/cc @nosami
> [release-8.3] Allow relative urls to start with "/"

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.FileNesting/FileNestingService.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/982815
> [FileNesting] Avoid computing file nesting tree for all projects

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.FileNesting/FileNestingService.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/982815
Backport of #8730.
/cc @rodrmoya
> [release-8.3] [FileNesting] Avoid computing file nesting tree for all projects

- main/msbuild/MonoDevelop.AfterCommon.props
> Minimum supported macOS is 10.12 now in the stub launcher makefiles

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/FolderNodeBuilder.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/ProjectFileNodeBuilder.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.FileNesting/FileNestingService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/982928
> [FileNesting] Move nested files when moving parent file

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/FolderNodeBuilder.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/ProjectFileNodeBuilder.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.FileNesting/FileNestingService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/982928
Backport of #8739.
> [release-8.3] [FileNesting] Move nested files when moving parent file

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Templating/DotNetCoreProjectTemplateWizard.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectSupportedTargetFrameworksTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateWizardTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectSupportedTargetFrameworks.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/983548
> Filter DotNetCore TargetFramework list selection to only include those with supported Sdks

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/FolderNodeBuilder.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/ProjectFileNodeBuilder.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.FileNesting/FileNestingService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/982928
Backport of #8739.
> [release-8.3-rtw] [FileNesting] Move nested files when moving parent file

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Templating/DotNetCoreProjectTemplateWizard.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectSupportedTargetFrameworksTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateWizardTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectSupportedTargetFrameworks.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/983548
Backport of #8740.
/cc @slluis @iantoalms
> [release-8.3] Filter DotNetCore TargetFramework list selection to only include those with supported Sdks

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Templating/DotNetCoreProjectTemplateWizard.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectSupportedTargetFrameworksTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateWizardTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectSupportedTargetFrameworks.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/983548
Backport of #8740.
/cc @slluis @iantoalms
> [release-8.3-rtw] Filter DotNetCore TargetFramework list selection to only include those with supported Sdks

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpSyntaxMode.fs
> Fix InvalidCastException by removing unneeded cast

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpSyntaxMode.fs
Fixes VSTS #984697
Backport of #8754.
/cc @nosami
> [release-8.3] Fix InvalidCastException by removing unneeded cast

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreRuntimeSystemInformation.cs
re: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/985133
> Force download of 2.1 runtime instead of 2.2

- version.config
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/982649
> Remove preview flag

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Debugger/RoslynDebugInfoProvider.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/BreakpointManager.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/BreakpointManagerService.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/ExceptionCaught/ExceptionCaughtAdornmentManager.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/Glyphs/BreakpointGlyphMouseProcessor.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/Glyphs/BreakpointGlyphTaggerProvider.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/Glyphs/CurrentStatementGlyphFactoryProvider.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/Glyphs/CurrentStatementGlyphTagger.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/Glyphs/CurrentStatementGlyphTaggerProvider.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/Glyphs/ReturnStatementGlyphFactoryProvider.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/Glyphs/ReturnStatementGlyphTagger.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/Glyphs/ReturnStatementGlyphTaggerProvider.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/QuickInfo/DebuggerQuickInfoSource.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/Tags/AbstractCurrentStatementTagger.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/Tags/BreakpointForegroundTaggerProvider.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/Tags/BreakpointTaggerProvider.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/Tags/CurrentStatementForegroundTagger.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/Tags/CurrentStatementForegroundTaggerProvider.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/Tags/CurrentStatementTagger.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/Tags/CurrentStatementTaggerProvider.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/Tags/ReturnStatementForegroundTaggerProvider.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/Tags/ReturnStatementTagger.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/Tags/ReturnStatementTaggerProvider.cs
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/ThemeToClassification.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/WindowCommands.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Navigation/TextFileNavigationPoint.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/984248
> Fix breakpoints inside .cshtml files.

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreRuntimeSystemInformation.cs
re: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/985133
Backport of #8778.
/cc @nosami
> [release-8.3] Force download of 2.1 runtime instead of 2.2

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/BreakpointPropertiesDialog.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/824300
> Debugger: Set position when using New Breakpoint with new editor

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Debugger/RoslynDebugInfoProvider.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/BreakpointManager.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/BreakpointManagerService.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/ExceptionCaught/ExceptionCaughtAdornmentManager.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/Glyphs/BreakpointGlyphMouseProcessor.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/Glyphs/BreakpointGlyphTaggerProvider.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/Glyphs/CurrentStatementGlyphFactoryProvider.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/Glyphs/CurrentStatementGlyphTagger.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/Glyphs/CurrentStatementGlyphTaggerProvider.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/Glyphs/ReturnStatementGlyphFactoryProvider.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/Glyphs/ReturnStatementGlyphTagger.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/Glyphs/ReturnStatementGlyphTaggerProvider.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/QuickInfo/DebuggerQuickInfoSource.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/Tags/AbstractCurrentStatementTagger.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/Tags/BreakpointForegroundTaggerProvider.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/Tags/BreakpointTaggerProvider.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/Tags/CurrentStatementForegroundTagger.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/Tags/CurrentStatementForegroundTaggerProvider.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/Tags/CurrentStatementTagger.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/Tags/CurrentStatementTaggerProvider.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/Tags/ReturnStatementForegroundTaggerProvider.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/Tags/ReturnStatementTagger.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/Tags/ReturnStatementTaggerProvider.cs
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/ThemeToClassification.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/WindowCommands.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Navigation/TextFileNavigationPoint.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/984248
Backport of #8771.
> [master] Fix breakpoints inside .cshtml files.

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/SearchPackagesSearchCategory.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/SearchInSolutionSearchCategory.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/SearchPopupWindow.cs
Backport to 8.3 only if we're going to update translations in service releases
> [Ide] Improve global search popup strings

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.csproj
- main/src/addins/MonoDevelop.AspNetCore/Properties/MonoDevelop.AspNetCore.addin.xml
- main/src/addins/MonoDevelop.AspNetCore/Templates/RazorComponent.razor
- main/src/addins/MonoDevelop.AspNetCore/Templates/RazorComponent.xft.xml
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Templating/DotNetCoreProjectTemplateWizard.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateWizardTests.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/943227
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/944132
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/980398
> Add support for Blazor server side projects

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Tests/MonoDevelop.AspNetCore.Tests/AspNetCoreProjectTests.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/FolderNodeBuilder.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/ProjectFileNodeBuilder.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.FileNesting/FileNestingService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/986845
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/988147
> [FileNesting] Include multiple nested files on move operations

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Tests/MonoDevelop.AspNetCore.Tests/AspNetCoreProjectTests.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/FolderNodeBuilder.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/ProjectFileNodeBuilder.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.FileNesting/FileNestingService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/986845
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/988147
Backport of #8798.
/cc @rodrmoya
> [release-8.3] [FileNesting] Include multiple nested files on move operations

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreVersionTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreVersion.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/987887
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/986987
> Don't throw exception for invalid dotnet core version

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/NSObjectResult.cs
Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/984191
> [AutoTest] Fix some cocoa queries being a bit too restrictive

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.FileNesting/NestingRule.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.FileNesting/NestingRulesProvider.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/950662
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/965804
> [FileNesting] Remove debugging output from Ide.log

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/BreakpointManager.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/988810/
> [Debugger] Catch ArgumentExceptions when creating a tracking span

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ImageService.cs
Requires https://github.com/mono/xwt/pull/977
Fixes VSTS #958241
Fixes VSTS #958248
Fixes VSTS #993725
> [Ide] Use Xwt.Drawing.ComposedImage for composed icons with cross-toolkit support

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/PathBar.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Tabstrip.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentViewContent.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/GtkShellDocumentViewContainer.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/GtkShellDocumentViewContainerTabs.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/GtkShellDocumentViewContent.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/GtkShellDocumentViewItem.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Gui.Documents/DocumentControllerTests.cs
See https://github.com/mono/monodevelop/pull/8477 for more context and a better diff.
> Address PR comments for new doc model post-merge

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Ide.cs
https://dev.azure.com/devdiv/DevDiv/_workitems/edit/825767
> [Ide] Add counter information for startup handler commands

- main/src/addins/MacPlatform/Dialogs/MacAddFileDialogHandler.cs
- main/src/addins/MacPlatform/Dialogs/MacOpenFileDialogHandler.cs
- main/src/addins/MacPlatform/Dialogs/MacSelectFileDialogHandler.cs
See for details: xamarin/xamarin-macios#6474
This reverts 508796b
Reopening VSTS #859111
Fixes VSTS #989519
> [Mac] Use static NSSavePanel.SavePanel to avoid crashes on Catalina

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectCellViewBase.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1000540
> [Debugger] Fixed an NRE font crash

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectValueView.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1000551/
Backport of #8894.
/cc @jstedfast
> [release-8.4] [Debugger] Use an actual spinner instead of a static image

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectValueView.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1000551/
> [Debugger] Use an actual spinner instead of a static image

- main/src/core/MonoDevelop.Ide/ExtensionModel/MimeTypes.addin.xml
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/999409
> Add more file extensions to msbuild mimetype

- main/src/addins/CSharpBinding/CSharpBinding.addin.xml
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MiscellaneousFilesWorkspace.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/999640
> MiscellaneousFilesWorkspace: support .csx scripts

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/EditorCommandHandlers.cs
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/Properties/MonoDevelop.TextEditor.addin.xml
Backport of #8882.
/cc @sandyarmstrong @DavidKarlas
> [release-8.4] Fix 824326: Shift+Enter not in new editor

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/PolicyOptionsPanel.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/752772
Duplicate of #8880
> [752772][PolicyOptions] fixed a11y of combobox

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.OptionPanels/BaseDirectoryPanelWidget.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.OptionPanels/GeneralProjectOptions.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/753511
Duplicate of #8873
> [753511] Fixed doubled VO strings

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/ViewCommands.cs
> [release-8.4] Fix 1002331: Support "Focus Document" commands in new editor

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectNameView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectValueView.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1000667/
> [Debugger] Fixed the text color used when editing Locals/Watches

- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/DesignerSupportService.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/MacPropertyGrid.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/NativePropertyEditor/ComponentModelEditorProvider.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/NativePropertyEditor/ComponentModelObjectEditor.cs
Backport of #8955.
/cc @Therzok
> [release-8.4] Fix leaktests

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/RefactoringPreviewTooltipWindow.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/CodePreviewWindow.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorPrintOperation.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/TextEditorOptions.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/OSXEditor.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Fonts/FontChooserPanelWidget.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Fonts/FontService.cs
Fixes VSTS #937839
Fixes VSTS #752348
Fixes VSTS #752341
Fixes VSTS #752307
Fixes VSTS #987295
> Fixes VSTS Bug 937839: [Feedback] Text Editor: font weight ignored

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/RefactoringPreviewTooltipWindow.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/CodePreviewWindow.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorPrintOperation.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/TextEditorOptions.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/OSXEditor.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Fonts/FontChooserPanelWidget.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Fonts/FontService.cs
Fixes VSTS #937839
Fixes VSTS #752348
Fixes VSTS #752341
Fixes VSTS #752307
Fixes VSTS #987295
Backport of #8106.
> [release-8.4] Fixes VSTS Bug 937839: [Feedback] Text Editor: font weight ignored

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.OptionPanels/BaseDirectoryPanelWidget.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.OptionPanels/GeneralProjectOptions.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/753511
Duplicate of #8873
Backport of #8930.
> [release-8.4] [753511] Fixed doubled VO strings

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/PolicyOptionsPanel.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/752772
Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/983388
Duplicate of #8880
Backport of #8929.
> [release-8.4] [752772][PolicyOptions] fixed a11y of combobox

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/Properties/MonoDevelop.TextEditor.addin.xml
Depends on an upcoming editor update to actually handle this command.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1001949
> Editor: Support for ShowQuickInfo command

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/RoslynSearchCategory.DeclaredSymbolInfoResult.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/SearchResult.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/754975
Things that are done in this PR:
* Added Description to AccessibilityMessage for SearchResult class
* Added Description to AccessibilityMessage in overrides for DeclaredSymbolInfoResult and FileSearchResult
> [754975] [Global Search Results] Added description to VoiceOver for search results

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Tabstrip.cs
was not providing any information related to whether the "Source",
"Changes" etc are selected or not.
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/810343
> Fixes VSTS Bug 810343: Accessibility: Document View Tabs: Voice Over

- main/src/addins/MonoDevelop.UnitTesting/Gui/TestResultsPad.cs
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/974577/
> [Unit Tests] let test results display properly in test result pad

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/PlatformService.cs
It's a change for https://github.com/xamarin/md-addins/pull/5698. 
- added `AccessibilityInUseChanged ` event
> [PlatformService] Added `AccessibilityInUseChanged`

- main/src/addins/MacPlatform/MacTelemetryDetails.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/IPlatformTelemetryDetails.cs
Addresses this work item: https://dev.azure.com/devdiv/DevDiv/_boards/board/t/VS%20for%20Mac%20-%20Technical%20Insights/Stories/?workitem=974964
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/974964
> Added machine hardware model to telemetry details

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectCellViewBase.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectNameView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectValueView.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/999602/
> [Debugger] Use the ~sel icon variants when the row is selected

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/RoslynSearchCategory.DeclaredSymbolInfoResult.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/SearchResult.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/754975
Things that are done in this PR:
* Added Description to AccessibilityMessage for SearchResult class
* Added Description to AccessibilityMessage in overrides for DeclaredSymbolInfoResult and FileSearchResult
Backport of #8947.
/cc @rodrmoya @Semptra
> [release-8.4] [754975] [Global Search Results] Added description to VoiceOver for search results

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.UI.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkTemplateCellRenderer.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/LanguageCellRenderer.cs
This fixes the remaining issue with language selection mentioned in #8991 and additionally category accessibility in the same dialog.
Fixes VSTS #751297
> [a11y] New project dialog incorrect language and category

- main/src/addins/MacPlatform/Dialogs/MacAlertDialogHandler.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/CheckoutCommand.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlTask.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.ProgressMonitoring/MessageDialogProgressMonitor.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/MessageService.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1002571
+ Added missing API for AskQuestion - only method which didn't take an optional parent window.
> Fixes VSTS Bug 1002571: Regression: VSC checkout message dialogs shown below progress dialog window.

- main/src/addins/MacPlatform/Dialogs/MacAlertDialogHandler.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/CheckoutCommand.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlTask.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.ProgressMonitoring/MessageDialogProgressMonitor.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/MessageService.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1002571
+ Added missing API for AskQuestion - only method which didn't take an optional parent window.
Backport of #8943.
> [release-8.4] Fixes VSTS Bug 1002571: Regression: VSC checkout message dialogs shown below progress dialog window.

- main/src/addins/MacPlatform/Dialogs/MacAlertDialogHandler.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/CheckoutCommand.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlTask.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.ProgressMonitoring/MessageDialogProgressMonitor.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/MessageService.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1002571
+ Added missing API for AskQuestion - only method which didn't take an optional parent window.
Backport of #8943.
> [release-8.3] Fixes VSTS Bug 1002571: Regression: VSC checkout message dialogs shown below progress dialog window.

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.csproj
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectCellViewBase.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectNameView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectTypeView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectValueView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerTextField.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeView.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1000666/
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/999611/
> [Debugger] Let Cocoa Do The Right Thing(tm)

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.csproj
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectCellViewBase.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectNameView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectTypeView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectValueView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerTextField.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeView.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1000666/
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/999611/
Backport of #8958.
/cc @jstedfast
> [release-8.4] [Debugger] Let Cocoa Do The Right Thing(tm)

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbarController.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/SearchPopupWindow.cs
System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/999353
Fixes VSTS Bug 999361: System.ArgumentOutOfRangeException exception in System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/999361
> Fixes VSTS Bug 999353: System.ArgumentOutOfRangeException exception in

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbarController.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/SearchPopupWindow.cs
System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/999353
Backport of #9034.
/cc @mkrueger
> [release-8.4] Fixes VSTS Bug 999353: System.ArgumentOutOfRangeException exception in

- main/src/addins/MonoDevelop.UnitTesting/Gui/TestResultsPad.cs
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/974577/
Backport of #8875.
/cc @mrward @ketttY
> [release-8.4] [Unit Tests] let test results display properly in test result pad

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeViewDataSource.cs
May fix https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1004450/
Backport of #9017.
/cc @jstedfast
> [release-8.4] [Debugger] Don't Dispose() items until *after* we call RemoveItems()

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreNotInstalledInfoBar.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreRuntime.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/982889
> [DotNetCore] Fix detection of required runtime for the project being run

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeViewDataSource.cs
May fix https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1004450/
> [Debugger] Don't Dispose() items until *after* we call RemoveItems()

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreNotInstalledInfoBar.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreRuntime.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/982889
Backport of #9047.
/cc @rodrmoya
> [release-8.4] [DotNetCore] Fix detection of required runtime for the project being run

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Tests/MonoDevelop.AspNetCore.Tests/AspNetCoreProjectTests.cs
- main/src/addins/MonoDevelop.AspNetCore/Resources/AspNetCore.filenesting.json
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/938197
> [AspNetCore] Update ASP.NET Core file nesting rules

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectValueView.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1004949/
> [Debugger] Node.Value can be null, if it is, use string.Empty

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeView.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1008045/
> [Debugger] ViewAtColumn can return null so protect against that

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/LaunchProfileProvider.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/965797
> [AspNetCore] Some launchSettings implementation code improvements

- main/src/addins/MonoDevelop.DotNetCore/Properties/MonoDevelop.DotNetCore.addin.xml
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1008309
> Only show Pack command on project node

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/LaunchProfileProvider.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/965797
Backport of #9092.
/cc @rodrmoya
> [release-8.4] [AspNetCore] Some launchSettings implementation code improvements

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Dialogs/SelectRepositoryDialog.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/UrlBasedRepositoryEditor.cs
was not reading the labels of the form controls(text boxes, drop-down)
in the dialog
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/807760
Backport of #9024.
/cc @mkrueger
> [release-8.4] Fixes VSTS Bug 807760: Accessibility: Checkout Repository: Voice Over

- main/src/addins/MonoDevelop.DotNetCore/Properties/MonoDevelop.DotNetCore.addin.xml
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1008309
Backport of #9103.
/cc @nosami
> [release-8.4] Only show Pack command on project node

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Gui/DotNetCoreRuntimeOptionsPanelWidget.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectSupportedTargetFrameworks.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/973338
> [DotNetCore] Allow selecting frameworks even if not installed

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Gui/DotNetCoreRuntimeOptionsPanelWidget.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectSupportedTargetFrameworks.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/973338
Backport of #9102.
/cc @rodrmoya
> [release-8.4] [DotNetCore] Allow selecting frameworks even if not installed

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Tabstrip.cs
was not providing any information related to whether the "Source",
"Changes" etc are selected or not.
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/810343
Backport of #8852.
> [release-8.4] Fixes VSTS Bug 810343: Accessibility: Document View Tabs: Voice Over

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Navigation/TextFileNavigationPoint.cs
While I was editing .cshtml this code threw exception often, so I fixed it the way I think it should be to never throw exception
> Fix exception caught while debugging

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/PinnedWatches/PinnedWatchAdornmentManager.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/999608
> [Debugger] Prevent pinned watches from disappearing during scroll/etc

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/PinnedWatches/PinnedWatchAdornmentManager.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/999608
Backport of #9126.
> [release-8.4] [Debugger] Prevent pinned watches from disappearing during scroll/etc

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Updater/AddinsUpdateHandler.cs
This PR fixes alignment of Extension window when we are in GTC mode and it's the parent window.
It also fixes all the error messages reported setting correctly the parent and centering.
it can be tested opening Extension and refreshing repository in "offline" mode. (some popups will open)
Fixes VSTS #935546 - [Shell] Extensions screen is not well aligned to parent
Fixes VSTS #872599 - [Feedback] Extension manager cannot be closed if remote is unreachable
Fixes VSTS #857544 - Cancel extension installation confirmation dialog position is offsetThis PR requires https://github.com/mono/mono-addins/pull/147
> Fixes current alignment centering Extension and children to parent

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Updater/AddinsUpdateHandler.cs
This PR fixes alignment of Extension window when we are in GTC mode and it's the parent window.
It also fixes all the error messages reported setting correctly the parent and centering.
it can be tested opening Extension and refreshing repository in "offline" mode. (some popups will open)
Fixes VSTS #935546 - [Shell] Extensions screen is not well aligned to parent
Fixes VSTS #872599 - [Feedback] Extension manager cannot be closed if remote is unreachable
This PR requires https://github.com/mono/mono-addins/pull/147
Backport of #8782.
> [release-8.4] Fixes current alignment centering Extension and children to parent

- main/msbuild/ReferencesVSEditor.Mac.props
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/MonoDevelop.TextEditor.Cocoa.csproj
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/Properties/MonoDevelop.TextEditor.Cocoa.addin.xml
Backport of #9130.
/cc @sandyarmstrong @DavidKarlas
> [release-8.4] Include IndentationManagerImpl into VSMac

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Navigation/TextFileNavigationPoint.cs
While I was editing .cshtml this code threw exception often, so I fixed it the way I think it should be to never throw exception
Backport of #9139.
> [release-8.4] Fix exception caught while debugging

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/BlameWidget.AuthorSectionAccessible.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/BlameWidget.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.csproj
Authors section in the extreme right is not read by voice over
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/810301
Backport of #8859.
> [release-8.4] Fixes VSTS Bug 810301: Accessibility: Version Control - Author:

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/BlameWidget.AuthorSectionAccessible.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/BlameWidget.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.csproj
Authors section in the extreme right is not read by voice over
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/810301
> Fixes VSTS Bug 810301: Accessibility: Version Control - Author:

- main/tests/test-projects/restore-netcore-offline/dotnetcoreconsole.csproj
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/991558
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/991564
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1002439
Backport of #9117.
/cc @rodrmoya
> [release-8.4] Bump to .NET Core 3.1

- main/src/addins/MonoDevelop.ConnectedServices/Gui.ServicesTab/ConfigurationSectionWidget.cs
- main/src/addins/MonoDevelop.ConnectedServices/Gui.ServicesTab/DependenciesSectionWidget.cs
- main/src/addins/MonoDevelop.ConnectedServices/Gui.ServicesTab/ServiceDetailsWidget.cs
- main/src/addins/MonoDevelop.ConnectedServices/Gui.ServicesTab/ServiceWidget.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/ExtendedHeaderBox.cs
This is not perfect but makes the connected services accessible. We can improve the usability in the next cycle.
Fixes VSTS #753572
> [ConnectedServices] Add accessibility support to the connected services view

- main/src/addins/MonoDevelop.ConnectedServices/Gui.ServicesTab/ConfigurationSectionWidget.cs
- main/src/addins/MonoDevelop.ConnectedServices/Gui.ServicesTab/DependenciesSectionWidget.cs
- main/src/addins/MonoDevelop.ConnectedServices/Gui.ServicesTab/ServiceDetailsWidget.cs
- main/src/addins/MonoDevelop.ConnectedServices/Gui.ServicesTab/ServiceWidget.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/ExtendedHeaderBox.cs
This is not perfect but makes the connected services accessible. We can improve the usability in the next cycle.
Fixes VSTS #753572
Backport of #9167.
/cc @sevoku
> [release-8.4] [ConnectedServices] Add accessibility support to the connected services view

- main/tests/test-projects/restore-netcore-offline/dotnetcoreconsole.csproj
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/991558
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/991564
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1002439
> Bump to .NET Core 3.1

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/GlobalToolTests.cs
To be merged after scaffolding has been merged
> Release 8.4 scaffolding disable test

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/OptionsDialog.cs
extension errors
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1000977
> Fixes VSTS Bug 1000977: Make preference dialog more resilient to

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Fonts/FontChooserPanelWidget.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Core.Tests.csproj
> [Windows] Fix build due to Xamarin.Mac reference

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/ScaffolderWizard.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/Scaffolders/ApiControllerEntityFrameworkScaffolder.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/Scaffolders/ControllerScaffolder.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/Scaffolders/ScaffolderBase.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Tests/MonoDevelop.AspNetCore.Tests.csproj
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Tests/MonoDevelop.AspNetCore.Tests/ScaffoldingTests.cs
Fixes VSTS https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1010619
> Add scaffolder tests + fix couple of bugs

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/ScaffolderWizard.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/Scaffolders/ApiControllerEntityFrameworkScaffolder.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/Scaffolders/ControllerScaffolder.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/Scaffolders/ScaffolderBase.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Tests/MonoDevelop.AspNetCore.Tests.csproj
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Tests/MonoDevelop.AspNetCore.Tests/ScaffoldingTests.cs
Fixes VSTS https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1010619
Backport of #9189.
/cc @nosami
> [release-8.4] Add scaffolder tests + fix couple of bugs

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/ModelVisitor.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/Scaffolders/ScaffolderBase.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.csproj
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1011422
Backport of #9203.
/cc @nosami
> [release-8.4] Fix 1011422

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/ModelVisitor.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/Scaffolders/ScaffolderBase.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.csproj
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1011422
> Fix 1011422

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/ScaffolderDialogController.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/ScaffolderTemplateConfigurePage.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1012524
Backport of #9201.
/cc @nosami
> [release-8.4] Set field value for ComboBoxEntry.TextEntry.Changed

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/ScaffolderDialogController.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/ScaffolderTemplateConfigurePage.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1012524
> Set field value for ComboBoxEntry.TextEntry.Changed

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectValueView.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1011400/
> [Debugger] Make sure Node isn't null in OnValueButtonActivated()

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectValueView.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1011400/
Backport of #9225.
/cc @jstedfast
> [release-8.4] [Debugger] Make sure Node isn't null in OnValueButtonActivated()

- main/src/addins/PerformanceDiagnostics/PerformanceDiagnostics/GlobalOptionsDialog.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/753558/
> [753558]Fix VO for output dir folder entry

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Dialogs/PublishToFolderDialog.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/984736
> [984736] Fix VO of text entry for folder selected

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Dialogs/PublishToFolderDialog.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/984736
Backport of #9181.
/cc @sevoku @GouriKumari
> [release-8.4] [984736] Fix VO of text entry for folder selected

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/QuickInfo/DebuggerQuickInfoSource.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1002160/
(I hope)
> [Debugger] Explicitly check cocoaView.VisualElement.Windows != null

- main/src/addins/MacPlatform/Dialogs/MacOpenFileDialogHandler.cs
> Always assign a CancellationTokenSource

- main/src/addins/MacPlatform/Dialogs/MacOpenFileDialogHandler.cs
Fixes VSTS #1016694
Backport of #9231.
/cc @Therzok
> [release-8.4] Always assign a CancellationTokenSource

- main/src/addins/MacPlatform/Dialogs/MacOpenFileDialogHandler.cs
Fixes VSTS #1016694
Backport of #9231.
/cc @Therzok
> [release-8.3] Always assign a CancellationTokenSource

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Commands/ScaffoldCommandHandler.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/Fields/ComboField.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/ModelVisitor.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/ScaffolderArgs.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/ScaffolderDialogController.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/ScaffolderTemplateConfigurePage.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/ScaffolderTemplateSelectPage.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/ScaffolderWizard.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/ScaffolderWizardPageBase.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/Scaffolders/ApiControllerEntityFrameworkScaffolder.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/Scaffolders/RazorPageEntityFrameworkCrudScaffolder.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/Scaffolders/RazorPageEntityFrameworkScaffolder.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/Scaffolders/ScaffolderBase.cs
Improve filtering for Model and DbContext class discovery && Make type discovery async
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1013322
Backport of #9208.
/cc @nosami
> [release-8.4] Fix 1013322

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/SearchResult.cs
MonoDevelop.Ide.FindInFiles.SearchResult.GetDocument()
GetDocument was not inside try…catch so an exception there could crash
the whole IDE. (async void should be avoided)
Why it crashes is hard to tell. There is a search & replace PR open that stabilizes that layer a bit.
> Fixes VSTS Bug 1002619: System.NullReferenceException exception in

- main/src/addins/PerformanceDiagnostics/PerformanceDiagnostics/GlobalOptionsDialog.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/753558/
Backport of #9177.
/cc @GouriKumari
> [release-8.4] [753558]Fix VO for output dir folder entry

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectValueView.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1004949/
(I hope)
> [Debugger] Make sure colorPreview has a non-null Layer property

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectValueView.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1004949/
(I hope)
Backport of #9223.
/cc @jstedfast
> [release-8.4] [Debugger] Make sure colorPreview has a non-null Layer property

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Commands/ScaffoldCommandHandler.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/Fields/ComboField.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/ModelVisitor.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/ScaffolderArgs.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/ScaffolderDialogController.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/ScaffolderTemplateConfigurePage.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/ScaffolderTemplateSelectPage.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/ScaffolderWizard.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/ScaffolderWizardPageBase.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/Scaffolders/ApiControllerEntityFrameworkScaffolder.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/Scaffolders/RazorPageEntityFrameworkCrudScaffolder.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/Scaffolders/RazorPageEntityFrameworkScaffolder.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/Scaffolders/ScaffolderBase.cs
Improve filtering for Model and DbContext class discovery && Make type discovery async
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1013322
> Fix 1013322

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/Repository.cs
MonoDevelop.VersionControl.Git.GitRepository.EnsureInitialized()
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1002614
Some operations need to be canceled on Dispose.
> Fixes VSTS Bug 1002614: System.ObjectDisposedException exception in

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Dialogs/CommitDialog.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/CommitCommand.cs
remains
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1003485
The commit dialog always reponses with ok when commit is clicked.
ButtonCommitClicked handles that dialog but doesn't change the
response.
So the best solution is to let the commit dialog handle the commit
logic itself.
> Fixes VSTS Bug 1003485: [Feedback] After Commit and Push changes

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
Fixes issue where Start Window couldn't open projects.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1017605
> CommandManager: Add missing null check

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
Fixes issue where Start Window couldn't open projects.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1017605
Backport of #9247.
> [release-8.4] CommandManager: Add missing null check

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/NSObjectResult.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestClientSession.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestToolbar.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbarController.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
The Current PR contains results of 4 tasks from 
[User Story 807892:](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/807892) [VSM] Enhance AutoTest to control Toolbar
These methods are required to remove applescript GetExecutionInfo.scpt from md-addins autotests
> Pr olga add autotest api for get execution info

- main/src/addins/MacPlatform/MainToolbar/AwesomeBar.cs
- main/src/addins/MacPlatform/MainToolbar/ButtonBar.cs
- main/src/addins/MacPlatform/MainToolbar/ButtonBarContainer.cs
- main/src/addins/MacPlatform/MainToolbar/MainToolbar.cs
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/753497
> Keyboard focus  not going to "Pause Execution" button 

- main/src/addins/MacPlatform/MainToolbar/AwesomeBar.cs
- main/src/addins/MacPlatform/MainToolbar/ButtonBar.cs
- main/src/addins/MacPlatform/MainToolbar/ButtonBarContainer.cs
- main/src/addins/MacPlatform/MainToolbar/MainToolbar.cs
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/753497
Backport of #9150.
/cc @sevoku @GouriKumari
> [release-8.4] Keyboard focus  not going to "Pause Execution" button 

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Project/CSharpCompilerParameters.cs
- Fixes AB#1018498
- Context: http://sourceroslyn.io/#Microsoft.CodeAnalysis.CSharp/CommandLine/CSharpCommandLineParser.cs,f777bd5ac8b781b5,references
- Context: https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties?view=vs-2019
The previous strategy used a project model extension mechanism which was not accurate in a couple of scenarios like plain .NET/.NET standard library project where it would erroneously results in `OutputKind.ConsoleApplication` being used.
This new logic instead leverages MSBuild directly in the same fashion than other implementations of Roslyn's workspaces do to get the most accurate information.
> [CSharpBinding] Rely on MSBuild's OutputType for determining Roslyn's OutputKind

- main/src/addins/MonoDevelop.AspNetCore/Templates/RazorComponent.xft.xml
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1012759
> [AspNetCore] Don't hard code BuildAction for Razor Component template

- main/src/addins/MonoDevelop.AspNetCore/Templates/RazorComponent.xft.xml
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1012759
Backport of #9264.
/cc @rodrmoya
> [release-8.4] [AspNetCore] Don't hard code BuildAction for Razor Component template

- main/po/ca.po
- main/po/cs.po
- main/po/da.po
- main/po/de.po
- main/po/es.po
- main/po/fr.po
- main/po/gl.po
- main/po/hu.po
- main/po/id.po
- main/po/it.po
- main/po/ja.po
- main/po/ko.po
- main/po/messages.po
- main/po/nb.po
- main/po/nl.po
- main/po/pl.po
- main/po/pt.po
- main/po/pt_BR.po
- main/po/ru.po
- main/po/sl.po
- main/po/sv.po
- main/po/tr.po
- main/po/uk.po
- main/po/zh_CN.po
- main/po/zh_TW.po
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1003503
> [release-8.4] Update translations

- main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/MonoDevelopContainedDocument.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices/MonoDevelopDocumentNavigationService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/IMonoDevelopHostDocument.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1010683
> Go to Definition for razor projection buffers

- main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/MonoDevelopContainedDocument.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices/MonoDevelopDocumentNavigationService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/IMonoDevelopHostDocument.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1010683
Backport of #9275.
> [release-8.4] Go to Definition for razor projection buffers

- main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/MonoDevelopContainedDocument.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices/MonoDevelopDocumentNavigationService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/IMonoDevelopHostDocument.cs
This reverts commit d0ec47952e2d2beadf1176e4be69cea35720a2c7.
It broke some normal usage of Go To Definition for C# files.
> Revert "Implement Go To Definition for Razor"

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/QuickInfo/DebuggerQuickInfoSource.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1020677
> [Debugger] Fix tooltips in razor and other projection buffers

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/QuickInfo/DebuggerQuickInfoSource.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1020677
Backport of #9291.
> [release-8.4] [Debugger] Fix tooltips in razor and other projection buffers

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.OptionPanels/KeyBindingsPanel.cs
When/after recording a new key binding, there is now way
to finish the assignment for keyboard only users, because
a tab key combination will be always recorded and not executed.
This changes the behaviour and allows Gtk to handle the
focus event:
* Don't accept tab as chord and let Gtk move the focus
* For accels allow tab to be entered,
but don't reset on a second tab and let Gtk handle it again
* If the accel is complete, move focus without resetting the entry,
allowing the user to finish entering a binding
Fixes VSTS #751986
> [Ide] Allow to unfocus the Keybinding entry with keyboard

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.OptionPanels/KeyBindingsPanel.cs
When/after recording a new key binding, there is now way
to finish the assignment for keyboard only users, because
a tab key combination will be always recorded and not executed.
This changes the behaviour and allows Gtk to handle the
focus event:
* Don't accept tab as chord and let Gtk move the focus
* For accels allow tab to be entered,
but don't reset on a second tab and let Gtk handle it again
* If the accel is complete, move focus without resetting the entry,
allowing the user to finish entering a binding
Fixes VSTS #751986
Backport of #9272.
/cc @sevoku
> [release-8.4] [Ide] Allow to unfocus the Keybinding entry with keyboard

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/Configuration/PackageDescription.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/Configuration/ScaffoldingConfig.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/Configuration/ScaffoldingPackageVersions.json
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/Configuration/SupportPolicyVersion.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/ScaffolderWizard.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Tests/MonoDevelop.AspNetCore.Tests/ScaffoldingTests.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.csproj
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1015867
Backport of #9215.
/cc @nosami
> [release-8.4] Allow scaffolders to choose packages/versions by TFM

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/PinnedWatches/PinnedWatchAdornmentManager.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/PinnedWatches/PinnedWatchView.cs
Fixes VSTS 1020647
Backport of #9293.
/cc @sgmunn
> [release-8.4] [Debugger] Update pinned watches when variables change

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/PinnedWatches/PinnedWatchAdornmentManager.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/PinnedWatches/PinnedWatchView.cs
> [Debugger] Update pinned watches when variables change

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Commands/PublishToFolderBaseCommandHandler.cs
Fixes:  https://devdiv.visualstudio.com/DevDiv/_queries/edit/1011069
Testing:
Create .Net Core Projects - including Http Trigger Function - and verify folder publishing
> Re-enable Folder Publishing Support for .Net Core Console and Library projects

- main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/MonoDevelopContainedDocument.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices/MonoDevelopDocumentNavigationService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/IMonoDevelopHostDocument.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1010683
> Implement Go To Definition for Razor

- main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/MonoDevelopContainedDocument.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices/MonoDevelopDocumentNavigationService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/IMonoDevelopHostDocument.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1010683
Backport of #9307.
> [release-8.4] Implement Go To Definition for Razor

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/Configuration/ScaffoldingConfig.cs
Backport of #9333.
/cc @nosami
> [release-8.4] Change case on package feed URL. Fixes VSTS #1022827

- main/src/core/MonoDevelop.Ide/ExtensionModel/Commands.addin.xml
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/ProjectCommands.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/ProjectFileNodeBuilder.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/ProjectFolderNodeBuilder.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/ProjectPadContextMenu.addin.xml
Changed the delete dialog for project files and folders. Add new context menu item `Exclude from project`
Fixes: 
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/983801/
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1018357?src=WorkItemMention&src-action=artifact_link
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1018379?src=WorkItemMention&src-action=artifact_link
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1018383?src=WorkItemMention&src-action=artifact_link
> [IDE] Change the delete dialog

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/PinnedWatches/PinnedWatchAdornmentManager.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1023242
> Debugger: Fix pinned watches in .razor/.cshtml files

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/PinnedWatches/PinnedWatchAdornmentManager.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1023242
Backport of #9343.
> [release-8.4] Debugger: Fix pinned watches in .razor/.cshtml files

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/QuickInfo/DebuggerQuickInfoSource.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1020556
Backport of #9359.
/cc @jstedfast
> [release-8.4] [Debugger] Don't evaluate null expressions in the tooltip logic

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/QuickInfo/DebuggerQuickInfoSource.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1020556
> [Debugger] Don't evaluate null expressions in the tooltip logic

- main/build/MacOSX/Info.plist.in
- main/build/MacOSX/Makefile.am
- main/msbuild/MonoDevelop.AfterCommon.props
Context: https://github.com/xamarinhq/swupdate/pull/54
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1023431
> Minimum supported OS should be 10.13

- main/build/MacOSX/Info.plist.in
- main/build/MacOSX/Makefile.am
- main/msbuild/MonoDevelop.AfterCommon.props
Context: https://github.com/xamarinhq/swupdate/pull/54
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1023431
Backport of #9345.
/cc @Therzok
> [release-8.4] Minimum supported OS should be 10.13

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/ObjectValueTreeViewController.cs
Fixes VSTS 1025766
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1025766
> [Debugger] Handle NRE when adding a watch when not debugging

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/ObjectValueTreeViewController.cs
Fixes VSTS 1025766
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1025766
Backport of #9373.
/cc @sgmunn
> [release-8.4] [Debugger] Handle NRE when adding a watch when not debugging

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Commands/ScaffoldCommandHandler.cs
Changed from Folder + File
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1027657
> Scaffolding is enabled for Project + Folder

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Commands/ScaffoldCommandHandler.cs
Changed from Folder + File
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1027657
Backport of #9381.
/cc @nosami
> [release-8.4] Scaffolding is enabled for Project + Folder

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Gui/ManagePackagesDialog.UI.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Gui/ManagePackagesDialog.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AtkCocoaHelper/AtkCocoaHelper.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AtkCocoaHelper/AtkCocoaHelperMac.cs
Fixes VSTS #1021556
Fixes VSTS #1021693
> [NuGet][1021556] Make tab labels behave like real tabs with VO

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Gui/ManagePackagesDialog.UI.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Gui/ManagePackagesDialog.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AtkCocoaHelper/AtkCocoaHelper.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AtkCocoaHelper/AtkCocoaHelperMac.cs
Fixes VSTS #1021556
Fixes VSTS #1021693
Backport of #9387.
/cc @sevoku
> [release-8.4] [NuGet][1021556] Make tab labels behave like real tabs with VO

- main/src/addins/MacPlatform/MainToolbar/StatusBar.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1019006
> [753577][StatusBar] announce changed status

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/CocoaTextViewContent.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1010385
> CocoaTextViewContent: Add AccessibilityTitle for editor group

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/DynamicFileManager.cs
Make sure dynamic files are added to the project info every time the project is reloaded.
Also double-check that the document we're about to reload still exists in the current solution.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1012526
> Fixes squiggles in Razor/Blazor files after project reload

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/DynamicFileManager.cs
Make sure dynamic files are added to the project info every time the project is reloaded.
Also double-check that the document we're about to reload still exists in the current solution.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1012526
Backport of #9376.
> [release-8.4] Fixes squiggles in Razor/Blazor files after project reload

- main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.VsTest/DiscoveredTests.cs
- main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.VsTest/VsTestNamespaceTestGroup.cs
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/901156/
> [Unit Test] Fix the nesting for unit tests

- main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.Tests/MonoDevelop.UnitTesting.Tests/VsTestUnitTestTests.cs
Test for https://devdiv.visualstudio.com/DevDiv/_workitems/edit/901156/
> Add test case for unit test nesting

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/ScaffolderTemplateConfigurePage.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1036179
> Remove blank entry from Scaffolder Model dropdown

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/ScaffolderTemplateConfigurePage.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1036179
Backport of #9468.
/cc @nosami
> [release-8.4] Remove blank entry from Scaffolder Model dropdown

- main/src/addins/MacPlatform/MainToolbar/StatusBar.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1019006
Backport of #9401.
> [release-8.4-a11y] [753577][StatusBar] announce changed status

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/ScaffolderTemplateConfigurePage.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1020849
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1036179
Backport of #9475.
/cc @nosami
> [release-8.4] Don't select Scaffolder dropdown lists to first item

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/ScaffolderTemplateConfigurePage.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1020849
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1036179
> Don't select Scaffolder dropdown lists to first item

- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/addins/MacPlatform/MainToolbar/StatusBar.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/PlatformService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/NewProjectController.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/DesktopService.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/947006
- moved `MakeAccessibilityAnnouncement` to `PlatformService.cs`
- deleted project creation events from `GtkNewProjectDialogBackend.cs`
- added one more announcement after creation process has started  
Backport of #9416.
> [release-8.4-a11y] [947006][NewProjectController] added announcement of project creation status

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Gui/ManagePackagesDialog.cs
> [NuGet] Native project selection dialog

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Gui/ManagePackagesDialog.cs
Fixes VSTS #1021688
Backport of #9483.
/cc @sevoku
> [release-8.4-a11y] [NuGet] Native project selection dialog

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreProjectExtension.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1024557
> [AspNetCore] Enable support for launchSettings.json in Worker services

- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/addins/MacPlatform/MainToolbar/StatusBar.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/PlatformService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/NewProjectController.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/DesktopService.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/947006
- moved `MakeAccessibilityAnnouncement` to `PlatformService.cs`
- deleted project creation events from `GtkNewProjectDialogBackend.cs`
- added one more announcement after creation process has started
> [947006][NewProjectController] added announcement of project creation status

- version.config
> Remove preview branding

- main/src/addins/MonoDevelop.AspNetCore/Properties/MonoDevelop.AspNetCore.addin.xml
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1036884
> [AspNetCore] Move Worker template to general section

- main/src/addins/MonoDevelop.Debugger.VSCodeDebugProtocol/MonoDevelop.Debugger.VsCodeDebugProtocol/MonoDevelop.Debugger.VsCodeDebugProtocol.csproj
- main/src/addins/MonoDevelop.Debugger.VSCodeDebugProtocol/MonoDevelop.Debugger.VsCodeDebugProtocol/VSCodeDebuggerSession.cs
- main/src/addins/MonoDevelop.Debugger.VSCodeDebugProtocol/MonoDevelop.Debugger.VsCodeDebugProtocol/VSCodeEvaluationSource.cs
- main/src/addins/MonoDevelop.Debugger.VSCodeDebugProtocol/MonoDevelop.Debugger.VsCodeDebugProtocol/VSCodeVariableSource.cs
- main/src/addins/MonoDevelop.Debugger.VSCodeDebugProtocol/MonoDevelop.Debugger.VsCodeDebugProtocol/VsCodeBacktrace.cs
- main/src/addins/MonoDevelop.Debugger.VSCodeDebugProtocol/MonoDevelop.Debugger.VsCodeDebugProtocol/VsCodeObjectSource.cs
Needed for https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1042237/
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1023874/
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1032065/
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1042217/
> [VsCodeDebugger] Log errors for GetAllLocals

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Templating/DotNetCoreProjectTemplateWizard.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests.csproj
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateWizardTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/TargetFrameworkTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdk.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/TargetFrameworkMonikerExtensions.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1008333
> [DotNetCore] Ignore unsupported SDKs in template wizard

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/EditorCompareWidgetBase.MiddleArea.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1042154
> Fixes VSTS Bug 1042154: Wrong accessibility translations

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/EditorCompareWidgetBase.MiddleArea.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1042154
Backport of #9509.
> [release-8.4-a11y] Fixes VSTS Bug 1042154: Wrong accessibility translations

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/ComparisonWidget.cs
> [VCS] Add a11y titles to Diff view

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/ComparisonWidget.cs
Fixes VSTS #810330
Backport of #9528.
/cc @sevoku
> [release-8.4-a11y] [VCS] Add a11y titles to Diff view

- main/src/addins/MonoDevelop.AspNetCore/Properties/MonoDevelop.AspNetCore.addin.xml
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1036884
Backport of #9495.
/cc @rodrmoya
> [release-8.4] [AspNetCore] Move Worker template to general section

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Templating/DotNetCoreProjectTemplateWizard.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests.csproj
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateWizardTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/TargetFrameworkTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdk.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/TargetFrameworkMonikerExtensions.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1008333
Backport of #9400.
/cc @rodrmoya
> [release-8.4] [DotNetCore] Ignore unsupported SDKs in template wizard

- main/build/MacOSX/monostub.mm
- main/src/addins/MacPlatform/MacPlatform.cs
- main/tests/MacPlatform.Tests/MacPlatformTest.cs
This should prevent hard crashing when working with exception handling in xammac
Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1042626
> [Mac] Set Marshal*Exception modes

- main/src/addins/MonoDevelop.Debugger.VSCodeDebugProtocol/MonoDevelop.Debugger.VsCodeDebugProtocol/MonoDevelop.Debugger.VsCodeDebugProtocol.csproj
- main/src/addins/MonoDevelop.Debugger.VSCodeDebugProtocol/MonoDevelop.Debugger.VsCodeDebugProtocol/VSCodeDebuggerSession.cs
- main/src/addins/MonoDevelop.Debugger.VSCodeDebugProtocol/MonoDevelop.Debugger.VsCodeDebugProtocol/VSCodeEvaluationSource.cs
- main/src/addins/MonoDevelop.Debugger.VSCodeDebugProtocol/MonoDevelop.Debugger.VsCodeDebugProtocol/VSCodeVariableSource.cs
- main/src/addins/MonoDevelop.Debugger.VSCodeDebugProtocol/MonoDevelop.Debugger.VsCodeDebugProtocol/VsCodeBacktrace.cs
- main/src/addins/MonoDevelop.Debugger.VSCodeDebugProtocol/MonoDevelop.Debugger.VsCodeDebugProtocol/VsCodeObjectSource.cs
Needed for https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1042237/
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1023874/
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1032065/
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1042217/
FIxes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1016662
Backport of https://github.com/mono/monodevelop/pull/9513
> [release-8.4] [VsCodeDebugger] various fixes

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/ScaffolderTemplateConfigurePage.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1036175
Backport of https://github.com/mono/monodevelop/pull/9478
> Release 8.4 [Scaffolding] Set ComboBoxEntries to autocomplete 

- main/src/addins/MacPlatform/MainToolbar/Styles.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Styles.cs
Reflecting new high contrast palette to error and warning text colors.
Fixes VSTS #1015990
> High Contrast Text

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/ScaffolderTemplateConfigurePage.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1036175
> [Scaffolding] Set ComboBoxEntries to autocomplete 

- main/src/addins/MonoDevelop.UnitTesting.NUnit/MonoDevelop.UnitTesting.NUnit/NUnitAssemblyTestSuite.cs
- main/src/addins/MonoDevelop.UnitTesting.NUnit/MonoDevelop.UnitTesting.NUnit/NUnitTestSuite.cs
- main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.Tests/MonoDevelop.UnitTesting.Tests.csproj
- main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.Tests/MonoDevelop.UnitTesting.Tests/VsTestUnitTestTests.cs
- main/src/addins/MonoDevelop.UnitTesting/Services/UnitTest.cs
Nesting:
**Solution -> Project -> Namespace -> Test class -> Test case**
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1042673/
> [Unit Test] Make the nesting logic for vstest and NUnit(Mono) consistent

- main/src/addins/MonoDevelop.AspNetCore/Templates/MVCViewImportsPage.xft.xml
- main/src/addins/MonoDevelop.AspNetCore/Templates/MVCViewLayoutPage.xft.xml
- main/src/addins/MonoDevelop.AspNetCore/Templates/MVCViewPage.xft.xml
- main/src/addins/MonoDevelop.AspNetCore/Templates/MVCViewStartPage.xft.xml
Fix https://dev.azure.com/DevDiv/DevDiv/_workitems/edit/1050440/
Tasks Done:
Change description of Razor view  to "Razor View Page"
> [1050440]Fix description of Razor files

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/BreakpointPad.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/BreakpointPropertiesDialog.cs
Enable editing of breakpoint locations, either line, function or exception
Fixes VSTS #528267
> [Debugger] Can't edit function breakpoint

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreProjectExtension.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1024557
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1050466
Backport of #9498.
/cc @rodrmoya
> [release-8.4] [AspNetCore] Enable support for launchSettings.json in Worker services

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/Configuration/ScaffoldingPackageVersions.json
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1022827
> Update fallback feed to match live feed

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/Configuration/ScaffoldingPackageVersions.json
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1022827
Backport of #9591.
/cc @nosami
> [release-8.4] Update fallback feed to match live feed
