main/src/core/Mono.Texteditor/Mono.TextEditor/Gui/TextViewMargin.cs
Actual fix in this commit is YToLine instead of textEditor.GetTextEditorData ().VAdjustment.Value / LineHeight which didn't take folded text into calculation resulting in miscalculating startLine/endLine for number of folded lines before current line. So it was invalidating LayoutDescriptor and ChunkDescriptor cache for all lines... hence performance hit on scrolling(mouse scroll, moving up or down with keyboard , debug stepping...)
I also moved linesToRemove into method since don't see good reason for being field... and small optimization for calculating startLine/endLine...
=> [TextEditor] Fix wrong invalidation of LayoutDescriptor and ChunkDescriptor

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProjectConfiguration.cs
For macros that supported by Visual Studio, see ref http://msdn.microsoft.com/en-us/library/42x5kfw4.aspx
The code handles "TARGETPATH" in the DotNetProjectConfiguration.cs file (see switch below), but the description for this tag was missed.
=> added missing $(TargetPath) macro

main/src/addins/TextTemplating/TextTransform/TextTransform.cs
As discussed with @mhutch in another thread, this branch implements silent success for TextTransform.exe.  Messages on failure have been left mostly unchanged (removed elipses in these cases).
=> Succeeds silently as per reference implementation.

main/src/addins/TextTemplating/Mono.TextTemplating.Tests/GenerationTests.cs, main/src/addins/TextTemplating/Mono.TextTemplating/Mono.TextTemplating/TemplatingEngine.cs
As discussed with @mhutch in another thread, this change makes 'C#' the default language setting.
I've also had a stab at a unit test for this change, however I can't get the unit tests to compile, apparently because I'm missing some of the stuff in main/external.  If I figure out how to get this set up, I'll check the unit tests and report back here.
=> Langugae defaults to C# + unit test

main/src/core/Mono.Texteditor/Mono.TextEditor/Gui/TextViewMargin.cs
This logic was added here: https://github.com/mono/monodevelop/commit/f7f17fe73066d3b181d7a0f2a87653b3e75d69fd#diff-2d27ddec65e6cd76bcb8bd8083311dd0R1830
I have no idea why it's good to start/end text Location in middle of character...(I'm maybe making regression, hence PR)
@mkrueger Any idea?
So what this change does it calculates position like this:
How I noticed this... If you try to hover mouse to see debug value of variable 'l' and you are just one pixel to right of middle(so still above 'l', but one pixel to right of middle) debug tooltip won't show up because IsNearX1 will be false and make index++ resulting into space(between 'l' and '=') instead of 'l', hence not displaying debug tooltip...
Red rectangle indicates hit area for debug tooltip(before/after).
=> [Core] PointToLocation starts/ends at start/end of char instead middle of char

main/src/core/Mono.Texteditor/Mono.TextEditor/Gui/TextViewMargin.cs
First commit is for optimisation of rendering. Main improvement comes change that cario.Fill/Stroke are called once per line instead for each space/tab. Another is IndexToLineX use instead of IndexToPos which fetches structure which needs marshalling and few other optimisations like caching textEditorWidth value instead of calling textEditor.Allocation.Width for every space/tab.
Here are videos of difference on [Mac](https://hipchat.xamarin.com/files/1/109/u6BFDEr2CHxHjND/DecorateTabsAndSpacesMac.mov) and [Windows(look at scrollbars)](https://hipchat.xamarin.com/files/1/109/egY4NRQcWkR8Ksg/DrawSpacesAndTabsOptimization.mp4)
Second commit is fixing glitch... I'm guessing we all seen glitch with spaces and tabs rendering like this:
This happens because when scrolling very top line is still …
=> Optimized spaces and tabs rendering + fixed drawing glitch

main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeActionEditorExtension.cs
when the NSMenu is closed.
Fixes http://forums.xamarin.com/discussion/comment/98039
@mhutch
=> [Refactoring] Add an NSMenuDelegate to handle unsetting SuppressTooltips

main/build/MacOSX/Info.plist.in
The vast majority of our users are using Mavericks or higher so
we are going to make Mavericks the minimum requirement for future
releases.
This should be clearly communicated before we merge and ship this.
=> [build] Make Mavericks the minimum supported version of MacOSX

main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.addin.xml, main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/FindDerivedClassesHandler.cs, main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/FindDerivedSymbolsHandler.cs, main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/RefactoryCommands.cs
* Fix the "Find Derived Symbols" navigation command to search in referencing projects
* Fix keybindable FindDerivedClasses command to actually do something
* Make FindDerivedClasses command find derived symbols when used on a member
=> Fix find derived symbols

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DefaultWorkbench.cs
1000 is just some arbitrary value, and it's too big to allow Windows
users to snap MonoDevelop windows left/right. So I'm choosing new
arbitrary sizes here. The new minimum width is 800, which means we'll
be able to snap left/right for resolutions as small as 1600px wide.
If we go much smaller than this, the toolbar is totally non-functional.
The new height is 540px, which is chosen because it's half of
1920x1080.
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=22146
=> [Ide] Change minimum size of the window.

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.PropertyGrid.Editors/ExpandableObjectEditor.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.PropertyGrid/EditorManager.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.PropertyGrid/PropertyEditorCell.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.PropertyGrid/PropertyGrid.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.PropertyGrid/PropertyGridTable.cs
Miscellaneous PropertyGrid fixes.
* Allow any TypeConverter to provider children, not just ExpandableObjectConverter
* Restores support for expanding child rows
* More consistently provides ITypeDescriptorContext to TypeConverters
=> PropertyGrid fixup

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs
Opening the realpath of a file prevents problems with debugging symlinked
files, such as the case https://bugzilla.xamarin.com/show_bug.cgi?id=27098
=> [Ide] Resolve full path of fileName before opening in Workbench

main/src/core/MonoDevelop.Core/MonoDevelop.Core/FileService.cs
These make it a lot easier to perform some action when (for example)
solution nodes are dragged or copied around.
=> [Core] Add FileCopied and FileMoved events to FileService

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestSession.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components/GtkUtil.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkMacInterop.cs
The command manager now can use the active NSView as initial target of
the command route, and can handle shortcuts when the focus is in
a native NSView.
=> [Ide] Fix command handling in native mac widgets

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ImageService.cs
CellRendererImage can't take null images. CellRendererImage.NullImage has
to be used instead.
Fixes bug #27323 - Lots of GtkTreeView errors due to new debugger visualizers
=> [Ide] Fix tree icon rendering issue

main/src/addins/MonoDevelop.GtkCore/MonoDevelop.GtkCore.GuiBuilder/GtkProjectServiceExtension.cs
I accidentally pushed to 5.9 and reverted this fix.
I'm re-reverting in a PR to apply the fix. This stops a NRE from happening when creating a Gtk project through the new Solution Dialog in case the gtk-sharp reference isn't set.
=> [5.9][Gtk] Fix a NRE with Gtk projects creation.

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/NewProjectConfiguration.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/NewProjectController.cs
The "Use git for version control" option is now disabled by default in the New Project dialog.
=> [5.9] Git version control disabled by default in New Project Dialog

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/UpdatedPackagesInSolutionTests.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/CheckForUpdatesTaskRunner.cs
The NuGet addin was accessing the Task's Result when the task was cancelled causing the TaskCanceledException to be thrown.
=> [NuGet] Prevent TaskCanceledException when check for updates cancelled

main/src/core/MonoDevelop.Ide/gtk-gui/MonoDevelop.Ide.Projects.GtkProjectConfigurationWidget.cs, main/src/core/MonoDevelop.Ide/gtk-gui/gui.stetic
Fixed bug 27652 - New "New solution" dialog has a button "Browse..." which is cut off
https://bugzilla.xamarin.com/show_bug.cgi?id=27652
On Linux the font is larger and the text for the create gitignore label was causing the Browse button to be truncated. Now the labels extend into the last table column which contains the Browse button so the button is no longer truncated.
=> [Ide] Fix New Project dialog browse button truncated on Linux.

main/src/core/Mono.Texteditor/Mono.TextEditor/Gui/FoldingScreenbackgroundRenderer.cs, main/src/core/Mono.Texteditor/Mono.TextEditor/Gui/TextArea.cs
Folding screen background ends on previous line, when last line of FoldSegment ends with < eof >.
Should be:
Folding screen background rendered wrong on big collapse segments.
Its easy to hit Cairo coordinate limits (+/- 8,388,608 https://developer.gnome.org/goocanvas/stable/goocanvas-coordinates.html) for top level folding segments, in relatively big source files. That's causing rendering artifacts. Issue resolved by clamping source folding rectangle with visible screen area.
Should be:
=> [TextEditor] Folding screen background rendered wrong.

main/src/addins/WindowsPlatform/WindowsPlatform/WindowsPlatform.cs
[Fixed bug 26622](https://bugzilla.xamarin.com/show_bug.cgi?id=26622) - Getting error "Save failed. Object reference not set to an instance of an object" when create ASP.NET MVC Razor Project template.
Handle a missing OpenWithProgids registry key when finding apps for a particular file extension.
=> [Windows] Fix null reference exception when registry key is missing.

main/src/core/MonoDevelop.Core/MonoDevelop.Core/FilePath.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectService.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.DockNotebook/DockNotebook.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/RootWorkspace.cs
This file:/// translation pattern happens in many places:
if (filename.StartsWith ("file://", StringComparison.Ordinal))
filename = new Uri(filename).LocalPath;
All of them use strings for paths, which is a smell
(http://c2.com/cgi/wiki?PrimitiveObsession) so we can kill two
birds with one stone if we change them to use FilePath instead,
and move this path sanitization to the FilePath ctor.
=> [Core/Ide] Sanitize file:// URIs in FilePath ctor

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectService.cs
Opening the realpath of a file prevents problems when using solutions
inside symlinked paths, such as:
- compilation problems [1].
- rendering of ugly relative paths (cosmetic) [2].
This is a similar fix to [3].
[1] https://bugzilla.xamarin.com/show_bug.cgi?id=27097
[2] https://bugzilla.xamarin.com/show_bug.cgi?id=27331
[3] https://github.com/mono/monodevelop/commit/32e25ea
=>  [Core] Resolve full path of workspaceItem before reading

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkProjectConfigurationWidget.cs
Fixed [bug 27872](https://bugzilla.xamarin.com/show_bug.cgi?id=27872) - Pressing enter twice in New Project dialog adds new line to project name
On the Mac pressing the enter/return key twice quickly when the New Project dialog was first shown would insert a carriage return \r into the project name text box. The carriage return is now removed from the text box. Also pasting in multiple lines into any of the text boxes will not insert any new line characters but only
the first line of pasted text.
=> [Ide] Fix carriage return added to project name in New Project dialog

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
When our main window isn't focused, most system commands should
just pass through. For example, Cmd-Shift-G in the file open
dialog should open the "Go to folder" sheet.
Exceptions to this are made for SelectAll, Cut, Copy, Paste.
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=27940
=> [Ide] When window is unfocused, let most system commands fall through

main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/DebugValueWindow.cs
This reverts commit b627818f26dfb37b39b1a6ac60299f09bd83b7ed.
This causes a bigger problem than the one it solves. This PR is to revert it for 5.9
=> Revert "[Debugger] Set tooltip window types/hints based on platform"

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/DockFrame.cs
When a pad is shown (for example Toolbox) it appears to have focus, but
in reality it doesn't because it's been blocked from accepting. At this
point we visually have input in the pad, but it's actually in the text
editor, and the only way to correct it (and get auto-hiding to work again)
is to click/focus the widget that already visually appears to have focus
so that it actually *does* have focus.
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=27917
=> [Docking] Don't disable AcceptFocus on the window or it confuses focus.

main/src/addins/MacPlatform/MacPlatform.cs, main/src/addins/WindowsPlatform/WindowsPlatform/WindowsPlatform.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/PlatformService.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ClassPad/SolutionNodeBuilder.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/FileOperationsBuilderExtension.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/ViewCommandHandlers.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/DesktopService.cs
This is very useful when folder has many files since it highlights and scrolls to file(s) user is interested in...
Linux is messed up... There is DBus command for this: "org.freedesktop.FileManager1.ShowItems" but it seems only Nautilus supports it... I could probably special case(detect if nautilus is main file browser) or any other file browser(dolphin) but then... Nautilus doesn't support selecting multiple files(it opens multiple windows for files in same folder).
So for now Linux doesn't support this :(
=> Added support for selecting files when using "Open containing folder"

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/DockFrame.cs
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=27868
=> [Mac] Check that the dialog is visible before raising over native docks

main/src/addins/MacPlatform/MacInterop/GtkQuartz.cs, main/src/addins/MacPlatform/MainToolbar/MainToolbar.cs, main/src/addins/MacPlatform/MainToolbar/SearchBar.cs, main/src/addins/MacPlatform/MainToolbar/StatusBar.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkMacInterop.cs
There are a few items remaining, but I can't fix them:
Undo/redo for NSTextField
https://bugzilla.xamarin.com/show_bug.cgi?id=27920
Reopened branch as-per no-force-push policy. Will start using forks from now on.
=> 5.9 last xmtoolbar fixes

Makefile, main/Makefile.am, main/tests/Makefile.am
Requires the patch set in https://github.com/mono/mono/pull/1616 to be applied to mono so the log profiler has coverage support
=> [Coverage] Add a make coverage option to run coverage tests

main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/ClassOutlineTextEditorExtension.cs
Addresses the warnings that flood the ide.log in the form of
ERROR [2015-03-16 14:33:51Z]: Gtk-Critical: GtkTreePath *gtk_tree_model_sort_get_path(GtkTreeModel *, GtkTreeIter *): assertion `tree_model_sort->stamp == iter->stamp' failed
Stack trace:
at Gtk.TreeSelection.gtk_tree_selection_select_iter(IntPtr , IntPtr )
at Gtk.TreeSelection.SelectIter(TreeIter iter) in /private/tmp/source-mono-mac-4.0.0-branch/bockbuild-mono-4.0.0-branch/profiles/mono-mac-xamarin/build-root/gtk-sharp-2.12.21/gtk/generated/TreeSelection.cs:line 133
at MonoDevelop.DesignerSupport.ClassOutlineTextEditorExtension.RefillOutlineStore() in /Users/builder/data/lanes/1494/9ebd512b/source/monodevelop/main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/ClassOutlineTextEditorExtension.cs:line 312
at …
=> [DesignerSupport] Use outline sort model to get the first item instead of the outline model.

main/configure.in
Checking for pkg-config was being done twice, and the first time
that was done was incomplete.
=> [configure] Move the full check for pkg-config

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/WorkbenchWindow.cs
Added a WindowRole for WorkbenchWindows of Monodevelop to allow target-oriented Rule-Creation in Windowmanagers like KWin.
This implements [FeatureRequest#23062](https://bugzilla.xamarin.com/show_bug.cgi?id=23062)
=> Added a WindowRole for WorkbenchWindows

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs
Fixes bug 19640 - Resource.designer.cs not recompiled on close-and-save
When prompting the user to save the file if the user closes the document, we don't send a file change event. We should really be calling Document.Save() rather than replicating part of the save logic here.
Also addresses a minor error where, if the file is unsaved, and the user cancels the SaveAs, we get an ArgumentNullException.
=> Monodevelop 5.9 branch bug 19640

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionEntityItem.cs
Mark a project as dirty for fast-build-check when it is cleaned.
Fixes bug #28449
=> [Core] Fix fast-build-check issue

main/src/addins/MonoDevelop.Debugger.Soft/MonoDevelop.Debugger.Soft/SoftDebuggerEngine.cs
[Bug 28550](https://bugzilla.xamarin.com/show_bug.cgi?id=28550) was discovered only now because UITests project was added and it's not referenced(hence built) on F5 bring this bug up...
Debugger bump is bringing only this commit: https://github.com/mono/debugger-libs/commit/c937df078222f1f910758d60adeda06ae706dc36
=> [Debugger] Bug 28550 and Hashtable values display on Mono4/.Net

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestClientSession.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestSession.cs, main/tests/UserInterfaceTests/CreateBuildTemplatesTestBase.cs, main/tests/UserInterfaceTests/Ide.cs, main/tests/UserInterfaceTests/MonoDevelopTemplatesTest.cs, main/tests/UserInterfaceTests/NewProjectController.cs, main/tests/UserInterfaceTests/UserInterfaceTests.csproj, main/tests/UserInterfaceTests/Util.cs
Fixes UserInterfaceTests
Tests templates for templates in file `MonoDevelopTemplatesTest.cs`
* Console Project
* Gtk# 2.0 Project
* Library
* NUnit Library Project
Steps taken for all the template tests
* Open `New Solution` dialog
* Select `.NET`
* Select the template type
* Click `OK`
* Enter `Project Name`
* Enter `Solution Name`
* Enter `Location`
* Asserts that `Create a project within the solution directory` is enable and visible. If yes, then unchecks it.
* Asserts that `Create a .gitignore file to ignore inessential files` is enabled and visible. If yes, then unchecks it.
* calls `beforeBuild` action, which is the action to be taken before the solution is built. In case of NUnit Project, that delegate blocks waiting for `Package updates are available.` to be visible in Status Bar …
=> Update UserInterfaceTests with template tests

main/tests/UserInterfaceTests/CreateBuildTemplatesTestBase.cs, main/tests/UserInterfaceTests/TestService.cs, main/tests/UserInterfaceTests/UITestBase.cs
This would allow the addins to use UITestBase to create their own UITest and specify the MonoDevelop.exe location
=> Allow Monodevelop executable path to be overridden from UITestBase

main/src/addins/NUnit/Services/NUnitProjectServiceExtension.cs, main/src/addins/NUnit/Services/NUnitService.cs
Fixed bug #28083 - When running an NUnit project, Xamarin Studio
always asks "An application is already running and will have to be
stopped. Do you want to continue?"
https://bugzilla.xamarin.com/show_bug.cgi?id=28083
When an NUnit project was run, either from the main toolbar menu or
from the Run menu, with Start Debugging or Start Without Debugging,
the NUnit addin was treating the running of the tests as a separate
run operation which would cause a prompt to be displayed to the user.
Now when the NUnit project is run the ProjectOperation's
CurrentRunOperation is not checked, nor modified by, the NUnit addin
since it is part of the CurrentRunOperation and not a separate
operation.
The user will still be prompted if they are debugging another project
in the solution and then try to run …
=> [NUnit] Fix prompt always displayed when running NUnit project.

main/src/addins/NUnit/Services/NUnitProjectServiceExtension.cs, main/src/addins/NUnit/Services/NUnitService.cs
Fixed bug [#28083](https://bugzilla.xamarin.com/show_bug.cgi?id=28083) - When running an NUnit project, Xamarin Studio always asks "An application is already running and will have to be stopped. Do you want to continue?"
When an NUnit project was run, either from the main toolbar menu or from the Run menu, with Start Debugging or Start Without Debugging, the NUnit addin was treating the running of the tests as a separate run operation which would cause a prompt to be displayed to the user. Now when the NUnit project is run the ProjectOperation's CurrentRunOperation is not checked, nor modified by, the NUnit addin since it is part of the CurrentRunOperation and not a separate operation.
The user will still be prompted if they are debugging another project in the solution and then try to …
=> 5.9 [NUnit] Fix prompt always displayed when running NUnit project.

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/ProjectOptionsDialog.cs
Fixes #28437 as well as a minor rendering issue for the iOS build options.
=> [Ide] Use DefaultHeight instead of HeightRequest when setting the height  of the project options dialog.

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbar.cs
Fixes (well, partly) #23507
- slightly wider on windows to accommodate more text, especially "Manage Android Devices...".
- don't indent the text when the drop down is closed (same as config combo).
=> [Ide] Minor tweak to runtime combo for windows

main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebuggingService.cs, main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ExceptionCaughtDialog.cs
Open exception dialog window
Also setting OnlyShowMyCode in exception dialog if user has OnlyMyCode enabled in debugger settings
Includes https://github.com/mono/debugger-libs/commit/5660243990e8c8483988ac31fac701a008379f27
https://bugzilla.xamarin.com/show_bug.cgi?id=24975
=> [Debugger] If exception is thrown and there is no user code in stack

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/FindInFilesDialog.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/ISearchProgressMonitor.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/Scope.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/SearchProgressMonitor.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/SearchResultPad.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/SearchResultWidget.cs
There's no much point in showing the Path column when the scope of
the FindInFiles search is "Current document" or "Selection" because
its value is going to be the same across all rows.
This is developed with a PathMode enum which will be useful too, for
a future commit that will allow using relative paths in certain
situations.
=> [FindInFiles] Hide the "Path" column if scope is current doc or selection

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.UI.cs
Fixed bug #28971 - New project window disappears if pads
(e.g. Application output, solution window) set to auto hide
https://bugzilla.xamarin.com/show_bug.cgi?id=28971
Simplest way to reproduce the problem is to configure the
solution window to be auto-hide and then right click the solution
and select Add - Add New Project. The New Project dialog will
open and then as the Solution window hides the New Project dialog
will be closed. This happens on the Mac but not on Windows.
=> 5.9 - Fix New Project dialog closing when auto-hide window closes

main/tests/UserInterfaceTests/CreateBuildTemplatesTestBase.cs, main/tests/UserInterfaceTests/MonoDevelopTemplatesTest.cs, main/tests/UserInterfaceTests/MonoDevelopTests/ASPNETTemplateTests.cs, main/tests/UserInterfaceTests/MonoDevelopTests/DotNetTemplatesTest.cs, main/tests/UserInterfaceTests/MonoDevelopTests/MiscTemplatesTest.cs, main/tests/UserInterfaceTests/NewProjectController.cs, main/tests/UserInterfaceTests/UserInterfaceTests.csproj
* Refactor and extract functionality in CreateBuildTemplatesTestBase so that it can be used in other tests
* Added ASP.NET tests for all templates
* Extracted General and Other category in TestBase
* Create a method which generates projectname from template name by cleaning it of any special chars
* Refactored MonoDevelopTemplatesTest to remove redundant information
* Added tests for Generic and C/C++ Miscellaneous templates
* Generic Kind
* Generic Project
* Packaging project
* C/C++ Kind
* Shared Library
* Static Library
* Console Project
=> Added UITest for ASP.NET and Miscellaneous templates

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.PropertyGrid.Editors/TextEditor.cs
This logic seemed wrong, Dispose would never fire the pending change request unless it was called a second time.
Fixes bug#29070
=> [Ide] When disposing, fire pending change request.

main/src/addins/WindowsPlatform/WindowsPlatform/WindowsSecureStoragePasswordProvider.cs
Hi,
I have a problem with PasswordService. I can add a password but can not retrieve it. Here is my pull request to fix the problem. 
More info: I'm using Windows 8.1 and when I use the method PasswordService.AddWebPassword(url, password); MonoDevelop creates credentials with empty UserName. When I try to get back the password it is empty string this is because ncred.UserName is equal to IntPtr.Zero.
=> Remove check for UserName equal to IntPtr.Zero

Makefile, main/Makefile.am, main/tests/Makefile.am
Instead of updating the existing `test` make target, created a new `uitest` make target which can be used to run UserInterfaceTests
=> Create a new test target named uitest to run UITests

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestClientSession.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestSession.cs, main/tests/UserInterfaceTests/CreateBuildTemplatesTestBase.cs, main/tests/UserInterfaceTests/Ide.cs
* GetCommandArrayInfoValues (Command) returns the arrayInfo values
of a command as a List<object>
* Added support to pass the dataItem argument with ExecuteCommand
* Ide.GetSolutionConfigurations () to get list of configurations
available for a solution created by the template
---
Call IdeApp.Exit() instead of letting Process to kill it
When IdeApp.Exit () is called, MonoDevelop goes through
proper code paths to properly shut down itself. Going
through Process.Kill () is not the correct method since
it does not hit the correct code paths. There were instances
where csproxy was not exiting and ended up holding a lot of
memory thereby hitting 15.96/16GB of memory.
Thanks to Alan for tracking down the issue
---
Update timeouts
* Package update timeout is now 120s to account for network …
=> Call IdeApp.Exit() instead of letting Process to kill it

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestSession.cs, main/tests/UserInterfaceTests/CreateBuildTemplatesTestBase.cs, main/tests/UserInterfaceTests/MonoDevelopTests/ASPNETTemplateTests.cs, main/tests/UserInterfaceTests/MonoDevelopTests/MiscTemplatesTest.cs, main/tests/UserInterfaceTests/NewProjectController.cs, main/tests/UserInterfaceTests/TemplateTestOptions.cs, main/tests/UserInterfaceTests/UserInterfaceTests.csproj
The goal is to make improve `CreateBuildTemplatesTestBase` class and break down the `CreateBuildProject` method into multiple virtual methods so that the subclass tests can override with their specific implementation.
This PR contains code from PR #886 to with merge conflicts resolved.
=> Refactor CreateBuildProject by breaking it into multiple virtual methods

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/FindInFilesDialog.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/ISearchProgressMonitor.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/Scope.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/SearchProgressMonitor.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/SearchResultPad.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/SearchResultWidget.cs
Relative paths to the solution base directory are easier to read
without horizontal scrolling.
=> [FindInFiles] Use relative paths in the Path column, when possible

main/src/addins/MacPlatform/MainToolbar/StatusBar.cs
Bug 28930 - NullReferenceException in status bar terminated Xamarin Studio
=> Fix NRE when clicking on the statusbar in wrong places.

main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValueTreeView.cs
In case of exception message.ToString() on Android it produced stacktrace message with \n as new line which was not trimmed on Windows
This is meant for Cycle5 SR1
=> Bug 28834 - Exception windows is not working properly

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/CheckForUpdatesProgressMonitorTests.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/PackageCompatibilityRunnerTests.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/UpdatedPackagesInSolutionTests.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageCompatibilityRunner.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/ProgressMonitorStatusMessageFactory.cs
Fixed bug #28730 - Status bar text from NuGet addin is too long
to fix in the status bar
https://bugzilla.xamarin.com/show_bug.cgi?id=28730
The new native status bar for Mac has a smaller width and the
status bar text from the NuGet addin would be too long to be
displayed. To reduce the length of the status bar text the
'Please see the Package Console for details.' text has been
removed.
=> 5.9.1 NuGet reduce status text length

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/NewProjectController.cs
Previous button not working with Empty Wizard.
Bug: https://bugzilla.xamarin.com/show_bug.cgi?id=29342
Trello Card: https://trello.com/c/E0ZkXubS/137-xs-bug-29342-macwizard-clicking-previous-on-configure-your-new-project-whens-selecting-spritekit-game-does-not-work-the-first-ti
=> [NewProjectDialog] Fixed #29342

main/src/addins/NUnit/Gui/TestResultsPad.cs, main/src/addins/NUnit/Services/ExternalTestRunner.cs, main/src/addins/NUnit/Services/NUnitAssemblyTestSuite.cs
Fixes bug 29457 - Uncaught exceptions from test can bring down the test runner.
Unhandled exceptions still bring down the test runner, but at least they
are now properly reported.
=> [NUnit] Properly report unhandled exceptions

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestClientSession.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestSession.cs, main/tests/UserInterfaceTests/CreateBuildTemplatesTestBase.cs, main/tests/UserInterfaceTests/Ide.cs, main/tests/UserInterfaceTests/MonoDevelopTests/ASPNETTemplateTests.cs, main/tests/UserInterfaceTests/MonoDevelopTests/DotNetTemplatesTest.cs, main/tests/UserInterfaceTests/MonoDevelopTests/MiscTemplatesTest.cs, main/tests/UserInterfaceTests/Util.cs
Adds support for Mac screenshots using native `Foundation` and `AppKit` support. There are instances where the tests are failing in XS, so having screenshots is the only reliable way to track down the issues
Thanks to Chris Hamons for the `DllImport` section.
=> Add screenshots to the unit tests for Mac platform

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Operations/ModelOperation.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/GtkTreeModelResult.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/GtkWidgetResult.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AppQuery.cs
If the combobox has been created with Gtk.ComboBox.NewText or the Gtk.TreeModel has a string as its first column then the Text operator will operate on it directly, using that first column.
If the combobox has been created by specifying a different type of model, or the required string is not the first column, then the Model operator will have to be used, and the combobox's Gtk.TreeModel will have to have the SemanticModelAttribute added to it.
=> [AutoTest] Add support for ComboBoxes.

main/Makefile.am, main/tests/Makefile.am, main/tests/UserInterfaceTests/MonoDevelopTests/ASPNETTemplateTests.cs, main/tests/UserInterfaceTests/MonoDevelopTests/DotNetTemplatesTest.cs, main/tests/UserInterfaceTests/MonoDevelopTests/MiscTemplatesTest.cs
Now when running
`make uitest assembly=assemblyname.dll`
it is possible to selectively run certain tests by passing another
optional argument named categories which is a comma seperated list
of NUnit categories
`make uitest assembly=UserInterfaceTests.dll categories=DotNet,Misc`
=> [UITest] Add filtering of uitest target by 'categories' argument

main/wintest.sh
Matches Mac and Linux behaviour from makefiles.
=> [Build] Don't fail tests for windows if dll is not found.

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestClientSession.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestSession.cs
During writing UITest it is important to more closely imitate the working of the UI. `CommandManager.DispatchCommand` takes another argument named `CommandSource source` which tells from the source of the request like `MainMenu` or `ContextMenu`. This is important as some commands can only be called from one source and not from another
=> [AutoTest] Add support for passing CommandSource to CommandManager.DispatchCommand

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.csproj, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageManagementSolutionExtensions.cs
Allow a PackageManagementProject to be obtained given just a
DotNetProject.
=> [NuGet] Extend project API to make it simpler to use.

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestSession.cs
Raising TimeoutException in the case of timeout can help us narrow down the
causes of failures because such exceptions can be filtered and analyzed
separately. Lots of timeout exception happen because the test machine
is slower or the network is slower which leads to test failures even when
there is nothing wrong with the tests.
cc: @iainx
=> [AutoTest] When a timeout occours, raise TimeoutException instead of generic Exception

main/src/addins/MacPlatform/Dialogs/MacSelectFileDialogHandler.cs
Set `NSOpenPanel.ResolvesAliases = false` so that paths selected by the user are returned as-is and not resolved (in the case of an alias/symlink).
This matches `Gtk.FileChooserDialog`’s behavior, which does not resolve symlinks and simply returns the path exactly as the user selected.
This also fixes [bxc#30655](https://bugzilla.xamarin.com/show_bug.cgi?id=30655) where the dialog causes symlinks to resolve and therefore persist in preferences for custom .NET runtimes.
=> MacPlatform: MacSelectFileDialogHandler: preserve symlinks (bxc#30655)

main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValueTreeView.cs
Fixing https://bugzilla.xamarin.com/show_bug.cgi?id=29725
=> [Debugger] Removed valueNames.Clear() to prevent WatchPad entries removal

main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs
with 14dad72ef710e0267a985c5b5ffc53100282f31d
For reference, http://forums.xamarin.com/discussion/39714/version-5-9-is-very-slow
=> Fix some gtk assertion spew in the logs that began

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Operations/ChildrenOperation.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Operations/IndexOperation.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Operations/MarkedOperation.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Operations/ModelOperation.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Operations/NextSiblingsOperation.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Operations/PropertyOperation.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Operations/TextOperation.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Operations/TypeOperation.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AppQuery.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestSession.cs
* Overridden `ToString ()` for all subclasses of `Operation` so that the original Query can be reconstructed
* For `AppQuery.ExecuteQuery` method, handle the call in a `try-catch` block and throw another `TimeoutException` with the caught `TimeoutException` as InnerException
* Added a Name argument to `CheckOperation` ctor so that wrappers over it can led `CheckOperation` about the actual Query syntax.
=> Added more debugging support to AutoTest

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Operations/ChildrenOperation.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Operations/IndexOperation.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Operations/MarkedOperation.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Operations/ModelOperation.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Operations/NextSiblingsOperation.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Operations/PropertyOperation.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Operations/TextOperation.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Operations/TypeOperation.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/GtkTreeModelResult.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/GtkWidgetResult.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AppQuery.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AppResult.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestSession.cs
Depends on https://github.com/mono/monodevelop/pull/926 first
This PR contains just one commit, which needs to be added on top over PR #926 - https://github.com/mono/monodevelop/commit/e4949ff7d6c443a0ab552bf9ee6c59917e3f03b8
Right now we can catch the exception and know the exact query only in method ExecuteQuery, WaitForElement and WaitForNoElement because in those methods we are provided with original AppQuery.
In methods like Select, Click, EnterText and Toggle, we just get the AppResult and hence it becomes hard to figure out the exact query which led to this result.
In this commit, SourceQuery is a string which holds the original string query which was assigned to it during evaluation. This is an additional data useful for debugging when there is a timeout in the above four methods …
=> Added SourceQuery to QueryResult so that actual query can be known during timeout

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestClientSession.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestSession.cs
Sometimes the result of clicking a button is a modal dialog opening. In these cases ExecuteOnIdleAndWait will timeout because button.Click () will not return until after the dialog has been closed. By setting wait = false the idle completion will not be waited on, and the method will return immediately
Fixes XB #30730
=> [Test Framework] Add a wait parameter to ExecuteOnIdle(AndWait)

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.PropertyGrid/PropertyGridTable.cs
the previous logic was unintuitive, so now show the tooltip while hovering the whole row
Bug 30545 - Properties Pad could use a tool tip for long property values
=> [PropertyPad] Query tooltip on whole row

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/GtkTreeModelResult.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AppResult.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.UI.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkProjectFolderPreviewWidget.cs, main/tests/UserInterfaceTests/CreateBuildTemplatesTestBase.cs, main/tests/UserInterfaceTests/DialogTests/NewProjectDialogTests.cs, main/tests/UserInterfaceTests/NewProjectController.cs, main/tests/UserInterfaceTests/UserInterfaceTests.csproj
For Cycle 6 we have a small UI enhancement for folder/project preview. This suite tests the preview by using 8 different combination of
* Create a project within solution directory - Checked and Unchecked
* Use git for version control - Checked and Unchecked
* Create a .gitignore file to ignore inessential files - Checked and Unchecked
the 8 tests are:
* WithoutGit--WithGitIgnore--WithProjectWithinSolution
* WithoutGit--WithGitIgnore--WithoutProjectWithinSolution
* WithGit--WithoutGitIgnore--WithProjectWithinSolution
* WithoutGit--WithoutGitIgnore--WithoutProjectWithinSolution
* WithGit--WithGitIgnore--WithProjectWithinSolution
* WithGit--WithGitIgnore--WithoutProjectWithinSolution
* WithGit--WithGitIgnore--WithProjectWithinSolution
=> Add UITests for NewProjectDialog's Project preview

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeTemplates/ExpansionObject.cs
Fix codeTemplate **GetComponentTypeOf** bug for generic collections.
**note**
Default 'foreach' template does not handle automatic type by default.
to add it you have to:
- add type to template:  'foreach($type$ $id$ in $collection$)'
- set function parameter for type to: GetComponentTypeOf("collection")
I'm not sure where to add this in the MD/src tree, changes to 'MonoDevelop-templates.xml' does not seem to have effect.
*Details:*
IType.GetAllBaseType() extention method returns 'System.Collections ' prior to 'System.Collections.Generic'
which causes fetching Generic Collection parameter's type to fail in CodeTemplate mechanic.
modified:         core/MonoDevelop.Ide/MonoDevelop.Ide.CodeTemplates/ExpansionObject.cs
=> [code] Fix Generic collection argument type return for code template

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/GtkWidgetResult.cs
Since we are comparing two objects which won't ever reference to
the same object, we should use object.Equals instead of using
the equality operator which on base object just resolves to
`object.ReferencesEqual`
http://stackoverflow.com/questions/814878/c-sharp-difference-between-and-equals
=> [AutoTest] Fix AppQuery.Property by using object.Equals instead of ==

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/GtkTreeModelResult.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/GtkWidgetResult.cs
This is a partial solution to select `TreeView` row when the `TreeModel` to `CellRenderer` mapping is done using `SetCellDataFunc` method instead of regular method of adding attributes.
This would work only when TreeModel contains complex type whose specific property are known. If `SetCellDataFunc` method has some code where a method is invoked to fetch the values, this won't work.
This patch would solve most of the common scenarios of selection. e.g. OptionsDialog has the Model which contains `OptionsDialogSection` as the first column. We can use `OptionsDialogSection.Label` to select the specific row.
If `OptionsDialogSection` has a complex type as it's label say `Date` which is of type `DateTime` and we want to match year, then we would need to use this query
```
Session.Select (c => …
```
=> [AutoTest] Use GtkTreeModelResult.Property to match IterValue properties

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/GtkTreeModelResult.cs
If a `Children ()` operation is called on a TreeView, then instead of returning null, return its immediate children, subsequent `Children ()` operation would be needed to child the child of the currently selected TreeIter
=> [AutoTest] Return the child TreeIter for TreeView when Children () is called

main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/AssemblyBrowserWidget.cs, main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/DomEventNodeBuilder.cs, main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/DomFieldNodeBuilder.cs, main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/DomPropertyNodeBuilder.cs
Some fixes for potential null dereferences discovered by Coverity.
The DOM related fixes may have been false positives.
=> [Assemby Browser] Fix some potential Null dereferences

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Operations/PropertyOperation.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/GtkWidgetResult.cs
* Also Fix PropertyOperation.ToString ()
=> [AutoTest] Property Operation now looks at Static and Non-Public members

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/GtkTreeModelResult.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/GtkWidgetResult.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/NSObjectResult.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AppResult.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestClientSession.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestSession.cs
A better flash implementation.
Flash is only an outline rather than solid red.
caller can use WaitForEvent ("FlashCompleted") to delay execution until the flash is completed
=> [Test Framework] Add ability to flash the AppResults

main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/ConflictResolutionDialog.cs, main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/CredentialsDialog.cs, main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/EditBranchDialog.cs, main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/EditRemoteDialog.cs, main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitConfigurationDialog.cs, main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/MergeDialog.cs, main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/NewStashDialog.cs, main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/PushDialog.cs, main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/StashManagerDialog.cs, main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/UserGitConfigDialog.cs, main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/UserInfoConflictDialog.cs, main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/gtk-gui/MonoDevelop.VersionControl.Git.EditRemoteDialog.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components/ContextMenuItem.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components/GtkUtil.cs
events on all Gtk.Entry widgets in its child tree and to manage
the context menu using MonoDevelop's ContextMenu component so we
have native context menus on OSX.
https://bugzilla.xamarin.com/show_bug.cgi?id=29751
=> Add an extension method to Gtk.Window to have it hijack right-click

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/GtkWidgetResult.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/NSObjectResult.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/ObjectResult.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AppResult.cs
After trying to explore the API, I realized that passing System.Type over remoting would randomly fail. This patch just  changes `AppResult. GetResultType` such that it just returns `System.Type.FullName` instead of `System.Type`
=> [AutoTest] Use string Type.FullName for ResultType instead of System.Type

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectService.cs
For Cycle 5 SR 3.
Fixed [bug #30299](https://bugzilla.xamarin.com/show_bug.cgi?id=30299) - User is unable to create iOS and other projects when Android addin is disabled.
To reproduce the original bug, open Xamarin Studio, disable the Android addin in the Add-in Manager, then try to create a new Xamarin.Forms solution. Clicking the Next button would not show
the Xamarin.Forms wizard page. In the logs there would be an error "Disabled add-ins can't be loaded" as the MonoDevelop.MonoAndroid addin was trying to be used.
The problem was that the Xamarin.Forms wizard checks that iOS and Android projects are supported using the ProjectService's CanCreateProject. This method was trying to load the Android addin's ProjectBinding but failing since the addin was disabled.
Now when an addin is …
=> [Core] Remove project binding when addin is disabled.

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestClientSession.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestSession.cs, main/tests/UserInterfaceTests/Ide.cs
IsBuildSuccessful is not right for being in AutoTestSession as it is an
interpretation of the data, which should be left up to the tests to decide. It
has been replaced with a method called ErrorCount which returns the number of
errors reported at a specified severity. It is then up to the caller to decide
what to do with this data.
=> [Test Framework] Remove the IsBuildSuccessful calls from AutoTestSession

main/src/core/MonoDevelop.Core/MonoDevelop.Core/Platform.cs
The code to call Gestalt is duplicated in both Platform.cs and MacSystemInformation.cs. Make the Platform method use the MacSystemInformation method.
=> [Core] Remove the duplicated Gestalt reading code

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/GtkTreeModelResult.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/GtkWidgetResult.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/NSObjectResult.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/ObjectResult.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AppResult.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestSession.cs
I am able to flash it properly without the `System.Action`
=> [AutoTest] Remove Action from Flash methods and redundant CheckForText

main/src/addins/MacPlatform/MainToolbar/MainToolbar.cs, main/src/addins/MacPlatform/MainToolbar/SearchBar.cs
Remove the focus from the Gtk focus system when the searchbar is focused.
Fixes BXC #29601 Pressing a shortcut key to the search in the top right moves the cursor to both the search box and text editor simultaneously
=> [MacPlatform] Prevent editor and search bar both having focus

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Operations/ChildrenOperation.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/GtkTreeModelResult.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AppQuery.cs
This allows us to inspect individual row of TreeView
=> [AutoTest] Override Properties () for GtkTreeModelResult and allow non-recursive Children with proper handling of TreeIter in GtkTreeViewResult

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.DockNotebook/DockNotebook.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components/ContextMenuExtensionsGtk.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components/MenuButton.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.OptionPanels/KeyBindingsPanel.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/DefaultPolicyOptionsDialog.cs
There are multiple systems for building menus in MonoDevelop
- Using the standard Gtk.Menu functions like MenuButton uses
- MonoDevelop.Components ContextMenu system where menus are described in an object model, and Gtk.Menu and NSMenus can be created from them
- By using CommandEntrySets, another model that can then generate Gtk.Menu or NSMenu
This patch ports MenuButton to use the MonoDevelop.Components.ContextMenu system and deprecates the old Gtk.Menu methods. This should make it possible to switch to using NSMenu for these popup menus on the Mac
=> [Components] Use the ContextMenu system to build the popup menu for MenuButton

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.Formats.MSBuild/MSBuildProjectHandler.cs
Bug 30802 - [Generic Project] Generic Project template cannot be built,
fails with Build failed. Object reference not set to an instance of an object
The variable `res` is set by `RunTarget` method which can return null
=> [MSBuild] Fix NRE on MSBuild (exposed when building a Generic Project Template)

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Ide.cs
Needed to resolve bug #29481 - "Supported List" should be a hyperlink instead of a button under Target Framework for Mac projects
=> [Ide] Set Gtk.LinkButton's URI handler

main/src/addins/NUnit/Gui/TestResultsPad.cs
Fixed [bug #31272](https://bugzilla.xamarin.com/show_bug.cgi?id=31272) - Test results disappear randomly after running a test.
Only clear the results in the Test Results window when a workspace item is closed or a new test run is started. Previously the Test Results window would be cleared when the active configuration
changed. The active configuration can be changed manually or if the SolutionItem's OnExecutionTargetsChanged method is called and the project does not use Debug as its default target. The Unit Tests window is still refreshed when the active configuration is changed.
=> [NUnit] Do not clear test results when active config changed.

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/GtkTreeModelResult.cs
Kind of embarrassing that I missed out this small call when updating Select last time.
Thanks to mhutch
=> [AutoTest] GtkTreeView should be focused before any Iter is selected

main/src/addins/MacPlatform/MainToolbar/MainToolbar.cs
Search through the overflow menu items to find the SearchBar rather than assuming it is the first one. Fixes BXC #32002
=> [MacPlatform] Don't assume the search bar is the 1st item in overflow

main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/AttachToProcessDialog.cs
Call OnRowActivated. Fixes issues with double clicking entries in the process tree view not working.
=> AttachToProcessDialog fix.

main/src/addins/MacPlatform/MainToolbar/MainToolbar.cs
When the NSPopover appeared MainToolbar was receiving a NSWindowDidResizeNotification for the NSPopover, but it was causing the NSTrackingAreas in the StatusBar to be regenerated. This could cause a race condition when the old tracking area was
removed and the mouse exited the area before the new tracking area was installed.
Fixed the race condition by Only processing the NSWindowDidResizeNotification whenever it was the window that the statusbar was contained in.
=> [MacPlatform] Stop statusbar's popovers not going away

main/src/addins/MacPlatform/MainToolbar/StatusBar.cs
When showing a status icon use RepositionStatusLayers instead of repeating the positioning code which didn't handle the case when there was a build result
Fixes BXC #33230
=> [MacPlatform] Status icons can overlap with the build results

main/build/MacOSX/Info.plist.in
Registering the UTIs for .cs and .fs files and marking them as conforming to public.source-code allows QuickLook to display the files as text when you press <space>
Once installed newly created .cs files will be registered as being of the UTI com.microsoft.c-sharp, old files will still
be registered with their old dynamic type.
You can check a file's UTI with:
> mdls file.cs
which will give
kMDItemContentTypeTree         = (
"com.microsoft.c-sharp",
"public.source-code",
"public.plain-text",
"public.text",
"public.data",
"public.item",
"public.content"
)
To register an existing .cs file as being of UTI com.microsoft.c-sharp you need to run mdimport
> mdimport file.cs
It is possible to wildcard this and use find to run it on all .cs files in the system. I don't know if not updating …
=> [Mac] Register UTIs for .cs and .fs files

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/ProgressMonitors.cs
If BringToFront=true and LocalsPad(or any other Pad) shares same space as "Application Output" it's always hidden by "Application Output" when debugging starts which can be very annoying
At first I thought there is bug in Layout switching which forgets which pad was displayed/selected last and only later realised that "Application Output" is always throwing itself in front of LocalsPad or other pads...
So every time that I restart debugging I have to switch back to LocalsPad...
If user likes watching Application Output... no problem he can always switch to it... and it will stay in front in next debug session...(aka same behaviour as now unless he changes to some other pad)...
/cc @slluis
=> [Ide] Disabling BringToFront for "Application Output" pad

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/GtkTreeModelResult.cs, main/tests/UserInterfaceTests/Controllers/SolutionExplorerController.cs
It is needed for scenarios like SolutionTree because the children rows are not made available for the first time unless the row is expanded.
Also update SolutionExplorerController to fully utilize this fix
=> [AutoTest] Expand the row in TreeView when it is selected

main/src/addins/MacPlatform/MacPlatform.cs
This patch removes the use of Carbon for ApplicationEvents in MacPlatform
Requires https://github.com/mono/xwt/pull/532 - I'll update this PR if/when that gets merged
[Doesn't remove the use of Carbon in mdmonitor as it uses a symlink to the ApplicationEvents file)
=> [MacPlatform] Don't use Carbon for application events

main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/RefactoringService.cs
propagation operator"
The default button was wrong because one button got removed. That
caused the dialog not to appear on windows.
=> Fixed "Bug 33065 - Dangerous: refactoring operations drop the null

main/src/core/Mono.Texteditor/Mono.TextEditor/Gui/GtkWorkarounds.cs
Clicking on the unit test margin was passing a null event to a method that was not expecting one.
=> [Core] Fix a NRE exception when opening the unit test margin menu

main/tests/UserInterfaceTests/UserInterfaceTests.csproj
As per 6e7f2dfcbc80271fdebdee5418b5ed80fe046086, "nuget restore" should not be called in xbuilds in Tarball builds (due to missing NuGet.exe bundle)
=> Make "NuGet.exe restore" conditional on git.

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestClientSession.cs
This module doesn't load on mac and only adds annoying warnings to Ide log
cc @iainx
=> [AutoTest] Remove loading of gail:atk-bridge

main/tests/UserInterfaceTests/UITestBase.cs
The name of the test is used to create the log file path, if a forward slash is present, the path gets corrupted. This change removes forward slash from test name when creating the IDE log path during test setup.
=> [UITest] Remove forward slashes from Ide log path during test setup

main/src/addins/NUnit/Services/NUnitAssemblyTestSuite.cs
Fixes tests that have spaces inside the function name such as :-
```
[<Test>]
member this.``Formats forall2 tooltip right aligned``() =
XS shows this error :-
NUnit-Console version 2.6.4.14350
Copyright (C) 2002-2012 Charlie Poole.
Copyright (C) 2002-2004 James W. Newkirk, Michael C. Two, Alexei A. Vorontsov.
Copyright (C) 2000-2002 Philip Craig.
All Rights Reserved.
Runtime Environment - 
OS Version: Unix 14.3.0.0
CLR Version: 4.0.30319.17020 ( Mono 4.0 ( 4.2.1 (explicit/9871c89 Wed Sep  2
17:21:48 EDT 2015) ) )
File type not known: forall2
```
=> Handle spaces in F# test names

main/src/addins/MacPlatform/Dialogs/MacAddFileDialogHandler.cs
Bug 33897 - Add Files operation stopped working in 5.9.5 / Mac OS X
10.11
=> [Mac] Fix NRE with accessory view on El Capitan

.gitmodules
Reverts mono/monodevelop#1037
Looks like this commit doesn't fix the bug.
=> Revert "[FSharp] Bump fsharpbinding submodule to fix #31456"

main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Projects/ProjectFileDescriptor.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.PropertyGrid/PropertyGrid.cs
Refresh the propertygrid on projectfile property changes.
Bug 33629 - Property grid should refresh when build action changed
=> [DesignerSupport] Update PropertyGrid on ProjectFile property changes.

main/tests/UserInterfaceTests/UITestBase.cs
When running ui tests on windows via wrench, some git files can't be cleaned up until mdtool exits. Handle the unauthorized exception to avoid test failure. Wrench will clean up the rest
=> [AutoTest] handle unauthorized exception in OnCleanUp ()

main/tests/UserInterfaceTests/UITestBase.cs
=> [AutoTest] make testpath and log name shorter

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestSession.cs
When calling GetGlobalValue check that each object in the name exists before descending further.
Fixes BXC #30853
=> [Autotest] Check the object exists before trying to get its properties

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
Add a check that a previously dispatched command has completed before dispatching a new one.
Most commands finish quickly, but those that open modal dialogs do not, and so it was possible to open multiple "Close without saving" dialogs by repeatedly pressing Ctrl-W on a dirty file or to cut/copy/paste while the dialog was open by Ctrl-W and then Ctrl-X
Fixes BXC #29519 - Multiple copies of the same modal dialog can be made visible at the same time
=> [Components] Prevent simultaneous command dispatches

main/tests/UserInterfaceTests/Ide.cs, main/tests/UserInterfaceTests/UITestBase.cs, main/tests/UserInterfaceTests/VersionControlTests/Git/GitStashManagerTests.cs
There are times when we are not sure if "Packages Added" or
"Project Saved" would end up showing on the status bar as there
is no defined order. This method can be used in tests to make
sure that out tests don't fail just because we can't predict
the order of status message
Also check for Xamarin Update open in a different line checking
first if it is not null to avoid NRE
Also update WaitForTextArea in git tests to give it 20 seconds
instead of standard 5 seconds for the project to be opened
=> [UITest] Added WaitForPackageUpdateOrSaved for NuGetAdded or Project Saved

main/tests/UserInterfaceTests/CreateBuildTemplatesTestBase.cs, main/tests/UserInterfaceTests/TemplateTestOptions.cs
Android Wear takes way more time, so hardcoding time for all templates of one Category is not a sensible way to go. The timeout should be associated with each template
=> [UITest] Add BuildTimeout in ProjectDetails as some templates take more time to build than others

main/tests/UserInterfaceTests/CreateBuildTemplatesTestBase.cs, main/tests/UserInterfaceTests/UITestBase.cs, main/tests/UserInterfaceTests/Util.cs
This creates a log file specific for the current test in the TestResults folder. It is registered with the LoggingService so any log entry will go to the log (usually errors which will be useful). 
The ReproStep method allows entries to the log that we can later parse to create bug report repro steps. The log looks something like this:
```
INFO[2015-09-24 15:09:13Z]: @Repro-Step-01: Create a new project
INFO[2015-09-24 15:09:13Z]: @Repro-Info-01: CategoryRoot=Other, Category=.NET, TemplateKindRoot=General, TemplateKind=Console Project
INFO[2015-09-24 15:09:13Z]: @Repro-Info-01: ProjectName=ConsoleProject, SolutionName=ConsoleProject, SolutionLocation=/Users/kylewhite/Workspace/monodevelop/main/build/tests/wrveibzd.8xy, ProjectInSolution=True, AddProjectToExistingSolution=False …
```
=> [UITest] Implement test log file and ReproStep method

main/tests/UserInterfaceTests/Util.cs
It now removes most invalid characters rather than only slashes. 
cc: @Therzok, since you pointed out it should be dashes
=> [UITest] Enhanced ToPathSafeString utility method

main/tests/UserInterfaceTests/Controllers/OptionsController.cs
The locator for SelectPane in the OptionsController only worked on Mac, with this change it will work on both platforms.
CC: @manish
=> [UITest] Updated locator for SelectPane

main/tests/UserInterfaceTests/DialogTests/NuGetDialogTests.cs, main/tests/UserInterfaceTests/Ide.cs, main/tests/UserInterfaceTests/UITestBase.cs, main/tests/UserInterfaceTests/VersionControlTests/Git/GitRepositoryConfigurationTests.cs, main/tests/UserInterfaceTests/VersionControlTests/Git/GitTests.cs
**[UITest] For UITest FileLogger use the testname as the logger**
This change is required because there are times when the test fails where XS crashes and doesn't get time for the logger to be cleaned up. Having different logger names for different tests would give other tests a chance to continue
---
**[UITest] WaitForIdeIdle does not unblock on specific messages. Extra messages can be added**
There are situations where the operation takes more than poll time and the method unblocks. Examples of such messages as "Solution loading..." or "Updatinng packages in solution..." etc. The method now also takes an optional argument to add more messages to block on if needed
------
**[UITest] Fix NuGet and Git tests by fixing timeouts and using gtk-sharp repo to clone**
=> FileLogger: use the testname as the logger, WaitForIdeIdle keeps blocked on certain messages

.gitignore, main/build/MacOSX/Makefile.am, main/build/MacOSX/monostub-test.m, main/build/MacOSX/monostub-utils.h, main/build/MacOSX/monostub.m
Added unit tests that will fail CI builds when these tests fail. If
this fails, you won't be able to run MonoDevelop on Mac anyway. :P
More importantly, I changed `push_env` so it takes into account other
parts that the beginning of the environment variable string. Now it
will check whether the path components are not the first component, the
path variable will no longer be updated.
`push_env` also now takes only a path component, so pieces need to be
added manually, or you need to `strsep(&value, ":")` before appending.
=> [Mac] Improved monostub and added unit tests!

main/tests/UserInterfaceTests/UITestBase.cs, main/tests/UserInterfaceTests/VersionControlTests/Git/GitBase.cs, main/tests/UserInterfaceTests/VersionControlTests/VCSBase.cs
In this change, copy the MonoDevelopProperties.xml from default location to test folder, set `MonoDevelop.Ide.AddinUpdater.CheckForUpdates` to `false` and pass this location as `MONODEVELOP_PROFILE`.
Additionally remove the Update Dialog waiting code as it is no longer needed
=> [UITest] Copy MonoDevelopProperties.xml to test profile and disable updater

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.DockNotebook/DockNotebook.cs
Fix a typo that was setting the instance variable rather than the property when selecting a new tab
Fixes BXC #34640
=> [IDE] Switch tabs when selecting from the drop down

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/GtkTreeModelResult.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/GtkWidgetResult.cs
This patch adds two things
* calling `Model ()` many times so that we can select a row based on multiple values
* Use GtkTreeModelResult.Toggle to set true/false for bool entries, this is useful for embedded checkboxes in the TreeView rows.
=> [AutoTest] Allow selecting row based on different models and Allow Toggling of embedded CheckBox in TreeView

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.Formats.MSBuild/SlnFileFormat.cs
Fixes bug #34575 - Saving a solution to a different filesystem than where
temporary files are written causes IOException
=> Fix solution save issue

main/src/addins/MacPlatform/Dialogs/MacSelectFileDialogHandler.cs
When no key window is focused, key window is null. Try routing back to
MainWindow is no KeyWindow is present.
Bug 34979 - Crash when uploading DYSM to Insights While Publishing to
App Store via Archive
=> [Mac] Prevent a NRE when no key window is focused.

main/src/core/MonoDevelop.Ide/MonoDevelop.Components/ContextMenuExtensionsMac.cs
Don't factor the titlebar height into the context menu
position when we're in fullscreen mode.
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=35172
This is already in `master`, this PR is to merge into `cycle6`
=> [Mac] Fix context menu position when app is fullscreen

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/StatusProgressMonitor.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.ProgressMonitoring/MessageDialogProgressMonitor.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.ProgressMonitoring/MultiTaskDialogProgressMonitor.cs
Excerpt of stacktrace
at MonoDevelop.Core.ProgressMonitor.ReportProgressChanged () [0x0000b]
in
/Users/builder/data/lanes/1507/4b7bd82d/source/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Core/ProgressMonitor.cs:635
at MonoDevelop.Core.ProgressMonitor/<Step>c__AnonStorey2.<>m__0
(object) [0x00017] in
/Users/builder/data/lanes/1507/4b7bd82d/source/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Core/ProgressMonitor.cs:287
at
MonoDevelop.Ide.Gui.GtkSynchronizationContext/<Post>c__AnonStorey0.<>m__0
() [0x00000] in
/Users/builder/data/lanes/1507/4b7bd82d/source/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/GtkSynchronizationContext.cs:36
at MonoDevelop.Ide.DispatchService/<GuiDispatch>c__AnonStorey1.<>m__0
() [0x00000] in …
=> [Ide] Fix infinite recursion on progress monitor progress reports

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbarController.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/RootWorkspace.cs
Bug 23889 - iOS device selection is not remembered after switching startup projects.
=> [Ide] Fix startup items not remembering device selection

main/build/MacOSX/Makefile.am
Building on OS-X with Mono 4.2.x that no longer sym-links a `gmcs` causes:
When bundling app on OS-X (with Mono 4.2.x that no longer sym-links a `gmcs`) results in:
```
pushd main/build/MacOSX
./make-dmg-bundle.sh
Building bundle for MonoDevelop 5.11.0.384...
Creating disk image (122MB)...
Attaching to disk image...
Populating image...
Cannot open assembly 'render.exe': No such file or directory.
mv: rename dmg-bg-with-version.png to MonoDevelop.mounted/.background/dmg-bg.png: No such file or directory
Detaching from disk image...
Creating distributable image...
Built disk image MonoDevelop-5.11.0.384.dmg
```
The root-cause of error via 'make render.exe'
```
pushd main/build/MacOSX
make render.exe
gmcs -r:System.Drawing render.cs
make: gmcs: No such file or directory
make: *** …
```
=> Build fix for main/build/MacOSX/render.exe as gmcs no longer exists

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Tasks/UserTasksView.cs
Fixed [bug #36027](https://bugzilla.xamarin.com/show_bug.cgi?id=36027) - Task Pad can no longer be sorted by the "completed" checkbox column
=> [Ide] Allow sorting by completed column in Task Pad.

main/src/addins/NUnit/Gui/TestResultsPad.cs
Fixed bug #35105 - Test Results pad status bar has overlapping views
https://bugzilla.xamarin.com/show_bug.cgi?id=35105
The status bar of the Test Results pad would sometimes show the same
test result information twice. This could cause the text to overlap
itself if the Test Results pad did not have enough room. The simplest
way to reproduce this is to start Xamarin Studio, open a project,
open the Test Results pad and dock it, then close the solution and
re-open it again. The test result text in the status bar is shown
twice and may overlap itself if the width of the Test Result window
is not wide enough.
Now the duplicate text is no longer shown. Also the progress bar is
hidden when the Test Results pad is first created since the progress
bar is shown when running a test and then hidden …
=> [NUnit] Fix duplicate test result text in Test Results status bar.

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DisplayBindingService.cs
This allows display bindings to be registered at runtime.  This is useful when an extension (like the Protobuild add-in I'm developing) needs to add and remove display bindings as it becomes aware of more supported extensions.
In the Protobuild add-in, we support having projects in the solution provide IDE editors, and we load the compiled assemblies into an AppDomain or GtkPlug/Socket/separate process to allow developers to provide additional editors for the content of their own project.
=> [roslyn branch] Allow display bindings to be registered at runtime

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Solution.cs
In the Protobuild add-in that I am writing, I need Protobuild modules to be derived from Solution.  Not only is this because Solution is the hard coded class that is used everywhere, but because Protobuild modules actually directly map to solutions.
Protobuild is a cross-platform project generator, and for each Protobuild module, it produces a solution file on disk (for the desired platform).  The add-in reads Protobuild modules directly, invokes the project generation, and then loads the real .NET solutions in the background, passing through all of the relevant calls from the module class through to the loaded solution.  When the user changes the active platform (Windows, Mac, Linux, iOS, Android, etc) in the IDE, Protobuild re-generates the solution and project files for the new …
=> [roslyn branch] Unseal Solution class

main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeActionEditorExtension.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components/ContextMenu.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components/ContextMenuExtensionsMac.cs
Use the ContextMenu object to share the Mac/Gtk code instead of creating yet another custom popup menu system
=> [MonoDevelop.Refactoring] Use MonoDevelop.Components.ContextMenu

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.Policies/PolicyService.cs
=> [Core] Use a default name for imported policies if none given.

main/src/core/MonoDevelop.Ide/gtkrc.mac
This fixes a regression caused by https://github.com/mono/xamarin-gtk-theme/commit/33ef875d70716b2a6fc210d9e4a9f6e2177ed6e6, which fixes the way the engine draws the text on buttons (required for https://github.com/mono/monodevelop/tree/dark-skin/ support). Previously the engine did not honor the Gtk state colors and our gtkrc did not declare them for option-/checkboxes.
Patched theme engine only:
Fixed Gtkrc for Mac:
=> [Ide][Mac] Fix checkbox style

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/SearchPopupWindow.cs
Fixed bug #29879 - Crash if I type in search box
https://bugzilla.xamarin.com/show_bug.cgi?id=29879
If a search category throws an exception when its ItemCount is called
then this can cause the IDE to terminate. One way to reproduce this
with Xamarin Studio 5.10 or later is to install an old version of the
NuGet extensions addin, version 0.10 or earlier, then attempt to use
the global search in the top right of the IDE. This was causing an
exception to be thrown in the SearchPopupWindow's OnDrawContent
method when it tried to use the ItemCount property. This then
terminated the IDE.
Now a search category that throws an exception is removed from the
list of results so the OnDrawContent method never uses a badly
behaving search category.
=> [Ide] Fix crash in global search popup window.

main/src/addins/NUnit/Gui/AbstractUnitTestEditorExtension.cs
Use the ContextMenu for the NUnit gutter menus so that the correct platform menus are used
Fixes BXC #34997
=> [NUnit] Use ContextMenu for NUnit gutter menus

main/src/core/Mono.Texteditor/Mono.TextEditor/TextEditorOptions.cs
The TextEditorOptions StaticZoomChanged static event handler was
keeping each TextEditor instance alive even after they were closed.
This was also causing the project to be kept alive since the
TextEditor's PolicyBag references the project. The TextEditorFactory
creates a new TextEditor and then adds an anonymous delegate to the
TextEditor's ZoomLevelChanged event. This delegate references the
original TextEditor. The ZoomLevelChanged event maps to the
TextEditorOptions ZoomLevelChanged event which adds the delegate
to the static event. The static event then references the original
TextEditor and keeps it alive until the IDE is closed.
Making the ZoomLevelChanged event not directly reference the static
event fixes the problem since there is only an instance event handler
pointing to the …
=> [TextEditor] Fix memory leak.

main/src/addins/MacPlatform/MacPlatform.cs
Check if a Gtk window that is marked as modal is also visible before returning True for an active modal window.
=> [MacPlatform] Check that a modal dialog is visible

main/src/core/MonoDevelop.Core/MonoDevelop.Core/FilePath.cs
Fixed bug #36432 - Cannot create new project c# console
https://bugzilla.xamarin.com/show_bug.cgi?id=36432
From the New Project dialog it was not possible to create a
project inside a directory that contained a '#' or a '%' even though
these are valid.
=> [Core] Allow # and % characters in file names.

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MetadataReferenceCache.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/RootWorkspace.cs
The metadata reference cache is now cleared when the last workspace item is closed. If the workspace is being reloaded, for example if the solution file has changed outside the IDE, then the cache is not cleared since the metadata will be re-used when the projects are loaded again.
=> [Ide] Clear metadata reference cache when workspace is closed.

main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/BlameWidget.cs
Introduces a menuAnnotation that keeps track of what line was clicked
at the time of showing the context menu.
Fixes unreliable command activation just to LeaveNotify events
happening too early when moving over the context menu.
=> [VCS] Fix Blame commands not reliably working

main/build/MacOSX/monostub-test.m, main/build/MacOSX/monostub-utils.h
DYLD_FALLBACK_LIBRARY_PATH was being reversed, so /usr/local/lib was moving to the front of the variable and taking precedence over the Mono framework directory.
If the user had an invalid/64bit incompatible version of a library in /usr/local/lib then we would crash.
=> [Monostub] Don't reverse the order of DYLD_FALLBACK_LIBRARY_PATH

main/src/addins/TextTemplating/Mono.TextTemplating/Mono.TextTemplating/CompiledTemplate.cs
This is a continuation of the discussion at #1166.  The problem with the code in master is that it will only find assemblies directly referenced by the template, not assemblies that those assemblies themselves reference.  This change adds `host.ResolveAssemblyReference()` as a fallback step after checking the reference assemblies listed in `assemblyFiles`, so that these 'second-step' dependencies can be found in the same directory as directly-referenced assemblies.
@slluis @mhutch @mrward
=> Added host.ResolveAssemblyReference() as a fallback for resolving assemblies not found in the directly-referenced assembly list

main/src/addins/MacPlatform/MacPlatform.cs
Instead of playing whack-a-mole everytime a new version of OSX adds a new magic window that breaks our modal window detection, this change makes a blacklist of windows we know are modal.
Currently we only need to blacklist NSOpenPanel and NSSavePanel. If other window types are added to the code, they should be added to this list.
Also check that a modal GtkWindow is also visible.
Fixes BXC #35465
Fixes BXC #34250
=> [MacPlatform] Move the Modal window detection from a whitelist to a blacklist

main/src/addins/MonoDevelop.WebReferences/MonoDevelop.WebReferences.WS/WebServiceDiscoveryResultWS.cs
Fixed bug #36276 - No Event Args or Event Handlers created in Web
References
https://bugzilla.xamarin.com/show_bug.cgi?id=36276
Adding a '.NET 2.0 Web Services' web reference was not generating
Async methods and events with Mono 4.2.1. With Mono 4.2 they were
being generated.
Changed the code generator options to use GenerateNewAsync which will
generate the Async methods and events for a web reference.
=> [WebReferences] Generate events for a web reference.

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/SearchResultWidget.cs
Now it looks all nice and sorted instead of random:
=> [Ide] When sorting SearchResultWidget by FileName also take "line" number into account

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Tasks/UserTasksView.cs
The path from the various editing args is relative to the sorted model, so we need to convert it to the unsorted model before accessing the data
Fixes BXC #36056
=> [IDE] Use the unsorted path to edit the model

main/src/addins/VersionControl/MonoDevelop.VersionControl.Git.Tests/BaseGitRepositoryTests.cs, main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
Bug 34236 - Commits reordered when rebasing
=> [Git] Fix rebase reordering commits.

main/src/core/MonoDevelop.Ide/AssemblyInfo.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/DesktopService.cs, main/src/tools/mdtool/mdtool.csproj, main/src/tools/mdtool/src/mdtool.cs
e.g. for mimetype lookup
Kinda hacky fix and for some reason we still end up with
FATAL ERROR [2015-12-15 20:54:24Z]: A platform service implementation has not been found.
but it works well enough for update-po.
=> [mdtool] Fix tools that depend on PlatformService

main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/PropertyPadVisitor.cs
Bug 33626 - [Regression] Auto-hidden property pad can't be used with
solution tree
=> [PropertyPad] Ignore autohide boxes from the command target visitor

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/ImportSymbolCompletionData.cs, main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/RoslynCodeCompletionFactory.cs, main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/RoslynSymbolCompletionData.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/CompletionData.cs
Fan fact: not roslyn specific bug
Basically fix is to replace text behind cursor only in case of Enter and Tab keys...
=> Bug 37248 - Roslyn: typing "<" after IEnumerable deletes the text in front of it.

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProjectExtension.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
which returns only projects which output is actually referenced
=> [Core] Introducing DotNetProject.GetReferencedAssemblyProject

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
So bug was if user started Rebuild/Build or any other long operation(also debugging and if he didn't use IDE and app terminated) that took more then 30sec and didn't interact with IDE UpdateStatus last operation would still be Stop(still building), because we stopped updating status bar after 30sec of no user interaction...
We had HandleWinMotionNotificationEvent which would update on user interaction but for some reason that event triggers few seconds after mouse is moved and only reacts to moves in GTK area(not in Mac StatusBar) plus it forces user to move mouse(if he switched to app with Alt+Tab) and always takes me few moments to realise build actually finished based on status bar and I have to move mouse to update stop/run icon
This is fixed by using win.FocusInEvent so when user …
=> [Ide] Improved updating of StatusBar after long status bar changing operation(mostly Rebuild)

main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs
Fixes issue with text view showing garbage characters (file loaded with wrong encoding) when using "Save As" and saving to a different encoding than the current view is using.
Repro steps on Windows:
1. Open UTF-8 encoded file.
2. Use "Save As" to save with new filename and select UTF-16 encoding (Default for me)
3. File is reloaded as UTF8 instead of UTF-16.
=>  [source-editor] Set encoding of view to encoding used for writing.

main/src/addins/MacPlatform/MainToolbar/AwesomeBar.cs
Use HitTest to check that we're double clicking inside the toolbar and not its children
=> [MacPlatform] Don't zoom when double clicking on the widgets in the toolbar

main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/ItemToolboxNode.cs, main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/ToolboxWidget.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Styles.cs
This property allows one to set the origin of an element in a toolbox (e.g. from which assembly, library, file the item comes from).
Originating from comments in the other PR: https://github.com/mono/monodevelop/pull/1228
=> Add Source property to ItemToolboxNode and render it in ToolboxWidget.

main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/TargetRuntime.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
Fix is made from two parts...
1st part(TargetRuntime.cs) is fixing method FindFacadeAssembliesForPCL for MonoDroid frameworks since instead of having Facades in every framework folder it only has in v1.0 folder which is hardcoded in [.targets file](https://github.com/xamarin/monodroid/blob/200ed2f87bdc0933338c623aa32b4b868859870f/tools/msbuild/Xamarin.Android.Common.targets#L547)...
2nd part(MonoDevelopWorkspace.cs) is fixing logic to also check if project reference includes Portable projects...
=> Bug 36857 - [Roslyn] False positive errors referencing PCL project

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.Policies/PolicyService.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/DefaultPolicyOptionsDialog.cs
Bug 10612 - Policies stored in file matching localized name, not ID
=> [Ide] Store policies using the ID not the name.

main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SearchAndReplaceWidget.cs
When changing the history, we would completely delete the old entry, making it almost impossible to get a search term added to the Recent Searches menu
Fixes BXC #35928
=> [SourceEditor] Don't delete the history while changing the test

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Refactoring/CSharpFeaturesTextEditorExtension.cs, main/src/addins/CSharpBinding/MonoDevelop.CSharp.Refactoring/ExtractMethodCommandHandler.cs, main/src/addins/CSharpBinding/MonoDevelop.CSharp.Refactoring/RefactoryCommands.cs, main/src/addins/CSharpBinding/MonoDevelop.CSharp.Refactoring/RenameHandler.cs, main/src/addins/MonoDevelop.GtkCore/MonoDevelop.GtkCore.GuiBuilder/ActionGroupView.cs, main/src/addins/MonoDevelop.GtkCore/MonoDevelop.GtkCore.GuiBuilder/CodeBinder.cs, main/src/addins/MonoDevelop.GtkCore/MonoDevelop.GtkCore.GuiBuilder/GuiBuilderView.cs, main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeActionEditorExtension.cs, main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Rename/RenameItemDialog.cs, main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Rename/RenameRefactoring.cs, main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/RefactoringSymbolInfo.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/MessageService.cs
This change should be reviewed by looking at commits separately...
* [Make all Renaming operations use Tasks/async/await instead of .Result](https://github.com/mono/monodevelop/commit/b00fa0bad2cea82dfd8991f17035deae1ed36eed)
* This one is pretty straight forward, just introduce async Task to Rename method and propagate Task all the way back to events
* [[Refactoring] Changed GetSymbolInfoAsync to run on thread pool](https://github.com/mono/monodevelop/commit/4fea349627a50fc1c6efe98bcc3b602cbe68d6c9)
* @mkrueger What do you think about this commit? I think this is best way to handle getting symbol info...
* [[Ide] Introduced MessageService.ExecuteTaskAndShowWaitDialog](https://github.com/mono/monodevelop/commit/db3dc0e6edfd56a9653e4690d38dc381bac90c0a)
* @slluis and anyone else …
=> Async renaming

main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/MonoTargetRuntime.cs
Reason why this check was added was to speedup boot time of IDE so it doesn't load all custom frameworks... But based on my testing it appears different runtimes are loaded as needed so there is no reason for this check anymore...
=> [Core] Load global xbuild-frameworks also for other runtimes then currently running

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
Make setter for CurrentSelectedWorkspaceItem, CurrentSelectedSoutionItem & CurrentSelectedItem public. Allows to set active solution and project without solution pad.
We are at Unity working a on new integration for MonoDevelop and we do not show the solution pad, however we do create an in-memory only solution. In order to be able to debug, build and perform other project operations, the solution must be set on the ProjectOperations. However, it is currently internal and only set when the solution pad is shown and the solution is selected through the solution pad tree view.
This change allows us to set the solution without having to visually show the solution pad first. If there is a better solution this to this problem, I would happily submit a new PR with any suggestions.
=> Make ProjectOperations setters public.

main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/IToolboxLoader.cs, main/src/addins/NUnit/Services/NUnitAssemblyTestSuite.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Core.Execution/MultipleOperationConsoles.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Core.Execution/ProcessHostController.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Core.Execution/ProcessService.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Core.Logging/AssertLoggingTraceListener.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj
Also reduced number of CreateExternalProcessObject overloads(removed unused)
Before this change it was impossible(afaik) to use tracepoints or Debug.WriteLine in unit tests...
=> [NUnit+Core] Debug.WriteLine and tracepoints now work when debugging unit test

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Project/CSharpProjectExtension.cs, main/src/addins/VBNetBinding/Project/VBProjectExtension.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
Currently only projects that have a type guid for C# or VB.NET are added to the type system. This is currently hard coded.
Now a project can indicate that it supports the type system. This allows other projects, such as DNX projects, which have a different type guid, to be supported by the type system and code completion will then work for C# files in these projects.
This is a rework of commit: a49d6220af5f369dcc243dde21c018b20755a846
=> [Ide] Allow other project types to be supported by the type system.

main/src/core/MonoDevelop.Core/MonoDevelop.Core.Web/RequestHelper.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Core/WebRequestHelper.cs
Instead of just passing the synchronous GetResponse to Task.Factory.StartNew, use the async version of all the functions instead
Fixes BXC #37284
=> [Core] Make WebRequestHelper.GetResponseAsync actually async

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Parser/TypeSystemProvider.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs
Reasoning here is this, user experience with 600ms delay is suffering mostly noticeable is SemanticHighlighting but also other stuff that is executed based on DocumentChanged with 600ms delay which is not ideal...
Second reasoning why this is acceptable is... It's parser job to cancel parsing based on CancellationToken and not abuse ThreadPool/CPU... If this change is problem... Parser should be reviewed to cancel faster...
@mkrueger Can you review this?
Changes in CSharpBinding/MonoDevelop.CSharp.Parser/TypeSystemProvider.cs:
* It's my understanding C# files are not Serialisable anymore, correct? Hence removed logic excluding them from `ParsedDocumentFlags.NotSerializable` based on IsCompileBuildAction... Instead making them `ParsedDocumentFlags.NotSerializable` always...
* I wrapped …
=> [Ide] Removed 600ms delay from StartReparseThread + few code cleanups

main/src/addins/NUnit/Gui/TestNodeBuilder.cs
This was needed to fix the rendering of F# test cases. Somewhere deep
inside nunit.core, the test name was being converted from something
like
`TestName("param1", "param2")`
to
`TestName<String>("param1", "param2")`
This was causing havoc in the Test pad.
=> [NUnit] Removes markup from test names

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextEditorViewContent.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/SdiWorkspaceWindow.cs
So problem was that I implemented xml comments via command on BaseXmlExtension class but that was considered after more generic implementation inside TextEditorViewContent, with this change extensions are considered before TextEditorViewContent allowing extension to implement more specific implementations then generic ones in TextEditorViewContent
After looking at this problem for some time and at CommandManager.cs...
IMHO, ideally instead of IMultiCastCommandRouter, IMultiCastCommandRouter, ICommandDelegator, ICommandDelegatorRouter, ICommandRouter.
We should just have:
```
interface IAfterCommandTarget
{
object GetAfterCommandTarget();
}
interface IAfterCommandTargets
{
IEnumerable GetAfterCommandTargets();
}
interface IBeforeCommandTarget
{
object GetBeforeCommandTarget();
}
interface …
```
=> Bug 37958 - XS 6 Preview Toggle Line Comments no longer work in XAML/XML files

main/src/addins/MacPlatform/MainToolbar/SelectorView.cs
Not sure if this the right way to do things, but this is the only way in which UITest can actually set configurations.
Without this patch, only the UI is updated since the UITest was just setting `ActiveConfiguration` property, but this change was not propagated all along.
I used `ConfigurationChanged (this, EventArgs.Empty)` since I noticed that `(object o, EventArgs e)` were not being used anywhere
=> Moved ConfigurationChanged and UpdatePathText inside ActiveConfiguration.set

main/src/addins/MacPlatform/MainToolbar/RunButton.cs
GtkWorkarounds.GetScaleFactor() returns the scale factor for the default screen, not the current screen so our Run button icons were using the wrong scale factor if you were running on a retina laptop but displaying on a non-retina screen. Use the MultiResImage helper to load dual res NSImages
=> [MacToolbar] GtkWorkarounds.GetScaleFactor() considered harmful

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/DockGroup.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/DockItemTitleTab.cs
The EditingLayout.xml in bug 32385 contains NaN for certain widths which caused 1 warning and 1 assertion.
Protect against both by checking for NaN before proceeding, and limiting widths to >= 1
Fixes BXC #32385
=> [Components] Protect against NaN in the Dock layout file

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/DockItemTitleTab.cs
Stop the pad label overlapping the icon when there's not enough space allocated for the whole tab.
Returns to the pre-dark skin behaviour of cropping the label.
Fixes BXC#38011
=> [IDE] Don't let pad label overlap icon

main/src/addins/MacPlatform/MainToolbar/StatusBar.cs
set.
Bug 32972 - [Roslyn] Crash in Mac toolbar
Bug 34719 - [Roslyn] XS Crashes after NRE in
MainToolbar.StatusBar.ShowPopoverForLayer
Thanks @iainx <3
=> [Mac] Fix crasher in toolbar when a tooltip for a status layer wasn't

main/src/addins/MacPlatform/MainToolbar/SelectorView.cs
If the runtime or configuration names are > 50 chars long ellipsize them so that the selector doesn't switch immediately to minimode
Fixes BXC 39018
=> [MacToolbar] Ellipsize text if the string is very long

main/src/addins/MacPlatform/MainToolbar/SelectorView.cs
If the runtime or configuration names are > 50 chars long ellipsize them so that the selector doesn't switch immediately to minimode
Fixes BXC 39018
=> [MacToolbar] Ellipsize text if the string is very long [c7]

main/src/addins/MonoDevelop.UnitTesting.NUnit/MonoDevelop.UnitTesting.NUnit/NUnitAssemblyTestSuite.cs
testContext.ExecutionContext.ExecutionHandler was null when not being ran under the debugger.
=> [NUnit] - allow the tests to run without being in debug mode

main/src/addins/MacPlatform/MainToolbar/SearchBar.cs
Fixes the gettext issue with the previous patch. Also included on c7 branch
=> [MacToolbar] Correctly mark the search text for translation

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProjectService.cs
Fixed bug #36960 - Adding/Opening unsupported project shows 'Could
not load...' warning pop up.
https://bugzilla.xamarin.com/show_bug.cgi?id=36960
Do not show a warning dialog when opening a solution containing
unsupported but known project types. A warning dialog is now only
shown for unknown project types or known unsupported project types
that cannot have their files loaded into the solution window.
=> [Core] Do not show warning dialog for known unsupported projects.

main/src/addins/MonoDevelop.UnitTesting/Services/UnitTestService.cs
Fixed bug #39525 - UITests fail to run connect
https://bugzilla.xamarin.com/show_bug.cgi?id=39525
The UnitTestService fires an TestSessionStarting event just before the
test is started. The event args passed contains a TestSession. In
Xamarin Studio 5 there was a completed event on the TestSession that
could be used to indicate the test had finished. This completed event
has been replaced with a Task. At the time the TestSessionStarting
event is fired the Task is not yet started but the existing Task says
it is completed. Since the TestSession's Task is marked as completed
when the TestSessionStarting event is fired any action that uses the
Task will run straight away since the Task is already completed even
though the test has not been started yet.
To fix this the creation of the Task …
=> [UnitTesting] Fix UITest failing to connect.

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.Helpers/FakeDotNetProject.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.Helpers/FakeNuGetPackageNewImportsHandler.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.Helpers/TestableMonoDevelopProjectSystem.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.csproj, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/MonoDevelopProjectSystemTests.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.csproj, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/INuGetPackageNewImportsHandler.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/MonoDevelopProjectSystem.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/NuGetPackageNewImportsHandler.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageManagementMSBuildExtension.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildObject.cs, main/tests/UnitTests/MonoDevelop.Projects/MSBuildProjectTests.cs
Adds support to insert an Import for .props in a NuGet package at the start of the project.
Added a fix for an extra newline being inserted when MSBuildProject's AddNewImport is called passing a beforeObject which is the first item in the project. This particular [commit](https://github.com/mono/monodevelop/commit/e834096c420d5c3938402f3333d0608932ee4123) could do with being reviewed.
=> [NuGet] insert .props at top of project file

main/src/core/MonoDevelop.Ide/MonoDevelop.Components/GtkWorkarounds.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components/IdeDialog.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/OptionsDialog.cs
Improved the method of disabling minimise/maximise for dialogs, and apply it to all IdeDialog derived classes
=> [IDE] Disable minimize/maximise for dialogs on OS X

main/src/addins/Deployment/MonoDevelop.Deployment/MonoDevelop.Deployment.NodeBuilders/PackagingProjectNodeBuilder.cs, main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/AssemblyNodeBuilder.cs, main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/AssemblyReferenceFolderNodeBuilder.cs, main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/AssemblyResourceFolderNodeBuilder.cs, main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/BaseTypeFolderNodeBuilder.cs, main/src/addins/MonoDevelop.Gettext/MonoDevelop.Gettext.NodeBuilders/TranslationProjectNodeBuilder.cs, main/src/addins/MonoDevelop.GtkCore/MonoDevelop.GtkCore.NodeBuilders/WidgetNodeBuilder.cs, main/src/addins/MonoDevelop.GtkCore/MonoDevelop.GtkCore.NodeBuilders/WindowsFolderNodeBuilder.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.NodeBuilders/ProjectPackagesFolderNodeBuilder.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.NodeBuilders/ProjectReferencesFromPackagesFolderNodeBuilder.cs, main/src/addins/MonoDevelop.UnitTesting/Gui/TestNodeBuilder.cs, main/src/addins/MonoDevelop.WebReferences/MonoDevelop.WebReferences.NodeBuilders/WebReferenceFolderNodeBuilder.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ClassPad/ClassNodeBuilder.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ClassPad/CombineNodeBuilder.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ClassPad/NamespaceData.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ClassPad/ProjectNodeBuilder.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ClassPad/SolutionNodeBuilder.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/FolderNodeBuilder.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/PortableFrameworkSubsetNodeBuilder.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/ProjectFileNodeBuilder.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/ProjectReferenceFolderNodeBuilder.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/ShowAllFilesBuilderExtension.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/SolutionFolderNodeBuilder.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/SolutionNodeBuilder.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/WorkspaceNodeBuilder.cs
To be taken with a grain of salt for now. It's orthogonal with https://github.com/mono/gtk-sharp/commit/f4d4443e4eb4ee130bbf786bd1718fafab44a524 and https://github.com/mono/gtk-sharp/commit/decbc5ac25d389d474f06e57dbaa1e99ef96d26c, but combined they improve the situation a lot.
I have no idea if this causes a slowdown with the current gtk-sharp, but it shouldn't do so.
Those patches above brought down building the TreeBuilder of libgit2sharp with one open file from 2 seconds down to 1.2s. Combined with https://github.com/mono/monodevelop/commit/18bb88f6c827e470837f239cd695d6af9ec769c8, it  _further_ optimized it down to 300ms.
That said, I thought it would be a good idea to replace occurrences of AddChild with AddChildren, as AddChildren is guarded against multiple resorting. This should …
=> Treeview speedups

main/src/addins/MacPlatform/MacPlatform.cs, main/src/addins/MacPlatform/MainToolbar/StatusBar.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Core/BrandingService.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/StatusArea.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/AboutMonoDevelopTabPage.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/CommonAboutDialog.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DefaultWorkbench.cs
The BrandingService's ApplicationName is no longer readonly. If the
UpdateApplicationName method is used to update the name then the
ApplicationNameChanged event will fire. This can be used to update
any part of the UI that is showing the old application name.
Moved the default name of the dialog image to a class so it can
be updated at runtime.
=> Branding service improvements

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/RemoteProjectBuilder.cs
Fix for [#39972](https://bugzilla.xamarin.com/show_bug.cgi?id=39972)(review bug description for more details)
With `Console.WriteLine` in `RemoteProjectBuilder`'s finalizer headless builds failed with:
```
System.NotSupportedException: Stream does not support writing
at System.IO.FileStream.Write (System.Byte[] array, Int32 offset, Int32 count) [0x000a5] in /private/tmp/source-mono-4.4.0/bockbuild-mono-4.4.0-branch/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/corlib/System.IO/FileStream.cs:632
...
```
Before finalizer method was used to call `Dispose` method and it's not actual anymore since reference counter [was implemented](https://github.com/mono/monodevelop/commit/7c5dfe52cb698c4c71acf597ff9598f8104b04fe) in `RemoteProjectBuilder`.
=> [Core] Remove RemoteProjectBuilder finalizer

main/src/addins/MacPlatform/MacPlatform.cs, main/src/core/MonoDevelop.Ide/ExtensionModel/Commands.addin.xml
This is the Monodevelop part to rename the menu. The dialog window must be renamed in mono-addins.
=> [IDE] Rename Add-in Manager -> Add-ins

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextEditorViewContent.cs
This commit fixes the traversal of the editor in the command target
chain, to take into account the traversal of the editor extensions too.
The SourceEditorView does not route into the TextEditor, which is in
fact the real iterator of the text editor extensions in the chain.
Bug 39660 - Upon changing "Build Action" property grid gets reset
=> [Ide] Fix editor traversal in command target chain

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.DockNotebook/DockNotebook.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/DockFrame.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/DockGroup.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/DockObject.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DefaultWorkbench.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs
Save layouts after a short delay after they've been changed, rather than waiting until the workspace window is closed
Fixes BXC #25609
Fixes BXC #33009
=> [IDE] Save layouts when they're changed

main/src/addins/MacPlatform/MacPlatform.cs
Use the OS X theme to decide the colour of the icon in the dark, not the XS theme
@vancura, in case you think this is better suited?
=> [MacPlatform] Use the OS X theme colour to decide the dock icon colour

main/src/addins/MonoDevelop.UnitTesting/Gui/TestResultsPad.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components/GtkUtil.cs
Cell Foreground color rendering needs to be disabled
using the “foreground-set” property if the cell had
no foreground color before it has been modified
by the tooltip. Otherwise the cell will render its foreground
with the default Gdk.Color.Zero which is actually black.
=> [Ide] Fix cell foreground after tree tooltip has been shown

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/RecentOpen.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.WelcomePage/WelcomePageRecentProjectsList.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.WelcomePage/WelcomePageSection.cs
The file is inacessible if it is on a network drive that's not
connected.
Git checkout also removes the file and writes a new one causing the
project to be removed.
Bug 37122 - XS deletes solution from "recently opened" list if it is
unavailable
=> [Ide] Don't remove projects from recent projects if they can't be found

main/src/core/MonoDevelop.Ide/MonoDevelop.Components/GtkUtil.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components/SearchEntry.cs
On the Mac use the native context menus for SearchEntry
=> [Components] Use the native context menus for SearchEntry

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/EditCommands.cs
=> [IDE] Allow Cmd+A to work as standard Gtk keybinding when in floating pad

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/LicenseAcceptanceService.cs
Fixed bug #40119 - When trying to add multiple Google Play Packages
in Xamarin Studio Android Project, the dialog automatically selects
Decline
https://bugzilla.xamarin.com/show_bug.cgi?id=40119
If the license dialog was displayed when the top most window was an
auto-hide window, such as the Package Console window, then when the
auto-hide window closed the license dialog also closed without any
user input. This would cancel the install of the NuGet package since
the license was declined.
Note that the dialog's Modal property has to be set to false so the
parent window can be set. If the dialog is modal then the parent
window specified in the call to MessageService.RunCustomDialog is
ignored. The dialog is still treated as modal on the Mac and on
Windows with the Modal property set to …
=> [NuGet] Fix license dialog closing with auto-hide parent window.

main/src/addins/MacPlatform/MainToolbar/AwesomeBar.cs, main/src/addins/MacPlatform/MainToolbar/MainToolbar.cs
Listen to the superview's frame changing and adjust the layout accordingly.
Fixes BXC #40099
=> [MacToolbar] Don't cut off the searchbar when in fullscreen mode

main/src/addins/MacPlatform/MacPlatform.cs, main/src/addins/MacPlatform/MainToolbar/StatusBar.cs, main/src/addins/WindowsPlatform/WindowsPlatform/MainToolbar/StatusBar.xaml.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Core/BrandingService.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/StatusArea.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/CommonAboutDialog.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DefaultWorkbench.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeVersionInfo.cs
Fixed bug #40133 - Edition shown in places it shouldn't be
https://bugzilla.xamarin.com/show_bug.cgi?id=40133
The edition was added to the application name globally so it affected
all parts of the IDE. Now the application's edition is only shown in
the About dialog, the status area and the main window title on
Windows.
The BrandingService now has two application names - a short IDE name
(ApplicationName) and one that includes the edition
(ApplicationLongName).
The BrandingService has also been changed so that these two
application names are properties that can be set instead of fields so
the separate setter method can be removed.
Also needs an md-addins change.
=> [Cycle 7] Restrict where the edition name is used. 

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageManagementSolutionExtensions.cs
If a package version is not specified then using the aggregate
repository with the machine cache as the priority repository will
use the highest version found in the local machine cache instead
of the aggregate repository. This can result in a lower version being
installed than what is available on a remote package source.
One example of this problem is when the Google Play Services dialog
is used. This installs a Google Play Service NuGet package but does
not specify a version. If the NuGet package being installed is
found in the local machine cache then it will be used instead of
the latest from nuget.org.
=> [Cycle 7] Fix wrong NuGet package version being installed.

main/tests/Ide.Tests/ProjectTemplateTests.cs, main/tests/UnitTests/TestBase.cs, main/tests/UnitTests/UnitTests.csproj
- Fixes monodevelop hang on debian 7 (according to @akoeplinger).
- Fixes templates tests (using IDs).
- Fixes test tree pad.
=> [Test/Templates] Fix gtk-critical errors

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/BraceMatcherTextEditorExtension.cs
The brace matcher feature was broken as side effect of bug fix #39798.
=> [Ide] Fixed brace matcher extension.

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/ExtensibleTreeView.cs
Bug 37814 - Unnecessary tooltip in solution pad
=> [Ide] TreeView now takes into account different font sizes

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Extensions/MimeTypeNode.cs
This fixes files such as file.XML being considered as XML files.
Bug 4752 - Mimetype system does not recognize files with uppercased extensions
cc @mkrueger
=> [Ide] Make mimetypes ignore case when checking supported files.

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.Helpers/FakePackageManager.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.Helpers/FakePackageRepository.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.Helpers/FakeProjectManager.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/MonoDevelopPackageManagerTests.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.csproj, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/IMonoDevelopPackageManager.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/MonoDevelopPackageManager.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageReferenceMonitor.cs
Fixed bug #40178 - Cannot add certain google play packages to Android
template
https://bugzilla.xamarin.com/show_bug.cgi?id=40178
The Xamarin.Android.Support.v7.AppCompat NuGet package depends on
a single version of the Xamarin.Android.Support.v4 NuGet package.
When a Xamarin Google Play Services NuGet package is installed
that depends on a higher version of the Xamarin.Android.Support.v4
NuGet package the install would fail to find a version of the
AppCompat NuGet package that is compatible. An error similar to the
following would be displayed in the Package Console window:
Could not add Xamarin.GooglePlayServices.Ads.
Updating 'Xamarin.Android.Support.v4 23.1.1.0' to
'Xamarin.Android.Support.v4 23.1.1.1' failed. Unable to find a version
of 'Xamarin.Android.Support.v7.AppCompat' that is …
=> [Cycle7][NuGet] Fix package resolution with Google Play Services packages.

main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/RefactoringService.cs
A breaking provider no longer breaks working ones.
If a provider breaks it's removed from the provider list to prevent
flooding of the IDE log.
=> Fixed 'Bug 39397 - F# Addin Breaks Find References in C#'.

main/src/addins/MacPlatform/MainToolbar/SelectorView.cs
Bug 40293 - User should not able to change Active Configuration of running application in XS.
=> [Mac] SelectorView should only do popup when enabled.

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/SearchInSolutionSearchCategory.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/FindInFilesDialog.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/SearchProgressMonitor.cs
When the "Find in Files" dialog is being closed, the Search Result Pad disappears (if it is not docked).
Fix: Search dialog retrieves the result pad from the monitor and focuses it when the Close button has been activated.
(fixes bug #37577)
=> [Papercut][Ide] Focus Search result pad on search dialog closed

main/src/addins/MacPlatform/MacPlatform.cs
This fixes the icon size to be set correctly when run from an app bundle.
=> [C7][Mac] Don't set an app icon if inside an app bundle.

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs, main/tests/UnitTests/MonoDevelop.Projects/ProjectTests.cs
Fixed bug #39094 - Restoring NuGet packages does not update the type
system
https://bugzilla.xamarin.com/show_bug.cgi?id=39094
After a NuGet package restore sometimes on Windows the text editor
would still show errors for types that are now available due to the
restored assemblies.
When the NuGet addin refreshes the references by calling
DotNetProject.RefreshReferenceStatus the reference is removed and
added back again to the project. The changes to the references
fires events which cause the TypeSystem to ask the project for the
updated assembly information. This may cause the project to update
its MSBuildProject information in memory. If the MSBuildProject
informationis updated after the reference is removed but before the
refreshed reference is added back again the MSBuildProject …
=> [Core] Fixed restored assembly not reflected in text editor.

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs, main/tests/UnitTests/MonoDevelop.Projects/ProjectTests.cs
Fixed bug #39094 - Restoring NuGet packages does not update the type
system
https://bugzilla.xamarin.com/show_bug.cgi?id=39094
After a NuGet package restore sometimes on Windows the text editor
would still show errors for types that are now available due to the
restored assemblies.
When the NuGet addin refreshes the references by calling
DotNetProject.RefreshReferenceStatus the reference is removed and
added back again to the project. The changes to the references
fires events which cause the TypeSystem to ask the project for the
updated assembly information. This may cause the project to update
its MSBuildProject information in memory. If the MSBuildProject
informationis updated after the reference is removed but before the
refreshed reference is added back again the MSBuildProject …
=> [Cycle 7][Core] Fixed restored assembly not reflected in text editor.

main/src/addins/MacPlatform/MainToolbar/AwesomeBar.cs, main/src/addins/MacPlatform/MainToolbar/MainToolbar.cs, main/src/addins/MacPlatform/MainToolbar/RunButton.cs, main/src/addins/MacPlatform/MainToolbar/SearchBar.cs, main/src/addins/MacPlatform/MainToolbar/Styles.cs
In El Capitan, the fullscreen toolbar does not respect the VibrantDark appearance if the user has the Graphite appearance selected instead of the default Blue. These hacks colour the fullscreen toolbar the correct grey we wanted in the first place.
Fixes BXC #40160
=> [MacToolbar] Hack to work around possible Cocoa bug in El Capitan

main/src/addins/MacPlatform/MainToolbar/AwesomeBar.cs, main/src/addins/MacPlatform/MainToolbar/MainToolbar.cs, main/src/addins/MacPlatform/MainToolbar/RunButton.cs, main/src/addins/MacPlatform/MainToolbar/SearchBar.cs, main/src/addins/MacPlatform/MainToolbar/Styles.cs
In El Capitan, the fullscreen toolbar does not respect the VibrantDark appearance if the user has the Graphite appearance selected instead of the default Blue. These hacks colour the fullscreen toolbar the correct grey we wanted in the first place.
Fixes BXC #40160
=> [MacToolbar] Hack to work around possible Cocoa bug in El Capitan [c7]

main/src/core/MonoDevelop.Ide/MonoDevelop.Components/GtkUtil.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/ExtensibleTreeView.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/UnknownEntryNodeBuilder.cs
Fix disabled state colors in Solution Pad
* Load cell foreground colors from GtkTreeView style
* Different selected state colors on Mac
* Fix Gdk.Color to Hex string conversion
(fixes bug #28451)
=> [Ide][Bug 28451] Fix disabled state colors in Solution Pad [c7]

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Features/Completion/ContextHandler/DelegateCreationContextHandler.cs, main/tests/MonoDevelop.CSharpBinding.Tests/Features/CodeCompletion/NR6/MiscTests.cs
No need to add methods in the delegate context handler - the roslyn
recommender already does that for us. Must be a left over from the NR5
engine.
=> Fixed 'Bug 40413 - Incorrect number of method overloads'.

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads/ErrorListPad.cs
When getting an iter from a sorted model, the store is not guaranteed to have the same iter paths.
Use the view's treemodel to get the element to ensure same elements are being used.
Bug 40157 - [Error Pad] Inverted click when errors/warnings are sorted descending
=> [Ide] Error list pad not taking into account a sorted model.

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildPropertyCore.cs, main/tests/UnitTests/MonoDevelop.Projects/MSBuildTests.cs
If after an MSBuild target is run with a set of properties to
evaluate and a property is missing when converting that property to
a FilePath the TryGetPathValue method would throw a null reference
exception if the property was not set by the MSBuild target.
=> [Cycle 7][Core] Fix null reference when getting missing property as path.

main/src/core/MonoDevelop.Core/MonoDevelop.Core.Execution/ProcessWrapper.cs
Fixed bug [#40379](https://bugzilla.xamarin.com/show_bug.cgi?id=40379).
Avoid "System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'handle'" when calling HasExited.
=> [Core] Fix ProcessWrapper

main/src/addins/WindowsPlatform/WindowsPlatform/MainToolbar/WPFToolbar.cs
Bug 40339 - [Cycle 7] Search list is not getting close after removing the search text in search box.
=> [Windows] Send the text changed event when encountering an empty string.

main/src/addins/WindowsPlatform/WindowsPlatform/Win32.cs, main/src/addins/WindowsPlatform/WindowsPlatform/WindowsPlatform.cs
Bug 40487 - [Cycle 7] Unable to exit in "Full Screen" mode on Windows XS .
=> [Win32] Use native full screening APIs instead of Gtk ones.

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/GenericProject.cs
Fixed bug #40507 - On creating Generic project, it is showing error
in Solution pad.
https://bugzilla.xamarin.com/show_bug.cgi?id=40507
Creating a new generic project would show an error icon next to the
project in the Solution pad. The error message was 'Invalid
configuration mapping'. The generic project was created without any
configuration property group since the properties inside this group
had the default values so the entire group is removed when the project
was saved.
<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Default|AnyCPU' ">
Now the OutputPath uses a different default value so the configuration
property group is saved in the generic project. The generic project
file created now matches what is created with Xamarin Studio 5.10.
=> [Cycle 7][Core] Fix invalid configuration mapping for new generic projects.

main/src/addins/MacPlatform/MainToolbar/StatusBar.cs, main/src/addins/WindowsPlatform/WindowsPlatform/MainToolbar/StatusBar.xaml.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/StatusArea.cs
Bug 24598 - Blank solution pane and text editor is displayed on clicking 'Xamarin Studio Status' bar after close Solution.
=> [Ide] Reset the message source pad on showing a ready statusbar.

main/src/core/MonoDevelop.Ide/MonoDevelop.Components/GtkWorkarounds.cs
(fixes bug #40260)
(cherry picked from commit 4552495e3f24f16af30923ba7ab831fd5a52be9a)
=> [Ide][Win][c7] Get global key modifiers from System.Windows

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/FindInFilesDialog.cs
Added focusing the Result Pad on clicking the close button in the
window titlebar.
Removed focusing of the result pad when no results are returned.
cc @slluis @VincentDondain @sevoku
=> [Ide] FindInFilesDialog will now focus the pad in different scenarios

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads/ErrorListPad.cs
=> [Ide] Make the build log the default focus in the Errors pad

main/src/addins/MacPlatform/MainToolbar/StatusBar.cs
It seems possible that progress can go from 0 -> 1 multiple times between a BeginProgress and EndProgress call but only the first
one will be seen. Instead reset the progress bar as if a BeginProgress had been called once the fade out animation is complete
Fixes BXC #38129
=> [MacToolbar] Reset progressbar after fadeout has finished

main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/InsertionPointService.cs
Declaring references need to be checked for the filename not just for
the position -> partial classes could span accross multiple files.
=> [Refactoring] Fixed extract method bug.

main/src/core/MonoDevelop.Ide/MonoDevelop.Components/ImageLoader.cs
If a download is not yet completed, we should not trigger a completed
event when assinging the event handler.
=> [Ide] Don't trigger the Completed event on assignment.

main/src/core/Mono.Texteditor/Mono.TextEditor/Document/TextDocument.cs
is in a collapsed region in XS 6.1'
It's caused by a race - we made the loading async this seems to be a
side effect of that.
=> Fixed 'Bug 40770 - Search Result links don't display properly if code

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Navigation/FindBaseSymbolsHandler.cs, main/src/addins/CSharpBinding/MonoDevelop.CSharp.Navigation/FindDerivedSymbolsHandler.cs, main/src/addins/CSharpBinding/MonoDevelop.CSharp.Navigation/FindExtensionMethodsHandler.cs, main/src/addins/CSharpBinding/MonoDevelop.CSharp.Navigation/FindImplementingMembersHandler.cs, main/src/addins/CSharpBinding/MonoDevelop.CSharp.Navigation/FindMemberOverloadsHandler.cs, main/src/addins/CSharpBinding/MonoDevelop.CSharp.Refactoring/CSharpFeaturesTextEditorExtension.cs, main/src/addins/CSharpBinding/MonoDevelop.CSharp.Refactoring/CSharpFindReferencesProvider.cs, main/src/addins/CSharpBinding/MonoDevelop.CSharp.Refactoring/FindProjectReferenceUsagesHandler.cs, main/src/addins/CSharpBinding/MonoDevelop.CSharp.Refactoring/FindReferencesHandler.cs, main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/RefactoringService.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/FindInFilesDialog.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/SearchProgressMonitor.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/SearchResultPad.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
cc @mkrueger @slluis 
This is pretty annoying as we can do Find references of methods like Dispose or ToString and the task takes a _LOT_ of CPU and Memory to finish.
This way, we can cancel an active search and get rid of wait times / having to close XS.
Unified cancellation reporting for searchprogressmonitor and fixed an exception that happened in Go to base command.
=> Search cancellation

Makefile
Otherwise typing `make` would fail with this error:
```
$ make
if test -d ".git"; then \
git submodule sync; \
git submodule update --init --recursive || exit 1; \
fi
/bin/sh: 2: git: not found
/bin/sh: 3: git: not found
Makefile:12: recipe for target 'update_submodules' failed
make: *** [update_submodules] Error 1
```
=> [build] Bail out early if `git` is not installed

main/src/core/MonoDevelop.Core/MonoDevelop.Core/FileService.cs
Bug occurred(rename not applied to .csproj) because rename operations was executed after saving operation, that happened because rename operation was posted to UI thread to be executed later while code flow continued and started saving, most of the time rename executed before save operation because that operation is executed on thread pool via Task.Run... With avoiding Posting on UI thread if we are already on UI thread we ensure rename is always executed before we even call Task.Run for saving.
=> Bug 40543 - I renamed an AXML, and it updated everywhere but the csproj

main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.OptionPanels/MarkerPanel.cs, main/src/addins/MonoDevelop.SourceEditor2/gtk-gui/MonoDevelop.SourceEditor.OptionPanels.MarkerPanel.cs, main/src/addins/MonoDevelop.SourceEditor2/gtk-gui/gui.stetic, main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/CommonTextEditorOptions.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/ErrorHandlerTextEditorExtension.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/DefaultSourceEditorOptions.cs
This option doesn't really make any sense anymore and causes unwanted
side effects. It was used for disabeling compiler errors in older
versions.
The compiler errors are now shown as message bubbles which can be
disabled separately.
This here was now used for the on the fly errors and if that's
disabled the fix system wouldn't be usable anymore.
=> [SourceEditor] Removed UnderlineError option.

main/src/core/MonoDevelop.Ide/MonoDevelop.Components/GtkWorkarounds.cs
While debugging some gtk stuff I noticed this is no longer used. I'd like to remove this, and then the corresponding code in gtk.
=> Remove HasNSTextFieldFocus

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Project/CodeGenerationPanel.cs, main/tests/UnitTests/MonoDevelop.CSharpBinding/CSharpProjectPropertiesTests.cs, main/tests/UnitTests/UnitTests.csproj
Problem is that project model is evaluating properties and ios/mac .targets files prepend their symbols... Workaround this problem is to remove duplicates in UI so when user makes changes it doesn't write prepended symbols...
=> Bug 40910 - Duplication of Compiler Define Symbols

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AppResult.cs
There is no way to fetch the actual value of the object fetched.
This comes handy when trying to fetch a value of TreeIter
=> [AutoTest] Make sure ToString() value is also saved as property

main/src/addins/CSharpBinding/MonoDevelop.CSharp.CodeGeneration/CreateConstructorGenerator.cs, main/src/addins/CSharpBinding/MonoDevelop.CSharp.CodeGeneration/WriteLineGenerator.cs
=> Fixed 'Bug 40893 - Ctor generator doesn’t recognize C#6 get-only

main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Projects/ProjectFileDescriptor.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.PropertyGrid/PropertyGrid.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.PropertyGrid/PropertyGridTable.cs
This makes the PropertyGrid more reliable when properties updates are
also triggered from outside the property grid.
We now have 3 scenarios of updates:
* ProjectFileDescriptor, which will update the value and trigger a
refresh if no edit session is in progress.
* PropertyGridEditor internal updates through the editor.
* While having a propertygrideditor session up and someone modifies
* the
value through external means, we will now trigger a grid population on
edit session end to ensure we have the right values inside each
element.
Bug 41135 - Properties window gets blank, on changing the Build
Action from Properties window.
=> [Ide] Don't trigger edit session mangling if we have one in progress

main/src/core/MonoDevelop.Ide/ExtensionModel/MonoDevelop.Ide.addin.xml, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Extensions/IErrorDocumentationProvider.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads/ErrorListPad.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Tasks/TaskListEntry.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
`IErrorDocumentationProvider` has one method: `GetDocumentationLink` which gives the address of the documentation for a given error code within the error's description.
Related to https://github.com/xamarin/md-addins/pull/1080.
=> Add documentation extension point

main/src/addins/Xml/Editor/BaseXmlEditorExtension.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs
Change in Document.cs fixes loop, since loop was caused by setting project not actually setting it
Changed in BaseXmlEditorExtension.cs is just respecting ProjectReloadCapability.None and not showing shared project switching option or calls AttachToProject method.
=> Bug 40784 - BaseXmlEditorExtension causes an infinite loop with shared asset projects

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/FileProvider.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/FindReplace.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/Scope.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs
A couple of patches to improve the Find In Files speed. tl;dr these patches cut about 10seconds from the time taken to search through files in Main.sln.
Some speed results from runs of 10 goes on Main.sln (18,000 files)
Average time to search every file for the word "Updater"
Master branch: 21.85 seconds (Range 20.36 -> 23.3)
With this patch applied: 11.63 seconds (Range 9.54 -> 14.34)
We can look closer at this because there are two phases to the search, generating the list of files and readers for them, and doing the search on those files.
Master (average over 10 runs):
- List files: 18.98 seconds (range: 17.5 -> 20.43)
- Search files: 2.85 seconds
With patch applied:
- List files: 8.81 seconds (range: 6.75 -> 11.46)
- Search files: 2.85 seconds
Which makes sense as we haven't touch the …
=> Improve the speed of Find in files

main/src/core/MonoDevelop.Ide/ExtensionModel/MonoDevelop.Ide.addin.xml, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Extensions/ErrorDocumentationProvider.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Tasks/TaskListEntry.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
It's now easier for add-ins to implement link to the documentation for specific error codes thanks to the custom extension point logic.
Here's an exemple of the only thing add-ins need to do:
```
<Extension path = "/MonoDevelop/Ide/ErrorDocumentationProvider">
<ErrorDocumentationProvider id = "MTErrorDocumentation"
regex = "MT\d{4}"
url = "https://developer.xamarin.com/guides/ios/troubleshooting/mtouch-errors/#{0}"/>
</Extension>
```
=> Make ErrorDocumentationProvider a custom extension point

main/src/addins/MonoDevelop.UnitTesting/Services/UnitTestService.cs
As per 14872cd219d96421caee9a69935c474488fcf94b, we were no longer
checking whether the passed context was null.
The context we are not assigning as per this change will be fixed up by
TestContext in the constructor and assigned a fallback value.
Bug 41320 - Run Unit Tests from Run Menu isn't working. Shows NRE in log
=> [NUnit] Guard against null execution context on running tests.

main/src/addins/MonoDevelop.UnitTesting/Gui/TestPad.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/ExtensibleTreeView.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ClassPad/ClassBrowserPad.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads/SolutionPad.cs
It's needed for automation of Xamarin Studio to avoid clash between multiple instances
=> Explicitly add Name to ExtensibleTreeView

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.NodeBuilders/PackageReferenceNode.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.NodeBuilders/PackageReferenceNodeBuilder.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.NodeBuilders/ProjectPackagesFolderNode.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.NodeBuilders/ProjectPackagesFolderNodeBuilder.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/ExtensibleTreeView.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/NodeBuilder.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Styles.cs
Fixes the color of the NuGet status message in solution pad nodes.
=> [C7][Bug 40898] Fix unreadable node status in soultion pad

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/SearchInSolutionSearchCategory.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/FindInFilesDialog.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/SearchProgressMonitor.cs
From #1359: When the "Find in Files" dialog is being closed, the Search Result Pad disappears (if it is not docked).
Fix: Search dialog retrieves the result pad from the monitor and focuses it when the Close button has been activated.
(fixes bug #37577)
(cherry picked from commit 0b9da61c9e836de36a703423d46f3c5ccfbf8cc7)
=> [C7][Bug 37577/40150] Focus Search result pad on search dialog closed

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
We need to have one statusbar progress per action we're doing, so we
will have to attach the same error pad to a different status bar for
build and clean.
The idea of the code is to have one statusbar monitor alive at a time,
while the error one is alive for the whole operation, and the
aggregated monitors are disposed at the end just so they're not
marked as finalized but not Disposed by profiler tools.
=> [Ide] Fixup rebuild progress monitor behaviour

main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlNodeExtension.cs
Set solution pad overlay icons only if the status
of the node has been changed. Otherwise keep
the original overlay.
(cherry picked from commit e5e9798a9952601ca128fa223c724e8511904b13)
(fixes bug #41580)
=> [VersionControl] Fix solution pad overlay icons [C7][Bug41580]

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
'ClassName.InitializeComponent()' and 'ClassName.InitializeComponent()'
This is same fix as https://github.com/mono/monodevelop/pull/1489 but for C7SR1
=> Bug 41572 - InitializeComponent() The Call is Ambiguous between

main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/SystemAssemblyService.cs
Reason this appeared only now and only to Matt is because he installed my adding which caused this here: https://github.com/DavidKarlas/VSCodeDebugger/blob/master/VSCodeDebugger/VSCodeDebuggerEngine.cs#L23
Since I will fix this in AddIn this weekend, maybe we can reject this commit for C7SR1(I already committed this check to master...)
I opened this PR against C7SR1 because bug is specified as such...
=> Bug 41604 - File not found exception logged every second into IDE log when not project not compiled

main/src/core/MonoDevelop.Core/MonoDevelop.Core/Runtime.cs, main/tests/UnitTests/MonoDevelop.Core/RuntimeTests.cs, main/tests/UnitTests/UnitTests.csproj
Also allow underlying exception to be thrown with RunInMainThread.
=> [Cycle7] Fix task failure not reported for Runtime.RunInMainThread

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Gui/AddPackagesDialog.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.csproj, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/BackgroundDispatcher.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/ImageLoader.cs
Fixed bug #41499 - Searching for a NuGet package takes five to ten
minutes to populate the results.
https://bugzilla.xamarin.com/show_bug.cgi?id=41499
When opening the Add Packages dialog sometimes it could take a while
(1 to 2 minutes) to display the list of NuGet packages. The problem
was that the images displayed in the Add Packages dialog for the
NuGet packages were loaded individually each using their own Task
which could use up many thread pool threads. The search itself uses a
Task and if this is run whilst the images are being loaded the task
can take a long time before a thread pool thread is made available to
start the search.
To fix this the image loading no longer uses tasks and instead uses
a single low priority background thread to load the images one at a
time.
=> [Cycle7][NuGet] Fix delay for packages to appear in Add Packages dialog.

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/PackageReferenceNodeTests.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/ProjectPackagesFolderNodeTests.cs
How the solution pad nodes display labels was changed in commit:
9197e1153e424ac964f50e6b444a7d393e459834
So instead of having one _label_ there is a primary and a secondary
label. The secondary label is displayed in a different colour text.
This broke the unit tests since they were based on the original
api where there was no secondary label and the code in the NuGet
addin has been changed to use a secondary label.
=> [Cycle7][NuGet] Fixed failing unit tests due to api change.

main/src/addins/MonoDevelop.DocFood/DocFood.config.xml
void methods'.
It's a slight difference between roslyn & NR5.
=> Fixed 'Bug 41795 - Generated documentation includes "returns" tag for

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/CompletionListWindow.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/TooltipInformationWindow.cs
I believe I've found the cause of the bug I tried to fix in pull request #1353 
Commit 176ab0480dd24fa2e3623ea5b85c228dd4036ab1 added a hack that uses a timeout to change the opacity of the tooltip window.
This timeout adds a small timing window where the opacity on the tooltip window could get updated after the tooltip window has been hidden.
After adding a check for if the tooltip window is set to visible before changing the opacity inside the timeout handler, I am no longer able to reproduce the bug.
The extra checks to the completion list window in my last pull request do not appear to be necessary after this fix and can be reverted.
=> [Ide]Stop tooltip from appearing after completion list has closed 

main/src/core/MonoDevelop.Ide/gtkrc.mac, main/src/core/MonoDevelop.Ide/gtkrc.mac-dark
This PR changes/fixes the Chack-/OptionButton design inside the Property Pad.
Current:
Patched Gtkrc (this PR):
With this change and the patched xamarin-gtk-theme (https://github.com/mono/xamarin-gtk-theme/pull/28) they will look even more native (will be automatically effective with an updated MDK):
=> [c7][Ide][Mac] Fix property pad checkbox design

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/CustomCommand.cs
Fixed bug #41722 - Build Failed
https://bugzilla.xamarin.com/show_bug.cgi?id=41722
When a custom command is created that runs before the build and is
configured to run on the external console then a null reference
exception is thrown when building. This is because the execution
context is null and it was being referenced when trying to create
an external console.
Command execution failed
at MonoDevelop.Projects.CustomCommand+<Execute>c__async0.MoveNext () [0x0016d] in /Users/builder/data/lanes/3342/694a75f0/source/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop.Projects/CustomCommand.cs:279
To repro:
1) Create a new C# console project.
2) Open project options and select Build - Custom Commands.
3) …
=> [Cycle7][Core] Fixed build failure when using custom commands.

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/ProjectCommands.cs
Fixed bug #41790 - Xamarin Studio fatal error when running project
build custom commands
https://bugzilla.xamarin.com/show_bug.cgi?id=41790
Running a custom command would cause a unhandled exception and
terminate the IDE. To reproduce:
1) In project options select Build - Custom Commands.
2) Select Custom Command in the drop down, enter a name and a
valid command. Press OK to save the changes.
3) Right click the project and run the custom command just created.
An unhandled exception has occured. Terminating Xamarin Studio? True
at MonoDevelop.Ide.Gui.Components.LogViewProgressMonitor.OnWriteLog (System.String message)
in monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/LogView.cs:723 …
=> [Cycle7][Ide] Fixed fatal error when running custom command.

main/src/addins/VersionControl/MonoDevelop.VersionControl.Subversion.Unix/MonoDevelop.VersionControl.Subversion.Unix.csproj, main/src/addins/VersionControl/MonoDevelop.VersionControl.Subversion.Unix/MonoDevelop.VersionControl.Subversion.Unix/SvnClient.cs
Bug 41661 - [Cycle 7] Subversion support is not available in the IDE on
Mac if libsvn_client cannot be located. Xcode does not install this
library by default
=> [Svn] Implement support to install Command Line Tools on demand.

main/src/addins/MonoDevelop.UnitTesting.NUnit/NUnitRunner/ExternalTestRunner.cs
The BasePath property on the created TestPackage was being set to the directory that contains the NUnitRunner.exe binary. It is supposed to be set to the directory that contains the test assembly.
=> [NUnit] Fix 41541 - App Config is not read in Unit Tests

main/src/addins/MonoDevelop.UnitTesting.NUnit/MonoDevelop.UnitTesting.NUnit/NUnitProjectTestSuite.cs
Fixed bug #41715 - Unit Tests pad shows "Load failed" for unit test
projects (both iOS and Android)
https://bugzilla.xamarin.com/show_bug.cgi?id=41715
Android and iOS unit test projects are not supported by the NUnit
addin and cause a load failure to be displayed in the Unit Tests
window. In older versions (5.0) of the NUnit addin the Android and iOS
unit test projects were not displayed in the Unit Tests window
since they were filtered out since the references did not match
any of the supported assembly names. The reference name check was
changed in 6.0 to match any nunitlite assembly reference ignoring
the case which meant XamarinAndroid.NUnitLite and
MonoTouch.NUnitLite were being loaded into the Unit Tests window.
Now the nunitlite reference name check has been made more strict so …
=> [NUnit] Fixed load failure for Android and iOS unit test projects.

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/ProjectCommands.cs
Fixed bug #41790 - Xamarin Studio fatal error when running project
build custom commands
https://bugzilla.xamarin.com/show_bug.cgi?id=41790
Running a custom command would cause a unhandled exception and
terminate the IDE. To reproduce:
1) In project options select Build - Custom Commands.
2) Select Custom Command in the drop down, enter a name and a
valid command. Press OK to save the changes.
3) Right click the project and run the custom command just created.
An unhandled exception has occured. Terminating Xamarin Studio? True
at MonoDevelop.Ide.Gui.Components.LogViewProgressMonitor.OnWriteLog (System.String message)
in monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/LogView.cs:723 …
=> [Cycle7-SR0][Ide] Fixed fatal error when running custom command.

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/RecentFileStorage.cs
Fixed bug #42187 - Welcome page items randomly disappear/reappear
https://bugzilla.xamarin.com/show_bug.cgi?id=42187
Sometimes the welcome page can load before the recently used items
are loaded. This results in only the pinned/favourited projects being
displayed on the welcome page and other recently used projects are
not shown.
=> [Ide] Fix welcome page items not always being displayed

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/RecentFileStorage.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/RecentItemsChangedEventArgs.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/RecentOpen.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.WelcomePage/WelcomePageRecentProjectsList.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
This modifies RecentFiles updates so that we do the following:
* Split Projects/Files into different events. This way we can guarantee
that for the WelcomePage, for example, we can subscribe only to project
changes that will cause a refresh of the items in the list.
* Don't trigger updates of recent items if nothing has changed
between the old and the new version.
=> [Ide] Optimize RecentFiles updates.

main/src/addins/TextTemplating/Mono.TextTemplating.Tests/DummyTemplateGenerator.cs, main/src/addins/TextTemplating/Mono.TextTemplating.Tests/GenerationTests.cs, main/src/addins/TextTemplating/Mono.TextTemplating.Tests/Mono.TextTemplating.Tests.csproj, main/src/addins/TextTemplating/Mono.TextTemplating/Mono.TextTemplating/TemplateGenerator.cs, main/src/addins/TextTemplating/Mono.TextTemplating/Mono.TextTemplating/TemplatingEngine.cs, main/src/addins/TextTemplating/MonoDevelop.TextTemplating/MonoDevelopTemplatingHost.cs, main/src/addins/TextTemplating/MonoDevelop.TextTemplating/ProjectFileTemplatingHost.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=41738
Changes by files:
ProjectFileTemplatingHost.cs:
Replacing properties like $(SolutionDir) with correct value when resolving assembly path(https://msdn.microsoft.com/en-us/library/bb126478.aspx#Anchor_3)
MonoDevelopTemplatingHost.cs:
Apperently it's legal to say "System.dll" in T4, which GAC lookup doesn't like
TemplatingEngine.cs:
/noconfig is needed so mcs.exe(or csc.exe) doesn't report error CS1703(An assembly `System' with the same identity has already been imported. Consider removing one of the references) for System.dll
TemplateGenerator.cs:
By adding reference by FullName we let framework resolve full path, which allows deduplication of System.dll reference in case when user also specifies <#@ assembly name="System.dll" #>
@mhutch …
=> Bug 41738 - The 'TextTemplatingFileGenerator' code generator crashed

main/src/core/Mono.Texteditor/Mono.TextEditor/Actions/ClipboardActions.cs
This reverts commit 1a4ae771f502e19e914d1111d8c0d8912863ee7b.
This revert is on `master`, but it needs to be on `cycle7` as well in order to fix https://bugzilla.xamarin.com/show_bug.cgi?id=39328
=> Revert "Disable MD_CLIPBOARD_FORMAT as a paste target on Windows"

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildEvaluationContext.cs, main/tests/UnitTests/MonoDevelop.Projects/MSBuildProjectTests.cs, main/tests/test-projects/msbuild-tests/functions.csproj
Fixes bug #41912 - [System.FormatException] MSBuild property evaluation
failed: FrameworkVersion.Replace(".", "").PadRight(3,"0")
=> [Core] Fix MSBuild evaluation issue

main/src/addins/CSharpBinding/MonoDevelop.CSharp.ClassOutline/CSharpOutlineTextEditorExtension.cs, main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/InternalExtensionAPI/ITextEditorImpl.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextEditor.cs
outline is clicked the caret is not moved to item on text editor'
=> Fixed 'Bug 41727 - Documentoutline Pad - When an item on document

main/src/core/MonoDevelop.Ide/MonoDevelop.Components/ContextMenuTreeView.cs
Fixed bug #38073 - Failure when dragging file from Project A to
Project B then back to Project A
https://bugzilla.xamarin.com/show_bug.cgi?id=38073
After adding a file to a project and then trying to drag that file
to another folder the file would not be dragged. The problem was that
selection was disabled by the ContextMenuTreeView and not reset
since the button release event is sometimes not fired.
=> [Ide] Fix failure to drag and drop file

main/src/core/MonoDevelop.Ide/MonoDevelop.Components/ContextMenuTreeView.cs
Fixed bug #38073 - Failure when dragging file from Project A to
Project B then back to Project A
https://bugzilla.xamarin.com/show_bug.cgi?id=38073
After adding a file to a project and then trying to drag that file
to another folder the file would not be dragged. The problem was that
selection was disabled by the ContextMenuTreeView and not reset
since the button release event is sometimes not fired.
=> [Cycle8][Ide] Fix failure to drag and drop file

main/src/addins/MonoDevelop.UnitTesting.NUnit/NUnitRunner/ExternalTestRunner.cs
The BasePath property on the created TestPackage was being set to the directory that contains the NUnitRunner.exe binary. It is supposed to be set to the directory that contains the test assembly.
=> Fix 41541 - App Config is not read in Unit Tests

main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/MonoTargetRuntime.cs
.. fallback to `$prefix/lib/mono/4.5` if toolsVersion==4.0 .
This restores the older behavior from before the msbuild switch was
added.
=> MonoTargetRuntime: Use correct xbuild dirs for toolsVersion 12.0/14.0 or

main/src/addins/TextTemplating/MonoDevelop.TextTemplating/GenerateCommandHandler.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CustomTools/CustomToolService.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CustomTools/MSBuildCustomTool.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CustomTools/SingleProjectFileCustomTool.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
When files are removed from a project, ProjectFile.Project is null. We
can use the value of project from the event args instead.
Fixes bug #42345
=> [Ide] Use the project that is passed from Workspace FileXXX events instead of the ProjectFile.Project

main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.Formats.MSBuild.dotnet.v14.1.csproj
Don't hard code
`/Library/Frameworks/Mono.frameworks/Versions/Current/...`, instead
construct the path from `$(MSBuildToolsPath)`
=> MSBuild(oss): Fix the msbuild assemblies' HintPaths for 14.1 builder

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/FolderNodeBuilder.cs
This PR tries to fix the issues with the initial directory in the "Add File ..." and "Add Files from Folder ..." dialogs.
The current behaviour is to navigate to the folder where the previously added file was located, or the selected solution folder, if the command is used for the first time. This seems to be confusing since different users expect different things to happen:
1. always open the selected folder (in order to i.e. add files which are alredy physically there but not part of the project, like described in https://bugzilla.xamarin.com/show_bug.cgi?id=18568#c0) 
2. always open the previously used folder in order to add files from outside to different locations inside the solution/project (opposite to 1. described in https://bugzilla.xamarin.com/show_bug.cgi?id=8506, aka current …
=> [Ide] Optimize initial Add File location [Bug 8506][Bug 18568]

main/src/core/MonoDevelop.Core/MonoDevelop.Core/Gettext.cs
On Windows SetThreadUILanguage must be
called for each thread. Setting CurrentThread.CurrentUICulture
or CultureInfo.DefaultThreadCurrentUICulture is
not enough.
(fixes bug #28033)
(cherry picked from commit bb3d385137a4e19905ac29e90a22c26435eac8e9)
=> [Core][Win] Fix translations in async operations

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/ImageLoader.cs
This is not really a bug, but Xwt images should always be loaded in the UI thread. It didn't break anything in the NuGet dialog, but has the potential to cause failures in the Xwt backend code (i.e. if the current Xwt toolkit is not Gtk for some reason).
=> [NuGet] Load package images on the UI thread

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.Helpers/FakeNuGetPackageManager.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/InstallNuGetPackageActionTests.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/InstallNuGetPackageAction.cs
Fixed bug #42807 - Adding all the Google Play Services packages to an
Android app throws an error as some dependents packages already exist
https://bugzilla.xamarin.com/show_bug.cgi?id=42807
NuGet v3 has different behaviour to NuGet v2. If a NuGet package is
already installed then an attempt is made to install the same
package version again then NuGet v3 will throw a
PackageAlreadyInstalledException. NuGet v2 would log a message and
not throw an error.
The PackageAlreadyInstalledException is now caught and a message is
logged instead of having the exception thrown. This makes the
behaviour consistent with previous versions of the IDE.
=> [Cycle8][NuGet] Handle install error when NuGet package already installed

main/src/core/MonoDevelop.Ide/ExtensionModel/Commands.addin.xml, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/DockItem.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components/GtkWorkarounds.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/WindowCommands.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DocumentSwitcher.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/IPadContainer.cs, main/src/core/MonoDevelop.Ide/options/KeyBindingSchemeVisualStudio-mac.xml, main/src/core/MonoDevelop.Ide/options/KeyBindingSchemeVisualStudio.xml
This PR adds following features to the document switcher:
* Space key cycles through categories (pads/documents)
* Better Pad Focus detection (the content/top level widget focus does not indicate whether the pad really has the focus, the top level window keeps track of the current focus widget and the patch veriefies whether that widget is a child of the pad or not, in order to detect the focus state of a pad correctly)
* Special separate commands to switch pads (Alt+F6 by default like in VS in Windows)
=> Optimized document switcher

main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs
floating and and item is clicked the caret is not moved to item on
text editor'
=> Fixed 'Bug 41727 - Document Outline Pad - When document outline pad is

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
Fixed bug #20204 - Adding existing items to a folder does not offer
overwrite option
https://bugzilla.xamarin.com/show_bug.cgi?id=20204
Adding existing files to a folder in a project would not allow the
existing files to be overwritten. The existing project files would
need to be deleted first. Now when adding an existing file to a folder
in a project where they already exist the user is prompted to
overwrite the existing file.
=> [Ide] Allow existing project files to be overwritten when adding files

main/src/core/MonoDevelop.Projects.Formats.MSBuild/app.v12.0.config, main/src/core/MonoDevelop.Projects.Formats.MSBuild/app.v14.0.config, main/src/core/MonoDevelop.Projects.Formats.MSBuild/app.v14.1.config, main/src/core/MonoDevelop.Projects.Formats.MSBuild/app.v4.0.config, main/src/core/MonoDevelop.Startup/app.config
Will only take effect on .NET 4.6.2+
=> Opt-into long path support on Windows

main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.Formats.MSBuild.dotnet.v12.0.csproj, main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.Formats.MSBuild.dotnet.v14.0.csproj, main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.Formats.MSBuild.dotnet.v14.1.csproj, main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.Formats.MSBuild.dotnet.v4.0.csproj, main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.Formats.MSBuild.v12.0.csproj, main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.Formats.MSBuild.v14.0.csproj, main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.Formats.MSBuild.v4.0.csproj
They were sharing a single intermediate output, so would
end up with lots of copies of one builder.
=> [C8][MSBuild] Fix versioned builders

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
Fixed bug #20204 - Adding existing items to a folder does not offer
overwrite option
https://bugzilla.xamarin.com/show_bug.cgi?id=20204
Adding existing files to a folder in a project would not allow the
existing files to be overwritten. The existing project files would
need to be deleted first. Now when adding an existing file to a folder
in a project where they already exist the user is prompted to
overwrite the existing file.
Add apply all check box to dialog when overwriting project files  …
When adding or moving multiple files into a project, and the files
already exist, the user will be shown a dialog asking if they want
to overwrite each file. The dialog has a Cancel, Skip and Overwrite
File button and an Apply to all check box when multiple files are
being added. If a single file …
=> [Cycle8] Allow overwrite project files to be overwritten when adding files

main/src/core/MonoDevelop.Core/MonoDevelop.Core.Execution/ProcessService.cs
Fixed bug #43194 - "Debug Test" is not showing up context menu when
right clicking test in Unit Test Pad
https://bugzilla.xamarin.com/show_bug.cgi?id=43194
The debug execution modes were not being found since there is now an
extra level of execution modes and the wrong level was being checked.
=> [Cycle8][Core] Fix no debug execution modes being found

main/tests/MacPlatform.Tests/CredentialsProviderTests.cs
=> [Mac] Try using a temporary keychain for the credentials tests.

main/src/core/MonoDevelop.Core/MonoDevelop.Core.Serialization/DataItem.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.Policies/PolicyBag.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.Policies/PolicyService.cs, main/tests/UnitTests/MonoDevelop.Projects/PolicyTests.cs
Fixed bug #43246 - Custom code formatting (Indentation) settings are
not stored and reset after the solution restart.
https://bugzilla.xamarin.com/show_bug.cgi?id=43246
When a single C# formatting option was changed so it matched the
inherited policy then the solution was not saved since the policy
information in the solution was not being updated correctly.
When a setting  matches the inherited policy it is removed from the
properties that are to be saved with the solution file. However if
that property was originally stored in the solution file it would not
be removed when the solution was saved. A simple way to reproduce this
is to create a new solution, open the Solution Options dialog, select
Source Code - Code Formatting - C# source code, C# format, Edit,
then change Indent case …
=> [Cycle8][Core] Fix C# formatting policy not saved for solution

main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/AnalyzeCurrentProjectHandler.cs, main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/AnalyzeWholeSolutionHandler.cs
After analyzing the source the diagnostic errors and warnings are
added to TaskService and displayed in the Errors window. On closing
the solution and then opening another solution the status bar would
still show the warning and error icons for these diagnostics tasks.
The tasks created for the analysis errors and warnings are now
associated with the project or solution so they are removed when
the solution is closed.
=> [Refactoring] Fix analysis tasks not cleared on solution being closed

main/external/fsharpbinding/MonoDevelop.FSharp.Tests/CompilerArguments.fs, main/external/fsharpbinding/MonoDevelop.FSharp.Tests/MonoDevelop.FSharp.Tests.fsproj, main/external/fsharpbinding/MonoDevelop.FSharp.Tests/ProjectCracking.fs, main/external/fsharpbinding/MonoDevelop.FSharp.Tests/Samples/android/fsandroid.fsproj, main/external/fsharpbinding/MonoDevelop.FSharp.Tests/Samples/android/fsandroidnuget2.sln, main/external/fsharpbinding/MonoDevelop.FSharp.Tests/Samples/android/fsandroidnuget2/MainActivity.fs, main/external/fsharpbinding/MonoDevelop.FSharp.Tests/Samples/android/fsandroidnuget2/fsandroidnuget2.fsproj, main/external/fsharpbinding/MonoDevelop.FSharp.Tests/TestBase.fs, main/external/fsharpbinding/MonoDevelop.FSharp.Tests/TestHelpers.fs, main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/CompilerArguments.fs, version-checks
Bundle NuGet version of FSharp.Core 4.0.0.1 and include it in all the Android templates. Fixes #43237
Also added some fixes so that the NuGet version of FSharp.Core takes precedence over the outdated packaged MonoDroid FSharp.Core
=> Cycle8 fix 43237

main/src/core/MonoDevelop.Core/MonoDevelop.Core/FileService.cs
Calculation of the size of the resulting string was wrong.
Fixes bug #42376 - Xamarin Studio 6.0 introduced crash while loading
our solution.
=> Fix crash when calculating absolute path

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
XS uses a lot of tasks/threads. To avoid deadlocking the IDE we should not
use such a low number. Mono's default is 400/400 at the time of writing. If
we actually want to limit it then lets go for a max of 125 threads. That gives
us plenty to work with, even if we do kick off 16 parallel nuget restores.
https://bugzilla.xamarin.com/show_bug.cgi?id=42342
=> Use a higher limit for max threads

main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/MonoTargetRuntime.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProjectService.cs, main/src/core/MonoDevelop.Projects.Formats.MSBuild/AssemblyInfo.v14.1.cs, main/src/core/MonoDevelop.Projects.Formats.MSBuild/Main.cs, main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.Formats.MSBuild.dotnet.v14.1.csproj, main/src/core/MonoDevelop.Projects.Formats.MSBuild/app.v15.0.config
OSS MSBuild bundled with the mono OSX installer is being updated from
14.1 to 15.0 (toolsVersion), and this updates our support for it.
Any new XS builds installed on OSX with this code will have 15.0
installed and not 14.1 . So, we just disable support for building
projects with 14.1 .
The app.config needs to be updated though because in our earlier build
the element name for extension paths was
`msbuildExtensionsPathSearchPaths`, but that was changed when it was
merged upstream to `projectImportSearchPaths`.
Also, the references in the project file are updated such that the
project can build if either 14.1 or 15.0 msbuild is available. And
at runtime, it will switch to 15.0 assemblies. The check for 14.1 can be
removed with the next release.
=> [msbuild] Add support for building with msbuild 15.0 instead of 14.1

main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj
.. overridden if they are set. This helps with msbuild based builds,
where the default is to use `csc.exe`, but mono's msbuild overrides it
to use `mcs.exe`.
=> Fix build with msbuild - MD.Core.csproj: Let ToolExe/ToolPath be ..

configure
The OS X-centric URL suggested by `./configure --profile=core` for OS X failures redirects to a generic Building Monodevelop page. Since it is already redirecting, I updated the URL to the OS X anchor on that destination page to both cut out the extra bounce and put people in the right section immediately.
=> [build] Keep suggested OS X build doc URL OS-specific.

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/DefaultMSBuildEngine.cs
This step was being done too late, therefore some property evaluation in the stack was already trying to use an empty string include. The most common failure path is Path.GetFullPath in GetMetadataValue
=> [MSBuild] Don't bother adding an evaluated item with an empty include

main/src/core/MonoDevelop.Core/MonoDevelop.Core/FilePath.cs
Rewrote the algorithm so it creates fewer strings. The only do the check when we get a match on the first path, so it shouldn't slow down the code a lot.
On 10,000,000 iterations, the benchmark results are as given:
New with slash: 1331ms
Old with slash: 1311ms
New without slash: 1397ms
Old without slash: 3088ms
This fixes memory pressure, slightly makes the slash variant slower, but
greatly improved the variant without slash.
=> [Core] FilePath no longer creates extra strings on IsChildPathof.

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Features/Completion/CompletionResult.cs, main/src/addins/CSharpBinding/MonoDevelop.CSharp.Features/ParameterHinting/ParameterHintingResult.cs, main/src/addins/CSharpBinding/Util/CloneableStack.cs, main/src/addins/CSharpBinding/Util/NameSyntaxExtensions.cs
This makes it so there is no Enumerator created, as the compiler is smart
enough to detect that if there is a strongly typed GetEnumerator() method
with a return value that structurally matches IEnumerator, it'll prefer
that.
In this case, we're talking about structs. This will save us IEnumerator
allocations all over the place.
Split of #1637 by only changing what's internal API.
=> [Perf] Improve enumerators in internal custom collections

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs
This reduces lock contention on threads by 74% on net_4_x.sln, from
75325ms to 19384ms.
=> [Ide] Reduce lock contention on file save/check background monitor

main/src/core/MonoDevelop.Ide/gtkrc.mac, main/src/core/MonoDevelop.Ide/gtkrc.mac-dark
This fix depends on mono/xamarin-gtk-theme@c202097fba9982925fff4d5e67d0ca0feadd8ecb and requires an updated mono build.
The problem with this is, that without the updated mono build the trees will always have the inactive selection color on Mac:
~~**Please don't merge now**, I'll update the status as soon as the new mono builds include the patch.~~
(fixes bug #40877)
=> [Ide][Mac] Fix unfocused selected tree row background

main/src/core/MonoDevelop.Ide/gtkrc.mac, main/src/core/MonoDevelop.Ide/gtkrc.mac-dark
This PR makes Gtk checks/radios look like native OSX ones and fully replaces the quartz Gtk engine:
This works with mono 4.6+ and is compatible with `cycle8`, @slluis let me know if we want to backport this.
=> [Mac] OSX style checkboxes with pure Gtk theme

main/Makefile.am
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=44889
=> [build] Use nuget.exe from nuget-binary's submodule if nuget not found

main/build/MacOSX/Info.plist.in
Fixed https://bugzilla.xamarin.com/show_bug.cgi?id=45247
Also I have no recollection or record of why I disabled QuartzGL
6 years ago, so let's try allowing it again.
=> [Mac] Don't force discrete GPU

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MetadataReferenceCache.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
=> Fixed 'Bug 44537 - XS 6.x branches are not reading XML documentation

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild.Conditions/ConditionParser.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild.Conditions/ConditionTokenizer.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild.Conditions/Token.cs
This commit is pretty much self-explanatory. this reduces allocations for
the Token struct, making the code behave better.
Tokens are short-lived, usually not lasting more than two stackframes. The
idea is that a Token is at most 16bytes in size (on 64bit), it is
immutable and it represents a single value.
This change overall causes a huge change in allocations:
* MonoDevelop.Projects.MSBuild.Conditions allocations go down by 120MB on Main.sln
* 144MB of Tokens are no longer created on the heap (7 million obj)
* ConditionTokenizer allocates 12MB more now, as it has two token members.
* ConditionFactoryExpression allocates 12MB more now as it has a token member.
This should also increase performance.
=> [MSBuild, Perf] Move Token to be a struct

main/src/addins/CSharpBinding/MonoDevelop.CSharp.ClassOutline/CSharpOutlineTextEditorExtension.cs
We're null reffing because the callback is being invokde after we
null out the `outlineTreeView`. I think it makes sense to remove
the callback when this is nulled out as we don't want it to be
refilled at that point.
Fixes this spew from my logs:
at MonoDevelop.CSharp.ClassOutline.CSharpOutlineTextEditorExtension.RefillOutlineStore () [0x00023] in /Users/alan/Projects/monodevelop/main/src/addins/CSharpBinding/MonoDevelop.CSharp.ClassOutline/CSharpOutlineTextEditorExtension.cs:303
at GLib.Timeout+TimeoutProxy.Handler (System.IntPtr data) [0x0003f] in /private/tmp/source-mono-4.8.0/bockbuild-mono-4.8.0-branch/profiles/mono-mac-xamarin/build-root/gtk-sharp-None/glib/Timeout.cs:73
=> [CSharpBinding] Remove the timeout when we release the outline view

main/configure.ac, main/src/addins/GnomePlatform/Gio.cs, main/src/addins/GnomePlatform/GnomePlatform.cs, main/src/addins/GnomePlatform/GnomePlatform.csproj
GnomePlatform relies on some *super* deprecated libraries, from old versions of GNOME 2. All of the things we use GNOME# for can be done better using more modern replacements, e.g. GIO (part of modern GLib). It'd be nice to have some Gtk+ 2.14+ methods, but that's another story for another day.
For now, this greatly simplifies the dependency chain on Linux, and makes it easier to handle some FlatPak cases in future work.
=> Remove all use of GNOME-specific libraries from GnomePlatform

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/SlnFile.cs
Skip lines which only contain whitespace characters, as they should not be parsed.
Bug 11494 - Exception on opening solution file after Perforce converts line endings to \r\r\n
cc @mhutch
=> [MSBuild] Guard against empty lines in a solution file.

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/NewProjectController.cs
SelectTemplate(templateId) does not take into account
that a template can be part of a group, where the parent
category references only the first template.
This patch adds an additional check for template group
members. If a group contains the requested template,
it selects the group in the dialog and the target language
accordingly.
(fixes bug #46332)
=> [Ide][Bug 46332] Fix preselection of grouped templates in new project dialog

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/NewProjectController.cs
**NOTE:** this is the same as #1667, but for C9
SelectTemplate(templateId) does not take into account
that a template can be part of a group, where the parent
category references only the first template.
This patch adds an additional check for template group
members. If a group contains the requested template,
it selects the group in the dialog and the target language
accordingly.
(fixes bug #46332)
=> [C9][Ide][Bug 46332] Fix preselection of grouped templates in new project dialog

main/src/core/MonoDevelop.Core/MonoDevelop.Core.Serialization/DataItem.cs
Problem was that Policies have 3 ItemData values with name “TextStylePolicy”(one for plain text, one for C# and one for XML).
Since commit 42b7775af9 when UpdateFromItem was called it overwrote same “TextStylePolicy” 3x, instead of creating 3 separate TextStylePolicy each for one language
With this change.. Once TextStylePolicy is updated it’s removed from list so on next loop, next TextStylePolicy is updated
@slluis can you please review this?
=> Bug 45274 - Cannot change the code formatting policy

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
Fixed bug #46701 - New Project template window does not remember
last project template
https://bugzilla.xamarin.com/show_bug.cgi?id=46701
When adding a new project to an existing solution the last created
project template was not selected by default. The problem was that
an empty string was being passed as the template id instead of null
so an attempt was made to select a matching template.
=> [cycle9][Ide] Fix last used project template not selected

main/build/MacOSX/monostub.m
This fixes an issue on OSX Sierra where having a rtl language second in your list would cause gtk's direction to be set to rtl.
https://forums.xamarin.com/discussion/82412/xamarin-studio-has-messed-up-and-now-shows-all-its-own-text-ui-from-right-to-left-cant-fix-it
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=41969
=> Set LANGUAGE from monostub

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs
Fixed bug #48017 - Unable to execute run configuration with
environment variable
https://bugzilla.xamarin.com/show_bug.cgi?id=48017
If a run configuration is used where Start external program is
specified and an environment variable is defined for the project then
running the project would show an Execution failed message and the
IDE log would contain:
```
Execution failed
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
at System.ThrowHelper.ThrowInvalidOperationException (System.ExceptionResource resource) [0x00000] in /private/tmp/source-mono-4.8.0/bockbuild-mono-4.8.0-branch/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/mscorlib/system/throwhelper.cs:99
at …
```
=> [Core] Fix execution error when environment variable used in run config

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/NewFileDialog.cs
Rerun name verification on category changes,
instead of just disabling the "New" button.
(fixes bug #46585)
(cherry picked from commit 3d28ae7471ec6ab8a499d5d8b03ccb8a2df99603)
=> [C9][46585][Ide] Verify file name on category change in New File Dialog

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs
Fixed bug #48017 - Unable to execute run configuration with
environment variable
https://bugzilla.xamarin.com/show_bug.cgi?id=48017
If a run configuration is used where Start external program is
specified and an environment variable is defined for the project then
running the project would show an Execution failed message and the
IDE log would contain:
```
Execution failed
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
at System.ThrowHelper.ThrowInvalidOperationException (System.ExceptionResource resource) [0x00000] in /private/tmp/source-mono-4.8.0/bockbuild-mono-4.8.0-branch/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/referencesource/mscorlib/system/throwhelper.cs:99
at …
```
=> [Cycle9][Core] Fix execution error when environment variable used in run config

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProjectService.cs
We replaced XBuild with MSBuild .targets files load time of Main.sln(as example) went from 30sec to 2.5min because MSBuild .targets have many more Before/After targets tries resulting in a lot of Directory.EnumerateFileSystemEntries fetching from hard drive resulting in slow load time.
Since MSBuild.exe doesn't handle file name case mismatches on case-sensetive file system, it doesn't make sense to do this in IDE.
=> [MSBuild] Disabled case insensitive file name lookup

main/src/addins/MacPlatform/MacInterop/LaunchServices.cs
- launchApplicationAtURLOptionsConfigurationErrorSelector can return null in some cases
such as when the application crashes on launch
=> Fix Launch Service Null Deference

main/build/MacOSX/monostub.m, version-checks
This makes some changes to monostub.m so we can re-use it for the ServiceHub native launcher.
The difference is that I added `#if USE_SIMPLE_PATH ... #endif` and inside there, it gets the path to use from `SIMPLE_PATH`, then those are passed by the compiler in md-addins.
=> Re-using monostub.m for ServiceHub

main/src/addins/MacPlatform/MainToolbar/SelectorView.cs
Bug 47797 - Clicking "Manage Google Emulators..." from the devices
drop-down results in duplicated windows
Verified by QA in master.
=> [C9][Mac] Only notify ActiveRuntime changed once on menuitem selection.

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestSession.cs
Sometimes the errors pad has errors not associated
with a WorkspaceObject
=> [AutoTest] Add a null conditional in GetErrors

main/build/MacOSX/monostub.m
This fixes an issue on OSX Sierra where having a rtl language
second in your list would cause gtk's direction to be set to
rtl.
https://forums.xamarin.com/discussion/82412/xamarin-studio-has-messed-up-and-now-shows-all-its-own-text-ui-from-right-to-left-cant-fix-it
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=41969
=> Set LANGUAGE from monostub (Cycle 8)

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProjectInstance.cs, main/tests/UnitTests/MonoDevelop.Projects/MSBuildTests.cs
Fixes bug #44761 - "Application has not been built" error message when
deploying XM app with a custom TargetOuputPath.
=> [Core] Add missing path separator in SolutionDir

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/CustomCommand.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/EnvironmentVariableCollection.cs
Try to load all legacy execution custom commands from all configurations,
and convert them to run configurations.
Fixes bug #43791 - Not possible to debug a tool using mdtool as the external
program to run with a Run Configuration
=> [Core] Improve loading of legacy custom commands

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs, main/tests/UnitTests/MonoDevelop.Projects/ProjectTests.cs, main/tests/test-projects/fast-build-test/FastBuildTest.csproj, main/tests/test-projects/fast-build-test/FastBuildTest.sln, main/tests/test-projects/fast-build-test/FastLibrary.csproj, main/tests/test-projects/fast-build-test/MyClass.cs, main/tests/test-projects/fast-build-test/Program.cs
When checking if a project needs to be built, also check the flag
for all dependencies, taking into account the time at which the
flag was set.
Fixes bug #45265 - Running Xamarin.Mac app after building library does not
build app
=> [Core] Fix fast needs build check issue

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextEditorViewContent.cs
This bug happened with 512768ca3 and 7356c217 aka https://github.com/mono/monodevelop/pull/1636
Reason for this bug was that TextEditor was Disposed only when underlying GTK editor was destroyed which resulted in leaking extensions(which kept event handlers causing exception). Ever since commits mentioned above GTK editor is not created until tab is selected(visible) hence GTK editor was never destroyed(hence no disposing)…
=> Bug 49500 - Null reference when installing a NuGet package

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/NewProjectController.cs
For Unknown reason dialog sometimes closes before `dialog.CloseDialog ();` is called on line 638. But also user can close dialog by clicking (x) button causing DisposeExistingNewItems to be called. This resulted in disposed solution  while still in progress of saving, hence exception.
It’s save to remove this two lines since this was just defensively placed to dispose objects in all cases(in case of exceptions…)
Disposing is still done after solution is saved and at 2nd defensive place(before creating new project) so also in case of unexpected exception in process we will clean things up
=> Bug 49517 - Cannot create a Forms project (PCL or Shared) using New Project Dialog

main/src/core/MonoDevelop.Ide/MonoDevelop.Components/DropDownBoxListWindow.cs
If the breadcrumb bar menu is opened and the user clicks outside of the application, the main window disappears. This is caused by the typehint of the
dropdown menu being set to Menu, which deep in the gdk internals sets
hidesOnDeactivate to YES on the menu window, which somehow seems to propagate
to the main window as well.
Setting the typehint to DropdownMenu instead of just Menu fixes this
=> Stop main window disappearing when losing focus [C9]

main/src/core/MonoDevelop.Ide/MonoDevelop.Components/DropDownBoxListWindow.cs
If the breadcrumb bar menu is opened and the user clicks outside of the application, the main window disappears. This is caused by the typehint of the
dropdown menu being set to Menu, which deep in the gdk internals sets
hidesOnDeactivate to YES on the menu window, which somehow seems to propagate
to the main window as well.
Setting the typehint to DropdownMenu instead of just Menu fixes this
=> Stop main window disappearing when losing focus

main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/ArrayAdaptor.cs, main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/CorDebuggerBacktrace.cs, main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/CorDebuggerSession.cs, main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/CorEvaluationContext.cs, main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/CorMethodCall.cs, main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/CorObjectAdaptor.cs, main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/CorValRef.cs, main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/FieldReference.cs, main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/MtaBacktrace.cs, main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/MtaObjectValueSource.cs, main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/MtaObjectValueUpdater.cs, main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/MtaRawValue.cs, main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/MtaRawValueArray.cs, main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/MtaRawValueString.cs, main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/MtaThread.cs, main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/PropertyReference.cs, main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/StringAdaptor.cs, main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/VariableReference.cs, main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/Win32.cs, main/src/addins/MonoDevelop.Debugger.Win32/MonoDevelop.Debugger.Win32/CorDebuggerEngine.cs
Namespace is adjusted to Mono.Debugging.Win32 to make them consistent with Mono.Debugging.* API.
=> [CorDebug] Namespace is adjusted to Mono.Debugging.Win32

main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/CorObjectAdaptor.cs
Proper caching of CorTypes:
* unresolved names have to be also cached, otherwise the cache in useless. Greatly increases performance of evaluation.
* type info fetched via mi.GetTypeTokenFromName() instead of iterating over all types in module. This increases performance as well.
=> Proper caching of CorTypes

main/src/addins/MonoDevelop.Debugger.Win32/CorApi2/Extensions/MetadataExtensions.cs, main/src/addins/MonoDevelop.Debugger.Win32/CorApi2/Metadata/MetadataType.cs, main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/CorObjectAdaptor.cs
* MetadataType.GetPropertyImpl() implementation
* Properly getting module for native types in RuntimeInvoke, because there were exceptions
* try{} block removed, null check for 'method' removed, because it's unnecessary
* try-catch in OverloadResolve()
=> CorDebug fixes

main/src/addins/MonoDevelop.Debugger.Win32/CorApi2/debug/Debugger.cs, main/src/addins/MonoDevelop.Debugger.Win32/CorApi2/debug/Process.cs, main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/CorDebuggerSession.cs
Now all the event handlers are invoked as strongly typed delegates.
=> Get rid of DynamicInvoke in Debugger.cs

main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/CorDebuggerSession.cs
I've decreased lock(documents) range to fix deadlock that occured in some cases during attach in BindSourceFileBreakpoints and UnbindSourceFileBreakpoints calls.
=> [CorDebug] Decrease lock range

main/src/addins/MonoDevelop.Debugger.Win32/CorApi2/Metadata/CorMetadata.cs
This fixes the tests:
CorAdvancedEvaluationAllowTargetInvokesTests.AdvancedEvaluationTests.Bug24998
CorAdvancedEvaluationAllowTargetInvokesTests.AdvancedEvaluationTests.YieldMethodTest
CorAdvancedEvaluationNoTargetInvokesTests.AdvancedEvaluationTests.Bug24998
CorAdvancedEvaluationNoTargetInvokesTests.AdvancedEvaluationTests.YieldMethodTest
CorEvaluationAllowTargetInvokesTests.EvaluationTests.Lists
=> GetTypeTokenFromName() fixed to handle nested types delimeted by '+'

main/src/addins/MonoDevelop.Debugger.Win32/CorApi2/Metadata/CorMetadata.cs
Sometimes EnumParams gives you a param with position that is out of m_argTypes.Count
Return typeof(object) for unmatched parameter
=> Fix for IndexOutOfRangeExceptions in GetParameters

main/src/addins/MonoDevelop.Debugger.Win32/CorApi/.editorconfig, main/src/addins/MonoDevelop.Debugger.Win32/CorApi2/.editorconfig, main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/.editorconfig
Makes editing easier because CorApi* and Mono.Debugging has different code styles.
=> .editorconfig files for CorDebug projects.

main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/CorDebuggerBacktrace.cs, main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/CorDebuggerSession.cs, main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/CorObjectAdaptor.cs
Module loading was made AppDomain specific. This should fix "Wrong AppDomain" exceptions during evaluation, function calls etc. More diagnostic added.
=> App domain specific module load

main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValueTreeView.cs
When an evaluating group's ObjectValue is updated the items were
added in reverse order in the Locals window. The first item was
replacing the existing item but then the rest were inserted one at
a time after the first item. This resulted in all items after the
first one being added in reverse order.
=> [Debugger] Fix incorrect ordering for evaluated group in Locals window

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Styles.cs
This makes it easier to find the current theme API and adds the CurrentStyle tag to the style tag model.
=> [C9] Add Gui.Styles.CurrentStyle for easier access and StylesStringTagModel usage

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
Problem is that after creating new project get_RunConfigurations is called which adds default run configuration and sets defaultRunConfigurationCreated to true. But after restoring NuGet packages we call OnReevaluateProject which removes default configurations already created and since we have defaultRunConfigurationCreated set to true, default configurations are not recreated… This seems like best place to reset defaultRunConfigurationCreated to false.
=> Bug 51137 - Web application can't be debugging when first created

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/PackageCompatibilityRunnerTests.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/PackageCompatibilityTests.cs
Wrench builds are failing with access denied errors trying read an
.xml PCL profile file. Avoid using PCL profile .xml files on the
Wrench server by specifying a different directory which does not
exist.
=> [Cycle9][NuGet] Fix the unit tests on Windows

main/src/addins/MonoDevelop.Packaging/Templates/CrossPlatformLibrary.xpt.xml
Fixed bug #51273 - Multiplatform library uses PCL Profile 78 instead of Profile 111
https://bugzilla.xamarin.com/show_bug.cgi?id=51273
Switching from PCL profile 78 to 111 makes the project template consistent with the standalone PCL project template.
=> [Cycle9][Packaging] Use PCL profile 111 in multiplatform project template

main/src/addins/MacPlatform/MacPlatform.cs, main/src/core/Mono.Texteditor/Mono.TextEditor/Gui/GtkWorkarounds.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components/GtkWorkarounds.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Ide.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
After the GLib mainloop exits, call NSApplication.Terminate() to make sure Cocoa terminates correctly and shuts down threads like those used for animations and such.
If NSApplication.Terminate() is called first, catch that call and cancel termination, instead calling Gtk.Application.Quit() so that we shutdown the GLib mainloop. This will in turn call NSApp.Terminate() a second time, which will *not* cancel termination and will perform
Cocoa cleanup as described above.
https://bugzilla.xamarin.com/show_bug.cgi?id=14789
=> Handle either Gtk.Application.Quit() or NSApplication.Terminate()

main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/ArrayAdaptor.cs, main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/CorDebuggerSession.cs, main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/CorObjectAdaptor.cs, main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/CorValRef.cs, main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/FieldReference.cs
(Zombie state exception thrown). In the most of cases CorValue stays alive between Continue-Stop, and this allows to greatly improve evaluation performance.
=> CorValRef invalidates only when it actually required

main/src/addins/MonoDevelop.Debugger.Win32/CorApi2/CorApi2.csproj, main/src/addins/MonoDevelop.Debugger.Win32/CorApi2/Extensions/MetadataExtensions.cs, main/src/addins/MonoDevelop.Debugger.Win32/CorApi2/Metadata/CorMetadata.cs, main/src/addins/MonoDevelop.Debugger.Win32/CorApi2/Metadata/GenericParameter.cs, main/src/addins/MonoDevelop.Debugger.Win32/CorApi2/Metadata/MetadataPropertyInfo.cs, main/src/addins/MonoDevelop.Debugger.Win32/CorApi2/Metadata/MetadataType.cs, main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/CorObjectAdaptor.cs
* MetadataExtensions.ReadType() now takes into account actual instantiation of generic type. It allows to correctly read types of method parameters in generic classes (the case when method parameter has T type).
This fixes overload resolve in evaluation.
* Introduced MethodGenericParameter and TypeGenericParameter to differentiate them in OverloadResolve. Both of the types are implementations of System.Type.
IsAssignableFrom() ignores MethodGenericParameter because we don't have information about it yet (constraints etc.) and returns true always in this case
=> Cor debug instantiations

main/src/addins/MonoDevelop.Autotools/MakefileProjectServiceExtension.cs, main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebuggingService.cs, main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/Extensions.cs, main/src/addins/MonoDevelop.UnitTesting.NUnit/MonoDevelop.UnitTesting.NUnit/NUnitAssemblyTestSuite.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Core.Execution/OperationConsoleFactory.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/CompiledAssemblyProject.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/ProjectCommands.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads/DefaultMonitorPad.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/ProgressMonitors.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
This is different aproach from https://github.com/mono/monodevelop/pull/1697
It sets suffix when Application Output is created and not from debugger when process is started/connected to.
Id of pad needs to be suffixed with title otherwise on reuse title can be wrong. Only downside of this is that we can end with many open Application Output pads because we don't reuse pads with different titles.
=> Bug 48234 - Unable to determine which `Application Output` pad belongs to which project

main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/TargetRuntime.cs
This can be hit in situations like dc6a7646e17aea9378a4fc44c8b668f6de7de8a4
=> [Core] Add logging in case we find a non-existent target framework

main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/ExtensibleTextEditor.cs, main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs, main/src/core/Mono.Texteditor/Mono.TextEditor/Gui/MonoTextEditor.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/InternalExtensionAPI/ITextEditorImpl.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextEditor.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/ViewCommandHandlers.cs
Allows editor widgets (search and goto line) to handle all keys.
(fix bug #49816)
=> [Ide] Run editor commands only if the editor is focused

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Features/SemanticHighlighting/SemanticHighlightingVisitor.cs
The dynamic keyword is not highlighted properly. In the UI, you can see
that it is actually highlighted as a keyword, but is quickly (< 1 second)
reverted to the default text color.
Removing "dynamic" from the list fixes the problem. There is a comment
that suggests that "var" and "dynamic" should be skipped here. "var" is
already omitted from the list.
=> Fix dynamic type keyword syntax highlighting

main/src/core/MonoDevelop.Core/MonoDevelop.Core/FilePath.cs, main/tests/UnitTests/MonoDevelop.Core/FilePathTests.cs
Bug 48212 - Unnecessary Expand icon is displaying with "Resources"
folder
=> [Ide] Fix FilePath.IsChildPathOf regression.

main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/CorDebuggerSession.cs
See
https://github.com/mono/debugger-libs/pull/91
=> implemented invalidation of stacks version on setNextStatement for CorDebuggerSession

main/src/core/MonoDevelop.Ide/MonoDevelop.Components/ContextMenuTreeView.cs
If the treeview is changed when unrealised (autohidden), the treeview doesn't update its internal vertical offset. This can lead to items being offset outside the visible area and therefore becoming unreachable. The only way to force the treeview is to recalculate this offset by setting the Vadjustment.Value, but it ignores values the same as the current value. Therefore we simply set it to something slightly different then back again.
See also MonoDevelop.Ide.Gui.Components.PadTreeView for the same fix.
Fixes BXC #31712
This sounds like something that might be able to be fixed in Gtk+ itself? @bratsche
=> [IDE] Force the solutionpad treeview to update its offsets

main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/CorDebuggerSession.cs
Implemented PrintTrace action for CorDebuggerSession breakpoints 
See
https://github.com/mono/debugger-libs/pull/90
=> implemented printTrace for CorDebuggerSession breakpoints

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components/MenuButtonEntry.cs
This fixes the assumption that only one commandmanager would exist. MenuButtonEntry would create its own command manager, that would then intercept all native cocoa keypresses.
Moved native cocoa key registration only to commandmanagers with
TopLevelWindows.
Special shout out to bug 51469 for giving us a repro to fix this.
Bug 40414 - [C7] Quick Search does not work at all.
=> [Ide] Fix searchbar unable to be typed in

main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/CorDebuggerSession.cs
Breakpoints.Clear() deactivates all the breakpoints. Otherwise COM exception may be thrown on Detach() or Terminate()
=> Breakpoints.Clear() deactivates all the breakpoints

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/UpdateAllNuGetPackagesInProjectActionTests.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/UpdateAllNuGetPackagesInProjectAction.cs
Fixed bug #51497 - Packages are updated to pre/beta-release version
if you update all packages
https://bugzilla.xamarin.com/show_bug.cgi?id=51497
With a pre-release NuGet package installed in a project and updating
all the NuGet packages in the project could cause the stable NuGet
packages to be updated to pre-release versions. This was because
on updating all the packages if any were pre-release the include
pre-release flag would be set on updating which would allow any
pre-release NuGet packages to be used on updating. Now with this
commit the include pre-release flag is not set on updating. NuGet v3
will still update pre-release NuGet packages to the latest pre-release
or latest stable, depending on which is the latest version, without
this include pre-release flag set. NuGet v2 …
=> [Cycle9][NuGet] Fix updating all packages installing unexpected pre-releases

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.WelcomePage/WelcomePageService.cs
This patch adds shown/hidden events to the WelcomePageService. This is required to fix bug #51576, where we need to hide/show a WebView when the welcome page visibility changes.
(cherry picked from commit 81caa7033bee8aa608d3a6e2c2b0555da5948931)
=> [Ide] Add WelcomePage shown/hidden events

main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/AssemblyReferenceFolderNodeBuilder.cs, main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/AssemblyResourceFolderNodeBuilder.cs, main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/BaseTypeFolderNodeBuilder.cs, main/src/addins/MonoDevelop.ConnectedServices/Gui.SolutionPad/ConnectedServicesFolderNodeBuilder.cs, main/src/addins/MonoDevelop.GtkCore/MonoDevelop.GtkCore.NodeBuilders/StockIconsNodeBuilder.cs, main/src/addins/MonoDevelop.GtkCore/MonoDevelop.GtkCore.NodeBuilders/WindowsFolderNodeBuilder.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.NodeBuilders/ProjectPackagesFolderNodeBuilder.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.NodeBuilders/ProjectReferencesFromPackagesFolderNodeBuilder.cs, main/src/addins/MonoDevelop.WebReferences/MonoDevelop.WebReferences.NodeBuilders/WebReferenceFolderNodeBuilder.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.GettingStarted/GettingStartedNodeBuilder.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/ExtensibleTreeView.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/NodeBuilder.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ClassPad/ClassNodeBuilder.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ClassPad/CombineNodeBuilder.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/PortableFrameworkSubsetNodeBuilder.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/ProjectFileNodeBuilder.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/ProjectFolderNodeBuilder.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/ProjectReferenceFolderNodeBuilder.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/SolutionFolderFileNodeBuilder.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/SolutionFolderNodeBuilder.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/SystemFileNodeBuilder.cs
This method is used to get the sorting group of a node. It makes it easier
for add-ins to set node ordering.
=> Introduce NodeBuilder.GetSortIndex()

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.GettingStarted/GettingStartedNodeBuilder.cs
If the project node in the solution pad is not expanded,
we need to provide the project node in order to
select the matching Getting Started node when the
active document changes to the Getting Started view.
(fix bug #51632)
(cherry picked from commit ba6931307bd43d8f316b3a238ba7cf65c41eb896)
=> [GettingStarted] Fix Solution Pad expanding

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs
Without the main UI thread's task scheduler being passed to the
ContinueWith the action was run on a thread pool thread instead of
the UI thread. This was causing the FileService.FileChanged event to
fire on a non-UI thread. It was also causing a crash if the project
file is edited in the text editor since the reload was being done on
a non-UI thread.
=> [Ide] Ensure document actions are run on UI thread.

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
Clean failures were reported if a Clean was done but not when a
Rebuild was run. The status bar would not show any error and the
Errors window would not show any failures. Also removed some unused
code that is not used when reporting Clean results.
=> [Ide] Fix Clean failures not reported on Rebuild

main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/Mono.Debugging.Win32.nuspec
Using buildver variable instead of Version because Version can't be used in <dependency> tag
=> Using buildver variable

main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.QuickTasks/QuickTaskMiniMapMode.cs, main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.QuickTasks/QuickTaskOverviewMode.cs
This PR includes some workarounds for broken HiDPI support in Gtk.
6cd6dea: fixes QuickTask icon blurriness on Mac
8998278: fixes MiniMap drawing on Windows
Both are *workarounds* and don't fix the actual issues inside Gtk. Related bugs: https://bugzilla.xamarin.com/show_bug.cgi?id=51376, https://bugzilla.xamarin.com/show_bug.cgi?id=51378
=> Fix HiDPI rendering issues

main/src/addins/Deployment/MonoDevelop.Deployment.Linux/MonoDevelop.Deployment.Linux/LinuxDeployData.cs, main/src/addins/MonoDevelop.Autotools/MakefileData.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/IMSBuildPropertySet.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildImport.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildObject.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProject.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProperty.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildXmlElement.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectConfiguration.cs, main/tests/UnitTests/MonoDevelop.Projects/MSBuildProjectTests.cs, main/tests/UnitTests/MonoDevelop.Projects/ProjectTests.cs
If a project has an Sdk attribute then on saving the xmlns attribute will not be added. If it exists on reading then on saving it will be removed.
There are few other places in the code, shown below, where the MSBuildProject.Schema constant, which holds the MSBuild xml namespace, is used instead of the MSBuildProject's xml namespace. MonoDevelop project extensions and external properties are currently handled. Not sure if we need to change LinuxDeployData and MakefileData to use the project's namespace instead. The others I suspect we will want to change to be consistent even if .NET Core projects are possibly not using them.
=> [DotNetCore] Remove xmlns attribute for Sdk style projects

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests.csproj, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTests.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreMSBuildProject.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs, main/src/addins/MonoDevelop.PackageManagement/AssemblyInfo.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.csproj, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/ProjectPackageReferenceTests.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/ProjectPackageReference.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildItem.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildObject.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProject.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProperty.cs, main/tests/UnitTests/MonoDevelop.Projects/MSBuildProjectTests.cs, main/tests/test-projects/dotnetcore-console/dotnetcore-console/dotnetcore-sdk-console.csproj, main/tests/test-projects/dotnetcore-console/dotnetcore-sdk-console.sln
MSBuildItem now has an `void AddKnownAttributes (params string[] names)` method where custom known attributes can be added. When the MSBuildItem is then written the associated properties will be written as attributes instead of child elements.
=> [DotNetCore] Support custom attributes on MSBuildItem

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ItemCollection.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs, main/tests/UnitTests/MonoDevelop.Projects/ProjectReevaluationTests.cs
When a new project reference is added and then the project is
reevaluated the project reference is replaced with a new instance
but the OwnerProject is not set. This caused code completion to stop
working in the text editor and types were marked with red error
markers.
A new ProjectReference has a BackingEvalItem which has no properties
so on reevaluating a new ProjectReference is created since no match
is found due to the missing properties. On calling Items.SetItem
there is no items added notification since ProjectReference implements
GetHashCode and Equals and the different instances are considered to
be the same. This resulted in a null OwnerProject for the
ProjectReference and when that was written out to xml a null reference
exception was thrown. To fix this the OwnerProject is set …
=> [DotNetCore] Fix OwnerProject null for project ref after reevaluation

main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.PreviewVisualizers/GenericPreviewVisualizer.cs, main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ExceptionCaughtDialog.cs
Fixing this bug it only needs changes in GenericPreviewVisualizer.cs, but while working on this bug I found how to correctly fix issues with lable.Selectable and avoiding auto-selecting and cursor appearing(setting CanFocus=false), so I fixed it also in ExceptionCaughtDialog)
=> Bug 50194 - Copying values from tooltip is difficult

main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebuggingService.cs
EllipsizedLength increased to 260 instead of 100 char, to cover more use cases like file paths
=> Bug 52177 - Show bigger strings in watch pad

main/winbuild-release.bat, main/winbuild.bat
If something goes wrong when trying to build locally you just see a split second of red in this Windows prompt. Adding pause here will leave the prompt open until you hit a key.
=> [Windows] Pause if launched from explorer.exe and if there is an error.

main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/BreakpointPad.cs, main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValueTreeView.cs, main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/Toolbox.cs, main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/ExtensibleTextEditor.cs, main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/StatusView.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components/ContextMenu.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components/ContextMenuExtensionsMac.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components/GtkUtil.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/ExtensibleTreeView.cs
This patch fixes the positioning of tree context menus, especially when opened using the Shift+F10 key combination.
=> [48669] Fix native contextmenu positioning

main/external/fsharpbinding/MonoDevelop.FSharp.Tests/ProjectTests.fs, main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpProject.fs
By default, Xamarin Studio creates an ItemGroup for each
build action type like this :-
```
<ItemGroup>
<Compile Include="MainActivity.fs" />
<Compile Include="Resources\Resource.designer.fs" />
<Compile Include="Properties\AssemblyInfo.fs" />
</ItemGroup>
<ItemGroup>
<None Include="Resources\AboutResources.txt" />
<None Include="Properties\AndroidManifest.xml" />
<None Include="Assets\AboutAssets.txt" />
<None Include="packages.config" />
</ItemGroup>
<ItemGroup>
<Folder Include="Resources\layout\" />
<Folder Include="Resources\values\" />
</ItemGroup>
<ItemGroup>
<AndroidResource Include="Resources\drawable\icon.png" />
<AndroidResource Include="Resources\drawable-hdpi\icon.png" />
<AndroidResource Include="Resources\drawable-xhdpi\icon.png" />
<AndroidResource …
```
=> [F#] Merge item groups for VS/Windows compatibility

main/external/fsharpbinding/MonoDevelop.FSharp.Tests/ProjectTests.fs, main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpProject.fs
(Mirror of #1828 for cycle9)
By default, Xamarin Studio creates an ItemGroup for each
build action type like this :-
```
<ItemGroup>
<Compile Include="MainActivity.fs" />
<Compile Include="Resources\Resource.designer.fs" />
<Compile Include="Properties\AssemblyInfo.fs" />
</ItemGroup>
<ItemGroup>
<None Include="Resources\AboutResources.txt" />
<None Include="Properties\AndroidManifest.xml" />
<None Include="Assets\AboutAssets.txt" />
<None Include="packages.config" />
</ItemGroup>
<ItemGroup>
<Folder Include="Resources\layout\" />
<Folder Include="Resources\values\" />
</ItemGroup>
<ItemGroup>
<AndroidResource Include="Resources\drawable\icon.png" />
<AndroidResource Include="Resources\drawable-hdpi\icon.png" />
<AndroidResource Include="Resources\drawable-xhdpi\icon.png" /> …
```
=> Cycle9 fsharp item groups

main/src/addins/CSharpBinding/MonoDevelop.CSharp/PathedDocumentTextEditorExtension.cs
```
WARNING **: Gtk operations should be done on the main Thread
at System.Environment.get_StackTrace () [0x00000] in /private/tmp/source-mono-4.8.0/bockbuild-mono-4.8.0-branch/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/corlib/System/Environment.cs:321
at Gtk.Application.AssertMainThread () [0x00023] in /private/tmp/source-mono-4.8.0/bockbuild-mono-4.8.0-branch/profiles/mono-mac-xamarin/build-root/gtk-sharp-None/gtk/Application.cs:124
at Gtk.Icon.SizeLookup (Gtk.IconSize size, System.Int32& width, System.Int32& height) [0x00001] in /private/tmp/source-mono-4.8.0/bockbuild-mono-4.8.0-branch/profiles/mono-mac-xamarin/build-root/gtk-sharp-None/gtk/generated/Icon.cs:50
at MonoDevelop.Components.GtkUtil.GetSize (Gtk.IconSize size, System.Int32& width, System.Int32& height) …
```
=> [CSharp] Fix gtk call happening on the UI thread

main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.Tests/EvaluationTests.cs
Re-enabling unit test which was disabled in past because it randomly failed(only on Wrench), hopefully whatever was causing failure was fixed otherwise I will take a deeper look at cause of this
=> Bug 36712 - Disabled SdbEvaluationAllowTargetInvokesTests.FormatArray unit test

main/external/fsharpbinding/MonoDevelop.FSharp.Tests/UnusedOpens.fs, main/external/fsharpbinding/MonoDevelop.FSharpBinding/HighlightUnusedCode.fs
e.g. in the following code, `n.Operators` shouldn't be grayed out.
namespace n
module Operators =
let (+) x y = x + y
namespace namespace1
open n.Operators
module module1 =
let x = 1 + 1
=> [F#] Don't gray out open statements that contain operators. Fixes #52355

main/src/core/MonoDevelop.Core/MonoDevelop.Core/Runtime.cs, main/src/core/MonoDevelop.Ide/gtk-gui/MonoDevelop.Ide.Gui.OptionPanels.BuildPanelWidget.cs, main/src/core/MonoDevelop.Ide/gtk-gui/gui.stetic
And drop the "EXPERIMENTAL" tag from the build panel option.
=> [msbuild] Make msbuild the default build engine, instead of xbuild

main/Makefile.am
This works around a bug in the Mono runtime which NuGet exposes when restoring lots of packages, and should make the MonoDevelop build much more dependable. See https://bugzilla.xamarin.com/show_bug.cgi?id=51590
=> Explicitly force serial NuGet restore

main/src/addins/MonoDevelop.ConnectedServices/ConnectedServices.cs, main/src/addins/MonoDevelop.ConnectedServices/Gui.ServicesTab/ConnectedServicesViewContent.cs
This change makes the following features public:
* Open the services gallery for a given project
* Open the service details view for a given service
* Query services supporting a given project
* Remove a service from a project (asking user for confirmation)
Would it make sense to open more features? Like adding a service to a project and show the confirmation dialog (allowing to add a service to all referencing projects) maybe?
cc @sgmunn
=> Make Connected Services API public

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/OnTheFlyFormatter.cs
This issue is surfaced on cutting and pasting a 19k line file
(TensorFlowSharp with Operations.cs)
The code wasn't formatted in the old variant, causing a ton of changed
spans in the document. Because of this, we ended up recalculating the
whole indentation of the document in NRefactory millions of times (I
could count 30 million before it crashed, 18gb of allocations).
With this change, pasting only does one block change of the text with the
formatted text. This causes invalidation of more lines, but since there
is no proper way of batching text span replacements, this is the only
possible fix I could find.
The code has an extra allocation caused by getting the whole document
text then substring-ing it, because there is no way (afaik) to get a
subtext of a given text.
Common usage might …
=> [CSharp] Fix on the fly formatter performance issue

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs
Cause was LoadingFinished event cancels the current analysis before
the task continuation so token.IsCancellationRequested was always ==
true.
=> Fixed 'Bug 52378 - Code completion broken on standalone files'

main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpBinding.addin.xml
The F# Addin  has never used the settings in this file by default
because of an issue in how the addin.xml was originally set up here
https://github.com/fsharp/xamarin-monodevelop-fsharp-addin/commit/576b2c574edef126e387379aef77aaca6862d5a5
Now Tabs to Spaces defaults to true. Fixes #37557 and #51499
=> [F#] Make FSharpStylePolicy.xml default

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProjectService.cs
The HandleGlobalPropertyProviderChanged event is never hooked, only removed.
=> [Core] Fix possible typo in MSBuildProjectService

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpTextPasteHandler.cs
This changes the code so it uses the same C# formatter as in the document options. Fixes perf issue in TensorFlowSharp Operations.cs copy/paste whole code issue.
=> [CSharp] Use the C# formatter instead of OnTheFlyFormatter when pasting

main/external/fsharpbinding/MonoDevelop.FSharp.Tests/UnusedOpens.fs, main/external/fsharpbinding/MonoDevelop.FSharpBinding/HighlightUnusedCode.fs
With the following code
```
namespace n
module ActivePattern =
let (|NotEmpty|_|) s =
match s with
| "" -> None
| _ -> Some NotEmpty
namespace namespace1
open n.ActivePattern
module module1 =
let s = ""
match s with
| NotEmpty -> Some s
| _ -> None
```
`open n.ActivePattern` is greyed out.
Reported by Alex Corrado
Fixes #52470
=> [F#] Don't grey out Active Pattern case namespaces

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpTextPasteHandler.cs
On pasting a large block of unformatted code, the formatter would trim
the text. Fix this issue.
cc @DavidKarlas this should fix your issue
=> [CSharp] Fix formatting on pasting large blocks of unformatted code

main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/MonoRuntimeInfo.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/MonoTargetRuntime.cs, main/tests/UnitTests/MonoDevelop.Projects/LocalCopyTests.cs
Fixes bug #52341 - MonoDevelop.Projects.LocalCopyTests.LocalCopyDefault
assumes compiler produces mdb debug file
=> Fix debug file issue with Mono 4.9.x

main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/AssemblyBrowserWidget.cs
Before, the code was racy, as it was all attaching a ContinueWith on
LoadingTask, which caused the following semantics:
* On ViewContent loading, it would attach a task to scroll to the loaded
assembly.
* On actual Go To Definition call, it would attach a task that would
scroll to the real type we're searching for.
The order in which these two happen is inverse to the order of
attaching, we would scroll back to the first item, even though we did
all the node expansion and selection work for the real item.
The fix is to only scroll to the assembly if the current selected node
is null or equal to the root node.
=> [AssemblyBrowser] Fix scrolling to type when doing Go To Definition

main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebuggingService.cs
Problem was that session.Dispose(); happened before StoppedEvent was called which meant that Breakpoints.Remove(entryBreakpoint); that Inspector AddIn did didn’t have effect because session.Dispose(); already disconnected BreakpointStore.
=> Bug 51960 - App freezing whilst attempting to debug on iOS Simulator

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProject.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
Updating the MSBuildProject when writing the project is done with a lock
however the xml generation is done outside of this lock. If a project
builder is requested whilst the project file is being saved the
MSBuildProject can be updated in memory by two different threads. The xml
then passed to the project builder may then be incorrect if another thread
is currently updating the MSBuildProject. Now the MSBuildProject update
and the xml generation is done with the same write lock. Saving to file is
not done inside the write lock.
=> [vNext][Core] Fix potential race condition on updating MSBuildProject

main/src/addins/TextTemplating/Mono.TextTemplating/Mono.TextTemplating/TemplatingEngine.cs
Problem started with ca287231cfe2d12 where I required resolving of full path of assembly to be able to remove duplicates by comparing FullName of assembly. Which works fine in case of running inside IDE but when TextTransform.exe is used engine doesn’t resolve to full path but leaves GAC assemblies unresolved, which is OK since compiler can resolve this just fine later in process.
=> Bug 52855 - Failure to resolve System.Core when executing a t4 script

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs, main/tests/UnitTests/MonoDevelop.Projects/MSBuildGlobTests.cs
If a file is deleted then there is no need to add a Remove MSBuild item for that file. Only if the file is removed from the project but not deleted will a Remove MSBuild item be added.
=> [vNext] Do not add Remove MSBuild item if file does not exist

main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.Formats.MSBuild/ProjectBuilder.v4.0.cs, main/tests/UnitTests/MonoDevelop.Projects/MSBuildTests.cs, main/tests/test-projects/msbuild-tests/false.targets, main/tests/test-projects/msbuild-tests/foo.targets, main/tests/test-projects/msbuild-tests/project-with-custom-build-target2.csproj, main/tests/test-projects/msbuild-tests/project-with-custom-build-target3.csproj, main/tests/test-projects/msbuild-tests/show.targets, main/tests/test-projects/msbuild-tests/true.targets
Fixed bug #45276 - Global MSBuild properties not available when
building project programmatically
https://bugzilla.xamarin.com/show_bug.cgi?id=45276
Properties set when building a single project would not cause a
re-evaluation of the project and would not affect the build.
var context = new ProjectOperationContext ();
context.GlobalProperties.SetValue ("PackOnBuild", "true");
IdeApp.ProjectOperations.Build (project, operationContext: context);
Here PackOnBuild whilst set would not change any existing properties
that used its value when using MSBuild. This problem did not affect
xbuild.
Now the project is re-evaluated if global properties are set. These
properties are removed after the build and the project is re-evaluated
again so they do not affect the next build.
=> [vNext][MSBuild] Fix global properties not available for project build

main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebuggingService.cs
Problem was that session.Dispose(); happened before StoppedEvent was called which meant that Breakpoints.Remove(entryBreakpoint); that Inspector AddIn did didn’t have effect because session.Dispose(); already disconnected BreakpointStore.
=> C9 Bug 51960 - App freezing whilst attempting to debug on iOS Simulator

main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpOutlineTextEditorExtension.fs
Fixes the following exception
```
System.InvalidProgramException: Invalid IL code in <StartupCode$FSharpBinding>.$FSharpOutlineTextEditorExtension/updateDocumentOutline@55:Invoke (): IL_0000: ldarg.1   
at GLib.Timeout+TimeoutProxy.Handler (System.IntPtr data) [0x0003f] in /private/tmp/source-mono-4.8.0/bockbuild-mono-4.8.0-branch/profiles/mono-mac-xamarin/build-root/gtk-sharp-None/glib/Timeout.cs:73 
```
=> Fix document outline

main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/TextDocument.cs
Fix an issue with link text (53005). Root cause was that the TextDocument's "currentSnapshot" was wrong in the middle of an edit in which people were making edits from inside the TextChanged event.
=> Fix issues with linked text.

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/DefaultMSBuildEngine.cs, main/tests/UnitTests/MonoDevelop.Projects/MSBuildTests.cs
MSBuild items were not being excluded if the file name contained a
dot character as well as the dot with the file extension. An MSBuild
item such as:
<None Include="**/*" Exclude="**/*.user" />
Would not exclude the following file:
foo.csproj.user
=> [vNext] Fix dotted filenames not excluded by wildcard

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs, main/tests/UnitTests/MonoDevelop.Projects/MSBuildGlobTests.cs, main/tests/test-projects/msbuild-glob-tests/glob-import-test.csproj, main/tests/test-projects/msbuild-glob-tests/glob-import-test.targets, main/tests/test-projects/msbuild-glob-tests/glob-import-update1-test.csproj
Setting CopyToOutputDirectory to PreserveNewest will generate an
Update item for a wildcard item. If CopyToOutputDirectory is then
changed back to None the Update item would not be removed from
the project file.
=> [vNext] Remove Update item for wildcard after changes reverted 

main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/TargetRuntime.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Core.addin.xml, main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.Extensions/ImportSearchPathExtensionNode.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/DefaultMSBuildEngine.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildEvaluationContext.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProject.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProjectService.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/RemoteProjectBuilder.cs, main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.MSBuild.Shared/Main.cs, main/src/core/MonoDevelop.Projects.Formats.MSBuild/app.v15.0.config, main/tests/UnitTests/MonoDevelop.Projects/MSBuildSearchPathTests.cs, main/tests/UnitTests/UnitTests.csproj, main/tests/test-projects/msbuild-search-paths/ConsoleProject.csproj, main/tests/test-projects/msbuild-search-paths/extensions-path/15.0/Microsoft.Common.targets/ImportAfter/injected-target.targets, main/tests/test-projects/msbuild-search-paths/extensions-path/simple.props
This PR introduces a new extension point and additional api that allows registering custom fallback search paths for MSBuild properties. For example, it can be used to define additional search paths for $(MSBuildExtensionsPath), which means that add-ins can provide their own target files to be imported in projects.
Since MSBuild loads search paths from the builder's config file, and there is no API to dynamically register those paths, what MD does is to make a copy of the project builder into the local cache directory and then modifies the config file, adding the required search paths.
=> Add support for custom MSBuild search paths

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild.Conditions/ConditionRelationalExpression.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/DefaultMSBuildEngine.cs
This reduces duplicate string parsing and condition tokenizing/ConditionExpression creation.
Reduces runtime and allocations on a simple console project from 17MB to 8.1MB and runtime from 500ms to 300ms.
=> [Core] Memoize ConditionParser usage.

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs, main/tests/UnitTests/MonoDevelop.Projects/MSBuildTests.cs, main/tests/test-projects/console-project-with-wildcards/ConsoleProject-import.csproj, main/tests/test-projects/console-project-with-wildcards/ConsoleProject-import.csproj.saved1, main/tests/test-projects/console-project-with-wildcards/ConsoleProject-import.targets, main/tests/test-projects/console-project-with-wildcards/ConsoleProject.csproj.saved3, main/tests/test-projects/console-project-with-wildcards/ConsoleProject.csproj.saved4, main/tests/test-projects/console-project-with-wildcards/ConsoleProject.csproj.saved5, main/tests/test-projects/console-project-with-wildcards/ConsoleProject.csproj.saved6
When an MSBuildItem is included with a wildcard and then its BuildAction is changed the project should add a Remove item and an Include item. The Remove item will remove it from the original
wildcard group.
Wildcard:
<Content Include="**\*.txt" />
Changing a .txt file to be an EmbeddedResource should add the following items to the project:
<Content Remove="TextFile.txt" />
<EmbeddedResource Include="TextFile.txt" />
A simple fix for the above with a test has been added.
**TODO**
The following need to be tested and/or implemented.
=> [vNext] Support build action changing with wildcard include

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProject.cs, main/tests/UnitTests/MonoDevelop.Projects/MSBuildProjectTests.cs
Remove and Update items are now added to their own ItemGroups
instead of being added to ItemGroups containing just the same
MSBuild items.
ItemGroups created for Remove items are inserted before Include
and Update ItemGroups. Remove items are inserted after Include
ItemGroups that have wildcard glob includes.
ItemGroups created for Include items are inserted before Update
ItemGroups.
TODO:
=> [vNext] Order and group new Remove and Update items

main/src/addins/CSharpBinding/CSharpBinding.addin.xml
This class was removed in 1a7513e22 but it was not removed from .addin.xml which is causing errors in log files
=> [CSharpBinding] Remove ProtocolMemberContextHandler from .addin.xml

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdkPaths.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/DefaultMSBuildEngine.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProject.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProjectService.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/RemoteProjectBuilder.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs, main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.Formats.MSBuild/BuildEngine.cs, main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.Formats.MSBuild/BuildEngine.v4.0.cs, main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.Formats.MSBuild/ProjectBuilder.v4.0.cs, main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.MSBuild.Shared/BuildEngine.Shared.cs, main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.MSBuild.Shared/RemoteBuildEngineMessages.cs, main/tests/UnitTests/MonoDevelop.Projects/MSBuildSearchPathTests.cs, main/tests/test-projects/msbuild-search-paths/ProjectUsingMultiSdk.csproj, main/tests/test-projects/msbuild-search-paths/ProjectUsingSdk.csproj, main/tests/test-projects/msbuild-search-paths/ProjectUsingSdk2.csproj, main/tests/test-projects/msbuild-search-paths/sdk-path-2/Bar.Sdk/Sdk/Sdk.props, main/tests/test-projects/msbuild-search-paths/sdk-path-2/Bar.Sdk/Sdk/Sdk.targets, main/tests/test-projects/msbuild-search-paths/sdk-path-all/Bar.Sdk/Sdk/Sdk.props, main/tests/test-projects/msbuild-search-paths/sdk-path-all/Bar.Sdk/Sdk/Sdk.targets, main/tests/test-projects/msbuild-search-paths/sdk-path-all/Foo.Sdk/Sdk/Sdk.props, main/tests/test-projects/msbuild-search-paths/sdk-path-all/Foo.Sdk/Sdk/Sdk.targets, main/tests/test-projects/msbuild-search-paths/sdk-path/Foo.Sdk/Sdk/Sdk.props, main/tests/test-projects/msbuild-search-paths/sdk-path/Foo.Sdk/Sdk/Sdk.targets
Search paths for MSBuildSDKsPath are now supported, but they are handled in a special way, since MSBuild really doesn't support fallback paths for MSBuildSDKsPath. When loading a new project that has a reference to an SDK we now look for that SDK in any of the registered locations. If a location is found, the path is provided to the project builder, which sets the MSBuildSDKsPath env var before loading the project.
I have checked this with regular projects, but not with .NET Core projects. It may be necessary to remove custom SDK handling code from the .NET Core add-in.
=> Add support for SDKs fallback search paths

main/src/addins/MonoDevelop.GtkCore/MonoDevelop.GtkCore.GuiBuilder/GuiBuilderProject.cs
While trying to reproduce https://bugzilla.xamarin.com/show_bug.cgi?id=38967 I noticed bug...
=> [GTK#] Fix designer toolbox to show custom widget from assembly references

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/PackageSpecCreatorTests.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/DotNetCoreNuGetProject.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageSpecCreator.cs
If a project reference cannot be resolved when restoring a .NET
Core project a null reference exception was reported in the Package
Console output. Now a warning is logged in the Package Console
output and the restore is allowed to complete.
=> [NuGet] Handle missing project when restoring a .NET Core project

main/src/core/MonoDevelop.Core/MonoDevelop.Core.Text/TextChangeEventArgs.cs
The issue here is that TextChangeEventArgs.GetNewOffset was using an updated position to pass to later calls. I've gone ahead and got rid of TextChange.GetNewOffset (only this caller remained), and instead of updating the position, updated a changeDelta.
The *real* fix here is to switch things over to using tracking or snapshot points, but this at least fixes the issue at hand (and potentially others), and we can debate switching over to the other data structures later.
=> Fix for https://bugzilla.xamarin.com/show_bug.cgi?id=53412

main/src/addins/CSharpBinding/Util/SymbolKeyExtensions.cs
This API was changed here:
https://github.com/dotnet/roslyn/commit/7ce073360b455fa7ba0054a377687e392b6cebd2#diff-0305ff927cc9a81ca44025667b546ccbR105
There is no need to fix this on master because roslyn-ivt branch doesnt have this code anymore(no more reflection ftw).
=> Bug 52716 - [Cycle 9] "Quick Fix > Encapsulate field: '...' (and use property)" refactoring command does nothing

main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.Formats.MSBuild/ProjectBuilder.v4.0.cs, main/tests/UnitTests/MonoDevelop.Projects/MSBuildTests.cs, main/tests/test-projects/dotnetcore-console/Sdks/Test.Import.Sdk/Sdk/Sdk.props, main/tests/test-projects/dotnetcore-console/Sdks/Test.Import.Sdk/Sdk/Sdk.targets, main/tests/test-projects/dotnetcore-console/Sdks/Test.Import.Sdk/Sdk/test-import.targets, main/tests/test-projects/dotnetcore-console/dotnetcore-console/dotnetcore-msbuildsdkspath-import.csproj, main/tests/test-projects/dotnetcore-console/dotnetcore-msbuildsdkspath-import.sln
Fixed 'The target "Build" does not exist in the project.' error when
building an ASP.NET Core project. The Microsoft.NET.Web.Sdk MSBuild props and targets use the MSBuildSdksPath property when importing other
MSBuild files. The MSBuildSDKsPath property is now explicitly
set as a global property for the project so the MSBuild props and
targets are now correctly imported.
=> [Core] Fix build error when building ASP.NET Core project

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Solution.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionFolder.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionItem.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionItemEventArgs.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbarController.cs
Always set workspace ActiveConfigurationId to a fully expanded one to
prevent unnecessary reloading of project files. For some projects the
SelectActiveConfiguration method first set the ActiveConfigurationId to
non-expanded version (eg. “Debug”) and later called SelectActiveRuntime
which set it again to an expanded one (eg. “Debug|Mixed Platforms”).
This resulted in double reloading of the project files.
=> Always set workspace ActiveConfigurationId to a fully expanded one

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs, main/tests/UnitTests/MonoDevelop.Projects/MSBuildTests.cs, main/tests/test-projects/console-project-imported-wildcard/ConsoleProject-imported-wildcard.csproj, main/tests/test-projects/console-project-imported-wildcard/Imports/AllCSharpFiles.props, main/tests/test-projects/console-project-imported-wildcard/Program.cs, main/tests/test-projects/console-project-with-wildcards/ConsoleProject.csproj.saved7
Fixed bug #53428 - Erroneous "Save failed" popup dialogs when adding
a new file to a .NET Standard Library
https://bugzilla.xamarin.com/show_bug.cgi?id=53428
Creating a new .NET Standard Library, then removing the single
Class1.cs file from the project and then adding a new C# class
file would result in two Save failed dialogs being displayed due to
a null reference exception. The problem was that when the last file
was removed from the project the unused glob item was being removed.
This glob item was imported and would then have its parent project
set to null. This glob item was then re-used when saving the project
again a second time after the new file was added and resulted in a
null reference exception. To fix this the unused glob item is not
removed if it is imported and does not …
=> [Core] Fix save failed after deleting file from .NET Core project

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/NewProjectController.cs
This is #1985 for 15.1:
This patch adds recent template filtering by the template visibility (solution/project) to the new project dialog.
(fix bug #53443)
=> [53443][Ide] Filter recent templates by visibility in new project dialog

main/src/addins/WindowsPlatform/WindowsPlatform/MainToolbar/TitleMenuItem.cs, main/src/core/MonoDevelop.Ide/options/KeyBindingSchemeVisualStudio-mac.xml, main/src/core/MonoDevelop.Ide/options/KeyBindingSchemeVisualStudio.xml
+Concise key binding shortcuts in menu items on Windows to be more consistant with VS (turn `Control+XXX` into `Ctrl+XXX`)
(fix bug #52984)
=> [52984][Ide] Update default format document key in VS key bindings

main/external/fsharpbinding/MonoDevelop.FSharp.Tests/TestWorkbenchWindow.fs, main/src/addins/MacPlatform/MacPlatform.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestSession.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components.DockNotebook/DockWindow.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DefaultWorkbench.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/HiddenWorkbenchWindow.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/IWorkbenchWindow.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/SdiWorkspaceWindow.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Ide.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/RootWorkspace.cs, main/tests/UnitTests/MonoDevelop.CSharpBinding/TestWorkbenchWindow.cs
If a workbench window contains an unsaved document, we ask the user to save it and run the save operation asynchronously. This is controlled by the WorkbenchWindowEventArgs.Cancel property and the result contols whether we set specific Gtk/GLib events as hanled or not (i.e. in order to allow or disallow Gtk to close a window).
The first problem here was the async EventHandler for the Closing event (https://github.com/mono/monodevelop/blob/master/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs#L844-L868) which was not awaited and the window was closed before the Save operation had a chance to run to completion. This is solved by an EventHandler delegate returning a Task, making it possible to await the handlers subscribed to the event (see …
=> [53089][Ide] Fix IWorkbenchWindow.Closing event handling with async operations

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.UnitTesting/DotNetCoreProjectTestSuite.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.UnitTesting/DotNetCoreTestPlatformAdapter.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.csproj, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectReader.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreRuntime.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdk.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdkInstalledCondition.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdkPaths.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetMigrate.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/MSBuildSdks.cs, main/src/addins/MonoDevelop.DotNetCore/Properties/MonoDevelop.DotNetCore.addin.xml
Also cache the .NET Core Sdk location and whether it is installed to prevent it from being run multiple times when checking the project templates should be hidden or not.
=> [DotNetCore] Hide project templates if .NET Core Sdk is not installed

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs
Creating a new F# .NET Core project would display duplicate F# files
(.fs) in the Solution window. Reloading the project would fix the
duplicates. When creating a new project the FSharp.NET.Sdk NuGet
package's imported MSBuild properties are not available so the
imported F# files from the default Microsoft.NET.Sdk MSBuild imports
are applied. This results in imported F# files as well as those
defined in the project and causes duplicate files in the Solution
window. To fix this imported F# files are ignored and not added to
the project since they will be defined directly in the project.
=> [DotNetCore] Fix duplicate F# files in Solution window

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs
When FSharp.NET.Sdk 1.0.0 was used by a project the build would fail
without the MSBuildExtensionsPath being overridden to point to the
correct folder where the .NET Core sdk was installed. Creating a new
F# project uses FSharp.NET.Sdk 1.0.* which installs the latest
version which currently is 1.0.2. FSharp.NET.Sdk 1.0.1 and above
now use the MSBuildSDKsPath instead of the MSBuildExtensionsPath so
the workaround is no longer needed.
=> [DotNetCore] Remove F# build workaround

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/RoslynSymbolCompletionData.cs
Xamarin.iOS for instance is using those custom attributes and this seems to be the simplest change to handle them.
Also their `ContainingNamespace` isn't `System`.
This change is unlikely to clash with something else.
=> [RoslynSymbolCompletionData] Handle Deprecated and Obsoleted attributes

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/FinalProjectConfigurationPage.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkProjectConfigurationWidget.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/NewProjectController.cs
Fix bug #53670: [New Project Dialog] Remove "Create a project directory within the solution directory" when adding projects to existing solution
(https://bugzilla.xamarin.com/show_bug.cgi?id=53670)
We need to prevent users from unchecking "Create a project directory within the solution directory" when adding projects to existing solution.
This is an action that can break projects if the user chooses to override files (users mistake because we ask confirmation but still there's no point in allowing that).
=> [NewProjectDialog] Disable 'Create a project directory within the solution directory' when adding projects to existing solution

main/tests/UnitTests/MonoDevelop.Projects/MSBuildTests.cs
Fixed tests that were failing due to different project line endings.
Disable some build tests on Windows.
Fixed a test failing due to different directory separator used on Windows.
=> Fixed some failing tests on Windows

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreRunConfiguration.cs
https://trello.com/c/n8OQw3tp/136-use-external-console-by-default-for-net-core-console-projects-and-web-projects
=> [DotNetCore] Change default for ExternalConsole to true for .Net Core projects(to match .NET projects)

main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/BreakpointPropertiesDialog.cs
@slluis can you verify this is something that we want?
Logic behind selecting whole text is that if user wants to change exception type... it just has to start typing and since text is selected it will delete it...
=> Bug 52946 - Exception catchpoint dialog should have System.Exception selected by default

main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpProject.fs
Adding a new F# file to an xUnit .NET Core project would add four
empty ItemGroup elements to the project file. xUnit .NET Core
projects use a wildcard include for F# files unlike the other F#
.NET Core projects.
=> [F#] Fix empty ItemGroups added to .NET Core project

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionItem.cs
* This method is used by the XAML forms previewer and by the iOS Designer.
When a storyboard belong to a Shared Asset project we need to find the iOS project which references that shared asset project.
=> [Core] Added `GetReferencedExtensionsFromFlavor` to `SolutionItem`.

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/MSBuildSdks.cs
I was getting an exception on startup -- leading to the dialog that extensions ... couldn't be loaded -- because binPath was coming up null.
This is just a Band-Aid. Matt should take a look at decide whether this is the proper fix (and either merge it or just remove the Don't Merge Yet label).
=> Prevent exception from being thrown on startup

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs
Otherwise it will try to find the new document in the old project and fail, causing analysisDocument to be null. And when analysisDocument is null, various language services are turned off.
The symptom was when calling Save As on a .css file completion stopped working. I've verified that after this call is made completion works fine after SaveAs on a .css file.
=> When an ad-hoc document is renamed unload the Adhoc project

main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SearchAndReplaceWidget.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components/SearchEntry.cs
Not exactly sure how that bug happened. The search entry threw an
exception before that search & replace widget lock. Remember: always
include full logs when reporting bugs.
Catched an exception in search & replace widget - that event handler
should never crash the IDE.
=> Fixed 'Bug 54010 - NullReference in SearchAndReplaceWidget kills XS'.

main/src/addins/MonoDevelop.UnitTesting.NUnit/MonoDevelop.UnitTesting.NUnit/ExternalTestRunner.cs, main/src/addins/MonoDevelop.UnitTesting.NUnit/MonoDevelop.UnitTesting.NUnit/NUnitAssemblyTestSuite.cs
Since 06a9d3ef1d Dispose was not blocking anymore for process to finish, causing dispose of console to happen before process terminated hence NRE exceptions.
=> Bug 53371 - "Debugger Operation Failed" when trying to debug an NUnittest after the test finishes

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreRuntime.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdk.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/MSBuildSdks.cs
Allow other addins to check if the .NET Core SDKs and the runtime is
installed.
=> [DotNetCore] .NET Core SDK and runtime detection are now public

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/Formats/Sublime3Format.cs
This adds support for :ascii: regex class, for 0-127 char values.
Fixes css and C++ syntax files which were triggering 'unknown unicode category : ^ascii'
cc @mkrueger: I'm not sure this is supposed to be just _printable_ ascii characters, which in turn would be 0x20 - 0x7E.
=> [Highlighting] Implement :ascii: class

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextEditor.cs
Bug was caused in ffc89f1c0 with changes in main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextEditorDisplayBinding.cs [Direct Link](https://github.com/mono/monodevelop/commit/ffc89f1c0b40e7883269fa5035d70e925991d6bb#diff-e9cb993b3a2ae4b0bf4a2c716a2a9bd0) file which changed to set MimeType during construction instead after construction which resulted in MimeTypeChanged event not being triggered hence tooltip providers not set, hence no tooltips
@mkrueger 
/cc: @slluis @sevoku
=> Fix tooltips in editor

main/src/core/MonoDevelop.Ide/MonoDevelop.Components/PathBar.cs
PathEntry constructor is not called from UI Thread so postpone contraction of UI elements until they are actually requested from UI thread
=> Fix errors caused by UI elements access from background threads

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/Formats/Sublime3Format.cs
This allows patterns such as [^:ascii:] used in the LESS.tmLanguage file.
=> [Regex] Fix parsing negative character classes

main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/MsNetTargetRuntime.cs
This adds a search for Visual Studio installation via registry keys. Also, fix this so it doesn't statically look for 15.0, but actually probes for toolsVersion.
=> [Core] Fix MSBuild tools probing for MSBuild 15 on Windows

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Gui/PackageSourcesWidget.cs
Adding `SemanticModelAttribute` to PackageSourceWidget like
https://github.com/mono/monodevelop/blob/master/main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/BreakpointPad.cs#L105-L108
=> PackageSourceWidget: Add SemanticModelAttribute to packageSourcesStore

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/RemoteProjectBuilder.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs, main/tests/UnitTests/MonoDevelop.Projects/MSBuildTests.cs, main/tests/test-projects/DotNetCoreProjectReference/DotNetCoreNetStandardProject/Class1.cs, main/tests/test-projects/DotNetCoreProjectReference/DotNetCoreNetStandardProject/DotNetCoreNetStandardProject.csproj, main/tests/test-projects/DotNetCoreProjectReference/DotNetCoreProjectReference.sln, main/tests/test-projects/DotNetCoreProjectReference/DotNetCoreProjectReference/DotNetFrameworkProject.csproj, main/tests/test-projects/DotNetCoreProjectReference/DotNetCoreProjectReference/MyClass.cs, main/tests/test-projects/DotNetCoreProjectReference/DotNetCoreProjectReference/Properties/AssemblyInfo.cs, main/tests/test-projects/DotNetCoreProjectReference/NoProjectReference.sln, main/tests/test-projects/DotNetCoreProjectReference/NoProjectReference/DotNetFrameworkProject.csproj, main/tests/test-projects/DotNetCoreProjectReference/NoProjectReference/MyClass.cs, main/tests/test-projects/DotNetCoreProjectReference/NoProjectReference/Properties/AssemblyInfo.cs
When a non .NET Core project references a .NET Core project the
build would fail with an error similar to:
Error MSB4019: The imported project
"~/Library/Caches/VisualStudio/7.0/MSBuild/8209_1/Sdks/Microsoft.NET.Sdk/Sdk/Sdk.props" was not found.
The MSBuildSDKsPath was not defined when building the project that
references the .NET Core project. Now a check is made of the
referenced projects and the MSBuildSDKsPath is set there is a
.NET Core project referenced.
=> [Core] Fix build error when .NET Core project is referenced

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/RegexEngine/Regex.cs, main/tests/UnitTests/MonoDevelop.Ide.Editor/RegexTests.cs
Was caused by a change in the regex engine usage. With the switch to
the vs editor editor operations have become too unefficient for
regular expressions and regexes have been switched to plain strings
again.
=> Fixed 'Bug 54152 - Crash caused by regex tests'

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/syntaxes/Yaml/Yaml.sublime-syntax
@madskristensen wanted to make sure MonoDevelop has support for .yml files. Turns out we already have support but just don't support the .yml extension. This one-liner adds that.
=> Add the .yml file extension for Yaml

main/winbuild.bat
'#' is not working as a comment in windows .bat files, resulting in:
```
'#' is not recognized as an internal or external command,
operable program or batch file.
```
=> Fix comment in winbuild.bat (# is not a valid comment in .bat files)

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionFolder.cs
Problem was that Solution.EntrySaved didn’t work for project that were inside SolutionFolder, hence runConfiguration were not updated
@slluis API changed a bit to more specific delegate so event can nicely propagate... This even is not used anywhere in monodevelop + md-addins source code + this is 7.0 change, so it should be OK change imo...
=> Bug 54132 - Run configurations for library projects do not show up

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Highlighting/KeywordHighlighters/AbstractAsyncHighlighter.cs
Haven't found a use case where it could happen - fixing the exception
is easy. I guess that an invalid/incomplete c# AST construct could
cause that.
=> Fixed ' Bug 54228 - AsyncMethodHighlighter null reference exception'.

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/DockFrameTopLevel.cs
This happens in case of ErrorPad being in AutoShow pad… Problem is that DockerFrame.UseWindowsForTopLevelFrames == false on Windows which results in ContainerWindow=null, hence exception
@iainx This was added for a11y to put title on window on Mac.. what will outcome of not setting this on Windows since it's not implemented as window...
=> Bug 54156 - double clicking on error bubble in editor crashes

main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/AssemblyNodeBuilder.cs, main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/NamespaceBuilder.cs
doesn't do anything for things without a namespace'
There wasn't a reason that global types were put into the '-'
namespace now they're ordered in the tree at the right position so the
find algorithm can find them properly.
=> Fixed 'Bug 43741 - Double clicking on search result or reference

main/tests/UnitTests/MonoDevelop.Projects/FlavorMigration.cs, main/tests/UnitTests/MonoDevelop.Projects/GetSourceFilesAsyncTests.cs, main/tests/UnitTests/MonoDevelop.Projects/ItemMetadataTests.cs, main/tests/UnitTests/MonoDevelop.Projects/LocalCopyTests.cs, main/tests/UnitTests/MonoDevelop.Projects/MSBuildGlobTests.cs, main/tests/UnitTests/MonoDevelop.Projects/MSBuildLoggerTests.cs, main/tests/UnitTests/MonoDevelop.Projects/MSBuildProjectTests.cs, main/tests/UnitTests/MonoDevelop.Projects/MSBuildSearchPathTests.cs, main/tests/UnitTests/MonoDevelop.Projects/MSBuildTests.cs, main/tests/UnitTests/MonoDevelop.Projects/MakefileTests.cs, main/tests/UnitTests/MonoDevelop.Projects/MdsTests.cs, main/tests/UnitTests/MonoDevelop.Projects/PolicyTests.cs, main/tests/UnitTests/MonoDevelop.Projects/ProjectCapabilityTests.cs, main/tests/UnitTests/MonoDevelop.Projects/ProjectReevaluationTests.cs, main/tests/UnitTests/MonoDevelop.Projects/ProjectTests.cs, main/tests/UnitTests/MonoDevelop.Projects/RunConfigurations.cs, main/tests/UnitTests/MonoDevelop.Projects/SharedAssetsProjectTests.cs, main/tests/UnitTests/MonoDevelop.Projects/SolutionFolderTests.cs, main/tests/UnitTests/MonoDevelop.Projects/SolutionTests.cs, main/tests/UnitTests/MonoDevelop.Projects/StringTagTests.cs, main/tests/UnitTests/MonoDevelop.Projects/TestProjectsChecks.cs, main/tests/UnitTests/MonoDevelop.Projects/WebProjectTests.cs, main/tests/UnitTests/MonoDevelop.Projects/WorkspaceTests.cs
Potentially reduce the risk of running out of resources (such as thread pool
threads) due to having too many project builders active.
=> Dispose solutions and projects in unit tests

main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/LanguageService.fs
Was seeing operation cancelled messages from the compiler when
passing in the output file name along with the source files
themselves for project references.
The key just needs to be unique for each project.. and as we have the
source code, there is no need for the compiler to parse the assemblies.
This results in _much_ faster time before intellisense etc. works
=> [F#] Faster project reference parsing

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProjectService.cs, main/tests/UnitTests/MonoDevelop.Projects/ProjectTests.cs, main/tests/test-projects/generic-project-with-import/GenericProject/GenericProject.mdproj, main/tests/test-projects/generic-project-with-import/generic-project.sln
Keep reading the project file for a PropertyGroup element. This
fixes the unknown project type message currently shown when opening
the po.mdproj project.
=> [Core] Handle generic projects with first element not PropertyGroup

main/winbuild.bat
The way the F# projects are set up right now at the bottom of the .fsproj we import StrongNamer.targets, but at the time of evaluation the packages are not restored yet and so the StrongNamer.targets are not imported. They are only imported during subsequent builds when the targets file is already present on disk.
This change calls into Paket and restores packages for the MonoDevelop.FSharpBinding project, which includes StrongNamer. This ensures that by the time the build evaluation happens the targets file for StrongNamer is already on disk.
=> Restore Paket references before building on Windows.

main/external/fsharpbinding/MonoDevelop.FSharp.Tests/TestHelpers.fs
Initialize XWT before initializing the desktop service, otherwise
the Mac platform initialization crashes.
=> Try to fix F# unit test failures

main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeActionEditorExtension.cs
Problem was that root.Span.Start starts with `using System;` but file has a lot of comment(license) before `using System;` which meant that root.Span.Length was very small(.End-.Start) and was outside of diagnostics, hence comparing with .End is more correct…
=> Bug 54301 - Implement interface missing from Quick Fixes

main/external/fsharpbinding/MonoDevelop.FSharp.Tests/SemanticHighlighting.fs, main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpSyntaxMode.fs
In the following code
```fsharp
type o = System.Object
```
the word System is highlighted incorrectly. Fixed to highlight as a
namespace.
=> [F#] Semantic highlighting fix

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/EditorTheme.cs
The exception in that bug looks like a threading issue.
=> Fixed 'Bug 54031 - NullReference in editor theming during startup'

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProject.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
When determining the MSBuildSdkPath to be used for a project, take into
account all referenced projects, including references of references.
=> Fix bad sdk import

main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.Formats.MSBuild/ProjectBuilder.v4.0.cs
It happened when trying to run a target on a project that has not been
saved to disk.
=> Fix crash when building temp project

main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/TextSegmentMarker.cs
PangoLayout's IndexToPos wants the byte offset into the
string and is storing data in UTF-8. Since we're currently
passing in the character offset the red wavy underlines are
misplaced when text before the error includes any multi-byte
characters.
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=53000
=> [TextEditor] Use the byte offset into the UTF8 string

main/src/core/MonoDevelop.Startup/MonoDevelop.Startup.csproj, main/src/core/MonoDevelop.Startup/packages.config
The problem is that editbin.exe is only found inside VS 2017 install path and that path isn't even well defined (unlike in previous VS releases). Additionally if we want to build on CI servers that path may not be available.
After much deliberation on where to get editbin.exe I've decided to create a NuGet package "LargeAddressAware" that downloads editbin.exe (and link.exe which is required, editbin.exe just calls into link.exe) and has a targets file that injects a call to editbin after CoreCompile is done.
See https://github.com/KirillOsenkov/LargeAddressAware
The target will only run on Windows (OS != Unix) and only when the LargeAddressAware MSBuild property is set.
Note that this is all temporary since Roslyn already has a plan to add LARGEADDRESSAWARE support to the compiler …
=> Use the LargeAddressAware NuGet package to reliably find editbin.exe.

main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git.csproj
On Windows when building we see an error:
```
C:\Temp\monodevelop\main\src\addins\VersionControl\MonoDevelop.VersionControl.Git\gtk-gui\generated.cs(17,17): Error CS0436: The type 'BinContainer' in 'C:\Temp\monodevelop\main\src\addins\VersionControl\MonoDevelop.VersionControl.Git\gtk-gui\generated.cs' conflicts with the imported type 'BinContainer' in 'MonoDevelop.SourceEditor, Version=2.6.0.0, Culture=neutral, PublicKeyToken=3ead7498f347467b'. Using the type defined in 'C:\Temp\monodevelop\main\src\addins\VersionControl\MonoDevelop.VersionControl.Git\gtk-gui\generated.cs'. (CS0436) (MonoDevelop.VersionControl.Git)
```
=> Disabling TreatWarningsAsErrors in VersionControl.Git.

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/DefaultMSBuildEngine.cs, main/tests/UnitTests/MonoDevelop.Projects/MSBuildGlobTests.cs, main/tests/test-projects/msbuild-glob-tests/glob-test2.csproj
Fixed bug #54342 - Long load times for .NET Core projects with
node_modules
https://bugzilla.xamarin.com/show_bug.cgi?id=54342
If an ASP.NET Core project uses say Gulp that will add lots of files
into the node_modules directory. This was causing a long load time.
The slow part was the DefaultMSBuildEngine's Evaluate method which
with 4200+ files in the node_modules directory would take around 2.5s
for each Evaluate method call. On loading a solution with one project
the Evaluate method would be called 6 times. Without the node_modules
directory the Evaluate method would take about 150ms for each call.
To fix this a regex is created when adding items for the excluded
directories. Directories and files inside these excluded directories
are ignored. For .NET Core there are wildcard includes …
=> [Core] Improve load times for ASP.NET Core projects

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/RestoreAndCheckForUpdatesAction.cs
If the solution contained .NET Core and non .NET Core projects
then the restore for the .NET Core projects would fail with a
null reference exception since the projects list was not populated.
=> [NuGet] Fix null reference on restoring packages

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/RestoreAndCheckForUpdatesAction.cs
Fixed a null reference exception preventing .NET Core projects from being
restored when they are created. This null ref was introduced by the change
made in the previous commit 42c209064228cfbbb4d6dbf0190032212f0fd927
=> [NuGet] Fix new .NET Core projects not being restored after creation

main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.Formats.MSBuild/ProjectBuilder.v4.0.cs
It happens when trying to run a target on a project that has not yet
been saved to disk.
=> [Core] Fix NRE in project builder

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/RoslynSymbolCompletionData.cs, main/tests/UnitTests/MonoDevelop.CSharpBinding/AutomaticBracketInsertionTests.cs
instead of offering completions'
=> Fixed 'Bug 54423 - Code completion automatically closes parenthesis,

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.NodeBuilders/DotNetCoreProjectNodeBuilderExtension.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.NodeBuilders/DotNetCoreProjectNodeCommandHandler.cs, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.csproj, main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs
If a file is copied into the project folder, or Save As is used with a file open in the editor, the file will not appear in the Solution window until the project is reloaded. Currently there is no file watcher support so for now the Refresh menu when you right click a project in the Solution window will re-evaluate the project so the files added will be displayed.
This is a partial fix for [bug #54474](https://bugzilla.xamarin.com/show_bug.cgi?id=54474)
=> [DotNetCore] Support refreshing the solution window

.gitmodules
https://github.com/mono/xwt/commit/550859d8a3a48f90017b79f6b67284ee90b2bc40 fixes an NRE when Xwt widgets are finalized without being disposed.
=> Bump Xwt, Fix unit tests finalizer NRE

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/RestoreAndCheckForUpdatesAction.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
Fixed bug #54327 - .NET Core project build fails when solution's location is moved
https://bugzilla.xamarin.com/show_bug.cgi?id=54327
Creating a new ASP.NET Core project, building it, closing the
solution, moving the solution to another folder, then opening it and
building it would show lots of build errors. The problem is that
the generated projectname.nuget.g.props file specifies the full path
to the project.assets.json file. The project.assets.json file
defines the NuGet packages and assemblies referenced. Since the
path to this file is now incorrect on moving the solution no
references are found by MSBuild since it cannot find the
project.assets.json file. Visual Studio handles this by always
restoring the solution when it is opened. So we now do the same for
.NET Core projects.
Also …
=> [NuGet] Fix .NET Core project build error after location changed 

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.Policies/PolicyContainer.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.Policies/PolicyService.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.Policies/PolicySet.cs
Sanitized a bit the policy container code. There Get(Type) and Get<T> methods
were supposed to have the same behavior, but they had different
implementations. Now all Get methods are based on the same code.
The real fix is that inheritsSet and inheritsScope are serialized only when
a policy was really found for that set and scope. Until now it was always
stored, so when deserializing, if the policy wasn't in the set for that
scope, it would crash.
=> Fix bug #54691 - Preferences aren't stored

main/src/addins/AspNet/MonoDevelop.AspNet.csproj, main/src/addins/AspNet/Projects/AspNetCoreFileTemplateCondition.cs, main/src/addins/AspNet/Properties/MonoDevelop.AspNet.addin.xml, main/src/addins/AspNet/Templates/AspNetCore/WebApiController.xft.xml
Fixed bug #54313 - ASP.NET Core project - Add New File should have a
template for Controller class
https://bugzilla.xamarin.com/show_bug.cgi?id=54313
Add a basic file template for an ASP.NET Core Web API Controller.
This file template is only available for ASP.NET Core Web projects.
=> [AspNet] Add ASP.NET Core Web API Controller file template

main/src/core/MonoDevelop.Core/MonoDevelop.Core.Text/TextFileUtility.cs
adding file or folder'.
The encodings handle the boms. Stripping them before just strips the
first chars of the file.
=> Fixed 'Bug 54631 - First two characters in project file removed when

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpTextEditorIndentation.cs, main/tests/UnitTests/MonoDevelop.CSharpBinding/CSharpTextEditorIndentationTests.cs
creates two strings joined with '+''
Re-enabled the tests that would've detected that. It was caused by a
slight incompatibility - line offsets are no longer updated on text
replace operations.
=> Fixed 'Bug 54676 - Pressing return in a string literal no longer

main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs, main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/TextMarker/GrayOutMarker.cs
Was caused by overlapping gray out markers. They're now using the cairo alpha value & color is corrected in the text view margin.
=> Fixed 'Bug 54500 - Difficult to read text'

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/Formats/OldFormat.cs
Preview 4'
The original bug is invalid, but it shows a break with importing old
schemes that have the base scheme attribute set.
=> Fixed 'Bug 54888 - Highlight Current Line doesn't work in VS for Mac

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.SharedAssetsProjects/SharedAssetsProject.cs, main/tests/Ide.Tests/ProjectTemplateTests.cs
Fixed bug #54909 - Adding new shared project to existing solution has
MyClass.cs defined as None MSBuild item
https://bugzilla.xamarin.com/show_bug.cgi?id=54909
Adding a new shared project to an existing solution was defining the
language name too late so the language binding was null on adding
the MyClass.cs file to the project so its build action was not
marked as Compile. The SharedAssetsProject was calling
the base class OnInitializeFromTemplate method before setting the
language name. On adding a new shared assets project to an existing
solution the ProjectCreateInfo's TemplateInitializationCallback is
set which causes the MyClass.cs file to be added to the project.
The TemplateInitializationCallback is null when a new solution is
being created but not when adding a project to an …
=> [Core] Fix build action when adding new shared project to solution

main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ImmediatePad.cs
Bug name says “anymore” suggesting it’s regression, which I think is not true…
Problem was that Immidate pad on purpose ignore disabled implicit evaluation since thats exactly what user invoked, but it also ignored for members which caused unintended effects by users, hence bugs, this is same as VS does it…
Also noticed VS does `ops.GroupPrivateMembers = false;`
=> Bug 54647 - You cannot disable implicit property evaluation in XS anymore

main/src/core/MonoDevelop.Ide/MonoDevelop.Components/GtkUtil.cs
This is probably a simple fix inside gtk+ but I'm having trouble getting my gtk Windows build scripts working. Would it be okay to merge this into monodevelop, and then if I can get it fixed in gtk then we can revert it?
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=54155
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=40188
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=40174
=> [Windows] HDPI icon scaling fixes

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Refactoring/CodeGenerationService.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
document'
I haven't found a repro case but the code generation service is now
much simpler. I guess that a reload may've messed up the project
id/project data map clearing these on solution load would fix that.
=> Fixed 'Bug 54711 - NullReference trying to insert code into a

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreRunConfiguration.cs
Fixed bug #54316 - ASP.NET Core project - Start debugging and then
stop, it does not close the terminal window
https://bugzilla.xamarin.com/show_bug.cgi?id=54316
New ASP.NET Core projects now do not use an external console by
default. New .NET Core console projects will still use an external
console by default. This makes new ASP.NET Core project's behaviour
the same as the existing ASP.NET projects.
=> [DotNetCore] ASP.NET Core projects do not use external console by default

main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs
Because its causing a lot of spam in log, confusion and false diagnostics in bug reports without any benefit in diagnosing problems
=> Removing warning from log file when breakpoint is outside file size

main/src/addins/AspNet/Templates/AspNetCore/WebApiController.xft.xml, main/src/addins/AspNet/Templates/Mvc/Controller.xft.xml, main/src/addins/AspNet/Templates/Mvc/WebConfigViews.xft.xml, main/src/addins/AspNet/Templates/MvcCommon/HomeController.cs, main/src/addins/AspNet/Templates/RouteConfig.cs, main/src/addins/AspNet/Templates/WebApiConfig.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/FileTemplateTagsModifier.cs
Fixed bug #55012 - New ASP.NET projects do not compile
https://bugzilla.xamarin.com/show_bug.cgi?id=55012
The default naming policy was changed for new files so it matches
Visual Studio: f8d5ae2
This change broke the ASP.NET MVC project templates since they expect
the files to have specific namespaces and now no longer compile.
The ASP.NET Project templates now use the RootNamespace instead of
the Namespace property in certain file templates so the expected
namespaces are created. The RootNamespace is the default namespace
used by the project if the file is created in the project's directory
and not in a sub-folder. This also means that the project templates
should now work for any namespace policy configured.
=> [AspNet] Fix MVC project templates after default policy changes

main/external/fsharpbinding/MonoDevelop.FSharpBinding/Templates/PortableLibrary.xpt.xml
Creating a new F# PCL project would fail to install the FSharp.Core
NuGet package since some of its dependencies were not available
with the F# addin. Also fixed a compilation error due to an
uncommented line.
=> [F#] Fix PCL project template

main/src/addins/AspNet/MonoDevelop.AspNet.csproj, main/src/addins/AspNet/packages.config, main/src/addins/TextTemplating/MonoDevelop.TextTemplating/MonoDevelop.TextTemplating.csproj, main/src/addins/TextTemplating/MonoDevelop.TextTemplating/packages.config
This way that the reference Mono.TextTemplating.dll is automatically signed when copied to output directory.
This fixes bug https://bugzilla.xamarin.com/show_bug.cgi?id=54679 where MonoDevelop crashes with:
Could not load file or assembly 'Mono.TextTemplating, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
=> Add StrongNamer to MonoDevelop.TextTemplating and MonoDevelop.AspNet.

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs
breaks IntelliSense'
It was caused by the project wasn't set correctly after save as.
=> Fixed 'Bug 55051 - Save As of a file that is part of a Core project

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/SingleFileDescriptionTemplate.cs
Project templates can now specify the CustomToolNamespace for files
that are added to a project.
<File
name="MyRazorView.cshtml"
src="MyRazorView.cshtml"
CustomTool="RazorTemplatePreprocessor"
CustomToolNamespace="${RootNamespace}" />
=> [Ide] Allow CustomToolNamespace to be set in project templates

main/src/addins/MonoDevelop.DotNetCore/Properties/AddinInfo.cs
=> Add add-in dependency from DotNetCore to PackageManagement

main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.csproj
The generated gtk-gui files have warnings in them.
=> Disable TreatWarningsAsErrors in MD.VersionControl.csproj

main/src/core/MonoDevelop.Core/MonoDevelop.Core/UnixSystemInformation.cs
Strip out identifying data from the logs. The same as -a but without the network nodename.
Two options that would not appear on Linux because of this would be processor and hardware platform information.
=> [About] Don't print out machine node name

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs
When running or debugging a .NET Core project without using the
external console the Application Output window created now has the
project name in its title. This matches the behaviour for .NET
projects.
=> [DotNetCore] Set application output window name

main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/TextDocument.cs, main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/TextLinkEditMode.cs
The undo stack optimization only works for typing - not for the multi step undos introduced with the vs model.
=> Fixed 'Bug 55108 - Undo commented region deletes extra text'

main/external/fsharpbinding/MonoDevelop.FSharp.Tests/IndentationTrackerTests.fs
This reverts commit fc31eaa827dab840497ad8c1b42252733bdac6bb.
Default tab size is back to 4.
=> Revert "[F#] Fix indentation tests for default tab width"

main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git.csproj
On Windows when building we see an error:
C:\Temp\monodevelop\main\src\addins\VersionControl\MonoDevelop.VersionControl.Git\gtk-gui\generated.cs(17,17): Error CS0436: The type 'BinContainer' in 'C:\Temp\monodevelop\main\src\addins\VersionControl\MonoDevelop.VersionControl.Git\gtk-gui\generated.cs' conflicts with the imported type 'BinContainer' in 'MonoDevelop.SourceEditor, Version=2.6.0.0, Culture=neutral, PublicKeyToken=3ead7498f347467b'. Using the type defined in 'C:\Temp\monodevelop\main\src\addins\VersionControl\MonoDevelop.VersionControl.Git\gtk-gui\generated.cs'. (CS0436) (MonoDevelop.VersionControl.Git)
=> Disabling treat warnings on errors in VersionControl.Git. (#2109)

main/src/core/MonoDevelop.Projects.Formats.MSBuild/app.v15.0.config
VS2017's command prompt sets an environment variable of the same name,
with a comment:
```
@REM Set VisualStudioVersion for compatibility with previous revisions of the
@REM VS Developer Command Prompt.
set "VisualStudioVersion=15.0
```
And the IDE seems to have the property set.
This is required because there might be targets that need to use it
before `Microsoft.Common.props`, which imports
`Microsoft.VisualStudioVersion.v*`, is imported. msbuild/mono has this
this in it's app.config .
This fixes https://bugzilla.xamarin.com/show_bug.cgi?id=54653 by
allowing `Microsoft.Portable.CurrentVersion.props` to be imported.
=> [msbuild] Set `$(VisualStudioVersion)==15.0` in the app.config

main/src/addins/WindowsPlatform/WindowsPlatform/Dialogs/OpenFileDialogHandler.cs
The windows save-as dialog was not able to select the UTF8 codepage, even when the OpenFileDialogHandler.BuildEncodingsCombo took in the UTF8 encoding. UTF8 and UTF16 have the same WindowsCodePage (1200) which happens to match the UTF16 CodePage but not the UTF8 CodePage (65001)
=> https://bugzilla.xamarin.com/show_bug.cgi?id=53033

main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/MsNetTargetRuntime.cs
Change the MSNetTargetRuntime to locate MSBuild 15 from the VS 2017 installed location as opposed to Program Files (x86)\MSBuild.
=> Use correct MSBuild 15.0 location in MSNetTargetRuntime.

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProjectService.cs
Declare local variables to make path calculations easier.
Don't copy the "template" .exe.config locally since we can read it directly from where it was (wherever that may be).
On Windows, copy all official MSBuild .dlls from the MSBuild bin location to the builder directory.
Don't have a foreach loop inside UpdateMSBuildExeConfigFile since there is always only one .config file we need to transform.
=> Refactor GetLocalMSBuildExeLocation

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.Policies/PolicyService.cs
When saving a policy, if a base policy set is not used for diff serialization
make sure the inheritsSet and inheritsScope values are removed from
the project or solution file, if they were previously set.
=> Fix bug #55244 - VS Mac not remembering some code formatting options

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProjectService.cs
Edit the .config file on Windows to contain correct values for MSBuild properties. These are sufficient to be able to build MonoDevelop on Windows using itself.
On Windows we take the original MSBuild.exe.config file as a starting point and modify it to set the properties we need.
=> Set MS build properties

main/build/MacOSX/monostub-utils.h
Bug 53324 - Svn is not working on latest version of Xamarin Studio 6.2
cc @mhutch
=> Add default fallback path for Xcode.app

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextEditorViewContent.cs
get "An Autosave file has been found for this file"'
=> Fixed 'Bug 55308 - Save as, then open original CSS or HTML file, you

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/BackgroundPackageActionRunner.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageManagementProgressMonitorFactory.cs
Prevent NuGet package errors being missed if another NuGet background
action is started whilst one is still being run. This was happening
when creating a new Forms project which installs NuGet packages
but also runs a .NET Core project restore. The .NET Core project
restore was clearing the Package Console so the full information
was not available.
Also make the package console pad id check more strict so the
correct pad is found.
=> [NuGet] Do not clear package console if action being processed

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Features/Completion/ContextHandler/ObjectCreationContextHandler.cs
That () completion confusion was caused by a wrong completion item -
in the object creation context only the object creation items should
be shown which handle the parens. That's the same behavior like in
VS.NET where the object creation handler is exclusive too.
=> Fixed 'Bug 55298 - Autocomplete () doesn't work'

main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/TargetFrameworkMoniker.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectService.cs
Use .NET 4.6.1 as default target framework for new projects, since
4.6.2 is not installed by default on Windows.
Fixes bug #55346 - MonoDevelop on Windows relies on 4.6.2 targeting
pack for standalone C# files
=> Update default target framework

main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.Formats.MSBuild/ProjectBuilder.v4.0.cs
Avoid unhandled exception when trying to build a project that has been
deleted after being loaded in the project builder.
=> Fix potential msbuild failure

main/src/core/MonoDevelop.Core/MonoDevelop.Core.Execution/RemoteProcessConnection.cs, main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.MSBuild.Shared/BuildEngine.Shared.cs
Fix race in project builder.
Don't reuse the workDoneEvent event anymore. In some cases it may
happen that the event is signaled twice (once when the work is
finished, and maybe once if the work is aborted just after it
finished. In those cases the second time the event is signaled it
could actually signal that the next task has been completed, which is
wrong. Also improve handling of thread abort exceptions, those
exceptions should never generate an error.
Should fix bug #52645 - XS cannot recover if the external MSBuild
builder dies
Fix deadlock in RemoteProcessConnection.
When processing a message response, the response should be notified
outside the messageWaiters lock, otherwise it may deadlock if the task
that handles the response is blocked in another lock.
=> Fix builder crash

main/src/core/Mono.TextEditor.Platform/Platform/Text/Impl/TextModel/TextDocumentFactoryService.cs, main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/TextDocument.cs, main/src/core/MonoDevelop.TextEditor.Tests/Mono.TextEditor.Tests/DocumentTests.cs
It's a fairly complex bug to fix. The behavior of VS.NET and XS
clearly differs. VS just uses the system default locale to dertmine
encoding. That's Encoding.Default on mono that's always UTF8 with bom.
So the vs loading routines assume that ascii files are always UTF8+BOM
on mono. Unfortunately we need to be able to consume the locales and
sometimes it clashes with UTF8 - the text file utility contains logic
to prevent these clashes. CP1252 files would be converted to UTF8
otherwise - it's not just a BOM bug - it's more an encoding
detection+incompatibilty bug - mosly caused by a bad design decision
from VS.NET.
Only way to fix that is using the text file utililty logic - it has
work arounded that issue since years.
=> Fixed 'Bug 53380 - [Webtools] Editor inserts BOMs sometimes'

main/src/core/MonoDevelop.Ide/MonoDevelop.Components/XwtBoxTooltip.cs
Delay tooltip hiding using a timer to
avoid flickering due to weird tookit behaviour.
(fixes bug #54985)
=> [54985] Fix XwtBoxTooltip flickering

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild.Conditions/ConditionFunctionExpression.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildEvaluationContext.cs
This commit introduces the inheritance of the file existence cache at
MSBuildEvaluationContext level.
By inheriting the parent exists evaluation cache, we end up doing less
IO on grabbing Condition='Exists(x)'.
The lock on the evaluation cache introduces an extra 300ms locking
contention, but Evaluate(ProjectInfo, MSBuildEvaluationCache,
MSBuildImport, bool) ends having a total lock contention time reduced by
3000ms. (8900ms -> 5612ms)
Time spent in the above method is reduced from 57639ms to 48601ms.
=> [Core] Smarter import evaluation

main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs, main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/TextDocument.cs, main/src/core/MonoDevelop.TextEditor.Tests/Mono.TextEditor.Tests/TextEditorDataTests.cs
Dirty state after undo needs to be checked. Seems to be caused by
event order changes in the vs text editor. Redo dirty checkworks btw.
This fixes a little bug in the dirty state of the enduno event as
well.
=> Fixed 'Bug 55459 - Undo doesn't bring files back to unmodified status'

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProjectService.cs, main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.MSBuild.Shared/Main.cs, main/src/core/MonoDevelop.Projects.Formats.MSBuild/app.v15.0.config
This switches to local copying the facade assemblies instead of using binding redirects,
to work with older mono.
=> [msbuild] Fix v4/v12 assemblies use with older mono

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
Fixed bug #55457 - Issue when trying to create a new project while a
file has changes
https://bugzilla.xamarin.com/show_bug.cgi?id=55457
With a file modified and open in the text editor, selecting New
Solution shows a dialog asking to save the modified file. Clicking the
Save button would then not open the New Project dialog. The problem
was that the Document.Save method returns a task and the code
was checking the Document's IsDirty property before the save
completed which prevented the New Project dialog from being opened.
=> [Ide] New project dialog not displayed when modified file saved

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/TypeSystemService_WorkspaceHandling.cs
That makes the work around with adding/removing event handlers
obsolete. That didn't really work because the event was triggered on
UI thread.
=> Fixed 'Bug 55476 - TypeSystem task loop'

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/syntaxes/CSharp/C#.sublime-syntax, main/src/core/MonoDevelop.TextEditor.Tests/Mono.TextEditor.Tests.DefaultEditActions/TextEditorTestBase.cs, main/src/core/MonoDevelop.TextEditor.Tests/Mono.TextEditor.Tests/SyntaxHighlightingTests.cs
string with "$@" prefix '
Was just a simple typo in the syntax files - hower it's now part of
the unit test suite.
=> Fixed 'Bug 55462 - Syntax highlighting breaks after using literal

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.UnitTesting/DotNetCoreTestPlatformAdapter.cs
Running the unit tests for a .NET Core project would fail if run
from the Test Results pad. The Application Output window would
open and the following error message would be displayed:
No executable found matching command "dotnet-/usr/local/share/dotnet/dotnet"
The command line arguments used were incorrect when the .NET Core
debugger is not used. The fix causes the tests to not be run in the
same way as they are run from the Unit Tests window. They are run
using the same command line as when debugging the tests instead of
with being run by the test runner process. The only difference
for the end user is that an Application Output window is displayed.
Possibly when the tests are run from the Unit Tests window they
should be run in the same way so test output to make it consistent.
=> [DotNetCore] Fixed Test Results pad - Rerun Tests failing

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.UnitTesting/DotNetCoreTestPlatformAdapter.cs
Fixed bug #55543 - .NET Core test runner output shown on single line
in Test Results window
https://bugzilla.xamarin.com/show_bug.cgi?id=55543
The Test Results - Output window had the test runner output
messages on a single line since they were added without a new line
at the end of the message.
=> [DotNetCore] Fix Test Results output messages on single line

main/build/MacOSX/Info.plist.in
Unless we explicitly set these keys, NSOpenPanel and NSSavePanel do not get localized.
ಠ_ಠ cocoa
=> [Loc] Allow native file dialogs to be localized using the locale

main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
Bug 55345 - VSforMac crashes when adding a Cocoa project
=> [Git] Guard against exceptions flowing out of git status.

main/src/addins/VersionControl/MonoDevelop.VersionControl.Subversion.Unix/MonoDevelop.VersionControl.Subversion.Unix.csproj, main/src/addins/VersionControl/MonoDevelop.VersionControl.Subversion.Unix/MonoDevelop.VersionControl.Subversion.Unix/LibApr.cs, main/src/addins/VersionControl/MonoDevelop.VersionControl.Subversion.Unix/MonoDevelop.VersionControl.Subversion.Unix/LibSvnClient.cs, main/src/addins/VersionControl/MonoDevelop.VersionControl.Subversion.Unix/MonoDevelop.VersionControl.Subversion.Unix/LibSvnClient2.cs
Formerly, this code would use library paths to open libsvn and libapr accordingly.
This meant that it would use the search paths for each library that would end up loading.
In the case of Xcode not being located and svn being installed via brew, it would load mismatched dlls for the two
libraries.
dlopen-ing libsvn will ensure the right apr is loaded for the probed svn lib
Bug 47563 - Visual Studio for mac crashes on opening a solution
=> [Svn] Make unix svn resilient to native crashes

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads/ErrorListPad.cs
Majority of fix is in checking if Width actually changed, since it turns out notification is sent multiple times even when size is not changed… While looking at GTK+ code I noticed there is much better way to invalidate recalculation of width for all rows: https://github.com/GNOME/gtk/blob/gtk-2-24/gtk/gtktreeviewcolumn.c#L3749-L3765
=> Bug 55158 - XS hangs if MSBuild returns 2000 errors

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/DockContainer.cs
This can happen because we manually emit the add signal.
=> [Ide] Don't log a message if the parent is already set correctly.

main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DefaultWorkbench.cs
move a file that is modified in the editor'
The real bug was that the open file closed when moving to another
location. This patch ensures that the move file event is handled
properly.
=> Fixed 'Bug 55456 - Incorrect behavior and exception when trying to

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/RoslynCompletionCategory.cs
This fixes an exception in RoslynCompletionCategory.Compare when comparing against custom categories.
=> [csharp] Avoid invalid cast exception on code completion

main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Xwt/XwtPopup.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Xwt/XwtThemedPopup.cs
This PR fixes Xwt based Popup positioning relative to targets with different screen coordinate systems. This includes only native Cocoa popups on top of Gtk/Cocoa targets, other constellations need to be fixed as soon as we make use of them and are marked with `TODO` comments.
(fixes bug #54483)
=> [54483] Fix XwtPopup Target screen bounds calculation

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/DotNetProjectProxy.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/MSBuildProjectExtensions.cs
Fixed bug #55563 - Updating NuGet package in .NET Core project does
not update project.assets.json file
https://bugzilla.xamarin.com/show_bug.cgi?id=55563
With an old version of a NuGet package installed in a .NET Core
project, updating the NuGet package would update the version correctly
in the project file but the project.assets.json file would have the
old version. This resulted in the wrong version displayed in the
Solution window. The problem was that the old package reference
version could be picked up since all package references were taken
from the evaluated items, as well as those defined in the project,
and only the first one is used when updating the project.assets.json
file. So now only imported package references are taken from the
evaluated items which ensures the correct …
=> [NuGet] Fix updating NuGet package not updating project.assets.json

main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/LicenseAcceptanceService.cs
Added workaround for bug #55089 - UI hang if main menu is open when
Licence Acceptance dialog displayed
Showing the XWT dialog using the GTK# backend instead of the native
Mac backend prevents the UI hang where the license dialog does not
respond to its buttons being clicked.
=> [NuGet] Add workaround for license dialog UI hang

main/src/addins/MonoDevelop.DotNetCore/Properties/MonoDevelop.DotNetCore.addin.xml
Added the .NET Standard library project to the .NET Core - Library -
General category in the New Project dialog. This project template
is also still available from the Multiplatform - Library category.
=> [DotNetCore] Add .NETStandard project template to .NET Core category

main/src/addins/MonoDevelop.Packaging/MonoDevelop.Packaging/DotNetProjectExtensions.cs, main/src/addins/MonoDevelop.Packaging/PostBuild.proj, main/src/addins/MonoDevelop.Packaging/Templates/CrossPlatformLibrary.xpt.xml, main/src/addins/MonoDevelop.Packaging/Templates/PackagingProject.xpt.xml, main/src/addins/MonoDevelop.Packaging/packages.config
Fixed bug #55665 - NuGetizer adds NuGet.Build.Packaging version
0.1.157-dev but latest avail is 0.1.248
https://bugzilla.xamarin.com/show_bug.cgi?id=55665
Updated to the latest stable version of the NuGet.Build.Packaging
NuGet package available from nuget.org.
Not sure if this needs to be tested by QA first, or if it needs to be included into 15.2. The original bug is targeted for 15.2. A workaround is to just update the NuGet package in the projects.
=> [NuGetizer] Update to latest stable NuGet.Build.Packaging

main/external/fsharpbinding/MonoDevelop.FSharpi.Service/MonoDevelop.FSharpInteractive.Service.fsproj
Add workaround for MSBuild not finding the assembly:
FSharp.Compiler.Interactive.Settings.dll
=> [F#] Fix build error with Mono 5.0.0.88

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AtkCocoaHelper/AtkCocoaHelper.cs
The action code was creating a circular ref between the accessible and the object via the signals. Break all the refs.
=> [Atk] Fix leak caused by circular referencing in Atk code.

main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
Run project reevaluation inside a writeProjectLock lock, otherwise
it may happen that the project is rewritten in the middle of
a reevaluation, and this will cause crashes.
Fixes bug #55658 - NRE when trying to restore packages in xUnit project
=> Fix threading issue when reevaluating project

main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/DefaultMSBuildEngine.cs, main/tests/UnitTests/MonoDevelop.Projects/MSBuildTests.cs, main/tests/test-projects/console-project-with-wildcards/ConsoleProject-imported-none-wildcard.csproj, main/tests/test-projects/console-project-with-wildcards/ConsoleProject-imported-none-wildcard.csproj.saved1, main/tests/test-projects/console-project-with-wildcards/Imports/AllNoneAndCSharpFiles.props
Fixed bug #55560 - Setting Build Action to None for C# file is ignored
https://bugzilla.xamarin.com/show_bug.cgi?id=55560
In a .NET Core project changing the build action for a C# file to
None made no changes to the project file. On re-opening the project
the file would have the build action of Compile.
The .NET Core sdk defines globs similar to the following:
<None Include="**/*" />
<None Remove="**/*.cs" />
<Compile Include="**/*.cs" />
On changing a C# file's build action to None the project model was
finding the file is included in the None glob include and not
making any changes to the project file. However C# files are removed
from the None glob include by the None remove glob and this was not
being taken into account. Now the remove glob is associated with its
corresponding glob …
=> [Core] Fix setting C# build action to none ignored for .NET Core

main/src/addins/CSharpBinding/MonoDevelop.CSharp.Features/ParameterHinting/ParameterHintingEngine.cs
Reduce allocations done while typing parameters for a method. Searching for a method to see overloads would've triggered a lot of calls throughout the whole compilation to see whether we could find extension methods.
Trim searching so we don't try to reduce all the extension methods we find, only reducing the ones which match the name of the caller.
Also, do name trimming at roslyn level, so we don't allocate unnecessarily.
Reduce allocation of typing MapEvent(PasswordEntryEvent.Activated, typeof(PasswordEntry), OnActivated); in Xwt's PasswordEntry static constructor.
=> [C#] Improve editor performance while typing.

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/SdiWorkspaceWindow.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs
Fixed bug in the logic that saves a document when it is closed.
args.Cancel was always set to true, which was wrong since
the Close method of the document would always return false,
even when properly saving the document.
This change was done to fix an issue with asyc save
of documents, which I think was properly fixed by
https://github.com/mono/monodevelop/commit/9c9f2aa021b3f48cb865f4307ae9b59372611b25
Fixes bug #55713 - Selecting recent solution when unsaved files
open does not open solution
=> Fix document save logic

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/CompletionTextEditorExtension.cs
This ensures that completion on backspace & delete only is triggered
when an identifier part was removed and not on word boundaries like in
the bug report.
=> Fixed 'Bug 55701 - Autocompletion too aggressive when using backspace'

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/PackageReferencePanel.cs
Fixed bug #55747 - Removing Reference in the Edit Reference Dialog
does not work
https://bugzilla.xamarin.com/show_bug.cgi?id=55747
Removing project or assembly references from the All tab in the
Edit References dialog was not updating the project file. The
references would remain in the project. The problem was that no
matches were found for the reference information being supplied by
the All tab to the reference dialog.
The project name is now used when removing a project reference.
Previously the project's filename was used. The assembly filename
without the path and without the file extension is now used when
removing an assembly reference. Previously the assembly's full
filename was used.
=> [Ide] Fix removing project/assembly references in References dialog

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/DotNetCoreNuGetProject.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/DefaultMSBuildEngine.cs, main/tests/UnitTests/MonoDevelop.Projects/MSBuildTests.cs, main/tests/test-projects/dotnetcore-console/Sdks/Test.Sdk/Sdk/Sdk.props
Fixed bug #55593 - The name 'InitializeComponent' does not exist in the
current context with .NETStandard/new csproj format portable library
https://bugzilla.xamarin.com/show_bug.cgi?id=55593
.NET Core projects add MSBuild imports to the generated nuget files:
ProjectName.csproj.nuget.g.targets and ProjectName.csproj.nuget.g.props.
These files are now implicitly added to ensure any imports from these
files are evaluated. This allows generated C# files from the
Xamarin.Forms NuGet package to be made available to the type system.
=> [DotNetCore] Import generated nuget targets

main/src/core/MonoDevelop.Core/MonoDevelop.Core.Execution/BinaryMessage.cs, main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.Formats.MSBuild/ProjectBuilder.cs, main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.Formats.MSBuild/ProjectBuilder.v4.0.cs, main/tests/UnitTests/MonoDevelop.Core/RemoteProcessConnectionTests.cs, main/tests/UnitTests/MonoDevelop.Projects/MSBuildTests.cs
Fixed bug #55751 - [iOS] Uploading iOS Forms PCL app from Xamarin
Studio to Test Cloud fails build step with "Unknown MSBuild Failure"
https://bugzilla.xamarin.com/show_bug.cgi?id=55751
Two fixes have been made. Both on their own fix the above bug. One fix is in the BinaryMessage so it handles a null dictionary value. Another fix is in the project builders for xbuild and MSBuild so they return an empty string for unknown properties that are being evaluated instead of null, which allows the BinaryMessage to send the message back to the IDE.
=> [Core] Handle unknown MSBuild property being evaluated during build

main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Actions/SelectionActions.cs
select text past the viewport'
=> Fixed 'Bug 55893 - Holding down Shift and the down key continues to

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs, main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/DotNetCoreNuGetProject.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/DefaultMSBuildEngine.cs, main/tests/UnitTests/MonoDevelop.Projects/MSBuildTests.cs, main/tests/test-projects/dotnetcore-console/Sdks/Test.Sdk/Sdk/Sdk.props
Cherry picked from d15-2 branch.
Fixed bug #55593 - The name 'InitializeComponent' does not exist in the
current context with .NETStandard/new csproj format portable library
https://bugzilla.xamarin.com/show_bug.cgi?id=55593
.NET Core projects add MSBuild imports to the generated nuget files:
ProjectName.csproj.nuget.g.targets and ProjectName.csproj.nuget.g.props.
These files are now implicitly added to ensure any imports from these
files are evaluated. This allows generated C# files from the
Xamarin.Forms NuGet package to be made available to the type system.
=> [master][DotNetCore] Import generated nuget targets

main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.csproj, main/src/addins/MonoDevelop.DotNetCore/Properties/MonoDevelop.DotNetCore.addin.xml, main/src/addins/MonoDevelop.DotNetCore/packages.config
Update the project templates to use the 1.0.0-beta1-20170427-174
templating NuGet packages.
The ASP.NET Core web project templates use unpublished NuGet packages so they currently will not restore.
=> [RTW][DotNetCore] Update project templates

main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/PackageReferencePanel.cs
Cherry-picked from d15-2 branch.
Fixed bug #55747 - Removing Reference in the Edit Reference Dialog
does not work
https://bugzilla.xamarin.com/show_bug.cgi?id=55747
Removing project or assembly references from the All tab in the
Edit References dialog was not updating the project file. The
references would remain in the project. The problem was that no
matches were found for the reference information being supplied by
the All tab to the reference dialog.
The project name is now used when removing a project reference.
Previously the project's filename was used. The assembly filename
without the path and without the file extension is now used when
removing an assembly reference. Previously the assembly's full
filename was used.
=> [Master][Ide] Fix removing project/assembly references in References dialog

main/src/addins/MonoDevelop.Debugger.VSCodeDebugProtocol/MonoDevelop.Debugger.VsCodeDebugProtocol/VsCodeObjectSource.cs
There are legit cases of type being null, like “Static members” and “Non-public members” groups, but also when evaluating variables(hover, repl…) .NET Core debugger doesn’t set Type which we in past considered as error, now we just ignore it and set it to empty string…
=> Bug 55869 - Can not inspect variables in .Net core applications

main/src/addins/Xml/Formatting/XmlFormatter.cs
If an xml file contained a DTD then the xml formatter would try
to resolve and download the DTD.
```
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd" >
<svg xmlns="http://www.w3.org/2000/svg">
...
```
This could cause the UI to hang.
There is no need to resolve any DTDs when formatting the xml so
the resolver is disabled. This fixes the long time spent waiting for
files to be formatted when a new ASP.NET Core web project is created.
=> [Xml] Prevent DTD being resolved when formatting xml

main/src/addins/Xml/Formatting/XmlFormatter.cs
Cherry picked from d15-2.
If an xml file contained a DTD then the xml formatter would try
to resolve and download the DTD.
```
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd" >
<svg xmlns="http://www.w3.org/2000/svg">
...
```
This could cause the UI to hang.
There is no need to resolve any DTDs when formatting the xml so
the resolver is disabled. This fixes the long time spent waiting for
files to be formatted when a new ASP.NET Core web project is created.
=> [master][Xml] Prevent DTD being resolved when formatting xml

main/src/core/MonoDevelop.Core/MonoDevelop.Core.addin.xml, main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj, main/src/core/MonoDevelop.Core/MonoDevelop.Projects.Extensions/AppliesToCondition.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/AppliesToAttribute.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs, main/src/core/MonoDevelop.Core/MonoDevelop.Projects/WorkspaceObject.cs, main/src/core/MonoDevelop.Ide/ExtensionModel/ItemOptionPanels.addin.xml, main/src/core/MonoDevelop.Ide/ExtensionModel/Templates.addin.xml, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/ItemOptionsDialog.cs, main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/FileTemplate.cs
This condition can be used to specify that a project extension, file template, or option panel apply to projects that match a particular capability expression.
=> [Project] Add VS-like AppliesTo extension condition

main/src/core/MonoDevelop.Core/MonoDevelop.Core.Execution/BinaryMessage.cs, main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.Formats.MSBuild/ProjectBuilder.cs, main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.Formats.MSBuild/ProjectBuilder.v4.0.cs, main/tests/UnitTests/MonoDevelop.Core/RemoteProcessConnectionTests.cs, main/tests/UnitTests/MonoDevelop.Projects/MSBuildTests.cs
Reworked the original fix for Bug #55751 - [iOS] Uploading iOS Forms
PCL app from Xamarin Studio to Test Cloud fails build step with
"Unknown MSBuild Failure"
Null dictionary string values are now handled in a simple way by
replacing the null with a place holder in the BinaryMessage.
The changes made to the ProjectBuilders have been reverted since
nulls are supported and no longer need to be replaced with empty
strings.
=> [Core] Support null dictionary string values in BinaryMessage

main/src/core/MonoDevelop.Ide/MonoDevelop.Components.DockNotebook/DockNotebookContainer.cs
Fixes bug #55399 - Editor columns become stacked hiding
one one column behind the other when VS is closed and reopen.
=> Fix bug when restoring document splits

main/src/addins/MonoDevelop.DotNetCore/Properties/MonoDevelop.DotNetCore.addin.xml
With Mono's MSBuild having the .NET Core SDK files, but the .NET
Core runtime or SDK not being installed separately, the .NET Core
category was displayed and it contained the .NET Standard library
project template. Whilst this project can be compiled it is
confusing that it is displayed in the .NET Core category when the
.NET Core sdk or runtime has not been installed.
The .NET Standard Library project template is now no longer displayed
in the .NET Core category if .NET Core is not installed separately.
This then prevents the .NET Core category from being displayed.
The .NET Standard Library project is still available in the
Multiplatform - Library category.
=> [d15-3-preview][DotNetCore] Do not show .NET Core category if runtime not installed

main/src/addins/MonoDevelop.DotNetCore/Properties/MonoDevelop.DotNetCore.addin.xml
With Mono's MSBuild having the .NET Core SDK files, but the .NET
Core runtime or SDK not being installed separately, the .NET Core
category was displayed and it contained the .NET Standard library
project template. Whilst this project can be compiled it is
confusing that it is displayed in the .NET Core category when the
.NET Core sdk or runtime has not been installed.
The .NET Standard Library project template is now no longer displayed
in the .NET Core category if .NET Core is not installed separately.
This then prevents the .NET Core category from being displayed.
The .NET Standard Library project is still available in the
Multiplatform - Library category.
=> [master][DotNetCore] Do not show .NET Core category if runtime not installed
