mono/monodevelop

- extras/BooBinding/po/ja.po
- extras/JavaBinding/po/ja.po
- extras/MonoDevelop.Database/po/ja.po
- main/po/ja.po
> [Po] Update Japanese Translation

- main/configure.in
mono from git master does not provide gmcs anymore
> do not require gmcs but mcs in the PATH

- main/src/addins/MonoDevelop.GtkCore/MonoDevelop.GtkCore/GtkDesignInfo.cs
- main/src/addins/MonoDevelop.GtkCore/MonoDevelop.GtkCore/ReferenceManager.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/AutoSave.cs
- main/src/core/Mono.Texteditor/Mono.TextEditor.Highlighting/SemanticRule.cs
- main/src/core/Mono.Texteditor/Mono.TextEditor.Highlighting/SyntaxMode.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core/FilePath.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectService.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/WorkspaceItemCollection.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandMenuItem.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/ShowAllFilesBuilderExtension.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/RootWorkspace.cs
> Performance Improvements

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/FindInFilesDialog.cs
MonoDevelop can open multiple solutions at once (or workspace documents
that can contain more than one solution), so using "Whole solution" as
the wording for this search option always is not ideal.
The enum element is renamed too, for clarity.
> [FindInFiles] Only use "Whole solution" when there is only one sol open

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/ExtensibleTreeView.cs
Model should not be null, but looks like it is in some cases.
> [Ide] Add some null checks

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
> [Ide] fix moving/copying empty directories between projects

- main/src/addins/MacPlatform/MacPlatform.csproj
- main/src/addins/MacPlatform/MainToolbar/CALayerExtensions.cs
- main/src/addins/MacPlatform/MainToolbar/MainToolbar.cs
- main/src/addins/MacPlatform/MainToolbar/SearchBar.cs
- main/src/addins/MacPlatform/MainToolbar/StatusBar.cs
- main/src/addins/MonoDevelop.GtkCore/MonoDevelop.GtkCore.GuiBuilder/GtkProjectServiceExtension.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestSession.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbar.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbarController.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/GtkUtil.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkMacInterop.cs
Will contain a collection of fixes for 5.9.
> [Don't merge yet] Monodevelop 5.9 branch toolbar fixes

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/ContextMenuExtensionsMac.cs
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=26170 and https://bugzilla.xamarin.com/show_bug.cgi?id=27557
> [Core] Fix position calculations of native Mac context menus

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/DispatchService.cs
In ProcessAnimations make a copy of the activeAnimations list when iterating
over it since new animations may be added while that loop runs. Simplified
a bit the code.
> [Ide] Fix crash in DispatchService animation code

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeActionEditorExtension.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/RefactoringService.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/RefactoryCommands.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/ExtensibleTreeView.cs
SR1 and SR2 fixes that were not cherry-picked into the watchkit branch
> WatchKit SR fixes

- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Instrumentation/Counter.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Instrumentation/TimerCounter.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core/Runtime.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects.Formats.MSBuild/MSBuildProjectHandler.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectService.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionItem.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandArrayInfo.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/ViewCommands.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Services.cs
Added new overloads to Counter for providing metadata.
Added metadata to some counters: AddinLoaded.
Added counters for MSBuild operations.
Added method for getting the metadata that has to be collected when a
project related event occurs.
Renamed several counters.
Count the time that it takes to execute a command.
> Instrumentation improvements

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorWidget.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=27599
> [Editor] Fix some visual quirks in the source editor overlay.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/ProjectNodeBuilder.cs
Fixes bug #20932 - Tapping on a file or folder in the solution pad of a SAP
causes the project to collapse.
> [Ide] Fix solution pad collapsing bug

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CustomTools/CustomToolService.cs
Michael already fixed this in master. I just cherry picked and reviewed commits.
> Bug 27973 - On adding Xaml file in Forms Shared project, XS gives error message.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
This PRs goal is to fix #799, in case of no focused window in the application.
That means, with #799, if we opened a popup, then closed it and tried a command, it wouldn't get processed if it weren't an editor command.
Now we route the implementation to the window and test if it can perform the event first.
> Fix to unfocused workbench fallthrough.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/AssemblyReferencePanel.cs
Set multiselect  option to allow addition of multiple package files while modifying references.
> [ide] Allow multi select in AddPackageRef file dialog

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Tasks/TaskStore.cs
Prevents e.g. opening the Windows Photo Viewer when a build
task has a problem with a PNG file.
> [Ide] Only jump to errors in text files

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/ProjectTemplate.cs
> [Ide] Do not use the localized template name with the template instantiation counter.

- main/src/addins/TextTemplating/TextTransform/TextTransform.cs
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=28768
Recreated #848 to pull request on top of master
> Add catch and output for all exceptions

- main/src/addins/TextTemplating/Mono.TextTemplating/Mono.TextTemplating/TemplateGenerator.cs
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=28776
Recreated #850 to pull request on top of master
> Fix Host.ResolvePath

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/FileDescriptionTemplate.cs
Provides creation of filename with only valid characters.
> [Ide] check for invalid characters for filename

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/ProjectFileNodeBuilder.cs
'Rename' operation is not working properly and it shows 'invalid characters error' all the time , this patch fixes this.
> [Ide] Configure 'Rename' operation

- README.md
> Update Gnome HIG link.

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValuePad.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValueTreeView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/TreePathReference.cs
Also https://github.com/mono/debugger-libs/pull/53 needs to be reviewed
> Bug 23265 and other fixes found while working on it

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/LogView.cs
Fixes bug #23721
Is it too late to propose this for 5.9?
> [Ide] Use native menu for test output textview's context menu.

- main/src/core/Mono.Texteditor/Mono.TextEditor/Gui/GtkWorkarounds.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.UI.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=29061
> [Ide] Win32 scale factor fixes for GTK new project dialog.

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/Commands.cs
> [Git] Add SolutionStatus along with Status to MonoDevelop.VersionControl.Commands

- main/src/addins/TextTemplating/Mono.TextTemplating/Mono.TextTemplating/TemplateGenerator.cs
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=28773
Recreates #849 to pull request on top of master
> Append dll for assembly if needed

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AppQuery.cs
Correctly add the toolbar views to the AppResults hierarchy
> [Test Framework] Correctly add the toolbar views to the AppResult

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/ExtensibleTextEditor.cs
- main/src/core/Mono.Texteditor/Mono.TextEditor/Actions/DeleteActions.cs
- main/src/core/MonoDevelop.Ide/ExtensionModel/Commands.addin.xml
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/TextEditorCommands.cs
- main/src/core/MonoDevelop.TextEditor.Tests/Mono.TextEditor.Tests.DefaultEditActions/DeleteActionTests.cs
Add an action to delete from the caret to the start of the line
> [Text Editor] Add Delete to start of line action

- main/tests/Makefile.am
Replace file with covfilter-file
> [Coverage] Update the coverage options for the new option names in mono master

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/EditBranchDialog.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitConfigurationDialog.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitSelectRevisionDialog.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/StatusView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/GtkNotebookResult.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/GtkTreeModelResult.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/GtkWidgetResult.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AppQuery.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
- main/tests/UserInterfaceTests/Ide.cs
- main/tests/UserInterfaceTests/UserInterfaceTests.csproj
- main/tests/UserInterfaceTests/VersionControlTests/GitRepositoryConfigurationTests.cs
- main/tests/UserInterfaceTests/VersionControlTests/GitTests.cs
- main/tests/UserInterfaceTests/VersionControlTests/VCSBase.cs
Tests Added:
* Commit successful
* Stash should notify if there is no changes
* Stash should not work if there is no HEAD commit
* Stash successful
* Unstash successful
* Create new Branch
* Switch Branch
* Edit Branch
* Select Remote
* Add Remote
* Edit Remote (disabled for now)
* Fetch Remote Branches
* Track Remote Branch in Local
> Added Git Tests

- main/src/addins/NUnit/Gui/TestPad.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandArrayInfo.cs
> [Test] Don't enable Debug Test while a test is running.

- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Instrumentation/Counter.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Instrumentation/TimerCounter.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestClientSession.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestSession.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Services.cs
Can generate output from timers like so
[TimerCounter: Name=IDE Initialization Id=Ide.Initialization Category=MonoDevelop.Core.Instrumentation.CounterCategory MinSeconds=0, TotalTime=00:00:02.4317040, AverageTime=00:00:02.4317040, MinTime=00:00:02.4317040, MaxTime=00:00:02.4317040, CountWithDuration=1]
[Counter: Name=Open documents, Enabled=True, Id=Open documents, Category=MonoDevelop.Core.Instrumentation.CounterCategory, Count=1, TotalCount=1, LastValue=MonoDevelop.Core.Instrumentation.CounterValue]
[Counter: Name=Documents in memory, Enabled=True, Id=Documents in memory, Category=MonoDevelop.Core.Instrumentation.CounterCategory, Count=1, TotalCount=1, LastValue=MonoDevelop.Core.Instrumentation.CounterValue]
[Counter: Name=Pads loaded, Enabled=True, Id=Pads loaded, …
> [Test Framework] Add method to get stats on counters and timers

- main/src/addins/NUnit/Gui/NUnitOptionsPanel.cs
- main/src/addins/NUnit/Services/NUnitAssemblyTestSuite.cs
- main/src/addins/NUnit/Services/UnitTest.cs
- main/src/addins/NUnit/Services/UnitTestResult.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/Commands.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitService.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/ProjectTemplateHandler.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionInfoCache.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core/Gettext.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/RootWorkspace.cs
> [WIP] Coverity fixes

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs
This is a followup to https://github.com/mono/monodevelop/pull/904
> [Debugger] Fix more gtk assertion spew. 

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebuggingService.cs
Bug 29006 - NUnit view resets to Solution view after debugging test
cc @DavidKarlas
> [Debugger] Fixed layout switching of the debugger to previous one

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/GtkWidgetResult.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/NSObjectResult.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AppQuery.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AppResult.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestClientSession.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestSession.cs
Generate an XML representation of the widget hierarchy using the members of an AppResult array as the root nodes
> [Test Framework] Export results as XML

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/MDMenu.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/ExtensibleTreeView.cs
Use NSMenu for the row button in the solution explorer pad instead of a Gtk.Menu
> [IDE] Use NSMenu for Solution Explorer Pad

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitConfigurationDialog.cs
- main/tests/UserInterfaceTests/Controllers/NuGetController.cs
- main/tests/UserInterfaceTests/VersionControlTests/Git/GitBase.cs
- main/tests/UserInterfaceTests/VersionControlTests/Git/GitRepositoryConfigurationTests.cs
* Updated NuGet Add Package button timeout to 30s
* Moved around a few methods into respective regions
* Added SemanticAttribute to Git Tag TreeView
> [UITest] Added Git Tag Tests

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Operations/SelectedOperation.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/GtkTreeModelResult.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/GtkWidgetResult.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/NSObjectResult.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/ObjectResult.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AppQuery.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AppResult.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
- main/tests/UserInterfaceTests/Controllers/NewFileController.cs
- main/tests/UserInterfaceTests/Controllers/NewProjectController.cs
- main/tests/UserInterfaceTests/CreateBuildTemplatesTestBase.cs
- main/tests/UserInterfaceTests/TemplateTests/ASPNETTemplateTests.cs
- main/tests/UserInterfaceTests/TemplateTests/DotNetTemplatesTest.cs
- main/tests/UserInterfaceTests/TemplateTests/MiscTemplatesTest.cs
There are a few scenarios where we need to check if a element has focus or is selected, e.g. SolutionPad or template in New Project Dialog.
> Implemented Selected () operation to check if an element/TreeIter is selected

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/RecentOpen.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=4064
> [Ide] Bump max recent project count to 25. Fixes #4064.

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/Makefile.am
Otherwise it doesn't get shipped in "make dist" tarballs
> Add build_libgit2.sh to EXTRA_DIST

- main/tests/UserInterfaceTests/Ide.cs
> [UITest] Fixed WaitForSolutionLoaded wait method

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/Makefile.am
- main/xbuild.include
Fixes missing build_libgit2.sh and all .targets files
> fix weird exclusions in "make dist"

- main/src/addins/MacPlatform/MainToolbar/SelectorView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbar.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbarController.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbarModels.cs
Fixes 94b61b55fd77733c59ea1135dcde11441092fb75 's ಠ_ಠ impact.
> Mutable runtimes

- main/src/core/MonoDevelop.Ide/ExtensionModel/Commands.addin.xml
- main/src/core/MonoDevelop.Ide/ExtensionModel/MainMenu.addin.xml
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/GtkWidgetResult.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestSession.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/ToolsCommands.cs
Implement recording of key events and commands executed. Save them to an XML file and replay them at a later date
> Session recording

- main/src/addins/MacPlatform/MainToolbar/MainToolbar.cs
- main/src/addins/MacPlatform/MainToolbar/SelectorView.cs
Bug 33769 - InvalidCast from the main bar
Bug 31116 - Mac Toolbar: Responsive treatment
Bug 30550 - Xamarin Studio crashes when resizing
cc @vancura @slluis @iainx
> [Mac] Dynamically resize the config/platform selector

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestSession.cs
cc: @manish @Therzok 
Will this be okay on Linux?
> [AutoTest] Implement TakeScreenshot for Windows

- main/tests/UserInterfaceTests/Util.cs
It is common we need to bold text, this will help. @Therzok
> [UITest] Add util for bolded text

- main/tests/UserInterfaceTests/TestService.cs
MONODEVELOP_PROFILE is what is expected.
main/src/core/MonoDevelop.Core/MonoDevelop.Core/UserProfile.cs#L32
> [UITest] Update custom user profile env var

- main/tests/UserInterfaceTests/Ide.cs
- main/tests/UserInterfaceTests/Workbench.cs
Main reason for implementing this was to see wrong StatusMessage in StatusBar...
@iainx @manish @kdubau 
Can someone review this and merge? Tnx
> [UITest] Improved WaitUntil to be able to add timeout message

- main/src/addins/MacPlatform/MainToolbar/StatusBar.cs
Bug 33966 - XS: Toolbar progress bar is misaligned on El Capitan
> [Mac] Moved mac progress bar 2px up on El Capitan

- main/src/core/Mono.Texteditor/Mono.TextEditor/Gui/GtkWorkarounds.cs
https://bugzilla.xamarin.com/show_bug.cgi?id=34759
> Fix quickfix context menu on non-Mac platforms

- main/tests/UserInterfaceTests/CreateBuildTemplatesTestBase.cs
- main/tests/UserInterfaceTests/UITestBase.cs
- main/tests/UserInterfaceTests/VersionControlTests/Git/GitBase.cs
- main/tests/UserInterfaceTests/VersionControlTests/VCSBase.cs
Sample reproduced steps for `EditGitRemoteNameAndPushUrlTest`
```
INFO[2015-10-22 14:22:23Z]: @Repro-Step-01: Click on Version Control > Checkout from Menu Bar
INFO[2015-10-22 14:22:23Z]: @Repro-Step-02: Select Type to 'Git'
INFO[2015-10-22 14:22:24Z]: @Repro-Step-03: Enter URL as 'git@github.com:mono/gtk-sharp.git'
INFO[2015-10-22 14:22:24Z]: @Repro-Step-04: Click OK
INFO[2015-10-22 14:22:25Z]: @Repro-Step-05: Wait for Clone to Finish
INFO[2015-10-22 14:22:50Z]: @Repro-Step-06: Click Version Control > Manage Branches and Remotes
INFO[2015-10-22 14:22:50Z]: @Repro-Step-07: Select the 'Remote Sources' tab
INFO[2015-10-22 14:22:51Z]: @Repro-Step-08: Click on Add
INFO[2015-10-22 14:22:52Z]: @Repro-Step-09: Enter Remote name as 'second'
INFO[2015-10-22 14:22:52Z]: @Repro-Step-10: Enter Remote …
```
> Add reproduction steps to Git

- main/tests/UserInterfaceTests/TestService.cs
- main/tests/UserInterfaceTests/UITestBase.cs
> [UITest] Add support for testing installed XS

- main/Makefile.am
- main/build/MacOSX/Makefile.am
- main/build/MacOSX/monostub-test.m
- main/build/MacOSX/monostub-utils.h
Fixes from the 64bit branch that make sense to master
> fixes from 64bit

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads/ErrorListPad.cs
This would be quite useful for UI Tests where build failed and we want to find out the failure.
> [Ide] Added names to ErrorListPad buttons

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextEditor.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextEditorViewContent.cs
@mkrueger can you review this? Trivial changes, just in case...
> [Roslyn] Set Project on ParseOptions & don't inject projections if disabled

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/SearchPopupWindow.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/SearchResult.cs
+Fixed exception thrown by Commands category in case of command without action
> [Ide] Fixed loading categories in global search if one category failed to load

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Solution.cs
The correct fix instead of #1152.
> [roslyn branch] Move NotifyItemReady to OnExtensionChainInitialized

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/Commands.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/PublishCommand.cs
Reverts stupid changes from
https://github.com/mono/monodevelop/commit/a72d7948fa71fe4941987163faa48a9ae5cc35b7
Bug 34310 - [Subversion] Version Control -> Update does not pass correct parameters
> [VCS] Fix regression with top menu commands using single file

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/MenuButton.cs
Use the platform's menu with the menu button rather than hardcoding the Gtk one
> Menubutton fixes

- main/src/addins/CSharpBinding/MonoDevelop.CSharp/ProjectSearchCategory.cs
When a solution was opened and then closed the unified search would
still return results from the last opened solution since the
ProjectSearchCategory keeps the symbol information after the solution
is closed. This keeps alive the solution and Roslyn workspace but only
temporarily until the next solution is opened. However it does mean
that you can still search for types in the previously closed solution
before another solution is opened.
Now when the last workspace item is closed the symbol information is
cleared from the project search category. This prevents types being
returned in the search results when no solution is opened. It also
allows the solution and workspace to be garbage collected when the
solution is closed without having to wait for another solution to be
opened.
> [CSharpBinding] Do not show search results from closed solution.

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/DotNetProject.cs
- main/tests/UnitTests/MonoDevelop.Projects/ProjectTests.cs
- main/tests/test-projects/conditional-project-reference/commonLib/MyClass.cs
- main/tests/test-projects/conditional-project-reference/commonLib/commonLib.csproj
- main/tests/test-projects/conditional-project-reference/conditional-project-reference.sln
- main/tests/test-projects/conditional-project-reference/conditional-project-reference/Program.cs
- main/tests/test-projects/conditional-project-reference/conditional-project-reference/conditional-project-reference.csproj
- main/tests/test-projects/conditional-project-reference/windowsLib/MyClass.cs
- main/tests/test-projects/conditional-project-reference/windowsLib/windowsLib.csproj
I'm pretty sure this is OK fix, but would prefer quick review by you @slluis 
Thank you
> Bug 34569 - [Regression] Project references don't handle Condition attributes

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Features/ExtractMethod/CSharp/CSharpSelectionValidator.cs
@mkrueger can you review this, since I'm not sure about this code, I just copied logic from other failed attempts to create SelectionInfo(see ifs below my change)
Problem is that later in execution code assumes Status is not null... thats where NRE occurs...
> [CSharpBinding] Fixing NRE exception found while debugging other stuff

- main/src/core/MonoDevelop.Ide/AssemblyInfo.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/DesktopService.cs
- main/src/tools/mdtool/mdtool.csproj
- main/src/tools/mdtool/src/mdtool.cs
> Revert "[mdtool] Fix tools that depend on PlatformService"

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects.SharedAssetsProjects/SharedAssetsProject.cs
@slluis can you please review this and merge?
> [Core] SharedProject handle referencing projects that are inside solution folder

- README.md
- main/src/core/MonoDevelop.Core/packages.config
> Fix: Remove package duplication line from package.config

- extras/MonoDevelop.Database/MonoDevelop.Database.Sql.Sqlite/MonoDevelop.Database.Sql.Sqlite.csproj
Remove invalid symbols from MonoDevelop.Database.Sql.Sqlite.csproj
> Fix: Invalid symbols in csproj file.

- main/configure.in
- main/src/addins/AspNet/Makefile.am
- main/tests/Makefile.am
- main/tests/MonoDevelop.CSharpBinding.Tests/Makefile.am
- main/xbuild.include
These changes are needed to successfully build the tarball and .deb/.rpm packages on Jenkins.
> Fix the Tarball and package build

- main/src/addins/MacPlatform/MainToolbar/AwesomeBar.cs
> [MacPlatform] Zoom the window when double clicking on the toolbar

- main/src/addins/MacPlatform/MainToolbar/StatusBar.cs
Reposition all the icons when the error or warning counts change
> [MacPlatform] Correctly layout the statusbar icons

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestClientSession.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AutoTestSession.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/DataTransferObjects.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
> [AutoTest] Added a method for getting TaskService errors

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/SearchResultPad.cs
> [IDE] Reset the search results when changing solution

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/BusyEvaluatorDialog.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebuggingService.cs
cc @DavidKarlas @jstedfast 
This is untested, as I don't know how to trigger the busy dialog.
> [Debugger] Fix some leaks caused by the permanent busy dialog.

- main/src/addins/MacPlatform/MainToolbar/AwesomeBar.cs
- main/src/addins/MacPlatform/MainToolbar/StatusBar.cs
Adjust the offsets to the toolbar isn't as blurry
> [MacToolbar] Fix the offsets so the statusbar is not so blurry

- main/src/addins/MacPlatform/MainToolbar/AwesomeBar.cs
> [MacToolbar] Respect the OSX toolbar double click setting

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/MultiConfigItemOptionsPanel.cs
Also added SemanticModelAttribute for automated testing support
> Add Name to MultiConfigItemOptionsPanel ComboBox and HBox

- configure
Adds --enable-mac32 command line.
> [64bit] Make 64bit the default

- main/src/core/Mono.Texteditor/Mono.TextEditor.csproj
- main/src/core/Mono.Texteditor/Styles/GruvboxStyle.json
> Add gruvbox theme

- main/src/core/Mono.Texteditor/SyntaxModes/FSharpSyntaxMode.xml
Tests [here](https://github.com/fsharp/xamarin-monodevelop-fsharp-addin/commit/fe3c217d549d9623fa51bb53dc5ca36d22b3fc69)
> [F#] Improving syntax mode

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Updater/UpdateService.cs
The daily check for updates was ignoring if the automatic updater checkbox was checked or not
> [IDE] Only run the updater automatically if it isn't turned off

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Updater/UpdateService.cs
The daily check for updates was ignoring if the automatic updater checkbox was checked or not
> [C7] [IDE] Only run the updater automatically if it isn't turned off

- main/src/addins/MonoDevelop.UnitTesting/Gui/TestNodeBuilder.cs
Escapes test names while still removing the F# generic argument present for F# test cases.
These test cases now render correctly
```
[TestCase (true, TestName = "Sample.True")] 
[TestCase (true, TestName = "Rigby+True")] 
[TestCase (false, TestName = "Dean_Road<>False")]
[TestCase (false, TestName = "IsDollah$Accepted")]
[TestCase (false, TestName = "IsPipe|Accepted")]
[TestCase (false, TestName = "IsAmpersand&Accepted")]
```
> [NUnit] Escape test names. Fixes #39210

- main/src/addins/MacPlatform/MainToolbar/MainToolbar.cs
- main/src/addins/MacPlatform/MainToolbar/SearchBar.cs
> [MacToolbar] Have the search shortcut in the search bar

- main/src/addins/MonoDevelop.UnitTesting/Gui/TestNodeBuilder.cs
Undo my earlier commit which turned out to be incorrect.
> [NUnit] - test names were being escaped twice

- main/src/addins/MacPlatform/MainToolbar/MainToolbar.cs
- main/src/addins/MacPlatform/MainToolbar/SearchBar.cs
> [MacToolbar] Have the search shortcut in the search bar - [c7]

- extras/MonoDevelop.Database/po/ko.po
All done.
and I signed up CLA.
> [Ide] Korean translation korean for extras/database

- main/src/addins/MacPlatform/MainToolbar/SelectorView.cs
Show the selector menu when the mouse is pressed so you can select a new configuration/runtime with one click
Fixes BXC #10026
> [MacToolbar] Show the selector menu on button press

- main/src/addins/MacPlatform/MainToolbar/SelectorView.cs
Show the selector menu when the mouse is pressed so you can select a new configuration/runtime with one click
Fixes BXC #10026
> [MacToolbar] Show the selector menu on button press [c7]

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/OptionsDialog.cs
> [IDE] Disable maximize/minimize on Preferences dialog [c7]

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/OptionsDialog.cs
> [IDE] Disable maximize/minimize on Preferences dialog

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/GtkWorkarounds.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/IdeDialog.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/OptionsDialog.cs
> [IDE] Disable minimize/maximise for dialogs on OS X [c7]

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/OptionsDialog.cs
> [Ide] Restore the last visited option panel

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/OptionsDialog.cs
> [Ide] Restore the last visited option panel [c7]

- main/src/addins/MacPlatform/MainToolbar/MainToolbar.cs
- main/src/addins/MacPlatform/MainToolbar/SearchBar.cs
> [Mac] Remove searchbar logging.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/ExtensibleTreeView.cs
(cherry picked from commit ad21cd689365e58025cbb3bdbb04862cbc8563ad)
> [Ide] Support selected overlay style in ExtensibleTreeView

- main/src/core/MonoDevelop.Ide/gtkrc.mac
- main/src/core/MonoDevelop.Ide/gtkrc.mac-dark
(cherry picked from commit a401ee415f35bbdd182397af92af0e146ac5c25f)
> [Ide][Mac] Disable focus rectangle in tree views

- main/src/addins/MacPlatform/MainToolbar/RunButton.cs
- main/src/addins/MacPlatform/MainToolbar/SearchBar.cs
- main/src/addins/MacPlatform/MainToolbar/SelectorView.cs
Bug 40134 - [Xamarin Studio] XS 6 crashes on startup due to
NullReferenceException
> [Mac] More aggressively nullcheck Window/Screen of a view.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs
There was a potential race condition when scheduling the preferences save after the workbench tabs had changed because the timer uses threads. Use an AsyncCriticalSection to avoid blocking the UI thread
Fixes BXC #40140
> [IDE] Fix race conditions when scheduling preferences save

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeIssues/CodeDiagnosticRunner.cs
> [Refactoring] Reduced the amount of thread pool threads required for

- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/AssemblyBrowserWidget.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/AssemblyLoader.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/AssemblyBrowserTypeNodeBuilder.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/AssemblyNodeBuilder.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/DomEventNodeBuilder.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/DomFieldNodeBuilder.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/DomMethodNodeBuilder.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/DomPropertyNodeBuilder.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/TreeNodes/DomTypeNodeBuilder.cs
Browser.'
widget.CecilLoader.LoadAssembly isn.t thread safe so it needs to run
on the main thread.
> Fixed 'Bug 40316 - [Cycle 7]User is not able to Search dll in Assembly

- main/src/addins/ChangeLogAddIn/CommitDialogExtensionWidget.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/EditBranchDialog.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/UrlBasedRepositoryEditor.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/gtk-gui/MonoDevelop.VersionControl.UrlBasedRepositoryEditor.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/gtk-gui/gui.stetic
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/ProjectFileNodeBuilder.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/SolutionFolderFileNodeBuilder.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DefaultWorkbench.cs
(cherry picked from commit 9bd0d01638799d61b675afb3067436f2a51e6fdf)
> [Ide] Fix missing error color parametrization [c7]

- main/src/addins/MacPlatform/Dialogs/MacOpenFileDialogHandler.cs
- main/src/addins/MacPlatform/Dialogs/SelectEncodingPopUpButton.cs
- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/addins/MacPlatform/MacPlatform.csproj
- main/src/addins/MacPlatform/MainToolbar/SearchBar.cs
- main/src/addins/MacPlatform/MainToolbar/SelectorView.cs
- main/src/addins/MacPlatform/MainToolbar/StatusBar.cs
Fix all the warnings in the MacPlatform code
> [MacPlatform] Fix warnings

- main/tests/UserInterfaceTests/Controllers/NewFileController.cs
- main/tests/UserInterfaceTests/Controllers/NewProjectController.cs
- main/tests/UserInterfaceTests/Controllers/NuGetController.cs
- main/tests/UserInterfaceTests/UserInterfaceTests.csproj
- main/tests/UserInterfaceTests/VersionControlTests/Git/GitBase.cs
- main/tests/UserInterfaceTests/VersionControlTests/VCSBase.cs
Fix warnings in UI Tests and turn on warnings as errors.
> [UI Test] Fix warnings

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Rename/RenameRefactoring.cs
subsequent document elements to be removed.'
> Fixed 'Bug 40464 - Rename refactoring a method parameter causes

- main/po/uk.po
> Ukrainian ui update

- main/src/addins/WindowsPlatform/WindowsPlatform/MainToolbar/ComboMenu.cs
(fixes bug #40452)
(cherry picked from commit 7962a37fb932c4bad16899cb931fa3d3f1217305)
> [Win][c7] Fix Bug 40452 - Device Dropdown getting "White" when user attach or remove the device

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/LogView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/ProgressMonitors.cs
Bug 40373 - Null reference exception in ScrollView
cc @alanmcgovern
> [Ide] Fix concurrency on defaultmonitorpad accessing.

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/RefactoringSymbolInfo.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
Highlighting or Code completion'
> Fixed 'Bug 40454 - Opening a new solution doesn't get Syntax

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
sometimes fails with a null reference exception.'
> Fixed 'Bug 40582 - The fix action "Using 'some namespace import'"

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DefaultWorkbench.cs
There was a race condition when saving layouts so refactored the code to use async await instead of Timers
> [IDE] Fix a crash when saving layouts

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopSourceTextContainer.cs
It's not a real fix - but without the cause it's impossible to tell
why that happened. However the editor should now recover and no longer
stop working.
> Fixed 'Bug 40504 - Once in a while the text editor stops working'

- main/src/addins/CSharpBinding/MonoDevelop.CSharp/CSharpNavigationTextEditorExtension.cs
- main/src/core/Mono.Texteditor/Mono.TextEditor/Document/TextDocument.cs
request links on the UI thread.
> [CSharpBinding] Navigation text editor extension no longer does

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs
This is a side effect of using async save operations.
> Fixed 'Bug 40710 - Crash closing a window in XS'

- main/po/zh_CN.po
Chinese Simplified language pack has been translated to 14%, I will continue to translate until 100%
> zh_CN.po   14%

- main/src/core/MonoDevelop.Ide/ExtensionModel/Commands.addin.xml
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.OptionPanels/KeyBindingsPanel.cs
This fixes the branding icon (and maybe some others) in the key bindings option panel.
> [C7][Ide] Run command update handlers in key bindings option panel

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/BreakpointPad.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/StackTracePad.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ThreadsPad.cs
Needed for automating and asserting items when testing Debugging functionality
> Added SemanticModelAttribue to Breakpoint,StackTrace and Threads pad

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Diagnostics/InconsistentNaming/NameConventionPanelWidget.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpFormattingProfileDialog.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValueTreeView.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeIssues/CodeIssuePanelWidget.cs
- main/src/addins/MonoDevelop.RegexToolkit/MonoDevelop.RegexToolkit/ElementHelpWidget.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.OptionPanels/HighlightingPanel.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeTemplates/CodeTemplatePanel.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/ExtensibleTreeView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/OptionsDialog.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.OptionPanels/KeyBindingsPanel.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/TemplatePickerWidget.cs
This prevents a memory leak with the data func, so it does not keep everything it references in memory.
> [WIP] Use static treeviewcolumn data funcs

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
@mkrueger can you review this solution? what do you think? Check also https://github.com/xamarin/md-addins/pull/1093
> Bug 41238 - Xamarin.Forms/Xaml/ Shared projects break code editor

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Features/Completion/CompletionEngine.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Features/Completion/ContextHandler/ObjectCreationContextHandler.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/Features/CodeCompletion/NR5/KeywordTests.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/Features/CodeCompletion/NR6/MiscTests.cs
A very special case which shows a little bug in type inference. Fixed
with a work around.
> Fixed 'Bug 41388 - Code completion is incorrect for array types'

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Features/ParameterHinting/ParameterHintingEngine.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/Features/ParameterHinting/ParameterHintingTests.cs
> Fixed 'Bug 41351 - No arguments code completion for methods called via

- main/src/addins/MacPlatform/MainToolbar/SelectorView.cs
This is a corresponding PR to https://github.com/mono/monodevelop/pull/1258 
This PR would help us select the device via test frameworks so that we can automate deploy to device
> When ActiveRuntime is changed, fire RuntimeChanged event

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
> Fixed 'Bug 41358 - Xamarin Stuidio crashed on add GTK# widget signal

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Subversion.Unix/MonoDevelop.VersionControl.Subversion.Unix.csproj
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Subversion.Unix/MonoDevelop.VersionControl.Subversion.Unix/SvnClient.cs
Need :eyes: from @slluis. When this is confirmed to be okay, I'll backport to C7.
> [Svn] Implement support to install Command Line Tools on demand.

- main/src/addins/MacPlatform/MainToolbar/StatusBar.cs
Bug 41720 - Add tooltip to searchbar cancellation
> [StatusBar] Implement cancellation tooltip.

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/NewProjectController.cs
Btw, this is not regression compared to C6(XS 5.10) I can reproduce same thing there.
https://bugzilla.xamarin.com/show_bug.cgi?id=40344
> Bug 40344 - [Cycle7] When user creates a project with same name then XS create two Projects

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Features/ParameterHinting/ParameterHintingEngine.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/Features/CodeCompletion/NR6/MiscTests.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/Features/ParameterHinting/ParameterHintingTests.cs
constructors and showing too many things'
> Fixed 'Bug 41245 - Attribute code completion not showing all

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
This refactors the code so both code paths use the same logic.
The problem of the old code was that for directory statuses, we'd query
the whole tree for conflicts and iterate all the index entries when
setting the info, thus doing an index refresh each time.
In comparison old and new case, we have these relative values:
[old] 128 OnGetDirectoryVersioninfoCalls with 222000ms
[new] 48 OnGetDirectoryVersionInfo calls with 50000ms
This optimizes by approximately 40%.
> [VCS] Optimize status querying

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild.Conditions/ConditionTokenizer.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildEvaluationContext.cs
> Solution load memory traffic decrease

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Features/IndentEngine/IndentState.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/Features/IndentationTests/AlignmentTests.cs
inline List<enum> initialisation'
> Fixed 'Bug 42310 - Extra indentation when using Smart indentation with

- main/src/core/Mono.Texteditor/Mono.TextEditor.Highlighting/SyntaxMode.cs
- main/src/core/Mono.Texteditor/SyntaxModes/FSharpSyntaxMode.xml
https://bugzilla.xamarin.com/show_bug.cgi?id=42239
> Cycle7 fix 42239

- main/src/core/MonoDevelop.Ide/options/KeyBindingSchemeVisualStudio-mac.xml
- main/src/core/MonoDevelop.Ide/options/KeyBindingSchemeVisualStudio.xml
(cherry picked from commit 558e999b4e1c969cdd0da59f528828bdfda05c5d)
> [Ide] Fix duplicate binding in VS schemes

- main/src/addins/Deployment/MonoDevelop.Deployment/MonoDevelop.Deployment/DeployService.cs
- main/src/addins/MonoDevelop.Autotools/MakefileData.cs
- main/src/addins/MonoDevelop.DocFood/MonoDevelop.DocFood/DocGenerator.cs
- main/src/addins/TextTemplating/TextTransform/Options.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/LogWidget.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/PcFileCache.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Execution/LocalConsole.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/IMSBuildPropertySet.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProject.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects.Text/TextFormatter.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbarController.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/SearchResult.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeTemplates/CodeTemplate.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/SearchResultWidget.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/Ambience.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MarkupUtilities.cs
https://github.com/mono/monodevelop/commit/ba4c744b29c7ee493de9100af432ff029eeaf248 and https://github.com/mono/monodevelop/commit/eecb9bfe7adf4152db08214f7c3c8233fa9b9ce6 are general purpose commits. The commit most important commit is https://github.com/mono/monodevelop/commit/50ebb30a842d05d765ca0de052246fd55038aa92.
> Traffic decrease

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.DockNotebook/DockWindow.cs
Fixed bug #31345 - Save file closed and confirmation popup is
appearing in Notebook window.
https://bugzilla.xamarin.com/show_bug.cgi?id=31345
Saved files are now no longer closed in a floating window before
unsaved files are saved. This allows the user to cancel the save and
all the files that were previously open will remain open in the
floating window.
When multiple unsaved files are open and the floating window is closed
only a single save file dialog will now be displayed with all the
files listed, each with a check box allowing a file to be saved or
not. Previously a save file dialog would appear for each unsaved file.
If there is only one unsaved file then the standard save file dialog is
used, the same as if you were closing a single unsaved file, that does
not have the check …
> [Ide] Improve handling of unsaved files in floating windows.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.DockNotebook/DockWindow.cs
Fixed bug #31345 - Save file closed and confirmation popup is
appearing in Notebook window.
https://bugzilla.xamarin.com/show_bug.cgi?id=31345
Saved files are now no longer closed in a floating window before
unsaved files are saved. This allows the user to cancel the save and
all the files that were previously open will remain open in the
floating window.
When multiple unsaved files are open and the floating window is closed
only a single save file dialog will now be displayed with all the
files listed, each with a check box allowing a file to be saved or
not. Previously a save file dialog would appear for each unsaved file.
If there is only one unsaved file then the standard save file dialog is
used, the same as if you were closing a single unsaved file, that does
not have the check …
> [Cycle8][Ide] Improve handling of unsaved files in floating windows.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/FolderNodeBuilder.cs
> [C8][Ide] Optimize initial Add File location [Bug 8506][Bug 18568]

- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/SyntaxHighlighting.fs
- main/src/core/Mono.Texteditor/SyntaxModes/FSharpSyntaxMode.xml
https://bugzilla.xamarin.com/show_bug.cgi?id=42575
> [F#] Fixes syntax issue #42575

- main/Makefile.am
- main/monodevelop.appdata.xml
This is displayed in GNOME and KDE software installers.
See https://people.freedesktop.org/~hughsient/appdata/
> Added an AppData file for Linux app stores

- main/Main.sln
- main/src/addins/PerformanceDiagnostics/PerformanceDiagnostics/Commands.cs
- main/src/addins/PerformanceDiagnostics/PerformanceDiagnostics/GlobalOptionsDialog.cs
- main/src/addins/PerformanceDiagnostics/PerformanceDiagnostics/Options.cs
- main/src/addins/PerformanceDiagnostics/PerformanceDiagnostics/PerformanceDiagnosticsAddIn.csproj
- main/src/addins/PerformanceDiagnostics/PerformanceDiagnostics/Properties/AddinInfo.cs
- main/src/addins/PerformanceDiagnostics/PerformanceDiagnostics/Properties/AssemblyInfo.cs
- main/src/addins/PerformanceDiagnostics/PerformanceDiagnostics/Properties/PerformanceDiagnostics.addin.xml
- main/src/addins/PerformanceDiagnostics/PerformanceDiagnostics/UIThreadMonitor.cs
- main/src/addins/PerformanceDiagnostics/UIThreadMonitorDaemon/Program.cs
- main/src/addins/PerformanceDiagnostics/UIThreadMonitorDaemon/Properties/AssemblyInfo.cs
- main/src/addins/PerformanceDiagnostics/UIThreadMonitorDaemon/UIThreadMonitorDaemon.csproj
Which samples cpu usage when UIThread doesn't respond
> Added PerformanceDiagnosticsAddIn with UIThreadMonitor tool

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Parser/TypeSystemProvider.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/TypeSystemParserNode.cs
This is fixing https://bugzilla.xamarin.com/show_bug.cgi?id=42389
> [Ide] Check file extension for compilation check as well.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/DockItem.cs
Use DesktopService to set window size and position.
(fixes bug# 37189)
> [Ide][Bug 37189] Fix placement of floating tabs

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Highlighting/HighlightUsagesExtension.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Refactoring/CSharpFindReferencesProvider.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Refactoring/FindReferencesHandler.cs
variable assignments when doing Find References"
> Fixed "Bug 42674 - In XS 6, Search Results no longer shows red for

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/MonoDevelopStatusBar.cs
Don't create widgets that are never displayed or used.
> [IDE] Cleanup the MonoDevelopStatusBar

- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/CopyPaste.fs
- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/MonoDevelop.FSharp.Tests.fsproj
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpIndentationTracker.fs
> Fixes copy paste indent when top line is empty.

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.CodeFixes/MoveTypeToFile/MoveTypeToFile.cs
Basically cherry picked b4ac3b5e to C8 minus .csproj change
> Bug 43797 - Moving class to its own file from Shared Asset Project adds the file to the wrong project

- main/build/MacOSX/monostub.m
- main/src/core/MonoDevelop.Core/MonoDevelop.Core/Gettext.cs
This issue is new in Sierra, where the preferred user interface
language contains regional information (which it should not).
In El Capitan, having Language set to English and Region set to Romania
would set [NSLocale currentLocale] to en_RO, while [NSLocale
preferredLanguage[0]] to en.
In Sierra, both now happen to be en_RO, which causes issues if you have
multiple preferred languages and as a result, causes bug
https://bugzilla.xamarin.com/show_bug.cgi?id=43806
> [Stub] Implement support for hijacking language if none is set in XS.

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/DefaultMSBuildEngine.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildEvaluationContext.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildPropertyGroup.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildPropertyGroupEvaluated.cs
- main/tests/UnitTests/MonoDevelop.Projects/MSBuildProjectTests.cs
- main/tests/test-projects/msbuild-project-test/test.csproj
- main/tests/test-projects/msbuild-tests/transforms.csproj
Among better support for complex MSBuild projects, it fixes bug #43509 - Failure
to evaluate msbuild item properties
> Add support for msbuild transforms and item functions

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.ClassOutline/CSharpOutlineTextEditorExtension.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Project/CompilerOptionsPanelWidget.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/AssemblyBrowserWidget.cs
- main/src/addins/MonoDevelop.Gettext/MonoDevelop.Gettext.Editor/POEditorWidget.cs
- main/src/addins/MonoDevelop.RegexToolkit/MonoDevelop.RegexToolkit/ElementHelpWidget.cs
- main/src/addins/MonoDevelop.RegexToolkit/MonoDevelop.RegexToolkit/RegexToolkitWidget.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.OptionPanels/HighlightingPanel.cs
- main/src/addins/TextTemplating/MonoDevelop.TextTemplating/Gui/T4EditorExtension.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/ChangeSetView.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/LogView.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/LogWidget.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/StatusView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.DockNotebook/TabStrip.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/SearchEntry.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/SearchResultWidget.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/ExtensibleTreeView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/DirtyFilesDialog.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/OptionsDialog.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.OptionPanels/KeyBindingsPanel.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DefaultWorkbench.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/NewFileDialog.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/TemplatePickerWidget.cs
This is a branch that fixes issues that appeared due to gtk# now behaving properly.
ListStore/TreeStore is managed by the TreeView, so no need to dispose.
The rest of the commits are self explanatory.
> Gtk# memory leak fixes

- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Execution/ProcessWrapper.cs
This moves the ProcessWrapper to use tasks instead of threads. The net benefit of this is that we use 60 less threads for loading Main.sln, as the threads are now assigned to threadpool threads.
Reduces total time spent in CaptureError from 60s to 0.8ms and CaptureOutput from 64s to 33ms.
> [Core] Optimize ProcessWrapper threads usage.

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs
- main/src/core/Mono.Texteditor/Mono.TextEditor/Document/TextDocument.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/InternalExtensionAPI/ITextEditorImpl.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextEditor.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/SdiWorkspaceWindow.cs
Take the second commit with a grain of salt, as I suck at naming. Any suggestion on what to replace 'SomethingSomething' with?
cc @DavidKarlas this fixes the issue you've been having.
cc @slluis and @mkrueger for sanity reviews.
> Editor optimizations

- main/src/core/Mono.Texteditor/Mono.TextEditor.Utils/TextFileUtility.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Text/TextFileUtility.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core/FileService.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionFolderItem.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/OptionsDialog.cs
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=44809
> Fix saving project.json on Windows

- main/src/addins/MacPlatform/MacExternalConsoleProcess.cs
If there is another app on the system called Terminal, then
opening an external console could fail. Fix this by using an
explicit path to Terminal.app.
> [Mac] Fix issue opening external console

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.OptionPanels/PortableRuntimeOptionsPanel.cs
> [netstandard] Add Name property to netstandard combo and entry

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/TypeSystemService_WorkspaceHandling.cs
- main/tests/UnitTests/MonoDevelop.Projects/ProjectTests.cs
- main/tests/test-projects/csharp-app-fsharp-lib/csappfslib.sln
- main/tests/test-projects/csharp-app-fsharp-lib/csappfslib/Program.cs
- main/tests/test-projects/csharp-app-fsharp-lib/csappfslib/Properties/AssemblyInfo.cs
- main/tests/test-projects/csharp-app-fsharp-lib/csappfslib/csappfslib.csproj
- main/tests/test-projects/csharp-app-fsharp-lib/fslib/AssemblyInfo.fs
- main/tests/test-projects/csharp-app-fsharp-lib/fslib/Component1.fs
- main/tests/test-projects/csharp-app-fsharp-lib/fslib/Script.fsx
- main/tests/test-projects/csharp-app-fsharp-lib/fslib/fslib.fsproj
Looks like this hasn't been working for at least 18 months
> Ensure F# projects are output tracked. Fixes #45556

- main/src/addins/GnomePlatform/Gio.cs
More leaks in GIO. Not all of them my fault.
> [gnome] Fix more GIO leaks

- main/external/fsharpbinding/MonoDevelop.FSharp.Shared/MonoDevelop.FSharp.Shared.fsproj
- main/external/fsharpbinding/MonoDevelop.FSharp.Shared/paket.references
- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/MonoDevelop.FSharp.Tests.fsproj
- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/Samples/Xamarin.iOS.fsproj
- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/Samples/android/fsandroid.fsproj
- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/Samples/android/fsandroidnuget2/fsandroidnuget2.fsproj
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpBinding.addin.xml
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/MonoDevelop.FSharp.fsproj
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Templates/FSharpConsoleProject.xpt.xml
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Templates/FSharpGtkProject.xpt.xml
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Templates/FSharpLibraryProject.xpt.xml
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Templates/FSharpNUnitLibraryProject.xpt.xml
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Templates/FSharpTutorialProject.xpt.xml
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Templates/PortableLibrary.xpt.xml
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/paket.references
- main/external/fsharpbinding/MonoDevelop.FSharpi.Service/MonoDevelop.FSharpInteractive.Service.fsproj
- main/external/fsharpbinding/MonoDevelop.FSharpi.Service/paket.references
- main/external/fsharpbinding/paket.lock
Updates MonoDevelop and the F# templates to use NuGet version of FSharp.Core.
> Nuget fsharp core

- main/external/fsharpbinding/MonoDevelop.FSharp.Shared/Lexer.fs
- main/external/fsharpbinding/MonoDevelop.FSharp.Shared/MonoDevelop.FSharp.Shared.fsproj
- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/MonoDevelop.FSharp.Tests.fsproj
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpTokens.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/MonoDevelop.FSharp.fsproj
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/ProjectSearchCategory.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/CompilerArguments.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/FSharpConsoleView.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/LanguageService.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/Lexer.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/TooltipHelpers.fs
- main/external/fsharpbinding/MonoDevelop.FSharpi.Service/MonoDevelop.FSharpInteractive.Service.fsproj
- main/external/fsharpbinding/paket.dependencies
- main/external/fsharpbinding/paket.lock
> [F#] update compiler to 8.0.0

- main/src/addins/CSharpBinding/MonoDevelop.CSharp/PathedDocumentTextEditorExtension.cs
Fixes an exception reported by Marek Habersack
> [CSharpBinding] Fixed possible null reference exception.

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProjectService.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionFolder.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionItem.cs
Can @mrward or @slluis can you do review?
I'm hoping to get this in before vNext preview 2. Since XS is having problems with changing ItemId on project.
> [Core] Set ItemId of .Net Core project to .sln value or in case of Reload to old ItemId

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects.SharedAssetsProjects/SharedAssetsProject.cs
Fixes bug #46960
File MyClass.cs could not be written. error when adding new shared library to solution
https://bugzilla.xamarin.com/show_bug.cgi?id=46960
> [Core] Handle NRE when determining if a file is compilable

- main/src/addins/Xml/Editor/BaseXmlEditorExtension.cs
> Fixed 'Bug 40966 - [Cycle 7] Cursor is not displaying at proper

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
This fixes a weird bug where common text editing commands like copy/paste don't work inside native dialogs (save/open file, etc).
The patch tries to call the corresponding Selector on the active NSWindow, which is the same what the default Cocoa inplementation would do, if `PerformKeyEquivalent` fails (native entries respond to the special `copy:`, `paste:`, etc. selectors and don't handle such key shortcuts directly)
(fixes bug #45134)
(fixes bug #48244)
@Therzok or @iainx could you review? I'm not sure, maybe I missed something...
> [Ide][Mac] Fix copy/paste commands inside native dialogs

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
#1706 fixes https://bugzilla.xamarin.com/show_bug.cgi?id=45134 which looks like a major bug to me (it affects not only the "Go to folder" entry in file dialogs, but all native Cocoa dialogs). So lets cherry-pick it to `cycle9`.
> [C9][Mac] Fix copy/paste commands inside native dialogs

- main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/CorDebuggerSession.cs
More extensive search of pdb files that allows to load pdb specified in .dll/.exe debug info. (E.g. pdb file can be located at different location than dll/exe)
> [CorDebug] More extensive search of pdb files

- main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/CorObjectAdaptor.cs
Now OverloadResolve() returns a pair of MethodInfo and CorType which this method was found in. This allows to perform RuntimeInvoke on a correct CorType (not given targetType, but actual method owner which can be base type of target) and pass correct TypeParameters.
Example:
Project 1:
public class GenericClass<T>
{
public T Get(T arg)
{
return arg;
}
}
Project 2:
public class GenericDerived : GenericClass<int>
{
}
internal class Program
{
public static void Main(string[] args)
{
var gd = new GenericDerived();
Console.WriteLine(gd.Get(4));
}
}
Before this fix evaluation of gd.Get(4) didn't work.
> [CorDebug] Overload resolve fixed

- main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/CorDebuggerSession.cs
BreakpointsAndSteppingTests.BreakpointInsideOneLineDelegateAsync
BreakpointsAndSteppingTests.DebuggerHiddenMethod
BreakpointsAndSteppingTests.DebuggerNonUserCodeMethod
BreakpointsAndSteppingTests.DebuggerStepThroughMethod
> Set JMC fix to repair tests

- main/src/addins/MonoDevelop.Debugger.Win32/CorApi2/Extensions/MetadataExtensions.cs
Fixes some exceptions in evaluation
> Metadata extensions fixes

- main/src/addins/MonoDevelop.Debugger.Win32/CorApi2/CorApi2.csproj
- main/src/addins/MonoDevelop.Debugger.Win32/CorApi2/debug/PdbHResult.cs
- main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/CorDebuggerSession.cs
If pdb loading failed the debugger shows the named error code in output.
> Named error codes on PDB loading.

- main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/CorDebuggerSession.cs
* Breakpoint activation exceptions are handled and shown to a user as human readable status.
* Now breakpoint condition or trace expressions is evaluated on separate thread to avoid deadlock.  We can't perform any evaluations inside the event handler, because the debugger thread is busy and we won't get any evaluation events there.
* NewString() and NewArray() unified into the new method NewSpecialObject(). Some issues are fixed in its logic: now OnEndEvaluating is called in finally block, eval.Abort() called after timeout, eval objects are checked in handler
> [CorDebug] Breakpoints fixes

- main/src/addins/MonoDevelop.Debugger.Win32/CorApi2/CorApi2.csproj
- main/src/addins/MonoDevelop.Debugger.Win32/CorApi2/debug/HResultUtil.cs
- main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/CorDebuggerSession.cs
> ToHResult() extension method to convert COMException code to defined HResult

- main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/CorObjectAdaptor.cs
More info at https://youtrack.jetbrains.com/issue/RIDER-2102
> Fix for evaluation of Nullable properties.

- main/po/po.mdproj
- main/src/addins/MonoDevelop.Gettext/MonoDevelop.Gettext.Editor/POEditorWidget.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Gui/AddPackagesDialog.UI.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.NodeBuilders/PackageReferenceNode.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.NodeBuilders/ProjectPackagesFolderNode.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionItem.cs
- main/src/core/MonoDevelop.Ide/ExtensionModel/MainMenu.addin.xml
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/CustomStringTagProvider.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/ViewCommands.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.OptionPanels/MonoRuntimePanel.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.WelcomePage/WelcomePageFeedItem.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.WelcomePage/WelcomePageRecentProjectsList.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/LocalizationService.cs
- main/src/core/MonoDevelop.Ide/gtk-gui/MonoDevelop.Ide.Gui.OptionPanels.MonoRuntimePanelWidget.cs
https://github.com/mono/monodevelop/pull/1733, but on top of master and without the last commit which affects the tabstrip
> Master translation fixes

- main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/CorDebuggerSession.cs
Changed insertion of breakpoints in CorDebuggerSession, now they are set to the outermost method, instead of how it was before:
In this example breakpoint on line 9 is set to the begin of lambda block
Now it looks like this:
> Fixed way of choosing best sequence point for breakpoints in CorDebuggerSession

- main/build/MacOSX/monostub-utils.h
Patch done by @mhutch.
Bug 51527 - [Installer]XS failed to open with Cycle9 Preview installer
> [Mac] Avoid forking to get Xcode path.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
Removes an intermediary list that's used to add CommandHandlers.
> [Ide] Optimize CommandHandler type handler generation.

- main/build/MacOSX/monostub.m
- version-checks
This is https://github.com/mono/monodevelop/pull/1703 for cycle9
> Cycle9 native servicehub launcher

- main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.MSBuild.Shared/BuildEngine.Shared.cs
- main/src/core/MonoDevelop.Projects.Formats.MSBuild/MonoDevelop.Projects.MSBuild.Shared/Main.cs
I hope I explained enough in commets
> [MSBuild] Fix problem with loading MSBuild.Build.dll outside GAC(in case of MSBuild instead of XBuild)

- main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/CorDebuggerSession.cs
Fixed bug with line breakpoints in several app domains. If you insert line breakpoint (CorDebuggerSession), it was resolved only for first app domain with appropriate symbols. Now any BreakEventInfo for line breakpoint contains list of CorFunctionBreakpoints
> insert corFunctionBreakpoints in several app domains

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.ClassOutline/CSharpOutlineTextEditorExtension.cs
> OutlineTreeView was null and causing a NRE

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/CredentialsDialog.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitService.cs
I could not repro the issue in 37638, and this is purely based on assumption of what is going on.
> Cycle9 37638

- main/src/addins/MonoDevelop.Debugger.Win32/CorApi/CorApi.csproj
- main/src/addins/MonoDevelop.Debugger.Win32/CorApi2/CorApi2.csproj
- main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/Mono.Debugging.Win32.csproj
Can be used to sign assemblies with custom key
> Custom properties for Win32 debugger projects

- main/src/addins/MonoDevelop.Debugger.Win32/CorApi/CorApi.csproj
- main/src/addins/MonoDevelop.Debugger.Win32/CorApi2/CorApi2.csproj
- main/src/addins/MonoDevelop.Debugger.Win32/Mono.Debugging.Win32/Mono.Debugging.Win32.csproj
Fixed path to relative without variables. If open the projects from custom solution the importing fails
> Import path fix

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/DebugValueWindow.cs
> [Debugger] Fixed bug with closing ObjectTreeView popup after closing Preview window

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
Throttle how frequently we dispatch commands that originate from keyboard shortcuts.
This is a revision of https://github.com/mono/monodevelop/pull/1802 and isn't specific to undo/redo. The bug can be reproduced using Cmd-V (Paste) and possibly other commands, so this PR fixes those as well.
https://bugzilla.xamarin.com/show_bug.cgi?id=34828
> [Mac] Throttle keyboard command dispatch

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.Tests/EvaluationTests.cs
This should be merged after https://github.com/mono/debugger-libs/pull/97 is merged and debugger-libs sumboulde bumped
> Unit tests for Bug 44851

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Templates/FSharpConsoleProject.xpt.xml
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Templates/FSharpLibraryProject.xpt.xml
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Templates/PortableLibrary.xpt.xml
> [F#] Fix link to fsharp.org in the templates.

- main/src/core/Mono.Texteditor/Mono.TextEditor.Utils/ImmutableText.cs
The code would infinitely loop until it went out of bounds.
> [Editor] Fix ImmutableText.WriteTo implementation.

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.Tests/EvaluationTests.cs
Unit tests for Bug 52333 it needs https://github.com/mono/debugger-libs/pull/99 merged&bumped before merging
> [Debugger.UnitTests] Unit tests for bug 52333

- main/tests/UnitTests/TestBase.cs
Take into account that Mono 4.9.x now generates .pdb files
> Fix solution tests

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
Fast msbuild operations don't require an exclusive lock to the builder
anymore. This should reduce builder allocation when loading a project,
since many quick targets needs to be executed after loading.
> Reduce project builder allocation

- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Execution/RemoteProcessConnection.cs
This fixes one race condition and then rewrites some continuation based code to be async/await as it is a bit easier to reason about.
> Remote connection race condition

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ExceptionCaughtDialog.cs
This is just reopened https://github.com/mono/monodevelop/pull/1847
> [Debugger] Added “Help link” to exception dialog and navigation on click

- main/src/addins/MacPlatform/MainToolbar/SelectorView.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Execution/ExecutionTarget.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbarController.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbarModels.cs
Implemented abstraction and mac backend for the toolbar selector requests.
> Toolbar requests

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.csproj
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetMigrate.cs
- main/src/addins/MonoDevelop.DotNetCore/Properties/MonoDevelop.DotNetCore.addin.xml
> [DotNetCore] Implementing `dotnet migrate` support inside IDE

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.csproj
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreExecutionCommand.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreExecutionHandler.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreRunConfiguration.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreRunConfigurationEditor.cs
- main/src/addins/MonoDevelop.DotNetCore/Properties/MonoDevelop.DotNetCore.addin.xml
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.OptionPanels/AssemblyRunConfigurationEditor.cs
Pretty happy with end result:
Application starts on correct url and browsers launches right after server starts listening(same as VS.net does it, by trying to connect to web server address).
> [DotNetCore] Added ASP.NET Core specific RunConfiguration settings(AppURL and LaunchBrowser)

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildEvaluationContext.cs
Fixes bug #52648 - MonoMacBuildExtension.UnpackContent fails to create
a directory
> Fix issue when building legacy projects

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpTextPasteHandler.cs
Mirror of adb6d8ab08d3b09092b5385af4bcc4632bd9785e
> [CSharpBinding] Fixed paste handler calculation.

- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/Interactive.fs
- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/MonoDevelop.FSharp.Tests.fsproj
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpInteractivePad.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/InteractiveSession.fs
- main/external/fsharpbinding/MonoDevelop.FSharpi.Service/MonoDevelop.FSharpInteractive.Service.fsproj
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=52721
> [F#] Fixes interactive window. Fixes #52721

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
While trying to reproduce and verify bug fix from fc37fbf I found few more issues
> Bug 51614 - Document is not part of the workspace exception

- main/src/addins/MonoDevelop.UnitTesting/Services/AbstractResultsStore.cs
This is a tentative fix for a concurrency case on registering unit tests.
Based on the stacktrace in the bug report, this seems like the TestRecord
is modified concurrently, thus causing issues on getting an item that
would've been added/removed (i.e. array resize).
Bug 42513 - Test result store seems to be corrupted - internal error when running many tests
> [NUnit] Concurrent-safe AbstractResultsStore

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
- main/tests/UnitTests/MonoDevelop.Projects/GetSourceFilesAsyncTests.cs
- main/tests/test-projects/project-with-corecompiledepends/project-with-conditioned-file.csproj
> [Core] Fix caching issue when getting source files

- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/SyntaxHighlighting.fs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/syntaxes/FSharp/F#.sublime-syntax
> [F#] Fixes a couple of highlighting bugs

- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/TextLinkEditMode.cs
Allow deletion of selection
Fix errors with multiple links
Delete dead code (this.window was never non-null)
> Fix for link text edit bugs:

- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/ProjectTests.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpProjectFileNodeExtension.fs
DotNet core projects don't have a default namespace, so the xml
reordering code was broken for these projects.
Fixed by detecting the default namespace instead of assuming one.
> [F#] Allow dotnet core file reordering

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreExecutionHandler.cs
Modify launch browser mechanism to use an http request instead of a socket connection.  This is more reliable in circumstances where the requested port is already listening.
> Modify launch browser mechanism to use an http request.

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreExecutionHandler.cs
Remove HttpRequest logic due to unintended side-effects, reverting back to TCP logic.  Add brief delay to allow server process to initialize.
> Remove HttpRequest logic due to unintended side-effects

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeFixMenuService.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core/Runtime.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/GtkWorkarounds.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/FolderNodeBuilder.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/GlobalOptionPersister.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MetadataReferenceCache.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
- main/winbuild.bat
And a whole bunch of other buglets I found along the way.
> Fix "Move Type to file" code action

- main/Makefile.am
https://github.com/xamarin/md-addins/pull/1647 will probably fix it but doing it also here, just to be safe
> Bug 54154 - NuGet restoration fails with latest Mono

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.csproj
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSystemInformation.cs
- main/src/addins/MonoDevelop.DotNetCore/Properties/MonoDevelop.DotNetCore.addin.xml
Show the path to the .NET Core runtime, SDK and MSBuild SDKs if they
exist.
> [DotNetCore] Show .NET Core info in About dialog

- version-checks
> [A11y] Bump md-addins

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DefaultWorkbench.cs
> [A11y] Only set the accessibility if the window is not NULL

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/NewProjectConfiguration.cs
- main/tests/UnitTests/MonoDevelop.Ide.Templates/FinalProjectConfigurationTests.cs
Fixed bug #53844 - Unable to create projects with name including '-'
character
https://bugzilla.xamarin.com/show_bug.cgi?id=53844
> [Ide] Allow dash character in project names

- .gitmodules
Switch from 4.0.0 to master branch.
> Update target branch for nuget-binary

- main/src/addins/MacPlatform/MainToolbar/StatusBar.cs
> [Mac] Make the status bar offset bigger on ElCap/Sierra

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs
Remove dead code (parentSolution is never used).
> Rename UnsubscibeAnalysisdocument -> UnsubscribeAnalysisDocument.

- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/Toolbox.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/ToolboxWidget.cs
> [A11y] Improve the accessibility of the Toolbox pad

- main/src/addins/MonoDevelop.UnitTesting/Gui/TestPad.cs
- main/src/addins/MonoDevelop.UnitTesting/Gui/TestResultsPad.cs
> [A11y] Add accessibility attributes to the test pads

- main/src/addins/MonoDevelop.DocFood/MonoDevelop.DocFood/DocFoodTextEditorExtension.cs
> Fixed 'Bug 54936 - Unable to type in third '/' when gathering class

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Highlighting/HighlightUsagesExtension.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Navigation/FindDerivedSymbolsHandler.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Refactoring/FindReferencesHandler.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Refactoring/RefactoryCommands.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Rename/RenameRefactoring.cs
assignments when file not in project'
> Fixed 'Bug 54787 - Highlight identifier references only working for

- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/CompilerArguments.fs
- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/Interactive.fs
- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/MonoDevelop.FSharp.Tests.fsproj
- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/SyntaxHighlighting.fs
- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/TestHelpers.fs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/syntaxes/FSharp/F#.sublime-syntax
Fixes some of the broken F# tests. The other tests will be fixed in a mono bump later.
> D15 2 fix fsharp tests

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AtkCocoaHelper/AtkCocoaHelper.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads/TaskListPad.cs
> [A11y] Add accessibility attributes for the Task pad

- main/src/addins/CSharpBinding/CSharpBinding.csproj
- version-checks
Fixes tests.
Needs https://github.com/xamarin/md-addins/pull/1738 to be merged
> F#/mono bump

- main/src/addins/CSharpBinding/MonoDevelop.CSharp/SignatureMarkupCreator.cs
in the preview tooltip in the code editor'
> Fixed 'Bug 55042 - String constant with null character does not show

- main/src/core/MonoDevelop.Ide/ExtensionModel/Policies.addin.xml
> Fixed 'Bug 54990 - Default C# Code Formatting options seem

- main/tests/TestRunner/Runner.cs
This allows GuiUnitNg to also work without relying on a more brittle manual type search
> [Tests] Alter test runner lookup for GuiUnit entry point

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.QuickTasks/QuickTaskOverviewMode.cs
Same stats on typing `#if` in the editor:
> Editor perf

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.QuickTasks/QuickTaskOverviewMode.cs
Copy of https://github.com/mono/monodevelop/pull/2179
> Editor perf2

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Templates/PortableLibrary.xpt.xml
- main/src/addins/CSharpBinding/templates/PortableLibrary.xpt.xml
It is deprecated as of December 2016.
> [Templates] Remove mention of Silverlight

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/CommonAboutDialog.cs
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=54080
> [Ide] Make the 'about' dialog modal.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/CommonAboutDialog.cs
This reverts commit 05ea8c1e211e0967f27d1ede8454da49d1b58d63.
mhutch says this is not a bug, so reverting.
> Revert "[Ide] Make the 'about' dialog modal."

- main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/ConfigFileUtilities.cs
This will be used in a subsequent commit to modify the msbuild.exe.config file.
> Add a config file helper.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.DockNotebook/DockNotebook.cs
Bug 54670 - focus improperly set to toolbar on changing documents
> [Ide] Set the focus to the last item in the container

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreRuntime.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdk.cs
Fixed bug #55191 - Log message when .NET Core is not installed
https://bugzilla.xamarin.com/show_bug.cgi?id=55191
> [DotNetCore] Log message when .NET Core is not installed

- main/src/core/MonoDevelop.Core/frameworks/framework_NET_1_1.xml
- main/src/core/MonoDevelop.Core/frameworks/framework_NET_2_0.xml
- main/src/core/MonoDevelop.Core/frameworks/framework_NET_3_0.xml
- main/src/core/MonoDevelop.Core/frameworks/framework_NET_3_5.xml
- main/src/core/MonoDevelop.Core/frameworks/framework_NET_3_5_client.xml
- main/src/core/MonoDevelop.Core/frameworks/framework_NET_4_0.xml
- main/src/core/MonoDevelop.Core/frameworks/framework_NET_4_0_client.xml
- main/src/core/MonoDevelop.Core/frameworks/framework_NET_4_5.xml
Fixes bug #55331 - Incorrect target framework names
> Fix the name of the .NET frameworks

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/ContextMenuItem.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/MDMenu.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/MDMenuItem.cs
Bug 53081 - Chinese translations include the mnemonics key
> [Ide] Properly handle mnemonics in chinese/korean languages

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AtkCocoaHelper/AtkCocoaHelper.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/StringTagSelectorButton.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.OptionPanels/CustomCommandWidget.cs
> [A11y] Improve the accessibility of the Custom Command Widget

- main/src/addins/CSharpBinding/CSharpBinding.addin.xml
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeFixMenuService.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.addin.xml
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.csproj
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/QuickFixMenuHandler.cs
We had that with nrefactory and it got removed because of speed
reasons. However now roslyn & refactoring essentials is much faster
and we support async command updates.
Time to bring back that feature.
> [Refactoring] Implemented quick fix menu

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpBinding.addin.xml
https://bugzilla.xamarin.com/show_bug.cgi?id=55309
> Fixes #55309

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs
excluding conditional ItemGroup'
This patch prevents the document in beeing in state Project != null &&
AnalysisDocument == null.
> Fixed 'Bug 55329 - [regression] IntelliSense not working with

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeIssues/DiagnosticResult.cs
> Fixed 'Bug 55100 - Source Analysis C# rules makes the tooltip

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs
This reverts commit 5c4c02e4bbd471fd84d1d4626ebcbe136e7364ef.
Accidental commit included.
> Revert "Revert "[Ide] fixed potential ad hoc project reloading issue.""

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
Fixed some potential exceptions found during trying out various
workarounds.
> Fixed 'Bug 55455 - Code completion lost when moving files'

- main/external/fsharpbinding/paket.lock
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=55512
Re: https://github.com/dungpa/fantomas/pull/208
> [F#] Fix format document by bumping Fantomas

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Navigation/TextFileNavigationPoint.cs
> Fixed 'Bug 55460 - Show Next / Previews commands don't open files in

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeIssues/AnalyzersFromAssembly.cs
Fix hiding the nonfunctional refactoring commands.
> [Refactoring] Hide nonfunctional refactorings

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/EditorFactory.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs
- main/src/core/Mono.TextEditor.Platform/TagBasedSyntaxHighlighting.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/TextDocument.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextEditorDisplayBinding.cs
Various changes to support VS/Venus-type projection in MD.
> Projection buffer support

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/ListWidget.cs
Should fix https://bugzilla.xamarin.com/show_bug.cgi?id=55634
> Make sure the comparer used to compare completion items is stable.

- main/src/core/MonoDevelop.Ide/ExtensionModel/GlobalOptionsDialog.addin.xml
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/IdeTheme.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.OptionPanels/D152AccessibilityPanel.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
Can be set through the UI or through defaults
defaults write MonoDevelop com.monodevelop.AccessibilityEnabled true
> [A11y] Add option to disable accessibility

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpFormattingProfileDialog.cs
> Fixed 'Bug 55707 - C# Formatting Edit window isn't sized to show

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
Was caused by a projection parsing error race. The lock should be
enough to fix it but now we've immutable data structures which add
more thread safety.
> Fixed 'Bug 55705 - Quick Fix doesn't do anything'

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpBinding.addin.xml
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=55873
> [F#] Only show Debug F# script menu for F# files.

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpProject.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/LanguageService.fs
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=55899
> D15 2 fix55899

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.DockNotebook/DockWindow.cs
The old implementation only called Close() on the first document of the
floating window. It needs to be called on all documents.
> Fix 55958 - Crash when closing a floating document window

- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Execution/ProcessService.cs
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=43304
> [Core] Catch ArgumentException in ProcessMonitor and log appropriately

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/SearchResultWidget.cs
The first commit fixed the issue, the second commit was just a safety related change :)
> Fix nullref searching

- main/external/fsharpbinding/MonoDevelop.FSharpi.Service/MonoDevelop.FSharpInteractive.Service.fsproj
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=55241
> [F#] Fix F# interactive window on linux.

- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/BraceMatcher.fs
- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/MonoDevelop.FSharp.Tests.fsproj
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpBraceMatcher.fs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/TextDocument.cs
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=55916
> [F#] Fix brace matcher when matching on parens

- main/src/addins/MonoDevelop.Debugger.VSCodeDebugProtocol/MonoDevelop.Debugger.VsCodeDebugProtocol/VsCodeObjectSource.cs
> Bug 55869 - Can not inspect variables in .Net core applications

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/NewConfigurationDialog.cs
> [A11y] Make the New Configuration dialog accessible

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads/SolutionPad.cs
> [A11y] Set accessibility attributes on the solution tree

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/NewFileDialog.cs
> [A11y] Set the label attribute on the New Files dialog entry

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/FileProvider.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.FindInFiles/FindReplace.cs
The find in files operation could add BOMs.
> [Ide] Preserve encoding when doing find in files.

- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/AssemblyBrowserWidget.cs
Browser'
It was no hang it was just slow.
> Fixed 'Bug 55947 - VSfMac hangs when searching an API in Assembly

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
Was caused by a project modify event invalidating the project data
during apply changes. Tracking project modifications is not needed
since TryApplyChanges replaces the solution with an already updated
one. Roslyn solution changes should just be reflected back to the ide
model.
> Fixed 'Bug 56080 - Renaming file to match class name deleted file'

- main/external/fsharpbinding/MonoDevelop.FSharp.Shared/Extensions.fs
- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/TestTooltipProvider.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpSymbolHelper.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/Extensions.fs
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=56135
> Fixes function type tooltips

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs
> [A11y] Add labels and help for each of the margins

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/AboutMonoDevelopTabPage.cs
> [A11y] Set the label for the About image

- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/MonoDevelop.FSharp.Tests.fsproj
- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/TagComments.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpParsedDocument.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpSyntaxMode.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpTokens.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/Lexer.fs
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=55396
> [F#] Adds tagged comments to the Tasks pad.

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ExceptionCaughtDialog.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/GtkWidgetResult.cs
Used the wrench build to try this out. Needed for automating clicking on "Show Details" when an exception is thrown
e.g. http://xqa.blob.core.windows.net/gist/006-Clicked-Show-Details.png-ea1df8fb08e44c44a5365e836526c851.png
> [AutoTest] Add ability to click on Label by emitting signal "activate-link"

- main/src/addins/MacPlatform/MacPlatform.cs
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=56300
> [Mac] Split-fullscreen should not disable menuitems

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Project/CodeGenerationPanel.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Project/CompilerOptionsPanelWidget.cs
- main/src/addins/MonoDevelop.Packaging/MonoDevelop.Packaging.Gui/GtkNuGetPackageMetadataOptionsPanelWidget.cs
- main/src/addins/MonoDevelop.Packaging/MonoDevelop.Packaging.Gui/GtkProjectNuGetBuildOptionsPanelWidget.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Dialogs/CommitMessageStylePanelWidget.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AtkCocoaHelper/AtkCocoaHelper.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/BaseFileEntry.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/MimeTypePolicyOptionsPanel.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.OptionPanels/TextStylePolicyPanel.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads/ErrorListPad.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.OptionPanels/BaseDirectoryPanelWidget.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.OptionPanels/CommonAssemblySigningPreferences.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.OptionPanels/CustomCommandWidget.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.OptionPanels/GeneralProjectOptions.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.OptionPanels/NamespaceSynchronisationPanel.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.OptionPanels/OutputOptionsPanel.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.StandardHeader/StandardHeaderPolicyPanel.cs
Adds label and help to most of the project options panels in the main repo. Panels using Xwt can't be
made accessible yet. Partially fixes #53537
> [A11y] Make the project options panels accessible

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/DarkStyle.json
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/FallbackStyle.json
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/GruvboxStyle.json
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/LightStyle.json
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/MonokaiStyle.json
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/NightshadeStyle.json
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/OblivionStyle.json
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/SolarizedDarkStyle.json
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/SolarizedLightStyle.json
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/TangoStyle.json
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/VisualStudioStyle.json
> Documentation comments color tweaks

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Features/Completion/CompletionEngine.cs
> Fixed 'Bug 56541 - Attempting to use "_" as a tuple-discard value

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Rename/RenameRefactoring.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/TextDocument.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Text/TextChangeEventArgs.cs
buffer'
Broke during the text buffer port.
> Fixed 'Bug 56584 - Canceling a refactoring operation messes up the

- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Text/TextChangeEventArgs.cs
That's mostly for consistency.
> [Core] Made the constructors public.

- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/SystemAssemblyService.cs
Added new FrameworksChanged event that is raised when new frameworks
are registered in SystemAssemblyService.
> Notify framework changes in SystemAssemblyService

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs
IntelliSense'
Was just an reopen of the analysis document missing - the underlying
bug was already fixed as a side effect.
> Fixed 'Bug 56704 - Renaming a file breaks Refactoring and

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/CellRendererDiff.cs
> [VCS] Change arrow character so windows renders it properly

- main/Main.sln
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.Tests/MonoDevelop.Debugger.Tests.csproj
This will need to be merged after https://github.com/mono/debugger-libs/pull/127 is merged and buumped
> Bug 53371 - IDE side(rest is in debugger-libs)

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.OptionPanels/CustomCommandPanelWidget.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.OptionPanels/CustomCommandWidget.cs
> [A11y] Allow the Custom Command widget to be keyboard focusable

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AtkCocoaHelper/AtkCocoaHelper.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/StringTagSelectorButton.cs
> [A11y] Make the StringTagSelectorButton an AXPopUpButton

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Features/Completion/ContextHandler/RegexContextHandler.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Features/SemanticHighlighting/SemanticHighlightingVisitor.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Highlighting/CSharpSyntaxMode.cs
Broke during nrefactory -> roslyn port.
> Fixed 'Bug 56944 - Wring colour of get identifier'

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/EditCommands.cs
Many native Cocoa widgets can handle default
editing commands through selectors. If the active
NSView is not an instance of NSText, check whether
it responds to the matching selector (cut/copy/paste)
and enable the command.
(fix bug #51520)
> [51520][Ide][Mac] Add Selector handling to default Edit commands

- main/src/addins/MonoDevelop.Debugger.VSCodeDebugProtocol/MonoDevelop.Debugger.VsCodeDebugProtocol/MonoDevelop.Debugger.VsCodeDebugProtocol.csproj
- main/src/addins/MonoDevelop.Debugger.VSCodeDebugProtocol/MonoDevelop.Debugger.VsCodeDebugProtocol/VSCodeDebuggerSession.cs
- main/src/addins/MonoDevelop.Debugger.VSCodeDebugProtocol/MonoDevelop.Debugger.VsCodeDebugProtocol/VsCodeObjectSource.cs
- main/src/addins/MonoDevelop.Debugger.VSCodeDebugProtocol/MonoDevelop.Debugger.VsCodeDebugProtocol/packages.config
This needs to be merged at same time as https://github.com/xamarin/md-addins/pull/2053
> Bumping VSCode debug protocol to latest version and some fixes

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/ListWidget.cs
arrow keystroke when selecting options'
Not a real fix - but the behavior is correct. However the display of
the suggestion mode is not. That should make a bigger difference.
> Fixed 'Bug 56290 - Code completion/Intellisense throws away first

- main/src/addins/MacPlatform/MainToolbar/StatusBar.cs
#2549 for `d15-3` (fixes bug #56725)
> [56725][Mac] Update or Hide status popover on status changes

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebugApplicationDialog.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Execution/CustomExecutionModeWidget.cs
> [A11y] Set label/help descriptions on Debug application dialog

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/MimeTypePolicyOptionsSection.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/PolicyOptionsPanel.cs
> [A11y] Set a label on the warning image

- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/CompilerArguments.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/CompilerArguments.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/CompilerLocationUtils.fs
Cherry picked https://github.com/mono/monodevelop/pull/2560 for d15-3
> D15 3 fsharp fix unit tests

- main/src/addins/GnomePlatform/GnomePlatform.cs
problem'
Ported patch from Matthias Gliwka which fixed the gnome-terminal
problem. I added some minor fixes & verified that it works on a recent
ubuntu.
> Fixed 'Bug 16804 - External console run on Gnome 3.10 terminal

- main/src/core/MonoDevelop.Ide/ExtensionModel/Commands.addin.xml
- main/src/core/MonoDevelop.Ide/options/KeyBindingSchemeVisualStudio-mac.xml
- main/src/core/MonoDevelop.Ide/options/KeyBindingSchemeVisualStudio.xml
#2576 for `d15-3`
(fixes bug #55143)
> [Ide] Don't bind Page+Up Page+Down keys by default

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Fonts/FontChooserPanelWidget.cs
> [A11y] Set the help description on the font buttons

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/LanguageService.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/MDLanguageService.fs
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=57061
> [F#] Fixes project reference caching. Fixes #57061

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs
#2594 for `d15-3`
(fixes bug #43049)
> [TextEditor] Don't modify root window background

- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/TextEditorOptions.cs
> [TextEditor] Properly copy the TextEditorOptions color style

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.OptionPanels/SdkLocationPanel.cs
> [A11y] Add accessibility for the icon in the SDK location panel

- main/src/addins/MonoDevelop.AzureFunctions/Properties/Manifest.addin.xml
- main/src/addins/MonoDevelop.DotNetCore/Properties/MonoDevelop.DotNetCore.addin.xml
- main/src/core/MonoDevelop.Ide/ExtensionModel/Templates.addin.xml
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Codons/TemplateCategoryCodon.cs
Updates mono-addins to latest master for custom localizer attribute.
Fix project template categories not added to translations.
> [d15-3][Ide] New project dialog translations

- main/external/fsharpbinding/MonoDevelop.FSharp.Gui/FSharpCompilerOptionsWidget.cs
- main/external/fsharpbinding/MonoDevelop.FSharp.Gui/gtk-gui/MonoDevelop.FSharp.Gui.FSharpCompilerOptionsWidget.cs
- main/external/fsharpbinding/MonoDevelop.FSharp.Gui/gtk-gui/gui.stetic
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpOptionsPanels.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpProject.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/CompilerArguments.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/Parameters.fs
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=52663
> Fsharp compiler options widget

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/syntaxes/CSharp/C#.sublime-syntax
- main/src/core/MonoDevelop.TextEditor.Tests/Mono.TextEditor.Tests/SyntaxHighlightingTests.cs
interpolation for local variables'
> Fixed 'Bug 57033 - Syntax Highlighting is not present with C#6 string

- main/external/fsharpbinding/MonoDevelop.FSharp.Gui/FSharpCompilerOptionsWidget.cs
- main/external/fsharpbinding/MonoDevelop.FSharp.Gui/gtk-gui/MonoDevelop.FSharp.Gui.FSharpCompilerOptionsWidget.cs
- main/external/fsharpbinding/MonoDevelop.FSharp.Gui/gtk-gui/gui.stetic
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpOptionsPanels.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpProject.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/CompilerArguments.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/Parameters.fs
Mirror of https://github.com/mono/monodevelop/pull/2612 (F# compiler options) for d15-3
> D15 3 fix 52663

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/SearchEntry.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/AbstractNavigationExtension.cs
The GSource handling code is now faster and these races happen easier now.
> [Ide] Fix invalid source being removed spew

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Project/CSharpCompilerParameters.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Project/CompilerOptionsPanelWidget.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
> Fixed 'Bug 57017 - Toggling "unsafe" now requires a complete project

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.csproj
- main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
- main/src/core/MonoDevelop.Ide/packages.config
- main/src/core/MonoDevelop.Startup/app.config
This is the first stage of adding VSMEF. It adds NuGet packages but doesn't do anything else yet. 
This makes it easier to prototype and test things.
> Add VSMEF prerequisites

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Composition/CompositionManager.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
Adds an (unused for now) CompositionManager.
> Add a MEF CompositionManager.

- main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj
- main/src/core/MonoDevelop.Core/packages.config
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
We will need this for WebTooling.
> Add Nuget package for Microsoft.CodeAnalysis.EditorFeatures.Text.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs
> [Ide] Fix NRE if a Document has no Editor

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Xwt/XwtPopup.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Xwt/XwtThemedPopup.cs
This is the missing PR #2244 for `master`
> [54483] Fix XwtPopup Target screen bounds calculation

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/DarkStyle.json
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/FallbackStyle.json
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/GruvboxStyle.json
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/LightStyle.json
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/MonokaiStyle.json
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/NightshadeStyle.json
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/OblivionStyle.json
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/SolarizedDarkStyle.json
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/SolarizedLightStyle.json
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/TangoStyle.json
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/VisualStudioStyle.json
> Fixed 'Bug 57619 - Triple line comments text syntax highlighted with

- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/HighlightUsagesTests.fs
- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/TestHelpers.fs
- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/UnusedOpens.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/HighlightUnusedCode.fs
.. for extension method. Fixes #57660
> [F#] Fix incorrect graying out of namespace..

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/CommandSearchCategory.cs
> [Ide] Hide array or hidden commands in global search

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.OptionPanels/KeyBindingsPanel.cs
> [Ide] Use Markup for Key bindings prefs warnings

- main/src/core/MonoDevelop.Core/MonoDevelop.Core.AddIns/FalseCondition.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core.AddIns/TrueCondition.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/WorkspaceObject.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/ItemOptionsDialog.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/FileTemplate.cs
The AppliesTo condition was not registered in a specific case when
project extensions were loaded.
> Fix bug #57479 - Condition AppliesTo not found message logged

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/MicrosoftTemplateEngineProjectTemplatingProvider.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/ProjectTemplatingProvider.cs
- main/tests/Ide.Tests/ProjectTemplateTests.cs
Original PR is at https://github.com/mono/monodevelop/pull/2718
> [Master] Bug 57840 - Adding .NET Standard project to existing solution/directory structure rewrites/reformats *all* source code on disk

- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/TestTooltipProvider.fs
I wrote a test for this [bug](https://bugzilla.xamarin.com/show_bug.cgi?id=57937), but it's working on master. Just 15-3 has the issue. May as well commit the test now that it's wrote.
> Test for #57937

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/LanguageService.fs
https://bugzilla.xamarin.com/show_bug.cgi?id=58001
> Fixes #58001 Deadlock in "Find Derived Types"

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/DockBarItem.cs
Makes the user interface much more sensible :)
> [A11y] The DockBarItem should be a button, not a group

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring/RefactoringPreviewTooltipWindow.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/ContextMenuExtensionsMac.cs
type tooltip preview obscures the context menu'
Was a complex fix because os x doesn't let me get the submenu position
- so the solution was a work around: position the tooltip around the
context menu but not at the right side.
> Fixed 'Bug 57866 - [VSFeedback Ticket] #443161 - quick actions new

- version-checks
Update md-addins reference to include latest fixes
> D15-3 md-addins bump 73710b7

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.Wrappers/SemanticHighlightingSyntaxMode.cs
parameters'
The bug was in that cache layer - but caching on this level isn't
required at all it needs to be done in the semantic highlighting
itself. Which is the case for our c# semantic highlighting as well for
the roslyn one so I decided to remove that.
> Fixed 'Bug 58023 - Semantic colorization disappears on method

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebuggingService.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValueTreeView.cs
Same as https://github.com/mono/monodevelop/pull/2770 but for 15.4
> Bug 57169 - Watch window does not update tuple information on change

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValueTreeView.cs
Two issues are fixed:
1) Bug in method `GetCellAtPos` which was using `cr.Visible`, which was wrong if row where pointer was had different value as last rendered row(which set `cr.Visible`)... Now for cells that have `AddAttribute("visible")` check store for actual value for that row so correct cell is picked up
2) Bug in method `OnButtonPressEvent` was that `base.OnButtonPressEvent` was called even when click was already processed, example is clicking on edit button(in case of string) it opened editor window, but after that window was closed, inline editing was started because `base.OnButtonPressEvent` was still called
> Fixed rare weird issues with mouse click on debug object tree view

- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/ProjectCracking.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/CompilerArguments.fs
Removed passing all package references to the compiler options.
> [F#] Fix unit tests

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/EditActions.cs
- main/src/core/MonoDevelop.TextEditor.Tests/Mono.TextEditor.Tests.DefaultEditActions/DeleteActionTests.cs
- main/src/core/MonoDevelop.TextEditor.Tests/Mono.TextEditor.Tests.DefaultEditActions/TextEditorTestBase.cs
> Fixed 'Bug 58123 - Writing " makes two of characters, but delete only

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Refactoring/RenameHandler.cs
> Fixed 'Bug 44384 - Rename refactoring on constructor should rename

- version-checks
To pull in the changes from https://github.com/xamarin/md-addins/pull/2241
> Bump md-addins for IdentityService  1.1.9

- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/TemplateTests.fs
The tests that create Android projects and compile them were failing
with 'The OutputPath property is not set for project'. This was
because the projects were saved after NuGet packages were installed.
The new Android projects use the Xamarin.Build.Download NuGet package
which adds a .props Import at the start of the project file. Saving
the Android project after this NuGet package was added would result
in the Xamarin.Android.FSharp.targets Import being added at the top
of the project file, since similar elements are grouped together.
The Xamarin.Android.FSharp.targets Import needs to be at the end of
the project file. Saving the project before adding the NuGet
packages fixes this problem.
When the Android project template changes are merged to d15-4 we will need this fix on the d15-4 …
> [F#] Fix Android project template compile tests

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads/ErrorListPad.cs
Fixed bug #11946 - Need a way to export build errors and warnings
https://bugzilla.xamarin.com/show_bug.cgi?id=11946
Allow multiple rows to be selected in the Errors pad. The Copy menu
will be enabled if multiple rows are selected. The Go to and Show
Error Reference menus will be disabled if multiple rows are selected.
The Copy menu will copy all selected rows to the clipboard.
> [Ide] Support selecting multiple rows in Errors pad

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/EventBoxTooltip.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ImageService.cs
Implemented focus for EventBoxTooltip
> Fixes BXC #53775

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CSharpCompletionTextEditorExtension.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/CompletionTextEditorExtension.cs
- main/tests/UnitTests/MonoDevelop.CSharpBinding/CSharpCompletionTextEditorTests.cs
- main/tests/UnitTests/UnitTests.csproj
doesn't work if "Show completion list after a character is typed" is
unchecked'
Command broke during API changes for the webtools team. I added a test
for that option.
> Fixed 'Bug 58473 - [VSFeedback Ticket] #460850 - Complete Word hotkey

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AtkCocoaHelper/AtkCocoaHelperMac.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AtkCocoaHelper/AtkCocoaHelperNoOp.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/INewProjectController.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/NewProjectController.cs
If the solution is correct, then I implement it on all such backends.
> BXC #53783

- main/src/addins/MonoDevelop.AzureFunctions/Properties/AddinInfo.cs
Updating per a discussion with @mhutch . Thanks!
> Update metadata for an upcoming update

- main/src/core/MonoDevelop.Ide/ExtensionModel/GlobalOptionsDialog.addin.xml
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/IdeTheme.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.OptionPanels/D152AccessibilityPanel.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
Can be set through the UI or through defaults
defaults write MonoDevelop com.monodevelop.AccessibilityEnabled true
> [A11y] Add option to disable accessibility [d15-4]

- version.config
Merge this after the last preview ships.
> 15.4 - Remove preview branding

- version.config
> Revert "15.4 - Remove preview branding"

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Tabstrip.cs
> [Ide] Fix document subview tab wrapping

- main/src/addins/AspNet/MonoDevelop.AspNet.csproj
Looks like I missed adding the xft.xml files to the project
@mhutch
> Add missing xft.xml files

- main/src/core/MonoDevelop.TextEditor.Tests/Mono.TextEditor.Tests.DefaultEditActions/DeleteActionTests.cs
One option needs to be set to run these tests.
> [TextEditor] Fixed unit tests.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/VSCodeImport/xml/syntaxes/xml.json
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/VSCodeImport/xml/syntaxes/xsl.json
Syntax grammar was fixed upstream.
> Fixed 'Bug 57014 - XAML color coding not always correct'

- version.config
This bump is required if we are going to do a SR.
> Bump MD version

- main/external/fsharpbinding/.paket/paket.targets
- main/external/fsharpbinding/MonoDevelop.FSharp.Gui/FSharpSettingsWidget.cs
- main/external/fsharpbinding/MonoDevelop.FSharp.Gui/gtk-gui/MonoDevelop.FSharp.Gui.FSharpSettingsWidget.cs
- main/external/fsharpbinding/MonoDevelop.FSharp.Shared/MonoDevelop.FSharp.Shared.fsproj
- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/MonoDevelop.FSharp.Tests.fsproj
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpBinding.addin.xml
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpInteractivePad.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpOptionsPanels.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpParsedDocument.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpParser.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/MonoDevelop.FSharp.fsproj
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/Extensions.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/LanguageService.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/TypeSignatureHelp.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/paket.references
- main/external/fsharpbinding/MonoDevelop.FSharpi.Service/MonoDevelop.FSharpInteractive.Service.fsproj
- main/external/fsharpbinding/paket.dependencies
- main/external/fsharpbinding/paket.lock
> FSharp type signatures

- main/src/addins/MacPlatform/MainToolbar/Styles.cs
- main/src/addins/MonoDevelop.ConnectedServices/Gui.ServicesTab/DependenciesSectionWidget.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/ToolboxWidget.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Gui/Styles.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/Styles.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/LogView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Styles.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkTemplateCellRenderer.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.WelcomePage/Style.cs
Colors refactoring: `DimTextColor` is now `SecondaryTextColor`.
> Colors refactoring: DimTextColor is now SecondaryTextColor

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/TypeSignatureHelp.fs
Only calculate if they haven't yet appeared or edits are taking place.
> Don't recalculate signature help markers when scrolling.

- main/src/addins/Xml/Completion/XmlCompletionData.cs
- main/src/addins/Xml/Editor/XmlEditorOptions.cs
Also needs https://github.com/xamarin/md-addins/pull/2379 to be merged
> Fixing Xaml bug on 15.4 branch

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/DockBarItem.cs
> [59123] Don't autohide pad while its dock item is hovered

- version-checks
> Updated reference to xamarin/md-addins

- main/src/addins/CSharpBinding/CSharpBinding.addin.xml
- main/src/addins/CSharpBinding/CSharpBinding.csproj
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/policies/MonoDevelopCSharpPolicy.xml
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/policies/MonoTextStylePolicy.xml
- main/src/core/MonoDevelop.Core/MonoDevelop.Core.addin.xml
follow the Mono coding guidelines and create a new separate
MonoDevelop policy'
> Fixed 'Bug 58218 - [C# Code Formatting Policy] Make the Mono policy

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/AboutMonoDevelopTabPage.cs
> Use an Xwt.LinkLabel for the about box link labels

- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/TypeSignatureHelp.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/TypeSignatureHelp.fs
> Fix for BCL override type signatures

- version-checks
fixes build failure from previous md-addins bump
> Updated reference to xamarin/md-addins@8dc8abf

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/MSBuildGlobTests.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/MSBuildTests.cs
- main/tests/test-projects/msbuild-glob-tests/glob-remove-saved2.csproj
- main/tests/test-projects/msbuild-glob-tests/glob-remove-saved3.csproj
- main/tests/test-projects/msbuild-glob-tests/glob-remove-test2.csproj
- Fixed bug [#59349](https://bugzilla.xamarin.com/show_bug.cgi?id=59349) - Remove item not added when file excluded from project
- Fix Remove item not added when Update item exists 
- Fix Update items not removed from project
> [Core] Fix remove item not added when file excluded

- version-checks
fixes 59416, more details in https://github.com/xamarin/md-addins/pull/2438
> Updated reference to xamarin/md-addins@5ca893b

- version-checks
> Updated reference to xamarin/md-addins@c2287f7

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/DropDownBoxListWindow.cs
Layout must be configured during initialization for initial window sizing.
(fixes bug #58836)
> [58836][Ide] Fix breadcrumb dropdown sizing

- version-checks
brings the latest Xcode9 changes for the iOS designer
> Updated reference to xamarin/md-addins@14b7f86

- version-checks
fix to auto-provision Itchy and Felix bots with xcode9 GM
fix 58389
[iOS] Fix CustomClass text box on windows  
[iOS] Properly override InternalSetValue for EnumPropertyEntry
> Updated reference to xamarin/md-addins@140b5e3

- main/src/addins/CSharpBinding/MonoDevelop.JSon/JSonIndentEngine.cs
- main/tests/Ide.Tests/MonoDevelop.SourceEditor/JSonIndentEngineTests.cs
indent options.
The indent engine now takes the text editor options into account.
> [CSharpBinding] JSon indent engine is not longer connected to c#

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Project/CSharpProjectExtension.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp/AstStockIcons.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp/DeclaredSymbolInfo.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp/ProjectSearchCategory.cs
Currently targeting `roslyn-persistent-storage-services`. Will switch to master when the former is merged.
https://www.screencast.com/t/t1wVpFEwr
> Roslyn search category

- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/ToolboxWidget.cs
Couldn't reproduce the bug but that should prevent the native crash.
> Fixed 'Bug 59471 - Partial emoji copy/paste crashes fatally'

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/CompletionTextEditorExtension.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
Cherry picked 2 commits from https://github.com/mono/monodevelop/pull/3059 since https://github.com/mono/monodevelop/pull/3059 probably won't make it to 15.5...
> Bug 59704 fix

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/OSXEditor.cs
undistinguishable and harder to read'
> Fixed 'Bug 59742 - Text rendering has changed, making some things

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Tooltips/LanguageItemTooltipProvider.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs
- main/src/core/MonoDevelop.Ide/ExtensionModel/Commands.addin.xml
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/TextEditorCommands.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/DefaultCommandTextEditorExtension.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/EditActions.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/InternalExtensionAPI/IEditorActionHost.cs
> Fixed 'Bug 59104 - Need a keyboard shortcut to trigger QuickInfo

- version-checks
Updated reference to xamarin/md-addins@83cf86d
fixes build
> Updated reference to xamarin/md-addins@83cf86d

- main/po/ja.po
- main/po/zh_CN.po
- main/po/zh_TW.po
It seems to be related to using markup. Remove these for now.
https://bugzilla.xamarin.com/show_bug.cgi?id=58759
> Remove some translations that are triggering a crash

- version-checks
Includes 
https://github.com/xamarin/md-addins/pull/2531#pullrequestreview-66504920
fixes:
https://bugzilla.xamarin.com/show_bug.cgi?id=59895
Forms 2.4.0 bump for F# templates
> Updated reference to xamarin/md-addins@a8da992

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.QuickTasks/QuickTaskOverviewMode.cs
Check the caches exist before trying to access them
Fixes #59894
> [QuickTasks] Check that the caches exist

- version-checks
Updated reference to xamarin/md-addins@c177c62
> Updated reference to xamarin/md-addins@c177c62

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/NSObjectResult.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AppResult.cs
Already approved and merged for master https://github.com/mono/monodevelop/pull/3143
> [AutoTest] Add Support for NSTableView 

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextEditor.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
> Fixed 'Bug 59975 - [VSfM] [d15_5 Bump live player] VSfM is crashing on

- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/TemplateTests.fs
To be merged after https://github.com/xamarin/md-addins/pull/2562. Fixes #59071
> Add test for F# Shared XAML Forms project

- main/Directory.build.props
- main/msbuild/ReferencesVSEditor.props
- main/src/addins/CSharpBinding/CSharpBinding.csproj
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.csproj
- main/src/addins/MonoDevelop.SourceEditor2/packages.config
- main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
- main/src/core/MonoDevelop.Ide/packages.config
- main/src/core/MonoDevelop.TextEditor.Tests/MonoDevelop.TextEditor.Tests.csproj
Import that file in projects that want VS Editor references.
> Consolidate VS Editor NuGet references in a single file.

- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/TextEditorData.cs
- main/src/core/MonoDevelop.TextEditor.Tests/Mono.TextEditor.Tests/SelectionTests.cs
> Fixed 'Bug 60093 - Current line highlight should be disabled while

- version-checks
Updated reference to xamarin/md-addins@6750dd2
https://github.com/xamarin/md-addins/compare/b9f3479f3cc13e209d6144247b3d7eecf9394717...d15-4
> Updated reference to xamarin/md-addins@6750dd2

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AppResult.cs
For 15.5 https://github.com/mono/monodevelop/pull/3192
> [AutoTest] Fix SetProperty when there is no "."

- main/src/core/MonoDevelop.Core/packages.config
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
- main/src/core/MonoDevelop.Ide/packages.config
This is in preparation for updating the editor.
> Add Microsoft.VisualStudio.Threading.

- version-checks
Updated reference to xamarin/md-addins@1c2ba73 
https://github.com/xamarin/md-addins/compare/a2188749ed10ccb5251afd607bca58ecb6a9983b...d15-5
Builds: https://code.internalx.com/Wrench/BuildDetails?buildId=3d79f0ac8eeb30bd5f52c6ff1caafca
https://wrench.internalx.com/Wrench/ViewLane.aspx?lane_id=5590&host_id=430&revision_id=916529
> Updated reference to xamarin/md-addins@1c2ba73

- version-checks
Updated reference to xamarin/md-addins@bb7fb55
https://github.com/xamarin/md-addins/compare/1525230165b6ba2f7f5bf7c046fa4475505f4cc9...d15-4
> Updated reference to xamarin/md-addins@bb7fb55

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/Formats/Sublime3Format.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/SyntaxHighlighting.cs
- main/tests/UnitTests/MonoDevelop.Ide.Editor/SyntaxHighlightingTest.cs
port of https://github.com/mono/monodevelop/pull/3187
> Fixed 'Bug 60055 - UI hang on opening TypeScript file'

- main/src/core/MonoDevelop.Ide/ExtensionModel/Templates.addin.xml
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/OrFileTemplateCondition.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/ProjectCapabilityFileTemplateCondition.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
I will also open PR for Xamarin.Forms addin which will make use of this new condition
> [Ide] Added Or and ProjectCapability file template conditions

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/CompletionData.cs
The sort was creating the icons and querying descriptions from roslyn for each item. This is not ok.
> 15.5 [Ide] Made code completion work fast again.

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpFormattingProfileDialog.cs
before/after comma' formatting preview isn't working'
> Fixed 'Bug 60130 - [VSFeedback Ticket] #505611 - C# 'Insert space

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/StackTracePad.cs
Problem was that we called `GetFrame` and `frame.FullStackframeText` from UI Thread, which in case if runtime crashes can hang UI so solution is same as we did for ThreadPad in 82436802a, fetch this data in threadpool and use data in UI Thread to set to UI elements
> Bug 60201 - Debugger not releasing - requires simulator restart

- main/src/addins/MacPlatform/MainToolbar/AwesomeBar.cs
- main/src/addins/MacPlatform/MainToolbar/RunButton.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/IdeTheme.cs
This Patch fixes various dark-theme issues on High Sierra.
> [60098][Ide][Mac] Fix dark theme issues on High Sierra

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Chart/Axis.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/ButtonBar.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs
Starting off my morning with some minor bug fixing, going through Coverity looking for low-hanging fruit.
Links to the Coverity issue are on each commit.
> Fix some minor null dereferences and resource leaks

- extras/MonoDevelop.Database/po/ar.po
- extras/MonoDevelop.Database/po/po.mdproj
i donot know if it support it but i will add it any way.
> Create ar.po (Arabic lang)

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
I also added extra `if (token.IsCancellationRequested) return;` so we don't schedule stuff on UI thread for no reason...
I did some testing and everything looks good `if(task.Complete==false)`(rerendering happens fine) I checked also code...
Typing feels more fluid...
> Removed .Wait(100) in GetCachedChunks which was causing small UI hangs while typing

- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/Interactive.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpInteractivePad.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpPathExtension.fs
Fix was added by @mkrueger to SegmentTree [here](https://github.com/mono/monodevelop/pull/3331/commits/0213869a5a6add2a1f561fa127eb8dbd636e8a48) but I already had this test ready to go.
> F# Make interactive pad testable and add test for prompt markers

- main/src/addins/MonoDevelop.SourceEditor2/VSEditor/ITagBasedSyntaxHighlightingFactory.cs
- main/src/addins/MonoDevelop.SourceEditor2/VSEditor/TagBasedSyntaxHighlighting.cs
We need ITextView so we can save MD ITextDocument to pass changed lines to HighlightingStateChanged event.
> Change ITagBasedSyntaxHighlightingFactory to accept an ITextView

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/SyntaxHighlightingService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/VSCodeImport/xml/syntaxes/xaml.json
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
I took xml.json copied it to xaml.json and added support for markupExtensions highlighting
> Fix #504170 No syntax highlighting for bindings

- main/src/addins/Xml/Editor/BaseXmlEditorExtension.cs
- main/src/addins/Xml/Formatting/XmlFormatterWriter.cs
- main/src/addins/Xml/Formatting/XmlFormattingPolicy.cs
- main/src/addins/Xml/Tests/Formatting/XmlFormatterTests.cs
When reviewing this I suggest looking at changes per commit since commits explain change and it's smaller chunk to digest
> Xml indent and formatting fixes

- main/src/core/MonoDevelop.Core/MonoDevelop.Core.ProgressMonitoring/AggregatedProgressMonitor.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core/ProgressMonitor.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Core.Tests.csproj
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Core/ProgressMonitorTests.cs
This method adds support for using arbitrary objects for reporting status.
> Implemented ProgressMonitor.ReportObject()

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateTests.cs
Try to reduce the chance of the NuGet restore failing by:
1) Using a custom NuGet.Config file that only uses the main
NuGet package source. This improves the restore speed and also
prevents other slower MyGet package sources from being used.
2) Use RestoreDisableParallel when running msbuild restore. This
should avoid any problems that happen in Mono when running restores
in parallel for many NuGet packages.
> [DotNetCore] Improve project template tests

- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/MonoDevelop.FSharp.Tests.fsproj
- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/UnusedOpens.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/HighlightUnusedCode.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/MonoDevelop.FSharp.fsproj
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/LanguageService.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/MDLanguageService.fs
- main/external/fsharpbinding/paket.dependencies
- main/external/fsharpbinding/paket.lock
- main/src/core/MonoDevelop.Startup/app.config
Fix unused opens analyzer bugs by switching over to new compiler API.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/520293
> Fix 520293

- main/msbuild/ReferencesVSEditor.props
- main/src/core/MonoDevelop.Core/packages.config
This gets rid of an assert that degrades dogfooding experience.
> Switch the VS Editor implementation to Release

- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/SyntaxHighlighting.fs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/syntaxes/FSharp/F#.sublime-syntax
> [F#] Syntax fix for module names containing namespaces

- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/SemanticHighlighting.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpSyntaxMode.fs
> [F#] Fix semantic highlighting for wildcard identifiers

- main/build/MacOSX/monostub.mm
- main/po/ja.po
- main/po/ko.po
- main/po/ru.po
- main/po/tr.po
- main/po/uk.po
- main/po/zh_CN.po
- main/po/zh_TW.po
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/GLibLogging.cs
Bug 60378 - [VSFeedback Ticket] #513042 - Global search function, enter a letter collapse
> [Ide] Fix different locales causing crashes in the IDE

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/ParameterInformationWindow.cs
> Fixed 'Bug 60178 - Completion window is being displayed on a different

- main/src/core/MonoDevelop.Core/MonoDevelop.Core/PropertyBag.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/SolutionFolder.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/WorkspaceObject.cs
Or use a builder to append blocks.
> [Core] Ditch immutable collections where not needed.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
Shaves 4 seconds off loading a solution for the first time.
Old:
```
77.55%   <ReadFile>b__0  •  4,024 ms  •  1 call  •  MonoDevelop.Projects.MSBuild.SlnFileFormat+<>c__DisplayClass18_0.<ReadFile>b__0
77.55%   ReadSolution  •  4,023 ms  •  1 call  •  MonoDevelop.Projects.Solution.ReadSolution(ProgressMonitor)
61.78%   Dispose  •  3,205 ms  •  1 call  •  MonoDevelop.Projects.SolutionLoadContext.Dispose
61.78%   <LoadItem>b__1  •  3,205 ms  •  1 call  •  MonoDevelop.Projects.MSBuild.MSBuildProjectService+<>c__DisplayClass58_0.<LoadItem>b__1(Object, EventArgs)
61.78%   EndLoad  •  3,205 ms  •  1 call  •  MonoDevelop.Projects.SolutionItem.EndLoad
61.75%   OnEndLoad  •  3,204 ms  •  1 call  •  MonoDevelop.Projects.DotNetProject.OnEndLoad
61.72%   Get  •  3,202 ms  •  1 call  • …
```
> [Ide] Kick off composition manager load after mono-addins loads

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.WelcomePage/WelcomePageService.cs
This allows extensions to show/hide the welcome page and to handle welcome page service events.
> [Ide] Public WelcomePageService 

- main/po/Makefile.am
- main/src/addins/MonoDevelop.Gettext/MonoDevelop.Gettext.NodeBuilders/TranslationNodeBuilder.cs
- main/src/addins/MonoDevelop.Gettext/MonoDevelop.Gettext.NodeBuilders/TranslationProjectNodeBuilder.cs
- main/src/addins/MonoDevelop.Gettext/MonoDevelop.Gettext/GettextTool.cs
- main/src/addins/MonoDevelop.Gettext/MonoDevelop.Gettext/TranslationProject.cs
This will not sort the messages.po. But that shouldn't be an issue, as we don't import that, it's only modified when generating it via this tool.
> [Gettext] Add option to output sorted translation files.

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Highlighting/HighlightUsagesExtension.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
Fixed leaks surrounding editing files with projections and ~a leak of a TextBufferUndoManager for each document that was opened.~ (filed [upstream](https://github.com/Microsoft/vs-editor-api/issues/8))
> Fix leaks2

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpProject.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/LanguageService.fs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/526683
> [F#] Hide class gathering icon when solution is closed before loaded.

- version.config
> Update version for SR2

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Ide.cs
> [Ide] Defer templating service until actually queried.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/CompletionController.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/CompletionListWindow.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/CompletionWindowManager.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Gui/CompletionListWindowTests.cs
> Fix NRE in completion window

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/MonoDevelop.FSharp.fsproj
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=61116
> Fix linux case sensitivity build issue. Fixes #61116

- .gitmodules
Only my last commit impacts code we use, the rest is in the C# <-> VB converter webapp
> [RefactoringEssentials] Switch to mono so we maintain commit flux

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/SignatureHelpParameterHintingData.cs
Without a use case it's hard to fix - seems to be an issue inside
roslyn. However there shouldn't be an IDE crash in case of a failure
in getting documentation.
> Fixed '530350-Error in signature help'

- main/src/addins/MonoDevelop.DocFood/DocFood.config.xml
Was only an error in the log file caused by the nested if not
statement. There was only 1 case in the whole file so I just
restructured the xml.
> Fixed '530536 - Error in DocFood'

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeIssues/AnalyzersFromAssembly.cs
> Fixed '530353 - Generate Overrides fix fails'

- main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj
- main/src/core/MonoDevelop.Core/MonoDevelop.Core/Runtime.cs
Port https://github.com/mono/monodevelop/pull/3560 to d15-6.
> Don't deploy Microsoft.Build.Tasks.Core.dll

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeIssues/AnalyzersFromAssembly.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeIssues/CodeDiagnosticDescriptor.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeIssues/CodeDiagnosticRunner.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeIssues/CodeIssuePanelWidget.cs
> [d15-6][Refactoring] Fix code issues panel and custom reporting

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/ProjectFileCollection.cs
Benchmark with results:
https://gist.github.com/Therzok/0d48f50112606cd90396e70d4d6f4547
```
Set item 370
Set items 216
```
> [Core] Only mutate immutable dictionary once per added range

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeIssues/AnalyzersFromAssembly.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeIssues/CodeDiagnosticDescriptor.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeIssues/CodeDiagnosticRunner.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeIssues/CodeIssuePanelWidget.cs
> [Refactoring] Fix code issues panel and custom reporting

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/ITextSegmentMarker.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/InternalExtensionAPI/ITextMarkerFactory.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextMarkerFactory.cs
> [SourceEditor] Added a way to create a simple colorized underline text

- main/src/core/MonoDevelop.Core/MonoDevelop.Core.Assemblies/MonoTargetRuntimeFactory.cs
Handle /app, from sandboxed apps
> [linux] Add /app to .pc prefixes

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeIssues/AnalyzersFromAssembly.cs
error)'
Deactivated until UI is implemented.
> Fixed 'Bug 61137 (`) - Cannot add Reference ( Microsoft.CodeAnalysis

- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/SyntaxHighlighting.fs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/syntaxes/FSharp/F#.sublime-syntax
Fixes #https://devdiv.visualstudio.com/DevDiv/_workitems/edit/534803
> Syntax highlighting fixes

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/FileRegistry.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorWidget.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/DocumentContext.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Document.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DocumentRegistry.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
It's a proposed fix for 524635 [Feedback] XAML files are not refreshed
after switching git branch.
> [Ide] Moved FileRegistry into the core ide.

- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/PlatformService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/OptionsDialog.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/NewFileDialog.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/DesktopService.cs
Disable row expansion in preferences and new file dialogs when using VoiceOver
> Fix 53727 proper

- main/src/addins/MacPlatform/MacExternalConsoleProcess.cs
If the command is null, we don't need to run an extra bash process
Fixes VSTS #554029
> [15.6] [Tools] Terminal cannot be used with Tools - Open in Terminal window

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/ErrorHandlerTextEditorExtension.cs
> Only call GetErrorsAsync once instead of multiple times

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CSharpCompletionTextEditorExtension.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.OptionPanels/CompletionAppearancePanel.cs
- main/src/addins/MonoDevelop.SourceEditor2/gtk-gui/MonoDevelop.SourceEditor.OptionPanels.CompletionAppearancePanel.cs
- main/src/addins/MonoDevelop.SourceEditor2/gtk-gui/gui.stetic
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdePreferences.cs
completion list'
https://devdiv.visualstudio.com/DevDiv/_workitems?id=555346
It's just a tweak in UI and the usage of the hide advanced members
option in the completion backend.
> Fixed 'VSTS 555346 - System.Xml.XmlTextWriter doesn't appear in

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/RemoteBuildEngineManager.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/SdkResolution.cs
> Get rid of some exceptions that occur during project open

- main/external/fsharpbinding/README.md
These instructions were out of data.  Cleaning this up as a way of making a trial PR to this repo
cc @nosami
> Update the F# binding README.md deleting old stuff

- main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildProjectInstance.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildPropertyEvaluated.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/MSBuildPropertyGroupEvaluated.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects/Project.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/ConfigurationMergingTests.cs
- main/tests/test-projects/test-configuration-merging/TestConfigurationMerging11.csproj
- main/tests/test-projects/test-configuration-merging/TestConfigurationMerging11.csproj.saved
- main/tests/test-projects/test-configuration-merging/TestConfigurationMerging11.csproj.saved2
- main/tests/test-projects/test-configuration-merging/TestConfigurationMerging11.props
> Fix serialization issue with ItemProperty and MergeToProject

- main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
Fixes the packaging step on Wrench.
> Structured build output - fix wrench

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputViewContent.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputWidget.cs
- Adds default tab naming
- Additional checks when saving .binlog file
> [Ide] Sets default naming and adds extension checks when saving

- version-checks
Updated reference to xamarin/md-addins@7c8f967
> Updated reference to xamarin/md-addins@7c8f967

- main/src/addins/MacPlatform/MainToolbar/SelectorView.cs
> [Toolbar][Mac] Fix various configuration selector issues

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.WelcomePage/WelcomePageSection.cs
> [15.6] Welcome screen improvements

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/FoldMarkerMargin.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/IconMargin.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/TextMarker/DebugTextMarker.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/BookmarkMarker.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/MarginMarker.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AtkCocoaHelper/AtkCocoaHelper.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AtkCocoaHelper/AtkCocoaHelperMac.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AtkCocoaHelper/AtkCocoaHelperNoOp.cs
Make the breakpoint and bookmark markers accessible.
Fix some warnings as well as we go.
> Accessible margins

- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/Interactive.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpInteractivePad.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/InteractiveSession.fs
> Set correct __SOURCE_DIRECTORY__ in FSI

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/DockBarItem.cs
> [15.5][560430] Don't autohide pad while its dock item is hovered

- main/src/addins/CSharpBinding/CSharpBinding.addin.xml
- main/src/addins/CSharpBinding/CSharpBinding.csproj
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.OptionsProvider/CSharpDocumentOptionsProvider.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.OptionsProvider/OptionProviderFactory.cs
- main/src/core/MonoDevelop.Ide/ExtensionModel/MonoDevelop.Ide.addin.xml
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
That'll fix code generation and formattting at various places:
intellisense, code actions and other roslyn features
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/525189.
> [CSharpBinding] Backported C# document options provider.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdePreferences.cs
to unchecked by default'
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/563772
> Fixed 'VSTS Bug 563772: Change Show EditorBrowsable.Advanced members

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AppQuery.cs
It has been pretty annoying doing the test reviews.
> Remove spam in Ide.log from logging data about NSSegmentedControl

- version-checks
Updated references to mono/xwt, xamarin/md-addins
> Updated references to mono/xwt, xamarin/md-addins

- version-checks
Updated reference to xamarin/md-addins@dce0ded
> Updated reference to xamarin/md-addins@dce0ded

- Makefile
This fixes exclusion path necessity and AOT's everything
> [AOT] Improve targets for AOT

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeFixMenuService.cs
Fixes VSTS #527500
Until the actual CodeFixService implementation we gain via editorFeatures,
mock the FixAllState via FixMultipleState which gathers all the diagnostics
with the same ID in a document
> [Refactoring] Fix Fix All in document command

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/PathBar.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutput.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputWidget.cs
Implements Navigation bar (breadcrumb)
> Buildoutput breadcrumb

- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/IndentationTrackerTests.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpBinding.addin.xml
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpIndentationTracker.fs
Fixes vsts #563768 (https://github.com/mono/monodevelop/issues/3797)
> F# Fix auto-indent

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CSharpCompletionTextEditorExtension.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding/CSharpCompletionTextEditorTests.cs
list'
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/568065
> Fixed 'Bug 568065: Multiple identical entries for Tuple in completion

- main/src/addins/GnomePlatform/GnomePlatform.cs
So create a runner for mate-terminal then.
> mate-terminal not support --app-id parameter

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/LogView.cs
The TextWriter was using the version of WriteConsoleLogText that takes no monitor. Change it to use the method that takes a monitor, but improve handling for
null monitors.
Fixes VSTS #567563
> [IDE] Fix null reference when code uses Log.WriteLine

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutput.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputNode.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputProcessor.cs
- main/tests/Ide.Tests/MonoDevelop.Ide/BuildOutputTests.cs
Centralizes in BuildOutputNode set the parent with AddChild function + test
Included some tests
>  Centralizes in BuildOutputNode set the parent with AddChild function + test

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/LogView.cs
The TextWriter was using the version of WriteConsoleLogText that takes no monitor. Change it to use the method that takes a monitor, but improve handling for
null monitors.
Fixes VSTS #567563
> [d15.6][IDE] Fix null reference when code uses Log.WriteLine

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeIssues/AnalyzersFromAssembly.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
https://devdiv.visualstudio.com/DevDiv/_workitems?id=552019
No UI required - just some functionality in the md workspace was
missing.
> Fixed 'VSTS 552019: Fix AddMissingReferenceCodeAction'

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/BlameView.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/VersionControl.addin.xml
Blame has negative connotations, author does not
> [VCS] Change the word blame to authors

- version-checks
Updated reference to xamarin/md-addins@5ce2b67
> Updated reference to xamarin/md-addins@5ce2b67

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/ErrorText.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/MessageBubbleCache.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/MessageBubbleTextMarker.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/568082
> Fixed VSTS Bug 568082: Message bubble do not show warning code

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutput.cs
After all, it really supports several BuildStarted/BuildFinished events
in a single .binlog, so no need to ignore those events to just have one
BuildStarted/BuildFinished.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/567575
> [Ide] Fix saving of build logs with multiple builders

- main/src/core/MonoDevelop.Core/MonoDevelop.Core/LoggingService.cs
LoggingService was not thread safe for adding and removing loggers,
and that sometimes caused a crash.
> Fix random crash when running unit tests

- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/IndentationTrackerTests.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpIndentationTracker.fs
> Fix character deletion bug caused by bad indentation tracker fix

- main/src/core/MonoDevelop.Ide/ExtensionModel/StockIcons.addin.xml
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutput.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputNode.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputTreeCellView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputWidget.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
Still in progress -> DO NOT MERGE
> Initial implementation BuildOutputTreeCellView a cell render

- main/src/core/MonoDevelop.Ide/ExtensionModel/StockIcons.addin.xml
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputNode.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputTreeCellView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/StockIcons.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/570039
> [Build output] Use error/warning icons for tasks with errors/warnings

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputTreeCellView.cs
Adds TextWrapping to current cell renderer
It takes into account the width of the Information Panel
> Adds TextWrapping to current cell renderer

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputNode.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputTreeCellView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/MSBuildOutputProcessor.cs
Adds additional information to Build node
Fixes #570045
> Adds additional information to Build node

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CompletionProvider/ProtocolMemberCompletionProvider.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/RoslynCompletionData.cs
completion suggestion
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/569951
That completion provider should move to md-addins.
> Fixed VSTS 569951: Method description is not displayed for code

- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor.Utils/CompressingTreeList.cs
https://github.com/mono/monodevelop/issues/3610
> Fixes issue #3610 Error in Diff Tracker

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputWidget.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/571669
> [Ide] Use alternating row colors in tree view

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputNode.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputProcessor.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputTreeCellView.cs
Adds feature to show errors and warnings when node is collapsed
Fixes #570136
Fixes #570560
> Adds feature to show errors and warnings when node is collapsed

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputNode.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputTreeCellView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputWidget.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/IBuildOutputContextProvider.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
Instead of hiding times that are < 1 second, always display them, as if not,
it really confuses users.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/571671
> [Ide] Improve timing representation

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputTreeCellView.cs
This happens when errors number exceeded from 2 digits
> Fixes the calculation to start draw warning icons

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputTreeCellView.cs
Our renderer now calculates the next elements using the previous TextLayout element
> Text positionin based in TextLayout in BuildOutputTreeCellView

- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/addins/MonoDevelop.UnitTesting/Services/AbstractUnitTestEditorExtension.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/ContextMenu.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/ContextMenuExtensionsMac.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputWidget.cs
This includes some ContextMenu API changes
> Native Structured Build Output – Fix native context menu

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=59717
> Fix startup for old GLib

- main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj
- main/src/core/MonoDevelop.Core/packages.config
This version includes ARM builds of libe_sqlite3.so
Replaces https://github.com/mono/monodevelop/pull/3923
> Update to a newer SQLitePCLRaw

- main/src/addins/CSharpBinding/MonoDevelop.CSharp/PathedDocumentTextEditorExtension.cs
https://github.com/mono/monodevelop/issues/4007
> Fixes issue #4007 UI accessed from non-UI thread

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CompletionProvider/ProtocolMemberCompletionProvider.cs
https://github.com/mono/monodevelop/issues/4006
> Fixes issue #4006  Fatal error terminated IDE

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/EditorConfigService.cs
Work around to guard against multiple start watching calls.
> [Ide] Fixed Editorconfig bug.

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.CodeRefactorings/UsingRefactorings/SortImportsCodeRefactoringProvider.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/576790
> Fixes VSTS 576790: Update text for Sort and remove usings

- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/TemplateTests.fs
Pre-requisite for https://github.com/xamarin/md-addins/pull/2960
> Ignore Xamarin Forms SDK project build test. It's currently not testable

- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/IToolboxLoader.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/ToolboxService.cs
- main/src/addins/MonoDevelop.GtkCore/MonoDevelop.GtkCore.GuiBuilder/ToolboxLoader.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Core/Runtime.cs
- main/src/core/MonoDevelop.Core/MonoDevelop.Projects.MSBuild/RemoteBuildEngineManager.cs
- main/tests/Ide.Tests/FileTransferTests.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Gui/CompletionListWindowTests.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Projects/DotNetCoreProjectTests.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Projects/PclToProjectJsonConversionTests.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Projects/ResourcesTests.cs
- main/tests/Ide.Tests/MonoDevelop.Ide/TypeSystemServiceTests.cs
- main/tests/Ide.Tests/MonoDevelop.Ide/UserPreferencesTests.cs
- main/tests/Ide.Tests/MonoDevelop.SourceEditor/DebugTooltipTests.cs
Make sure all solutions and projects created during test execution are properly disposed.
> Fix potential hang in Ide tests

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/MdTextViewLineCollection.MdTextViewLine.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/MdTextViewLineCollection.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/MonoTextEditor.ITextView.cs
- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs
ITextViewLines in the view
https://github.com/mono/monodevelop/issues/3999
> Fixes issue #3999 MdTextViewLineCollection does not format all

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AtkCocoaHelper/AtkCocoaHelperMac.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AtkCocoaHelper/AtkCocoaHelperNoOp.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.DockNotebook/DockNotebookTab.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.DockNotebook/TabStrip.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/DockItem.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/DockItemContainer.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/DockItemTitleTab.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/DockItemToolbar.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/TabStrip.cs
D15.7 version of the tidy-up-groups branch
> Tidy up groups d15 7

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/HighlightUnusedCode.fs
Backport https://github.com/mono/monodevelop/pull/3528 to fix VSTS  #577640 F# editor is horribly slow
> D15-6 fix 577640

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Project/CSharpCompilerParameters.cs
Fix this issue https://github.com/mono/monodevelop/issues/4105
> Support C# 7.2

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CompletionProvider/ProtocolMemberCompletionProvider.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/LineSeparatorTextEditorExtension.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/576053
Only affects the 15-6 branch.
> Fixes VSTS 576053: MonoDevelop closes trying to open a solution project

- main/src/core/MonoDevelop.Ide/ExtensionModel/StockIcons.addin.xml
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputTreeCellView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputWidget.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/MSBuildOutputProcessor.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/StockIcons.cs
This do some refactors in our cell renderer to integrate expand feature which Lluis included in Xwt examples.
Probably well need better icons in expander.
Fixes #570068
> Adds expander feature and selection + bumps xwt

- main/src/addins/CSharpBinding/MonoDevelop.CSharp/SignatureMarkupCreator.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/RoslynCompletionData.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/SignatureHelpParameterHintingData.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/SyntaxHighlightingService.cs
> [Ide] Fix editor tooltip theme fitting

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputTreeCellView.cs
Aligns configuration and start time to the left of the screen
Fixes Task #578470
> Aligns configuration and start time to the left of the screen

- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/MonoDevelop.FSharp.Tests.fsproj
- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/SolutionPadOrdering.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpProjectFileNodeExtension.fs
> Fixes solution pad rendering order for Linked files

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/DispatchService.cs
Something is queueing a null callback on the UI thread. Stop that from happening, and log a stacktrace on the bg thread doing the queueing so we know what is causing it
Fixse VSTS #581086 - NRE exception in MD.Ide. DispatchService
> [Ide] Fix a crash happening on a null callback post/send

- main/Directory.Build.props
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Project/CSharpCompilerParameters.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Project/CSharpLanguageVersionHelper.cs
- main/src/core/MonoDevelop.Core/packages.config
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Composition/CompositionManager.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/EditorThemeColors.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/Formats/OldFormat.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/RoslynClassificationHighlighting.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopPersistentStorageLocationService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
- main/src/core/MonoDevelop.Startup/app.config
- main/tests/MonoDevelop.Refactoring.Tests/MonoDevelop.Refactoring.Tests.csproj
@Therzok there's currently a build failure here:
```
"C:\monodevelop\main\src\core\MonoDevelop.Ide\MonoDevelop.Ide.csproj" (default target) (24) ->
(CoreCompile target) ->
MonoDevelop.Ide.TypeSystem\MonoDevelopPersistentStorageLocationService.cs(47,54): error CS0535: 'MonoDevelopPe
rsistentStorageLocationService' does not implement interface member 'IPersistentStorageLocationService.TryGetSto
rageLocation(SolutionId)' [C:\monodevelop\main\src\core\MonoDevelop.Ide\MonoDevelop.Ide.csproj]
MonoDevelop.Ide.TypeSystem\MonoDevelopPersistentStorageLocationService.cs(47,54): error CS0535: 'MonoDevelopPe
rsistentStorageLocationService' does not implement interface member 'IPersistentStorageLocationService.StorageLo
cationChanging' [C:\monodevelop\main\src\core\MonoDevelop.Ide\MonoDevelop.Ide.csproj …
```
> Bump Roslyn to 2.8.0-beta2-62708-11

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CodeCompletion/CompletionWindowManager.cs
https://github.com/mono/monodevelop/issues/4092
> Fixes issue #4092 Fatal error in intellisense (master)

- main/src/addins/MacPlatform/MainToolbar/MainToolbar.cs
> [61249][Mac] Trigger global search when initiated from the editor

- main/src/addins/MacPlatform/MainToolbar/MainToolbar.cs
#4053 for 15.7, Fixes bxc #61249
> [15.7][61249][Mac] Trigger global search when initiated from the editor

- main/src/addins/MonoDevelop.SourceEditor2/VSEditor/Language/Impl/QuickInfo/QuickInfoController.cs
Cancellation token may be disposed in a race condition
> Fix a nullreference exception in QuickInfo

- main/src/core/MonoDevelop.Core/MonoDevelop.Core.csproj
- main/src/core/MonoDevelop.Core/packages.config
Actually there is no need to bump other users since assembly API and version is same...
> Fix 578232: bump Mono.Cecil

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/DiffTracker.cs
- main/src/core/MonoDevelop.TextEditor.Tests/Mono.TextEditor.Tests/DiffTrackerTests.cs
- main/src/core/MonoDevelop.TextEditor.Tests/MonoDevelop.TextEditor.Tests.csproj
It's now underpinned with a test suite as well.
> [SourceEditor] Fixed diff tracker.

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/581661
Seems that a span change detection was missing completely - that this
worked in former versions must've been a side effect. I took the
chance to ensure that highlighting is really done in background which
looks ok on my systems.
> Fixes VSTS 581661: [Feedback] /* */ Comments slow or non responsive

- main/src/addins/CSharpBinding/CSharpBinding.csproj
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.CodeGeneration/CodeGenerationOptions.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Features/AutoInsertBracket/CSharpAutoInsertBracketHandler.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpFormatter.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpTextEditorIndentation.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/OnTheFlyFormatter.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Resolver/HelperMethods.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp/DocumentContextExtension.cs
https://github.com/mono/monodevelop/issues/4173
> Fixes issue #4173 C# sources with `None` build action are not editable

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/ISyntaxHighlighting.cs
This way it's a bit less complex.
> [SourceEditor] Implemented other apporach to fix the update issue.

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/DocumentUpdateRequest.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/SyntaxHighlighting.cs
The text mate based highlighting was broken as well. And streamlined
the text view highlighting recognition changes.
> [SourceEditor] Fixed text mate highlighting.

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git.Tests/GitIntegrityTests.cs
The tests are obviously not so exhaustive, but it verifies the utilities work
properly and that blame is handled correctly, for additions, changes, insertions,
deletion.
> [VCS] Make blame integrity tests not depend on MD git repo

- main/src/addins/MacPlatform/Dialogs/MacAddFileDialogHandler.cs
This uses the same fix as a4bbb0989b9c9767766e6b16a83f0c07c406d0c2
to fix this dialog being broken on High Sierra. Don't layout
after setting the accessory view
Fixes VSTS #585364 Add File/[Options] UI is not shown
> [15.7][Mac] Fix Add Files dialog being broken on High Sierra

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeIssues/CodeDiagnosticRunner.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor.Utils/CompressingTreeList.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/DiffTracker.cs
- main/src/core/MonoDevelop.TextEditor.Tests/Mono.TextEditor.Tests/DiffTrackerTests.cs
- main/src/core/MonoDevelop.TextEditor.Tests/MonoDevelop.TextEditor.Tests.csproj
It's now underpinned with a test suite as well.
Fixes VSTS #584103.
> [15.6] Extreme drop in editor performance after update to version

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextViewMargin.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/DocumentUpdateRequest.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/ISyntaxHighlighting.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/SyntaxHighlighting.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/581661
Seems that a span change detection was missing completely - that this
worked in former versions must've been a side effect. I took the
chance to ensure that highlighting is really done in background which
looks ok on my systems.
> [15.6] Fixes VSTS 581661: [Feedback] /* */ Comments slow or non responsive

- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/UrlMarker.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/HighlightUrlExtension.cs
as you collapse indentation
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/585183
Found & fixed a small drawing bug for url markers as well.
> Fixed VSTS 585183: In HTML/Razor files, url underlines do not adjust
