mono/monodevelop

- main/build/MacOSX/make-dmg-bundle.sh
With the move to Xcode 10.2, we need to build on Mojave bots, and there's
a bug (https://github.com/al45tair/dmgbuild/issues/10) that makes unmounting
time out on the bots, which is fixed by just retrying :/
Backport of #7809.
/cc @rodrmoya
> [release-8.0] [Mac] Retry unmounting because of an issue in the Mojave bots

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/SourceCodeLookup.cs
Since it is possible that the assemblies being debugged could have
been compiled on a different system (potentially with different line
endings), compute hashes for the source code in 3 formats:
1. The source code file with line endings as-is
2. The source code file with DOS line endings
3. The source code file with UNIX line endings
Note: sometimes source code may have mixed line endings, so it is
important to calculate the source code as-is and not just
canonicalized UNIX and DOS line endings.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/642329
Fixes issue #5260
> [Debugger] Improved source checksum logic for UNIX and DOS line endings

- main/build/MacOSX/make-dmg-bundle.sh
This fixes 'make dmg' step in VSTS on the Mojave bot pool, where doing the
image generation in several steps, including mounting and unmounting, was
timing out.
> [release-8.1] [Mac] Refactor DMG generation to just use a single hdiutil call

- main/build/MacOSX/make-dmg-bundle.sh
This fixes 'make dmg' step in VSTS on the Mojave bot pool, where doing the
image generation in several steps, including mounting and unmounting, was
timing out.
Backport of #7830.
/cc @rodrmoya
> [release-8.0] [Mac] Refactor DMG generation to just use a single hdiutil call

- main/src/addins/MacPlatform/MacPlatform.cs
Stop force resizing the window, because in some situations it can cause the NSWindow and the GtkWindow to be different
sizes.
Fixes VSTS #900933
> [Mac] Don't force resize the window when positioning it

- main/src/addins/MacPlatform/MacPlatform.cs
Stop force resizing the window, because in some situations it can cause the NSWindow and the GtkWindow to be different
sizes.
Fixes VSTS #900933
Backport of #7764.
/cc @iainx
> [release-8.1] [Mac] Don't force resize the window when positioning it

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/DefaultWorkbench.cs
An error disposing a pad on closing the workbench results in
a fatal exception which may crash the IDE. Handle any error on
disposing the pad with a try/catch.
Fixes VSTS #911276 - [Watson] Crash in PackageConsolePad
> [Ide] Handle exception disposing pad on closing the workbench.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/DefaultWorkbench.cs
An error disposing a pad on closing the workbench results in
a fatal exception which may crash the IDE. Handle any error on
disposing the pad with a try/catch.
Fixes VSTS #911276 - [Watson] Crash in PackageConsolePad
Backport of #7836.
/cc @mrward
> [release-8.1] [Ide] Handle exception disposing pad on closing the workbench.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.DockNotebook/DockNotebookContainer.cs
This is a workaround until we find the right solution for the broken GDK events with embedded native views.
Fixes VSTS #910879
> [Ide] Use regular Gtk.HPaned for split view with the new editor

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.DockNotebook/DockNotebookContainer.cs
This is a workaround until we find the right solution for the broken GDK events with embedded native views.
Fixes VSTS #910879
Backport of #7838.
/cc @sevoku
> [release-8.1] [Ide] Use regular Gtk.HPaned for split view with the new editor

- main/build/MacOSX/BinaryCompatBaseline.txt
- main/tests/Ide.Tests/MonoDevelop.Ide.Gui/GLibLoggingTests.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.RoslynServices/MonoDevelopProjectCacheHostServiceTests.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/MSBuildProjectTests.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/ProjectTests.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/ProjectWithWildcardsTests.cs
Mono 6.0 has changed the assembly resolution error message from:
Could not load file or assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies
To:
Could not load the file 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
> Update BinaryCompat for Mono 6.0

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/TreeBuilder.cs
AddChildren
https://github.com/mono/monodevelop/issues/7403
Setting the sort function there is not needed Freeze/Thaw is the only
thing needed at that point to prevent updates and unneeded sorting.
> Fixes issue #7403 UI hang due to setting DefaultSortFunc in

- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebugCommands.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/Extensions.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/RootWorkspace.cs
The memento needs to be restored after the toolbar has been attached to the window to take it into consideration in the size calculations. This caused problems when combined with Workbench.Present: If the workbench window was first shown using Present, subsequent calls to EnsureLayout would never update the window size to take the toolbar height into consideration, which caused the mouse pointer offset bugs.
Also unify the confusion between Workbench.Show and Workbench.Present, deprecating the former.
Fixes VSTS #911290
> [IDE] Restore the memento after the toolbar has been attached

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Debugger/RoslynDebugInfoProvider.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/QuickInfo/DebuggerQuickInfoSource.cs
Fix 842970: [Feedback] Editing tooltips are shown instead of debugging tooltips
Fix 855907: [Feedback] Debugging Variable Values Regression, Visual Studio for Mac Preview 3 New Editor Preview
VSWindows doesn't show intelisense tooltips, but old editor did and it makes sense to show intelisense tooltips rather then nothing... But last time I was bringing this feature to new editor I didn't copy old editor logic instead took shortcuts that resulted in this 2 bugs, now old editor logic is copied and all should be good going forward.
Also brought another related feature I liked in old editor, which is evaluating selected text when hovering selected text, useful for evaluating parts of `if` statements and to evaluate method calls.
> Fixes new editor debugger tooltip not showing errors

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentController.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/911693
Revert "[Ide] Added a disposed token to the document controller API."
This reverts commit 800c10b8d37ebc6aeb9367390bc3015244614701.
> Fixes VSTS Bug 911693: New document model dispose logic was regressed

- main/build/MacOSX/monostub.mm
Backport of #7883.
/cc @slluis
> [pr-bump-deps-for-d16-2] Bump min mono version to 6.0.0.296

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Project/CompilerOptionsPanelWidget.cs
Remove `CSharp8` and `LatestMajor` from unsupported list.
Fixes https://devdiv.visualstudio.com/DevDiv/_workItems/edit/916849
> [CSharpBinding] Allow choosing C# 8

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Project/CompilerOptionsPanelWidget.cs
Remove `CSharp8` and `LatestMajor` from unsupported list.
Fixes https://devdiv.visualstudio.com/DevDiv/_workItems/edit/916849
Backport of #7870.
/cc @slluis @sandyarmstrong
> [release-8.2-preview1] [CSharpBinding] Allow choosing C# 8

- main/src/addins/AspNet/Properties/MonoDevelop.AspNet.addin.xml
The extension was removed with https://github.com/mono/monodevelop/commit/4971b9d3563fa4660e022177194263803df9d968
> Delete reference to RazorCSharpEditorExtension that no longer exists.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/DockContainer.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/MacSplitterWidget.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/SplitterGtkNSViewHostWidget.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/SplitterMacHostWidget.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/SplitterWidgetWrapper.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
This PR fixes the resize behaviour in dock containers when mouse is over native embed areas
To solve this, we had to deal with some problems:
- Create a MacSplitterWidget (because we need this view above the GTK layer to capture some mouse over events),
- Doesn't break GTK
- Capture and not let GTK swallow the mouse events 
- Introduces SplitterGtkNSViewHostWidget based in a new GtkNSViewHostWidget, this layer encapsules  the logic to handle drag logic between toolkits
In order not to break GTK, I tried first to encapsule both backends and expose it over a wrapper class  SplitterWidgetWrapper with same interface.
In case of the cocoa backend, I created a native view (MacSplitterWidget) which GTK embeds into a SplitterGtkNSViewHostWidget extending from GtkNSViewHostWidget. This host widget …
> Fixes resize dock containers in our dock system moving  SplitterWidget to native

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/Properties/MonoDevelop.TextEditor.addin.xml
This PR lights up support for `Go To Matching Brace` command in the new editor. 
**Note: it requires an API Sync to happen.**
VSTS: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/891769
VSEC PR: https://github.com/xamarin/vs-editor-core/pull/335
> Fixes VSTS 891769: Go To Matching Brace does not work

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.ExtractInterface/ExtractInterfaceOptionService.cs
It appears a [change](https://github.com/mono/monodevelop/commit/5f30ab59a877f97724d68350d0b846822b2c4e23#diff-43ce8a1c5ce56b4b8c9e5bde48d8efe9) removed an explicit call to `Dispose` the dialog. That meant that while the service received and acted upon the return value (i.e. it generated the extracted interface, etc.) the actual dialog was never closed/disposed of. 
I've wrapped it in a `using` statement, which seems to have done the trick.
VSTS link: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/893547
> Fixes VSTS 893547: Extract Interface Dialog buttons don't close dialog

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/Properties/MonoDevelop.TextEditor.addin.xml
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/SupportedFileTypeExtensionNode.cs
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/TextViewDisplayBinding.cs
This adds a new extension point that extensions can use to opt individual file types into the new editor, optionally controlled by feature flags.
This means that extensions can light up new file types in the new editor without changing the new editor itself.
> [TextEditor] Allow extensions to opt file types into new editor

- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/MacToolboxWidget.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/ToolboxPad.cs
We are hitting this issue from Catalina users, not tested yet in a Catalina machine.
probably happens because we are calling the Refresh after resize the toolbox pad, and to calculate the item size it a list mode it uses the Frame.width.  
I moved Refresh call after the ShowAll call from the gtk widget, and also added a condition to ensure never our item size is going to be negative, and also added a try/catch with some logging information
Fixes VSTS #905849 - NSInternalInconsistencyException negative or zero item sizes are not supported in the flow layout in MacToolboxWidget
> [Watson][Toolbox] Ensures ItemSize is always positive and log if exception occurs

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.ExtractInterface/ExtractInterfaceOptionService.cs
It appears a [change](https://github.com/mono/monodevelop/commit/5f30ab59a877f97724d68350d0b846822b2c4e23#diff-43ce8a1c5ce56b4b8c9e5bde48d8efe9) removed an explicit call to `Dispose` the dialog. That meant that while the service received and acted upon the return value (i.e. it generated the extracted interface, etc.) the actual dialog was never closed/disposed of. 
I've wrapped it in a `using` statement, which seems to have done the trick.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/918117/
Backport of #7850.
> [release-8.1] Fixes VSTS 918117: Extract Interface Dialog buttons don't close dialog

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CSharpCompletionTextEditorExtension.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.OptionPanels/CompletionOptionsPanel.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices.Options/RoslynPreferences.cs
Roslyn implemented this feature as a per-language setting, not a global
intellisense setting like MonoDevelop has. In the future, we should
reorganize this setting to reflect that (and match Windows).
Ensure that the Roslyn feature is disabled in old editor completion. The
items show up correctly in the list, but insertion fails to actually add
the `using` statement. The old editor can continue using its existing
implementation of this feature.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/756548
> Map "Show import items" option to equivalent Roslyn feature

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
Two (or more) files are created from outside of VS4Mac, then, using VS4Mac are added to Version Control and try to Commit with only one of the files selected.
The expected result is that we only Commit the selected file, however we commit everything.
The problem is that, when doing the Add of a file in Version Control, internally we do a Stage (we add the path of the file to the git index). At the end it is the same as what we do in a Commit. So, although in the Commit only select one of the files, every added files are included (they are in the index).
Added some changes to Unstage the unselected changes and re-stage at the end of the Commit (whether done or in case of an error).
Fixes VSTS #825343
> [Version Control] Mismatches actual files commited vs selected when using git 

- main/tests/Ide.Tests/MonoDevelop.Ide.RoslynServices/MonoDevelopProjectCacheHostServiceTests.cs
- main/tests/UnitTests/ObjectReference.cs
If we want to be sure that an object will be collected, all its references must be done within PerformNoPinAction. This also means that the object must be allocated in such a region. Also we should immediately collect after the action, so the object is dead for good, and not bring back additional references to it (for example by calling weakReference.IsAlive which is going to access the Target and might keep it alive on stack, previously producing failures of these tests).
Unify line endings because it screwed up my editor.
Fixes https://github.com/mono/mono/issues/14882
> Fix tests that rely on object collection

- .gitmodules
Need to switch off of Kirill's fork to the new official repo for servicing 8.1 as well.
> [release-8.1] vs-editor-api: switch to official Microsoft repo

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopMetadataReferenceManager.cs
By doing so, we ensure that any in-flight operation to update an assembly from disk must happen before we clear the caches.
Backport of #7810.
> [release-8.1] [Workspace] Swap the order of cache clearing in the manager.

- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/MacToolboxWidget.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/ToolboxPad.cs
We are hitting this issue from Catalina users, not tested yet in a Catalina machine.
probably happens because we are calling the Refresh after resize the toolbox pad, and to calculate the item size it a list mode it uses the Frame.width.  
I moved Refresh call after the ShowAll call from the gtk widget, and also added a condition to ensure never our item size is going to be negative, and also added a try/catch with some logging information
Fixes VSTS #905849 - NSInternalInconsistencyException negative or zero item sizes are not supported in the flow layout in MacToolboxWidget 
Backport of #7854.
> [release-8.1] [Watson][Toolbox] Ensures ItemSize is always positive and log if exception occurs

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/TextViewContent.cs
Instead the task of disposing it should be left to the document model registry. In case where said instance is shared, the manual dispose would corrupt the version still stored inside the registry causing all sorts of failures when reopening documents.
Backport of #7608.
/cc @slluis @garuma
> [release-8.1] [TextEditor] Don\u0027t manually dispose the TextDocument instance.

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlTask.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/StatusProgressMonitor.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.ProgressMonitoring/MessageDialogProgressMonitor.cs
Having the Get To Code Dialog and not having the Workbench visible, can not see the StatusView monitor feedback.
Added changes to use an alert instead of using the monitor if the workbench is not visible.
Fixes VSTS #896537
> [Shell] Show an alert in StatusMonitor if the Workbench is not visible

- main/Directory.Build.props
- main/src/addins/MacPlatform/MacInterop/Carbon.cs
- main/src/addins/MacPlatform/MacPlatform.cs
Exception handlers considered empty will trigger a build and edit-time warning.
Fixes VSTS #774649 - SDL - Validate all new code is free of 'swallow everything' exception handlers
> Bump to new MD analyzer nuget

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/MessageService.cs
It seems that, on Mojave and for ... unknown reasons, setting TransientFor more than once on a window makes the transient window's subwindows (like popup menus, tooltips) appear behind it if the root window is fullscreen.
Fixes VSTS #911342
Fixes VSTS #735232
Fixes VSTS #893128
Fixes VSTS #888180
Fixes VSTS #890152
Fixes VSTS #850411
Fixes VSTS #918636
Fixes VSTS #848640
Fixes VSTS #856017
Fixes VSTS #891805
Fixes VSTS #893128
> [IDE] Only set TransientFor when showing the window, not when centering

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/MessageService.cs
It seems that, on Mojave and for ... unknown reasons, setting TransientFor more than once on a window makes the transient window's subwindows (like popup menus, tooltips) appear behind it if the root window is fullscreen.
Fixes VSTS #911342
Fixes VSTS #735232
Fixes VSTS #893128
Fixes VSTS #888180
Fixes VSTS #890152
Fixes VSTS #850411
Fixes VSTS #918636
Fixes VSTS #848640
Fixes VSTS #856017
Fixes VSTS #891805
Fixes VSTS #893128
Backport of #7923.
> [release-8.2] [IDE] Only set TransientFor when showing the window, not when centering

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/CSharpEnableNewEditorSwitchController.cs
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/Properties/MonoDevelop.TextEditor.addin.xml
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/TextViewDisplayBinding.cs
Fix AB#918947
Additionally this PR removes the entries for XAML and Android resource files which are now exported by their respective addins.
> [TextEditor] Use feature flag instead of global option to enable new editor for C#

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/MessageService.cs
It seems that, on Mojave and for ... unknown reasons, setting TransientFor more than once on a window makes the transient window's subwindows (like popup menus, tooltips) appear behind it if the root window is fullscreen.
Fixes VSTS #911342
Fixes VSTS #735232
Fixes VSTS #893128
Fixes VSTS #888180
Fixes VSTS #890152
Fixes VSTS #850411
Fixes VSTS #918636
Fixes VSTS #848640
Fixes VSTS #856017
Fixes VSTS #891805
Fixes VSTS #893128
Backport of #7923.
> [release-8.1] [IDE] Only set TransientFor when showing the window, not when centering

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/CSharpEnableNewEditorSwitchController.cs
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/Properties/MonoDevelop.TextEditor.addin.xml
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/TextViewDisplayBinding.cs
Fix AB#918947
Additionally this PR removes the entries for XAML and Android resource files which are now exported by their respective addins.
Backport of #7929.
/cc @abock @garuma
> [release-8.2] [TextEditor] Use feature flag instead of global option to enable new editor for C#

- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/IDragDataToolboxNode.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.csproj
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/ToolboxPad.cs
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/ToolboxDropHandler.cs
Dropping things on `ITextView` is handled by different `IDropHandler`s. `IDropHandler` is chosen based on `[DropFormat ("XXX")]` and priority... So now when ToolboxPad starts dragging session we always insert `MonoDevelopToolBox` so our `MonoDevelopToolBoxDropHandler` is picked to handle dropping. Which then executes `ConsumeItem` for currently selected item on `Document` that is parent of `textView` that was dropped on.
I also added `IDragDataToolboxNode` interface which allows others e.g. Android Designer to define their own `DropFormat` and `byte[]` data when dragging starts that they want to pass to their own `IDropHandler`.
> Fixed Snippets Drag&Drop and added ability for Android Designer to do D&D

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/ExceptionCaught/ExceptionCaughtAdornmentManager.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/923058
Backport of #7942.
/cc @abock
> [master] [release-8.1] ExceptionCaughtAdornmentManager: catch and log exception

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/ExceptionCaught/ExceptionCaughtAdornmentManager.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/923058
Backport of #7942.
/cc @abock
> [release-8.2] [release-8.1] ExceptionCaughtAdornmentManager: catch and log exception

- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/IDragDataToolboxNode.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.csproj
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/ToolboxPad.cs
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/ToolboxDropHandler.cs
Dropping things on `ITextView` is handled by different `IDropHandler`s. `IDropHandler` is chosen based on `[DropFormat ("XXX")]` and priority... So now when ToolboxPad starts dragging session we always insert `MonoDevelopToolBox` so our `MonoDevelopToolBoxDropHandler` is picked to handle dropping. Which then executes `ConsumeItem` for currently selected item on `Document` that is parent of `textView` that was dropped on.
I also added `IDragDataToolboxNode` interface which allows others e.g. Android Designer to define their own `DropFormat` and `byte[]` data when dragging starts that they want to pass to their own `IDropHandler`.
Backport of #7906.
> [release-8.2] Fixed Snippets Drag&Drop and added ability for Android Designer to do D&D

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_queries/edit/923054
Backport of #7938.
/cc @abock
> [master] GtkNSViewHost: fix NRE in OnFocusOutEvent

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_queries/edit/923054
Backport of #7938.
/cc @abock
> [release-8.2] GtkNSViewHost: fix NRE in OnFocusOutEvent

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
because LibGit2Sharp (Ide closed)
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/901467
Running that as blocking operation could lead to locks/very long
delays running repository.Blame in locked context should fix a
possible multi threaded blame issue. However I couldn't reproduce the
issue.
Improved blame code a bit.
> Fixes VSTS Bug 901467: Suddenly and silently native crash in the IDE

- main/Directory.Build.props
FYI @sandyarmstrong
Changes since [2e7c46d683](https://www.github.com/dotnet/roslyn/commit/2e7c46d683):
- [Merge pull request #36345 from jasonmalinowski/unskip-test](https://www.github.com/dotnet/roslyn/pull/36345)
- [Add option to emit nullable metadata for public members only (#36398)](https://www.github.com/dotnet/roslyn/pull/36398)
- [Added null checks on F# external access services (#36469)](https://www.github.com/dotnet/roslyn/pull/36469)
- [Merge pull request #36465 from dotnet/revert-36006-extract_open_file_tracker](https://www.github.com/dotnet/roslyn/pull/36465)
- [Merge pull request #36463 from tmeschter/ShortenLongResourceID-190614](https://www.github.com/dotnet/roslyn/pull/36463)
- [Merge pull request #36462 from dotnet/dev/jorobich/add-wpf-reference](https://www.github.com/d …
> Bump Roslyn to 3.2.0-beta4-19317-08

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/Extensions/IProjectionBufferProvider.cs
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/TextViewContent.cs
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/TextViewImports.cs
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/Util/ProjectionTextDataModel.cs
This will be used by the new web editors to provide the surface Htmlx buffer for .cshtml views.
If the projection buffer is not specified the behavior is identical to the regular vanilla VacuousTextDataModel.
> Add an extension point to provide projection buffers during text view construction

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.DockNotebook/DockNotebookContainer.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/MacSplitterWidget.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/HPanedThin.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/DragEventTrapView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/VPanedThin.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
Use the same technique we use for Pad resizing in #7762 to fix the resizing in the document split view.
> Fixes VSTS [#910879](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/910879)
> Fix split editor view with the new editor

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.DockNotebook/DockNotebookContainer.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/MacSplitterWidget.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/HPanedThin.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/DragEventTrapView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/VPanedThin.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
Use the same technique we use for Pad resizing in #7762 to fix the resizing in the document split view.
> Fixes VSTS [#910879](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/910879)
Backport of #7896.
/cc @sevoku
> [release-8.2] Fix split editor view with the new editor

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlTask.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/StatusProgressMonitor.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.ProgressMonitoring/MessageDialogProgressMonitor.cs
Having the Get To Code Dialog and not having the Workbench visible, can not see the StatusView monitor feedback.
Added changes to use an alert instead of using the monitor if the workbench is not visible.
Fixes VSTS #896537
Backport of #7629.
> [release-8.2] [Shell] Show an alert in StatusMonitor if the Workbench is not visible

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/TextViewContent.cs
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/ThemeToClassification.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/EditorConfigService.cs
Prefer new `rulers` value from editorconfig, which allows setting
multiple vertical rulers (like in vscode).
Then, check `max_line_length` like the old editor does.
Finally, use the VSmac preference/policy system.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/798040
>  TextViewContent: Show column rulers, including new editorconfig value

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/TextViewContent.cs
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/ThemeToClassification.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/EditorConfigService.cs
Prefer new `rulers` value from editorconfig, which allows setting
multiple vertical rulers (like in vscode).
Then, check `max_line_length` like the old editor does.
Finally, use the VSmac preference/policy system.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/798040
Backport of #7975.
> [release-8.2]  TextViewContent: Show column rulers, including new editorconfig value

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/OnTheFlyFormattingPanel.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices.Options/RoslynPreferences.cs
* ShowCompletionItemFilters (new UI landing in editor)
* TriggerOnDeletion (forced in old editor, configurable in new)
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/914033
Backport of #7976.
> [release-8.2] C#: Add some missing options

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Services.cs
Services.CounterReport() tries to insert 16 counters in the array, but the predefined array size is just 15 which leads to `IndexOutOfBoundsException`
> Services.CounterReport() - increase array size to hold all 16 counters

- main/msbuild/ReferencesVSEditor.Windows.props
- main/src/core/MonoDevelop.Ide/AssemblyInfo.cs
It uses the Microsoft public key, so we can't just use the MSBuild InternalsVisibleTo item, because it presupposes the MonoDevelop public key.
Also fix Windows build while i'm at it.
> Add IVT to the new WebEditors addin.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/InfoBar.cs
The InfoBar padding is different for bars with buttons and those without.
By setting a `MinHeight` on the inner InfoBar HBox, we can have the same padding appear for both, making them consistent.
Fixes VSTS #934603 - Improve padding of InfoBar items when no button is present
> Fixes VSTS #934603 - Improve padding of InfoBar items when no button is present

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.ProjectSystemHandler.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
- main/tests/Ide.Tests/MonoDevelop.Ide/TypeSystemServiceTests.cs
- main/tests/test-projects/projection-tests/missing-projection-file.sln
- main/tests/test-projects/projection-tests/missing-projection-file/MyClass.cs
- main/tests/test-projects/projection-tests/missing-projection-file/missing-projection-file.csproj
If a project referenced a .xaml file that did not exist then the
type system would throw a file not exception and not load any
type information for the solution. This then broke code completion,
go to declaration, etc. To avoid this error a check is made to
ensure the file exists before trying to generate projections for the
.xaml file.
Fixes VSTS #918867 - Missing xaml file breaks intellisense
Backport of #7996.
> [release-8.1] [Ide] Fix missing xaml file breaking intellisense

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.ProjectSystemHandler.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
- main/tests/Ide.Tests/MonoDevelop.Ide/TypeSystemServiceTests.cs
- main/tests/test-projects/projection-tests/missing-projection-file.sln
- main/tests/test-projects/projection-tests/missing-projection-file/MyClass.cs
- main/tests/test-projects/projection-tests/missing-projection-file/missing-projection-file.csproj
If a project referenced a .xaml file that did not exist then the
type system would throw a file not exception and not load any
type information for the solution. This then broke code completion,
go to declaration, etc. To avoid this error a check is made to
ensure the file exists before trying to generate projections for the
.xaml file.
Fixes VSTS #918867 - Missing xaml file breaks intellisense
Backport of #7996.
> [release-8.2] [Ide] Fix missing xaml file breaking intellisense

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.ProjectSystemHandler.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
- main/tests/Ide.Tests/MonoDevelop.Ide/TypeSystemServiceTests.cs
- main/tests/test-projects/projection-tests/missing-projection-file.sln
- main/tests/test-projects/projection-tests/missing-projection-file/MyClass.cs
- main/tests/test-projects/projection-tests/missing-projection-file/missing-projection-file.csproj
If a project referenced a .xaml file that did not exist then the
type system would throw a file not exception and not load any
type information for the solution. This then broke code completion,
go to declaration, etc. To avoid this error a check is made to
ensure the file exists before trying to generate projections for the
.xaml file.
Fixes VSTS #918867 - Missing xaml file breaks intellisense
> [Ide] Fix missing xaml file breaking intellisense

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
The crash:
```
FATAL ERROR [2019-04-30 14:04:35Z]: Visual Studio failed to start. Some of the assemblies required to run Visual Studio (for example gtk-sharp)may not be properly installed in the GAC.
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
at System.Collections.Generic.List`1[T].get_Item (System.Int32 index) [0x0000e] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-08/external/bockbuild/builds/mono-x64/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/List.cs:163 
at MonoDevelop.Components.Commands.CommandManager.ProcessKeyEventCore (Gdk.EventKey ev) [0x0016e] in /Users/vsts/agent/2.150.0/work/1/s/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Comp …
```
> [Shell] Fix fatal error changing keybindings prefs to ReSharper 

- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/PopoverWindow.cs
MonoDevelop.MacIntegration.MacPlatformService.RemoveWindowShadow
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/930131
Hard to tell how that happened - but added some checks that should
prevent the exception.
> Fixes VSTS Bug 930131: [Watson] NullReferenceException in

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.ProjectSystemHandler.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
- main/tests/Ide.Tests/MonoDevelop.Ide/TypeSystemServiceTests.cs
- main/tests/test-projects/projection-tests/missing-projection-file.sln
- main/tests/test-projects/projection-tests/missing-projection-file/MyClass.cs
- main/tests/test-projects/projection-tests/missing-projection-file/missing-projection-file.csproj
If a project referenced a .xaml file that did not exist then the
type system would throw a file not exception and not load any
type information for the solution. This then broke code completion,
go to declaration, etc. To avoid this error a check is made to
ensure the file exists before trying to generate projections for the
.xaml file.
Fixes VSTS #918867 - Missing xaml file breaks intellisense
Backport of #7996.
Backport of #7999.
/cc @sgmunn @monojenkins
> [release-8.2-preview2] [release-8.2] [Ide] Fix missing xaml file breaking intellisense

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs
MonoDevelop.Ide.Gui.Workbench.ReparseOpenDocuments()
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/935202
> Fixes VSTS Bug 935202: System.NullReferenceException exception in

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentController.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentView.cs
MonoDevelop.SourceEditor.SourceEditorView.MonoDevelop.Ide.Editor.ITextEditorImpl.GrabFocus()
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/935392
Without a repro it's hard to tell where that happens. I added dispose
checks & a null check on different levels of the call. It's caused by
the document level - GrabFocus beeing called on a disposed editor.
> Fixes VSTS Bug 935392: System.NullReferenceException exception in

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/PublishCommand.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/VersionControl.addin.xml
option is always disabled
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/936306
Command was put in main menu but the command was not implemented for
the main menu case.
> Fixes VSTS Bug 936306: [Feedback] The "Publish in version control"

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/PublishCommand.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/VersionControl.addin.xml
option is always disabled
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/936306
Command was put in main menu but the command was not implemented for
the main menu case.
Backport of #7994.
> [release-8.1] Fixes VSTS Bug 936306: [Feedback] The "Publish in version control"

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/PublishCommand.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/VersionControl.addin.xml
option is always disabled
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/936306
Command was put in main menu but the command was not implemented for
the main menu case.
Backport of #7994.
> [release-8.2] Fixes VSTS Bug 936306: [Feedback] The "Publish in version control"

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/InfoBar.cs
The InfoBar padding is different for bars with buttons and those without.
By setting a `MinHeight` on the inner InfoBar HBox, we can have the same padding appear for both, making them consistent.
Fixes VSTS #934603 - Improve padding of InfoBar items when no button is present
Backport of #7964.
/cc @sevoku @drasticactions
> [release-8.2] Fixes VSTS #934603 - Improve padding of InfoBar items when no button is present

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/InfoBar.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices/MonoDevelopInfoBarService.cs
Backport of #7965.
/cc @Therzok
> [release-8.2] Add some null checks that would prevent showing an info bar if an item array wasn't passed.

- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/PopoverWindow.cs
MonoDevelop.MacIntegration.MacPlatformService.RemoveWindowShadow
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/930131
Hard to tell how that happened - but added some checks that should
prevent the exception.
Backport of #7968.
> [release-8.2] Fixes VSTS Bug 930131: [Watson] NullReferenceException in

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
The crash:
```
FATAL ERROR [2019-04-30 14:04:35Z]: Visual Studio failed to start. Some of the assemblies required to run Visual Studio (for example gtk-sharp)may not be properly installed in the GAC.
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
at System.Collections.Generic.List`1[T].get_Item (System.Int32 index) [0x0000e] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-08/external/bockbuild/builds/mono-x64/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/List.cs:163 
at MonoDevelop.Components.Commands.CommandManager.ProcessKeyEventCore (Gdk.EventKey ev) [0x0016e] in /Users/vsts/agent/2.150.0/work/1/s/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Comp …
```
> [release-8.2] [Shell] Fix fatal error changing keybindings prefs to ReSharper 

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/Workbench.cs
MonoDevelop.Ide.Gui.Workbench.ReparseOpenDocuments()
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/935202
Backport of #8010.
> [release-8.2] Fixes VSTS Bug 935202: System.NullReferenceException exception in

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentController.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentView.cs
MonoDevelop.SourceEditor.SourceEditorView.MonoDevelop.Ide.Editor.ITextEditorImpl.GrabFocus()
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/935392
Without a repro it's hard to tell where that happens. I added dispose
checks & a null check on different levels of the call. It's caused by
the document level - GrabFocus beeing called on a disposed editor.
Backport of #7993.
> [release-8.2] Fixes VSTS Bug 935392: System.NullReferenceException exception in

- main/src/addins/AspNet/WebForms/WebFormsTypeContext.cs
When opening and editing a WebForm.aspx file directly within the IDE (no project associated and loaded) this throws a NRE.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/935179
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/860971
> [aspnet] Prevents NRE when no project is loaded

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
stashes local changes but never pops the stash
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/901126
CommonPreMergeRebase changes the gitupdateoptions without that change
the local changes are not unstashed in the postmergerebase operation.
> Fixes VSTS Bug 901126: Updating from git w/ remote & local changes

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
stashes local changes but never pops the stash
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/901126
CommonPreMergeRebase changes the gitupdateoptions without that change
the local changes are not unstashed in the postmergerebase operation.
Backport of #7969.
> [release-8.2] Fixes VSTS Bug 901126: Updating from git w/ remote & local changes

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextEditorViewContent.cs
The controller for the old editor didn't properly synchronize the value of HasUnsavedChanges with the internal textEditor dirty flag.
This would cause normal saves of the model to perpetuate a state where the editor controller's HasUnsavedChanges flag would never get reset to true because the internal dirty state would have been kept back.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/936466
> Fixes VSTS #936466
> [Ide] Fix state corruption with new-document-model and old editor

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextEditorViewContent.cs
The controller for the old editor didn't properly synchronize the value of HasUnsavedChanges with the internal textEditor dirty flag.
This would cause normal saves of the model to perpetuate a state where the editor controller's HasUnsavedChanges flag would never get reset to true because the internal dirty state would have been kept back.
Fixes VSTS #936466
Backport of #8001.
/cc @sevoku @garuma
> [release-8.1] [Ide] Fix state corruption with new-document-model and old editor

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextEditorViewContent.cs
The controller for the old editor didn't properly synchronize the value of HasUnsavedChanges with the internal textEditor dirty flag.
This would cause normal saves of the model to perpetuate a state where the editor controller's HasUnsavedChanges flag would never get reset to true because the internal dirty state would have been kept back.
Fixes VSTS #936466
Backport of #8001.
/cc @sevoku @garuma
> [release-8.2] [Ide] Fix state corruption with new-document-model and old editor

- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/PopoverWindow.cs
MonoDevelop.MacIntegration.MacPlatformService.RemoveWindowShadow
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/930131
Hard to tell how that happened - but added some checks that should
prevent the exception.
Backport of #7968.
> [release-8.1] Fixes VSTS Bug 930131: [Watson] NullReferenceException in

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/DockContainer.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/MacSplitterWidget.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/SplitterGtkNSViewHostWidget.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/SplitterMacHostWidget.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/SplitterWidgetWrapper.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
This PR fixes the resize behaviour in dock containers when mouse is over native embed areas
To solve this, we had to deal with some problems:
- Create a MacSplitterWidget (because we need this view above the GTK layer to capture some mouse over events),
- Doesn't break GTK
- Capture and not let GTK swallow the mouse events 
- Introduces SplitterGtkNSViewHostWidget based in a new GtkNSViewHostWidget, this layer encapsules  the logic to handle drag logic between toolkits
In order not to break GTK,  I tried first to encapsule both backends and expose it over a wrapper class  SplitterWidgetWrapper with same interface.
In case of the cocoa backend, I created a native view (MacSplitterWidget) which GTK embeds into a SplitterGtkNSViewHostWidget extending from GtkNSViewHostWidget. This host …
> [release-8.1] Fixes resize dock containers in our dock system moving  SplitterWidget to native

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Extensions/FileNameEvalutor.cs
- main/tests/Ide.Tests/MonoDevelop.Ide/FileNameEvaluatorTests.cs
match
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/936228
The file name evaluator didn't take the full path - it only worked
with file name. Which is an unusual API. I changed it that it works
with full path as well so a future mis-use of the API is prevented.
> Fixes VSTS Bug 936228: Exact match and regex match mimetypes no longer

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.WelcomePage/IWelcomeWindowProvider.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.WelcomePage/WelcomePageService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Ide.cs
Adds EnsureInitializedAsync alternative method to wait the initialization from the Ide
This PR is necessary in: https://github.com/xamarin/md-addins/pull/4760
> [GetToCode] Adds EnsureInitializedAsync alternative method to wait the initialization from the Ide

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/DotNetCoreDevCertsTool.cs
Backport of #7916.
/cc @rodrmoya
> [release-8.2] [DotNetCore] Make DotNetCoreDevCertsTool public

- main/src/addins/AspNet/WebForms/WebFormsTypeContext.cs
When opening and editing a WebForm.aspx file directly within the IDE (no project associated and loaded) this throws a NRE.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/935179
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/860971
Backport of #8018.
> [release-8.2] [aspnet] Prevents NRE when no project is loaded

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Extensions/FileNameEvalutor.cs
- main/tests/Ide.Tests/MonoDevelop.Ide/FileNameEvaluatorTests.cs
match
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/936228
The file name evaluator didn't take the full path - it only worked
with file name. Which is an unusual API. I changed it that it works
with full path as well so a future mis-use of the API is prevented.
Backport of #8003.
/cc @mkrueger
> [release-8.2] Fixes VSTS Bug 936228: Exact match and regex match mimetypes no longer

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.WelcomePage/IWelcomeWindowProvider.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.WelcomePage/WelcomePageService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Ide.cs
Adds EnsureInitializedAsync alternative method to wait the initialization from the Ide
This PR is necessary in: https://github.com/xamarin/md-addins/pull/4855
Backport of #7771.
> [release-8.2] [GetToCode] Adds EnsureInitializedAsync alternative method to wait the initialization from the Ide

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/Properties/MonoDevelop.TextEditor.Cocoa.addin.xml
Removed `<Map` for Backspace command/key. So it’s not handled by MonoDevelop, hence its passed to native editor so `KeyDown` method is called which calls `InterpretKeyEvents` so native IME processing logic updates its internal state so IME input after typing more characters after Backspace is correct, otherwise IME reinserts deleted chars
> Fix 937834: In the new editor, the Chinese input repeats.

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/Properties/MonoDevelop.TextEditor.Cocoa.addin.xml
Removed `<Map` for Backspace command/key. So it’s not handled by MonoDevelop, hence its passed to native editor so `KeyDown` method is called which calls `InterpretKeyEvents` so native IME processing logic updates its internal state so IME input after typing more characters after Backspace is correct, otherwise IME reinserts deleted chars
Backport of #8040.
/cc @slluis @DavidKarlas
> [master] Fix 937834: In the new editor, the Chinese input repeats.

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/Properties/MonoDevelop.TextEditor.Cocoa.addin.xml
Removed `<Map` for Backspace command/key. So it’s not handled by MonoDevelop, hence its passed to native editor so `KeyDown` method is called which calls `InterpretKeyEvents` so native IME processing logic updates its internal state so IME input after typing more characters after Backspace is correct, otherwise IME reinserts deleted chars
Backport of #8040.
> [release-8.1] Fix 937834: In the new editor, the Chinese input repeats.

- main/Directory.Build.props
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpFormatter.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.OptionProvider/CSharpDocumentOptionsProvider.cs
- main/src/addins/MonoDevelop.SourceEditor2/VSEditor/TextEditorInitializationService.cs
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/TextViewContent.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/DefaultSourceEditorOptions.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextEditorViewContent.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/TextPolicyDocumentOptionsProvider.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.RoslynServices/RoslynServiceTests.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding.Refactoring/CSharpCodeActionEditorExtensionTests.cs
FYI @sandyarmstrong 
Updating roslyn to [2768eee](https://www.github.com/dotnet/roslyn/commit/2768eeeb2f449f768fe5233291dec940441b7f4f)
Changes since [09ead1c](https://www.github.com/dotnet/roslyn/commit/09ead1c8036683f2939e9bc22508a33c1ea6c8bd)
- [[master] Update dependencies from dotnet/arcade (#36651)](https://www.github.com/dotnet/roslyn/pull/36651)
- [Merge pull request #36671 from sharwell/update-analyzers-easy](https://www.github.com/dotnet/roslyn/pull/36671)
- [Merge pull request #36500 from ericmutta/patch-1](https://www.github.com/dotnet/roslyn/pull/36500)
- [added NFW to get some data on incremental parsing bug where source si. (#36620)](https://www.github.com/dotnet/roslyn/pull/36620)
- [Honor Disallow/AllowNull and Maybe/NotNull on properties …
> Bump Roslyn to 3.2.0-beta4-19324-01

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentManager.cs
Microsoft.VisualStudio.Text.SnapshotPoint..ctor()
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/935201
line.Start + Column - 1 will throw if Column is at EOL the - 1 is
interpreted as (Start + Column) - 1. Using brackets to evaluate it
differently : Start + (Column - 1) would fix the issue but I added the
bounds check to prevent the exeception from happening in all cases.
> Fixes VSTS Bug 935201: System.ArgumentOutOfRangeException exception in

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Tasks/CommentTasksProvider.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/936021
doc.Name is just the file name - the task list requires the full path.
> Fixes VSTS Bug 936021: "Go to Task" is broken in Tasks panel

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CSharpCompletionTextEditorExtension.cs
Add a OnlyOnRanRanToCompletion option and execute synchronously.
Fixes VSTS #798074 - Unobserved exception in CSharpCompletionTextEditorExtension
> [C#] Fix unhandled exception that is thrown when completion is canceled

- main/Directory.Build.props
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpFormatter.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.OptionProvider/CSharpDocumentOptionsProvider.cs
- main/src/addins/MonoDevelop.SourceEditor2/VSEditor/TextEditorInitializationService.cs
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/TextViewContent.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/DefaultSourceEditorOptions.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor/TextEditorViewContent.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/TextPolicyDocumentOptionsProvider.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.RoslynServices/RoslynServiceTests.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding.Refactoring/CSharpCodeActionEditorExtensionTests.cs
FYI @sandyarmstrong 
Updating roslyn to [2768eee](https://www.github.com/dotnet/roslyn/commit/2768eeeb2f449f768fe5233291dec940441b7f4f)
Changes since [09ead1c](https://www.github.com/dotnet/roslyn/commit/09ead1c8036683f2939e9bc22508a33c1ea6c8bd)
- [[master] Update dependencies from dotnet/arcade (#36651)](https://www.github.com/dotnet/roslyn/pull/36651)
- [Merge pull request #36671 from sharwell/update-analyzers-easy](https://www.github.com/dotnet/roslyn/pull/36671)
- [Merge pull request #36500 from ericmutta/patch-1](https://www.github.com/dotnet/roslyn/pull/36500)
- [added NFW to get some data on incremental parsing bug where source si. (#36620)](https://www.github.com/dotnet/roslyn/pull/36620)
- [Honor Disallow/AllowNull and Maybe/NotNull on properties …
> [release-8.2] Bump Roslyn to 3.2.0-beta4-19324-01

- main/src/tools/mdtool/mdtool.csproj
- main/src/tools/mdtool/src/mdtool.cs
This reverts commit 2299cacfc9b17f29f5a59c5663edd69b074965cd.
Opened PR to validate that VSTS is not reporting errors in test suites correctly:
https://devdiv.visualstudio.com/DevDiv/_apps/hub/ms.vss-releaseManagement-web.hub-explorer?releaseId=372751&_a=release-environment-extension&environmentId=1749792&extensionId=ms.vss-test-web.test-result-in-release-environment-editor-tab
```
MonoDevelop.CSharpBinding.CSharpCompletionTextEditorTests.TestVSTSBug564610
MonoDevelop.CSharpBinding.Tests.Features.Completion.ProtocolMemberCompletionTests.TestBug39428
```
Both currently fail in CI, but the status is reported as green. I suspect it's because we call terminate indiscriminately.
[725899](https://dev.azure.com/DevDiv/DevDiv/_workitems/edit/725899) did mention we need to call exit in non-normal …
> Revert "[mdtool] Call terminate when ending (#7982)"

- main/src/addins/MacPlatform/Dialogs/MacAlertDialogHandler.cs
[Mac] Correctly queue modal sheets
If you change the current branch outside of Monodevelop and certain files change then `ProjectOperations.AllowSave` will be called and it will display a sheet. Sometimes however, if multiple files change, the first sheet is shown, and the second is shown at the same time as a dialog.
The sheet is shown in `MacAlertDialogHandler` using `BeginSheet`
`BeginSheet` starts a modal sheet, but does it without changing the Runloop. To
block for a response we need to call `NSApplication.RunModalForWindow`.
It seems like when `RunModalForWindow` is called on a sheet, it does not stop processing the mainloop because when `AllowSave` still creates a second sheet. This sheet is then queued for showing once the first sheet is closed.
According to the documentation
> If …
> Fix queued sheets

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CSharpCompletionTextEditorExtension.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/Features/Completion/AbstractCSharpCompletionProviderTests.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/Features/Completion/ProtocolMemberCompletionTests.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding/CSharpCompletionTextEditorTests.cs
ProtocolCompletionProvider was called twice. Removed the redundant call.
> [CSharpBinding] Fixed failing editor tests.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/MDMenuItem.cs
The problem is:
```
MonoDevelop.Components.Commands.CommandManager.GetCommandInfo(Object,CommandTargetRoute,CancellationToken)
MonoDevelop.Components.Commands.CommandManager.GetCommandInfo(Object,CommandTargetRoute)
MonoDevelop.Components.Mac.MDMenuItem.Update(MDMenu,Int32&)
MonoDevelop.Components.Mac.MDMenu.UpdateCommands()
MonoDevelop.Components.Mac.MDMenu.MenuNeedsUpdate(NSMenu)
Gtk.Application.Run()
MonoDevelop.Ide.IdeStartup.Run(MonoDevelopOptions)
MonoDevelop.Ide.IdeStartup.Main(String[],IdeCustomizer)
```
However, I can not reproduce the issue. In the logs appear addins like MFractor, LiveXAML and others. I have tried with all installed without success.
> Fixes VSTS #935128
Backport of #8090.
> [release-8.2] [Shell] InvalidOperationException updating MDMenuItem

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs
in Mono.TextEditor.TextArea.FocusOut()
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/937031
FocusOut should never produce a fatal crash.
> Fixes VSTS Bug 937031: [FATAL] System.NullReferenceException exception

- main/src/addins/MonoDevelop.SourceEditor2/Mono.TextEditor/Gui/TextArea.cs
in Mono.TextEditor.TextArea.FocusOut()
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/937031
FocusOut should never produce a fatal crash.
Backport of #8068.
> [release-8.2] Fixes VSTS Bug 937031: [FATAL] System.NullReferenceException exception

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Tasks/CommentTasksProvider.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/936021
doc.Name is just the file name - the task list requires the full path.
Backport of #8041.
/cc @mkrueger
> [release-8.2] Fixes VSTS Bug 936021: "Go to Task" is broken in Tasks panel

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/MDMenuItem.cs
The problem is:
```
MonoDevelop.Components.Commands.CommandManager.GetCommandInfo(Object,CommandTargetRoute,CancellationToken)
MonoDevelop.Components.Commands.CommandManager.GetCommandInfo(Object,CommandTargetRoute)
MonoDevelop.Components.Mac.MDMenuItem.Update(MDMenu,Int32&)
MonoDevelop.Components.Mac.MDMenu.UpdateCommands()
MonoDevelop.Components.Mac.MDMenu.MenuNeedsUpdate(NSMenu)
Gtk.Application.Run()
MonoDevelop.Ide.IdeStartup.Run(MonoDevelopOptions)
MonoDevelop.Ide.IdeStartup.Main(String[],IdeCustomizer)
```
However, I can not reproduce the issue. In the logs appear addins like MFractor, LiveXAML and others. I have tried with all installed without success.
> Fixes VSTS #935128
> [Shell] InvalidOperationException updating MDMenuItem

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CSharpCompletionTextEditorExtension.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/Features/Completion/AbstractCSharpCompletionProviderTests.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/Features/Completion/ProtocolMemberCompletionTests.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding/CSharpCompletionTextEditorTests.cs
ProtocolCompletionProvider was called twice. Removed the redundant call.
Backport of #8092.
> [release-8.2] [CSharpBinding] Fixed failing editor tests.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/MDMenuItem.cs
The problem is:
```
MonoDevelop.Components.Commands.CommandManager.GetCommandInfo(Object,CommandTargetRoute,CancellationToken)
MonoDevelop.Components.Commands.CommandManager.GetCommandInfo(Object,CommandTargetRoute)
MonoDevelop.Components.Mac.MDMenuItem.Update(MDMenu,Int32&)
MonoDevelop.Components.Mac.MDMenu.UpdateCommands()
MonoDevelop.Components.Mac.MDMenu.MenuNeedsUpdate(NSMenu)
Gtk.Application.Run()
MonoDevelop.Ide.IdeStartup.Run(MonoDevelopOptions)
MonoDevelop.Ide.IdeStartup.Main(String[],IdeCustomizer)
```
However, I can not reproduce the issue. In the logs appear addins like MFractor, LiveXAML and others. I have tried with all installed without success.
> Fixes VSTS #935128
Backport of #8090.
> [release-8.1] [Shell] InvalidOperationException updating MDMenuItem

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpParser.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpSyntaxMode.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/MDLanguageService.fs
Fixes VSTS #939713
Semantic highlighting was not working at all. Only regex highlighting was being used.
> Fix F# semantic highlighting

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpParser.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpSyntaxMode.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/MDLanguageService.fs
Fixes VSTS #939713
Semantic highlighting was not working at all. Only regex highlighting was being used.
> [release-8.1] Fix F# semantic highlighting

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpParser.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpSyntaxMode.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/MDLanguageService.fs
Fixes VSTS #939713
Semantic highlighting was not working at all. Only regex highlighting was being used.
Backport of #8109.
/cc @nosami
> [release-8.2] Fix F# semantic highlighting

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Tasks/CommentTasksProvider.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/936021
doc.Name is just the file name - the task list requires the full path.
Backport of #8041.
> [release-8.1] Fixes VSTS Bug 936021: "Go to Task" is broken in Tasks panel

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/TextViewContent.cs
This is an attempt to fix Null Reference Exceptions that happen when `TextViewContent` is disposed.
There were two potential cases where this would have potentially happened, one, where `sourceEditorOptions` was null, and second, when `TextView` was null in the call to `TextView.Options`.
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/935137/
> Fixes VSTS 935137: Null Reference Exceptions when disposing TextViewContent

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentManager.cs
In some cases (like a deletion of code from the document, then trying to double click an existing Search Result), this method might have been called with a line number that no longer exists. This resulted in a call to the API that threw an exception. Now, the method checks the line count in the snapshot, and aborts. Both cases (a graceful failure, and an exception) are logged, so we can see if this continues to happen.
I was able to repro the steps to get the exception, but I couldn’t repro a crash of the IDE:
1. Have a class with a field, reference that field in a bunch of places
1. Select Find References, and keep the results
1. Delete most of the document, save it, and close it
1. Double click a reference
> Fixes VSTS 917028: Calling ScrollToRequestedCaretLocation with an invalid line number caused an exception

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
The previous logic relied on the new Roslyn text deriving from the old Roslyn text via a chain of changes. We have seen a case in XAML where an extra change came from somewhere, deleting a random character. The change couldn't be explained by diffing between the old text and the new text.
The right thing to do here (and that's what VS Windows does) is to just give the desired new text to the Editor and let the Editor diff it. We pass the ComputeMinimalChange option so the editor will arrive at a minimal set of correct edits without Roslyn help.
We shouldn't worry about performance here because it's an infrequent scenario and the editor is really good at diffing efficiently, and the files of average size aren't a concern in terms of allocating the string.
> Fix the workspace logic to apply new text to a buffer.

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Debugger/CSharpBreakpointSpanResolver.cs
I also added logic to fallback to whole line breakpoint in case Roslyn fails to find matching statement to place breakpoint on.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/935181/
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/935126/
> Fix 935181: TryGetBreakpointSpan called with invalid position

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/TextViewContent.cs
This is an attempt to fix Null Reference Exceptions that happen when `TextViewContent` is disposed.
There were two potential cases where this would have potentially happened, one, where `sourceEditorOptions` was null, and second, when `TextView` was null in the call to `TextView.Options`.
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/935137/
Backport of #8097.
> [release-8.2] Fixes VSTS 935137: Null Reference Exceptions when disposing TextViewContent

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/ExtensibleTreeView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/ShowAllFilesBuilderExtension.cs
reference exception
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/776934
Setting the store to null after the node builders are destoyed should
fix the issue theoretically. I couldn't reproduce it on my machine so
I added some insanity checks in the event handlers as well.
> Fixes VSTS Bug 776934: TreeBuilderContext.GetTreeBuilder() null

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/ExtensibleTreeView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/ShowAllFilesBuilderExtension.cs
reference exception
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/776934
Setting the store to null after the node builders are destoyed should
fix the issue theoretically. I couldn't reproduce it on my machine so
I added some insanity checks in the event handlers as well.
Backport of #8087.
> [release-8.2] Fixes VSTS Bug 776934: TreeBuilderContext.GetTreeBuilder() null

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentManager.cs
Microsoft.VisualStudio.Text.SnapshotPoint..ctor()
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/935201
line.Start + Column - 1 will throw if Column is at EOL the - 1 is
interpreted as (Start + Column) - 1. Using brackets to evaluate it
differently : Start + (Column - 1) would fix the issue but I added the
bounds check to prevent the exeception from happening in all cases.
Backport of #8036.
> [release-8.2] Fixes VSTS Bug 935201: System.ArgumentOutOfRangeException exception in

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentManager.cs
In some cases (like a deletion of code from the document, then trying to double click an existing Search Result), this method might have been called with a line number that no longer exists. This resulted in a call to the API that threw an exception. Now, the method checks the line count in the snapshot, and aborts. Both cases (a graceful failure, and an exception) are logged, so we can see if this continues to happen.
Original PR: #8105
> [Backport] Fixes VSTS 917028: Calling ScrollToRequestedCaretLocation with an invalid line number caused an exception

- main/src/addins/MonoDevelop.HexEditor/Mono.MHex/HexEditor.cs
- main/src/addins/MonoDevelop.HexEditor/Mono.MHex/HexEditorDebugger.cs
in Mono.MHex.HexEditor.Dispose()
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/942353
Can't really determine the cause - Options should always be != null
but it's the only thing that can throw a null ref exception. But in
any case Dispose shouldn't cause a fatal exception.
> Fixes VSTS Bug 942353: [FATAL] System.NullReferenceException exception

- main/src/addins/MonoDevelop.HexEditor/Mono.MHex/HexEditor.cs
- main/src/addins/MonoDevelop.HexEditor/Mono.MHex/HexEditorDebugger.cs
in Mono.MHex.HexEditor.Dispose()
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/942353
Can't really determine the cause - Options should always be != null
but it's the only thing that can throw a null ref exception. But in
any case Dispose shouldn't cause a fatal exception.
Backport of #8135.
/cc @mkrueger
> [release-8.2] Fixes VSTS Bug 942353: [FATAL] System.NullReferenceException exception

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpFormattingProfileDialog.cs
In Preferences - Source Code - Code Formatting - C# when the Edit
button was clicked in the Format tab the IDE would crash. The problem
was that the dialog being displayed was being used as its own parent
in MessageService. Which was causing a stack overflow.
```
Stack overflow: IP: 0x7fff57f71b9c, fault addr: 0x7ffeed8e6ff8
Stacktrace:
at AppKit.NSWindow.AddChildWindow (AppKit.NSWindow,AppKit.NSWindowOrderingMode) [0x00032] in /Library/Frameworks/Xamarin.Mac.framework/Versions/5.14.0.83/src/Xamarin.Mac/AppKit/NSWindow.g.cs:2089
<...>
at MonoDevelop.Ide.MessageService.ShowCustomModalDialog (Gtk.Window,MonoDevelop.Components.Window) [0x00042] in /Users/vsts/agent/2.153.2/work/1/s/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/MessageService.cs:398
at …
```
> [CSharpBinding] Fix crash on opening C# format profile dialog

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Formatting/CSharpFormattingProfileDialog.cs
In Preferences - Source Code - Code Formatting - C# when the Edit
button was clicked in the Format tab the IDE would crash. The problem
was that the dialog being displayed was being used as its own parent
in MessageService. Which was causing a stack overflow.
```
Stack overflow: IP: 0x7fff57f71b9c, fault addr: 0x7ffeed8e6ff8
Stacktrace:
at AppKit.NSWindow.AddChildWindow (AppKit.NSWindow,AppKit.NSWindowOrderingMode) [0x00032] in /Library/Frameworks/Xamarin.Mac.framework/Versions/5.14.0.83/src/Xamarin.Mac/AppKit/NSWindow.g.cs:2089
<...>
at MonoDevelop.Ide.MessageService.ShowCustomModalDialog (Gtk.Window,MonoDevelop.Components.Window) [0x00042] in /Users/vsts/agent/2.153.2/work/1/s/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/MessageService.cs:398
at …
```
> [release-8.2] [CSharpBinding] Fix crash on opening C# format profile dialog

- main/src/addins/MacPlatform/MacPlatform.cs
It turns out the answer to
// FIXME: could this block in rare cases?
was "No, it blocks every time", so make the delegate async and await on the call instead.
Also remove the old Carbon handler and move the important bits into the Cocoa handler instead as it hasn't been deprecated for at least a decade
Fixes VSTS #942401
> [Mac] Don't hang when terminating through the dock icon

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Completion/CSharpCompletionTextEditorExtension.cs
Add a OnlyOnRanRanToCompletion option and execute synchronously.
Fixes VSTS #798074 - Unobserved exception in CSharpCompletionTextEditorExtension
Backport of #8033.
/cc @Therzok
> [release-8.2] [C#] Fix unhandled exception that is thrown when completion is canceled

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/VPanedThin.cs
Each time the StatusView is opened, we get the following exception.Seems to be a problem related to Splitter initialization.
```
Stack trace: 
at MonoDevelop.Ide.Gui.GLibLogging.LoggerMethod (System.IntPtr logDomainPtr, MonoDevelop.Ide.Gui.GLibLogging+LogLevelFlags logLevel, System.IntPtr messagePtr) [0x00039] in /Users/jsuarezruiz/Projects/MonoDevelop/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/GLibLogging.cs:259 
at MonoDevelop.Ide.Gui.GLibLogging+Log+<>c.<.cctor>b__23_0 (System.IntPtr domain, MonoDevelop.Ide.Gui.GLibLogging+LogLevelFlags level, System.IntPtr message, MonoDevelop.Ide.Gui.GLibLogging+LogFunc user_data) [0x00001] in /Users/jsuarezruiz/Projects/MonoDevelop/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/GLibLogging.cs:103 
at …
```
> [Version Control] Fix exception opening the StatusView

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/VPanedThin.cs
Each time the StatusView is opened, we get the following exception.Seems to be a problem related to Splitter initialization.
```
Stack trace: 
at MonoDevelop.Ide.Gui.GLibLogging.LoggerMethod (System.IntPtr logDomainPtr, MonoDevelop.Ide.Gui.GLibLogging+LogLevelFlags logLevel, System.IntPtr messagePtr) [0x00039] in /Users/jsuarezruiz/Projects/MonoDevelop/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/GLibLogging.cs:259 
at MonoDevelop.Ide.Gui.GLibLogging+Log+<>c.<.cctor>b__23_0 (System.IntPtr domain, MonoDevelop.Ide.Gui.GLibLogging+LogLevelFlags level, System.IntPtr message, MonoDevelop.Ide.Gui.GLibLogging+LogFunc user_data) [0x00001] in /Users/jsuarezruiz/Projects/MonoDevelop/monodevelop/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/GLibLogging.cs:103 
at …
```
> [release-8.2] [Version Control] Fix exception opening the StatusView

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/TextViewContent.cs
* Don't show column rulers if user has them disabled, regardless of any setting in `.editorconfig` files
* Always initialize options from MonoDevelop policy system when handling editorconfig change events
> TextViewContent: Fix some issues with column ruler display

- main/src/addins/MacPlatform/Dialogs/MacSelectFileDialogHandler.cs
a url's path property might be null if the referenced resource no longer exists
Fixes VSTS #940763
> [Mac] Check if the Url path is null

- main/src/addins/MacPlatform/MainToolbar/MainToolbar.cs
- main/src/addins/MacPlatform/MainToolbar/SearchBar.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/CommandSearchCategory.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/IMainToolbarView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbar.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbarController.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/SearchPopupWindow.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/SearchResult.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/PlatformService.cs
In fullscreen Cocoa stops delivering performKeyEquivalent messages to the
SearchBar which breaks handling of cursor keys and similar. Instead of using
it, use our own delegate to catch control:textView:doCommandBySelector: and
create a command from the selector.
Fixes VSTS #937857
> [Mac] Fix keyboard input in Global Search when in fullscreen

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeActionEditorExtension.cs
```
ERROR [2019-07-03 23:58:10Z]: An unhandled exception has occurred. Terminating Visual Studio? False
at MonoDevelop.CodeActions.CodeActionEditorExtension+<>c__DisplayClass14_1.<GetCurrentFixesAsync>b__2 () [0x00000] in /Users/vsts/agent/2.153.2/work/1/s/monodevelop/main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeActionEditorExtension.cs:161
at (wrapper delegate-invoke) System.Func`1[System.Collections.Immutable.ImmutableArray`1[Microsoft.CodeAnalysis.CodeFixes.CodeFixCollection]].invoke_TResult()
at MonoDevelop.Core.Runtime+<>c__44`1[T].<RunInMainThread>b__44_0 (System.Object state) [0x00013] in /Users/vsts/agent/2.153.2/work/1/s/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop. …
```
> [C#] Fix crasher in code actions in the old editor

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AtkCocoaHelper/AtkCocoaHelperMac.cs
> [A11y] Check for selector before trying to call accessibility method

- main/src/addins/MacPlatform/Dialogs/MacSelectFileDialogHandler.cs
a url's path property might be null if the referenced resource no longer exists
Fixes VSTS #940763
Backport of #8183.
/cc @iainx
> [release-8.2] [Mac] Check if the Url path is null

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/TextViewContent.Commands.cs
The IDE side of wiring up Sort and Join Lines.
Needs a VSEA sync and VSEC bump that includes https://github.com/xamarin/vs-editor-core/pull/358. 
- a mixture of normal and box selections when joining/merging lines results in some _wonky_ text as the result
- a boxed selection is not correctly restored when sorting the lines
- This should use the commanding approach that we use for most other things
- Fixes https://vsmac.dev/832745
- Fixes https://vsmac.dev/937869
- Fixes https://vsmac.dev/918951
> Fixes 832745, 937869, 918951 - Implement Sort and Join Lines

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/UrlBasedRepositoryEditor.cs
WITHOUT a port?
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/938346
Port -1 is now the value to omit the port in the uri.
> Fixes VSTS Bug 938346: [Feedback] How to use subverision over svn+ssh

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSystemInformation.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/934237
> [dotnetcore] Uses DotNetCoreSdkPaths resolver instead of DotNetCoreSdk

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValueTreeView.cs
A bit of a long shot, but it should/could fix the NRE here. We fixed one possible NRE with DisplayValue but we see the same error since that fix. The offset is +0 so I'm thinking that it's early in the method and the only thing I can think of here is that Get_Model is not returning the store from Gtk. We can use store here in its place since they are (or should be) the same object.
Fixes VSTS 849589
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/849589
> [debugger] Use store instead of Model

- main/build/MacOSX/monostub-utils.h
Fixes VSTS #935540 - Subversion addin could not load libsvn_client, so it will be disabled.
> Fix svn probe in Xcode.app

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValueTreeView.cs
A bit of a long shot, but it should/could fix the NRE here. We fixed one possible NRE with DisplayValue but we see the same error since that fix. The offset is +0 so I'm thinking that it's early in the method and the only thing I can think of here is that Get_Model is not returning the store from Gtk. We can use store here in its place since they are (or should be) the same object.
Fixes VSTS 849589
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/849589
Backport of #8171.
/cc @slluis @sgmunn
> [release-8.2] [debugger] Use store instead of Model

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/WorkbenchStatusBar.cs
file
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/941853
The BeginProgress API is the cause of that - IconID can beconverted to
a string. Other calls of that method are ok.
> Fixes VSTS Bug 941853: Unknown icon shown in status bar when opening a

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/BlameWidget.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/ComparisonWidget.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/EditorCompareWidgetBase.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/BlameCommand.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/DefaultBlameViewHandler.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/DefaultDiffViewHandler.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/DefaultMergeViewHandler.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/DiffCommand.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/MergeCommand.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlCommandHandler.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlDocumentController.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/940831
Blame/Diff now works without an text editor attached. The default view
handlers hide the diff/blame/merge view and commands because they need
the current text from somewhere - that's done through the ITextBuffer
API which needs to be provided by the document controller. But for
read-only views it would be possible to use these commands with
potential custom view handlers that enable these controllers on
specific view contents.
> Fixes VSTS Bug 940831: "Authors" (Blame) tab fails to load

- main/src/addins/MacPlatform/Dialogs/MacAlertDialogHandler.cs
- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/addins/MacPlatform/MacProxyCredentialProvider.cs
SharedApplication.ApplicationIconImage is not meant to be used
to retrieve the actual bundle icon, but only to change the default icon.
Instead of SharedApplication.ApplicationIconImage get the icon
directly from the bundle by default and fall-back to BrandingService
if not running from an app bundle.
Fixes VSTS #905844
> [Mac] Fix NSImageCacheException exception when getting the app icon

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorPrintOperation.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/820341
The only way to ensure that the theme can be printed in a good quality
is to use the default light theme for printing. The same with the font
size - it used to be the editor zoom factor but setting it to a
constant zoom facotr gives the print code the control over the size.
Fonts currently are way bigger than they should be in printing.
> Fixed Bug 820341: [Feedback] Unable to print code

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/BlameCommand.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/DiffCommand.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/943824
Fixes VSTS Bug 946944: [Feedback] Diff Incorrect
Diff View could be loaded before the text view had the text - that
caused that the "local" text was empty. The blame view had the same
issue (but crashed) - fixed that as well.
> Fixes VSTS FeedbackTicket 943824: Diff Incorrect

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreExecutionCommand.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreExecutionHandler.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreExecutionCommand.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreExecutionHandler.cs
Instead of duplicating code, just make the ExecutionHandler's call
the specific Command implementation of its PostLaunch logic.
> [DotNetCore] Allow *Command's to provide post launch operations

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentManager.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/RootWorkspace.cs
Avoid enumerating GetAllItems for each open document
This should fix some performance issue when closing a decently sized workspace with 20 open documents and 2 solutions.
> [Ide] Small cleanup and optimization in RootWorkspace

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/ExtensibleTextEditor.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/948635
EditorExtension no longer works on that level - it's moved to IDE
TextEditor for handling. Using the TextEditor from the document is
safer.
> Fixes VSTS Bug 948635: [Feedback] Tab doesn't work in text files

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AtkCocoaHelper/AtkCocoaHelperMac.cs
Check accessibilityServesAsTitleForUIElements selector is available
for UI element when trying to remove the accessibility element
from the title.
Unhandled ObjC Exception
MonoDevelop.MacIntegration.MacPlatformService+MarshalledObjCException: NSInvalidArgumentException: -[ACAccessibilityElement accessibilityServesAsTitleForUIElements:]: unrecognized selector sent to instance
at MonoDevelop.Components.Mac.Messaging:IntPtr_objc_msgSend <0x00111>
at MonoDevelop.Components.AtkCocoaHelper.AtkCocoaMacExtensions:RemoveElementFromTitle <0x0027a>
at MonoDevelop.Ide.WelcomePage.WelcomePageSection:RemoveAccessibiltyTitledWidget <0x0018a>
at MonoDevelop.Ide.WelcomePage.WelcomePageRecentProjectsList:RecentFilesChanged <0x00282>
at …
> [A11y] Check selector before trying to call accessibility method

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/InfoBar.cs
* Align all buttons to the right side
* Align the first hyperlink item to the end of the text
* Fix jumping buttons on window resize
Screencast (this is just an example based on existing code):
Fixes VSTS #948301
> [Ide] Fix InfoBar button alignments

- main/src/addins/MacPlatform/Dialogs/MacAlertDialogHandler.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/MessageService.cs
Adds an optional `MessageDescription.HelpUrl`, depending on the platform a special help button will be shown in the message dialog, which will open the given Url in the browser. For now only on Mac, since Gtk has no special Help button in dialogs (needs design) and we have no native WPF impl. for windows.
> [Ide][Mac] Add Help button support to MessageService

- main/src/addins/MonoDevelop.UnitTesting.NUnit/NUnit3Runner/NUnitTestRunner.cs
Support assemblies should always be used if they have already
been loaded.
Fixes UI tests when running locally.
> Use support assemblies when trying to resolve

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/ExtensibleTextEditor.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/948635
EditorExtension no longer works on that level - it's moved to IDE
TextEditor for handling. Using the TextEditor from the document is
safer.
Backport of #8231.
/cc @mkrueger
> [release-8.2] Fixes VSTS Bug 948635: [Feedback] Tab doesn't work in text files

- main/src/addins/MacPlatform/Dialogs/MacAlertDialogHandler.cs
- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/addins/MacPlatform/MacProxyCredentialProvider.cs
SharedApplication.ApplicationIconImage is not meant to be used
to retrieve the actual bundle icon, but only to change the default icon.
Instead of SharedApplication.ApplicationIconImage get the icon
directly from the bundle by default and fall-back to BrandingService
if not running from an app bundle.
Fixes VSTS #905844
Backport of #8213.
/cc @sevoku
> [release-8.2] [Mac] Fix NSImageCacheException exception when getting the app icon

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AtkCocoaHelper/AtkCocoaHelperMac.cs
Fixes VSTS #940756
Backport of #8180.
/cc @iainx
> [release-8.2] [A11y] Check for selector before trying to call accessibility method

- main/tests/MacPlatform.Tests/MacPlatformTest.cs
Forgot to add this to https://github.com/mono/monodevelop/pull/8234
> [MacPlatform] Add test for browsers retrieval via GetApplications

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.ClassOutline/CSharpOutlineTextEditorExtension.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.ClassOutline/CSharpOutlineTextEditorExtensionProvider.cs
Wiring the change handlers for Document Outline control.
Fixes https://vsmac.dev/948416/.
> Fixes VSTS 948416: Document Outline does not refresh

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.OptionPanels/CompletionOptionsPanel.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices.Options/RoslynPreferences.cs
In the new editor (as on Windows), this is controlled at the language
service level, not the editor level. So, just like with
"Show import items", it should really be a per-language setting.
Just like with "Show import items", set the C#-specific preference
along with the global preference. This does not address the problem for
other languages that default to new editor (like XAML and AXML).
Note that the associated `ConfigurationProperty` is initialized lazily,
because otherwise its dependency on `DefaultSourceEditorOptions` leads
to a circular initialization dependency and hangs the IDE.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/950309
> Editor: Respect pref to not show completion window while typing

- main/msbuild/MDBuildTasks/MDBuildTasks.csproj
`msbuild -t:Pack -p:Configuration=Debug -p:TargetFramework=net472` fails
> [MSBuild] Bump MSBuild Tasks to target .NET 4.7.2

- main/Directory.Build.props
- main/msbuild/ReferencesVSEditor.Mac.props
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.csproj
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/MonoDevelop.TextEditor.Cocoa.csproj
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Wpf/MonoDevelop.TextEditor.Wpf.csproj
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/MonoDevelop.TextEditor.csproj
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
This should make it easier for us to have all vs-editor-api references
point to vs-editor-core when available. There are some blockers to that
change, so for now just take this one preparatory step.
> Build: Use a property to access the vs-editor-api directory

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/TextViewContent.cs
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/TextViewImports.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/ViewCommandHandlers.cs
I’ve modified the way the editor reacts to Toggle Folding/Outlining.
We used to rely on the command being remapped to a handler in VSEC, but that caused a few additional problems, like the menu text not always being in sync. 
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/950315/
> Fixes VSTS 950315: Code Folding menu toggle does not work in new editor 

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/WorkbenchStatusBar.cs
file
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/941853
The BeginProgress API is the cause of that - IconID can beconverted to
a string. Other calls of that method are ok.
Backport of #8208.
> [release-8.2] Fixes VSTS Bug 941853: Unknown icon shown in status bar when opening a

- main/src/addins/MacPlatform/MainToolbar/MainToolbar.cs
- main/src/addins/MacPlatform/MainToolbar/SearchBar.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/CommandSearchCategory.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/IMainToolbarView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbar.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbarController.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/SearchPopupWindow.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/SearchResult.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/PlatformService.cs
In fullscreen Cocoa stops delivering performKeyEquivalent messages to the
SearchBar which breaks handling of cursor keys and similar. Instead of using
it, use our own delegate to catch control:textView:doCommandBySelector: and
create a command from the selector.
Fixes VSTS #937857
Backport of #8111.
/cc @iainx
> [release-8.2] [Mac] Fix keyboard input in Global Search when in fullscreen

- main/build/MacOSX/monostub-utils.h
Fixes VSTS #935540 - Subversion addin could not load libsvn_client, so it will be disabled.
Backport of #8155.
/cc @sevoku @Therzok
> [release-8.2] Fix svn probe in Xcode.app

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeActionEditorExtension.cs
```
ERROR [2019-07-03 23:58:10Z]: An unhandled exception has occurred. Terminating Visual Studio? False
at MonoDevelop.CodeActions.CodeActionEditorExtension+<>c__DisplayClass14_1.<GetCurrentFixesAsync>b__2 () [0x00000] in /Users/vsts/agent/2.153.2/work/1/s/monodevelop/main/src/addins/MonoDevelop.Refactoring/MonoDevelop.CodeActions/CodeActionEditorExtension.cs:161
at (wrapper delegate-invoke) System.Func`1[System.Collections.Immutable.ImmutableArray`1[Microsoft.CodeAnalysis.CodeFixes.CodeFixCollection]].invoke_TResult()
at MonoDevelop.Core.Runtime+<>c__44`1[T].<RunInMainThread>b__44_0 (System.Object state) [0x00013] in /Users/vsts/agent/2.153.2/work/1/s/monodevelop/main/src/core/MonoDevelop.Core/MonoDevelop. …
```
> [release-8.2] [C#] Fix crasher in code actions in the old editor

- main/Directory.Build.props
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.PackageInstaller/PackageInstallerService.cs
Changes since [7d47461](https://www.github.com/dotnet/roslyn/commit/7d47461):
- [Merge pull request #37416 from jnm2/sort_traits_features](https://www.github.com/dotnet/roslyn/pull/37416)
- [Remove naming styles before generating field/property/parameter in constructor related refactorings (#36220)](https://www.github.com/dotnet/roslyn/pull/36220)
- [Merge pull request #37403 from dotnet/dev/jorobich/publish-dotnet-format](https://www.github.com/dotnet/roslyn/pull/37403)
- [Update dependencies from https://github.com/dotnet/arcade build 20190719.2 (#37393)](https://www.github.com/dotnet/roslyn/pull/37393)
- [Merge pull request #37149 from ryzngard/issue/33287_generateconstructorwithdialog_vb](https://www.github.com/dotnet/roslyn/pull/37149)
- [Include netstandard2.1 in the set of default …
> Bump Roslyn to 3.3.0-beta2-19374-02

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/BreakpointManager.cs
Just like line numbers, column numbers are also 1-based, but when
calculating the byte position, we need to adjust for 0-based indexes.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/917922/
> [Debugger] Fixed toggling of breakpoints at the end of a line

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git.Tests/MonoDevelop.VersionControl.Git.Tests.csproj
LibGit2Sharp is failing to load in the unit tests. Not marking it as a local copy reference seems to fix it.
Fixes VSTS #958036
> Make LibGit2Sharp not a local reference in the test project

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Ide.cs
The IdeApp.DispatchIdleActions method is sometimes called just after startup.
When that happens, if the user has not had any interaction with the ide,
the CommandService.LastUserInteration property will have the default DateTime
value. The old code was substracting that value from the current time, which
would be a huge amount of milliseconds, and would overflow when converting
to int. It all would result with DispatchIdleActions being called over and over
with a negative number, finally causing a stack overflow.
Fixes VSTS #958148
> Fix stack overflow at startup

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/Ide.cs
The IdeApp.DispatchIdleActions method is sometimes called just after startup.
When that happens, if the user has not had any interaction with the ide,
the CommandService.LastUserInteration property will have the default DateTime
value. The old code was substracting that value from the current time, which
would be a huge amount of milliseconds, and would overflow when converting
to int. It all would result with DispatchIdleActions being called over and over
with a negative number, finally causing a stack overflow.
Fixes VSTS #958148
Backport of #8309.
/cc @slluis
> [release-8.2] Fix stack overflow at startup

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/DefaultBlameViewHandler.cs
the new editor
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/952599
The base class of the new editor has changed so it no longer works.
Checking the file model is the faster solution in any case.
> Fixes VSTS Bug 952599: Version control document views are missing with

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
KeyBindingManager.Commands can return null, so handle a null return. Wrap the
call to ProcessKeyEventCore in a try catch block to make sure we handle and log
any other possible problems with it.
Fixes VSTS #944669
> [IDE] Handle bindings returning null commands

- main/build/MacOSX/monostub.mm
App bundle will not start unless Mono 6.4.0.94 or later is installed.
Xamarin.Mac 5.16 depends requires Mono 6.4.0.94 or later.
Visual Studio failed to start. Some of the assemblies required to run Visual Studio (for example gtk-sharp)may not be properly installed in the GAC.
System.Exception: Toolkit could not be loaded ---> System.NotSupportedException: This version of Xamarin.Mac requires Mono 6.4.0.94, but found Mono 6.0.0.311.
at ObjCRuntime.Runtime.VerifyMonoVersion () [0x000b1] in /Library/Frameworks/Xamarin.Mac.framework/Versions/5.16.1.0/src/Xamarin.Mac/ObjCRuntime/Runtime.mac.cs:153
Fixes VSTS #953417 - No error message when running VS Mac with
unsupported Mono version
> [build] Update min Mono version to 6.4.0.94

- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/AssemblyBrowserWidget.cs
System.Threading.Tasks.Task.WhenAll[PEFile]()
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/944655
That exact crash shouldn't happen anymore in the current version
(definitions is now an ImmutableList and never null) but a crash at
that point should not crash the IDE in any case.
> Fixes VSTS Bug 944655: [FATAL] System.ArgumentException exception in

- main/Directory.Build.props
- main/msbuild/RoslynVersion.props
This makes it easier to `Import` elsewhere (say, submodules or other repos with their own `Directory.Build.props`) so that Roslyn version can be more easily unified in IDE components.
> Build: Move Roslyn version to separate props file

- main/build/MacOSX/Entitlements.plist
- main/build/MacOSX/Makefile.am
With the hardened runtime, we now need to specify the paths of all libraries
that are dlopened in the binary's rpath
> [MacOS] Specify dlopen library paths

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/Properties/MonoDevelop.TextEditor.Cocoa.addin.xml
- main/src/core/MonoDevelop.Ide/ExtensionModel/Commands.addin.xml
- main/src/core/MonoDevelop.Ide/ExtensionModel/MainMenu.addin.xml
1. Rename "Use Selection for *" commands to have proper macOS labels
2. Move cmd+e keybinding from `FindNextSelection` command to
`UseSelectionForFind`.
3. Add `UseSelectionForFind` command to main menu.
4. Add support for missing find commands to new editor.
It's unfortunate that we have two similar commands here but it's
important that cmd+e behaves as the user expects (it should not have
"find next" behavior...it just sets search text and keeps focus in
editor).
Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/947125
>  TextEditor: "Use Selection for Find" fixes

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CustomTools/CustomToolService.cs
If an exception is thrown by a custom tool then this may result in
an unobserved task exception. The exception is set on a task
completion source whose task is only observed if a build is waiting
for custom tools to complete or another custom tool is run again for
the same file.
There does not seem to be any need to set the exception on the task
completion source since all errors are reported in the IDE and
callers of the CustomToolService Update or UpdateAsync do not get
access to this task. Now the task completion source has its result
set instead of setting the exception since the only thing needed is
to ensure the task is completed.
Fixes VSTS #958223 - System.Threading.Tasks.TaskCanceledException exception
in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess()
> [Ide] Fix unobserved task exception in CustomToolService

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/Styles.cs
Set the foreground color to be the correct foreground color in style. Solve the white text on white background issue for Exception Caught Window. (Works with both light and dark theme)
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/961237
> [Project Model] Fix the text color issue in the Exception Caught Window

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.CustomTools/CustomToolService.cs
If an exception is thrown by a custom tool then this may result in
an unobserved task exception. The exception is set on a task
completion source whose task is only observed if a build is waiting
for custom tools to complete or another custom tool is run again for
the same file.
There does not seem to be any need to set the exception on the task
completion source since all errors are reported in the IDE and
callers of the CustomToolService Update or UpdateAsync do not get
access to this task. Now the task completion source has its result
set instead of setting the exception since the only thing needed is
to ensure the task is completed.
Fixes VSTS #958223 - System.Threading.Tasks.TaskCanceledException exception
in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess()
Backport …
> [release-8.2] [Ide] Fix unobserved task exception in CustomToolService

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/ActionCommand.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/CommandSearchCategory.cs
This will help surface IDE commands higher than those coming from addins, which is helpful when the addins don't follow convention or create the same commands under new ids (i.e. Format Document).
This is an example of how the WebAddin contributes commands that somehow overpower the Format Document command we surface. I feel we should rank _internal_ ones higher. 
This will surface with users when this is merged: https://github.com/mono/monodevelop/pull/8323
> Artificially rank the commands from the current add-in higher in Navigate To

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/RoslynHelpers.fs
- main/msbuild/RoslynVersion.props
Changes since [e4e7c09](https://www.github.com/dotnet/roslyn/commit/e4e7c09):
- [Make Microsoft.CodeAnalysis.Analyzers reference conditional in╬ô├ç┬¬ (#37619)](https://www.github.com/dotnet/roslyn/pull/37619)
- [Merge pull request #37600 from petrroll/release/dev16.3-preview2](https://www.github.com/dotnet/roslyn/pull/37600)
- [Merge pull request #37623 from mavasani/FixTypingCrash](https://www.github.com/dotnet/roslyn/pull/37623)
- [Merge pull request #37620 from dotnet/release/dev16.2](https://www.github.com/dotnet/roslyn/pull/37620)
- [Merge pull request #37534 from dotnet/dev/jorobich/update-dependencies](https://www.github.com/dotnet/roslyn/pull/37534)
- [Handle checking for language version in speculative semantic model (#37513) …
> Bump Roslyn to 3.3.0-beta2-19401-05

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/Properties/MonoDevelop.TextEditor.addin.xml
This is the Monodevelop side of https://github.com/xamarin/vs-editor-core/pull/380.
It simply reconciles the difference Go To Brace command arguments that we use, and uses the same ones that VS-Platform introduced.
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/941510
> Fixes 941510: Reconcile GoToMatchingBraceCommandArgs with GoToBraceCommandArgs

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
KeyBindingManager.Commands can return null, so handle a null return. Wrap the
call to ProcessKeyEventCore in a try catch block to make sure we handle and log
any other possible problems with it.
Fixes VSTS #944669
Backport of #8235.
> [release-8.2] [IDE] Handle bindings returning null commands

- main/build/MacOSX/Entitlements.plist
Add entitlements to allow MonoDevelop to use AppleScript and debug apps
> [Mac] Add some more entitlements

- main/src/core/MonoDevelop.Ide/ExtensionModel/Commands.addin.xml
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/ProjectCommands.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/FolderNodeBuilder.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/ProjectPadContextMenu.addin.xml
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ProjectOperations.cs
Create shortcut for New Class... from the folder context-menu within the solution pad. From the Add menu, if New Class... is clicked, in the New File dialog, General | Empty Class is always selected.
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/643343
> [Project Model] Shortcut for add new class in C# projects

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Project/CompilerOptionsPanelWidget.cs
Allow users to set Preview in the C# compiler options panel, which
had previously been disabled as part of #816208.
Fixes VSTS #950743
> [CSharp] Enable Preview

- main/src/core/MonoDevelop.Ide/ExtensionModel/StockIcons.addin.xml
Also filed https://devdiv-design.visualstudio.com/D3%20Studio/_workitems/edit/7661
to get a better-sized icon here.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/943079
> Icons: Map md-warning to KnownImageIds.IntellisenseWarning

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices/MonoDevelopExtensionManager.cs
In some multi-targeting scenarios, `CSharpSemanticQuickInfoProvider` can
throw an error. Roslyn's default extension manager behavior in cases
like this is to disable the offending QuickInfo provider. But if that
happens, the provider is disabled until you close/reopen the solution.
Avoid this, so that the most useful C# tooltips don't go away just
because this error gets hit.
Temporary workaround for https://devdiv.visualstudio.com/DevDiv/_workitems/edit/960181
> Roslyn: Don't disable Roslyn's semantic QuickInfo after known error

- main/xbuild.include
This reverts commit 2842fa9ae48db9afc5c5f0a934d03bc8a77a81b3.
VSTS only seems to properly detect error lines in the log when the MSBuild task is used, not when we have a bash script invoking make.
> Revert "Use minimal verbosity for msbuild builds"

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/Gui/MonoDevelop.VersionControl.Git.UserGitConfigDialog.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitCommitDialogExtension.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Dialogs/CommitDialog.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.csproj
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/CommitDialogExtension.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/MessageService.cs
attempting to commit to Git
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/961599
MessageService was causing a stack Overflow it could add a dialog as
child to itself. However teh git commit dialog should set itself as
parent for the git config dialog.
> Fixes VSTS Bug 961599: [Feedback] Visual Studio crashes/exists when

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartupTracker.cs
Fixes VSTS #960621 - Startup section timings are not logged in the IDE log
Also some miscellaneous object retention and cleanup
> [Ide] Log information about the IDE initialization section duration

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/ManagePackagesViewModelTests.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/ManagePackagesViewModel.cs
The Updates tab would show 'Multiple' for the current version when the
same package version was installed in multiple projects.
Fixes VSTS #963252 - Manage NuGet packages showing multiple current
versions when only one is installed
> [NuGet] Fix current version label in Manage NuGet packages dialog

- main/Directory.Build.props
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/RoslynHelpers.fs
This property has moved to its own props file.
It was accidentally restored here via bad merge/rebase in
https://github.com/mono/monodevelop/pull/8201, causing
the version in the props file to be overridden.
Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/959442
> Directory.Build.props: Remove NuGetVersionRoslyn

- main/Directory.Build.props
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/RoslynHelpers.fs
This property has moved to its own props file.
It was accidentally restored here via bad merge/rebase in
https://github.com/mono/monodevelop/pull/8201, causing
the version in the props file to be overridden.
Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/959442
Backport of #8407.
> [release-8.3] Directory.Build.props: Remove NuGetVersionRoslyn

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateTests.cs
- main/tests/IdeUnitTests/ProjectTemplateTest.cs
See if this fixes the project template tests.
Temporary change - should not be needed when the packages
are published on nuget.org.
Backport of #8379.
/cc @rodrmoya @mrward
> [release-8.3] [DotNetCore] Add custom .NET Core sdk package sources

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/ManagePackagesViewModelTests.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/ManagePackagesViewModel.cs
The Updates tab would show 'Multiple' for the current version when the
same package version was installed in multiple projects.
Fixes VSTS #963252 - Manage NuGet packages showing multiple current
versions when only one is installed
Backport of #8362.
/cc @mrward
> [release-8.3] [NuGet] Fix current version label in Manage NuGet packages dialog

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreExecutionHandler.cs
For some reason (so far, seems to be a bug in the latest Mono we bumped
to), TcpClient stopped working on this several years old code that has had
no change that could have broken it. So, as a workaround, switch to use
HttpClient, which works.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/962315
> [AspNetCore] Switch to HttpClient from TcpClient

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreExecutionHandler.cs
For some reason (so far, seems to be a bug in the latest Mono we bumped
to), TcpClient stopped working on this several years old code that has had
no change that could have broken it. So, as a workaround, switch to use
HttpClient, which works.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/962315
Backport of #8417.
/cc @rodrmoya
> [release-8.3] [AspNetCore] Switch to HttpClient from TcpClient

- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/UrlMarker.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/HighlightUrlExtension.cs
Mono.TextEditor.UrlMarker.Draw()
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/958225
I assume LineSegment == null in UrlMarker caused the
NullReferenceException.
Extracted 2 methods out of the Draw method in UrlTextMarker + refactored it a bit.
> Fixes VSTS Bug 958225: System.NullReferenceException exception in

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/BlameCommand.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/DiffCommand.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/946944
Diff View could be loaded before the text view had the text - that
caused that the "local" text was empty. The blame view had the same
issue (but crashed) - fixed that as well.
Backport of #8195.
/cc @mkrueger
> [release-8.2] Fixes VSTS FeedbackTicket 943824: Diff Incorrect

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/Gui/MonoDevelop.VersionControl.Git.UserGitConfigDialog.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitCommitDialogExtension.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Dialogs/CommitDialog.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.csproj
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/CommitDialogExtension.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/MessageService.cs
attempting to commit to Git
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/961599
MessageService was causing a stack Overflow it could add a dialog as
child to itself. However teh git commit dialog should set itself as
parent for the git config dialog.
Backport of #8354.
> [release-8.3] Fixes VSTS Bug 961599: [Feedback] Visual Studio crashes/exists when

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.Helpers/RestoreTestBase.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.csproj
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/AssemblyReferenceWithConditionTests.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/FullyQualifiedReferencePathTests.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/PackageManagementCanReferenceProjectExtensionTests.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/UpdateXamarinFormsBuildTest.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.addin.xml
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.csproj
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageManagementCanReferenceProjectExtension.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/RestoreNuGetPackagesAction.cs
- main/tests/test-projects/CanReferenceProjectTests/CanReferenceProjectTests.sln
- main/tests/test-projects/CanReferenceProjectTests/Net46NetStandard10/Net46NetStandard10.csproj
- main/tests/test-projects/CanReferenceProjectTests/Net472/Net472.csproj
- main/tests/test-projects/CanReferenceProjectTests/NetCore21Net472/NetCore21Net472.csproj
- main/tests/test-projects/CanReferenceProjectTests/NetStandard11/NetStandard11.csproj
The Edit References dialog uses the Project.CanReferenceProject method
to determine if a project can be referenced. This does not consider
multi-target framework projects. Now a DotNetProjectExtension has
been added to the NuGet addin that uses NuGet to determine the
compatibility of all target frameworks the projects use.
Report all target frameworks as incompatible in the Edit References
dialog instead of just the first target framework.
Fixes VSTS #959111 - Unable to add references with multi-target
framework project
> [NuGet] Make references dialog aware of multi-target projects

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.Helpers/RestoreTestBase.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.csproj
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/AssemblyReferenceWithConditionTests.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/FullyQualifiedReferencePathTests.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/PackageManagementCanReferenceProjectExtensionTests.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/UpdateXamarinFormsBuildTest.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.addin.xml
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.csproj
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageManagementCanReferenceProjectExtension.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/RestoreNuGetPackagesAction.cs
- main/tests/test-projects/CanReferenceProjectTests/CanReferenceProjectTests.sln
- main/tests/test-projects/CanReferenceProjectTests/Net46NetStandard10/Net46NetStandard10.csproj
- main/tests/test-projects/CanReferenceProjectTests/Net472/Net472.csproj
- main/tests/test-projects/CanReferenceProjectTests/NetCore21Net472/NetCore21Net472.csproj
- main/tests/test-projects/CanReferenceProjectTests/NetStandard11/NetStandard11.csproj
The Edit References dialog uses the Project.CanReferenceProject method
to determine if a project can be referenced. This does not consider
multi-target framework projects. Now a DotNetProjectExtension has
been added to the NuGet addin that uses NuGet to determine the
compatibility of all target frameworks the projects use.
Report all target frameworks as incompatible in the Edit References
dialog instead of just the first target framework.
Fixes VSTS #959111 - Unable to add references with multi-target
framework project
Backport of #8409.
/cc @mrward
> [release-8.3] [NuGet] Make references dialog aware of multi-target projects

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/EditorCompareWidgetBase.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor.Utils/TextBreaker.cs
Mono.TextEditor.Utils.TextBreaker.BreakLinesIntoWords()
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/959146
I can't find the cause of it. I checked the parameters of
BreakLinesIntoWords now. The diff must be out of sync with the text
document that should now not happen, it's checked before paint that
the versions match. In any case that implementation is more solid.
> Fixes VSTS Bug 959146: System.NullReferenceException exception in

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/EditorCompareWidgetBase.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor.Utils/TextBreaker.cs
Mono.TextEditor.Utils.TextBreaker.BreakLinesIntoWords()
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/959146
I can't find the cause of it. I checked the parameters of
BreakLinesIntoWords now. The diff must be out of sync with the text
document that should now not happen, it's checked before paint that
the versions match. In any case that implementation is more solid.
Backport of #8360.
/cc @mkrueger
> [release-8.3] Fixes VSTS Bug 959146: System.NullReferenceException exception in

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/DockFrame.cs
than the screen
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/962517
It's easy to reproduce - just make the window big, hover -> make
window small - hover. The validation fixes that issue.
> Fixes VSTS Bug 962517: [Feedback] Application output window is bigger

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.addin.xml
Using the same command ids as those in the separate NuGet extensions
addin can cause odd behaviour if an old NuGet extensions addin is
disabled in the IDE. This can result in the Manage NuGet Packages
not being shown on the Solution window's context menu.
> [NuGet] Use different command ids for manage packages commands

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.addin.xml
Using the same command ids as those in the separate NuGet extensions
addin can cause odd behaviour if an old NuGet extensions addin is
disabled in the IDE. This can result in the Manage NuGet Packages
not being shown on the Solution window's context menu.
Backport of #8416.
/cc @mrward
> [release-8.3] [NuGet] Use different command ids for manage packages commands

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/EditorCompareWidgetBase.cs
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor.Utils/TextBreaker.cs
Mono.TextEditor.Utils.TextBreaker.BreakLinesIntoWords()
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/959146
I can't find the cause of it. I checked the parameters of
BreakLinesIntoWords now. The diff must be out of sync with the text
document that should now not happen, it's checked before paint that
the versions match. In any case that implementation is more solid.
Backport of #8360.
> [release-8.2] Fixes VSTS Bug 959146: System.NullReferenceException exception in

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs
Repro steps:
1) Create a solution with a .NET Core app project.
2) Add a .Net Core API project to this existing solution.
During project creation the API project will try to access the ParentSolution property in the FileService_FileChanged callback, before it has been set on the project.
This change is the least risky and minimal fix to avoid the NRE exception. A subsequent PR should include broader changes to avoid unnecessary duplication effort of global.json processing at the project level, among other improvements.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/944667
> Fix NRE when accessing null ParentSolution property on DotNetCoreProject

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DependencyNodeTests.cs
- main/tests/test-projects/DotNetCoreDependenciesFolder/NetStandardOneIndirectNuGetWarning.csproj
No longer using the Microsoft.IdentityModel.Clients.ActiveDirectory
NuGet package but a custom package built just for the unit test.
> [DotNetCore] Use custom package for NuGet indirect diagnostic warning test

- main/src/addins/MonoDevelop.DotNetCore/Properties/MonoDevelop.DotNetCore.addin.xml
The Dependencies and NuGet folder did not show the Manage NuGet Packages
menu item in the project's context menu since the command id had been
renamed.
> [DotNetCore] Fix Manage NuGet Packages menu missing from Dependencies

- main/src/addins/MonoDevelop.DotNetCore/Properties/MonoDevelop.DotNetCore.addin.xml
The Dependencies and NuGet folder did not show the Manage NuGet Packages
menu item in the project's context menu since the command id had been
renamed.
Backport of #8455.
/cc @mrward
> [release-8.3] [DotNetCore] Fix Manage NuGet Packages menu missing from Dependencies

- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/AssemblyBrowserWidget.cs
MonoDevelop.AssemblyBrowser.AssemblyBrowserWidget.<>c__XXX.<EnsureDefinitionsLoaded>b__XXX()
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/958247
It could be that this exception didn't happen anymore however it's
hard to tell - this is basically the last thing that potentially could
be null in that method.
> Fixes VSTS Bug 958247: System.NullReferenceException exception in

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.csproj
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/PackageLoadContextTests.cs
- main/src/addins/MonoDevelop.PackageManagement/NuGet.PackageManagement.UI/PackageCollection.cs
Ignore package references that have no version specified in the
project. This fixes a null reference exception displayed in the
Updates tab of the Manage NuGet packages dialog for an ASP.NET Core
web project.
Fixes VSTS #965689 - Manage NuGet Package has yellow bar with
"Object reference not set to an instance of an object"
> [NuGet] Handle packages with no version in Manage Packages dialog

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.csproj
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/PackageLoadContextTests.cs
- main/src/addins/MonoDevelop.PackageManagement/NuGet.PackageManagement.UI/PackageCollection.cs
Ignore package references that have no version specified in the
project. This fixes a null reference exception displayed in the
Updates tab of the Manage NuGet packages dialog for an ASP.NET Core
web project.
Fixes VSTS #965689 - Manage NuGet Package has yellow bar with
"Object reference not set to an instance of an object"
Backport of #8422.
/cc @mrward
> [release-8.3] [NuGet] Handle packages with no version in Manage Packages dialog

- main/src/addins/MonoDevelop.GtkCore/MonoDevelop.GtkCore.GuiBuilder/CombinedDesignView.cs
- main/src/addins/MonoDevelop.GtkCore/MonoDevelop.GtkCore.GuiBuilder/GuiBuilderView.cs
Can now drag and drop GTK# widgets from the Toolbox window to the
GTK# window or widget being designed.
Fixes VSTS #951728 - GTK# toolbox is empty on Visual Studio Community
2019 on the MAC
Fixes github #8278 - When creating a Gtk#2.0 project on Mac OS X, the
toolbox fails to populate for the Designer
> [GtkCore] Fix toolbox items not displayed

- main/src/addins/MonoDevelop.GtkCore/MonoDevelop.GtkCore.GuiBuilder/CombinedDesignView.cs
- main/src/addins/MonoDevelop.GtkCore/MonoDevelop.GtkCore.GuiBuilder/GuiBuilderView.cs
Can now drag and drop GTK# widgets from the Toolbox window to the
GTK# window or widget being designed.
Fixes VSTS #951728 - GTK# toolbox is empty on Visual Studio Community
2019 on the MAC
Fixes github #8278 - When creating a Gtk#2.0 project on Mac OS X, the
toolbox fails to populate for the Designer
Backport of #8463.
/cc @mrward
> [release-8.3] [GtkCore] Fix toolbox items not displayed

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/Glyphs/BreakpointGlyphMouseProcessor.cs
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/MdMouseProcessorProvider.cs
This is now handled by `ICocoaMouseProcessorEvents` implementors. From
the perspective of mouse _processors_, this is now a standard right
click on Mac.
> TextEditor: Mouse processors don't need to deal with ctrl+click anymore

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/Glyphs/BreakpointGlyphMouseProcessor.cs
- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/MdMouseProcessorProvider.cs
This is now handled by `ICocoaMouseProcessorEvents` implementors. From
the perspective of mouse _processors_, this is now a standard right
click on Mac.
Backport of #8426.
> [release-8.3] TextEditor: Mouse processors don't need to deal with ctrl+click anymore

- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/AssemblyBrowserWidget.cs
MonoDevelop.AssemblyBrowser.AssemblyBrowserWidget.<>c__XXX.<EnsureDefinitionsLoaded>b__XXX()
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/958247
It could be that this exception didn't happen anymore however it's
hard to tell - this is basically the last thing that potentially could
be null in that method.
Backport of #8387.
/cc @mkrueger
> [release-8.3] Fixes VSTS Bug 958247: System.NullReferenceException exception in

- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/UrlMarker.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Extension/HighlightUrlExtension.cs
Mono.TextEditor.UrlMarker.Draw()
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/958225
I assume LineSegment == null in UrlMarker caused the
NullReferenceException.
Extracted 2 methods out of the Draw method in UrlTextMarker + refactored it a bit.
Backport of #8392.
/cc @mkrueger
> [release-8.3] Fixes VSTS Bug 958225: System.NullReferenceException exception in

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/DockFrame.cs
than the screen
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/962517
It's easy to reproduce - just make the window big, hover -> make
window small - hover. The validation fixes that issue.
Backport of #8414.
> [release-8.3] Fixes VSTS Bug 962517: [Feedback] Application output window is bigger

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DocumentRegistry.cs
A new - not yet saved - document can't have a last write time. Although it's not a crasher, we should not even try to get the write time if we know that the file doesn't exist.
> [Ide] Don't log an error if getting last write time for new documents fails

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlDocumentController.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/GtkTreeModelResult.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/GtkWidgetResult.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/NSObjectResult.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/WebViewResult.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/AppResult.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest/ObjectProperties.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/MDLinkMenuItem.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/MDMenu.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/MDMenuItem.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentViewContainer.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/GtkShellDocumentViewContainer.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/GtkShellDocumentViewContainerTabs.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/GtkShellDocumentViewContent.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/GtkShellDocumentViewItem.cs
- main/tests/Ide.Tests/MonoDevelop.Components.AutoTest/AppResultTests.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Gui.Documents/DocumentControllerTests.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Tests.csproj
Fixes VSTS #964955 - ObjectProperties are leaked due in AutoTest service
Fixes VSTS #965064 - GtkShellDocumentView is not properly disposed
> [Ide] Fix various leaks causing retention of document model and autotest objects

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.Helpers/FakePackageMetadataProvider.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.Helpers/TestableManagePackagesViewModel.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/ManagePackagesViewModelTests.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/ManagePackagesProjectInfo.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/ManagePackagesViewModel.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/UninstallNuGetPackageAction.cs
Checking more than one NuGet package in the Manage NuGet packages
dialog when that NuGet package is installed in multiple projects
could result in projects being listed multiple times in the Select
Projects dialog. This was because each checked package id was
being checked against all the packages installed in the project and
for each match the project was being returned. This would result
in the same project being listed multiple times in the dialog which
was confusing.
Fixes VSTS #966636 - NuGet Package Manager dialog after selecting
multiple packages to uninstall unclear
Also added more tests for the Manage NuGet packages dialog.
Fixes VSTS #961926 - [test coverage] nuget - solution wide nuget management
> [NuGet] Fix duplicate projects in select projects dialog

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.Helpers/FakePackageMetadataProvider.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.Helpers/TestableManagePackagesViewModel.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/ManagePackagesViewModelTests.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/ManagePackagesProjectInfo.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/ManagePackagesViewModel.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/UninstallNuGetPackageAction.cs
Checking more than one NuGet package in the Manage NuGet packages
dialog when that NuGet package is installed in multiple projects
could result in projects being listed multiple times in the Select
Projects dialog. This was because each checked package id was
being checked against all the packages installed in the project and
for each match the project was being returned. This would result
in the same project being listed multiple times in the dialog which
was confusing.
Fixes VSTS #966636 - NuGet Package Manager dialog after selecting
multiple packages to uninstall unclear
Also added more tests for the Manage NuGet packages dialog.
Fixes VSTS #961926 - [test coverage] nuget - solution wide nuget management
Backport of #8468.
/cc @mrward
> [release-8.3] [NuGet] Fix duplicate projects in select projects dialog

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Control.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Window.cs
This is the second attempt at fixing VSTS 945987, where Format Document doesn't work if invoked from the Navigate To window. The first PR https://github.com/mono/monodevelop/pull/8265 attempted to resolve in a way that would allow commands to execute correctly on the handler, but as was pointed out, we also needed a way to allow native widgets to be focused. 
I built on changes from here #7521 and extended the fix as it kept throwing exceptions. 
Fixes https://vsmac.dev/945987
> Fixes VSTS 945987: Format document doesn't work from Navigate To when using the new editor

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git.Tests/BaseGitRepositoryTests.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/Commands.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitConfigurationDialog.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitService.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/StashManagerDialog.cs
Hard to tell what did go wrong for the user which opened the bug request.
I made the switch branch code async and cleaned it up a bit - ThawEvents may've been called too soon by RunBlockingOperation and BranchSelectionChanged is now in sync with the whole operation.
> Fixes VSTS Bug 950651: VS4MAc does not handle switching branches well

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git.Tests/BaseGitRepositoryTests.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/Commands.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitConfigurationDialog.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitService.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/StashManagerDialog.cs
Hard to tell what did go wrong for the user which opened the bug request.
I made the switch branch code async and cleaned it up a bit - ThawEvents may've been called too soon by RunBlockingOperation and BranchSelectionChanged is now in sync with the whole operation.
Backport of #8415.
> [release-8.3] Fixes VSTS Bug 950651: VS4MAc does not handle switching branches well

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
The IVT is needed to expose WorkspaceExtensions.RegisterSolutionCrawler() which is internal.
> Add IVT to TypeScriptAddin.

- main/build/MacOSX/Entitlements.plist
- main/build/MacOSX/Makefile.am
- main/build/MacOSX/render.cs
- version-checks
This puts in the necessary changes to make VSMac function after turning on the hardened runtime flag. There's a corresponding PR in https://github.com/xamarin/md-addins/pull/5177.
This needs to land on both `master` and the current release branches.
@iainx Can you look over this (I just rebased it on top of this morning's master) and get this merged in. Also, I don't know where the current release branches are, so this needs to be backported there as well.
cc @sevoku 
Fixes VSTS #962402
> Enable notarization

- main/build/MacOSX/Entitlements.plist
- main/build/MacOSX/Makefile.am
- main/build/MacOSX/render.cs
- version-checks
This puts in the necessary changes to make VSMac function after turning on the hardened runtime flag. There's a corresponding PR in xamarin/md-addins#5193.
This needs to land on both master and the current release branches.
@iainx Can you look over this (I just rebased it on top of this morning's master) and get this merged in. Also, I don't know where the current release branches are, so this needs to be backported there as well.
Backport of #8396 
cc @duncanmak 
Fixes VSTS #962402
> [release-8.3] Enable notarization

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FakeSearchCategory.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/ProjectSearchCategory.fs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/SearchPackagesSearchCategory.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/CommandSearchCategory.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/FileSearchCategory.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/RoslynSearchCategory.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/SearchCategory.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/SearchInSolutionSearchCategory.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/SearchPopupWindow.cs
The Global Search is a very useful tool to search any text in different search providers in MD or extensions
We have a big performance problem in large solutions like MD, on opening a solution it takes about 3 minutes to show any result.
Investigating I found it's happening because we wait to finish all the providers to show any result, and it seems, some search providers takes more time than expected to finish, and this delays all the other results. The problem will grow as we add more suppliers to the search.
To solve this, we now show the search window **instantly**, and we launch all the search provider tasks in parallel and we add each one of the results as they finish the tasks, **that ends up starting to show results in ~1 second**.
On the other hand, I have created a new "Loading" …
> [GlobalSearch] Improves current GlobalSearch performance showing results

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
The IVT is needed to expose WorkspaceExtensions.RegisterSolutionCrawler() which is internal.
Backport of #8487.
> [release-8.3] Add IVT to TypeScriptAddin.

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs
Repro steps:
1) Create a solution with a .NET Core app project.
2) Add a .Net Core API project to this existing solution.
During project creation the API project will try to access the ParentSolution property in the FileService_FileChanged callback, before it has been set on the project.
This change is the least risky and minimal fix to avoid the NRE exception. A subsequent PR should include broader changes to avoid unnecessary duplication effort of global.json processing at the project level, among other improvements.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/944667
Backport of #8440.
> [release-8.3] Fix NRE when accessing null ParentSolution property on DotNetCoreProject

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Gui/ManagePackagesDialog.cs
[NuGet] Allow checkboxes to be selected by keyboard in packages dialog  …
Previously pressing space or enter would cause the selected package,
or multiple packages if checked, to be installed. Now pressing space
or enter checks or unchecks the package.
Fixes VSTS #750399 - Accessibility: Onfocus issue has been observed
while selecting packages from the list
Fixes VSTS #750407 - Accessibility: Checkboxes for selecting multiple
packages are not accessible through keyboard
[NuGet] Do not install package when enter pressed in search text box
No longer installing the selected package in the Manage NuGet Packages
dialog when the enter key is pressed. This has caused a bit of
confusion and can cause a package to be installed when the user is
trying to run the search. Note that the search is a …
> [NuGet] Allow checkboxes to be selected by keyboard in packages dialog

- main/src/tools/ExtensionTools/ExtensionTools.csproj
If the ExtensionTools project is built before MonoDevelop.Ide then
the build will fail since it tries to reference Xamarin.Mac.dll from
main/build/bin instead of external. Changed the project to use
Xamarin.Mac.dll from the external directory.
Had this happen on a release-8.2 based branch. Could not repro locally but it seems like it could happen. The majority of other projects reference it from the external directory not the build/bin directory.
> [Tools] Fix Xamarin.Mac reference in ExtensionTools

- main/src/addins/PerformanceDiagnostics/PerformanceDiagnostics/Commands.cs
- main/src/addins/PerformanceDiagnostics/PerformanceDiagnostics/Properties/PerformanceDiagnostics.addin.xml
- main/src/core/MonoDevelop.Core/MonoDevelop.Utilities/SampleProfiler.cs
This commit introduces spindump as a profiling backend, alongside sample.
spindump has the advantage of being able to distinguish running threads
from waiting threads, thus will only generate information about things
spinning on the CPU.
On the other hand, spindump (even the normal report) is not loadable in Instruments.
But given the fact that the data is way smaller:
On the same scenario:
Sample, ~1450 stacktrace lines: https://gist.github.com/Therzok/d81908c632a3b93b30727a2b98c03d0b
Spindump, ~1200 stacktrace lines: https://gist.github.com/Therzok/94a6d3ee44ec26ce76b9266e76fa6dda
But the latter contains only actual running time, nothing that is actually spent waiting on synchronization
primitives.
Introduced a few new regexes to handle spindump format. Keep output that is sample …
> [Core] Add a way to use spindump as a profiler backend

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/NSObjectResult.cs
> [AutoTest] Add logging in NSObjectResult.SetActiveRuntime to trace source of NRE

- main/src/addins/MacPlatform/MacInterop/Carbon.cs
- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/tools/mdmonitor/Main.cs
- main/tests/MacPlatform.Tests/CarbonTests.cs
The Carbon code for changing the application name is private and unsupported,
and fragile, and isn't really needed anymore as we just want to use the app
name from the app bundle.
The downside of this is that the app name displayed when debugging from inside
the IDE is "mono64" and when run from 'make run' it is MonoDevelop. Run from
an appbundle, it gets the correct name
Fixes vSTS #899321
> [Mac] Remove the code for changing application name

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.Tests/BreakpointsAndSteppingTests.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.Tests/MonoDevelop.Debugger.Tests.csproj
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/BreakpointManager.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/BreakpointPad.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebugCommands.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebuggingService.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor.QuickTasks/QuickTaskOverviewMode.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SourceEditorView.cs
- main/src/tools/ExtensionTools/ExtensionTools.csproj
Backport of #8313
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/949284
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/935168
This removes all the locks around the breakpoint store now that it is thread safe and bumps to pick up the changes.
> [release-8.2] Thread safe BreakpointStore

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/NSObjectResult.cs
Fixes #958151
Fixes #941255
Backport of #8470.
/cc @manish 
---
This is not a product bug, but a test infrastructure bug which causes automated test failure and leads to having to run the tests manually
> [release-8.2] [AutoTest] Add logging in NSObjectResult.SetActiveRuntime to trace source of NRE

- main/src/addins/MacPlatform/MainToolbar/MainToolbar.cs
Search popup window was disappearing in fullscreen on a second monitor
Fixes VSTS #969968
Backport of #8498.
> [release-8.3] [Mac] Send the correct frame

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/NSStackViewExtensions.cs
SetContentHuggingPriorityForOrientation and SetContentCompressionResistancePriority both have `float priority`, so use that.
> [Mac] Use actual type from signature, float instead of int

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/NSObjectResult.cs
Fixes #958151
Fixes #941255
Backport of #8470.
/cc @sevoku @manish
> [release-8.3] [AutoTest] Add logging in NSObjectResult.SetActiveRuntime to trace source of NRE

- main/src/addins/MacPlatform/MacInterop/Carbon.cs
- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/tools/mdmonitor/Main.cs
- main/tests/MacPlatform.Tests/CarbonTests.cs
The Carbon code for changing the application name is private and unsupported,
and fragile, and isn't really needed anymore as we just want to use the app
name from the app bundle.
The downside of this is that the app name displayed when debugging from inside
the IDE is "mono64" and when run from 'make run' it is MonoDevelop. Run from
an appbundle, it gets the correct name
Fixes vSTS #899321
Backport of #8510.
/cc @iainx
> [release-8.3] [Mac] Remove the code for changing application name

- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/ToolboxPad.cs
* Fixes Bug #943089 - [VS for Mac] Failed to drag new controls into designer after adding a control
> [Toolbox] Fixes broken state dragging items when pad is closed

- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/ToolboxPad.cs
* Fixes Bug #943089 - [VS for Mac] Failed to drag new controls into designer after adding a control
Backport of #8526.
> [release-8.3] [Toolbox] Fixes broken state dragging items when pad is closed

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreProjectExtension.cs
Repro steps:
1) Create a solution with a .NET Core app project.
2) Add a .Net Core API project to this existing solution.
During project creation the API project will try to access the ParentSolution property in the FileService_FileChanged callback, before it has been set on the project.
This change is the least risky and minimal fix to avoid the NRE exception. A subsequent PR should include broader changes to avoid unnecessary duplication effort of global.json processing at the project level, among other improvements.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/944667
Backport of #8440.
> [release-8.2] Fix NRE when accessing null ParentSolution property on DotNetCoreProject

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/DropDownBoxListWindow.cs
If appears that in some circumstances, the snapshot changes as we get to calling the ActivateItem method on the provider, causing an argument out of range exception. This attempts to fix it by (1) boxing the offset to the current length of the current (valid) snapshot, and (2) catching any exception that would still flow to (this particular) UI element.
Fixes: https://vsmac.dev/940776
> Fixes 940776: System.ArgumentOutOfRangeException on selection change in drop down

- main/src/addins/MacPlatform/Dialogs/MacOpenFileDialogHandler.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Extensions/IOpenFileDialogHandler.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/OpenFileDialog.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/MessageService.cs
This PR depends on: https://github.com/xamarin/md-addins/pull/4765
By default OpenPanel dialog opens at center of the screen but in case of GTC, we need consistency in the current OperationButtons (Open File and NewProjectDialog) behaviour, this by default opens centered by based in the parent window.
Fixes VSTS #859111 - Inconsistent dialog locations
> Adds feature to center current open panel based in parent window

- main/src/addins/AspNet/Projects/AspNetAppProjectFlavor.cs
- main/src/addins/MacPlatform/MacPlatform.cs
- main/tests/MacPlatform.Tests/MacPlatformTest.cs
[Mac] Handle filenames not just urls in GetApplications
MacPlatformService.GetApplications was using NSUrl.FromString which
works for hyperlinks but returns null for file that contains a space
character in its path. This was causing the open file dialog to
never close.
```
Parameter name: url
at CoreServices.LaunchServices.GetDefaultApplicationUrlForUrl (Foundation.NSUrl url, CoreServices.LSRoles roles) [0x00030] in /Library/Frameworks/Xamarin.Mac.framework/Versions/5.16.1.17/src/Xamarin.Mac/CoreServices/LaunchServices.cs:97
at MonoDevelop.MacIntegration.MacPlatformService.GetApplications (System.String filename) [0x00024] in /Users/vsts/agent/2.155.1/work/1/s/monodevelop/main/src/addins/MacPlatform/MacPlatform.cs:966
at MonoDevelop.Ide.DesktopService.GetApplications (System.String …
```
> [Mac] Fix not being able to open a file with external application

- main/src/addins/AspNet/Projects/AspNetAppProjectFlavor.cs
- main/src/addins/MacPlatform/MacPlatform.cs
- main/tests/MacPlatform.Tests/MacPlatformTest.cs
[Mac] Handle filenames not just urls in GetApplications
MacPlatformService.GetApplications was using NSUrl.FromString which
works for hyperlinks but returns null for file that contains a space
character in its path. This was causing the open file dialog to
never close.
```
Parameter name: url
at CoreServices.LaunchServices.GetDefaultApplicationUrlForUrl (Foundation.NSUrl url, CoreServices.LSRoles roles) [0x00030] in /Library/Frameworks/Xamarin.Mac.framework/Versions/5.16.1.17/src/Xamarin.Mac/CoreServices/LaunchServices.cs:97
at MonoDevelop.MacIntegration.MacPlatformService.GetApplications (System.String filename) [0x00024] in /Users/vsts/agent/2.155.1/work/1/s/monodevelop/main/src/addins/MacPlatform/MacPlatform.cs:966
at MonoDevelop.Ide.DesktopService.GetApplications (System.String …
```
> [release-8.3] [Mac] Fix not being able to open a file with external application

- main/src/addins/CSharpBinding/Gui/MonoDevelop.CSharp.Formatting.CSharpFormattingProfileDialog.cs
The issue has already been fixed in MessageDialog, nevertheless
Hide, Show and ShowAll should never be called in the ctor
of a Gtk Dialog or Window. Even Hide will realize the window
and make it the key window on mac for the current UI iteration,
which will confuse MessageService and probably other logic
relying on a valid focused key window.
Fixes VSTS #943186
> [CSharp] Don't hide formatting dialog in ctor

- main/src/addins/CSharpBinding/Gui/MonoDevelop.CSharp.Formatting.CSharpFormattingProfileDialog.cs
The issue has already been fixed in MessageDialog, nevertheless
Hide, Show and ShowAll should never be called in the ctor
of a Gtk Dialog or Window. Even Hide will realize the window
and make it the key window on mac for the current UI iteration,
which will confuse MessageService and probably other logic
relying on a valid focused key window.
Fixes VSTS #943186
Backport of #8550.
/cc @sevoku
> [release-8.3] [CSharp] Don't hide formatting dialog in ctor

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentView.cs
When grabbing the focus of a view, the actual grab is done after
dispatching the event queue. It may happen that after the events are
executed, the view bacame hidden (for example, maybe an attached view
was set active). In that case, don't try to grab the focus since it
maye cause an unexpected re-activation of the view.
Fixes VSTS #963585 – Diff/View commands broken in SolutonPad
> Fix document focus issue

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentView.cs
When grabbing the focus of a view, the actual grab is done after
dispatching the event queue. It may happen that after the events are
executed, the view bacame hidden (for example, maybe an attached view
was set active). In that case, don't try to grab the focus since it
maye cause an unexpected re-activation of the view.
Fixes VSTS #963585 – Diff/View commands broken in SolutonPad
Backport of #8571.
/cc @slluis
> [release-8.3] Fix document focus issue

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreSDKResolverTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSdkPaths.cs
Fixes VSTS #948292
Backport of #8546.
/cc @nosami
> [release-8.3] Check that SDK root path exists before versions

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FakeSearchCategory.fs
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/ProjectSearchCategory.fs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/SearchPackagesSearchCategory.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/CommandSearchCategory.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/FileSearchCategory.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/RoslynSearchCategory.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/SearchCategory.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/SearchInSolutionSearchCategory.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/SearchPopupWindow.cs
The Global Search is a very useful tool to search any text in different search providers in MD or extensions
We have a big performance problem in large solutions like MD, on opening a solution it takes about 3 minutes to show any result.
Investigating I found it's happening because we wait to finish all the providers to show any result, and it seems, some search providers takes more time than expected to finish, and this delays all the other results. The problem will grow as we add more suppliers to the search.
To solve this, we now show the search window **instantly**, and we launch all the search provider tasks in parallel and we add each one of the results as they finish the tasks, **that ends up starting to show results in ~1 second**.
On the other hand, I have created a new "Loading" …
> [release-8.3] [GlobalSearch] Improves current GlobalSearch performance showing results

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/NSObjectResult.cs
Fixes #958151
Fixes #941255
Backport of #8470.
/cc @manish
> [release-8.2-xcode11] [AutoTest] Add logging in NSObjectResult.SetActiveRuntime to trace source of NRE

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/NSObjectResult.cs
Fixes #958151
Fixes #941255
Backport of #8470.
/cc @manish
> [release-8.3-xcode11] [AutoTest] Add logging in NSObjectResult.SetActiveRuntime to trace source of NRE

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Options/AbstractOptionPreviewViewModel.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Options/CheckBoxOptionViewModel.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Options/CheckBoxWithComboOptionViewModel.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Options/RadioButtonViewModel.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Options/Style/BooleanCodeStyleOptionViewModel.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Options/Style/EnumCodeStyleOptionViewModel.cs
click OK in the Preferences menu in Visual Studio for Mac.
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/972866
> Fixes VSTS Bug 972866: [Feedback] Preferences are not saved when I

- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Options/AbstractOptionPreviewViewModel.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Options/CheckBoxOptionViewModel.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Options/CheckBoxWithComboOptionViewModel.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Options/RadioButtonViewModel.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Options/Style/BooleanCodeStyleOptionViewModel.cs
- main/src/addins/MonoDevelop.Refactoring/MonoDevelop.Refactoring.Options/Style/EnumCodeStyleOptionViewModel.cs
click OK in the Preferences menu in Visual Studio for Mac.
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/972866
Backport of #8522.
> [release-8.3] Fixes VSTS Bug 972866: [Feedback] Preferences are not saved when I

- main/src/addins/MacPlatform/Dialogs/MacOpenFileDialogHandler.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Extensions/IOpenFileDialogHandler.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/OpenFileDialog.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/MessageService.cs
This PR depends on: https://github.com/xamarin/md-addins/pull/5273
By default OpenPanel dialog opens at center of the screen but in case of GTC, we need consistency in the current OperationButtons (Open File and NewProjectDialog) behaviour, this by default opens centered by based in the parent window.
Fixes VSTS #859111 - Inconsistent dialog locations
Backport of #7785.
> [release-8.3] Adds feature to center current open panel based in parent window

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/Commands.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitService.cs
Applied changes to show more information about the stash operation status (conflicts, stash not found, uncommitted changes, etc.).
Fixes VSTS #901094
Backport of #7813.
> [release-8.3] [Version Control] Popping a git stash that has conflicts gives invalid warning and no further logs

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateTests.cs
This reverts commit 70dcec9619bfcd1d15eb5b5ea0eee1130cb6041e.
.NET Core 3.0 preview 9 fixes the problem building VB.NET projects.
Fixes VSTS #964872 - VB.NET netcore project test failing
> Revert "[DotNetCore] Disable VB.NET test cases for 3.0"

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreProjectTemplateTests.cs
This reverts commit 70dcec9619bfcd1d15eb5b5ea0eee1130cb6041e.
.NET Core 3.0 preview 9 fixes the problem building VB.NET projects.
Fixes VSTS #964872 - VB.NET netcore project test failing
Backport of #8580.
/cc @mrward
> [release-8.3] Revert "[DotNetCore] Disable VB.NET test cases for 3.0"

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/Commands.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitService.cs
Applied changes to show more information about the stash operation status (conflicts, stash not found, uncommitted changes, etc.).
Fixes VSTS #901094
> [Version Control] Popping a git stash that has conflicts gives invalid warning and no further logs

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git.Tests/BaseGitRepositoryTests.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
error 'Version control operation filed'
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/940635
I think we're running into a libgit bug. Libgit2 works correctly if
the library itself does the submodule checkout - it's more reliable
for us to let do libgit2 the job as well.
> Fixes VSTS Bug 940635: Cloning project with submodules is stops with

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git.Tests/BaseGitRepositoryTests.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
error 'Version control operation filed'
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/940635
I think we're running into a libgit bug. Libgit2 works correctly if
the library itself does the submodule checkout - it's more reliable
for us to let do libgit2 the job as well.
Backport of #8199.
> [release-8.3] Fixes VSTS Bug 940635: Cloning project with submodules is stops with

- main/src/core/MonoDevelop.Ide/ExtensionModel/StockIcons.addin.xml
On Windows:
On Mac:
md-reference image:
KnownImageId.Reference image:
Id:
Backport of #8583.
/cc @sandyarmstrong @sailro
> [release-8.3] Icons: Map md-reference to KnownImageIds.Reference

- main/external/fsharpbinding/MonoDevelop.FSharp.Shared/Lexer.fs
- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/LexerTests.fs
- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/MonoDevelop.FSharp.Tests.fsproj
- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpTokens.fs
Fixes VSTS #963356
Make Lexer.parseLine tail recursive and remove mutable state
Backport of #8529.
/cc @nosami
> [release-8.3] [F#] Fix parsing of long lines

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
When Workbench.Present() is executed for the first time
it will set up the layout, hiding the welcome page.
> [Ide] Show welcome page after preseting workbench

- main/src/core/MonoDevelop.Ide/ExtensionModel/StockIcons.addin.xml
See https://github.com/mono/monodevelop/pull/8363 for the previous (temporary) icon mapping.
This change was requested by design (@vancura et al).
> Icons: Design change to KnownImageIds.IntellisenseWarning icon

- main/src/core/MonoDevelop.Ide/ExtensionModel/StockIcons.addin.xml
See https://github.com/mono/monodevelop/pull/8363 for the previous (temporary) icon mapping.
This change was requested by design (@vancura et al).
Backport of #8616.
> [release-8.3] Icons: Design change to KnownImageIds.IntellisenseWarning icon

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Project/CSharpCompilerParameters.cs
This ensures that the editor and language service are aware of nullable context settings at the project level.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/970026
> CSharpCompilerParameters: Add support for "nullable"

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Project/CSharpCompilerParameters.cs
This ensures that the editor and language service are aware of nullable context settings at the project level.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/970026
Backport of #8618.
> [release-8.3] CSharpCompilerParameters: Add support for "nullable"

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlDocumentController.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentView.cs
This reverts commit d58a3c5c0bc01073dcfb528f3bed685488866ed3. introduced in #8483
Fixes VSTS #977977
Backport of #8643
> [release-8.3] Revert "[VersionControl] Document controller now reacts on file status change."

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlDocumentController.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentView.cs
This reverts commit d58a3c5c0bc01073dcfb528f3bed685488866ed3. introduced in #8483
Fixes VSTS #977977
Backport of #8643
Backport of #8645.
/cc @slluis @sevoku
> [release-8.3-prebiew3.1] [release-8.3] Revert "[VersionControl] Document controller now reacts on file status change."

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
`GetOpenDocumentIds` returned invalid documentId, this can happened if user removed open document by clicking on `Solution pad` and removed document, when asked to `Delete` or `Remove from Project` if user chose `Remove from Project` document remained opened in editor but Roslyn workspace still considered it as open in project, hence wrongly returning it via `GetOpenDocumentIds`, with this change every time project is reloaded we ensure there is no invalid documents in list
> Remove document from `GetOpenDocumentIds` when removed from project

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
`GetOpenDocumentIds` returned invalid documentId, this can happened if user removed open document by clicking on `Solution pad` and removed document, when asked to `Delete` or `Remove from Project` if user chose `Remove from Project` document remained opened in editor but Roslyn workspace still considered it as open in project, hence wrongly returning it via `GetOpenDocumentIds`, with this change every time project is reloaded we ensure there is no invalid documents in list
Backport of #8639.
> [release-8.3] Remove document from `GetOpenDocumentIds` when removed from project

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.ProjectData.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.ProjectDataMap.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.ProjectSystemHandler.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspaceProjectDataMapTests.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspaceProjectDataTests.cs
It's possible for events like device (dis)connect to make several quick
calls to `ActiveConfigurationChanged`, some of which would be canceled,
ultimately causing old `DocumentId` data to get lost during project
reload.
Creating new `DocumentId`s could break multiple Roslyn services such as
intellisense. This change makes the whole process more robust so that
`DocumentId` data does not get lost.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/915494
> Workspace: Prevent DocumentIds from changing on configuration change

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.ProjectData.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.ProjectDataMap.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.ProjectSystemHandler.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspaceProjectDataMapTests.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspaceProjectDataTests.cs
It's possible for events like device (dis)connect to make several quick
calls to `ActiveConfigurationChanged`, some of which would be canceled,
ultimately causing old `DocumentId` data to get lost during project
reload.
Creating new `DocumentId`s could break multiple Roslyn services such as
intellisense. This change makes the whole process more robust so that
`DocumentId` data does not get lost.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/915494
Backport of #8647.
/cc @sandyarmstrong @Therzok
> [release-8.3] Workspace: Prevent DocumentIds from changing on configuration change

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/Properties/MonoDevelop.TextEditor.addin.xml
Visual Studio Editor has 2 commands to show code completion `CommitUniqueCompletionListItemCommandArgs` and `InvokeCompletionListCommandArgs` there are 2 differences between two..
1) If there is unique item(only 1) in list just complete it without showing code completion
2) At least for web-tools difference is also, filter or not list of items
Since Cmd/Ctrl+Space on Windows but also in old editor behaved as `CommitUniqueCompletionListItemCommandArgs` this mapping is much more correct.
> Map `ShowCompletionWindow` to `CommitUniqueCompletionListItem`

- main/msbuild/RoslynVersion.props
Changes since [c82648d](https://www.github.com/dotnet/roslyn/commit/c82648d):
- [Increase Editor Completion Timeout for tests (#38413)](https://www.github.com/dotnet/roslyn/pull/38413)
- [Merge pull request #38441 from mavasani/Issue38330](https://www.github.com/dotnet/roslyn/pull/38441)
- [Merge pull request #38425 from 333fred/source-build-workspaces](https://www.github.com/dotnet/roslyn/pull/38425)
- [Consider nullability when comparing IReference instances during emit (#38249) (#38396)](https://www.github.com/dotnet/roslyn/pull/38396)
- [Merge pull request #38412 from heejaechang/experimentService2](https://www.github.com/dotnet/roslyn/pull/38412)
- [Merge pull request #38356 from heejaechang/experimentService](https://www.github.com/dotnet/roslyn/pull/38356)
- [Merge pull request …
> Bump Roslyn to 3.3.1-beta3-19454-05

- main/msbuild/RoslynVersion.props
Changes since [c82648d](https://www.github.com/dotnet/roslyn/commit/c82648d):
- [Increase Editor Completion Timeout for tests (#38413)](https://www.github.com/dotnet/roslyn/pull/38413)
- [Merge pull request #38441 from mavasani/Issue38330](https://www.github.com/dotnet/roslyn/pull/38441)
- [Merge pull request #38425 from 333fred/source-build-workspaces](https://www.github.com/dotnet/roslyn/pull/38425)
- [Consider nullability when comparing IReference instances during emit (#38249) (#38396)](https://www.github.com/dotnet/roslyn/pull/38396)
- [Merge pull request #38412 from heejaechang/experimentService2](https://www.github.com/dotnet/roslyn/pull/38412)
- [Merge pull request #38356 from heejaechang/experimentService](https://www.github.com/dotnet/roslyn/pull/38356)
- [Merge pull request …
> [release-8.3] Bump Roslyn to 3.3.1-beta3-19454-05

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/Properties/MonoDevelop.TextEditor.addin.xml
Visual Studio Editor has 2 commands to show code completion `CommitUniqueCompletionListItemCommandArgs` and `InvokeCompletionListCommandArgs` there are 2 differences between two..
1) If there is unique item(only 1) in list just complete it without showing code completion
2) At least for web-tools difference is also, filter or not list of items
Since Cmd/Ctrl+Space on Windows but also in old editor behaved as `CommitUniqueCompletionListItemCommandArgs` this mapping is much more correct.
Backport of #8663.
> [release-8.3] Map `ShowCompletionWindow` to `CommitUniqueCompletionListItem`

- main/src/addins/AspNet/Projects/AspNetAppProjectFlavor.cs
- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreProjectExtension.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/DesktopApplication.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/PlatformService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/DesktopService.cs
- main/tests/MacPlatform.Tests/MacPlatformTest.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/970420
This still shows iTerm as a browser, but this is the same the OS shows:
So, as discussed on the bug, provided this is what the OS shows, do the same on our side.
> [AspNet*] Filter HTTP handlers to viewer role

- main/src/addins/AspNet/Projects/AspNetAppProjectFlavor.cs
- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreProjectExtension.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/DesktopApplication.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/PlatformService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/DesktopService.cs
- main/tests/MacPlatform.Tests/MacPlatformTest.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/970420
This still shows iTerm as a browser, but this is the same the OS shows:
So, as discussed on the bug, provided this is what the OS shows, do the same on our side.
Backport of #8649.
/cc @rodrmoya
> [release-8.3] [AspNet*] Filter HTTP handlers to viewer role

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DocumentRegistry.cs
Like new usaved files, also documents without being a file have no
write time.
Fixes VSTS #976445
> [Ide] Fix ArgumentNullException when loading non-file documents

- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Core/DedicatedThreadSchedulerTests.cs
The tests is timing out sometimes. It might happen in slow machines,
or there might be a legitimate bug that is causing tasks to never be
dispatched. Let's find out.
Backport of #8676.
/cc @slluis
> [release-8.3] Increase timeout of TestTasksExecuteSequentially

- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Core/DedicatedThreadSchedulerTests.cs
The tests is timing out sometimes. It might happen in slow machines,
or there might be a legitimate bug that is causing tasks to never be
dispatched. Let's find out.
> Increase timeout of TestTasksExecuteSequentially

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/TextViewContent.cs
Problem was that TextBuffer still had default `TabSize` of `4` so when indentions were calculated it it was wrong in some cases.
> Fix 934342: When I press shift+tab, the selected code lines don't get un-indented

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/ThemeToClassification.cs
Using reflection is never pretty way to fix a bug, but themeing/coloring API of VS is just too old and ugly...
So for now this is solution, because alternative is so much code and potential bugs I would rather not do that...
> Fix 980541: Switching themes in Preferences corrupts colors in editor 

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
Keyboard remapper applications can cause invalid events to be
sent to the key event handlers. Check that events passed to the keypress
handler are actually key events
Fixes VSTS #935180
> [IDE] Check that events passed to the keypress handler are key events

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DocumentRegistry.cs
A new - not yet saved - document can't have a last write time. Although it's not a crasher, we should not even try to get the write time if we know that the file doesn't exist.
Backport of #8380.
/cc @slluis @sevoku
> [release-8.3] [Ide] Don't log an error if getting last write time for new documents fails

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui/DocumentRegistry.cs
Like new usaved files, also documents without being a file have no
write time.
Fixes VSTS #976445
Backport of #8608.
/cc @slluis @sevoku
> [release-8.3] [Ide] Fix ArgumentNullException when loading non-file documents

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/TextViewContent.cs
Problem was that TextBuffer still had default `TabSize` of `4` so when indentions were calculated it it was wrong in some cases.
Backport of #8668.
> [release-8.3] Fix 934342: When I press shift+tab, the selected code lines don't get un-indented

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/ThemeToClassification.cs
Using reflection is never pretty way to fix a bug, but themeing/coloring API of VS is just too old and ugly...
So for now this is solution, because alternative is so much code and potential bugs I would rather not do that...
Backport of #8661.
> [release-8.3] Fix 980541: Switching themes in Preferences corrupts colors in editor 

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/BlameView.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/DiffView.cs
Backport of #8585.
/cc @Therzok
> [release-8.3] [VCS] VSEditor uses 0 based indices, so adjust for that

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
Keyboard remapper applications can cause invalid events to be
sent to the key event handlers. Check that events passed to the keypress
handler are actually key events
Fixes VSTS #935180
Backport of #8664.
> [release-8.3] [IDE] Check that events passed to the keypress handler are key events

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkMacInterop.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Window.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/WindowCommands.cs
This PR fixes current WindowList command handler, where it was raising an exception trying to cast a NSWindow (WelcomeScreen) into a GtkWindow.
To fix this I did changes to use our current component.window abstraction instead the specific (adding some missing properties to reuse), also a small fix to ensure the the window exists (not  disposed or closed)  between this 2 menu statements (show menu and clicked)
Additionally included the fix to ensure we don't show duplicated items
To show correctly the WelcomeScreen title this PR needs https://github.com/xamarin/md-addins/pull/5346
Fixes VSTS #960819 - Exception in MacPlatformService.GetNSWindow
Fixes VSTS #976240 - Recent Windows list shows the same pad multiple times
> Fixes current WindowList command handler to show correctly opened windows

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkMacInterop.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Window.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/WindowCommands.cs
This PR fixes current WindowList command handler, where it was raising an exception trying to cast a NSWindow (WelcomeScreen) into a GtkWindow.
To fix this I did changes to use our current component.window abstraction instead the specific (adding some missing properties to reuse), also a small fix to ensure the the window exists (not  disposed or closed)  between this 2 menu statements (show menu and clicked)
Additionally included the fix to ensure we don't show duplicated items
To show correctly the WelcomeScreen title this PR needs https://github.com/xamarin/md-addins/pull/5346
Fixes VSTS #960819 - Exception in MacPlatformService.GetNSWindow
Fixes VSTS #976240 - Recent Windows list shows the same pad multiple times
Backport of #8623.
> [release-8.3] Fixes current WindowList command handler to show correctly opened windows

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git.Tests/BaseGitRepositoryTests.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitConfigurationDialog.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitService.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Subversion/MonoDevelop.VersionControl.Subversion/SubversionRepository.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/BlameView.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/BlameWidget.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/DiffView.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/Repository.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlFileSystemExtension.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionInfo.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionInfoCache.cs
We need to offset based on hunk inserted/removed lengths
Fixes VSTS 978853 - [VersionControl] GitRepository: Error retrieving history System.ArgumentException: Offset and length were out of bounds
Fixes VSTS #977874 - Renaming file makes intellisense disapear when project has .git
Fixes VSTS #787121 - [Watson] Git commands are run on the UI thread, causing the UI to hang
Backport of #8682.
/cc @Therzok
> [release-8.3] [Git] Fix blame command on mixed hunks

- main/build/MacOSX/Entitlements.plist
- main/build/MacOSX/Makefile.am
- main/build/MacOSX/render.cs
This puts in the necessary changes to make VSMac function after turning on the hardened runtime flag.
Backport of #8396
cc @duncanmak
Fixes VSTS #962402
> [release-8.2-xcode11] Enable notarization

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.NodeBuilders/FrameworkReferencesNode.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests.csproj
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DependencyNodeTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/FakeUpdatedPackagesInWorkspace.cs
The Frameworks folder for .NET Core 3.0 and .NET Standard 2.1
projects would show an update count label if the project had package
updates. Framework references cannot be updated in the IDE, and also
are not typically defined in the project itself, so the update count
should not be shown.
Fixes VSTS #980887 - Frameworks node under dependencies has a message
about updates next to it
> [DotNetCore] Do not show update count label on Frameworks folder

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.NodeBuilders/FrameworkReferencesNode.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.NodeBuilders/FrameworkReferencesNodeBuilder.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests.csproj
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DependencyNodeTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/FakeUpdatedPackagesInWorkspace.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/TestableFrameworkReferencesNodeBuilder.cs
- main/tests/test-projects/DotNetCoreDependenciesFolder/NetCore30JsonNet.csproj
- main/tests/test-projects/DotNetCoreDependenciesFolder/NetStandard21JsonNet.csproj
Backport of #8691
The Frameworks folder for .NET Core 3.0 and .NET Standard 2.1
projects would show an update count label if the project had package
updates. Framework references cannot be updated in the IDE, and also
are not typically defined in the project itself, so the update count
should not be shown.
Fixes VSTS #980887 - Frameworks node under dependencies has a message
about updates next to it
> [release-8.3][DotNetCore] Do not show update count label on Frameworks folde

- main/src/addins/CSharpBinding/MonoDevelop.CSharp/CSharpPathedDocumentExtension.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp/PathedDocumentTextEditorExtension.cs
- main/src/addins/Xml/Editor/BaseXmlEditorExtension.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Control.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputWidget.cs
DropDownListBox is actually a Window, so use that as the type when adding to the table, not plain Control.
This prevents duplicates from being added to the map, and ensures the right type is added for this widget.
Fixes VSTS #976424 - Unhandled argument exception adding to ConditionalWeakTable in Components.Control
> [Core] Fix adding derived Control items to the weak map

- main/src/addins/CSharpBinding/MonoDevelop.CSharp/CSharpPathedDocumentExtension.cs
- main/src/addins/CSharpBinding/MonoDevelop.CSharp/PathedDocumentTextEditorExtension.cs
- main/src/addins/Xml/Editor/BaseXmlEditorExtension.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.BuildOutputView/BuildOutputWidget.cs
DropDownListBox is actually a Window, so use that as the type when adding to the table, not plain Control.
This prevents duplicates from being added to the map, and ensures the right type is added for this widget.
Fixes VSTS #976424 - Unhandled argument exception adding to ConditionalWeakTable in Components.Control
Backport of #8693.
/cc @Therzok
> [release-8.3] [Core] Fix adding derived Control items to the weak map

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/VersionControlDocumentInfo.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl/VersionControlDocumentController.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentView.cs
Merged back the code that updates the version control tabs when the status of a
file changes.  That code was reverted because it caused VSTS 977977, but this PR
fixes the bug that the old PR introduced.
When a controller is being initialized, the Document property may not yet be
set. This happens for example, when a designer view creates an editor view on
its own to be added to a container together with the designer. In that scenario,
the editor view is created and fully initialized before it is added to the
document. The old implementation of VersionControlDocumentController relied on
the Document property to initialize VersionControlDocumentInfo.Document, and
that was used later to get the file name. Instead, now it gets the file name
directly from the controller.
There are other …
> Fix version control view initialization issue

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreVersionTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreSystemInformation.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreVersion.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/981132
Backport of #8705.
/cc @nosami
> [release-8.3] Parse revision number out of .NET Core SDK preview version

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Tests/MonoDevelop.AspNetCore.Tests/AspNetCoreProjectTests.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreNestingRulesProvider.cs
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/977852
The current logic which determines whether FileNesting is enabled checks for the existence of the UsingMicrosoftNETSdkWeb project property.
This isn't set in a Razor Class Library project, so we also look for the RazorTargetName property which is always set in this project type (see https://docs.microsoft.com/en-us/aspnet/core/razor-pages/sdk?view=aspnetcore-2.2)
Backport of #8704.
/cc @slluis @iantoalms
> [release-8.3] Enable FileNesting support on Razor Class Library projects

- main/src/addins/MonoDevelop.HexEditor/Mono.MHex.Data/ByteBufferModel.cs
This fix introduces a change in our implementation to get a file stream for the HexEditor, because mono has an issue in FileStream implementation with the SynchronizationContext
This does not solve the mono problem, but with the Hexadecimal Editor
Fixes VSTS #978857 - [HexEditor] View failed to load. System.AggregateException:EnsureUIThread
> Fixes a System.AggregateException trying opening HexEditor document

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/SearchPopupWindow.cs
Avoid refresing the search results window too often.
Fixes bug #972204 - Too much flickering while typing in searchbar
This is a less intrusive alternative of https://github.com/mono/monodevelop/pull/8703.
> Fix flickering issue in results window

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/SearchPopupWindow.cs
Avoid refresing the search results window too often.
Fixes bug #972204 - Too much flickering while typing in searchbar
This is a less intrusive alternative of https://github.com/mono/monodevelop/pull/8703.
Backport of #8719.
/cc @slluis
> [release-8.3] Fix flickering issue in results window

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreExecutionTarget.cs
Make AspNetCoreExecutionTarget public so that we can determine the active execution target and hence preferred browser from external code
> Enable Browser Selection on Publish Part 1

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Tests/MonoDevelop.AspNetCore.Tests/AspNetCoreProjectTests.cs
It should be testing if file nesting applies to a Razor Class library
project, not if it is enabled, which is always true unless explicitly
disabled.
> [AspNetCore] Fix Razor Class Lib file nesting test

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreExecutionTarget.cs
Make AspNetCoreExecutionTarget public so that we can determine the active execution target and hence preferred browser from external code
Backport of #8725.
/cc @iantoalms
> [release-8.3] Enable Browser Selection on Publish Part 1

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/TextViewContent.Commands.cs
Allows various keyboard commands to continue working if, for example,
an editor margin contains a view that accepts input.
Backport of #8736.
> [master] TextViewContent: Only handle commands if text view has keyboard focus

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/TextViewContent.Commands.cs
Allows various keyboard commands to continue working if, for example,
an editor margin contains a view that accepts input.
> TextViewContent: Only handle commands if text view has keyboard focus

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
Fixes VSTS #983894 - Switching branches doesn't respect target framework changes
Fixes VSTS #984213 - FileWatcher sometimes stops raising events, causing files to stop reloading when external changes occur
> [Git] Fix FileService discarding events due to imbalanced freeze/thaw

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
Fixes VSTS #983894 - Switching branches doesn't respect target framework changes
Fixes VSTS #984213 - FileWatcher sometimes stops raising events, causing files to stop reloading when external changes occur
Backport of #8749.
> [release-8.3-rtw] [Git] Fix FileService discarding events due to imbalanced freeze/thaw

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
Fixes VSTS #983894 - Switching branches doesn't respect target framework changes
Fixes VSTS #984213 - FileWatcher sometimes stops raising events, causing files to stop reloading when external changes occur
Backport of #8749.
/cc @Therzok
> [release-8.3] [Git] Fix FileService discarding events due to imbalanced freeze/thaw

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/FileService.fs
Sometimes the Document.Editor property was null which caused
the whole project to not get parsed
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/984699
> [F#] Fix LanguageService exception

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/Services/FileService.fs
Sometimes the Document.Editor property was null which caused
the whole project to not get parsed
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/984699
Backport of #8756.
/cc @nosami
> [release-8.3] [F#] Fix LanguageService exception

- main/src/addins/VersionControl/MonoDevelop.VersionControl/AddinInfo.cs
Version control api has changed. This will prevent the load of version control extensions targeting old versions of the IDE.
> Break back compat of version control add-in

- main/src/addins/VersionControl/MonoDevelop.VersionControl/AddinInfo.cs
Version control api has changed. This will prevent the load of version control extensions targeting old versions of the IDE.
Backport of #8744.
/cc @slluis
> [release-8.3] Break back compat of version control add-in

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/GtkShellDocumentViewItem.cs
When attachments are added to a view, a new attachments container is
added, which has the main view as first item and the attachments as
additional items. Before inserting the main view as first item of the
attachments container we need to make sure it is detached from the
parent container, otherwise it can't be added to the new container.
Also fixed exception that may happen when a view is realized and then
quickly disposed.
Fixes VSTS #983862 - Editor goes blank if solution pad is used to move
an unsaved file to another folder
> Fix attachment view display issue

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentView.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/GtkShellDocumentViewItem.cs
When attachments are added to a view, a new attachments container is
added, which has the main view as first item and the attachments as
additional items. Before inserting the main view as first item of the
attachments container we need to make sure it is detached from the
parent container, otherwise it can't be added to the new container.
Also fixed exception that may happen when a view is realized and then
quickly disposed.
Fixes VSTS #983862 - Editor goes blank if solution pad is used to move
an unsaved file to another folder
Backport of https://github.com/mono/monodevelop/pull/8760
Backport of #8761.
/cc @slluis
> [release-8.3-rtw] Fix attachment view display issue

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
Azure DevOps Git
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/984467
I couldn't reproduce the issue but running the fetch operation on an
exclusive threat should prevent other operations from interfering.
> Fixes VSTS Bug 984467: SIGABRT when attempting to fetch a branch from

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
Azure DevOps Git
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/984467
I couldn't reproduce the issue but running the fetch operation on an
exclusive threat should prevent other operations from interfering.
Backport of #8764.
/cc @mkrueger
> [release-8.3] Fixes VSTS Bug 984467: SIGABRT when attempting to fetch a branch from

- main/src/addins/VersionControl/MonoDevelop.VersionControl/AddinInfo.cs
Version control api has changed. This will prevent the load of version control extensions targeting old versions of the IDE.
Fixes Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/985656
Backport of #8744.
/cc @slluis 
Backport of #8746.
/cc @slluis @monojenkins
> [release-8.3-rtw] [release-8.3] Break back compat of version control add-in

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Navigation/DocumentNavigationPoint.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Navigation/TextFileNavigationPoint.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Tasks/TaskStore.cs
Our navigation history seems to be broken because we are not refreshing current Line and Column of all TextFileNavigationPoint.cs items (is stays at 0).
This PR also fixes a case when the document is closed but has a TextFileNavigationPoint. We empty the doc variable for a good clean, but in case of go history of a closed document we need to re-set this property to set the cursor correctly in the line
Fixes VSTS #984818 - "Navigate Back" shorcut it's not working correctly
Backport of #8768.
> [release-8.3] Fixes current navigation history and takes care about closed documents

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Navigation/DocumentNavigationPoint.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Navigation/TextFileNavigationPoint.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Tasks/TaskStore.cs
Our navigation history seems to be broken because we are not refreshing current Line and Column of all TextFileNavigationPoint.cs items (is stays at 0).
This PR also fixes a case when the document is closed but has a TextFileNavigationPoint. We empty the doc variable for a good clean, but in case of go history of a closed document we need to re-set this property to set the cursor correctly in the line
Fixes VSTS #984818 - "Navigate Back" shorcut it's not working correctly
> Fixes current navigation history and takes care about closed documents

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.AutoTest.Results/NSObjectResult.cs
[Bug 983495:](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/983495) ArgumentNullException is triggered in NSObjectResult on Active Runtime selection in Autotest
> [AutoTest] NSObjectResult: Check for null runtimeName is added

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/SearchPopupWindow.cs
Added some locks required when accessing data that can mutate while
running the search.
Hopefully fixes VSTS #984594
> Fix crash in global search

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/SearchPopupWindow.cs
Added some locks required when accessing data that can mutate while
running the search.
Hopefully fixes VSTS #984594
Backport of #8808.
/cc @slluis
> [release-8.3] Fix crash in global search

- main/external/fsharpbinding/MonoDevelop.FSharp.Shared/Lexer.fs
- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/LexerTests.fs
Before this fix, the stack could overflow with ~12000 lines on my
machine.
Unit test is using 100000 lines without a crash
Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/988934
Backport of #8811.
/cc @nosami
> [release-8.3] [F#] Fix recursion stack overflow when parsing big files

- main/external/fsharpbinding/MonoDevelop.FSharp.Shared/Lexer.fs
- main/external/fsharpbinding/MonoDevelop.FSharp.Tests/LexerTests.fs
Before this fix, the stack could overflow with ~12000 lines on my
machine.
Unit test is using 100000 lines without a crash
Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/988934
> [F#] Fix recursion stack overflow when parsing big files

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
Advertise the NSView accessible children to the Cocoa accessibilty subsystem so that Cocoa widgets embedded inside GtkNSViewHosts will be accessible.
This is the `GtkNSViewHost` part from #8502 by @netonjm 
Fixes VSTS #977183 - [DockSystem] Accessibility VoiceOver hierarchy seems to be broken for Embedded native views
> [A11y] Make GtkNSViewHost accessible

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FakeSearchCategory.fs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/CommandSearchCategory.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbarController.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/SearchPopupWindow.cs
This avoids unneeded global search hiding and redrawing
so that we actually don't need to throttle the incoming results
to avoid flickering.
This reverts 731915e557e92dfe7333a1fab6cd37335aae1583 introduced in https://github.com/mono/monodevelop/pull/8719
Fixes VSTS #972204
Fixes VSTS #982384
Fixes VSTS #984594
Fixes VSTS #985811
> [Ide] Improve global search result reporting even more

- main/src/addins/MonoDevelop.UnitTesting/MonoDevelop.UnitTesting.VsTest/VsTestProjectTestSuite.cs
When UnitTestService is running the tests, for VsTest, it is using the old tests before all test information is refreshed.
In UnitTestGroup.Refresh(), Tests collection is accessed which triggered VsTestProjectTestSuite’s `OnCreateTests()`. However it will return the control to the calling thread once `VsTestDiscoveryAdapter.Instance.DiscoverTestsAsync (Project);` is called. This causes the tests not properly refreshed.
For the fix, a new method `DiscoverTestAsync()`is created, which does the same thing as old `OnCreateTests()` does, but returns a Task. Local variable `testDiscoveryTask` is created and shared by `OnCreateTests()` and `Refresh()`. We use it to know when `Refresh()` can return.
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/967657/
> [Unit Tests] avoid running old tests in VsTestProjectTestSuite

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
Runtime.GetNSObject does a null check
> Add null check for accessibility and remove redundant one

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DotNetCoreVersionTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/DotNetCoreVersion.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/987887
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/986987
Backport of #8797.
/cc @nosami
> [release-8.3] Don't throw exception for invalid dotnet core version

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FakeSearchCategory.fs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/CommandSearchCategory.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbarController.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/SearchPopupWindow.cs
This avoids unneeded global search hiding and redrawing
so that we actually don't need to throttle the incoming results
to avoid flickering.
This reverts 731915e557e92dfe7333a1fab6cd37335aae1583 introduced in https://github.com/mono/monodevelop/pull/8719
Fixes VSTS #972204
Fixes VSTS #982384
Fixes VSTS #984594
Fixes VSTS #985811
Backport of #8786.
/cc @sevoku
> [release-8.3] [Ide] Improve global search result reporting even more

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/ProjectPackageReferenceTests.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/DotNetProjectExtensions.cs
Handle a null Project.MSBuildProject when the NuGet addin's
GetInstalledPackages API is called.
```
System.NullReferenceException
Object reference not set to an instance of an object
MonoDevelop.PackageManagement.DotNetProjectExtensions.GetDotNetCoreTargetFrameworks(Project)
MonoDevelop.PackageManagement.ProjectPackageReference.GetFramework()
MonoDevelop.PackageManagement.ProjectPackageReference.CreatePackageReference()
MonoDevelop.PackageManagement.PackageReferenceNuGetProject.<>c.<GetPackageReferences>b__XXX(ProjectPackageReference)
System.Linq.Enumerable.SelectEnumerableIterator`2[[MonoDevelop.PackageManagement.ProjectPackageReference, MonoDevelop.PackageManagement, Version=1.0.0.0, Culture=neutral, PublicKeyToken=3ead7498f347467b],[NuGet.Packaging.PackageReference, NuGet.Packaging, …
```
> [release-8.3] [NuGet] Handle NuGet addin API used when project disposed

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
The check for an empty `NSEvent.Characters` is too exhaustive for attempting to validate an event. The explicit check for Key Up/Down should be enough.
Apple documentation states that dead keys will result in an empty string for `NSEvent.Characters`, but these keys should be allowed to be processed as well by commanding.
This fixes a regression introduced in #8664.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/985131
> Fix 985131: Unable to pull up the emoji selector

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
The check for an empty `NSEvent.Characters` is too exhaustive for attempting to validate an event. The explicit check for Key Up/Down should be enough.
Apple documentation states that dead keys will result in an empty string for `NSEvent.Characters`, but these keys should be allowed to be processed as well by commanding.
This fixes a regression introduced in #8664.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/985131
Backport of #8832.
/cc @abock
> [release-8.3] Fix 985131: Unable to pull up the emoji selector

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices.Options/RoslynPreferences.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.RoslynServices.Options/RoslynPreferencesTests.cs
```
The given key 'XAML' was not present in the dictionary.
["System.ThrowHelper.GetKeyNotFoundException(Object)","System.ThrowHelper.ThrowKeyNotFoundException(Object)","System.Collections.Generic.Dictionary`2[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[MonoDevelop.Ide.RoslynServices.Options.RoslynPreferences.PerLanguagePreferences, MonoDevelop.Ide, Version=2.6.0.0, Culture=neutral, PublicKeyToken=3ead7498f347467b]].get_Item(String)","MonoDevelop.Ide.RoslynServices.Options.RoslynPreferences.For(String)","MonoDevelop.Ide.TypeSystem.MonoDevelopWorkspace.IsUserOptionOn()","MonoDevelop.Ide.TypeSystem.MonoDevelopWorkspace.OnMemoryStatusChanged(Object,PlatformMemoryStatusEventArgs)","System.CoreExtensions.SafeInvoke[PlatformMemoryStatusEventArgs] …
```
> [Roslyn] Fix support for non-roslyn language name

- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/LocalCopyTests.cs
Mono 2019-08 v6.6.0.104 changed the compiler used to build gtk-sharp from `mcs` to `csc`.
As a result, we do not have .mdb files anymore, rather the normal .pdb.
This fixes the test to look for the right file.
> [Core] Fix test to work with new gtk-sharp.dll.pdb

- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/LocalCopyTests.cs
Mono 2019-08 v6.6.0.104 changed the compiler used to build gtk-sharp from `mcs` to `csc`.
As a result, we do not have .mdb files anymore, rather the normal .pdb.
This fixes the test to look for the right file.
Backport of #8845.
/cc @kdubau
> [release-8.4] [Core] Fix test to work with new gtk-sharp.dll.pdb

- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/IToolboxWidget.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/MacToolbox.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/MacToolboxViewItems.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/MacToolboxWidget.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/MacToolboxWidgetFlowLayoutDelegate.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/NativeViews/ClickedButton.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/NativeViews/SearchTextField.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/NativeViews/ToggleButton.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/KeyCodes.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/VerticalAlignmentTextCell.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
This include some fixes and code clean for the Toolbox
* Fixes Bug #971161 - [Toolbox] Bad alignment in "There are no tools available for the current " label
* Fixes Bug #935560 - [Toolbox] Tab key to change between views seems to be broken
* Fixes Bug #752358: Accessibility: Toolbox Pad: Toolbox button is not accessible by keyboard as it is not receiving focus while tabbing and shift tabbing
* Fixes Bug #972118 - [Toolbox] Selected item color it's not working when item has no focus
* Fixes Bug #972184 - [Toolbox] Filtering is not leaving the current selected item
> [Toolbox][a11y] Some accessibility fixes

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/NSViewExtensions.cs
The method is implemented in XamMac, no need to duplicate the implementation
Fixes VSTS #973862 - Type forward NSViewExtensions.SortSubviews to Xamarin.Mac
> [Ide] Mark NSViewExtensions as obsolete and remove it in future versions

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Window.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/ProgressDialog.cs
all applications
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/983399
ProgressDialog didn't had the parent set. In VS4Mac the parent is a
NSWindow so it's needed to set the parent in that case after the gtk
window has been created.
> Fixes VSTS Bug 983399: [VersionControl] Credential dialog is on top of

- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/SearchAndReplaceWidget.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/SearchInSolutionSearchCategory.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Components/LogView.cs
Fixes VSTS #611793 - quit re-defaulting to case sensitive search #4727
By default, in MonoDevelop preferences, the "Automatically Set Pattern Casing" setting is off. However, in the product code when retrieving this setting it's defaulting to enable it. This change modifies the default value (when retrieving this setting from the PropertyService) to match the default setting show in preferences. As I confirmed this worked in the legacy editor, I also found that the Search in Solution feature from the search box also displayed this bug, likewise for the Find for log views.
I've tested and confirmed that search is now case insensitive until Automatically Set Pattern Casing is enabled in preferences by the user. This also matches the behavior in the new editor.
> Fixes VSTS #611793 - quit re-defaulting to case sensitive search #4727

- main/src/addins/VersionControl/MonoDevelop.VersionControl/MonoDevelop.VersionControl.Views/EditorCompareWidgetBase.cs
Over was not reading anything when the focus moves to the vertical
scroll bars in the "Changes" window and the central section which
shows differences.
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/810270
Removed scroll bars from the list.
> Fixes VSTS Bug 810270: Accessibility: Version Control - Changes: Voice

- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/AssemblyBrowserViewContent.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/TypeSystemService_WorkspaceHandling.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/TypeSystemService_WorkspaceRequestRegistration.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.csproj
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/RootWorkspace.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.TypeSystem/TypeSystemServiceTests.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.TypeSystem/WorkspaceFilesCacheTests.cs
- main/tests/Ide.Tests/MonoDevelop.Ide/TypeSystemServiceTests.cs
- main/tests/IdeUnitTests/ProjectTemplateTest.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/DotNetCoreFileWatcherTests.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/DotNetCoreProjectTests.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/MultiTargetProjectTests.cs
- main/tests/MonoDevelop.Core.Tests/MonoDevelop.Projects/ProjectTests.cs
- main/tests/UnitTests/Util.cs
Refactor the current code to move the workspace registrations from TypeSystemService
into Solution.ExtendedProperties.
This way, we can keep track of all the registrations done for a solution, and cancel
all of them whenever a solution is disposed.
The second part of the PR is splitting each request into its own TaskCompletionSource.
Reusing the same task has unintended side effects due to the cancellation token being
passed as a parameter.
Using the same task meant that if some CancellationTokenSource decided to cancel its
request, it would cancel all the current active requests on the solution
Fixes VSTS #977144 - Leak detected on cleanup iteration in MonoDevelop.Projects.Solution class
Fixes VSTS #977335 - Quality of local testing
> [Ide] Rework GetWorkspaceAsync to cancel requests on any solution dispose

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
First of all, DateTime.Now is culture aware, and applies culture information to actually get the value, so it's really slow.
Secondly, it's really low resolution. Use Stopwatch to get better elapsed time for command activation
> [Ide] Switch command activation to use a stopwatch instead of DateTime

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/CocoaTextViewContent.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
`ObjectDisposedException` when closing TextEditor
Problem was with recent work to garbage collect memory of new editor, .Dispose were called from TextView.Close method, which disposed controls too early so now, when GtkHost is destroyed we also call NSView.Dispose so native controls are disposed a little later then before so accesses shouldn't happen after this point.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/997787
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/992438
> Fix 997787 and Fix 992438

- main/src/addins/MacPlatform/Dialogs/MacAddFileDialogHandler.cs
- main/src/addins/MacPlatform/Dialogs/MacOpenFileDialogHandler.cs
- main/src/addins/MacPlatform/Dialogs/MacSelectFileDialogHandler.cs
See for details: xamarin/xamarin-macios#6474
This reverts 508796b
Reopening VSTS #859111
Fixes VSTS #989519
Backport of #8877
> [8.3][Mac] Use static NSSavePanel.SavePanel to avoid crashes on Catalina

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectCellViewBase.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1000540
Backport of #8885.
/cc @jstedfast
> [release-8.4] [Debugger] Fixed an NRE font crash

- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/PropertyPadVisitor.cs
Fixes #999288 - Native Property Pad switches context when it loses focus
> Don't allow Reset current property pad in case of item focused changed

- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/PropertyPadVisitor.cs
Fixes #999288 - Native Property Pad switches context when it loses focus
Backport of #8883.
> [release-8.4] Don't allow Reset current property pad in case of item focused changed

- main/src/addins/MacPlatform/Dialogs/MacCommonFileDialogHandler.cs
This problem happens only in Catalina, in a first try I thought it was something about bindings or new behaviour but investigating I tested in a real xcode swift application and I can reproduce the issue. 
The problem only happens when we set the parent in any NSSavePanel. This breaks the accessory view (no matter the complexity). I think we'll need wait a fix in cocoa. 
switft code: https://gist.github.com/netonjm/c2f526e6df8143281448ccf461a64221
To try speed up this I also opened an issue in Apple Feedback : 
https://feedbackassistant.apple.com/feedback/7380159
That's how it feels now.
Open Dialog
Fixes VSTS #1000498 - Open/Save File dialog accessory views not visible on Catalina
> [Catalina] Fixes broken accessory view in any NSSavePanel based panels (Cocoa bug)

- main/src/addins/MacPlatform/Dialogs/MacCommonFileDialogHandler.cs
This problem happens only in Catalina, in a first try I thought it was something about bindings or new behaviour but investigating I tested in a real xcode swift application and I can reproduce the issue. 
The problem only happens when we set the parent in any NSSavePanel. This breaks the accessory view (no matter the complexity). I think we'll need wait a fix in cocoa. 
switft code: https://gist.github.com/netonjm/c2f526e6df8143281448ccf461a64221
To try speed up this I also opened an issue in Apple Feedback : 
https://feedbackassistant.apple.com/feedback/7380159
That's how it feels now.
Open Dialog
Fixes VSTS #1000498 - Open/Save File dialog accessory views not visible on Catalina
Backport of #8923.
> [release-8.4] [Catalina] Fixes broken accessory view in any NSSavePanel based panels (Cocoa bug)

- main/src/addins/MacPlatform/Dialogs/MacCommonFileDialogHandler.cs
This problem happens only in Catalina, in a first try I thought it was something about bindings or new behaviour but investigating I tested in a real xcode swift application and I can reproduce the issue. 
The problem only happens when we set the parent in any NSSavePanel. This breaks the accessory view (no matter the complexity). I think we'll need wait a fix in cocoa. 
switft code: https://gist.github.com/netonjm/c2f526e6df8143281448ccf461a64221
To try speed up this I also opened an issue in Apple Feedback : 
https://feedbackassistant.apple.com/feedback/7380159
That's how it feels now.
Open Dialog
Fixes VSTS #1000498 - Open/Save File dialog accessory views not visible on Catalina
Backport of #8923.
> [release-8.3] [Catalina] Fixes broken accessory view in any NSSavePanel based panels (Cocoa bug)

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.Tests/ObjectValueTreeViewControllerTests.cs
Increase the timeout used before evaluating results to give the
ObjectValue timers time to actually complete.
> [Debugger] FIxed the ObjectValueTreeViewController unit tests

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/GtkShellDocumentViewContainerTabs.cs
Fixes VSTS #1002168 - [VS for Mac]The split tab is empty in Xamarin.Forms project
Backport of #8950.
> [release-8.4-preview1] [Ide] Fix document tabs container disposing widgets on mode change

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/GtkShellDocumentViewContainerTabs.cs
Fixes VSTS #1002168 - [VS for Mac]The split tab is empty in Xamarin.Forms project
> [Ide] Fix document tabs container disposing widgets on mode change

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/GtkShellDocumentViewContainerTabs.cs
Fixes VSTS #1002168 - [VS for Mac]The split tab is empty in Xamarin.Forms project
Backport of #8950.
/cc @Therzok
> [release-8.4] [Ide] Fix document tabs container disposing widgets on mode change

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Gui/DotNetCoreSdkLocationWidget.UI.cs
In Preferences - Projects - SDK Locations - .NET Core, opening
the open file dialog and then closing it would end up with the
Preferences dialog not having focus. This only happens when the IDE
window is open. When the Start Window is open then the focus goes
back to the Preferences dialog. To reproduce this tab to the browse
button, press space to open the open file dialog, then press
escape. The focus should be on the browse button, but the dialog
does not have the focus so tabbing does not move around the dialog.
To fix this the dialog is explicitly focussed after the select file
dialog is closed. Note that the SDK locations dialog uses the XWT
OpenFileDialog which does not set the focus back to its parent. The
MonoDevelop.Components.SelectFileDialog will set focus back to its …
> [DotNetCore] Fix focus in SDK locations options page

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor/Properties/MonoDevelop.TextEditor.addin.xml
Depends on an upcoming editor update to actually handle this command.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1001949
Backport of #8935.
> [release-8.4] Editor: Support for ShowQuickInfo command

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.OptionPanels/RunConfigurationsPanel.cs
Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/752629
After pressing Enter on configuration selection, focus now goes to the first control of the Panel.
> [752629] [RunConfigurationsOptionsPanel] Fix keyboard focus after configuration selection

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.Tests/ObjectValueTreeViewControllerTests.cs
Increase the timeout used before evaluating results to give the
ObjectValue timers time to actually complete.
Backport of #8956.
/cc @jstedfast
> [release-8.4] [Debugger] FIxed the ObjectValueTreeViewController unit tests

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectCellViewBase.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectNameView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectValueView.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/999602/
Backport of #8970.
/cc @jstedfast
> [release-8.4] [Debugger] Use the ~sel icon variants when the row is selected

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/PlatformService.cs
It's a change for https://github.com/xamarin/md-addins/pull/5698. 
- added `AccessibilityInUseChanged ` event
Backport of #8974.
> [release-8.4] [PlatformService] Added `AccessibilityInUseChanged`

- main/msbuild/RoslynVersion.props
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.OptionProvider/StyleViewModel.cs
Updating Roslyn to 20191018.2 (7c7708e)
Changes since [5ca9538](https://www.github.com/dotnet/roslyn/commit/5ca9538):
- [Add test for #34921 (#39365)](https://www.github.com/dotnet/roslyn/pull/39365)
- [Merge pull request #39127 from mavasani/SolutionItemEditorConfig](https://www.github.com/dotnet/roslyn/pull/39127)
- [Use ConstructWithNullability in InferTypeInAwaitExpression since the inferred type may include nullable information (#39335)](https://www.github.com/dotnet/roslyn/pull/39335)
- [Ensure synthesized closure method is static for static local function (#38147)](https://www.github.com/dotnet/roslyn/pull/38147)
- [Skip RenamingEscapedIdentifiers (#39330)](https://www.github.com/dotnet/roslyn/pull/39330)
- [Do not wait for output writer thread to complete when aborting execution …
> Bump Roslyn to 3.4.0-beta3-19518-02

- main/msbuild/RoslynVersion.props
- main/src/addins/CSharpBinding/MonoDevelop.CSharp.OptionProvider/StyleViewModel.cs
Updating Roslyn to 20191018.2 (7c7708e)
Changes since [5ca9538](https://www.github.com/dotnet/roslyn/commit/5ca9538):
- [Add test for #34921 (#39365)](https://www.github.com/dotnet/roslyn/pull/39365)
- [Merge pull request #39127 from mavasani/SolutionItemEditorConfig](https://www.github.com/dotnet/roslyn/pull/39127)
- [Use ConstructWithNullability in InferTypeInAwaitExpression since the inferred type may include nullable information (#39335)](https://www.github.com/dotnet/roslyn/pull/39335)
- [Ensure synthesized closure method is static for static local function (#38147)](https://www.github.com/dotnet/roslyn/pull/38147)
- [Skip RenamingEscapedIdentifiers (#39330)](https://www.github.com/dotnet/roslyn/pull/39330)
- [Do not wait for output writer thread to complete when aborting execution …
> [release-8.4] Bump Roslyn to 3.4.0-beta3-19518-02

- main/src/addins/MacPlatform/MacTelemetryDetails.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Desktop/IPlatformTelemetryDetails.cs
creating new pull request to backport https://github.com/mono/monodevelop/pull/8960 to 8.4 since the monodevelop and mdaddins branches have to have same names
> Added machine hardware model to telemetry details

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.DockNotebook/TabStrip.cs
Fixes VSTS #984216 - [Tabs] Pin button is really close from Close button when there are many tabs in the TabStrip
> Fixes pin tab separation on smaller tabs

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.DockNotebook/TabStrip.cs
Fixes VSTS #984216 - [Tabs] Pin button is really close from Close button when there are many tabs in the TabStrip
Backport of #8914.
> [release-8.4] Fixes pin tab separation on smaller tabs

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Gui/AddPackageSourceDialog.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Gui/PackageSourcesWidget.cs
In Preferences - NuGet - Sources, the Add Package Source dialog
would lose focus when the Browse button was used. A way to reproduce
this is to tab to the Add button, press space, then tab to the
Browse button in the Add Package Source dialog, press space, then
press escape. The Add Package Source dialog then no longer has focus
and tabbing does not work.
Fixed this by explicitly setting focus back to the parent dialog
when a child dialog is closed.
Fixes VSTS #1003430 - Accessibility: NuGet add package source dialog
browse button loses dialog focus
> [NuGet] Fix dialog loss of focus on adding new package source

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Gui/AddPackageSourceDialog.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Gui/PackageSourcesWidget.cs
In Preferences - NuGet - Sources, the Add Package Source dialog
would lose focus when the Browse button was used. A way to reproduce
this is to tab to the Add button, press space, then tab to the
Browse button in the Add Package Source dialog, press space, then
press escape. The Add Package Source dialog then no longer has focus
and tabbing does not work.
Fixed this by explicitly setting focus back to the parent dialog
when a child dialog is closed.
Fixes VSTS #1003430 - Accessibility: NuGet add package source dialog
browse button loses dialog focus
Backport of #8973.
/cc @mrward
> [release-8.4] [NuGet] Fix dialog loss of focus on adding new package source

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.csproj
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/ExpressionEventArgs.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/ObjectValueTreeViewController.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/WatchPad.cs
This avoids scenarios where we clear the expressions list thereby
losing all known expressions.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1002638/
Backport of #8967.
/cc @jstedfast
> [release-8.4] [Debugger] Fixed tracking of current expressions in Watch Pad

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitCredentials.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
SSH credentials are prefered now over username/password.
Fixed deadlock when getting credentials from extensions.
Fixes VSTS #993869
> [Git] Azure DevOps Git Clone Hangs

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitCredentials.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
SSH credentials are prefered now over username/password. That fixes the problem.
Fixes VSTS #993869
Backport of #8906.
> [release-8.3] [Git] Azure DevOps Git Clone Hangs

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitCredentials.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
SSH credentials are prefered now over username/password. That fixes the problem.
Fixes VSTS #993869
Backport of #8906.
> [release-8.4] [Git] Azure DevOps Git Clone Hangs

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Tabstrip.cs
See: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/810343
https://github.com/mono/monodevelop/pull/8925
Didn't know that Accessibility can be == null.
Fixes VSTS #1005254 - File content isn't displayed after opening
> [Ide] Fixed possible null reference exception.

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Debugger/DebuggerCompletionController.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding.Debugging/DebuggerCompletionControllerTests.cs
Fixes VSTS 958245
System.ArgumentOutOfRangeException exception in Microsoft.VisualStudio.Text.Implementation.BinaryStringRebuilder.GetLineFromLineNumber()
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/958245
---
I think the location end line is '1' based from where we subtract 1 from it to GetLineFromLineNumber but I might be wrong there.
> [Debugger] Handle case when the text snapshot has less lines than the breakpoint location

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Gui/ManagePackagesDialog.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.Helpers/FakeNuGetPackageManager.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.Helpers/FakeNuGetProjectContext.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.Helpers/FakePackageRestoreManager.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.Helpers/TestableUpdateMultipleNuGetPackagesAction.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.csproj
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/InstallPackageWithAvailableItemNameTests.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/ManagePackagesViewModelTests.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/UpdateMultipleNuGetPackagesActionTests.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/UpdateStrictPackageDependenciesTests.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/UpdateXamarinFormsBuildTest.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.csproj
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/INuGetPackageManager.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/ManagePackagesViewModel.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/MonoDevelopBuildIntegratedRestorer.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/MonoDevelopNuGetPackageManager.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/ProjectReferenceMaintainerCollection.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/UpdateAllNuGetPackagesInProjectAction.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/UpdateMultipleNuGetPackagesAction.cs
- main/tests/test-projects/NuGetUpdateAvailableItems/NuGetUpdateAvailableItems.sln
- main/tests/test-projects/NuGetUpdateAvailableItems/PackageReferenceProject/PackageReferenceProject.csproj
- main/tests/test-projects/NuGetUpdateAvailableItems/SdkStyleProject/SdkStyleProject.csproj
- main/tests/test-projects/StrictNuGetDependency/StrictNuGetDependency.csproj
- main/tests/test-projects/StrictNuGetDependency/StrictNuGetDependency.csproj-saved
- main/tests/test-projects/StrictNuGetDependency/StrictNuGetDependency.sln
Updating two NuGet package references that have a strict dependency
on a single version of another NuGet package not explicitly added
to the project would fail in the Manage NuGet Packages dialog. This
was because the update would be done one package at a time. Doing
the update of the two NuGet packages together allows NuGet to
update both so they then use the new strict dependency.
Note that updating all packages in the project from the Solution
window does not have this problem since there the packages are
updated together in a batch.
Fixes VSTS #986960 - Solution nuget updater fails to update a set of
packages that all have a related dependency update
> [NuGet] Update multiple packages together in a batch

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Gui/ManagePackagesDialog.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.Helpers/FakeNuGetPackageManager.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.Helpers/FakeNuGetProjectContext.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.Helpers/FakePackageRestoreManager.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.Helpers/TestableUpdateMultipleNuGetPackagesAction.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests.csproj
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/InstallPackageWithAvailableItemNameTests.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/ManagePackagesViewModelTests.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/UpdateMultipleNuGetPackagesActionTests.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/UpdateStrictPackageDependenciesTests.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Tests/MonoDevelop.PackageManagement.Tests/UpdateXamarinFormsBuildTest.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.csproj
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/INuGetPackageManager.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/ManagePackagesViewModel.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/MonoDevelopBuildIntegratedRestorer.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/MonoDevelopNuGetPackageManager.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/ProjectReferenceMaintainerCollection.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/UpdateAllNuGetPackagesInProjectAction.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/UpdateMultipleNuGetPackagesAction.cs
- main/tests/test-projects/NuGetUpdateAvailableItems/NuGetUpdateAvailableItems.sln
- main/tests/test-projects/NuGetUpdateAvailableItems/PackageReferenceProject/PackageReferenceProject.csproj
- main/tests/test-projects/NuGetUpdateAvailableItems/SdkStyleProject/SdkStyleProject.csproj
- main/tests/test-projects/StrictNuGetDependency/StrictNuGetDependency.csproj
- main/tests/test-projects/StrictNuGetDependency/StrictNuGetDependency.csproj-saved
- main/tests/test-projects/StrictNuGetDependency/StrictNuGetDependency.sln
Updating two NuGet package references that have a strict dependency
on a single version of another NuGet package not explicitly added
to the project would fail in the Manage NuGet Packages dialog. This
was because the update would be done one package at a time. Doing
the update of the two NuGet packages together allows NuGet to
update both so they then use the new strict dependency.
Note that updating all packages in the project from the Solution
window does not have this problem since there the packages are
updated together in a batch.
Fixes VSTS #986960 - Solution nuget updater fails to update a set of
packages that all have a related dependency update
Backport of #8818.
/cc @mrward
> [release-8.4] [NuGet] Update multiple packages together in a batch

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreProjectExtension.cs
When loading a ASP.NET Core project, OnCreateRunConfiguration is called
for the "Default" config, and the ASP.NET Core implementation does the
syncing of the launchSettings.json file, in which case it enumerates
the existing RunConfigurations in the Project, which in turn calls
again OnCreateRunConfiguration to create the "Default" again.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1005086
> [AspNetCore] Avoid exception when saving run configurations

- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/PropertyPad.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
Basically the problem was we didn't have a mechanism to hide **custom property panels** in case of DockSystem needs hide a Pad for some reason (like relayout or unexpected tab change). Now with the native embeded views we need not only hide the GtkViewHost but also the contained native view.
Fixes VSTS #1001720 - Property Panel overlays Document Outline pane when opening new Xaml files
1) Open a Xaml Forms Project, close all Xaml Files.
2) Select the Properties Tab
3) Open a Xaml File
4) Select the Document Outline Tab
5) Open a second Xaml File
> Fixes overlapping in custom native property pad on PadContentShown/Hidden

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreProjectExtension.cs
When loading a ASP.NET Core project, OnCreateRunConfiguration is called
for the "Default" config, and the ASP.NET Core implementation does the
syncing of the launchSettings.json file, in which case it enumerates
the existing RunConfigurations in the Project, which in turn calls
again OnCreateRunConfiguration to create the "Default" again.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1005086
Backport of #9038.
/cc @rodrmoya
> [release-8.4] [AspNetCore] Avoid exception when saving run configurations

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/QuickInfo/DebuggerQuickInfoSource.cs
After the context switch to the main thread in order to show the tooltip,
check that the request hasn't been cancelled due to the editor window
being closed in the meantime (for example).
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1002160/
> [Debugger] Make sure tooltip request wasn't cancelled before showing

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.ProjectData.cs
All those workspace references are not necessary to be passed along
> [Ide] Clean a bit of the ProjectData implementation

- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/PropertyPad.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
Basically the problem was we didn't have a mechanism to hide **custom property panels** in case of DockSystem needs hide a Pad for some reason (like relayout or unexpected tab change). Now with the native embeded views we need not only hide the GtkViewHost but also the contained native view.
Fixes VSTS #1001720 - Property Panel overlays Document Outline pane when opening new Xaml files
1) Open a Xaml Forms Project, close all Xaml Files.
2) Select the Properties Tab
3) Open a Xaml File
4) Select the Document Outline Tab
5) Open a second Xaml File
Backport of #8922.
> [release-8.4] Fixes overlapping in custom native property pad on PadContentShown/Hidden

- main/src/addins/MacPlatform/MainToolbar/MainToolbar.cs
Fixes NRE focusing main toolbar in early initializations when the window is not yet attached to the view
Fixes VSTS #1002143 - [FATAL] System.NullReferenceException exception in MonoDevelop.MacIntegration.MainToolbar.MainToolbar.Focus()
Backport of #9023.
/cc @netonjm
> [release-8.4] Fixes NRE focusing main toolbar in early initializations when the window is not yet attached to the view

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.ProjectData.cs
All those workspace references are not necessary to be passed along
Backport of #8998.
/cc @Therzok
> [release-8.4] [Ide] Clean a bit of the ProjectData implementation

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectValueView.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1004949/
Backport of #9061.
/cc @jstedfast
> [release-8.4] [Debugger] Node.Value can be null, if it is, use string.Empty

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeView.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1008045/
Backport of #9088.
/cc @jstedfast
> [release-8.4] [Debugger] ViewAtColumn can return null so protect against that

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Debugger/DebuggerCompletionController.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding.Debugging/DebuggerCompletionControllerTests.cs
Fixes VSTS 958245
System.ArgumentOutOfRangeException exception in Microsoft.VisualStudio.Text.Implementation.BinaryStringRebuilder.GetLineFromLineNumber()
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/958245
---
I think the location end line is '1' based from where we subtract 1 from it to GetLineFromLineNumber but I might be wrong there.
Backport of #8933.
/cc @sgmunn
> [release-8.4] [Debugger] Handle case when the text snapshot has less lines than the breakpoint location

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.OptionPanels/RunConfigurationsPanel.cs
Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/752629
After pressing Enter on configuration selection, focus now goes to the first control of the Panel.
Backport of #8946.
/cc @sevoku @Semptra
> [release-8.4] [752629] [RunConfigurationsOptionsPanel] Fix keyboard focus after configuration selection

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Tests/MonoDevelop.AspNetCore.Tests/AspNetCoreProjectTests.cs
It should be testing if file nesting applies to a Razor Class library
project, not if it is enabled, which is always true unless explicitly
disabled.
Backport of #8729.
/cc @rodrmoya
> [release-8.3] [AspNetCore] Fix Razor Class Lib file nesting test

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/EnvironmentVariableCollectionEditor.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.OptionPanels/AssemblyRunConfigurationEditor.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.OptionPanels/ProcessRunConfigurationEditor.cs
Fixes VSTS 752769 in conjunction with https://github.com/mono/xwt/pull/987
Accessibility: Project Options - Run Configuration: No on-screen or programmatically associated label provided for the edit fields.
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/752769
> [Project] Make Run Configurations accessible

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/EnvironmentVariableCollectionEditor.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.OptionPanels/AssemblyRunConfigurationEditor.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.OptionPanels/ProcessRunConfigurationEditor.cs
Fixes VSTS 752769 in conjunction with https://github.com/mono/xwt/pull/987
Accessibility: Project Options - Run Configuration: No on-screen or programmatically associated label provided for the edit fields.
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/752769
Backport of #8965.
/cc @sevoku @sgmunn
> [release-8.4] [Project] Make Run Configurations accessible

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeView.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1008367/
> [Debugger] Make sure SelectedRow isn't -1 when renaming an expression

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeView.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1008367/
Backport of #9112.
/cc @jstedfast
> [release-8.4] [Debugger] Make sure SelectedRow isn't -1 when renaming an expression

- main/build/MacOSX/BinaryCheckerConfig.txt
Monodroid includes MSBuild.Workspace, which is confusing the checker. Ignore it to be able to build.
> Ignore MSBuild.Workspaces

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/BreakpointPropertiesDialog.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/Styles.cs
> [Debugger] Fix color contrast of secondary labels in breakpoint props dialog

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/BreakpointPropertiesDialog.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/Styles.cs
Fixes VSTS #754224
Backport of #9142.
/cc @sevoku
> [release-8.4] [Debugger] Fix color contrast of secondary labels in breakpoint props dialog

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.NodeBuilders/DependenciesNode.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.NodeBuilders/FrameworkReferenceNodeCache.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.NodeBuilders/FrameworkReferencesNode.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.NodeBuilders/TargetFrameworkNode.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DependencyNodeTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/TestableTargetFrameworkNodeBuilder.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/TargetFrameworkExtensions.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/TargetFrameworkMonikerExtensions.cs
- main/tests/test-projects/DotNetCoreDependenciesFolder/NetStandard21NetStandard20NetCore30NetCore21.csproj
If a multi-target project used .NET Standard 2.1, or .NET Core 3.0, and
an older framework such as .NET Standard 2.0, or .NET Core 2.1, then
the Solution window would not show the correct folders under the
Dependencies folder. If the first target framework was .NET Standard
2.0 then an SDK folder would be displayed for all frameworks. If the
first target framework was .NET Standard 2.1 then a Frameworks folder
would be displayed for all frameworks.
The problem was that there was no multi-target support for
FrameworkReferences. Each framework that supports FrameworkReferences
needs to have the ResolveFrameworkReferences MSBuild target called
separately. Also all project target frameworks are checked individually
when building the Solution window tree nodes. Previously the first
target …
> [DotNetCore] Fix incorrect folders displayed for multi-target projects

- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.NodeBuilders/DependenciesNode.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.NodeBuilders/FrameworkReferenceNodeCache.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.NodeBuilders/FrameworkReferencesNode.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.NodeBuilders/TargetFrameworkNode.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/DependencyNodeTests.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore.Tests/MonoDevelop.DotNetCore.Tests/TestableTargetFrameworkNodeBuilder.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/TargetFrameworkExtensions.cs
- main/src/addins/MonoDevelop.DotNetCore/MonoDevelop.DotNetCore/TargetFrameworkMonikerExtensions.cs
- main/tests/test-projects/DotNetCoreDependenciesFolder/NetStandard21NetStandard20NetCore30NetCore21.csproj
If a multi-target project used .NET Standard 2.1, or .NET Core 3.0, and
an older framework such as .NET Standard 2.0, or .NET Core 2.1, then
the Solution window would not show the correct folders under the
Dependencies folder. If the first target framework was .NET Standard
2.0 then an SDK folder would be displayed for all frameworks. If the
first target framework was .NET Standard 2.1 then a Frameworks folder
would be displayed for all frameworks.
The problem was that there was no multi-target support for
FrameworkReferences. Each framework that supports FrameworkReferences
needs to have the ResolveFrameworkReferences MSBuild target called
separately. Also all project target frameworks are checked individually
when building the Solution window tree nodes. Previously the first
target …
> [release-8.4] [DotNetCore] Fix incorrect folders displayed for multi-target projects

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/VisualStudioStyle.json
Updated the Visual Studio theme to fix the text selection color, which was too dark and made text hard to read when selected.
While making the change, I also updated a few other colors to match Windows:
* Usages (i.e. identifier highighting)
* Find results
* Link colors
Fixes VSTS #1009498.
> Updated Visual Studio theme

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/themes/VisualStudioStyle.json
Updated the Visual Studio theme to fix the text selection color, which was too dark and made text hard to read when selected.
While making the change, I also updated a few other colors to match Windows:
* Usages (i.e. identifier highighting)
* Find results
* Link colors
Fixes VSTS #1009498.
Backport of #9131.
/cc @jmatthiesen
> [release-8.4] Updated Visual Studio theme

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.UI.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkTemplateCellRenderer.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/LanguageCellRenderer.cs
If F# was selected for one template in the New Project dialog but
the other templates did not support F# then moving to the other
templates F Sharp would be announced by Voice Over. The problem was
that the wrong language was being set for the Text associated with
the language selector.
Fixes VSTS #752317 - Accessibility: In Project description Voice over
is reading  letter C as F (C#(C number) as F#(F number))
Fixes VSTS #751297 - Accessibility: Voice over is not reading the  whole project details in recently used templates page
> [Ide] Fix incorrect language read by voice over in New Project dialog

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.UI.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkTemplateCellRenderer.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/LanguageCellRenderer.cs
If F# was selected for one template in the New Project dialog but
the other templates did not support F# then moving to the other
templates F Sharp would be announced by Voice Over. The problem was
that the wrong language was being set for the Text associated with
the language selector.
Fixes VSTS #752317 - Accessibility: In Project description Voice over
is reading  letter C as F (C#(C number) as F#(F number))
Fixes VSTS #751297 - Accessibility: Voice over is not reading the  whole project details in recently used templates page
Backport of #8991.
/cc @mrward
> [release-8.4] [Ide] Fix incorrect language read by voice over in New Project dialog

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
Handle an UnauthorizedAccessException when trying to determine if
the filename passed as a startup argument is a workspace item. The
exception is caught and logged and return a non-zero exit code.
Previously this would generate a fatal exception.
```
System.IO.FileStream..ctor(String,FileMode,FileAccess,FileShare,Int32,Boolean,FileOptions)
System.IO.FileStream..ctor(String,FileMode,FileAccess,FileShare,Int32,FileOptions)
System.IO.StreamReader..ctor(String,Encoding,Boolean,Int32)
System.IO.StreamReader..ctor(String,Boolean)
System.IO.StreamReader..ctor(String)
MonoDevelop.Projects.MSBuild.SlnFile.GetFileVersion(String)
MonoDevelop.Projects.MSBuild.SlnFileFormat.CanReadFile(String,MSBuildFileFormat)
MonoDevelop.Projects.MSBuild.MSBuildFileFormat.CanReadFile(FilePath,Type) …
```
> [Ide] Handle unauthorized access exception on startup

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/IdeStartup.cs
Handle an UnauthorizedAccessException when trying to determine if
the filename passed as a startup argument is a workspace item. The
exception is caught and logged and return a non-zero exit code.
Previously this would generate a fatal exception.
```
System.IO.FileStream..ctor(String,FileMode,FileAccess,FileShare,Int32,Boolean,FileOptions)
System.IO.FileStream..ctor(String,FileMode,FileAccess,FileShare,Int32,FileOptions)
System.IO.StreamReader..ctor(String,Encoding,Boolean,Int32)
System.IO.StreamReader..ctor(String,Boolean)
System.IO.StreamReader..ctor(String)
MonoDevelop.Projects.MSBuild.SlnFile.GetFileVersion(String)
MonoDevelop.Projects.MSBuild.SlnFileFormat.CanReadFile(String,MSBuildFileFormat)
MonoDevelop.Projects.MSBuild.MSBuildFileFormat.CanReadFile(FilePath,Type) …
```
> [release-8.4] [Ide] Handle unauthorized access exception on startup

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpFormattingPanelWidget.fs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/MacToolbox.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/NativeViews/SearchTextField.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/NativeViews/ToggleButton.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/IPropertyPad.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/MacPropertyGrid.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/NativePropertyEditor/ComponentModelEditorProvider.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/NativePropertyEditor/ComponentModelObjectEditor.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/NativePropertyEditor/PropertyInfo/DescriptorPropertyInfo.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/PropertyPad.cs
- main/src/addins/Xml/Formatting/XmlFormattingPolicyPanelWidget.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.PropertyGrid/IPropertyGrid.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.PropertyGrid/PropertyGrid.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/NativeViewHelper.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/MessageService.cs
NOTES: Proppy doesn't expose any API to allow us remove the toolbar
https://github.com/xamarin/Xamarin.PropertyEditing/issues/663
Also there is an issue in numeric decimal editors in Culture separator symbol non ENGLISH based
https://github.com/xamarin/Xamarin.PropertyEditing/issues/662
Fixes VSTS #1003417 - Replace current F# format preference panel to use native Proppy
Fixes VSTS #1003416 - Replace current XML format preference panel to use native Proppy
Fixes VSTS #1002622 - Add a mechanism outside proppy to hide toolbar
Fixes VSTS #637121 - Accessibility: Preferences - Code Formatting: Unable to access Layout,Refracting,Spacing categorized formattings using keyboard.
Fixes VSTS #637246 - Accessibility: Preferences - Code Formatting F#: Not able to access Attributes,Document,Elements …
> Abstracts IPropertyGrid and uses in Preferences to fix a11c issues

- main/external/fsharpbinding/MonoDevelop.FSharpBinding/FSharpFormattingPanelWidget.fs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/MacToolbox.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/NativeViews/SearchTextField.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport.Toolbox/NativeViews/ToggleButton.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/IPropertyPad.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/MacPropertyGrid.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/NativePropertyEditor/ComponentModelEditorProvider.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/NativePropertyEditor/ComponentModelObjectEditor.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/NativePropertyEditor/PropertyInfo/DescriptorPropertyInfo.cs
- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/PropertyPad.cs
- main/src/addins/Xml/Formatting/XmlFormattingPolicyPanelWidget.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.PropertyGrid/IPropertyGrid.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.PropertyGrid/PropertyGrid.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/NativeViewHelper.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/MessageService.cs
NOTES: Proppy doesn't expose any API to allow us remove the toolbar
https://github.com/xamarin/Xamarin.PropertyEditing/issues/663
Also there is an issue in numeric decimal editors in Culture separator symbol non ENGLISH based
https://github.com/xamarin/Xamarin.PropertyEditing/issues/662
Fixes VSTS #1003417 - Replace current F# format preference panel to use native Proppy
Fixes VSTS #1003416 - Replace current XML format preference panel to use native Proppy
Fixes VSTS #1002622 - Add a mechanism outside proppy to hide toolbar
Fixes VSTS #637121 - Accessibility: Preferences - Code Formatting: Unable to access Layout,Refracting,Spacing categorized formattings using keyboard.
Fixes VSTS #637246 - Accessibility: Preferences - Code Formatting F#: Not able to access Attributes,Document,Elements …
> [release-8.4] Abstracts IPropertyGrid and uses in Preferences to fix a11c issues

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebugCommands.cs
Previously Voice Over would announce 'Breakpoint added' or 'Breakpoint
removed'. Now the line number and filename is announced. This matches
the behaviour of VS Code.
Fixes VSTS #1010391 - VoiceOver is not reading appropriate information
about addition of breakpoints
> [Debugger] Add line/filename to toggle breakpoint voice over message

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebugCommands.cs
Previously Voice Over would announce 'Breakpoint added' or 'Breakpoint
removed'. Now the line number and filename is announced. This matches
the behaviour of VS Code.
Fixes VSTS #1010391 - VoiceOver is not reading appropriate information
about addition of breakpoints
Backport of #9161.
/cc @mrward
> [release-8.4] [Debugger] Add line/filename to toggle breakpoint voice over message

- main/src/addins/MacPlatform/MacPlatform.cs
Causes crashes in the wild under high memory pressure conditions
Fixes VSTS #1008370 - [FATAL] SigSegv signal in Xamarin.Mac.dll!ObjCRuntime.Trampolines.SDAction::Invoke+0
> [release-8.4][Mac] Disable memory monitor due to broken xammac binding

- main/src/addins/MacPlatform/MacPlatform.cs
- main/tests/MacPlatform.Tests/MacPlatformTest.cs
Causes crashes in the wild under high memory pressure conditions
Fixes VSTS #1008370 - [FATAL] SigSegv signal in Xamarin.Mac.dll!ObjCRuntime.Trampolines.SDAction::Invoke+0
Backport of #9182.
/cc @Therzok
> [release-8.3] [Mac] Disable memory monitor due to broken xammac binding

- NuGet.config
- main/Directory.Build.props
Update to version 3.0.0-rc1.19464.2
Fixes VSTS #999874 - New Blazor project has template sections which
haven't been processed
> [Ide] Update dotnet templating engine

- NuGet.config
- main/Directory.Build.props
Update to version 3.0.0-rc1.19464.2
Fixes VSTS #999874 - New Blazor project has template sections which
haven't been processed
Backport of #9185.
/cc @mrward 
Backport of #9186.
/cc @rodrmoya @monojenkins
> [release-8.4-preview2] [release-8.4] [Ide] Update dotnet templating engine

- NuGet.config
- main/Directory.Build.props
Update to version 3.0.0-rc1.19464.2
Fixes VSTS #999874 - New Blazor project has template sections which
haven't been processed
Backport of #9185.
/cc @mrward
> [release-8.4] [Ide] Update dotnet templating engine

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/ExpressionEventArgs.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/ObjectValueTreeViewController.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/WatchPad.cs
For deleting, 2 bugs are fixed:
1. Deleting an expression now works between sessions (failed before because
removing the node sets the Parent to null and thus 'is RootObjectValueNode'
failed, causing no ExpressionRemoved event to fire.
2. If the user has multiple of the same expression, the old logic would remove
the first instance even if the user was deleting the last instance.
A similar bug existed for editing an existing expression if the user had
identical expressions in the list.
> [Debugger] Fixed deleting/changing of expressions in Watch Pad

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/ExpressionEventArgs.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/ObjectValueTreeViewController.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/WatchPad.cs
For deleting, 2 bugs are fixed:
1. Deleting an expression now works between sessions (failed before because
removing the node sets the Parent to null and thus 'is RootObjectValueNode'
failed, causing no ExpressionRemoved event to fire.
2. If the user has multiple of the same expression, the old logic would remove
the first instance even if the user was deleting the last instance.
A similar bug existed for editing an existing expression if the user had
identical expressions in the list.
Backport of #9193.
/cc @jstedfast
> [release-8.4] [Debugger] Fixed deleting/changing of expressions in Watch Pad

- main/src/addins/MacPlatform/Dialogs/MacOpenFileDialogHandler.cs
The NSSavePanel.DidChangeToDirectory event is broken on Catalina and using a custom delegate doesn't seem to be supported by Xamarin.Mac (although we don't know if that'd actually fix the crash).
This fixes a potential race with the `NSSavePanel.DidChangeToDirectory` delayed continuation and adds an additional check for `NSOpenSavePanelUrlEventArgs.NewDirectoryUrl` being NSNull, which can happen on Catalina for some unknown reason.
~and disables `NSSavePanel.DidChangeToDirectory` handling on Catalina (introduced in 5a2894490ba43c9e1056d09f39255c794facbe8d for https://github.com/mono/monodevelop/pull/3119)~.
Fixes VSTS #985660
Fixes VSTS #1015827
> [Mac][985660] Fix NSSavePanel crash on Catalina

- main/src/addins/MacPlatform/KernelInterop.cs
It seems that the API requires the count in natural_t units, not in bytes. Fixing this, fixes the crasher in Catalina
the reason it crashes in Catalina is that in Catalina task_info tries to write more data to the output struct (for Mojave the size of the struct and the maximum size written by Mojave was the same, so it didn't matter that the size argument was too big, because Mojave would never write more than the size of the buffer anyway)
Thanks to @rolfbjarne for the investigative work
> [Mac] Fix binding for task_info

- main/src/addins/MacPlatform/Dialogs/MacOpenFileDialogHandler.cs
The NSSavePanel.DidChangeToDirectory event is broken on Catalina and using a custom delegate doesn't seem to be supported by Xamarin.Mac (although we don't know if that'd actually fix the crash).
This fixes a potential race with the `NSSavePanel.DidChangeToDirectory` delayed continuation and disables `NSSavePanel.DidChangeToDirectory` handling on Catalina (introduced in 5a2894490ba43c9e1056d09f39255c794facbe8d for https://github.com/mono/monodevelop/pull/3119).
Fixes VSTS #985660
Backport of #9210.
/cc @sevoku
> [release-8.4] [Mac][985660] Fix NSSavePanel crash on Catalina

- main/src/addins/MacPlatform/Dialogs/MacOpenFileDialogHandler.cs
The NSSavePanel.DidChangeToDirectory event is broken on Catalina and using a custom delegate doesn't seem to be supported by Xamarin.Mac (although we don't know if that'd actually fix the crash).
This fixes a potential race with the `NSSavePanel.DidChangeToDirectory` delayed continuation and disables `NSSavePanel.DidChangeToDirectory` handling on Catalina (introduced in 5a2894490ba43c9e1056d09f39255c794facbe8d for https://github.com/mono/monodevelop/pull/3119).
Fixes VSTS #985660
Backport of #9210.
/cc @sevoku
> [release-8.3] [Mac][985660] Fix NSSavePanel crash on Catalina

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/QuickInfo/DebuggerQuickInfoSource.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1002160/
(I hope)
Backport of #9221.
/cc @jstedfast
> [release-8.4] [Debugger] Explicitly check cocoaView.VisualElement.Windows != null

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ExceptionCaughtDialog.cs
Fixes https://github.com/mono/monodevelop/issues/8204
> [UI] Remove trailing period from exception caught dialog

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Commands/FileCommands.cs
GetFocusedTopLevelWindow gets the most top level window, but in some contexts this could be transients windows which could be closed unexpectly for a reason.
I changed to use IDE or GTC as parent to get a consistent not disposable windowlike parent of OpenFile dialog
Fixes VSTS #998575 - [FATAL] System.ObjectDisposedException exception in Foundation.NSObject.get_SuperHandle()
> Prevents OpenFile dialog set a disposable parent window setting to IDE or GTC instead the last focused top level

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/LicenseAcceptanceService.cs
I changed in nuget license dialog to use IDE or GTC as parent to get a consistent not disposable window like parent
Fixes VSTS #961624 - "System.ObjectDisposedException: Cannot access a disposed object" error when trying to access nuget license dialog
> Prevents not disposable parent window in nuget license dialog setting to IDE or GTC instead use XwtRootWindow

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/LicenseAcceptanceService.cs
I changed in nuget license dialog to use IDE or GTC as parent to get a consistent not disposable window like parent
Fixes VSTS #961624 - "System.ObjectDisposedException: Cannot access a disposed object" error when trying to access nuget license dialog
Backport of #9120.
> [release-8.4] Prevents not disposable parent window in nuget license dialog setting to IDE or GTC instead use XwtRootWindow

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
Focus wasn't given back to the Solution pad when the `View | Pads | Solution` command was invoked.
> Fixes 1007912: Keyboard focus isn't given to Solution pad

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
Focus wasn't given back to the Solution pad when the `View | Pads | Solution` command was invoked. 
Backport of #9216.
/cc @sandyarmstrong @avodovnik
> [release-8.4] Fixes 1007912: Keyboard focus isn't given to Solution pad

- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/ToolboxPad.cs
Don't start Drag in cases of no currentEvent from Gtk
Fixes VSTS #998490 - [FATAL] SigAbrt exception in gtk-sharp.dll!mdtoken:6000ae2+4c
> Don't start Drag in cases of no currentEvent from Gtk

- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/ToolboxPad.cs
Don't start Drag in cases of no currentEvent from Gtk
Fixes VSTS #998490 - [FATAL] SigAbrt exception in gtk-sharp.dll!mdtoken:6000ae2+4c
Backport of #9114.
> [release-8.4] Don't start Drag in cases of no currentEvent from Gtk

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/MicrosoftTemplateEngineProjectTemplatingProvider.cs
The templating engine creates all the outputs correctly, but PrimaryOutputs
contains the files containing the "sourceName" from the template
("NewApp" in the Xamarin.Forms case), not the real names of the files
on disk (NewApp.csproj instead of $ProjectName.csproj).
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1016597
> [Ide] Work around bug in Xamarin.Forms multi project templates

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Templates/MicrosoftTemplateEngineProjectTemplatingProvider.cs
The templating engine creates all the outputs correctly, but PrimaryOutputs
contains the files containing the "sourceName" from the template
("NewApp" in the Xamarin.Forms case), not the real names of the files
on disk (NewApp.csproj instead of $ProjectName.csproj).
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1016597
Backport of #9235.
> [release-8.4] [Ide] Work around bug in Xamarin.Forms multi project templates

- main/msbuild/RoslynVersion.props
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/TextDocument.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/TextBufferFileModel.cs
Updating Roslyn to 20191025.13 ([b8a5611](https://www.github.com/dotnet/roslyn/commit/b8a5611))
[Changes](https://github.com/dotnet/roslyn/compare/7c7708e...b8a5611?w=1) since [7c7708e](https://www.github.com/dotnet/roslyn/commit/7c7708e):
- [Merge pull request #39450 from mavasani/TelemetryLogging](https://www.github.com/dotnet/roslyn/pull/39450)
- [Merge pull request #39159 from jasonmalinowski/support-inferred-indentation](https://www.github.com/dotnet/roslyn/pull/39159)
- [Variable suggestions show duplicated filter buttons on completion window (#39499)](https://www.github.com/dotnet/roslyn/pull/39499)
- [Merge pull request #39487 from dibarbet/port_editorconfig](https://www.github.com/dotnet/roslyn/pull/39487)
- [Merge pull request #39473 from …
> Bump Roslyn to 3.4.0-beta3-19525-13

- main/msbuild/RoslynVersion.props
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/TextDocument.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/TextBufferFileModel.cs
Updating Roslyn to 20191025.13 ([b8a5611](https://www.github.com/dotnet/roslyn/commit/b8a5611))
[Changes](https://github.com/dotnet/roslyn/compare/7c7708e...b8a5611?w=1) since [7c7708e](https://www.github.com/dotnet/roslyn/commit/7c7708e):
- [Merge pull request #39450 from mavasani/TelemetryLogging](https://www.github.com/dotnet/roslyn/pull/39450)
- [Merge pull request #39159 from jasonmalinowski/support-inferred-indentation](https://www.github.com/dotnet/roslyn/pull/39159)
- [Variable suggestions show duplicated filter buttons on completion window (#39499)](https://www.github.com/dotnet/roslyn/pull/39499)
- [Merge pull request #39487 from dibarbet/port_editorconfig](https://www.github.com/dotnet/roslyn/pull/39487)
- [Merge pull request #39473 from …
> [release-8.4] Bump Roslyn to 3.4.0-beta3-19525-13

- main/msbuild/RoslynVersion.props
- main/src/core/Mono.TextEditor.Shared/Mono.TextEditor/Document/TextDocument.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/TextBufferFileModel.cs
Updating Roslyn to 20191106.2 ([24c9587](https://www.github.com/dotnet/roslyn/commit/24c9587))
[Changes](https://github.com/dotnet/roslyn/compare/b8a5611...24c9587?w=1) since [b8a5611](https://www.github.com/dotnet/roslyn/commit/b8a5611):
- [Merge pull request #39680 from JoeRobich/fix-uithread-check](https://www.github.com/dotnet/roslyn/pull/39680)
- [Merge pull request #39675 from dotnet/move-16.4-to-beta4](https://www.github.com/dotnet/roslyn/pull/39675)
- [Merge pull request #39639 from dotnet/revert-39587-use-vs-core-sdk](https://www.github.com/dotnet/roslyn/pull/39639)
- [Merge pull request #39638 from JoeRobich/fix-test-strings](https://www.github.com/dotnet/roslyn/pull/39638)
- [Merge pull request #39642 from JoeRobich/skip-int-tests](https://www.github.com/dotnet/roslyn/pull/39642 …
> Bump Roslyn to 3.4.0-beta4-19556-02

- main/msbuild/RoslynVersion.props
Updating Roslyn to 20191106.2 ([24c9587](https://www.github.com/dotnet/roslyn/commit/24c9587))
[Changes](https://github.com/dotnet/roslyn/compare/b8a5611...24c9587?w=1) since [b8a5611](https://www.github.com/dotnet/roslyn/commit/b8a5611):
- [Merge pull request #39680 from JoeRobich/fix-uithread-check](https://www.github.com/dotnet/roslyn/pull/39680)
- [Merge pull request #39675 from dotnet/move-16.4-to-beta4](https://www.github.com/dotnet/roslyn/pull/39675)
- [Merge pull request #39639 from dotnet/revert-39587-use-vs-core-sdk](https://www.github.com/dotnet/roslyn/pull/39639)
- [Merge pull request #39638 from JoeRobich/fix-test-strings](https://www.github.com/dotnet/roslyn/pull/39638)
- [Merge pull request #39642 from JoeRobich/skip-int-tests](https://www.github.com/dotnet/roslyn/pull/39642 …
> [release-8.4] Bump Roslyn to 3.4.0-beta4-19556-02

- main/src/addins/MacPlatform/MacIdeAppleEvents.cs
- main/src/addins/MacPlatform/MacPlatform.cs
- main/src/addins/MacPlatform/MacPlatform.csproj
- main/src/addins/MacPlatform/query-vsmac.mm
Unity needs to be able to query running instances of MD/VS Mac for the active/selected current solution path.
/cc @jbevain
> MacIdeAppleEvents: add an apple event for getting current solution path

- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/AssemblyBrowserNavigationPoint.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/AssemblyBrowserViewContent.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/AssemblyBrowserWidget.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/991658
AssemblyBrowser navigation points were broken. The assembly
definitions are disposed on close so the definitions need to be
reloaded using file names.
> Fixes VSTS Bug 991658: Crashes from "Critical Gtk Errors" in log

- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/AssemblyBrowserNavigationPoint.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/AssemblyBrowserViewContent.cs
- main/src/addins/MonoDevelop.AssemblyBrowser/MonoDevelop.AssemblyBrowser/AssemblyBrowserWidget.cs
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/991658
AssemblyBrowser navigation points were broken. The assembly
definitions are disposed on close so the definitions need to be
reloaded using file names.
Backport of #9072.
> [release-8.4] Fixes VSTS Bug 991658: Crashes from "Critical Gtk Errors" in log

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/PinnedWatches/PinnedWatchView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/QuickInfo/MacDebuggerTooltipWindow.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectCellViewBase.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectNameView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectTypeView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectValueView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueNode.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/ShowMoreValuesObjectValueNode.cs
Fixes VSTS 1002713
Fixes issues with the tooltip sizing on catalina. Speeds up the calculation of the column widths and fixes a NRE when expanding using the "show values", "more values" buttons.
this also fixes VSTS 1011400
> [Debugger] Optimize debugger tooltip resizing

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/PinnedWatches/PinnedWatchView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/QuickInfo/MacDebuggerTooltipWindow.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectCellViewBase.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectNameView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectTypeView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectValueView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueNode.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/ShowMoreValuesObjectValueNode.cs
Fixes VSTS 1002713
Fixes issues with the tooltip sizing on catalina. Speeds up the calculation of the column widths and fixes a NRE when expanding using the "show values", "more values" buttons.
this also fixes VSTS 1011400
Backport of #9270.
/cc @sgmunn @jstedfast
> [release-8.4] [Debugger] Optimize debugger tooltip resizing

- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/ToolboxPad.cs
This commit reverts https://github.com/mono/monodevelop/commit/9fdbbcf765427e48a894d96d0aeab2354a587b74which introduces a regression
doing a drag and drop in cases where the current event is IntPtr.Zero
reopening https://devdiv.visualstudio.com/DevDiv/_workitems/edit/998490
Fixes VSTS #1019066
> Fixes drag and drop in toolbox when current event is IntPtr.Zero

- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/ToolboxPad.cs
This commit reverts https://github.com/mono/monodevelop/commit/9fdbbcf765427e48a894d96d0aeab2354a587b74which introduces a regression
doing a drag and drop in cases where the current event is IntPtr.Zero
reopening https://devdiv.visualstudio.com/DevDiv/_workitems/edit/998490
Backport of #9276.
/cc @netonjm
> [release-8.4] Fixes drag and drop in toolbox when current event is IntPtr.Zero

- main/src/addins/CSharpBinding/MonoDevelop.Ide.Completion.Presentation/MonoDevelopContainedDocument.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.RoslynServices/MonoDevelopDocumentNavigationService.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/IMonoDevelopHostDocument.cs
This reverts commit d0ec47952e2d2beadf1176e4be69cea35720a2c7.
It broke some normal usage of Go To Definition for C# files.
Backport of #9288.
> [release-8.4] Revert "Implement Go To Definition for Razor"

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/BreakpointPropertiesDialog.cs
Use LabelWidget rather than Label for combo boxes,
because Label is also used to reflect combo box
selections with AtkCocoa.
Also add some more accessibility label relations.
Fixes VSTS #1018518
Backport of #9294.
/cc @sevoku
> [release-8.4] [Debugger] Improve Breakpoint dialog accessibility

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/BreakpointPropertiesDialog.cs
Use LabelWidget rather than Label for combo boxes,
because Label is also used to reflect combo box
selections with AtkCocoa.
Also add some more accessibility label relations.
Fixes VSTS #1018518
> [Debugger] Improve Breakpoint dialog accessibility

- main/src/core/MonoDevelop.Ide/gtkrc.mac
- main/src/core/MonoDevelop.Ide/gtkrc.mac-dark
||old|new|
| --- | --- | --- |
|**light**|<img width="153" alt="grafik" src="https://user-images.githubusercontent.com/951587/68770919-53582c00-0627-11ea-9b2b-e977dc43e37a.png">|<img width="154" alt="grafik" src="https://user-images.githubusercontent.com/951587/68770864-3c193e80-0627-11ea-8948-dd2f6d88071d.png">|
|**dark**||<img width="158" alt="grafik" src="https://user-images.githubusercontent.com/951587/68771253-f9a43180-0627-11ea-8542-74168984dba0.png">|
||old|new|
| --- | --- | --- |
|**light**|<img width="76" alt="grafik" src="https://user-images.githubusercontent.com/951587/68771531-7f27e180-0628-11ea-99b1-80c0541e0b97.png"><img width="77" alt="grafik" src="https://user-images.githubusercontent.com/951587/68771546-87801c80-0628-11ea-8c22-7cb0f6bc4212.png">|<img width="80" …
> [Ide][Mac] Fix several focus contrast issues with Gtk

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/LocalsPad.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeViewDataSource.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValuePad.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/WatchPad.cs
Simplest guess for VSTS 1004450
I'm not going to claim this as a fix, but it is possibly related and, without some larger refactoring, seems to be the simplest of the guesses that we have for those crashes. Also, related changes in column sizing code might be related and offer fixes (if the crashes were in tooltips or pinned watches, which we can't tell because it's the same code for all cases).
In any case, we should add these begin/end updates around code where we manipulate the tree items. 
---
related:
VSTS 1008044
Backport of #9290.
/cc @sgmunn
> [release-8.4] [Debugger] Add more Begin/End Updates around tree manipulation

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/LocalsPad.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeViewDataSource.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValuePad.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/WatchPad.cs
Simplest guess for VSTS 1004450
I'm not going to claim this as a fix, but it is possibly related and, without some larger refactoring, seems to be the simplest of the guesses that we have for those crashes. Also, related changes in column sizing code might be related and offer fixes (if the crashes were in tooltips or pinned watches, which we can't tell because it's the same code for all cases).
In any case, we should add these begin/end updates around code where we manipulate the tree items. 
---
related:
VSTS 1008044
> [Debugger] Add more Begin/End Updates around tree manipulation

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/Configuration/PackageDescription.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/Configuration/ScaffoldingConfig.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/Configuration/ScaffoldingPackageVersions.json
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/Configuration/SupportPolicyVersion.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/ScaffolderWizard.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Tests/MonoDevelop.AspNetCore.Tests/ScaffoldingTests.cs
- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.csproj
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1015867
> Allow scaffolders to choose packages/versions by TFM

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/PinnedWatches/PinnedWatchView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/QuickInfo/MacDebuggerTooltipWindow.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeViewDataSource.cs
Currently, the editor intercepts scrolling events that an adornment
such as the PinnedWatchView might want to receive. This prevents such an
adornment from being properly scrollable.
Looking at how pinned watches work on Windows, however, the watch itself
cannot be expanded. Rather, the user can click an expand button to see
the child items in a popup. Inspired by this, I have removed scrolling
and expansion from the PinnedWatchView, and made it so hovering a watch
shows the same popover tooltip (which _is_ scrollable, as it's a child
window) that one sees when hovering a value in the editor.
A few notes:
* Changed the data source to not add child nodes at all when
`AllowExpanding` is not set on the tree view. This ensures there will
be no disclosure triangle.
* Pinned watches whose …
> [Debugger] Simplify PinnedWatchView, allow scrolling children via popover

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/PinnedWatches/PinnedWatchView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/QuickInfo/MacDebuggerTooltipWindow.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeViewDataSource.cs
Currently, the editor intercepts scrolling events that an adornment
such as the PinnedWatchView might want to receive. This prevents such an
adornment from being properly scrollable.
Looking at how pinned watches work on Windows, however, the watch itself
cannot be expanded. Rather, the user can click an expand button to see
the child items in a popup. Inspired by this, I have removed scrolling
and expansion from the PinnedWatchView, and made it so hovering a watch
shows the same popover tooltip (which _is_ scrollable, as it's a child
window) that one sees when hovering a value in the editor.
A few notes:
* Changed the data source to not add child nodes at all when
`AllowExpanding` is not set on the tree view. This ensures there will
be no disclosure triangle.
* Pinned watches whose …
> [release-8.4] [Debugger] Simplify PinnedWatchView, allow scrolling children via popover

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Commands/PublishToFolderBaseCommandHandler.cs
Fixes:  https://devdiv.visualstudio.com/DevDiv/_queries/edit/1011069
Testing:
Create .Net Core Projects - including Http Trigger Function - and verify folder publishing
Backport of #9304.
/cc @iantoalms
> [release-8.4] Re-enable Folder Publishing Support for .Net Core Console and Library projects

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeView.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1016073/
> [Debugger] Catch EvaluatorExceptions in MacObjectValueTreeView.OnCopy()

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeView.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1016073/
Backport of #9302.
/cc @slluis @jstedfast
> [release-8.4] [Debugger] Catch EvaluatorExceptions in MacObjectValueTreeView.OnCopy()

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/DynamicFileManager.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.ProjectSystemHandler.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/TypeSystemService_WorkspaceHandling.cs
Virtual documents come from Razor when a .cshtml file is opened and they have .cshtml.g.cs file extension. These are C# projection buffers generated by Razor and only exist while the corresponding .cshtml file is open in an editor.
Dynamic documents also come from Razor but these come from all .razor and .cshtml files in the project that have the MSBuild item type "Content". These don't have to be open in the editor.
The problem is that we weren't adding virtual and dynamic documents in all scenarios. Specifically when the solution was initially loaded our code was not running and so if a Razor document was open before the solution was loading it wouldn't get added to the workspace properly.
To mitigate this we've found a single codepath (LoadProject) that all the logic in the project …
> Refactor how virtual and dynamic documents are added to the workspace.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/DynamicFileManager.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.ProjectSystemHandler.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/TypeSystemService_WorkspaceHandling.cs
Virtual documents come from Razor when a .cshtml file is opened and they have .cshtml.g.cs file extension. These are C# projection buffers generated by Razor and only exist while the corresponding .cshtml file is open in an editor.
Dynamic documents also come from Razor but these come from all .razor and .cshtml files in the project that have the MSBuild item type "Content". These don't have to be open in the editor.
The problem is that we weren't adding virtual and dynamic documents in all scenarios. Specifically when the solution was initially loaded our code was not running and so if a Razor document was open before the solution was loading it wouldn't get added to the workspace properly.
To mitigate this we've found a single codepath (LoadProject) that all the logic in the project …
> [release-8.4] Refactor how virtual and dynamic documents are added to the workspace.

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/Mac/GtkNSViewHost.cs
Revert "First pass to fix solution pad not regaining focus on shortcut press."
This reverts commit 7e01fd039a5c6705189f0a927868919e953e9c73 in this PR : https://github.com/mono/monodevelop/pull/9216
I reverted this commit because introduces new problems, in this case infinite focus loops on in Pads with autohide with embedded native views ( https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1020127)
Additionally all this logic is going to be obsolete by https://github.com/mono/monodevelop/pull/9267
which hopefully will fix this issue also.
Fixes VSTS #1020127 - Toolbox focus flickers when in autohide mode
> Revert "First pass to fix solution pad not regaining focus on shortcut press."

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/DockBarItem.cs
Ensures don't close autohide window if focus are in embedded panels
Fixes VSTS #1001359 - Properties window opens and then closes on right clicking project file and select Properties
Backport of #9324. 
/cc @netonjm
> [release-8.4] Ensures don't close autohide window if focus are in embedded panels

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Docking/DockBarItem.cs
Ensures don't close autohide window if focus are in embedded panels
Fixes VSTS #1001359 - Properties window opens and then closes on right clicking project file and select Properties
> Ensures don't close autohide window if focus are in embedded panels

- main/msbuild/RoslynVersion.props
Updating Roslyn to 20191112.5 ([ff930de](https://www.github.com/dotnet/roslyn/commit/ff930de))
[Changes](https://github.com/dotnet/roslyn/compare/24c9587...ff930de?w=1)  since [24c9587](https://www.github.com/dotnet/roslyn/commit/24c9587):
- [Merge pull request #39636 from sharwell/inheritdoc-overflow](https://www.github.com/dotnet/roslyn/pull/39636)
- [Merge pull request #39630 from v-zbsail/loc_20191101_release_dev16.4-vs-deps](https://www.github.com/dotnet/roslyn/pull/39630)
- [Do not fail fast on cancellation (#39627)](https://www.github.com/dotnet/roslyn/pull/39627)
- [Don't store pooled object in cache (#39729)](https://www.github.com/dotnet/roslyn/pull/39729)
- [Merge pull request #39726 from jasonmalinowski/fix-devenv-build](https://www.github.com/dotnet/roslyn/pull/39726)
- …
> [release-8.4] Bump Roslyn to 3.4.0-beta4-19562-05

- main/msbuild/RoslynVersion.props
Updating Roslyn to 20191112.5 ([ff930de](https://www.github.com/dotnet/roslyn/commit/ff930de))
[Changes](https://github.com/dotnet/roslyn/compare/24c9587...ff930de?w=1)  since [24c9587](https://www.github.com/dotnet/roslyn/commit/24c9587):
- [Merge pull request #39636 from sharwell/inheritdoc-overflow](https://www.github.com/dotnet/roslyn/pull/39636)
- [Merge pull request #39630 from v-zbsail/loc_20191101_release_dev16.4-vs-deps](https://www.github.com/dotnet/roslyn/pull/39630)
- [Do not fail fast on cancellation (#39627)](https://www.github.com/dotnet/roslyn/pull/39627)
- [Don't store pooled object in cache (#39729)](https://www.github.com/dotnet/roslyn/pull/39729)
- [Merge pull request #39726 from jasonmalinowski/fix-devenv-build](https://www.github.com/dotnet/roslyn/pull/39726)
- …
> Bump Roslyn to 3.4.0-beta4-19562-05

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/PinnedWatches/PinnedWatchView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/QuickInfo/MacDebuggerTooltipWindow.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebugValueWindow.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ExceptionCaughtDialog.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Gtk/GtkObjectValueTreeView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeViewDelegate.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/ObjectValueTreeViewController.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValuePad.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/PinnedWatchWidget.cs
This prevents the row from getting into an odd
selected-but-not-focused state.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1021870/
Backport of #9342.
/cc @jstedfast
> [release-8.4] [Debugger] Don't allow selection of the pinned watch row

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/PinnedWatches/PinnedWatchView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/QuickInfo/MacDebuggerTooltipWindow.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebugValueWindow.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ExceptionCaughtDialog.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Gtk/GtkObjectValueTreeView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeViewDelegate.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/ObjectValueTreeViewController.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValuePad.cs
- main/src/addins/MonoDevelop.SourceEditor2/MonoDevelop.SourceEditor/PinnedWatchWidget.cs
This prevents the row from getting into an odd
selected-but-not-focused state.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1021870/
> [Debugger] Don't allow selection of the pinned watch row

- main/msbuild/RoslynVersion.props
@sandyarmstrong This bumps Roslyn to what we expect to be the 16.4 GA build.
Changes since [ff930de](https://www.github.com/dotnet/roslyn/commit/ff930de):
- [EnC: Fix document out-of-sync checks when module is not loaded when debugging session starts (#39836)](https://www.github.com/dotnet/roslyn/pull/39836)
> Bump Roslyn to 3.4.0-beta4-19568-04

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/DocumentManager.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/DefaultWorkbench.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Shell/SdiWorkspaceWindow.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Gui.Documents/DocumentManagerTests.cs
Main problem was that `IsNewDocument = false;` is called after `FilePath` is updated(which calls SetTitleEvent) which means logic for assigning untitled name was executed instead setting to `controller.DocumentTitle`, by moving code to `DocumentManager` we achieve following things:
1) Move logic specific to FileDocumentController out of SdiWorkspaceWindow.cs
2) Simplify logic in SdiWorkspaceWindow.cs(removal of `myUntitledTitle`)
3) And by moving logic of creating unique file name closer to start of document creation reduce chance of bugs and code complexity that has to deal with file name change in middle of creation
Also added unit test for new code in DocumentManager
> Fix 1023500: When saving new document, tab title doesn't update

- version-checks
We no longer build it by default, so removing it would be nice
> Remove heapshot

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Documents/FileDocumentController.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.Gui.Documents/DocumentManagerTests.cs
I think that anything that needs Canonical comparison should make conversion itself.
I'm also not aware of any regressions this might cause... @slluis any ideas?
> Fix 1023494: Unsaved new documents have `/` added to begining of file name

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Gui/ManagePackagesDialog.UI.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Gui/ManagePackagesDialog.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.NodeBuilders/PackageReferenceNodeDescriptor.cs
Various accessibility fixes:
- Fixes VSTS #1021638 - Accessibility: NuGet Packages: VoiceOver is not announcing the label for all the combo box and edit box present on the screen .
- Fixes VSTS #1021699 - Manage NuGet Packages_ConsolidateTab_ScreenReader:Voice Over is not announcing the table name
- Fixes VSTS #1022836 - Manage NuGet Packages_Usability: Unable to identify the instructions about search criteria.
- Fixes VSTS #1021702 - Accessibility: NuGet Packages: Column Header name is not present for the first column. 
- Fixes VSTS #1021636 - Accessibility: NuGet: Improper announcement for the "ID" word.
- Fixes VSTS #1022830 - Accessibility: NuGet Packages: VoiceOver is not announcing the status message.
> [NuGet] Manage packages dialog accessibility

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Gui/ManagePackagesDialog.UI.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Gui/ManagePackagesDialog.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.NodeBuilders/PackageReferenceNodeDescriptor.cs
Various accessibility fixes:
- Fixes VSTS #1021638 - Accessibility: NuGet Packages: VoiceOver is not announcing the label for all the combo box and edit box present on the screen .
- Fixes VSTS #1021699 - Manage NuGet Packages_ConsolidateTab_ScreenReader:Voice Over is not announcing the table name
- Fixes VSTS #1022836 - Manage NuGet Packages_Usability: Unable to identify the instructions about search criteria.
- Fixes VSTS #1021702 - Accessibility: NuGet Packages: Column Header name is not present for the first column. 
- Fixes VSTS #1021636 - Accessibility: NuGet: Improper announcement for the "ID" word.
- Fixes VSTS #1022830 - Accessibility: NuGet Packages: VoiceOver is not announcing the status message.
Backport of #9379.
/cc @mrward
> [release-8.4] [NuGet] Manage packages dialog accessibility

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/SelectReferenceDialog.cs
This is a partial fix for VSTS #750263, AtkCocoa needs to support the right focus order, including an Action widget.
> [Ide] Let the references search be a child of the notebook

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/SelectReferenceDialog.cs
This is a partial fix for VSTS #750263, AtkCocoa needs to support the right focus order, including an Action widget.
Backport of #6926.
/cc @sevoku
> [release-8.4] [Ide] Let the references search be a child of the notebook

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.csproj
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebuggerAsyncCompletionSource.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/DebuggerCompletionCommandHandler.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectNameView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectTypeView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerTextField.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/ObjectValueTreeViewController.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/999418/
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1018525/
backport of https://github.com/mono/monodevelop/pull/9166
> [Release-8.4] [Debugger] Implemented code-completion for the new MacObjectValueTree

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ExceptionCaughtDialog.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectNameView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectValueView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/ObjectValueTreeViewController.cs
- Fixes VSTS #782188 - Voiceover doesn't give any information about the "eye" and "Pen" icon which are interactive
- Fixes VSTS #1025889 - VoiceOver does not announce the image name.
- Fixes VSTS #1025898 - ScreenReader focus does not go on the table.
Problems:
- Tabbing into and out of the Properties tree view is currently broken. Seems to be a problem with the interaction with the GtkNSViewHost and the native tree view control.
Small changes to the UI:
- Replaced the Properties tree view the new native one created by Jeff.
- Removed the expanders since they were causing problems with Voice Over.
UI Before:
UI After:
> [Debugger] Exception caught dialog accessibility

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ExceptionCaughtDialog.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectNameView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacDebuggerObjectValueView.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/ObjectValueTreeViewController.cs
- Fixes VSTS #782188 - Voiceover doesn't give any information about the "eye" and "Pen" icon which are interactive
- Fixes VSTS #1025889 - VoiceOver does not announce the image name.
- Fixes VSTS #1025898 - ScreenReader focus does not go on the table.
Problems:
- Tabbing into and out of the Properties tree view is currently broken. Seems to be a problem with the interaction with the GtkNSViewHost and the native tree view control.
Small changes to the UI:
- Replaced the Properties tree view the new native one created by Jeff.
- Removed the expanders since they were causing problems with Voice Over.
UI Before:
UI After:
Backport of #9398.
/cc @mrward
> [release-8.4] [Debugger] Exception caught dialog accessibility

- main/src/addins/MonoDevelop.TextEditor/MonoDevelop.TextEditor.Cocoa/CocoaTextViewContent.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1010385
Backport of #9411.
> [release-8.4] CocoaTextViewContent: Add AccessibilityTitle for editor group

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/ContextMenuExtensionsMac.cs
This introduces a null check, and also introduces additional debug levelchecks for others, just to make sure if we do run into this while debugging, that we are aware.
Fixes https://vsmac.dev/1026106
> Fixes 1026106 - in some cases, NSEvent seems to have been null

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/ContextMenuExtensionsMac.cs
This introduces a null check, and also introduces additional debug levelchecks for others, just to make sure if we do run into this while debugging, that we are aware.
Fixes https://vsmac.dev/1026106 
Backport of #9405.
/cc @sandyarmstrong @avodovnik
> [release-8.4] Fixes 1026106 - in some cases, NSEvent seems to have been null

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/Commands.cs
MonoDevelop.VersionControl.Git.dll!MonoDevelop.VersionControl.Git.SwitchToBranchHandler::Update+98
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1030370
Backport of #9435.
> [release-8.4] Fixes VSTS Bug 1030370: [FATAL] SigTerm signal in

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/Commands.cs
MonoDevelop.VersionControl.Git.dll!MonoDevelop.VersionControl.Git.SwitchToBranchHandler::Update+98
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1030370
> Fixes VSTS Bug 1030370: [FATAL] SigTerm signal in

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/Commands.cs
MonoDevelop.VersionControl.Git.dll!MonoDevelop.VersionControl.Git.TaskFailureExtensions::RunWaitAndCapture+0
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1027417
Was the only command call left using the non async update which may
cause dead locks.
Backport of #9421.
> [release-8.4] Fixes VSTS Bug 1027417: [FATAL] SigTerm signal in

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/Commands.cs
MonoDevelop.VersionControl.Git.dll!MonoDevelop.VersionControl.Git.TaskFailureExtensions::RunWaitAndCapture+0
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1027417
Was the only command call left using the non async update which may
cause dead locks.
> Fixes VSTS Bug 1027417: [FATAL] SigTerm signal in

- main/build/MacOSX/monostub.mm
This option tells Mono Jitter to set FramePointer register for managed stack frames, this register is important for native profilers and other native tools when unwinding call stack otherwise they don't know how to continue unwinding past managed stack frame and bail...
I asked mono performance/benchmark team to run their tests with and without this environment variable and results were same, hence conclusion is there is no performance difference.
This will help with getting before sampling data when using "Profile for 5 seconds" and other similar tools.
> SetEnv MONO_DEBUG=disable_omit_fp

- main/Directory.Build.props
Downgraded VS Test from 16.4 to 16.2. The 16.4 version fails to
discover tests. Test Discovery Console window has the error:
```
Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException:
Testhost process exited with error: The application to execute does
not exist: ''
```
The more recent VS Test seems to not find the testhost.dll causing
test discovery to fail.
VS Test 16.2 is used by .NET Core 3.1 SDK.
Fixes VSTS #1030325 - VS Test discovery fails
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1030325
> [UnitTesting] Fix VS Test discovery failing

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.FileNesting/NestingRule.cs
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1034938
Given the current FileNesting logic, we check for a potential parent which matches a filepath spec. We filter out these parents if they are directories using FilePath.IsDirectory, which causes IO via Directory.Exists.  As we already know whether a filepath in the project filelist is a directory, we should delay this filtering and avoid the IO.
Testing:
This change has a 2x speedup (~2.5mins to ~1.1min) for a React.js & Redux Asp.Net Core project which has a node_modules folder added to the project.
> Improve FileNesting performance by avoiding costly IO

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects.FileNesting/NestingRule.cs
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1034938
Given the current FileNesting logic, we check for a potential parent which matches a filepath spec. We filter out these parents if they are directories using FilePath.IsDirectory, which causes IO via Directory.Exists.  As we already know whether a filepath in the project filelist is a directory, we should delay this filtering and avoid the IO.
Testing:
This change has a 2x speedup (~2.5mins to ~1.1min) for a React.js & Redux Asp.Net Core project which has a node_modules folder added to the project.
Backport of #9451.
/cc @iantoalms
> [release-8.4] Improve FileNesting performance by avoiding costly IO

- main/src/addins/MacPlatform/MacPlatform.cs
When a message dialog is shown, we try to get the currently focused
top level window if no parent is provided. This is done by the
GetFocusedTopLevelWindow() method that is implemented in MacPlatform.
This method should not return auto-hide pads as top level windows,
and there is a check for that, but the check doesn't work when
the auto-hide pad is implemented with Cocoa, since the pad may have
the Cocoa focus but not the GTK focus. It may happen then that an
auto-hide pad is used for parenting a message dialog, and if the
pad is auto-hidden, the modal dialog will also be hidden and
will block the whole IDE. The patch adds an additional check to
the condition for detecting if a top level is focused or not.
Fixes bug #1027840
> Fix dialog parenting issue

- main/src/addins/MacPlatform/MacPlatform.cs
When a message dialog is shown, we try to get the currently focused
top level window if no parent is provided. This is done by the
GetFocusedTopLevelWindow() method that is implemented in MacPlatform.
This method should not return auto-hide pads as top level windows,
and there is a check for that, but the check doesn't work when
the auto-hide pad is implemented with Cocoa, since the pad may have
the Cocoa focus but not the GTK focus. It may happen then that an
auto-hide pad is used for parenting a message dialog, and if the
pad is auto-hidden, the modal dialog will also be hidden and
will block the whole IDE. The patch adds an additional check to
the condition for detecting if a top level is focused or not.
Fixes bug #1027840
Backport of #9470.
/cc @slluis
> [release-8.4] Fix dialog parenting issue

- main/build/MacOSX/BinaryCompatBaseline.txt
Removes System.Net.Http.Primitives and Google.Apis.Core error lines.
Needed by https://github.com/xamarin/md-addins/pull/6088
> Fixes BinaryCompatBaseline.txt for Archive publishing fix

- main/src/core/MonoDevelop.Ide/ExtensionModel/Commands.addin.xml
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/ProjectFileNodeBuilder.cs
- For linked files only provide "Remove" (bound with cmd + delete shortcut) like VS Win
VS Win:
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1026629/
> [IDE] Remove linked files from project

- main/build/MacOSX/BinaryCompatBaseline.txt
Removes errors for System.Net.Http.Primitives and Google.Apis.Core.
This is required for https://github.com/xamarin/md-addins/pull/6097
> Updates CompatBaseline for Archive Publishing fix

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreRunConfiguration.cs
When we set it to false, the field is removed from launchSettings.json, so
when reading it back, it needs to default to false if not present to be a
correct end user experience.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1015890
> [AspNetCore] Default "launchBrowser" to false

- main/src/addins/MonoDevelop.AspNetCore/Templates/MVCViewImportsPage.xft.xml
- main/src/addins/MonoDevelop.AspNetCore/Templates/MVCViewLayoutPage.xft.xml
- main/src/addins/MonoDevelop.AspNetCore/Templates/MVCViewPage.xft.xml
- main/src/addins/MonoDevelop.AspNetCore/Templates/MVCViewStartPage.xft.xml
- main/src/addins/MonoDevelop.AspNetCore/Templates/MvcController.xft.xml
VS Windows shows all item templates as "Razor ...", without any mention
to MVC, which causes confusion, so change to match the descriptions.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1016547
> [AspNetCore] Match item templates' descriptions to those in VS Win

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ExceptionCaughtDialog.cs
- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/Styles.cs
Fixes VSTS #1007551
The bottom footer was white. This was a regression from somewhere.
> Fix the footer color of the exception caught dialog

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageManagementCredentialService.cs
- main/src/addins/MonoDevelop.PackageManagement/NuGet.Credentials/CredentialService.cs
This will do a barebone registration of available, plugin-based credential providers (like the Azure DevOps one) without implementing any authentication flow. The idea is that users can pre-authenticate via another mean (manual MSBuild invocation or NuGet binary) and the IDE will, at least, be able to retrieve those cached credentials.
Fixes VSTS #632121 - NuGet credential providers
> [PackageManagement] Register credential providers coming from secure plugins

- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/NativePropertyEditor/ComponentModelEditorProvider.cs
An object that derives from CustomTypeDescriptor would not show the
custom properties in the new native property editor but would with
the old property editor.
The problem was that the type was being passed to the TypeDescriptor's
GetProperties method instead of the object providing the properties.
Fixes VSTS #1047889 - New Property Editor does not support
CustomTypeDescriptors
> [DesignerSupport] Support CustomTypeDescriptors in new property editor

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/ExceptionCaught/ExceptionCaughtAdornmentManager.cs
Only reasonable fix is to follow VS Windows way of displaying it as window because things get tricky with wrapped view where you can't just expand text view scrollable width...
Fixes VSTS #822175
Fixes VSTS #1025880
> Fix 822175: Exception adornment scrolled outside of view

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger.VSTextView/ExceptionCaught/ExceptionCaughtAdornmentManager.cs
Only reasonable fix is to follow VS Windows way of displaying it as window because things get tricky with wrapped view where you can't just expand text view scrollable width...
Fixes VSTS #822175
Fixes VSTS #1025880
Backport of #7706.
/cc @sevoku @DavidKarlas
> [release-8.4-a11y] Fix 822175: Exception adornment scrolled outside of view

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore/AspNetCoreProjectExtension.cs
With the enabling of launchSettings.json support for Worker services,
we added support, by mistake, to run it on the user's installed
browsers, which is wrong, as Worker services are just console
applications.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1050466
> [AspNetCore] Don't create browser-based execution targets for Worker services

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/MainToolbarController.cs
If a multi-run configuration is selected in the main toolbar and a
project is reloaded a crash can occur since the main toolbar has not
updated its project mappings. Exception thrown:
```
System.Collections.Generic.KeyNotFoundException: The given key
'MonoDevelop.CSharp.Project.CSharpProject' was not present in the
dictionary.
System.ThrowHelper.GetKeyNotFoundException(Object)
System.ThrowHelper.ThrowKeyNotFoundException(Object)
System.Collections.Generic.Dictionary`2[[MonoDevelop.Projects.SolutionItem],[MonoDevelop.Components.MainToolbar.ConfigurationMerger]].get_Item(SolutionItem)
MonoDevelop.Components.MainToolbar.MainToolbarController.FillRuntimesForProject(List`1,SolutionItem,Int32&)
MonoDevelop.Components.MainToolbar.MainToolbarController.FillRuntimes() …
```
> [release-8.4] [Ide] Fix crash in main toolbar after project is reloaded

- main/src/addins/MonoDevelop.DesignerSupport/MonoDevelop.DesignerSupport/NativePropertyEditor/ComponentModelEditorProvider.cs
An object that derives from CustomTypeDescriptor would not show the
custom properties in the new native property editor but would with
the old property editor.
The problem was that the type was being passed to the TypeDescriptor's
GetProperties method instead of the object providing the properties.
Fixes VSTS #1047889 - New Property Editor does not support
CustomTypeDescriptors
Backport of #9507.
/cc @mrward
> [release-8.4] [DesignerSupport] Support CustomTypeDescriptors in new property editor

- main/src/addins/CSharpBinding/MonoDevelop.CSharp.Project/CSharpCompilerParameters.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
- main/tests/Ide.Tests/MonoDevelop.Ide.TypeSystem/TypeSystemServiceTests.cs
- main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding.Tests.csproj
- main/tests/MonoDevelop.CSharpBinding.Tests/MonoDevelop.CSharpBinding/CSharpCompilerParametersTests.cs
- main/tests/test-projects/multi-target-reload/Class1.cs
- main/tests/test-projects/multi-target-reload/multi-target-reload.csproj
- main/tests/test-projects/multi-target-reload/multi-target-reload.sln
- main/tests/test-projects/multi-target-reload/netstandard.csproj
Editing an SDK project that targeted a single target framework so it
targets multiple target frameworks would result in the intellisense
not being updated from that point when the project changed, such as
when a new file was added.
The problem was that the Project.Modified event handler was removed
for the project when the old project was removed since the Roslyn
project id to project mapping had already been updated during the
reload to point to the new project. To avoid this a check is made to
ensure that no other project ids exist in the mapping before the
event handler is removed.
Fixes VSTS #1035311 - Wrong version of multi target project referenced
in .net framework project
Also fixed a null reference for new project added to existing solution. Adding a new project to an existing …
> [Ide] Fix intellisense not updated after adding target frameworks

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Gui/ManagePackagesDialogRunner.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.csproj
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/MonoDevelopPluginFactory.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageManagementCredentialService.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/PackageManagementServices.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/RepositoryProviderFactoryExtensions.cs
- main/src/addins/MonoDevelop.PackageManagement/NuGet.Credentials/CredentialService.cs
This will do a barebone registration of available, plugin-based credential providers (like the Azure DevOps one) without implementing any authentication flow. The idea is that users can pre-authenticate via another mean (manual MSBuild invocation or NuGet binary) and the IDE will, at least, be able to retrieve those cached credentials.
Fixes VSTS #632121 - NuGet credential providers
Still some odd behaviour here. If you open the Manage Packages dialog whilst check for updates is running it seems that you get the dialog asking for credentials. It seems that the request is being treated as a retry so the NuGet credential provider removes it from the session token cache, if that is being used.
> [NuGet] Register credential providers coming from secure plugins

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/CommandSearchCategory.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/FileSearchCategory.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/RoslynSearchCategory.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.MainToolbar/SearchInSolutionSearchCategory.cs
The `Contains` extension comes in from a separate library, not sure about the implementation. Use Array.IndexOf
Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1044378
> Simplify SearchCategory tags

- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git.Tests/BaseGitRepositoryTests.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/Commands.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitConfigurationDialog.cs
- main/src/addins/VersionControl/MonoDevelop.VersionControl.Git/MonoDevelop.VersionControl.Git/GitRepository.cs
MonoDevelop.VersionControl.Git.dll!MonoDevelop.VersionControl.Git.TaskFailureExtensions::RunWaitAndCapture+0
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1027415
Hard to reproduce the issue (only 4 Hits). The GitConfigurationDialog
does some long running operations where the cancellation token isn't
passed to these. That got fixed.
But the main issue is the Dispose that could dead lock on the
GitRepository. Since destroy is done on the dedicated operation thread
it may dead lock in some situations.
That can only happen if something long running blocks the
DedicatedOperationFactory. Now the DedicatedOperationFactory
operations get linked to the disposeToken which should cancel these
operations.
But all actions need to get the combined token and use that for their
cancellations.
> Fixes VSTS Bug 1027415: [FATAL] SigTerm signal in MonoDevelop.VersionControl.Git.dll!MonoDevelop.VersionControl.Git.GitRepository::Dispose+49

- main/src/addins/MacPlatform/KernelInterop.cs
It seems that the API requires the count in natural_t units, not in bytes. Fixing this, fixes the crasher in Catalina
the reason it crashes in Catalina is that in Catalina task_info tries to write more data to the output struct (for Mojave the size of the struct and the maximum size written by Mojave was the same, so it didn't matter that the size argument was too big, because Mojave would never write more than the size of the buffer anyway)
Thanks to @rolfbjarne for the investigative work
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1008370
Backport of #9214.
> [release-8.4] [Mac] Fix binding for task_info

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement/LicenseAcceptanceService.cs
Added a feature switch to allow the license acceptance dialog
to be disabled. This can be done by setting the environment
variable:
MD_FEATURES_DISABLED=NuGetLicenseAcceptanceDialog
By default the license acceptance dialog will be displayed. The
feature switch can be used by automation tests to disable the
dialog and the license acceptance for the NuGet package will
occur without the user being prompted.
Fixes VSTS #1036006 - Disable license acceptance dialog with
feature switch
> [NuGet] Allow license acceptance dialog to be disabled

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ImageService.cs
* sort resources by name, to ensure same sequence for all icons
* use a global static dictionary for loaded resources
* filter by requested name to avoid Xwt.Image parser scanning all resources over and over again
> [Ide] Improve ImageService.CustomImageLoader

- main/src/addins/MacPlatform/MacPlatform.cs
The AppDelegate always knows what the start up reason was, so check it there as
a final check if we missed the startup notification
Fixes VSTS #984249
> [Mac] Improve startup reason detection

- main/src/addins/MacPlatform/MacPlatform.cs
The AppDelegate always knows what the start up reason was, so check it there as
a final check if we missed the startup notification
Fixes VSTS #984249
Backport of #9526.
> [release-8.4] [Mac] Improve startup reason detection

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/ScaffolderTemplateConfigurePage.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1049876
Things that are done in this PR:
* Added Accessible.Title property for input controls
This fixes VoiceOver accessibility announcements made on text fields, combo boxes and file selectors on ASP.NET Core Scaffolding dialogs (see screenshot attached).
Backport of #9559.
/cc @rodrmoya @Semptra
> [release-8.4] [1049876] [Scaffolding] Added Accessible.Title property for input controls

- main/src/addins/MonoDevelop.AspNetCore/MonoDevelop.AspNetCore.Scaffolding/ScaffolderTemplateConfigurePage.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1049876
Things that are done in this PR:
* Added Accessible.Title property for input controls
This fixes VoiceOver accessibility announcements made on text fields, combo boxes and file selectors on ASP.NET Core Scaffolding dialogs (see screenshot attached).
> [1049876] [Scaffolding] Added Accessible.Title property for input controls

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Gui/ManagePackagesDialog.UI.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Gui/ManagePackagesDialog.cs
A regular label does not allow focus unless it's selectable or a link
and there is no simple workaround for that.
Fixes VSTS #1021581
Backport of #9555.
/cc @sevoku
> [release-8.4] [NuGet] Use a custom label to allow tab focus in package management

- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Gui/ManagePackagesDialog.UI.cs
- main/src/addins/MonoDevelop.PackageManagement/MonoDevelop.PackageManagement.Gui/ManagePackagesDialog.cs
A regular label does not allow focus unless it's selectable or a link
and there is no simple workaround for that.
Fixes VSTS #1021581
> [NuGet] Use a custom label to allow tab focus in package management

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Dialogs/VersionInformationTabPage.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1032534
This button should now be localized
> [1032534] [About VS for Mac] Add localization to "Show loaded assemblies" string

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/GtkNewProjectDialogBackend.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1019742
Another possible fix could be moving `dialog.CloseDialog ()` (https://github.com/mono/monodevelop/blob/master/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Projects/NewProjectController.cs#L683) at the beginning of `Create` method.
Here is how this dialog looks like after clicking on "Create" button:
> [1019742] Disable VBox controls before project creation

- main/src/addins/AspNet/Properties/AddinInfo.cs
- main/src/addins/AspNet/Properties/MonoDevelop.AspNet.addin.xml
This switches the aspx file editing to the old editor an and includes .aspx, .ashx, .asmx, .ascx, .master, .asax, ~.cshtml, .html, .htm~ extensions.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1049891
> VSTS 1049891:  aspx files no intellisense 

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/InformationPopoverWidget.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Wizard/WizardDialogController.cs
When the TooltipPopoverWindow is visible, the parent
might receive mouse in/out events rapidly, depending
on the parenting status of the parent dialogs. This might
be caused by some Gtk Loop issue.
Delaying the hiding of the popup when the mouse leaves
effectively workarounds the issue.
> Fix information popover flickering

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/IMonoDevelopHostDocument.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/MonoDevelopWorkspace.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.TypeSystem/TypeSystemService.cs
Right clicking in the text editor and selecting an item underneath
'Configure and Supress issues' would not add an .editorconfig file
or update the existing one.
The problem was that this feature requires changes in the type system
service.
Some odd behaviour with multiple projects in the solution, which looks like a Roslyn bug, where the editorconfig file is added as a link to a different project to the one the file being worked on belongs to.
Fixes VSTS #1001982 - Attempting to add analyzer configs fails silently
(to the user)
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1001982
Test cases linked to on above bug report.
> [Ide] Support adding/updating .editorconfig with Roslyn

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Pads.ProjectPad/ProjectFileNodeBuilder.cs
- After a file is deleted from Finder outside VS Mac, right click on the file in the IDE will show "Remove" instead of "Delete" and a dialog will confirm user's choice to remove the file and its child from the project. If any child exists, it will be removed (not deleted)
Discussion: Should we directly delete the child?
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1051207
> [IDE] Allow deleting missing files from project

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components.Commands/CommandManager.cs
This PR fixes the routing of CommandHadlers into a native widgets. Basically we were not getting the active window correctly in cases when a native widget was focused then the routing was failing, affecting to all the key shortcuts combinations.
In the current example shows how Copy shorcut now works on the native cocoa Watch panel
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/999606/
> Fixes CommandHandler routing in native widgets

- main/src/addins/MonoDevelop.Debugger.VSCodeDebugProtocol/MonoDevelop.Debugger.VsCodeDebugProtocol/VSCodeDebuggerSession.cs
For OnSetNextStatement(), convert exceptions into NotSupportedException
so that higher-level code properly handles this case.
For Stepping, just drop & log the exception like SoftDebuggerSession does.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1042237
> [Debugger] Added more logging for VsCodeDebugger protocol requests

- main/src/core/MonoDevelop.Ide/MonoDevelop.Components/InformationPopoverWidget.cs
- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Gui.Wizard/WizardDialogController.cs
When the TooltipPopoverWindow is visible, the parent
might receive mouse in/out events rapidly, depending
on the parenting status of the parent dialogs. This might
be caused by some Gtk Loop issue.
Delaying the hiding of the popup when the mouse leaves
effectively workarounds the issue.
Backport of #9576.
/cc @sevoku
> [release-8.4] Fix information popover flickering

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeView.cs
Based on "Find References" on GetRawValue(), it seems that this can
sometimes return RawValueString instead of string. Make sure that
we handle this instead of assuming the value returned by GetRawValue()
is always a string.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1054038/
> [Debugger] Fix InvalidCastException in MacObjectValueTreeView.OnCopy()

- main/src/addins/MonoDevelop.Debugger.VSCodeDebugProtocol/MonoDevelop.Debugger.VsCodeDebugProtocol/VSCodeDebuggerSession.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1051257/
Fixes VSTS #1051257
(The exceptionCaughtDialog's position is a bit weird, filing another bug to record it)
> [Debugger] Update exception options to include unhandled exception

- main/src/core/MonoDevelop.Ide/MonoDevelop.Ide/ImageService.cs
to avoid adding duplicate EmbeddedResource entries to project files.
Background:
To support loading the correct icons in selected state with dark theme and high contrast mode, we'd need to add duplicate resources entries to all csproj file like this:
```diff
<EmbeddedResource Include="icons\project-32~dark~sel.png" />
+    <EmbeddedResource Include="icons\project-32~dark~sel.png" >
+      <LogicalName>project-32~contrast~dark~sel.png</LogicalName>
+    </EmbeddedResource>
<EmbeddedResource Include="icons\project-32~dark~sel%402x.png" />
+    <EmbeddedResource Include="icons\project-32~dark~sel%402x.png" >
+      <LogicalName>project-32~contrast~dark~sel@2x.png</LogicalName>
+    </EmbeddedResource>
```
this could be automated, but would be hard to maintain afterwards (it's already quite …
> [Ide] Dynamically add ~contrast~dark~sel resource mappings

- main/src/addins/MonoDevelop.Debugger/MonoDevelop.Debugger/ObjectValue/Mac/MacObjectValueTreeView.cs
Based on "Find References" on GetRawValue(), it seems that this can
sometimes return RawValueString instead of string. Make sure that
we handle this instead of assuming the value returned by GetRawValue()
is always a string.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1054038/
Backport of #9584.
/cc @jstedfast
> [release-8.4] [Debugger] Fix InvalidCastException in MacObjectValueTreeView.OnCopy()

- main/src/addins/AspNet/Properties/AddinInfo.cs
- main/src/addins/AspNet/Properties/MonoDevelop.AspNet.addin.xml
This switches the aspx file editing to the old editor an and includes .aspx, .ashx, .asmx, .ascx, .master, .asax, ~.cshtml, .html, .htm~ extensions.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1049891
Backport of #9566.
/cc @mrward @avodovnik
> [release-8.4] VSTS 1049891:  aspx files no intellisense 
